' Gambas module file

Public $APIMonth As String

Public Function GetDHISJson(xFixVar As Variant[], xTableVar As Variant[]) As Variant[]

  Dim xVar As Variant[]
  Dim aColl As Collection

  Dim xFixArry As String[]
  Dim xLabel As String
  Dim xColm As String

  Dim rowColl As Collection
  Dim xval As Variant

  xVar = New Variant[]

  For Each xFixArry In xFixVar
    xLabel = xFixArry[0]
    xColm = xFixArry[1]
    For Each rowColl In xTableVar
      If rowColl["0"] = xLabel Then
        xval = rowColl[xColm]

        If xFixArry[3] And If xFixArry[2] Then
          aColl = New Collection
          aColl.Add(xLabel & "-" & xColm, "_comment")
          aColl.Add(xFixArry[3], "categoryOptionCombo")
          aColl.Add(xFixArry[2], "dataElement")
          aColl.Add(CStr(xval), "value")
          xVar.Add(aColl)
        Endif

      Endif
    Next
  Next

  Return xVar

End

''for IP morbidity and mortality
Public Function GetDHISJsonDiagno(xFixVar As Variant[], xTableVar As Variant[]) As Variant[]

  Dim xVar As Variant[]
  Dim aColl As Collection

  Dim xFixArry As String[]
  Dim xLabel As String
  Dim xColm As String

  Dim rowColl As Collection
  Dim xval As Variant

  xVar = New Variant[]

  For Each xFixArry In xFixVar
    xLabel = xFixArry[0]
    xColm = xFixArry[1]
    For Each rowColl In xTableVar
      xval = rowColl[xColm]

      If xFixArry[3] And If xFixArry[2] Then
        aColl = New Collection
        aColl.Add(xLabel & "-" & xColm, "_comment")
        aColl.Add(xFixArry[3], "categoryOptionCombo")
        aColl.Add(xFixArry[2], "dataElement")
        aColl.Add(CStr(xval), "value")
        xVar.Add(aColl)
      Endif

    Next
  Next

  Return xVar

End

''only for safe motherhood complications
Public Function GetDHISJsonSecond(xFixVar As Variant[], xTableVar As Variant[]) As Variant[]

  Dim xVar As Variant[]
  Dim aColl As Collection

  Dim xFixArry As String[]
  Dim xLabel As String
  Dim xColm As String

  Dim rowColl As Collection
  Dim xval As Variant

  xVar = New Variant[]

  For Each xFixArry In xFixVar
    xLabel = xFixArry[0]
    xColm = xFixArry[1]
    For Each rowColl In xTableVar
      If rowColl["1"] = xLabel Then
        xval = rowColl[xColm]

        If xFixArry[3] And If xFixArry[2] Then
          aColl = New Collection
          aColl.Add(xLabel & "-" & xColm, "_comment")
          aColl.Add(xFixArry[3], "categoryOptionCombo")
          aColl.Add(xFixArry[2], "dataElement")
          aColl.Add(CStr(xval), "value")
          xVar.Add(aColl)
        Endif

      Endif
    Next
  Next

  Return xVar

End

''======================== DHIS TAGS ==========================
''dataelement,optioncombo
Public Function SetTableCellTags(sChapter As String, Optional sCategory As String) As Variant[]

  Dim aVar As Variant[]
  Dim xArr As String[]

  aVar = New Variant[]

  If sChapter = "Hospital Summary Dataset" Then
    If sCategory = "Hospital Services" Then
      xArr = ["0-9 years", "1", "HscG3R78Jzc", "I1gylzOskBs"]
      aVar.Add(xArr)
      xArr = ["0-9 years", "2", "HscG3R78Jzc", "TTNFd2X49S6"]
      aVar.Add(xArr)
      xArr = ["0-9 years", "3", "XjuXeaVPUsr", "I1gylzOskBs"]
      aVar.Add(xArr)
      xArr = ["0-9 years", "4", "XjuXeaVPUsr", "TTNFd2X49S6"]
      aVar.Add(xArr)

      xArr = ["10-14 years", "1", "HscG3R78Jzc", "ciTvZ1HjQTw"]
      aVar.Add(xArr)
      xArr = ["10-14 years", "2", "HscG3R78Jzc", "SDgsEKTs0IH"]
      aVar.Add(xArr)
      xArr = ["10-14 years", "3", "XjuXeaVPUsr", "ciTvZ1HjQTw"]
      aVar.Add(xArr)
      xArr = ["10-14 years", "4", "XjuXeaVPUsr", "SDgsEKTs0IH"]
      aVar.Add(xArr)

      xArr = ["15-19 years", "1", "HscG3R78Jzc", "RnH2ZpATWSI"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "2", "HscG3R78Jzc", "ffNSZ7u5Y5P"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "3", "XjuXeaVPUsr", "RnH2ZpATWSI"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "4", "XjuXeaVPUsr", "ffNSZ7u5Y5P"]
      aVar.Add(xArr)

      xArr = ["20-59 years", "1", "HscG3R78Jzc", "sfmUgn8yywu"]
      aVar.Add(xArr)
      xArr = ["20-59 years", "2", "HscG3R78Jzc", "iUcXHCikw4W"]
      aVar.Add(xArr)
      xArr = ["20-59 years", "3", "XjuXeaVPUsr", "sfmUgn8yywu"]
      aVar.Add(xArr)
      xArr = ["20-59 years", "4", "XjuXeaVPUsr", "iUcXHCikw4W"]
      aVar.Add(xArr)

      xArr = ["60-69 years", "1", "HscG3R78Jzc", "COAFy42YNLg"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "2", "HscG3R78Jzc", "D7tJYC2XYrC"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "3", "XjuXeaVPUsr", "COAFy42YNLg"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "4", "XjuXeaVPUsr", "D7tJYC2XYrC"]
      aVar.Add(xArr)

      xArr = [">=70 years", "1", "HscG3R78Jzc", "M0yrPwi8vEK"]
      aVar.Add(xArr)
      xArr = [">=70 years", "2", "HscG3R78Jzc", "DYUdGTQhgf9"]
      aVar.Add(xArr)
      xArr = [">=70 years", "3", "XjuXeaVPUsr", "M0yrPwi8vEK"]
      aVar.Add(xArr)
      xArr = [">=70 years", "4", "XjuXeaVPUsr", "DYUdGTQhgf9"]
      aVar.Add(xArr)

    Else If sCategory = "Emergency Services" Then
      xArr = ["0-9 years", "1", "fuHbV1eiKs0", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["0-9 years", "2", "fuHbV1eiKs0", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["10-14 years", "1", "qQ8UCWW6YUs", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["10-14 years", "2", "qQ8UCWW6YUs", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["15-19 years", "1", "SbdW0pjvph3", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "2", "SbdW0pjvph3", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["20-59 years", "1", "CLYbMAU5lhD", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-59 years", "2", "CLYbMAU5lhD", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["60-69 years", "1", "GaDfMW8NKGd", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "2", "GaDfMW8NKGd", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = [">=70 years", "1", "jXzZ2AFEqgP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">=70 years", "2", "jXzZ2AFEqgP", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Diagnostic/Other Services" Then
      xArr = ["X-ray", "2", "RXIa0TIoAP4", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Ultrasonogram (USG)", "2", "Hy2ikWKzAUh", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Echocardiogram (Echo)", "2", "gglzlE7oJpI", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Electro Encephalo Gram (EEG)", "2", "yVhL13Rc3Gw", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Electrocardiogram (ECG)", "2", "HXPj1cIqZIC", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Trademill", "2", "aBbZ4GirNpN", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Computed Tomographic (CT) Scan", "2", "zQnc9f0Gq8Z", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Magnetic Resonance Imaging (MRI)", "2", "gT5hXh5IQ8Y", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Endoscopy", "2", "rU9EUoLmd1K", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Colonoscopy", "2", "CUrV07L8274", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Bronchoscopy", "2", "Ly477FanXE3", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Nuclear Medicine", "2", "d7xsrk6ZliX", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Mammogram", "2", "vigLadIlROn", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Cystoscopy", "2", "ztdpCtP5eOM", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["DEXA Scan", "2", "F8mMHpJm9cd", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["DTPA Scan", "2", "TbGgV5AODKc", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Electroconvulsive Therapy (ECT)", "2", "ctyxkCUBEbX", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Transcranial Magnetic Simulation (TMS)", "2", "ScWyls97aqY", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Free Service for Impoverished Citizen" Then
      xArr = ["Heart Disease", "1", "hcc1X0ZUcwu", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Heart Disease", "2", "hcc1X0ZUcwu", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["Kidney Disease", "1", "vAedweDY9Ov", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Kidney Disease", "2", "vAedweDY9Ov", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["Cancer", "1", "sMadF784Ipm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Cancer", "2", "sMadF784Ipm", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["Head Injuries", "1", "mepsRa1P7TF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Head Injuries", "2", "mepsRa1P7TF", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["Spinal Injuries", "1", "NwwONXCMqqS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Spinal Injuries", "2", "NwwONXCMqqS", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["Alzheimers Disease", "1", "wrUj1hRMeRR", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Alzheimers Disease", "2", "wrUj1hRMeRR", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["Parkinsons Disease", "1", "lZRVWKdFWUz", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Parkinsons Disease", "2", "lZRVWKdFWUz", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["Sickle Cell Anaemia", "1", "P75PjLQQwYx", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Sickle Cell Anaemia", "2", "P75PjLQQwYx", "PflKpozpO7b"]
      aVar.Add(xArr)

    Endif

  Else If sChapter = "Hospital Indoor Service" Then
    If sCategory = "Inpatient Outcome" Then
      xArr = ["0-7 days", "1", "niC6UlH8lG8", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["0-7 days", "2", "niC6UlH8lG8", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["0-7 days", "3", "ZchNDuXAuns", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["0-7 days", "4", "ZchNDuXAuns", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["0-7 days", "5", "mNpQUrhMY2M", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["0-7 days", "6", "mNpQUrhMY2M", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["0-7 days", "7", "PjX59M4FWsV", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["0-7 days", "8", "PjX59M4FWsV", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["0-7 days", "9", "Fqk8Q7IyFGm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["0-7 days", "10", "Fqk8Q7IyFGm", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["0-7 days", "11", "uOpuphGuSnO", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["0-7 days", "12", "uOpuphGuSnO", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["0-7 days", "13", "WQRxFdjHUwu", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["0-7 days", "14", "WQRxFdjHUwu", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["8-28 days", "1", "aw0UrONFp8G", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["8-28 days", "2", "aw0UrONFp8G", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["8-28 days", "3", "JZxN7maZNTP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["8-28 days", "4", "JZxN7maZNTP", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["8-28 days", "5", "FSJ68ws5R8q", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["8-28 days", "6", "FSJ68ws5R8q", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["8-28 days", "7", "tJPTannLCpR", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["8-28 days", "8", "tJPTannLCpR", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["8-28 days", "9", "lTMICysCO1L", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["8-28 days", "10", "lTMICysCO1L", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["8-28 days", "11", "TY2g2JJ60se", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["8-28 days", "12", "TY2g2JJ60se", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["8-28 days", "13", "aebRNbazF1u", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["8-28 days", "14", "aebRNbazF1u", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["29 days-1 year", "1", "VT7pxUmkCk4", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "2", "VT7pxUmkCk4", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "3", "FBGTznlhG52", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "4", "FBGTznlhG52", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "5", "MG81K0P93cC", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "6", "MG81K0P93cC", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "7", "nAwr1SuDL5X", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "8", "nAwr1SuDL5X", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "9", "q1hEowbwEte", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "10", "q1hEowbwEte", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "11", "I9luOd2a7XZ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "12", "I9luOd2a7XZ", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "13", "u5Ju7K3EFZ3", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "14", "u5Ju7K3EFZ3", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["1-4 years", "1", "hfKKGFpcahT", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "2", "hfKKGFpcahT", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "3", "SY9yhXNOxKV", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "4", "SY9yhXNOxKV", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "5", "BHMcr2LttVZ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "6", "BHMcr2LttVZ", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "7", "uHC49o0YWzj", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "8", "uHC49o0YWzj", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "9", "R9VsHuLaaOV", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "10", "R9VsHuLaaOV", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "11", "y9WZpRQwfwP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "12", "y9WZpRQwfwP", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "13", "W1Tfa8N3tEq", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "14", "W1Tfa8N3tEq", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["5-14 years", "1", "idfm34Azg6Q", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "2", "idfm34Azg6Q", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "3", "SrXLG8LgypM", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "4", "SrXLG8LgypM", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "5", "q1rh08vhNLa", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "6", "q1rh08vhNLa", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "7", "aFDqE1qyJwH", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "8", "aFDqE1qyJwH", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "9", "i80uwDMocMV", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "10", "i80uwDMocMV", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "11", "RZxcXR28SV3", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "12", "RZxcXR28SV3", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "13", "YTzkpp1RDGx", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "14", "YTzkpp1RDGx", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["15-19 years", "1", "jeODCTX57ty", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "2", "jeODCTX57ty", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "3", "QnPXOhBy2L0", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "4", "QnPXOhBy2L0", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "5", "FVUaOSyrp8X", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "6", "FVUaOSyrp8X", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "7", "HnwIe5GtEQd", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "8", "HnwIe5GtEQd", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "9", "PZP5PrfHPeK", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "10", "PZP5PrfHPeK", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "11", "J3B6Aqs64TL", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "12", "J3B6Aqs64TL", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "13", "NuvEJyyrRyn", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "14", "NuvEJyyrRyn", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["20-29 years", "1", "eWZ03zEBkBX", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "2", "eWZ03zEBkBX", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "3", "fGGxZFck8rJ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "4", "fGGxZFck8rJ", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "5", "qC0mnCelPuB", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "6", "qC0mnCelPuB", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "7", "oQDF5rAiZ9s", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "8", "oQDF5rAiZ9s", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "9", "OC96VpJIdoE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "10", "OC96VpJIdoE", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "11", "EHz6GfxpuXw", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "12", "EHz6GfxpuXw", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "13", "qNch4vXPvMS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "14", "qNch4vXPvMS", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["30-39 years", "1", "byiU4Z8VZxP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "2", "byiU4Z8VZxP", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "3", "BCTQqvSi9Fp", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "4", "BCTQqvSi9Fp", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "5", "xRGqy7Adibr", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "6", "xRGqy7Adibr", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "7", "Nifo5ju2pPP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "8", "Nifo5ju2pPP", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "9", "xOBWxJ7rtOG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "10", "xOBWxJ7rtOG", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "11", "r5ovXqoUemk", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "12", "r5ovXqoUemk", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "13", "UAbEC9wm8JC", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "14", "UAbEC9wm8JC", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["40-49 years", "1", "qFKmdcMXi8R", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "2", "qFKmdcMXi8R", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "3", "SYsn3Q7bpEM", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "4", "SYsn3Q7bpEM", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "5", "jSCf0lQ0CKP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "6", "jSCf0lQ0CKP", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "7", "MzCbP9IShpH", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "8", "MzCbP9IShpH", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "9", "GwmblUqSoMS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "10", "GwmblUqSoMS", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "11", "VDDHvT1MISE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "12", "VDDHvT1MISE", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "13", "EDHAawGus2l", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "14", "EDHAawGus2l", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["50-59 years", "1", "XgqSseUwYwV", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "2", "XgqSseUwYwV", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "3", "QZzqdCD5pWM", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "4", "QZzqdCD5pWM", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "5", "O3Z3alM218T", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "6", "O3Z3alM218T", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "7", "IgUWH05VOXS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "8", "IgUWH05VOXS", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "9", "rvi6BdbtIu1", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "10", "rvi6BdbtIu1", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "11", "rjN2W3sO17N", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "12", "rjN2W3sO17N", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "13", "q9HWBr7XI3j", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "14", "q9HWBr7XI3j", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["60-69 years", "1", "x6AnbSOW91m", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "2", "x6AnbSOW91m", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "3", "kfKZhz8cxld", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "4", "kfKZhz8cxld", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "5", "X8zqZMPNOgz", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "6", "X8zqZMPNOgz", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "7", "O55ilAmKVCL", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "8", "O55ilAmKVCL", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "9", "cWW5H0a30nH", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "10", "cWW5H0a30nH", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "11", "rVq4pfFzR1Y", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "12", "rVq4pfFzR1Y", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "13", "ADTvSS6ZkWi", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["60-69 years", "14", "ADTvSS6ZkWi", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = [">= 70 years", "1", "ExK3mV0mW4C", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">= 70 years", "2", "ExK3mV0mW4C", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = [">= 70 years", "3", "Z4zwE88awmI", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">= 70 years", "4", "Z4zwE88awmI", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = [">= 70 years", "5", "mJtKzHyyCAW", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">= 70 years", "6", "mJtKzHyyCAW", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = [">= 70 years", "7", "lGlrmWuQ6BN", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">= 70 years", "8", "lGlrmWuQ6BN", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = [">= 70 years", "9", "QMtXxyDBkoy", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">= 70 years", "10", "QMtXxyDBkoy", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = [">= 70 years", "11", "K7ysJSxXsmE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">= 70 years", "12", "K7ysJSxXsmE", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = [">= 70 years", "13", "UBWw7aps69k", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">= 70 years", "14", "UBWw7aps69k", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Neonate Form" Then
      xArr = ["Primi(G=1)", "1", "Iyu2jI3uZLe", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Primi(G=1)", "2", "XfaiH4LO4HU", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Primi(G=1)", "3", "J16O3bLT94B", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Primi(G=1)", "4", "Wz9lyL4EFgc", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Multi(G=1-4)", "1", "OQ4CxYP11zR", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Multi(G=1-4)", "2", "kK32tZ49ToM", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Multi(G=1-4)", "3", "Wz6fi5h43ln", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Multi(G=1-4)", "4", "f95dTxsNaOr", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Grand Multi(G>=5)", "1", "ErsRqXBszJe", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Grand Multi(G>=5)", "2", "GU5n3qxVV1G", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Grand Multi(G>=5)", "3", "FeOTYqWEND5", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Grand Multi(G>=5)", "4", "fgGIHbLGHr3", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Maternal Age" Then
      xArr = ["<20 Yrs", "1", "LLtybn3Il5y", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["<20 Yrs", "2", "a7MLCIvl3N0", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["<20 Yrs", "3", "i4LqEvJTyyH", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["<20 Yrs", "4", "NmLTLB5IM4x", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["20-34 Yrs", "1", "Ynoi7oT6Cui", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["20-34 Yrs", "2", "jW4Nxz5ZtTc", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["20-34 Yrs", "3", "T2RIoCzbcrE", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["20-34 Yrs", "4", "NNa4syq83FQ", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = [">=35 Yrs", "1", "DmCnfwpVcMT", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = [">=35 Yrs", "2", "yoj2oCbvriM", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = [">=35 Yrs", "3", "bbMBbR3oQa5", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = [">=35 Yrs", "4", "KWtpxg9gMS0", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Medico-Legal Cases" Then

    Else If sCategory = "Type of Surgeries" Then
      xArr = ["Major:Emergency", "1", "CLhWwTR9cvm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Major:Emergency", "2", "CLhWwTR9cvm", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Major:Emergency", "3", "LkfqkCTEMqY", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Major:Inpatients", "1", "npj4tlqKsRw", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Major:Inpatients", "2", "npj4tlqKsRw", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Major:Inpatients", "3", "DD8l8cg0zzD", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Intermediate:Emergency", "1", "cYSIelGCG3M", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Intermediate:Emergency", "2", "cYSIelGCG3M", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Intermediate:Emergency", "3", "myd5N04yqWS", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Intermediate:Inpatients", "1", "jiDCdaL2uK8", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Intermediate:Inpatients", "2", "jiDCdaL2uK8", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Intermediate:Inpatients", "3", "OCHPfRV20lM", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Minor:Outpatients", "1", "XOIIA9PktoG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Minor:Outpatients", "2", "XOIIA9PktoG", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Minor:Outpatients", "3", "f9CFvnVSAic", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Minor:Inpatients", "1", "ds89kwFirfa", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Minor:Inpatients", "2", "ds89kwFirfa", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Minor:Inpatients", "3", "yNvksqFvO65", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Minor:Emergency", "1", "PPLkh56gSDt", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Minor:Emergency", "2", "PPLkh56gSDt", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Minor:Emergency", "3", "gGNm8ee9hl8", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Plaster", "1", "bRyy4uqVUn6", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Plaster", "2", "bRyy4uqVUn6", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Death Information" Then
      xArr = ["Early Neonatal(0-6 days)", "1", "wE8Ua9fF57W", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Early Neonatal(0-6 days)", "2", "wE8Ua9fF57W", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["Late Neonatal(7-27 days)", "1", "i9Fd6Sg4Xvz", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Late Neonatal(7-27 days)", "2", "i9Fd6Sg4Xvz", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["Maternal (All)", "1", "OWZvJevMlQd", "ye1QuAMRG5Z"]
      aVar.Add(xArr)

      xArr = ["Post Operative", "1", "HUtoMj9IIHY", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Post Operative", "2", "HUtoMj9IIHY", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["Emergency", "1", "E71fixytlb4", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Emergency", "2", "E71fixytlb4", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["Inpatient", "1", "zyYi2g0sMwN", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Inpatient", "2", "zyYi2g0sMwN", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Free health service summary" Then
      xArr = ["Partially", "1", "XFaB9VkN3Sh", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Partially", "2", "eXUI9zdrFSY", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Completely", "1", "kpcheWPcaMi", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Completely", "2", "sT2uMMZvrSJ", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Social Security Programme" Then
      xArr = ["Outpatients", "1", "fMgY7buyPgJ", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Outpatients", "2", "TQchxgpT1Mg", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Outpatients", "3", "U0aYCzqSIrV", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Outpatients", "4", "pGKBCQ2y96V", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Outpatients", "5", "SIODC3GmBPx", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Outpatients", "6", "d5xARcg2y1L", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Outpatients", "7", "xD4PTWeBft4", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Inpatients", "1", "blQafu930Fk", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Inpatients", "2", "K2QvU18Cy9V", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Inpatients", "3", "oLHqNDw8P0e", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Inpatients", "4", "FpFz27OnLjo", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Inpatients", "5", "brA0o59G66l", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Inpatients", "6", "WYnBzcM4iwO", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Inpatients", "7", "JT6R8JDcdm7", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Emergency", "1", "sboNx8FiP4d", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Emergency", "2", "B9svAWSTFQt", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Emergency", "3", "xkfNycS7hEG", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Emergency", "4", "wYwdmBDhBNu", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Emergency", "5", "YLBxlWQ2Ji5", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Emergency", "6", "qLLnISVBthc", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Emergency", "7", "sSIsC8lbPDs", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Referred Out", "1", "yeGkme7Wda5", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Referred Out", "2", "zrx6bskmDpn", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Referred Out", "3", "NoJQulKOcgB", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Referred Out", "4", "riAMS7MJ8Kz", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Referred Out", "5", "pF1Mv020yUl", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Referred Out", "6", "GnYEgVNXJ0K", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Referred Out", "7", "r46z953ZAdI", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Endif

  Else If sChapter = "Inpatient Morbidity" Then
    xArr = ["0-7 days:Female", "2", "M6iIxQ7dWte", "fKrPh3mNwuA"]
    aVar.Add(xArr)
    xArr = ["0-7 days:Male", "3", "M6iIxQ7dWte", "AqOY5BvwChr"]
    aVar.Add(xArr)
    xArr = ["8-28 days:Female", "4", "M6iIxQ7dWte", "C1nelEDcfkS"]
    aVar.Add(xArr)
    xArr = ["8-28 days:Male", "5", "M6iIxQ7dWte", "YaaywTY9eKq"]
    aVar.Add(xArr)
    xArr = ["29 days-1 year:Female", "6", "M6iIxQ7dWte", "MQj7sk1V2Wd"]
    aVar.Add(xArr)
    xArr = ["29 days-1 year:Male", "7", "M6iIxQ7dWte", "QQt2JrzlZbo"]
    aVar.Add(xArr)
    xArr = ["1-4 years:Female", "8", "M6iIxQ7dWte", "mh3DYEYBSpg"]
    aVar.Add(xArr)
    xArr = ["1-4 years:Male", "9", "M6iIxQ7dWte", "EkuvSkGwGeG"]
    aVar.Add(xArr)
    xArr = ["5-14 years:Female", "10", "M6iIxQ7dWte", "ImeluxdRw47"]
    aVar.Add(xArr)
    xArr = ["5-14 years:Male", "11", "M6iIxQ7dWte", "YF8d9qgfLzR"]
    aVar.Add(xArr)
    xArr = ["15-19 years:Female", "12", "M6iIxQ7dWte", "lo7vNzsUiBe"]
    aVar.Add(xArr)
    xArr = ["15-19 years:Male", "13", "M6iIxQ7dWte", "dU1fetpED4w"]
    aVar.Add(xArr)
    xArr = ["20-29 years:Female", "14", "M6iIxQ7dWte", "miqFgXB82SV"]
    aVar.Add(xArr)
    xArr = ["20-29 years:Male", "15", "M6iIxQ7dWte", "m05Jven6ovZ"]
    aVar.Add(xArr)
    xArr = ["30-39 years:Female", "16", "M6iIxQ7dWte", "QOM5Xn9HRRF"]
    aVar.Add(xArr)
    xArr = ["30-39 years:Male", "17", "M6iIxQ7dWte", "lu1kdcpahOB"]
    aVar.Add(xArr)
    xArr = ["40-49 years:Female", "18", "M6iIxQ7dWte", "KpJMRZlgWu2"]
    aVar.Add(xArr)
    xArr = ["40-49 years:Male", "19", "M6iIxQ7dWte", "mpbNAZM7jRI"]
    aVar.Add(xArr)
    xArr = ["50-59 years:Female", "20", "M6iIxQ7dWte", "C9vCxjeox4h"]
    aVar.Add(xArr)
    xArr = ["50-59 years:Male", "21", "M6iIxQ7dWte", "XwK3g2awV0e"]
    aVar.Add(xArr)
    xArr = ["60-69 years:Female", "22", "M6iIxQ7dWte", "VDZFWJbjE7D"]
    aVar.Add(xArr)
    xArr = ["60-69 years:Male", "23", "M6iIxQ7dWte", "dhIPuVKMinp"]
    aVar.Add(xArr)
    xArr = [">= 70 years:Female", "24", "M6iIxQ7dWte", "N6V9yOzGjyc"]
    aVar.Add(xArr)
    xArr = [">= 70 years:Male", "25", "M6iIxQ7dWte", "PrnAj8Z0mrJ"]
    aVar.Add(xArr)

  Else If sChapter = "Hospital Mortality" Then
    xArr = ["0-7 days:Female", "2", "p64v9xIGIg0", "fKrPh3mNwuA"]
    aVar.Add(xArr)
    xArr = ["0-7 days:Male", "3", "p64v9xIGIg0", "AqOY5BvwChr"]
    aVar.Add(xArr)
    xArr = ["8-28 days:Female", "4", "p64v9xIGIg0", "C1nelEDcfkS"]
    aVar.Add(xArr)
    xArr = ["8-28 days:Male", "5", "p64v9xIGIg0", "YaaywTY9eKq"]
    aVar.Add(xArr)
    xArr = ["29 days-1 year:Female", "6", "p64v9xIGIg0", "MQj7sk1V2Wd"]
    aVar.Add(xArr)
    xArr = ["29 days-1 year:Male", "7", "p64v9xIGIg0", "QQt2JrzlZbo"]
    aVar.Add(xArr)
    xArr = ["1-4 years:Female", "8", "p64v9xIGIg0", "mh3DYEYBSpg"]
    aVar.Add(xArr)
    xArr = ["1-4 years:Male", "9", "p64v9xIGIg0", "EkuvSkGwGeG"]
    aVar.Add(xArr)
    xArr = ["5-14 years:Female", "10", "p64v9xIGIg0", "ImeluxdRw47"]
    aVar.Add(xArr)
    xArr = ["5-14 years:Male", "11", "p64v9xIGIg0", "YF8d9qgfLzR"]
    aVar.Add(xArr)
    xArr = ["15-19 years:Female", "12", "p64v9xIGIg0", "lo7vNzsUiBe"]
    aVar.Add(xArr)
    xArr = ["15-19 years:Male", "13", "p64v9xIGIg0", "dU1fetpED4w"]
    aVar.Add(xArr)
    xArr = ["20-29 years:Female", "14", "p64v9xIGIg0", "miqFgXB82SV"]
    aVar.Add(xArr)
    xArr = ["20-29 years:Male", "15", "p64v9xIGIg0", "m05Jven6ovZ"]
    aVar.Add(xArr)
    xArr = ["30-39 years:Female", "16", "p64v9xIGIg0", "QOM5Xn9HRRF"]
    aVar.Add(xArr)
    xArr = ["30-39 years:Male", "17", "p64v9xIGIg0", "lu1kdcpahOB"]
    aVar.Add(xArr)
    xArr = ["40-49 years:Female", "18", "p64v9xIGIg0", "KpJMRZlgWu2"]
    aVar.Add(xArr)
    xArr = ["40-49 years:Male", "19", "p64v9xIGIg0", "mpbNAZM7jRI"]
    aVar.Add(xArr)
    xArr = ["50-59 years:Female", "20", "p64v9xIGIg0", "C9vCxjeox4h"]
    aVar.Add(xArr)
    xArr = ["50-59 years:Male", "21", "p64v9xIGIg0", "XwK3g2awV0e"]
    aVar.Add(xArr)
    xArr = ["60-69 years:Female", "22", "p64v9xIGIg0", "VDZFWJbjE7D"]
    aVar.Add(xArr)
    xArr = ["60-69 years:Male", "23", "p64v9xIGIg0", "dhIPuVKMinp"]
    aVar.Add(xArr)
    xArr = [">= 70 years:Female", "24", "p64v9xIGIg0", "N6V9yOzGjyc"]
    aVar.Add(xArr)
    xArr = [">= 70 years:Male", "25", "p64v9xIGIg0", "PrnAj8Z0mrJ"]
    aVar.Add(xArr)

  Else If sChapter = "Maternal And New-born Health" Then
    If sCategory = "ANC Services" Then
      xArr = ["First (Anytime)", "1", "C6ubEqEew8X", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["First (Anytime)", "2", "kSnqP4GPOsQ", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Upto 12 weeks", "1", "vTDKlAOKGjn", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Upto 12 weeks", "2", "ZcrvEPX6AgY", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Four times", "1", "RtidqFs7NRc", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Four times", "2", "gNcAqChA90J", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Eight times", "1", "hGW7Z3Y7xzA", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Eight times", "2", "pvTVo0fTEW1", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Delivery Service" Then
      xArr = ["SBA trained ANM", "1", "T9SHzXzpwnJ", "o6KMyyni9Vl"]
      aVar.Add(xArr)
      xArr = ["SBA trained ANM", "2", "T9SHzXzpwnJ", "UGR7o8AHNH2"]
      aVar.Add(xArr)

      xArr = ["Skilled Health Professional", "1", "nRDFRYBCiuz", "o6KMyyni9Vl"]
      aVar.Add(xArr)
      xArr = ["Skilled Health Professional", "2", "nRDFRYBCiuz", "UGR7o8AHNH2"]
      aVar.Add(xArr)

      xArr = ["Other Health Professional", "1", "NPzEfDEIBBl", "o6KMyyni9Vl"]
      aVar.Add(xArr)
      xArr = ["Other Health Professional", "2", "NPzEfDEIBBl", "UGR7o8AHNH2"]
      aVar.Add(xArr)

      xArr = ["Home Attendant", "1", "pgmxB8n1Vv7", "o6KMyyni9Vl"]
      aVar.Add(xArr)
      xArr = ["Home Attendant", "2", "pgmxB8n1Vv7", "UGR7o8AHNH2"]
      aVar.Add(xArr)

    Else If sCategory = "Delivery Type" Then
      xArr = ["Spontaneous", "1", "VdZyJrLrSg5", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Spontaneous", "2", "rqny3AJuymt", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Spontaneous", "3", "c6dLz049UWw", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Vacuum/Forcep", "1", "CtX7O3pbtL3", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Surgery", "1", "BoPXsSKiPVx", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Surgery", "2", "xAulrqfseew", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Surgery", "3", "zgNUMf4qP2Z", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Delivery Outcome" Then
      xArr = ["Total Mothers", "1", "UQTYGjWr7wz", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Total Mothers", "2", "cMo5gmSt1yV", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Total Mothers", "3", "pP3HfFu4Bte", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Live Baby(Female)", "1", "Yjwho2iruhu", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Live Baby(Female)", "2", "w0fvdvU1yuF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Live Baby(Female)", "3", "ZtwhYCiEQ7w", "ye1QuAMRG5Z"]
      aVar.Add(xArr)

      xArr = ["Live Baby(Male)", "1", "Yjwho2iruhu", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Live Baby(Male)", "2", "w0fvdvU1yuF", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Live Baby(Male)", "3", "ZtwhYCiEQ7w", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Stillbirth" Then
      xArr = ["Fresh Still Birth", "1", "k2StfxOzXpx", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Macerated Still Birth", "1", "FlyYBxnmKup", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Incentive" Then
      xArr = ["Transport Incentive", "1", "dZo1PDWPAO1", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Transport Incentive", "2", "ysTJteUVzO1", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["ANC Incentive", "1", "MO4VQOLebuG", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["ANC Incentive", "2", "ua0pnAingEU", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Obstetric Complications" Then
      '"Ectopic pregnancy;JA01"
      xArr = ["JA01", "2", "f4ueiBTKF1T", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA01", "3", "b1PTkXsRdX6", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA01", "4", "WWOFK8vAADY", "kdsirVNKdhm"]
      aVar.Add(xArr)

      '"Abortion complication;JA05"
      xArr = ["JA05", "2", "S4CFTXyEFVc", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA05", "3", "qkUkDDvmwS0", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA05", "4", "q8L2FAXjU4I", "kdsirVNKdhm"]
      aVar.Add(xArr)

      '"Pre-eclampsia;JA24"
      xArr = ["JA24", "2", "v3zKVR5wJt3", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA24", "3", "ohdTLUyqYXk", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA24", "4", "WEes0A6r9Dh", "kdsirVNKdhm"]
      aVar.Add(xArr)

      '"Eclampsia;JA25"
      xArr = ["JA25", "2", "PELChUNfW2C", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA25", "3", "H0VEoxGraGW", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA25", "4", "ItB5JYfclT1", "kdsirVNKdhm"]
      aVar.Add(xArr)

      '"Hyperemesis grivadarum;JA60.0"
      xArr = ["JA60.0", "2", "LIo3j809JrK", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA60.0", "3", "AudMtjCeYOv", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA60.0", "4", "TF2VKOKKdzZ", "kdsirVNKdhm"]
      aVar.Add(xArr)

      '"Antepartum haemorrhage;JA41"
      xArr = ["JA41", "2", "ueBJTsv0PXr", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA41", "3", "WaovoeTaaaw", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA41", "4", "BKM6OWQmRku", "kdsirVNKdhm"]
      aVar.Add(xArr)

      '"Prolonged labour;JB03"
      xArr = ["JB03", "2", "wsncKYDcmqr", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JB03", "3", "dGAB4Mox8Sl", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JB03", "4", "yPybiey409s", "kdsirVNKdhm"]
      aVar.Add(xArr)

      '"Obstructed Labor;JB06"
      xArr = ["JB06", "2", "Dior21jcQCe", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JB06", "3", "G7IUvliObQp", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JB06", "4", "Gv1oyaeNKxv", "kdsirVNKdhm"]
      aVar.Add(xArr)

      '"Gestational Hypertension;JA23"
      xArr = ["JA23", "2", "VO1obyQWvjO", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA23", "3", "LnnazOkLzwa", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA23", "4", "uMem3pOk3TV", "kdsirVNKdhm"]
      aVar.Add(xArr)

      '"Ruptured uterus;JB0A.1"
      xArr = ["JB0A.1", "2", "nwQoDUhFR1z", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JB0A.1", "3", "ZJ663GTjG1x", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JB0A.1", "4", "PHry6X0GfZL", "kdsirVNKdhm"]
      aVar.Add(xArr)

      '"Postpartum haemorrhage;JA43"
      xArr = ["JA43", "2", "PGNd6jcxJX4", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA43", "3", "W3Stsxj1Lcb", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA43", "4", "nq5GBHIhiIt", "kdsirVNKdhm"]
      aVar.Add(xArr)

      '"Retained placenta;JA43.0"
      xArr = ["JA43.0", "2", "kV3JhKJWMR8", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA43.0", "3", "vCrWmEcmnhC", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JA43.0", "4", "vbi3VCU85Pe", "kdsirVNKdhm"]
      aVar.Add(xArr)

      '"Pueperal sepsis;JB40.0"
      xArr = ["JB40.0", "2", "dHet49ySm06", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JB40.0", "3", "tWRdOmeobnZ", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JB40.0", "4", "c3BpP1lVGNC", "kdsirVNKdhm"]
      aVar.Add(xArr)

      '"C-Section Wound Infection;JB40.1"
      xArr = ["JB40.1", "2", "FexcOBCpEz3", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JB40.1", "3", "FnXt15rpfca", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JB40.1", "4", "WimUNMADw5X", "kdsirVNKdhm"]
      aVar.Add(xArr)

      '"Other complications;JB0Y"
      xArr = ["JB0Y", "2", "XAzAbTRbJve", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JB0Y", "3", "qhRyGiA3XAN", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["JB0Y", "4", "AqCYkbLoysp", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Blood Transfusion" Then
      xArr = ["Transfusion done", "1", "byf1Rf6bEPt", "kRwzaFG6GPV"]
      aVar.Add(xArr)
      xArr = ["Transfusion done", "2", "byf1Rf6bEPt", "UxlNYkFakvE"]
      aVar.Add(xArr)
      xArr = ["Transfusion done", "3", "byf1Rf6bEPt", "DMyKvTLRZPc"]
      aVar.Add(xArr)

      xArr = ["Transfusion not done", "1", "PSSyeHAZVcx", "kRwzaFG6GPV"]
      aVar.Add(xArr)
      xArr = ["Transfusion not done", "2", "PSSyeHAZVcx", "UxlNYkFakvE"]
      aVar.Add(xArr)
      xArr = ["Transfusion not done", "3", "PSSyeHAZVcx", "DMyKvTLRZPc"]
      aVar.Add(xArr)

    Else If sCategory = "Birth Weight" Then
      xArr = ["Normal(>=2.5Kg)", "1", "uzX1NG6xDwr", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Normal(>=2.5Kg)", "2", "DjglomjSiAu", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Normal(>=2.5Kg)", "3", "vIuy5zKUj82", "tCy6R2UbkA1"]
      aVar.Add(xArr)
      xArr = ["Normal(>=2.5Kg)", "4", "vIuy5zKUj82", "XXgFel6hY5K"]
      aVar.Add(xArr)
      xArr = ["Normal(>=2.5Kg)", "5", "vIuy5zKUj82", "KiFbliu1f8r"]
      aVar.Add(xArr)
      xArr = ["Normal(>=2.5Kg)", "6", "GDJYMsnrkvy", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Low(1.5-2.5Kg)", "1", "r1x2daA3pwt", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Low(1.5-2.5Kg)", "2", "stOtnhrYX9J", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Low(1.5-2.5Kg)", "3", "ssjLchkxrC3", "tCy6R2UbkA1"]
      aVar.Add(xArr)
      xArr = ["Low(1.5-2.5Kg)", "4", "ssjLchkxrC3", "XXgFel6hY5K"]
      aVar.Add(xArr)
      xArr = ["Low(1.5-2.5Kg)", "5", "ssjLchkxrC3", "KiFbliu1f8r"]
      aVar.Add(xArr)
      xArr = ["Low(1.5-2.5Kg)", "6", "JCo1sEf9nZV", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Very Low(<1.5Kg)", "1", "uGteAfUfOBk", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Very Low(<1.5Kg)", "2", "DFEHOcOqW5a", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Very Low(<1.5Kg)", "3", "zaFinXSR0UY", "tCy6R2UbkA1"]
      aVar.Add(xArr)
      xArr = ["Very Low(<1.5Kg)", "4", "zaFinXSR0UY", "XXgFel6hY5K"]
      aVar.Add(xArr)
      xArr = ["Very Low(<1.5Kg)", "5", "zaFinXSR0UY", "KiFbliu1f8r"]
      aVar.Add(xArr)
      xArr = ["Very Low(<1.5Kg)", "6", "T83jtwxnALp", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "PNC Visit" Then
      xArr = ["First time", "1", "b8jGBrMfBbP", "kXFhKYzLFKT"]
      aVar.Add(xArr)
      xArr = ["First time", "2", "xXGoDPlPopJ", "kXFhKYzLFKT"]
      aVar.Add(xArr)
      xArr = ["First time", "3", "b8jGBrMfBbP", "VSSmCVmaTM5"]
      aVar.Add(xArr)
      xArr = ["First time", "4", "xXGoDPlPopJ", "VSSmCVmaTM5"]
      aVar.Add(xArr)

      xArr = ["Two times", "1", "ZMdVETMGwzz", "kXFhKYzLFKT"]
      aVar.Add(xArr)
      xArr = ["Two times", "2", "xGc4o4Oj3W8", "kXFhKYzLFKT"]
      aVar.Add(xArr)
      xArr = ["Two times", "3", "ZMdVETMGwzz", "VSSmCVmaTM5"]
      aVar.Add(xArr)
      xArr = ["Two times", "4", "xGc4o4Oj3W8", "VSSmCVmaTM5"]
      aVar.Add(xArr)

      xArr = ["Three times", "1", "Aw24Ejbp63F", "kXFhKYzLFKT"]
      aVar.Add(xArr)
      xArr = ["Three times", "2", "uKeGRM3UK5z", "kXFhKYzLFKT"]
      aVar.Add(xArr)
      xArr = ["Three times", "3", "Aw24Ejbp63F", "VSSmCVmaTM5"]
      aVar.Add(xArr)
      xArr = ["Three times", "4", "uKeGRM3UK5z", "VSSmCVmaTM5"]
      aVar.Add(xArr)

      xArr = ["Four times", "1", "mTfqwld6Ipc", "kXFhKYzLFKT"]
      aVar.Add(xArr)
      xArr = ["Four times", "2", "oMUgt63LJWU", "kXFhKYzLFKT"]
      aVar.Add(xArr)
      xArr = ["Four times", "3", "mTfqwld6Ipc", "VSSmCVmaTM5"]
      aVar.Add(xArr)
      xArr = ["Four times", "4", "oMUgt63LJWU", "VSSmCVmaTM5"]
      aVar.Add(xArr)

    Else If sCategory = "Maternal Death" Then
      xArr = ["Health Facility", "1", "YZfwWNZzfg0", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Health Facility", "2", "BL5XaUOJ6aw", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Health Facility", "3", "IMFPhLtATaw", "kdsirVNKdhm"]

    Else If sCategory = "Neonatal Death" Then
      xArr = ["Health Facility", "1", "Fr9hLa5q3YE", "nOyy5SUrox6"]
      aVar.Add(xArr)
      xArr = ["Health Facility", "2", "Fr9hLa5q3YE", "ZpMmXgciIXo"]
      aVar.Add(xArr)

    Else If sCategory = "Safe Abortion Service" Then
    Endif

  Else If sChapter = "Family Planning Program" Then

  Else If sChapter = "New Born Care" Then
    If sCategory = "Number of sick babies admitted at SNCU/NICU/KMCU" Then

    Else If sCategory = "Management & Treatment Outocmes at SNCU/NICU/KMCU" Then

    Else If sCategory = "Number managed with KMC at SNCU/NICU/KMCU" Then

    Endif

  Else If sChapter = "Non Communicable Disease" Then
    If sCategory = "Number of NCD cases on Treatment (OPD/Emergency)" Then
      ' Hypertension
      xArr = ["Hypertension", "1", "LeCza0mAdOB", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Hypertension", "2", "LeCza0mAdOB", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Hypertension", "3", "rwi79TawFmj", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Hypertension", "4", "rwi79TawFmj", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Hypertension", "5", "Sd0yXZtNvCN", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Hypertension", "6", "Sd0yXZtNvCN", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Hypertension", "7", "Sd0yXZtNvCN", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Hypertension", "8", "Sd0yXZtNvCN", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Hypertension", "9", "HInTiOU9WQf", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Cardiovascular Disease
      xArr = ["Cardiovascular Disease", "1", "hvIornoPPoF", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Cardiovascular Disease", "2", "hvIornoPPoF", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Cardiovascular Disease", "3", "AT4WBoEQ0hi", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Cardiovascular Disease", "4", "AT4WBoEQ0hi", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Cardiovascular Disease", "5", "CyCw6LwwrQX", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Cardiovascular Disease", "6", "CyCw6LwwrQX", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Cardiovascular Disease", "7", "CyCw6LwwrQX", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Cardiovascular Disease", "8", "CyCw6LwwrQX", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Cardiovascular Disease", "9", "nDuTcDfiJV8", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Diabetes
      xArr = ["Diabetes", "1", "SzSje67t0kS", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Diabetes", "2", "SzSje67t0kS", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Diabetes", "3", "AzwVCsmrb9P", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Diabetes", "4", "AzwVCsmrb9P", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Diabetes", "5", "Qp1fdBPEvwL", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Diabetes", "6", "Qp1fdBPEvwL", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Diabetes", "7", "Qp1fdBPEvwL", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Diabetes", "8", "Qp1fdBPEvwL", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Diabetes", "9", "ot7GJAN0aGC", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Cancer
      xArr = ["Cancer", "1", "EXoCamTZaQd", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Cancer", "2", "EXoCamTZaQd", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Cancer", "3", "Owm4lIptBzc", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Cancer", "4", "Owm4lIptBzc", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Cancer", "5", "fXs7iiMEDzA", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Cancer", "6", "fXs7iiMEDzA", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Cancer", "7", "fXs7iiMEDzA", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Cancer", "8", "fXs7iiMEDzA", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Cancer", "9", "QCetvRjIt2H", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' COPD
      xArr = ["COPD", "1", "q2eXZ7fqNWj", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["COPD", "2", "q2eXZ7fqNWj", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["COPD", "3", "Djed3cBdM67", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["COPD", "4", "Djed3cBdM67", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["COPD", "5", "aB3Mue9SZo0", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["COPD", "6", "aB3Mue9SZo0", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["COPD", "7", "aB3Mue9SZo0", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["COPD", "8", "aB3Mue9SZo0", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["COPD", "9", "SbS5ZdAVecb", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Asthma
      xArr = ["Asthma", "1", "JPfItOPmXXc", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Asthma", "2", "JPfItOPmXXc", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Asthma", "3", "tsBgfmFzhfi", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Asthma", "4", "tsBgfmFzhfi", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Asthma", "5", "izwuKmaUGmN", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Asthma", "6", "izwuKmaUGmN", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Asthma", "7", "izwuKmaUGmN", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Asthma", "8", "izwuKmaUGmN", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Asthma", "9", "lNtDBQ1rfNe", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Chronic Kideny Disease(CKD)
      xArr = ["Chronic Kideny Disease(CKD)", "1", "Lm1h4O5ZMGU", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Chronic Kideny Disease(CKD)", "2", "Lm1h4O5ZMGU", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Chronic Kideny Disease(CKD)", "3", "hGhANWBn0KW", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Chronic Kideny Disease(CKD)", "4", "hGhANWBn0KW", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Chronic Kideny Disease(CKD)", "5", "KVKlg4NTtpA", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Chronic Kideny Disease(CKD)", "6", "KVKlg4NTtpA", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Chronic Kideny Disease(CKD)", "7", "KVKlg4NTtpA", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Chronic Kideny Disease(CKD)", "8", "KVKlg4NTtpA", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Chronic Kideny Disease(CKD)", "9", "uF3Bdqhu2FP", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Rheumatic Heart Disease(RHD)
      xArr = ["Rheumatic Heart Disease(RHD)", "1", "fFU4ZRSykUK", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Rheumatic Heart Disease(RHD)", "2", "fFU4ZRSykUK", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Rheumatic Heart Disease(RHD)", "3", "tYB9QjEUmOC", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Rheumatic Heart Disease(RHD)", "4", "tYB9QjEUmOC", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Rheumatic Heart Disease(RHD)", "5", "xUHMyVueYQm", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Rheumatic Heart Disease(RHD)", "6", "xUHMyVueYQm", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Rheumatic Heart Disease(RHD)", "7", "xUHMyVueYQm", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Rheumatic Heart Disease(RHD)", "8", "xUHMyVueYQm", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Rheumatic Heart Disease(RHD)", "9", "Px4swgdsH7y", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Stroke
      xArr = ["Stroke", "1", "oJ50L9ODiVa", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Stroke", "2", "oJ50L9ODiVa", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Stroke", "3", "KErZn3Ywi5B", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Stroke", "4", "KErZn3Ywi5B", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Stroke", "5", "aLkVzthM6Wy", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Stroke", "6", "aLkVzthM6Wy", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Stroke", "7", "aLkVzthM6Wy", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Stroke", "8", "aLkVzthM6Wy", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Stroke", "9", "q2D8c1cLVyj", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Heart Attacks
      xArr = ["Heart Attacks", "1", "fquGHB0ZIum", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Heart Attacks", "2", "fquGHB0ZIum", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Heart Attacks", "3", "lma6oW6rdAn", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Heart Attacks", "4", "lma6oW6rdAn", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Heart Attacks", "5", "Y0qIoSb84qk", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Heart Attacks", "6", "Y0qIoSb84qk", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Heart Attacks", "7", "Y0qIoSb84qk", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Heart Attacks", "8", "Y0qIoSb84qk", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Heart Attacks", "9", "NLACl6NYb3H", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Thyroid Diseases
      xArr = ["Thyroid Diseases", "1", "iwazxMkEYAC", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Thyroid Diseases", "2", "iwazxMkEYAC", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Thyroid Diseases", "3", "pgp0HxUbUfS", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Thyroid Diseases", "4", "pgp0HxUbUfS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Thyroid Diseases", "5", "tujDM5qBjim", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Thyroid Diseases", "6", "tujDM5qBjim", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Thyroid Diseases", "7", "tujDM5qBjim", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Thyroid Diseases", "8", "tujDM5qBjim", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Thyroid Diseases", "9", "nYLo2XkOXAJ", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Congenital Heart Disease
      xArr = ["Congenital Heart Disease", "1", "HDU41Z5SB6g", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Congenital Heart Disease", "2", "HDU41Z5SB6g", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Congenital Heart Disease", "3", "UjAJzmPK6on", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Congenital Heart Disease", "4", "UjAJzmPK6on", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Congenital Heart Disease", "5", "liNh3r6CSnV", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Congenital Heart Disease", "6", "liNh3r6CSnV", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Congenital Heart Disease", "7", "liNh3r6CSnV", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Congenital Heart Disease", "8", "liNh3r6CSnV", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Congenital Heart Disease", "9", "VFsGMZMrtDg", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Sickle cell diseases And other haemoglobinopathies
      xArr = ["Sickle cell diseases And other haemoglobinopathies", "1", "cHmpZiJ8qHX", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Sickle cell diseases And other haemoglobinopathies", "2", "cHmpZiJ8qHX", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Sickle cell diseases And other haemoglobinopathies", "3", "FobDOzaxmnw", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Sickle cell diseases And other haemoglobinopathies", "4", "FobDOzaxmnw", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Sickle cell diseases And other haemoglobinopathies", "5", "gWQRAuXx6QZ", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Sickle cell diseases And other haemoglobinopathies", "6", "gWQRAuXx6QZ", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Sickle cell diseases And other haemoglobinopathies", "7", "gWQRAuXx6QZ", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Sickle cell diseases And other haemoglobinopathies", "8", "gWQRAuXx6QZ", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Sickle cell diseases And other haemoglobinopathies", "9", "Qxs8EeNslpX", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Alcohol Liver Diseases
      xArr = ["Alcohol Liver Diseases", "1", "xG1PwasWatm", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Alcohol Liver Diseases", "2", "xG1PwasWatm", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Alcohol Liver Diseases", "3", "mxzNTfBGQss", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Alcohol Liver Diseases", "4", "mxzNTfBGQss", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Alcohol Liver Diseases", "5", "nu9yUtcpeZn", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Alcohol Liver Diseases", "6", "nu9yUtcpeZn", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Alcohol Liver Diseases", "7", "nu9yUtcpeZn", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Alcohol Liver Diseases", "8", "nu9yUtcpeZn", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Alcohol Liver Diseases", "9", "k3bRvwLEZSp", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Obesity
      xArr = ["Obesity", "1", "XLwB1KffIDh", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Obesity", "2", "XLwB1KffIDh", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Obesity", "3", "Jc4qrNqkcpJ", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Obesity", "4", "Jc4qrNqkcpJ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Obesity", "5", "xVbdLCoOdC9", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Obesity", "6", "xVbdLCoOdC9", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Obesity", "7", "xVbdLCoOdC9", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Obesity", "8", "xVbdLCoOdC9", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Obesity", "9", "GKaQJ506bL2", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Other NCDs cases
      xArr = ["Other NCDs cases", "1", "bxxVeSrq4Wx", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Other NCDs cases", "2", "bxxVeSrq4Wx", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Other NCDs cases", "3", "CMALKBzhU1S", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Other NCDs cases", "4", "CMALKBzhU1S", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Other NCDs cases", "5", "iJW3klyHoXj", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Other NCDs cases", "6", "iJW3klyHoXj", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Other NCDs cases", "7", "iJW3klyHoXj", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Other NCDs cases", "8", "iJW3klyHoXj", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Other NCDs cases", "9", "IxWtnYzCpLt", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Number of NCD Cause-Specific Deaths" Then
      ' Cardiovascular Disease
      xArr = ["Cardiovascular Disease", "1", "HIsvA1jUvuN", "KEZMn4LrcVd"]
      aVar.Add(xArr)
      xArr = ["Cardiovascular Disease", "2", "HIsvA1jUvuN", "WRJMEMEtGxf"]
      aVar.Add(xArr)
      xArr = ["Cardiovascular Disease", "3", "HCFKV1hOzj6", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Cardiovascular Disease", "4", "HCFKV1hOzj6", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Cardiovascular Disease", "5", "HCFKV1hOzj6", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Cardiovascular Disease", "6", "HCFKV1hOzj6", "lV0XyIUa4h0"]

      ' Cancer
      xArr = ["Cancer", "1", "RzyxxiAje5q", "KEZMn4LrcVd"]
      aVar.Add(xArr)
      xArr = ["Cancer", "2", "RzyxxiAje5q", "WRJMEMEtGxf"]
      aVar.Add(xArr)
      xArr = ["Cancer", "3", "RciF1sxp9gC", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Cancer", "4", "RciF1sxp9gC", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Cancer", "5", "RciF1sxp9gC", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Cancer", "6", "RciF1sxp9gC", "lV0XyIUa4h0"]

      ' Diabetes
      xArr = ["Diabetes", "1", "cOFMAqA6P04", "KEZMn4LrcVd"]
      aVar.Add(xArr)
      xArr = ["Diabetes", "2", "cOFMAqA6P04", "WRJMEMEtGxf"]
      aVar.Add(xArr)
      xArr = ["Diabetes", "3", "jJqu6XeskfM", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Diabetes", "4", "jJqu6XeskfM", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Diabetes", "5", "jJqu6XeskfM", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Diabetes", "6", "jJqu6XeskfM", "lV0XyIUa4h0"]

      ' Chronic Respiratory Diseases
      xArr = ["Chronic Respiratory Diseases", "1", "pr746JC8Ts4", "KEZMn4LrcVd"]
      aVar.Add(xArr)
      xArr = ["Chronic Respiratory Diseases", "2", "pr746JC8Ts4", "WRJMEMEtGxf"]
      aVar.Add(xArr)
      xArr = ["Chronic Respiratory Diseases", "3", "QgwXdirIRzb", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Chronic Respiratory Diseases", "4", "QgwXdirIRzb", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Chronic Respiratory Diseases", "5", "QgwXdirIRzb", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Chronic Respiratory Diseases", "6", "QgwXdirIRzb", "lV0XyIUa4h0"]

      ' Suicide
      xArr = ["Suicide", "1", "fOsZsorwG5i", "KEZMn4LrcVd"]
      aVar.Add(xArr)
      xArr = ["Suicide", "2", "fOsZsorwG5i", "WRJMEMEtGxf"]
      aVar.Add(xArr)
      xArr = ["Suicide", "3", "pObwpMGitkw", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Suicide", "4", "pObwpMGitkw", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Suicide", "5", "pObwpMGitkw", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Suicide", "6", "pObwpMGitkw", "lV0XyIUa4h0"]

      ' Other NCDs
      xArr = ["Other NCDs", "1", "NdyA2SIrTp3", "KEZMn4LrcVd"]
      aVar.Add(xArr)
      xArr = ["Other NCDs", "2", "NdyA2SIrTp3", "WRJMEMEtGxf"]
      aVar.Add(xArr)
      xArr = ["Other NCDs", "3", "EYnGnMPpUj5", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Other NCDs", "4", "EYnGnMPpUj5", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Other NCDs", "5", "EYnGnMPpUj5", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Other NCDs", "6", "EYnGnMPpUj5", "lV0XyIUa4h0"]

    Else If sCategory = "Total number of new cancers cases managed" Then

    Else If sCategory = "Number of Injuries" Then
      ' Road Traffic Injuries(RTI)
      xArr = ["Road Traffic Injuries(RTI)", "1", "z4zZKycUn7q", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Road Traffic Injuries(RTI)", "2", "z4zZKycUn7q", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Road Traffic Injuries(RTI)", "3", "iMe5jjpXrgy", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Road Traffic Injuries(RTI)", "4", "iMe5jjpXrgy", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Road Traffic Injuries(RTI)", "5", "rc7cUdQIxFK", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Road Traffic Injuries(RTI)", "6", "rc7cUdQIxFK", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Road Traffic Injuries(RTI)", "7", "rc7cUdQIxFK", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Road Traffic Injuries(RTI)", "8", "rc7cUdQIxFK", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Road Traffic Injuries(RTI)", "9", "k7EUJegDMPw", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Fall
      xArr = ["Fall", "1", "FVPiuc1WHWd", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Fall", "2", "FVPiuc1WHWd", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Fall", "3", "xWAGqPiHnhR", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Fall", "4", "xWAGqPiHnhR", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Fall", "5", "xgrkJMQFjvR", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Fall", "6", "xgrkJMQFjvR", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Fall", "7", "xgrkJMQFjvR", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Fall", "8", "xgrkJMQFjvR", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Fall", "9", "RWeMysLqLUD", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Burn
      xArr = ["Burn", "1", "DWCS2PhHOzE", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Burn", "2", "DWCS2PhHOzE", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Burn", "3", "s8Al8Y511BD", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Burn", "4", "s8Al8Y511BD", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Burn", "5", "qXcuzRnU7ku", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Burn", "6", "qXcuzRnU7ku", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Burn", "7", "qXcuzRnU7ku", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Burn", "8", "qXcuzRnU7ku", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Burn", "9", "RG9qyLUZA3B", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Drowning
      xArr = ["Drowning", "1", "Bwjtjctlg4t", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Drowning", "2", "Bwjtjctlg4t", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Drowning", "3", "RydrtJXs1Qv", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Drowning", "4", "RydrtJXs1Qv", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Drowning", "5", "Aw73bGnlibS", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Drowning", "6", "Aw73bGnlibS", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Drowning", "7", "Aw73bGnlibS", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Drowning", "8", "Aw73bGnlibS", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Drowning", "9", "vhxTNvGDV24", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Bites
      xArr = ["Bites", "1", "mLsQrl20Npb", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Bites", "2", "mLsQrl20Npb", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Bites", "3", "mmY3cVGSnoy", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Bites", "4", "mmY3cVGSnoy", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Bites", "5", "z5C55Elfbns", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Bites", "6", "z5C55Elfbns", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Bites", "7", "z5C55Elfbns", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Bites", "8", "z5C55Elfbns", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Bites", "9", "gMWDrchdKEf", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Occupational Injury
      xArr = ["Occupational Injury", "1", "DW9mTz15kBJ", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Occupational Injury", "2", "DW9mTz15kBJ", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Occupational Injury", "3", "eQDVYQObSqY", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Occupational Injury", "4", "eQDVYQObSqY", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Occupational Injury", "5", "gPJ4vw4w3fW", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Occupational Injury", "6", "gPJ4vw4w3fW", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Occupational Injury", "7", "gPJ4vw4w3fW", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Occupational Injury", "8", "gPJ4vw4w3fW", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Occupational Injury", "9", "TqyxRCHcuNi", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Violence
      xArr = ["Violence", "1", "eSZ2WOItNma", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Violence", "2", "eSZ2WOItNma", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Violence", "3", "h6rlme8MpxG", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Violence", "4", "h6rlme8MpxG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Violence", "5", "tHkf40JQtJl", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Violence", "6", "tHkf40JQtJl", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Violence", "7", "tHkf40JQtJl", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Violence", "8", "tHkf40JQtJl", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Violence", "9", "bA7sBRfMVlB", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Self-Harm
      xArr = ["Self-Harm", "1", "efTf37JgM6Z", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Self-Harm", "2", "efTf37JgM6Z", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Self-Harm", "3", "qII6xcs3GS6", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Self-Harm", "4", "qII6xcs3GS6", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Self-Harm", "5", "L0wYGMPGngI", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Self-Harm", "6", "L0wYGMPGngI", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Self-Harm", "7", "L0wYGMPGngI", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Self-Harm", "8", "L0wYGMPGngI", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Self-Harm", "9", "WAKWAHJrB4P", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Number of Injury Deaths" Then

    Else If sCategory = "Number of Mental Health Cases on Treatment (OPD/Emergency)" Then
      'Depression
      xArr = ["Depression", "1", "BSoyDcGsoTi", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Depression", "2", "BSoyDcGsoTi", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Depression", "3", "iV1oU9TI80S", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Depression", "4", "iV1oU9TI80S", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Depression", "5", "qjcLdv2oJMs", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Depression", "6", "qjcLdv2oJMs", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Depression", "7", "qjcLdv2oJMs", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Depression", "8", "qjcLdv2oJMs", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Depression", "9", "a6n16yanXNx", "kdsirVNKdhm"]
      aVar.Add(xArr)

      'Suicide Attempt
      xArr = ["Suicide Attempt", "1", "CHTSv94BzJB", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Suicide Attempt", "2", "CHTSv94BzJB", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Suicide Attempt", "3", "YxQkSqI1ovU", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Suicide Attempt", "4", "YxQkSqI1ovU", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Suicide Attempt", "5", "uHqYEyUYzYD", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Suicide Attempt", "6", "uHqYEyUYzYD", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Suicide Attempt", "7", "uHqYEyUYzYD", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Suicide Attempt", "8", "uHqYEyUYzYD", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Suicide Attempt", "9", "oR96oVHb75u", "kdsirVNKdhm"]
      aVar.Add(xArr)

      'Epilepsy
      xArr = ["Epilepsy", "1", "XMe3M7MQFWv", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Epilepsy", "2", "XMe3M7MQFWv", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Epilepsy", "3", "LUvZY8VlV1p", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Epilepsy", "4", "LUvZY8VlV1p", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Epilepsy", "5", "CfNuhJf8SQ3", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Epilepsy", "6", "CfNuhJf8SQ3", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Epilepsy", "7", "CfNuhJf8SQ3", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Epilepsy", "8", "CfNuhJf8SQ3", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Epilepsy", "9", "j73EVObipZJ", "kdsirVNKdhm"]
      aVar.Add(xArr)

      'Psychosis
      xArr = ["Psychosis", "1", "c3GlhRxjXif", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Psychosis", "2", "c3GlhRxjXif", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Psychosis", "3", "Mche4Wnn0RK", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Psychosis", "4", "Mche4Wnn0RK", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Psychosis", "5", "l345Bcnhrxt", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Psychosis", "6", "l345Bcnhrxt", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Psychosis", "7", "l345Bcnhrxt", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Psychosis", "8", "l345Bcnhrxt", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Psychosis", "9", "IsjYfoseOWN", "kdsirVNKdhm"]
      aVar.Add(xArr)

      'Anxiety Disorder
      xArr = ["Anxiety Disorder", "1", "oOi7YC5f0wI", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Anxiety Disorder", "2", "oOi7YC5f0wI", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Anxiety Disorder", "3", "ck3mDfwnhwo", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Anxiety Disorder", "4", "ck3mDfwnhwo", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Anxiety Disorder", "5", "u9t9JI1F3yt", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Anxiety Disorder", "6", "u9t9JI1F3yt", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Anxiety Disorder", "7", "u9t9JI1F3yt", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Anxiety Disorder", "8", "u9t9JI1F3yt", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Anxiety Disorder", "9", "s6AMaecZ22Y", "kdsirVNKdhm"]
      aVar.Add(xArr)

      'Emotional and Behavioural Disorder of Children and Adolescents
      xArr = ["Emotional and Behavioural Disorder of Children and Adolescents", "1", "kH8oyQGpHPB", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Emotional and Behavioural Disorder of Children and Adolescents", "2", "kH8oyQGpHPB", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Emotional and Behavioural Disorder of Children and Adolescents", "3", "OSvktMqsEUi", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Emotional and Behavioural Disorder of Children and Adolescents", "4", "OSvktMqsEUi", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Emotional and Behavioural Disorder of Children and Adolescents", "5", "wphqrBoCHzQ", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Emotional and Behavioural Disorder of Children and Adolescents", "9", "FvSbWNyvk64", "kdsirVNKdhm"]
      aVar.Add(xArr)

      'Dementia
      xArr = ["Dementia", "1", "O77ZPunXVyH", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Dementia", "2", "O77ZPunXVyH", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Dementia", "3", "gLgVbhGl3qr", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Dementia", "4", "gLgVbhGl3qr", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Dementia", "7", "YcLXjQTuyBg", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Dementia", "8", "YcLXjQTuyBg", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Dementia", "9", "UyPtG8Tc72e", "kdsirVNKdhm"]
      aVar.Add(xArr)

      'Conversion Disorder
      xArr = ["Conversion Disorder", "1", "geP5gKRwrL7", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Conversion Disorder", "2", "geP5gKRwrL7", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Conversion Disorder", "3", "xARbXiDXjJh", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Conversion Disorder", "4", "xARbXiDXjJh", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Conversion Disorder", "5", "YwthPUC9ulq", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Conversion Disorder", "6", "YwthPUC9ulq", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Conversion Disorder", "7", "YwthPUC9ulq", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Conversion Disorder", "8", "YwthPUC9ulq", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Conversion Disorder", "9", "F3E961HkfLx", "kdsirVNKdhm"]
      aVar.Add(xArr)

      'Bipolar Disorder
      xArr = ["Bipolar Disorder", "1", "wwtv9tyh9Lc", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Bipolar Disorder", "2", "wwtv9tyh9Lc", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Bipolar Disorder", "3", "yixNF8bo6oD", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Bipolar Disorder", "4", "yixNF8bo6oD", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Bipolar Disorder", "5", "sFNhiAKKXwz", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Bipolar Disorder", "6", "sFNhiAKKXwz", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Bipolar Disorder", "7", "sFNhiAKKXwz", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Bipolar Disorder", "8", "sFNhiAKKXwz", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Bipolar Disorder", "9", "iDAklbmfXcc", "kdsirVNKdhm"]
      aVar.Add(xArr)

      'Other Mental Disorder
      xArr = ["Other Mental Disorder", "1", "VHgfBgnw9ng", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Other Mental Disorder", "2", "VHgfBgnw9ng", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Other Mental Disorder", "3", "efc1qmLJLt6", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Other Mental Disorder", "4", "efc1qmLJLt6", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Other Mental Disorder", "5", "CAGgmuzdGGm", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Other Mental Disorder", "6", "CAGgmuzdGGm", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Other Mental Disorder", "7", "CAGgmuzdGGm", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Other Mental Disorder", "8", "CAGgmuzdGGm", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Other Mental Disorder", "9", "TQl5Hgxpsa0", "kdsirVNKdhm"]
      aVar.Add(xArr)

      'Alcohol Use Disorder
      xArr = ["Alcohol Use Disorder", "1", "cQDXLpUOVVp", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Alcohol Use Disorder", "2", "cQDXLpUOVVp", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Alcohol Use Disorder", "3", "N3nxel5keim", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Alcohol Use Disorder", "4", "N3nxel5keim", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Alcohol Use Disorder", "5", "KGezaPUqXnI", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Alcohol Use Disorder", "6", "KGezaPUqXnI", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Alcohol Use Disorder", "7", "KGezaPUqXnI", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Alcohol Use Disorder", "8", "KGezaPUqXnI", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Alcohol Use Disorder", "9", "RiokyGz3dwy", "kdsirVNKdhm"]
      aVar.Add(xArr)

      'Other Substance Use Disorders
      xArr = ["Other Substance Use Disorders", "1", "qIAtGRUqn8E", "pwrowQx8vq6"]
      aVar.Add(xArr)
      xArr = ["Other Substance Use Disorders", "2", "qIAtGRUqn8E", "iBXAu03RvKM"]
      aVar.Add(xArr)
      xArr = ["Other Substance Use Disorders", "3", "XMTB1JbxCRp", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Other Substance Use Disorders", "4", "XMTB1JbxCRp", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Other Substance Use Disorders", "5", "QC2sdLALBeX", "HfnX7psZ9oj"]
      aVar.Add(xArr)
      xArr = ["Other Substance Use Disorders", "6", "QC2sdLALBeX", "rqWi5RL6YPR"]
      aVar.Add(xArr)
      xArr = ["Other Substance Use Disorders", "7", "QC2sdLALBeX", "LLmUXbbVXc8"]
      aVar.Add(xArr)
      xArr = ["Other Substance Use Disorders", "8", "QC2sdLALBeX", "lV0XyIUa4h0"]
      aVar.Add(xArr)
      xArr = ["Other Substance Use Disorders", "9", "J6g5SqeeGkh", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Type of Mental Health Cases" Then

    Else If sCategory = "Control and Follow Up Cases for Hypertension and Diabetes" Then

    Endif

    'GetNewOPDMorbidity(sCategory)
  Else If sChapter = "New Outpatient Morbidity" Then
    If sCategory = "Certain Infectious or Parasitic Diseases" Then
      ' Measles
      xArr = ["1F03", "2", "ZrwTzFTdZhz", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1F03", "3", "ZrwTzFTdZhz", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Diptheria
      xArr = ["1C17", "2", "CSRB2H5GLDZ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1C17", "3", "CSRB2H5GLDZ", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Whooping Cough
      xArr = ["1C12", "2", "Y3S9491u1gd", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1C12", "3", "Y3S9491u1gd", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Neonatal Tetanus
      xArr = ["1C15", "2", "QQSZDRTD294", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1C15", "3", "QQSZDRTD294", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Tetanus
      xArr = ["1C13", "2", "qkAsR3sHGWM", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1C13", "3", "qkAsR3sHGWM", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Tuberculosis
      xArr = ["1B1Z", "2", "cVIqiRvVHVE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1B1Z", "3", "cVIqiRvVHVE", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Flaccid Paralysis(AFP)
      xArr = ["MB56", "2", "cSBNopxh2ZP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MB56", "3", "cSBNopxh2ZP", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Rubella
      xArr = ["1F02", "2", "EJOh3U60jKx", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1F02", "3", "EJOh3U60jKx", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Mumps
      xArr = ["1D80", "2", "BpxwodMjTM4", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1D80", "3", "BpxwodMjTM4", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Chicken Pox
      xArr = ["1E90.0", "2", "ZJPpYiYwPeW", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1E90.0", "3", "ZJPpYiYwPeW", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hepatitis B
      xArr = ["1E51.0Z", "2", "cI801zaVGau", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1E51.0Z", "3", "cI801zaVGau", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Communicable, Vector Borne" Then
      ' Acute Encephalitis Like Syndrome(AES)
      xArr = ["1D00", "2", "pHrDUquZIYm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1D00", "3", "pHrDUquZIYm", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Filariasis
      xArr = ["1F66", "2", "zcypZ3frGDB", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1F66", "3", "zcypZ3frGDB", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Clinical Malaria
      xArr = ["1F45", "2", "QDaBpwjmfws", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1F45", "3", "QDaBpwjmfws", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Malaria(Plasmodium Falciparum)
      xArr = ["1F40", "2", "fZsSPCGs3d9", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1F40", "3", "fZsSPCGs3d9", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Malaria(Plasmodium Vivax)
      xArr = ["1F41", "2", "LZYfptKIqkh", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1F41", "3", "LZYfptKIqkh", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Dengue Fever
      xArr = ["1D2Z", "2", "XBZPrqWn6OG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1D2Z", "3", "XBZPrqWn6OG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Kala - azar / Leshmaniasis
      xArr = ["1F54.0", "2", "gCLElGi3gze", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1F54.0", "3", "gCLElGi3gze", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Scrub Typhus
      xArr = ["1C30.3", "2", "G8wYJTMKN0U", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1C30.3", "3", "G8wYJTMKN0U", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Japanese Encephalitis
      xArr = ["1C85", "2", "UcD9xoD0pHx", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1C85", "3", "UcD9xoD0pHx", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Communicable, Water/Food Borne" Then
      ' Typhoid(Enteric Fever)
      xArr = ["1A07", "2", "gwhVCfaS9UN", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1A07", "3", "gwhVCfaS9UN", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute gastro - enteritis(AGE)
      xArr = ["1A40", "2", "cISG3BoGZTm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1A40", "3", "cISG3BoGZTm", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Ameobic Dysentery / Amoebiasis
      xArr = ["1A36.00", "2", "td2iBmsLero", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1A36.00", "3", "td2iBmsLero", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Bacillary Dysentery / Shigellosis
      xArr = ["1A02", "2", "y3glz39HVvQ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1A02", "3", "y3glz39HVvQ", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Presumed non -Inf ectious diarrhoea
      xArr = ["ME05.1", "2", "LAwTvVrfnOB", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ME05.1", "3", "LAwTvVrfnOB", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Cholera
      xArr = ["1A00", "2", "FJ0pdVWlBbG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1A00", "3", "FJ0pdVWlBbG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Intestinal Worms
      xArr = ["1F90.2", "2", "te3iSwrdWO7", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1F90.2", "3", "te3iSwrdWO7", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Jaundice
      xArr = ["ME10.1", "2", "iZDCnd0VgWy", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ME10.1", "3", "iZDCnd0VgWy", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hepatitis A
      xArr = ["1E50.0", "2", "w5mNn2EBUmg", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1E50.0", "3", "w5mNn2EBUmg", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hepatitis E
      xArr = ["1E51.3", "2", "LAP6lgcrJi5", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1E51.3", "3", "LAP6lgcrJi5", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Volume Depletion(Dehydration)
      xArr = ["5C70", "2", "ZZsL7yaqg4L", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5C70", "3", "ZZsL7yaqg4L", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Bacterial Intestinal infection
      xArr = ["1A0Z", "2", "iVcBPvC8Dm4", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1A0Z", "3", "iVcBPvC8Dm4", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Other Communicable Diseases" Then
      ' Leprosy
      xArr = ["1B20", "2", "zCnvG70EbAa", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1B20", "3", "zCnvG70EbAa", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Meningitis
      xArr = ["1D01.Y", "2", "E80SAeiK4KF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1D01.Y", "3", "E80SAeiK4KF", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "HIV/STI" Then
      'HIV Infection
      xArr = ["1C62", "2", "oVnNnGHesch", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1C62", "3", "oVnNnGHesch", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Urethral Discharge Syndrome(UDS)Gonococal
      xArr = ["1A70.0Y", "2", "B8CqXFlCBr5", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1A70.0Y", "3", "B8CqXFlCBr5", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Scrotal Swelling Syndrome(SSS)
      xArr = ["MF40.2Y", "3", "BJpAbmeRUVm", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Vaginal Discharge Syndrome(VDS)
      xArr = ["MF3A", "2", "HuGvgg2pOA2", "ye1QuAMRG5Z"]
      aVar.Add(xArr)

      ' Lower Abdominal Pain Syndrome(LAPS)
      xArr = ["MD81.12", "2", "uPijgtgd0jA", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MD81.12", "3", "uPijgtgd0jA", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Neonatal Conjuctive Syndrome(NCS)
      xArr = ["KA65.0", "2", "A7ZUMi18b2C", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["KA65.0", "3", "A7ZUMi18b2C", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Genital User Disease Syndrome(GUDS) - female
      xArr = ["GA6Z", "2", "b0flJFAByeR", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Genital User Disease Syndrome(GUDS) - male
      xArr = ["GB0Z", "3", "ru2303Sy7nA", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Inguinal Bubo Syndrome(IBS)
      xArr = ["BD90.Y", "2", "s4WLJ0dumzx", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["BD90.Y", "3", "s4WLJ0dumzx", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Syphilis
      xArr = ["1A6Z", "2", "wxnuAwt1Hqm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1A6Z", "3", "wxnuAwt1Hqm", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Other Infected Diseases" Then
      ' ARI / Lower respiratory tract infection(LRTI)
      xArr = ["CA4Z", "2", "eimjIL0RFb8", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA4Z", "3", "eimjIL0RFb8", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Upper respiratory tract infection(URTI)
      xArr = ["CA07.0", "2", "C1dYWXuPeBo", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA07.0", "3", "C1dYWXuPeBo", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Pneumonia
      xArr = ["CA40", "2", "ZCcVuwqAfaG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA40", "3", "ZCcVuwqAfaG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Bronchitis(Acute & chronic)
      xArr = ["CA20", "2", "G2SkThUYe5w", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA20", "3", "G2SkThUYe5w", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Urinary Tract Infection(UTI)
      xArr = ["GC08", "2", "uV5LwN8OzCy", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["GC08", "3", "uV5LwN8OzCy", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Viral Influenza
      xArr = ["1E32", "2", "qrTjnhUQ195", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1E32", "3", "qrTjnhUQ195", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Reproductive Tract Infection(RTI) - Female
      xArr = ["GA0Z", "2", "z1O4M2enpI3", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Reproductive Tract Infection(RTI) - Male
      xArr = ["GB07", "3", "INDKIQBLb3i", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Nutritional & Metabolic Disorder" Then
      ' Goitre, Cretinism
      xArr = ["5A01", "2", "Qvvn1g4XfZ1", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5A01", "3", "Qvvn1g4XfZ1", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Diabetes Mellitus(DM)
      xArr = ["5A14", "2", "l09HErr6ggw", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5A14", "3", "l09HErr6ggw", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Malnutrition
      xArr = ["5B7Z", "2", "oh9zomy0bdm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5B7Z", "3", "oh9zomy0bdm", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Avitaminoses & other nutrient deficiency
      xArr = ["5B7Y", "2", "bp53MgxccqQ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5B7Y", "3", "bp53MgxccqQ", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Obesity
      xArr = ["5B81", "2", "EKavdicUQaW", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5B81", "3", "EKavdicUQaW", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Anaemia / Polyneuropathy
      xArr = ["3A9Z", "2", "doJ6CNvMbmw", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["3A9Z", "3", "doJ6CNvMbmw", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Polyneuritis
      xArr = ["8C0Z", "2", "nDWUFmrIPCA", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["8C0Z", "3", "nDWUFmrIPCA", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Skin Diseases" Then
      ' Acne
      xArr = ["ED80", "2", "VAqYKbRvrHe", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ED80", "3", "VAqYKbRvrHe", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Warts
      xArr = ["1A95", "2", "aoQoJU7AQ9O", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1A95", "3", "aoQoJU7AQ9O", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Chloasma / melasma
      xArr = ["ED60.1", "2", "ZfcANR0riP1", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ED60.1", "3", "ZfcANR0riP1", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Urticaria
      xArr = ["EB05", "2", "FN5uLuYjGmq", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["EB05", "3", "FN5uLuYjGmq", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Dermatitis / Eczema
      xArr = ["EA8Z", "2", "tS2cUtWNXpI", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["EA8Z", "3", "tS2cUtWNXpI", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Alopecia
      xArr = ["ED70", "2", "DuhReYAWpjc", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ED70", "3", "DuhReYAWpjc", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Cellulitis
      xArr = ["1B70", "2", "V6jeKfAPnko", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1B70", "3", "V6jeKfAPnko", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Pediculosis(Lice)
      xArr = ["1G00", "2", "NOYxO4z4lEY", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1G00", "3", "NOYxO4z4lEY", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Vitiligo
      xArr = ["ED63.0", "2", "Xzw4N8KPWQS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ED63.0", "3", "Xzw4N8KPWQS", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Albinism
      xArr = ["EC23.2", "2", "Xfr7s6N5ILP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["EC23.2", "3", "Xfr7s6N5ILP", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Herpes simplex
      xArr = ["1F00.0", "2", "FAaK12zZX3M", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1F00.0", "3", "FAaK12zZX3M", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Herpes zoster
      xArr = ["1E91.Z", "2", "ZfULTbeDgRF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1E91.Z", "3", "ZfULTbeDgRF", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Erythroderma
      xArr = ["EB10", "2", "lvrJamUsDfR", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["EB10", "3", "lvrJamUsDfR", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Impetigo
      xArr = ["1B72", "2", "tdl64qm6OIo", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1B72", "3", "tdl64qm6OIo", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Boils
      xArr = ["1B75.0", "2", "DjYPzxgHx9v", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1B75.0", "3", "DjYPzxgHx9v", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Abscess
      xArr = ["1B75.3", "2", "axzMcDrcIfU", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1B75.3", "3", "axzMcDrcIfU", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Furunculosis
      xArr = ["1B75.2", "2", "mq1lHdw5EZ2", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1B75.2", "3", "mq1lHdw5EZ2", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Fungal infection(Lichen planus)
      xArr = ["EA60", "2", "rwQjknPpoey", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["EA60", "3", "rwQjknPpoey", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Scabies
      xArr = ["1G04", "2", "txuV68xtrYc", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1G04", "3", "txuV68xtrYc", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Leukoderma
      xArr = ["1A61.3", "2", "JNQxHWNvhcf", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1A61.3", "3", "JNQxHWNvhcf", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Psoriasis
      xArr = ["EA90", "2", "ZhcOrFM8ho1", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["EA90", "3", "ZhcOrFM8ho1", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Lymphadenitis
      xArr = ["BD90.0", "2", "IihXJC3GzYF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["BD90.0", "3", "IihXJC3GzYF", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Frostbite
      xArr = ["NE4Z", "2", "PvspE7rlkWK", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NE4Z", "3", "PvspE7rlkWK", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Ear, Nose and Throat Infection" Then
      ' Acute Suppurative Otitis Media
      xArr = ["AA90", "2", "xtYZSzBt4j8", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["AA90", "3", "xtYZSzBt4j8", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Chronic Suppurative Otitis Media
      xArr = ["AA91", "2", "GbSRNVeeY9r", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["AA91", "3", "GbSRNVeeY9r", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Sinusitis
      xArr = ["CA0A", "2", "OJUFnZllsLL", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA0A", "3", "OJUFnZllsLL", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Tonsilitis
      xArr = ["CA03", "2", "Ezc8lbdvcW6", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA03", "3", "Ezc8lbdvcW6", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Pharyngitis / Sore throat
      xArr = ["CA02", "2", "yFJdnwOrHXf", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA02", "3", "yFJdnwOrHXf", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Foreign body In ear
      xArr = ["ND71", "2", "o2Jx5MaLlex", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ND71", "3", "o2Jx5MaLlex", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Foreign body In nose
      xArr = ["ND72.1", "2", "CminYXY6RpV", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ND72.1", "3", "CminYXY6RpV", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Foreign body In throat
      xArr = ["ND72.2", "2", "ek34FewqNAf", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ND72.2", "3", "ek34FewqNAf", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Wax
      xArr = ["AA42", "2", "glyCwpl4XX3", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["AA42", "3", "glyCwpl4XX3", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Nasal Polyps
      xArr = ["CA0J", "2", "a506kRKpXFX", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA0J", "3", "a506kRKpXFX", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Deviated nasal septum(DNS)
      xArr = ["CA0D", "2", "MRSR1vwB7DR", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA0D", "3", "MRSR1vwB7DR", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Rhinitis
      xArr = ["CA09.0", "2", "WTmwO75ijQ0", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA09.0", "3", "WTmwO75ijQ0", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Otitis externa
      xArr = ["AA3Z", "2", "iIHlesXptP0", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["AA3Z", "3", "iIHlesXptP0", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Reflux laryngitis
      xArr = ["CA05.0", "2", "voyeqQ4VHCX", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA05.0", "3", "voyeqQ4VHCX", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Frunculosis Of Ear
      xArr = ["1B75.2", "2", "d6rbLkuwYOX", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1B75.2", "3", "d6rbLkuwYOX", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Nasal Vestibulitis
      xArr = ["CA0Y", "2", "HtTcLcPa76T", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA0Y", "3", "HtTcLcPa76T", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Oral Health Related Problems" Then
      ' Dental caries
      xArr = ["DA08.0", "2", "GyGRGTZsRHN", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA08.0", "3", "GyGRGTZsRHN", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Toothache
      xArr = ["DA0A.Y", "2", "bEaNbyFhWqE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA0A.Y", "3", "bEaNbyFhWqE", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Periodontal disease(gum disease)
      xArr = ["DA0D", "2", "PGX59e9bSPx", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA0D", "3", "PGX59e9bSPx", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Other disorder Of teeth
      xArr = ["DA07.3", "2", "xoQX7YuYQ8d", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA07.3", "3", "xoQX7YuYQ8d", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Oral ulcer(Aphthous & herpetic)
      xArr = ["DA01.10", "2", "FZZdZbgcA47", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA01.10", "3", "FZZdZbgcA47", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Glossitis
      xArr = ["DA03.0", "2", "MkJoAC3k84L", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA03.0", "3", "MkJoAC3k84L", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Stomatitis
      xArr = ["DA01", "2", "dzEJovRUDc7", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA01", "3", "dzEJovRUDc7", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Tooth impaction
      xArr = ["DA07.8", "2", "dFlqpKxwTYh", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA07.8", "3", "dFlqpKxwTYh", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hypoplasia
      xArr = ["3A70", "2", "IriSNYAZb14", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["3A70", "3", "IriSNYAZb14", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Leukoplakia
      xArr = ["DA01.00", "2", "OOO9AMFyOuM", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA01.00", "3", "OOO9AMFyOuM", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Fungal infection(candidiasis)
      xArr = ["1F23", "2", "jXZokvGicd1", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1F23", "3", "jXZokvGicd1", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Oral space infection & abscess
      xArr = ["DA01.30", "2", "nwdHjVGNJXP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA01.30", "3", "nwdHjVGNJXP", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Stained Teeth
      xArr = ["DA08.4", "2", "iNrqjFueJy1", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA08.4", "3", "iNrqjFueJy1", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Chipped Tooth
      xArr = ["NA0D.01", "2", "zk7V0m3RA7A", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NA0D.01", "3", "zk7V0m3RA7A", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hyperdontia
      xArr = ["LA30.3", "2", "KRfpvHKnT8n", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["LA30.3", "3", "KRfpvHKnT8n", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hypersensitivity
      xArr = ["DA08.Y", "2", "zN880cooTgl", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA08.Y", "3", "zN880cooTgl", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Oral cancer
      xArr = ["2B6E", "2", "KkV2jvCCISU", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2B6E", "3", "KkV2jvCCISU", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Gingivitis
      xArr = ["DA0B.Y", "2", "GeJACUuNCRP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA0B.Y", "3", "GeJACUuNCRP", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Periodontitis
      xArr = ["DA0C.Y", "2", "Tc7OOHf9AnE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA0C.Y", "3", "Tc7OOHf9AnE", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Dry Mouth
      xArr = ["DA02.1", "2", "qSCo6gFpbA7", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA02.1", "3", "qSCo6gFpbA7", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Eye Problems" Then
      ' Conjunctivitis
      xArr = ["9A60.Z", "2", "BQhbt7KIEPW", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9A60.Z", "3", "BQhbt7KIEPW", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Trachoma
      xArr = ["1C23.Z", "2", "S6sNGnudQxv", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1C23.Z", "3", "S6sNGnudQxv", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Cataract
      xArr = ["9B10", "2", "Lxyk9qE4YVm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9B10", "3", "Lxyk9qE4YVm", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Blindness
      xArr = ["9D90", "2", "e37wBcnOczg", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9D90", "3", "e37wBcnOczg", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Refractive Error
      xArr = ["9D00", "2", "IqwX6ARGCF7", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9D00", "3", "IqwX6ARGCF7", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Glaucoma
      xArr = ["9C61", "2", "RdpEs3jOLCH", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9C61", "3", "RdpEs3jOLCH", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Colour blindness
      xArr = ["9D44", "2", "zWK9OO0pMaM", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9D44", "3", "zWK9OO0pMaM", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Exophthalmos
      xArr = ["9A20.00", "2", "SzcyHRm0seg", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9A20.00", "3", "SzcyHRm0seg", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Stye(External Hordelum)
      xArr = ["9A01.20", "2", "K1Vggqh7EZL", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9A01.20", "3", "K1Vggqh7EZL", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Chalazion
      xArr = ["9A02.01", "2", "NukRpHU2mcF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9A02.01", "3", "NukRpHU2mcF", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Pterygium
      xArr = ["9A61.1", "2", "Bq8dxhxEmcI", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9A61.1", "3", "Bq8dxhxEmcI", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Diabetic retinopathy
      xArr = ["9B71.0", "2", "sMRPKqciSdG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9B71.0", "3", "sMRPKqciSdG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hypertensive retinopathy
      xArr = ["9B71.1", "2", "lNtBCvtTxhy", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9B71.1", "3", "lNtBCvtTxhy", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Entropion
      xArr = ["9A03.1", "2", "b1YXlOITj25", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9A03.1", "3", "b1YXlOITj25", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Traumatic eye disease
      xArr = ["NA06", "2", "tnm6bH7SuJ2", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NA06", "3", "tnm6bH7SuJ2", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Uveitis
      xArr = ["9A96", "2", "mvm8Z3wTFmT", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9A96", "3", "mvm8Z3wTFmT", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Macular degeneration(age related)
      xArr = ["9B78.3", "2", "dHT1BRQHShX", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9B78.3", "3", "dHT1BRQHShX", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Amblyopia(Lazy eye)
      xArr = ["9D46", "2", "KBoL28KAp3v", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9D46", "3", "KBoL28KAp3v", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Squint
      xArr = ["9C8Y", "2", "LPL3KuAFTFb", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9C8Y", "3", "LPL3KuAFTFb", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Retinitis pigmentosa
      xArr = ["9B70", "2", "pLdnHZ6QHyu", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9B70", "3", "pLdnHZ6QHyu", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Nightblindness / visual disturbance
      xArr = ["MC1Y", "2", "Myk6XIoYftg", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MC1Y", "3", "Myk6XIoYftg", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Retinoblastoma
      xArr = ["2D02.2", "2", "jjYff5pdoVS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2D02.2", "3", "jjYff5pdoVS", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Red Eye
      xArr = ["MC15", "2", "n0shLXzsRei", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MC15", "3", "n0shLXzsRei", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Blepharitis
      xArr = ["9A01.3", "2", "q8avBkQYnRz", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9A01.3", "3", "q8avBkQYnRz", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Neonatal Conjunctivitis(NEOS)
      xArr = ["KA65.0", "2", "et9kurthKJ4", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["KA65.0", "3", "et9kurthKJ4", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Obstetrics Complications" Then
      ' Ectopic Pregnancy
      xArr = ["JA01", "2", "l9K5FDX0TzP", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Abortion Complication
      xArr = ["A05.2", "2", "l2WtbkagDEQ", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Pregnancy Induced Hypertension(PIH)
      xArr = ["JA23", "2", "x6rCNsx0k94", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Severe / Pre - eclampsia
      xArr = ["JA24.1", "2", "EELNfz1YCZv", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Antepartum Eclampsia
      xArr = ["JA25.0", "2", "SQNwhuIWZnE", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Intrapartum Eclampsia
      xArr = ["JA25.1", "2", "AR2PUdMddYz", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Postpartum Eclampsia
      xArr = ["JA25.2", "2", "kdWPXAMCv2N", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Hyperemesis Grivadarum
      xArr = ["JA60.0", "2", "jdMSjAAFrsr", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Antepartum Haemorrhage
      xArr = ["JA41", "2", "PJklaKiPahr", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Prolonged labour
      xArr = ["JB03", "2", "wOcRtQidQ51", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Obstructed Labor
      xArr = ["JB06", "2", "tYjWPArxgfm", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Ruptured Uterus
      xArr = ["JB0A.1", "2", "CMTTYvszId4", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Postpartum Haemorrhage
      xArr = ["JA43", "2", "tKnSyC5j6yR", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Retained Placenta
      xArr = ["JA43.0", "2", "klPzarmP4i5", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Other Complications Of labor and delivery
      xArr = ["JB0D", "2", "DHYZJyfhw1s", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Pueperal Sepsis
      xArr = ["JB40.0", "2", "daRv0ld07Hm", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Gynaecological Problems" Then
      ' Pelvic Inflammatory Disease(PID)
      xArr = ["GA05", "2", "ZcI2ieytA1s", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Prolapsed uterus
      xArr = ["GC40", "2", "ldgv9ph2mBj", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Menstrual disorder
      xArr = ["GA20", "2", "eVXV442upyV", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Disfunctional Uterine Bleeding(DUB)
      xArr = ["GA2Y", "2", "KRiv3u1UVbQ", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Sub -fertility(Female)
      xArr = ["GA31", "2", "bQBY0ZM3U1Q", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Sub -fertility / infertility(Male)
      xArr = ["GB04", "3", "fCv76CsoGVC", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Mental Health related problems" Then
      ' Dementia
      xArr = ["6D8Z", "2", "bPqpAal7GQR", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6D8Z", "3", "bPqpAal7GQR", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Addiction(ch.acoholisim, Dipsomania, drug)
      xArr = ["6C40.2", "2", "YZoJchLc66y", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6C40.2", "3", "YZoJchLc66y", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Schizophrenia
      xArr = ["6A20", "2", "VY580eVaGXw", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6A20", "3", "VY580eVaGXw", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute psychotic disorder
      xArr = ["6A23", "2", "gZf4PtuvTuB", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6A23", "3", "gZf4PtuvTuB", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Bipolar affective disorder
      xArr = ["6A60.1", "2", "wpE1UaVVdRB", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6A60.1", "3", "wpE1UaVVdRB", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Depression
      xArr = ["6A7Z", "2", "Dj1nN42wiMd", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6A7Z", "3", "Dj1nN42wiMd", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Phobic Anxiety
      xArr = ["6B0Z", "2", "m09EZ409OyU", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6B0Z", "3", "m09EZ409OyU", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Pyschosis
      xArr = ["6A22", "2", "AItZIQeritY", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6A22", "3", "AItZIQeritY", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Obsessive - compulsive disorder
      xArr = ["6A22", "2", "pmLQfrfxRGP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6A22", "3", "pmLQfrfxRGP", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Conversive disorder(Hysteria)
      xArr = ["6B60", "2", "HEHjpjSkufl", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6B60", "3", "HEHjpjSkufl", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Neurosis
      xArr = ["6B00", "2", "XsxNnzlF1BX", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6B00", "3", "XsxNnzlF1BX", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Intellectual Disability
      xArr = ["6A00", "2", "HgbiECMw5b0", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6A00", "3", "HgbiECMw5b0", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Epilepsy
      xArr = ["8A6Z", "2", "pGgj6Uir7IQ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["8A6Z", "3", "pGgj6Uir7IQ", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Migraine
      xArr = ["8A80", "2", "qJ4iFmazTlj", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["8A80", "3", "qJ4iFmazTlj", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Mental illness(unspecified)
      xArr = ["6E8Z", "2", "WVh4R6WYimN", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6E8Z", "3", "WVh4R6WYimN", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Anxiety Disorder
      xArr = ["MB24.3", "2", "PuUh7b5KUMg", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MB24.3", "3", "PuUh7b5KUMg", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Alcohol Use Disorder
      xArr = ["6C40", "2", "HLPy8f80TG9", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6C40", "3", "HLPy8f80TG9", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Substance Use Disorder
      xArr = ["6C4Z", "2", "pGIog18uNHE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6C4Z", "3", "pGIog18uNHE", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Malignancy" Then
      ' Breast cancer
      xArr = ["2C6Z", "2", "foBSqZVlQqZ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2C6Z", "3", "foBSqZVlQqZ", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Cervical / uterine cancer
      xArr = ["2C77", "2", "KaHd1xBHBfO", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2C77", "3", "KaHd1xBHBfO", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Lung / brunchial Cancer
      xArr = ["2C25", "2", "FvUsjP01G6w", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2C25", "3", "FvUsjP01G6w", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Oesophagus cancer
      xArr = ["2B70", "2", "wzTTSKR3JgH", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2B70", "3", "wzTTSKR3JgH", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Stomach cancer
      xArr = ["2B72", "2", "CHDJ7eiK26X", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2B72", "3", "CHDJ7eiK26X", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Thyroid cancer
      xArr = ["2D10", "2", "qA53nDCEOgt", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2D10", "3", "qA53nDCEOgt", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Liver cancer
      xArr = ["2C12.0", "2", "Bj8m5N2pTT4", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2C12.0", "3", "Bj8m5N2pTT4", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Pancreatic cancer
      xArr = ["2C10", "2", "Ls6DBELhucD", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2C10", "3", "Ls6DBELhucD", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Bone / Bone Marrow Cancer
      xArr = ["2E03", "2", "RVhyQYMBoTs", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2E03", "3", "RVhyQYMBoTs", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Gall bladder cancer
      xArr = ["2C13", "2", "cWN72D91wWx", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2C13", "3", "cWN72D91wWx", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Colorectal(colon With rectum)cancer
      xArr = ["2B91", "2", "PYQPAx2s3On", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2B91", "3", "PYQPAx2s3On", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Oral cancer
      xArr = ["2B6E", "2", "KkV2jvCCISU", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2B6E", "3", "KkV2jvCCISU", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Lymphoma cancer
      xArr = ["2B33.5", "2", "KVZxc94qbg0", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2B33.5", "3", "KVZxc94qbg0", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Ovary cancer
      xArr = ["2C73", "2", "rorMnL90qUo", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2C73", "3", "rorMnL90qUo", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Urinary bladder cancer
      xArr = ["2C94", "2", "XeLKZHIMpSb", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2C94", "3", "XeLKZHIMpSb", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Nasopharyngeal cancer
      xArr = ["2B6B", "2", "g8lF7Um9jQA", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2B6B", "3", "g8lF7Um9jQA", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Head & neck cancer
      xArr = ["2C4Z", "2", "CFfXxPrIx8E", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2C4Z", "3", "CFfXxPrIx8E", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Other Cancer
      xArr = ["2D4Z", "2", "sO9oFKB9IAJ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2D4Z", "3", "sO9oFKB9IAJ", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hematological malignancy
      xArr = ["2B33", "2", "Tcq1b4uRLTl", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["2B33", "3", "Tcq1b4uRLTl", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Cardiovascular & Respiratory Related Problems" Then
      ' Hypertension
      xArr = ["BA00", "2", "qrqs5BcXz4K", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["BA00", "3", "qrqs5BcXz4K", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Congestive heart failure
      xArr = ["BD10", "2", "JNDXvvL6e73", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["BD10", "3", "JNDXvvL6e73", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Cardiac heart failure
      xArr = ["BD1Z", "2", "CAgq78eCGoT", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["BD1Z", "3", "CAgq78eCGoT", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Chronic Obstructive Pulmonary Disease(COPD)
      xArr = ["CA22", "2", "nGRapIBn04F", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA22", "3", "nGRapIBn04F", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute rheumatic fever
      xArr = ["1B40", "2", "bWTc0CtkExj", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1B40", "3", "bWTc0CtkExj", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Rheumatic heart disease(RHD)
      xArr = ["BC20.1", "2", "wYzKSWInjSq", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["BC20.1", "3", "wYzKSWInjSq", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Ischemic heart disease
      xArr = ["BA6Z", "2", "S4wji3QBoDj", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["BA6Z", "3", "S4wji3QBoDj", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Other cardiovascular problems
      xArr = ["BE2Y", "2", "qtjVLLOPJMq", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["BE2Y", "3", "qtjVLLOPJMq", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Bronchial asthma
      xArr = ["CA23.32", "2", "aeNEz2w7vUt", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA23.32", "3", "aeNEz2w7vUt", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Other Diseases & Injuries" Then
      ' Acute Renal failure
      xArr = ["GB60", "2", "CDE0GWEcSai", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["GB60", "3", "CDE0GWEcSai", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Chronic Renal failure
      xArr = ["GB61", "2", "r3sO6KWErru", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["GB61", "3", "r3sO6KWErru", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Nephritis
      xArr = ["GB40", "2", "LgjEP3jIXsd", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["GB40", "3", "LgjEP3jIXsd", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Nephrotic syndrome
      xArr = ["GB40", "2", "F9nektGalvQ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["GB40", "3", "F9nektGalvQ", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Drowning
      xArr = ["PA9Z", "2", "EH7DUl0MrEX", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["PA9Z", "3", "EH7DUl0MrEX", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Pyrexia Of Unknown Origin(PUO)
      xArr = ["MG26", "2", "uuMnXAm0kdm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MG26", "3", "uuMnXAm0kdm", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Gastritis(APD)
      xArr = ["DA42", "2", "PeTGehwYB0s", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA42", "3", "PeTGehwYB0s", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Insect / Wasp bite
      xArr = ["PA75", "2", "AfuEmTogPN2", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["PA75", "3", "AfuEmTogPN2", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Cut Injuries
      xArr = ["ND56", "2", "YtPBGWCccw7", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ND56", "3", "YtPBGWCccw7", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Cirrhosis Of liver
      xArr = ["DB93.1", "2", "QXFsxDNzIa3", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DB93.1", "3", "QXFsxDNzIa3", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Burns and Scalds
      xArr = ["NE2Z", "2", "LFBNWB6AEAS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NE2Z", "3", "LFBNWB6AEAS", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Toxic Effect
      xArr = ["NE60", "2", "OqXKbJoicMI", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NE60", "3", "OqXKbJoicMI", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' ' Dog Bite
      ' xArr = ["PA7Z", "2", "hlijidCZeXC", "ye1QuAMRG5Z"]
      ' aVar.Add(xArr)
      ' xArr = ["PA7Z", "3", "hlijidCZeXC", "PflKpozpO7b"]
      ' aVar.Add(xArr)

      ' Other rabies susceptible animal bite
      xArr = ["1C82", "2", "OD3nX0vpeRk", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1C82", "3", "OD3nX0vpeRk", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Snake bite: Poisonous
      xArr = ["PA7Z", "2", "ZK7kbGKuFhH", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["PA7Z", "3", "ZK7kbGKuFhH", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' ' Snake bite: Non - poisonous
      ' xArr = ["PA7Z", "2", "SdnBnsRltSh", "ye1QuAMRG5Z"]
      ' aVar.Add(xArr)
      ' xArr = ["PA7Z", "3", "SdnBnsRltSh", "PflKpozpO7b"]
      ' aVar.Add(xArr)

    Else If sCategory = "Orthopaedic Problems" Then
      ' Rheumatoid arthritis
      xArr = ["FA20", "2", "NNlu3dspuAb", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["FA20", "3", "NNlu3dspuAb", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Arthritis
      xArr = ["FA2Z", "2", "f14blP528FG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["FA2Z", "3", "f14blP528FG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Osteo arthrosis
      xArr = ["FA0Z", "2", "zcqze4wzYJf", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["FA0Z", "3", "zcqze4wzYJf", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Back ache(musculo - skeletal pain)
      xArr = ["ME84", "2", "PABYQLhP6kF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ME84", "3", "PABYQLhP6kF", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Lower Back Pain(LBP)
      xArr = ["ME84.2", "2", "ndIndgtn4VV", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ME84.2", "3", "ndIndgtn4VV", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Lower Back Pain(LBP)chronic
      xArr = ["MG30.02", "2", "P4Q4WLZE5Uw", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MG30.02", "3", "P4Q4WLZE5Uw", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Fractures
      xArr = ["ND56.2", "2", "F1uuffMUyFH", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ND56.2", "3", "F1uuffMUyFH", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Tendonitis
      xArr = ["FB55.Z", "2", "kRcki0HPrzK", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["FB55.Z", "3", "kRcki0HPrzK", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Ligamentous Sprain
      xArr = ["ND56.3", "2", "wwNnQiK9BL5", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ND56.3", "3", "wwNnQiK9BL5", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Neck Pain
      xArr = ["ME84.0", "2", "bLwEmxj2RiC", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ME84.0", "3", "bLwEmxj2RiC", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Joint Stiffness
      xArr = ["ME85", "2", "cunBHt0wvUr", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ME85", "3", "cunBHt0wvUr", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Spondylosis
      xArr = ["FA8Z", "2", "tNijzaDiPQq", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["FA8Z", "3", "tNijzaDiPQq", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Spondylolisthesis
      xArr = ["FA84.Z", "2", "GG6K9THTEw4", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["FA84.Z", "3", "GG6K9THTEw4", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Surgical Problems" Then
      ' Acid peptic disorders(disease)
      xArr = ["DA41.2", "2", "YCXYzdxUeum", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA41.2", "3", "YCXYzdxUeum", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Anal Fissure
      xArr = ["DB50.0", "2", "jdsiabr6R8B", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DB50.0", "3", "jdsiabr6R8B", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Anal fistula
      xArr = ["DB50.1", "2", "INV87zUyfus", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DB50.1", "3", "INV87zUyfus", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Fistula Of Intestine
      xArr = ["DB31.0", "2", "OJRkVtEJZJA", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DB31.0", "3", "OJRkVtEJZJA", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Renal stones
      xArr = ["GB70.0Z", "2", "sOXBvbQfg3k", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["GB70.0Z", "3", "sOXBvbQfg3k", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Breast lumps(Adenoma)
      xArr = ["MF30", "2", "iiJsrZe0bNk", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MF30", "3", "iiJsrZe0bNk", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Mastitis(Ignored breast) / breast abscess
      xArr = ["GB21.Z", "2", "fi0vtzIViQE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["GB21.Z", "3", "fi0vtzIViQE", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Mastalgia breast
      xArr = ["GB23.5", "2", "asmWrHpopvG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["GB23.5", "3", "asmWrHpopvG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Lumps(lipoma)
      xArr = ["ME61", "2", "ba2N6S0Nqdb", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ME61", "3", "ba2N6S0Nqdb", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Sebaceous cyst
      xArr = ["EK70.0Z", "2", "ctGjkbCRtZn", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["EK70.0Z", "3", "ctGjkbCRtZn", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Pilonidal sinus
      xArr = ["EG63.0", "2", "ZhUGMCZfdWb", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["EG63.0", "3", "ZhUGMCZfdWb", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Appendicitis
      xArr = ["DB10.Z", "2", "NM4bzwrsgs0", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DB10.Z", "3", "NM4bzwrsgs0", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Cholecystitis
      xArr = ["DC12.Z", "2", "QxEgmIN7OQM", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DC12.Z", "3", "QxEgmIN7OQM", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Cholelithiasis(gall stone)
      xArr = ["DC11.Z", "2", "A6x6SS5Dgds", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DC11.Z", "3", "A6x6SS5Dgds", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hernia
      xArr = ["DD5Z", "2", "Wtjpt7S9YQG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DD5Z", "3", "Wtjpt7S9YQG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hydrocoele
      xArr = ["GB00.Z", "2", "y0eNCU4p6nf", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["GB00.Z", "3", "y0eNCU4p6nf", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Phimosis / para - phimosis
      xArr = ["GB05.2", "2", "DEtuUddCtlE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["GB05.2", "3", "DEtuUddCtlE", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Haemorrhoids / Piles
      xArr = ["DB60.Z", "2", "WEEGs3oAxHz", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DB60.Z", "3", "WEEGs3oAxHz", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Epididymitis / Orchitis
      xArr = ["GB02.1", "2", "so2s568hmR9", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["GB02.1", "3", "so2s568hmR9", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Prostatism(BEP / BPH)
      xArr = ["GA90", "2", "Y5tTcY8S6tG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["GA90", "3", "Y5tTcY8S6tG", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Reasons for Contact with Health Services" Then
      ' General Examination
      xArr = ["QA00", "2", "hhF8unbGDvH", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["QA00", "3", "hhF8unbGDvH", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Routine general health checkup
      xArr = ["QA03", "2", "kLzqhClFOUj", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["QA03", "3", "kLzqhClFOUj", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Screeing Examination For infectious disease
      xArr = ["QA08", "2", "ZS5BWPoUc3V", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["QA08", "3", "ZS5BWPoUc3V", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Screening Examination For Neoplasms
      xArr = ["QA09", "2", "Mz2N95C2GBd", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["QA09", "3", "Mz2N95C2GBd", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Counseling
      xArr = ["QA1Z", "2", "SFvtAwxOQzC", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["QA1Z", "3", "SFvtAwxOQzC", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Reason Associated With Reproduction
      xArr = ["QA21.Z", "2", "HxrrbsAqyeK", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["QA21.Z", "3", "HxrrbsAqyeK", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Procreative management
      xArr = ["QA3Z", "2", "ItL1KGvUFOC", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["QA3Z", "3", "ItL1KGvUFOC", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Pregnancy Examination
      xArr = ["QA40", "2", "EKSttMk1htc", "ye1QuAMRG5Z"]
      aVar.Add(xArr)

      ' Antenatal Screening
      xArr = ["QA45", "2", "YUtWzAMSciZ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)

      ' Postpartum care Or Examination
      xArr = ["QA48", "2", "lnn6QJPjLq5", "ye1QuAMRG5Z"]
      aVar.Add(xArr)

      ' Problems related To unwanted pregnancy
      xArr = ["QA49", "2", "iHtPpjk8dlR", "ye1QuAMRG5Z"]
      aVar.Add(xArr)

      ' Menopausal Counselling
      xArr = ["QA4B", "2", "RpYKV3jN4eI", "ye1QuAMRG5Z"]
      aVar.Add(xArr)

      ' Blood donor
      xArr = ["QB20", "2", "gJSwP9t4uVU", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["QB20", "3", "gJSwP9t4uVU", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Follow up care invoving plastic surgery
      xArr = ["QB83", "2", "sKqfojmFULI", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["QB83", "3", "sKqfojmFULI", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Care invoving Dialysis
      xArr = ["QB94", "2", "a4UjEBXaRAI", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["QB94", "3", "a4UjEBXaRAI", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Care involvivg Rehabilitation procedures
      xArr = ["QB95", "2", "iNbL2YKjJt2", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["QB95", "3", "iNbL2YKjJt2", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Radiotherapy session
      xArr = ["QB96", "2", "pBfeHDJGUkc", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["QB96", "3", "pBfeHDJGUkc", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Chemotherapy session
      xArr = ["QB97", "2", "rh0J7pvRf7l", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["QB97", "3", "rh0J7pvRf7l", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Palliative care
      xArr = ["QB9B", "2", "mrQlLZbA6wB", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["QB9B", "3", "mrQlLZbA6wB", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acquired absence Of body structure
      xArr = ["QF0Z", "2", "kII60figzgN", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["QF0Z", "3", "kII60figzgN", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Common Symptoms" Then
      ' General Consideration On Pain
      xArr = ["MG3Z", "2", "mFJzub2Qp4X", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MG3Z", "3", "mFJzub2Qp4X", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Chest Pain
      xArr = ["MD30", "2", "TNqiG1Sdg2l", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MD30", "3", "TNqiG1Sdg2l", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Breathlessness / Shortness Of Breath
      xArr = ["MD11.5", "2", "QrRDFVy1Mjy", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MD11.5", "3", "QrRDFVy1Mjy", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Cough
      xArr = ["MD12", "2", "hpZ3dxdi8ec", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MD12", "3", "hpZ3dxdi8ec", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Abdominal Pain
      xArr = ["MD81", "2", "gCBjGGyu3Ob", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MD81", "3", "gCBjGGyu3Ob", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Nause and Vomiting
      xArr = ["MD90.1", "2", "iURsh4W0Wxp", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MD90.1", "3", "iURsh4W0Wxp", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Headache
      xArr = ["MB4D", "2", "STQAKvx4hrd", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MB4D", "3", "STQAKvx4hrd", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Fever
      xArr = ["MG26", "2", "AhFweT7BqD9", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MG26", "3", "AhFweT7BqD9", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Dizziness and Vertiligo
      xArr = ["MB48.0", "2", "HIS1nrVKXig", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MB48.0", "3", "HIS1nrVKXig", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Syncope(Sudden Collapse Or LOC)
      xArr = ["MG45", "2", "B5cvXBhXIgG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MG45", "3", "B5cvXBhXIgG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Itching(Pruritus)
      xArr = ["EC90.0", "2", "N3MRYiUHzil", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["EC90.0", "3", "N3MRYiUHzil", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Fatigue and Weakness(Generalized)
      xArr = ["MG22", "2", "bexWnaEedW6", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MG22", "3", "bexWnaEedW6", "PflKpozpO7b"]
      aVar.Add(xArr)

    Endif

    ' GetNewEmerMorbidity(sCategory)
  Else If sChapter = "Common Emergency Diseases" Then
    If sCategory = "Respiratory Emergencies" Then
      ' Shorthness Of breath
      xArr = ["MD11.5", "2", "t45npJnyYX2", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MD11.5", "3", "t45npJnyYX2", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute exacerbation Of (COPD)
      xArr = ["CA22.0", "2", "eHBGSTdPE2w", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA22.0", "3", "eHBGSTdPE2w", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Bronchial Asthma
      xArr = ["CA23.32", "2", "XUu6HJdPhwx", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA23.32", "3", "XUu6HJdPhwx", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Pneumonia
      xArr = ["CA40", "2", "XiFS1e4yOtf", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA40", "3", "XiFS1e4yOtf", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Aspiration Pneumonia
      xArr = ["CA71.0", "2", "j0MQKLYOrfa", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA71.0", "3", "j0MQKLYOrfa", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Pneumothorax
      xArr = ["CB21", "2", "ONcZ3jTM7yE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CB21", "3", "ONcZ3jTM7yE", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hemoptysis
      xArr = ["MD22", "2", "W1RDyPX4ToH", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MD22", "3", "W1RDyPX4ToH", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Pulmonary Embolism
      xArr = ["BB00.0", "2", "zCxndEx1c83", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["BB00.0", "3", "zCxndEx1c83", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Mountain Sickness
      xArr = ["NF04", "2", "VCE42jTyous", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NF04", "3", "VCE42jTyous", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' High Altitude Pulmonary Edema(HAPE)
      xArr = ["CA81.1", "2", "RWTnrQMZHVV", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA81.1", "3", "RWTnrQMZHVV", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' High Altitude Cerebral Edema(HACE)
      xArr = ["8D60.1", "2", "M2N83f5QFwU", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["8D60.1", "3", "M2N83f5QFwU", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Respiratory Failure
      xArr = ["CB41.0", "2", "fuiRUiXeO6f", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CB41.0", "3", "fuiRUiXeO6f", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Respiratory Distress Syndrome
      xArr = ["CB00", "2", "NZwTVptsIQj", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CB00", "3", "NZwTVptsIQj", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Cardiac Emergencies" Then
      ' Chest pain
      xArr = ["MD30", "2", "TNqiG1Sdg2l", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MD30", "3", "TNqiG1Sdg2l", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Coronary Syndrome
      xArr = ["BA4Z", "2", "GChE6m7LCZm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["BA4Z", "3", "GChE6m7LCZm", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Myocardial Infraction
      xArr = ["BA41", "2", "jDRgN1HlxCe", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["BA41", "3", "jDRgN1HlxCe", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Arrhythmias - tachyarrhythmias and bradyarrhythmias
      xArr = ["BC9Z", "2", "diRnln2aCIs", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["BC9Z", "3", "diRnln2aCIs", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Actute Pulmonary Edema
      xArr = ["CB01", "2", "Cji0IzSoKhP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CB01", "3", "Cji0IzSoKhP", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Cardiac Tamponade
      xArr = ["BB23", "2", "nOhQbvKprC9", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["BB23", "3", "nOhQbvKprC9", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Cardiogenic Shock
      xArr = ["MG40.0", "2", "HZ5ocPfFbJW", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MG40.0", "3", "HZ5ocPfFbJW", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hypertensive Emergencies
      xArr = ["BA03", "2", "JwxymjIkm6v", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["BA03", "3", "JwxymjIkm6v", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Neurological Emergencies" Then
      ' Coma
      xArr = ["MB20.1", "2", "GevxHU0NL2d", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MB20.1", "3", "GevxHU0NL2d", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Seizures
      xArr = ["8A68", "2", "PjCZw3W1zbq", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["8A68", "3", "PjCZw3W1zbq", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute CNS Infections
      xArr = ["1D0Z", "2", "UU28JEw0H2e", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1D0Z", "3", "UU28JEw0H2e", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Cerebrovascular Accidents
      xArr = ["8B20", "2", "IoXxOcitIRc", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["8B20", "3", "IoXxOcitIRc", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Guillain - Barre Syndrome(GBS)
      xArr = ["8C01.0", "2", "YbnHdT5Yw3w", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["8C01.0", "3", "YbnHdT5Yw3w", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Raised Intracranial Pressure
      xArr = ["8D60", "2", "u8fYTWeCXkq", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["8D60", "3", "u8fYTWeCXkq", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Gastrointestinal Emergencies" Then
      ' Abdominal pain
      xArr = ["MD81", "2", "cKxi5aUr8a6", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MD81", "3", "cKxi5aUr8a6", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Gastritis
      xArr = ["DA42", "2", "B98JFyVJ1hl", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA42", "3", "B98JFyVJ1hl", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Gastroenteritis
      xArr = ["1A40", "2", "PVzhMRtg9Tq", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1A40", "3", "PVzhMRtg9Tq", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Appendicitis
      xArr = ["DB10.0", "2", "rdrfbkRbj2Z", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DB10.0", "3", "rdrfbkRbj2Z", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Cholecystitis
      xArr = ["DC12.0", "2", "IdF3pSxp1Ve", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DC12.0", "3", "IdF3pSxp1Ve", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Gastrointestinal Bleeding(GIB)
      xArr = ["ME24.9", "2", "P3NvntLjiDQ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ME24.9", "3", "P3NvntLjiDQ", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Fulminant Hepatic Failure
      xArr = ["DB91", "2", "N0qTOjQ5svi", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DB91", "3", "N0qTOjQ5svi", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Pancreatitis
      xArr = ["DC31", "2", "kxR6s54etIp", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DC31", "3", "kxR6s54etIp", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Strangulated / Obstructed Herina
      xArr = ["DB50.0", "2", "k9rd8jW3kNF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DB50.0", "3", "k9rd8jW3kNF", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Intestinal Obstrucction
      xArr = ["DB30", "2", "JYTPYn4m6YB", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DB30", "3", "JYTPYn4m6YB", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hallow Viscus Perforation
      xArr = ["ME24.3", "2", "Nr64hBBHZx2", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ME24.3", "3", "Nr64hBBHZx2", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Peritonitis
      xArr = ["DC50", "2", "daEVQbCUq6k", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DC50", "3", "daEVQbCUq6k", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Genitourinary Emergencies" Then
      ' Renal Colic
      xArr = ["MF56", "2", "WoURwvcjfiG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MF56", "3", "WoURwvcjfiG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hematuria
      xArr = ["MF50.4", "2", "wX3ZzwT8MGN", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MF50.4", "3", "wX3ZzwT8MGN", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Actute Retention Of Urine
      xArr = ["MF50.3", "2", "uu9fuezz2MR", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MF50.3", "3", "uu9fuezz2MR", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Testicular Torsion
      xArr = ["GB01.0", "2", "xo4bR7UE9cK", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["GB01.0", "3", "xo4bR7UE9cK", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Paraphimosis
      xArr = ["GB05.3", "2", "ne7bITs5K1E", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["GB05.3", "3", "ne7bITs5K1E", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Gynecology and Obstetrical Emergencies" Then
      ' Ectopic Pregnancy
      xArr = ["JA01", "2", "Ft8hOM1zsVY", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Antepartum Haemorrhage
      xArr = ["JA41", "2", "J4n594HErwp", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Ruptured Uterus
      xArr = ["JB0A.1", "2", "TnTpN2z1B8H", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Pregnancy Induced Hypertension(PIH)
      xArr = ["JA23", "2", "GyhhcDPlJMX", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Obstructed Labour
      xArr = ["JB06", "2", "h38nCS7pLJH", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Postpartum Haemorrhage
      xArr = ["JA43", "2", "wgpVLyhGgog", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Puerperal pyrexia
      xArr = ["JB40.0", "2", "ZySlIot5f9f", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ' Hypermesis Gravidraum
      xArr = ["JA60.0", "2", "g86Ku1XdewY", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Orthopaedic & Trauma" Then
      ' Head Injury
      xArr = ["NA0Z", "2", "AXUQqXfqF6g", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NA0Z", "3", "AXUQqXfqF6g", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Abdominal and pelvic Injury
      xArr = ["NB9Z", "2", "PUmhBUquDyF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NB9Z", "3", "PUmhBUquDyF", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Chest Injuries
      xArr = ["NB3Z", "2", "w5RP2Dxn56b", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NB3Z", "3", "w5RP2Dxn56b", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Muskuloskeletal Injuries
      xArr = ["ND56", "2", "XaXmjYTxrQP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ND56", "3", "XaXmjYTxrQP", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Compartment Syndrome
      xArr = ["NF0A.6", "2", "tDaQtZ3cPY5", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NF0A.6", "3", "tDaQtZ3cPY5", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Traumatic amputation
      xArr = ["ND56.8", "2", "jBflyH7hF3J", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ND56.8", "3", "jBflyH7hF3J", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Toothace / Odontalgia
      xArr = ["DA0Y", "2", "l7v7MsQS7lI", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["DA0Y", "3", "l7v7MsQS7lI", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Dental Fractures
      xArr = ["NA0D.02", "2", "brOAQlzPp3C", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NA0D.02", "3", "brOAQlzPp3C", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Temporomandibular joint(TMJ)Dislocation
      xArr = ["NA03.0", "2", "YWMDvNBlnNV", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NA03.0", "3", "YWMDvNBlnNV", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Gum Bleeding
      xArr = ["MD80", "2", "wLZKsKA0W3U", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MD80", "3", "wLZKsKA0W3U", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Metabolic Emergencies" Then
      ' Hypoklaemia
      xArr = ["5C77", "2", "sZawi4OObgG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5C77", "3", "sZawi4OObgG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hyperkalemia
      xArr = ["5C76", "2", "aW09FYrRhWG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5C76", "3", "aW09FYrRhWG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hyponatremia
      xArr = ["5C70.1", "2", "m7QS7b88Ml5", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5C70.1", "3", "m7QS7b88Ml5", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hypernatremia
      xArr = ["5C71", "2", "CKH2nJjIwUv", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5C71", "3", "CKH2nJjIwUv", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Hypoglycemia
      xArr = ["5A41", "2", "r6BZqMWAj5P", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5A41", "3", "r6BZqMWAj5P", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Diabetic Ketoacidosis(DKA)
      xArr = ["5A22.0", "2", "v8sbkORRmzD", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5A22.0", "3", "v8sbkORRmzD", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Adrenal Crisis
      xArr = ["5A74.1", "2", "JZnqrEEDK9Z", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5A74.1", "3", "JZnqrEEDK9Z", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Ocular Emergencies" Then
      ' Foreign body Eye
      xArr = ["ND70", "2", "HON9NGyljcj", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ND70", "3", "HON9NGyljcj", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Sudden loss Of Vision
      xArr = ["9D5Y", "2", "mTcq0gzsvuS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["9D5Y", "3", "mTcq0gzsvuS", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Chemical Injuries
      xArr = ["ND99.1", "2", "Qyc2BP1TIA9", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["ND99.1", "3", "Qyc2BP1TIA9", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "ENT Emergencies" Then
      ' Epistaxis
      xArr = ["MD20", "2", "gI0wEWeSOqS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["MD20", "3", "gI0wEWeSOqS", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Foreign body ENT
      xArr = ["NA00.2", "2", "ABQSMFHm3pH", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NA00.2", "3", "ABQSMFHm3pH", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Burns" Then
      ' Thermal burns
      xArr = ["NE2Z", "2", "z15CIqNtu0U", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NE2Z", "3", "z15CIqNtu0U", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Electrical & Lightening Injuries
      xArr = ["NF08.0", "2", "JfAaF0VNFOy", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NF08.0", "3", "JfAaF0VNFOy", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Mental Health Emergencies" Then
      ' Alchohol intoxication
      xArr = ["6C40.3", "2", "pGnNUcKcxSk", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6C40.3", "3", "pGnNUcKcxSk", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Alchohol Use disorder
      xArr = ["6C40", "2", "g9LCpJSh9An", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6C40", "3", "g9LCpJSh9An", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Anxiety disorder
      xArr = ["6B00", "2", "M3TK38EoLvD", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6B00", "3", "M3TK38EoLvD", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Conversion Disorder
      xArr = ["6B60", "2", "MInojlnjzt1", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6B60", "3", "MInojlnjzt1", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Depression
      xArr = ["6A7Z", "2", "pbHYbi8QCbW", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6A7Z", "3", "pbHYbi8QCbW", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute psychosis
      xArr = ["6A23", "2", "lom6kA4Hp81", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["6A23", "3", "lom6kA4Hp81", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Toxicological Emergencies" Then
      ' Outline Of Poisoning
      xArr = ["NE60", "2", "B8ctEsO0mA1", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NE60", "3", "B8ctEsO0mA1", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Organophosphorus Poisoning(Rodenticides)
      xArr = ["PB33", "2", "Dwt3vDV8fza", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["PB33", "3", "Dwt3vDV8fza", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' ' Aluminium Phosphide
      ' xArr = ["NE60", "2", "M9mlptxOMcc", "ye1QuAMRG5Z"]
      ' aVar.Add(xArr)
      ' xArr = ["NE60", "3", "M9mlptxOMcc", "PflKpozpO7b"]
      ' aVar.Add(xArr)

      ' Mushroom Poisoning
      xArr = ["NE61", "2", "WNjiV82hleX", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NE61", "3", "WNjiV82hleX", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' ' Wild Honey Poisoning
      ' xArr = ["NE61", "2", "kd7YxRcbq1b", "ye1QuAMRG5Z"]
      ' aVar.Add(xArr)
      ' xArr = ["NE61", "3", "kd7YxRcbq1b", "PflKpozpO7b"]
      ' aVar.Add(xArr)
      '
      ' ' Dhatura Poisoning
      ' xArr = ["NE61", "2", "jp4yW6DCXKA", "ye1QuAMRG5Z"]
      ' aVar.Add(xArr)
      ' xArr = ["NE61", "3", "jp4yW6DCXKA", "PflKpozpO7b"]
      ' aVar.Add(xArr)

      ' Paracetamol Poisoning
      xArr = ["NE59", "2", "Ic0esMWSmnj", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["NE59", "3", "Ic0esMWSmnj", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' ' Antidotes
      ' xArr = ["NE60", "2", "KPYoTSr7Yt5", "ye1QuAMRG5Z"]
      ' aVar.Add(xArr)
      ' xArr = ["NE60", "3", "KPYoTSr7Yt5", "PflKpozpO7b"]
      ' aVar.Add(xArr)

    Else If sCategory = "Bite" Then
      ' Snake Bite
      xArr = ["PA7Z", "2", "pB5LKSelTht", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["PA7Z", "3", "pB5LKSelTht", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' ' Animal Bite
      ' xArr = ["PA7Z", "2", "WyIZXig6ZW8", "ye1QuAMRG5Z"]
      ' aVar.Add(xArr)
      ' xArr = ["PA7Z", "3", "WyIZXig6ZW8", "PflKpozpO7b"]
      ' aVar.Add(xArr)

      ' Rabies
      xArr = ["1C82", "2", "R2QzgRXuhmZ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1C82", "3", "R2QzgRXuhmZ", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' ' Insect Bite
      ' xArr = ["PA75", "2", "u2F0JZnfyg9", "ye1QuAMRG5Z"]
      ' aVar.Add(xArr)
      ' xArr = ["PA75", "3", "u2F0JZnfyg9", "PflKpozpO7b"]
      ' aVar.Add(xArr)

    Else If sCategory = "Paediatric Emergencies" Then
      ' Diarrhoea
      xArr = ["KB8C", "2", "FjZ4SAzhH3j", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["KB8C", "3", "FjZ4SAzhH3j", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute Respiratory Tract infection
      xArr = ["CA4Z", "2", "GvayS7w3TpL", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA4Z", "3", "GvayS7w3TpL", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Acute epiglottitis
      xArr = ["CA06.1", "2", "u4qLyDnsElq", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA06.1", "3", "u4qLyDnsElq", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Laryngitis & laryngotracheobrochitis
      xArr = ["CA05.0", "2", "N6RcJD3LtVq", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["CA05.0", "3", "N6RcJD3LtVq", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Pneumonia
      xArr = ["KB23", "2", "Ysq2YVFqY8O", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["KB23", "3", "Ysq2YVFqY8O", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' Febrile Convulsions
      xArr = ["KB06", "2", "LV3BrlQXzRP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["KB06", "3", "LV3BrlQXzRP", "PflKpozpO7b"]
      aVar.Add(xArr)

    Endif

  Else If sChapter = "Laboratory Services" Then
    If sCategory = "HAEMATOLOGY" Then
      '"HB",
      xArr = ["HB", "2", "MX5XthyOLIX", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"RBC Count",
      xArr = ["RBC Count", "2", "ga8cotZYUGN", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"TLC",
      xArr = ["TLC", "2", "udHP9cMdus0", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Platelets Count",
      xArr = ["Platelets Count", "2", "HkVFI7zvtco", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ' "DLC",
      xArr = ["DLC", "2", "Ks9ADEZCFQd", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"ESR",
      xArr = ["ESR", "2", "hcN0jcWCBLx", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"MCV",
      xArr = ["MCV", "2", "o6paypYS2tc", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"MCH",
      xArr = ["MCH", "2", "kTMrl2nmqdQ", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"MCHC",
      xArr = ["MCHC", "2", "mucJ3LkNOGi", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"RDW",
      xArr = ["RDW", "2", "jtq2eCYU4TI", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Blood Group & Rh Type",
      xArr = ["Blood Group & Rh Type", "2", "sgR3aHSyj0A", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Coombs test",
      xArr = ["Coombs test", "2", "V2rLFh947Xk", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Retics",
      xArr = ["Retics", "2", "XJcUhKfv6iG", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"PBS/PBF",
      xArr = ["PBS/PBF", "2", "IB7pwInGJ2Z", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"HbA1c",
      xArr = ["HbA1c", "2", "TPfANsOsI68", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Special Stain(MPO)",
      xArr = ["Special Stain(MPO)", "2", "JWcZvHhr1Wh", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Special Stain(PAS)",
      xArr = ["Special Stain(PAS)", "2", "JaZYiW0YaCW", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Sickling Test",
      xArr = ["Sickling Test", "2", "TWkqsR5UgVd", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Urine for Hemosiderin",
      xArr = ["Urine for Hemosiderin", "2", "KhBNHEeaRQ6", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"BT",
      xArr = ["BT", "2", "PEtNspPKfGU", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"CT",
      xArr = ["CT", "2", "VxCaWebcSNY", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"PT-INR",
      xArr = ["PT-INR", "2", "hvKJZhQvtlD", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"APTT",
      xArr = ["APTT", "2", "lQ3GQrEk9mB", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Bone Marrow Analysis",
      xArr = ["Bone Marrow Analysis", "2", "I8Z2E4Kmgii", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Aldehyde test",
      xArr = ["Aldehyde test", "2", "QPNEYl5SKm8", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"MP Total",
      xArr = ["MP Total", "2", "UX2IdkwZPm6", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Smear MP Pos(PF)",
      xArr = ["Smear MP Pos(PF)", "2", "nTOEK8miG0K", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Smear MP Pos(PV)",
      xArr = ["Smear MP Pos(PV)", "2", "LZPBP5dgWs0", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Smear MP Pos(P-MIX)",
      xArr = ["Smear MP Pos(P-MIX)", "2", "myzTAYlWVAc", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"MF",
      xArr = ["MF", "2", "r25JvgKGqwE", "kdsirVNKdhm"]  'total
      aVar.Add(xArr)
      xArr = ["MF", "1", "TVZ5CT66epd", "kdsirVNKdhm"]  ''positive
      aVar.Add(xArr)
      '"LD Bodies",
      xArr = ["LD Bodies", "2", "dkU2y8nxG0h", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Hb Electrophoresis",
      xArr = ["Hb Electrophoresis", "2", "F8v1z9J0lOg", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ' "LE cell",
      xArr = ["LE cell", "2", "RdQOc3LQLP7", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"ALC",
      xArr = ["ALC", "2", "MT1F817ybIC", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"AEF",
      xArr = ["AEF", "2", "VlnMWXp6Sqr", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"FDP",
      xArr = ["FDP", "2", "bwHADypDLFl", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"D-dimer",
      xArr = ["D-dimer", "2", "roqaipUwNjT", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Fac VIII",
      xArr = ["Fac VIII", "2", "vBnEHWgBcLR", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Fac IX",
      xArr = ["Fac IX", "2", "UK3UTayMDhQ", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Cross Matching",
      xArr = ["Cross Matching", "2", "FLukVmXHeQx", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Others"
      xArr = ["Others", "2", "ksFMz4c0I39", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "IMMUNOLOGY" Then
      '"Pregnancy Test (UPT)",
      xArr = ["Pregnancy Test (UPT)", "2", "R5coLEZO6gu", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"ASO",
      xArr = ["ASO", "2", "Bdh8yF2CdD8", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"CRP",
      xArr = ["CRP", "2", "biBCfb3VTLe", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"RA Factor",
      xArr = ["RA Factor", "2", "NHUktqhJjbE", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"TPHA",
      xArr = ["TPHA", "2", "KQGrcNYhocs", "A0ezJDD4TfL"]  ''total
      aVar.Add(xArr)
      xArr = ["TPHA", "1", "KQGrcNYhocs", "wCvNkhhbSbl"]  ''positive
      aVar.Add(xArr)
      '"ANA",
      xArr = ["ANA", "2", "nkd4WEiWYpm", "A0ezJDD4TfL"]
      aVar.Add(xArr)
      '"Anti-dsDNA",
      xArr = ["Anti-dsDNA", "2", "nOITz2nNxAs", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"PRPR/VDRL",
      xArr = ["PRPR/VDRL", "2", "llvGO9epm7O", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["PRPR/VDRL", "1", "mhrHV87Zc9U", "kdsirVNKdhm"]   ''positive
      aVar.Add(xArr)
      '"CEA",
      xArr = ["CEA", "2", "Chpshc4ebjM", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"CA-125",
      xArr = ["CA-125", "2", "gVibsIFUGKo", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"CA-19.9",
      xArr = ["CA-19.9", "2", "Y75eapME064", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"CA-15.3",
      xArr = ["CA-15.3", "2", "wt7S2uqK6K1", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Toxo",
      xArr = ["Toxo", "2", "vbl1CwVTr6v", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Rubella",
      xArr = ["Rubella", "2", "RBHRqI1plDF", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"CMV",
      xArr = ["CMV", "2", "kbaZJco7mAo", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"HSV",
      xArr = ["HSV", "2", "YEgSZqDWUNm", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Measles",
      xArr = ["Measles", "2", "SJZ1Uv3fXPn", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Echinococcus",
      xArr = ["Echinococcus", "2", "lv5WiRQ4EeS", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Amoebiasis",
      xArr = ["Amoebiasis", "2", "ZCoqqsa2dPi", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"PSA",
      xArr = ["PSA", "2", "U8KGjwMF8pn", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Ferritin",
      xArr = ["Ferritin", "2", "ZD0rMCtnrmu", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Cysticercosis",
      xArr = ["Cysticercosis", "2", "dRgsrcHnY6k", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Brucella",
      xArr = ["Brucella", "2", "lrfHXRRnECT", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Thyroglobulin",
      xArr = ["Thyroglobulin", "2", "uYVS9Y6WGGX", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Anti TPO",
      xArr = ["Anti TPO", "2", "nmdxncyFWLp", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Protein Electrophoresis",
      xArr = ["Protein Electrophoresis", "2", "ys3Z6SrXbl8", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Anti-CCP",
      xArr = ["Anti-CCP", "2", "hg6gptvIanY", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"RK-39",
      xArr = ["RK-39", "2", "Vjdjtgx1vez", "A0ezJDD4TfL"]
      aVar.Add(xArr)
      xArr = ["RK-39", "1", "Vjdjtgx1vez", "wCvNkhhbSbl"]   ''positive
      aVar.Add(xArr)
      '"JE",
      xArr = ["JE", "2", "zebx7lWQoyM", "A0ezJDD4TfL"]
      aVar.Add(xArr)
      xArr = ["JE", "1", "zebx7lWQoyM", "wCvNkhhbSbl"]   ''positive
      aVar.Add(xArr)
      '"Dengue",
      xArr = ["Dengue", "2", "ci7ny20DDx5", "A0ezJDD4TfL"]
      aVar.Add(xArr)
      xArr = ["Dengue", "1", "rXWBtyTUZQT", "kdsirVNKdhm"]   ''positive
      aVar.Add(xArr)
      '"Rapid MP test",
      xArr = ["Rapid MP test", "2", "FxeXI2YccuG", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Rapid MP test", "1", "B5ykil1xCD7", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Rapid MP test", "1", "uxXLme8h5rp", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Rapid MP test", "1", "pk65G1mjDRY", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Mantoux test",
      xArr = ["Mantoux test", "2", "iR2RIlfklv4", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Chikungunya",
      xArr = ["Chikungunya", "2", "mWOLG4uhHKF", "A0ezJDD4TfL"]
      aVar.Add(xArr)
      xArr = ["Chikungunya", "1", "mWOLG4uhHKF", "wCvNkhhbSbl"]   ''positive
      aVar.Add(xArr)
      '"Scrub Typhus",
      xArr = ["Scrub Typhus", "2", "IlNmTeeBikM", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"H. Pylori",
      xArr = ["H. Pylori", "2", "ruFgBQtcLeT", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Leptospira",
      xArr = ["Leptospira", "2", "ST5xRwmGRmQ", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Widal Test",
      xArr = ["Widal Test", "2", "czXIORFAbvx", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Others"]
      xArr = ["Others", "2", "qdCl7C4jfvE", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "BIOCHEMISTRY" Then
      '"Sugar",
      xArr = ["Sugar", "2", "GYgsh4jyQhD", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Blood Urea",
      xArr = ["Blood Urea", "2", "zEyNSH7f3bc", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Creatinine",
      xArr = ["Creatinine", "2", "EAej1kE1URL", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Sodium (Na)",
      xArr = ["Sodium (Na)", "2", "gCtmVdbe7SY", "kdsirVNKdhm"]
      aVar.Add(xArr)
      'Potassium (K)",
      xArr = ["Potassium (K)", "2", "KkBUEB0zQPc", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Calcium",
      xArr = ["Calcium", "2", "R5LM4KpJvod", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Phosphorus",
      xArr = ["Phosphorus", "2", "FNACMSYVtoH", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Magnesium",
      xArr = ["Magnesium", "2", "K1sYUht3jjV", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Uric acid",
      xArr = ["Uric acid", "2", "aZL9j6tqQ9p", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Total Cholesterol",
      xArr = ["Total Cholesterol", "2", "wulw5ifRsNe", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Triglycerides",
      xArr = ["Triglycerides", "2", "aSL8XQRSfQp", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"HDL",
      xArr = ["HDL", "2", "EDGJSDQRSBc", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"LDL",
      xArr = ["LDL", "2", "VXTX6a2cthA", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Amylase",
      xArr = ["Amylase", "2", "jnhUYbBZse7", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Micro albumin",
      xArr = ["Micro albumin", "2", "BdUuj8ytHYt", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Bilirubin",
      xArr = ["Bilirubin", "2", "APPyfaSy6hf", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"SGPT",
      xArr = ["SGPT", "2", "uk6zFeOqUKH", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Alk Phos",
      xArr = ["Alk Phos", "2", "iKAc48pZwIU", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"SGOT",
      xArr = ["SGOT", "2", "a0yIeDftBG7", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Total Protein",
      xArr = ["Total Protein", "2", "n5icJ65j8Q3", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Gamma GT",
      xArr = ["Gamma GT", "2", "FrhqMwAiYdj", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"24hr urine protein",
      xArr = ["24hr urine protein", "2", "C7eoJAFCH0M", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"24hr urine U/A",
      xArr = ["24hr urine U/A", "2", "zl0PSyO6WQx", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Creatinine Clearance",
      xArr = ["Creatinine Clearance", "2", "Wqf9ZelXBdQ", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Iron",
      xArr = ["Iron", "2", "ExnjpyTiZkk", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"TIBC",
      xArr = ["TIBC", "2", "w1CqsqkUyl8", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"CPK-MB",
      xArr = ["CPK-MB", "2", "i0ymcWrlIw3", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"CPK-NAC",
      xArr = ["CPK-NAC", "2", "Ikff1OUhABP", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"LDH",
      xArr = ["LDH", "2", "u1gdmCfIfGa", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Iso-Trop-I",
      xArr = ["Iso-Trop-I", "2", "oGlhaIup37P", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Others"]
      xArr = ["Others", "2", "RqSKEolefFR", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "BACTERIOLOGY" Then
      '"Gram stain",
      xArr = ["Gram stain", "2", "coBAbfppycX", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Culture (Blood)"
      xArr = ["Culture (Blood)", "2", "it4JusH87Wk", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Culture (Urine)"
      xArr = ["Culture (Urine)", "2", "sLACvSMlg2x", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Culture (Body Fluid)"
      xArr = ["Culture (Body Fluid)", "2", "xMXbKs6edeu", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Culture (Swab)"
      xArr = ["Culture (Swab)", "2", "MkoyR8apLNJ", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Culture (Stool)"
      xArr = ["Culture (Stool)", "2", "llI4WtU0scF", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Culture (Water)"
      xArr = ["Culture (Water)", "2", "mV5BSo4BMEk", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Culture (Pus)"
      xArr = ["Culture (Pus)", "2", "kp79HNscnxJ", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Culture (Sputum)"
      xArr = ["Culture (Sputum)", "2", "dXK9lQSnxrg", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Culture (CSF)"
      xArr = ["Culture (CSF)", "2", "gvv8uQaWTcW", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Culture (Others)"
      xArr = ["Culture (Others)", "2", "BcUCgFWFJBe", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Sputum AFB",
      xArr = ["Sputum AFB", "2", "iHLe8HKsB3K", "A0ezJDD4TfL"]
      aVar.Add(xArr)
      '"Other AFB",
      xArr = ["Other AFB", "2", "sgUz4KSpNIA", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Leprosy Smear",
      xArr = ["Leprosy Smear", "2", "Lruh22ELAGR", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"India Ink Test",
      xArr = ["India Ink Test", "2", "Av4WfkcxAQA", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Anaerobic Culture",
      xArr = ["Anaerobic Culture", "2", "HOAJkAvmzz4", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Fungus(KOH Test)",
      xArr = ["Fungus(KOH Test)", "2", "Ko8Z7R3PaN2", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Fungus(Culture)",
      xArr = ["Fungus(Culture)", "2", "KaPqUD0bWdd", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Others"]
      xArr = ["Others", "2", "VTEmZoEWvp1", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "VIROLOGY" Then
      '"HIV RDT",
      xArr = ["HIV RDT", "2", "HJpcsC6D0at", "A0ezJDD4TfL"]
      aVar.Add(xArr)
      xArr = ["HIV RDT", "1", "HJpcsC6D0at", "wCvNkhhbSbl"]
      aVar.Add(xArr)
      '"HBSAg RDT",
      xArr = ["HBSAg RDT", "2", "X8FtE4lSQYQ", "A0ezJDD4TfL"]
      aVar.Add(xArr)
      xArr = ["HBSAg RDT", "1", "X8FtE4lSQYQ", "wCvNkhhbSbl"]
      aVar.Add(xArr)
      '"HCV RDT",
      xArr = ["HCV RDT", "2", "AETUEJEkhGk", "A0ezJDD4TfL"]
      aVar.Add(xArr)
      xArr = ["HCV RDT", "1", "AETUEJEkhGk", "wCvNkhhbSbl"]
      aVar.Add(xArr)
      '"HIV ELISA/CLIA",
      xArr = ["HIV ELISA/CLIA", "2", "NkGOcGwTbsy", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["HIV ELISA/CLIA", "1", "pnHCOiMByVG", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"HAV ELISA/CLIA",
      xArr = ["HAV ELISA/CLIA", "2", "IgK9Nv2q8ay", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["HAV ELISA/CLIA", "1", "gh8PuXfYKGn", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"HBsAg ELISA/CLIA",
      xArr = ["HBsAg ELISA/CLIA", "2", "XyVUts5xSAc", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["HBsAg ELISA/CLIA", "1", "NWgPfhRvUBB", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"HCV ELISA/CLIA",
      xArr = ["HCV ELISA/CLIA", "2", "LaF7BzXQSKV", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["HCV ELISA/CLIA", "1", "GKiu4RclCUe", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"HEV ELISA/CLIA",
      xArr = ["HEV ELISA/CLIA", "2", "WmSJOvBs3Ck", "A0ezJDD4TfL"]
      aVar.Add(xArr)
      xArr = ["HEV ELISA/CLIA", "1", "WmSJOvBs3Ck", "wCvNkhhbSbl"]
      aVar.Add(xArr)
      '"Anti-HBs",
      xArr = ["Anti-HBs", "2", "xcxZPAxhCrT", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"HBeAg",
      xArr = ["HBeAg", "2", "dVvGXhFywu7", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Anti-HBe",
      xArr = ["Anti-HBe", "2", "X5nw2T7NV8r", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"HBcAg",
      xArr = ["HBcAg", "2", "BZIy8aFttCi", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Anti HBcAg",
      xArr = ["Anti HBcAg", "2", "T4Q5ABFtjDP", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Western blot",
      xArr = ["Western blot", "2", "HQr6MM8GsjH", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"CD4 count",
      xArr = ["CD4 count", "2", "ujt1GxVHLHV", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Viral load",
      xArr = ["Viral load", "2", "DcQtyLaLoCx", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Others"]
      xArr = ["Others", "2", "vmRFuQZTS6N", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "PARASITOLOGY" Then
      '"Stool R/E",
      xArr = ["Stool R/E", "2", "b3zYEkHFmat", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Occult blood",
      xArr = ["Occult blood", "2", "z9i5nhshIPk", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Reducing sugar",
      xArr = ["Reducing sugar", "2", "aydXkBquvXP", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Urine R/E",
      xArr = ["Urine R/E", "2", "PX30ls6pIRm", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Bile salts",
      xArr = ["Bile salts", "2", "KC4gQ1lbXAg", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Bile pigments",
      xArr = ["Bile pigments", "2", "uVcWLuam362", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Urobilinogen",
      xArr = ["Urobilinogen", "2", "XEe49IIPcoD", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Porphobilinogen",
      xArr = ["Porphobilinogen", "2", "pZSos4N7N2Y", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Acetone",
      xArr = ["Acetone", "2", "W1DQovLs4sh", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Chyle",
      xArr = ["Chyle", "2", "rzfTpDSCtgk", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Specific Gravity",
      xArr = ["Specific Gravity", "2", "rhxy310LFSm", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Bence Jones protein",
      xArr = ["Bence Jones protein", "2", "cGHCgAKZnjR", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Semen analysis",
      xArr = ["Semen analysis", "2", "SXwweKinsnK", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Others"]
      xArr = ["Others", "2", "uWALxnktvW8", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "HORMONE/ENDOCRINE" Then
      '"T3",
      xArr = ["T3", "2", "LzXPUrRvir7", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"T4",
      xArr = ["T4", "2", "WqsPscUDVDk", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"TSH",
      xArr = ["TSH", "2", "QsKf27NOrBI", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Cortisol",
      xArr = ["Cortisol", "2", "qHhZNumTNcz", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"AFP",
      xArr = ["AFP", "2", "vdMAkrFTc6e", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"LH",
      xArr = ["LH", "2", "W7tq5I1K1BO", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"FSH",
      xArr = ["FSH", "2", "rUL3GChBDhn", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Prolactin",
      xArr = ["Prolactin", "2", "c0JMi1fDGqe", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Oestrogen",
      xArr = ["Oestrogen", "2", "V8mAXNggfSP", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Progesterone",
      xArr = ["Progesterone", "2", "o6U9cg57pSH", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Testosterone",
      xArr = ["Testosterone", "2", "GOMZ5qZQVs7", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Vit.D",
      xArr = ["Vit.D", "2", "ad7l9UXQ95i", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Vit.B12",
      xArr = ["Vit.B12", "2", "W58gwBA5MiV", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Others"]
      xArr = ["Others", "2", "O2l3vMZAkYD", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "DRUG ANALYSIS" Then
      '"Carbamazepine",
      xArr = ["Carbamazepine", "2", "mMckO2ciFc8", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Cyclosporine",
      xArr = ["Cyclosporine", "2", "dSvjfeY3o91", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Valporic acid",
      xArr = ["Valporic acid", "2", "Buc8Fke2SMT", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Phenytoin",
      xArr = ["Phenytoin", "2", "d6EvPlKfJLX", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Digoxine",
      xArr = ["Digoxine", "2", "gBGJ7ghPg92", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Tacrolimus",
      xArr = ["Tacrolimus", "2", "rolQymvE0V7", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Others"]
      xArr = ["Others", "2", "aFxFDDT7Oaf", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "HISTOPATHOLOGY/CYTOLOGY" Then
      '"Biopsy(H & E)",
      xArr = ["Biopsy(H & E)", "2", "CLAPaXEhw5K", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Biopsy(Other)",
      xArr = ["Biopsy(Other)", "2", "GavlUw7f7UO", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Cytology(Pap)",
      xArr = ["Cytology(Pap)", "2", "U2jRar05uYB", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Cytology(Giemsa)",
      xArr = ["Cytology(Giemsa)", "2", "CqTFn3gaaxt", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Cytology(Others)"]
      xArr = ["Cytology(Others)", "2", "NjfwcREF9Ro", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "IMMUNO-HISTO CHEMISTRY" Then
      '"ER",
      xArr = ["ER", "2", "G2cxwinrrRA", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"PR",
      xArr = ["PR", "2", "QAKH6RCErmb", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"G-FAP",
      xArr = ["G-FAP", "2", "OAX1MLXQ5JV", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"S-100",
      xArr = ["S-100", "2", "eMDAo089gz3", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Vimentin",
      xArr = ["Vimentin", "2", "V89xWqV2EGN", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Cytokeratin",
      xArr = ["Cytokeratin", "2", "AhRD9oaSjeL", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Others"]
      xArr = ["Others", "2", "kZZRJEecl4i", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "MOLECULAR LAB" Then
      '"Covid-19 PCR",
      xArr = ["Covid-19 PCR", "2", "OHLcnsYbP4u", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Influenza",
      xArr = ["Influenza", "2", "T7Q1TLmqZSn", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '"Leukemia Panel"
      xArr = ["Leukemia Panel", "2", "keYqBgyPBPJ", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Endif

  Else If sChapter = "Geriatric Services" Then
    If sCategory = "Age Grouping" Then

    Else If sCategory = "Caste/Ethnicity" Then

    Else If sCategory = "HI Enrollment" Then

    Else If sCategory = "Types of services" Then

    Else If sCategory = "Source of expenses" Then

    Else If sCategory = "Hospital department" Then

    Else If sCategory = "Disease" Then

    Endif

  Else If sChapter = "One-Stop Crisis Management Center" Then
    If sCategory = "Age Group and Sex" Then

    Else If sCategory = "Disability" Then

    Else If sCategory = "Number of reported case by service" Then

    Else If sCategory = "Cause of violence" Then

    Else If sCategory = "Types of violence" Then

    Else If sCategory = "Number of new cases by Caste/Ethnicity" Then

    Else If sCategory = "Relationship of the perpetrator" Then

    Else If sCategory = "Age and Sex of Perpetrator" Then

    Endif

  Else If sChapter = "Social Service Unit" Then
    If sCategory = "Age Group and Sex" Then

    Else If sCategory = "Caste and Ethinicity" Then

    Else If sCategory = "HI Enrollment" Then

    Else If sCategory = "Hospital Department" Then

    Else If sCategory = "Target group" Then

    Endif

  Endif

  Return aVar

End

''====================== Dataset =================
Public Function GetHMISDataSetValue(sChapter As String, sHead As String, Optional sItem As String) As String

  Dim xval As String
  ' Dim sList As String[]

  ' TreeView1.Add("Summary of Services", "Summary of Services", pic3)
  If sChapter = "Hospital Summary Dataset" Then
    If sHead = "Hospital Services" Then
      xval = "CjuEkVeLgsT"
    Else If sHead = "Emergency Services" Then
      xval = "CjuEkVeLgsT"
    Else If sHead = "Diagnostic/Other Services" Then
      xval = "CjuEkVeLgsT"
    Else If sHead = "Free Service for Impoverished Citizen" Then
      xval = "CjuEkVeLgsT"
    Endif

    ' TreeView1.Add("Summary of Indoor Services", "Summary of Indoor Services", pic3)
  Else If sChapter = "Hospital Indoor Service" Then
    If sHead = "Inpatient Outcome" Then
      xval = "wFShrjdBjpR"
    Else If sHead = "Neonate Form" Then
      xval = "wFShrjdBjpR"
    Else If sHead = "Maternal Age" Then
      xval = "wFShrjdBjpR"
    Else If sHead = "Medico-Legal Cases" Then
      xval = "wFShrjdBjpR"
    Else If sHead = "Type of Surgeries" Then
      xval = "wFShrjdBjpR"
    Else If sHead = "Death Information" Then
      xval = "wFShrjdBjpR"
    Else If sHead = "Social Security Programme" Then
      xval = "wFShrjdBjpR"
    Else If sHead = "Free health service summary" Then
      xval = "wFShrjdBjpR"
    Endif

  Else If sChapter = "Inpatient Morbidity" Then
    xval = "G5TIM3GE43V"
  Else If sChapter = "Hospital Mortality" Then
    xval = "G5TIM3GE43V"

    ' TreeView1.Add("Safe Motherhood Programme", "Safe Motherhood Programme", pic3)
  Else If sChapter = "Maternal And New-born Health" Then
    If sHead = "ANC Services" Then
      xval = "cwvwxPZg83G"
    Else If sHead = "Delivery Service" Then
      xval = "cwvwxPZg83G"
    Else If sHead = "Delivery Type" Then
      xval = "cwvwxPZg83G"
    Else If sHead = "Delivery Outcome" Then
      xval = "cwvwxPZg83G"
    Else If sHead = "Stillbirth" Then
      xval = "cwvwxPZg83G"
    Else If sHead = "Incentive" Then
      xval = "cwvwxPZg83G"
    Else If sHead = "Obstetric Complications" Then
      xval = "cwvwxPZg83G"
    Else If sHead = "Blood Transfusion" Then
      xval = "cwvwxPZg83G"
    Else If sHead = "Birth Weight" Then
      xval = "cwvwxPZg83G"
    Else If sHead = "PNC Visit" Then
      xval = "cwvwxPZg83G"
    Else If sHead = "Maternal Death" Then
      xval = "cwvwxPZg83G"
    Else If sHead = "Neonatal Death" Then
      xval = "cwvwxPZg83G"
    Else If sHead = "Safe Abortion Service" Then
      xval = "cwvwxPZg83G"
    Endif

    ' TreeView1.Add("Family Planning Program", "Family Planning Programme", pic3)
  Else If sChapter = "Family Planning Program" Then

    ' TreeView1.Add("Newborn Care", "Newborn Care", pic3)
  Else If sChapter = "New Born Care" Then
    If sHead = "Number of sick babies admitted at SNCU/NICU/KMCU" Then
      xval = "q5g8VD5iMB0"
    Else If sHead = "Management & Treatment Outocmes at SNCU/NICU/KMCU" Then
      xval = "q5g8VD5iMB0"
    Else If sHead = "Number managed with KMC at SNCU/NICU/KMCU" Then
      xval = "q5g8VD5iMB0"
    Endif

    ' TreeView1.Add("Non-Communicable Diseases", "Non-Communicable Diseases", pic3)
  Else If sChapter = "Non Communicable Disease" Then
    If sHead = "Number of NCD cases on Treatment (OPD/Emergency)" Then
      xval = "JTlbVBM1sFY"
    Else If sHead = "Number of NCD Cause-Specific Deaths" Then
      xval = "JTlbVBM1sFY"
    Else If sHead = "Total number of new cancers cases managed" Then
      xval = "JTlbVBM1sFY"
    Else If sHead = "Number of Injuries" Then
      xval = "JTlbVBM1sFY"
    Else If sHead = "Number of Injury Deaths" Then
      xval = "JTlbVBM1sFY"
    Else If sHead = "Number of Mental Health Cases on Treatment (OPD/Emergency)" Then
      xval = "JTlbVBM1sFY"
    Else If sHead = "Type of Mental Health Cases" Then
      xval = "JTlbVBM1sFY"
    Else If sHead = "Control and Follow Up Cases for Hypertension and Diabetes" Then
      xval = "JTlbVBM1sFY"
    Endif

    ' TreeView1.Add("New Outpatient Morbidity", "New Outpatient Morbidity", pic3)
  Else If sChapter = "New Outpatient Morbidity" Then
    If sHead = "Certain Infectious or Parasitic Diseases" Then
      xval = "sEk5FwsTs9O"
    Else If sHead = "Communicable, Vector Borne" Then
      xval = "sEk5FwsTs9O"
    Else If sHead = "Communicable, Water/Food Borne" Then
      xval = "sEk5FwsTs9O"
    Else If sHead = "Other Communicable Diseases" Then
      xval = "sEk5FwsTs9O"
    Else If sHead = "HIV/STI" Then
      xval = "sEk5FwsTs9O"
    Else If sHead = "Other Infected Diseases" Then
      xval = "sEk5FwsTs9O"
    Else If sHead = "Nutritional & Metabolic Disorder" Then
      ' sList = ["5A01", "5A14", "5B7Z"]
      If sItem = "OPD1" Then
        xval = "sEk5FwsTs9O" ''OPD1
      Else If sItem = "OPD2" Then
        xval = "ox6D4Rx3YG7"   ''OPD2
      Endif
    Else If sHead = "Skin Diseases" Then
      xval = "ox6D4Rx3YG7"
    Else If sHead = "Ear, Nose and Throat Infection" Then
      xval = "ox6D4Rx3YG7"
    Else If sHead = "Oral Health Related Problems" Then
      xval = "ox6D4Rx3YG7"
      ''OPD3
    Else If sHead = "Eye Problems" Then
      xval = "JyROdbGRHgf"
    Else If sHead = "Obstetrics Complications" Then
      xval = "JyROdbGRHgf"
    Else If sHead = "Gynaecological Problems" Then
      xval = "JyROdbGRHgf"
    Else If sHead = "Mental Health related problems" Then
      ' sList = ["6B00", "6A00", "8A6Z", "8A80", "6E8Z", "MB24.3", "6C40", "6C4Z"]
      If sItem = "OPD4" Then
        xval = "a2mU4zjXrki"   ''OPD4
      Else If sItem = "OPD3" Then
        xval = "JyROdbGRHgf"   ''OPD3
      Endif
    Else If sHead = "Malignancy" Then
      xval = "a2mU4zjXrki"
    Else If sHead = "Cardiovascular & Respiratory Related Problems" Then
      xval = "a2mU4zjXrki"
    Else If sHead = "Other Diseases & Injuries" Then
      xval = "a2mU4zjXrki"
    Else If sHead = "Orthopaedic Problems" Then
      ' sList = ["FB55.Z", "ND56.3", "ME84.0", "ME85", "FA8Z", "FA84.Z"]
      If sItem = "OPD5" Then
        xval = "sH9aOPSIjVN"  ''OPD5
      Else If sItem = "OPD4" Then
        xval = "a2mU4zjXrki"  ''OPD4
      Endif
    Else If sHead = "Surgical Problems" Then
      xval = "sH9aOPSIjVN"
    Else If sHead = "Reasons for Contact with Health Services" Then
      xval = "sH9aOPSIjVN"
    Else If sHead = "Common Symptoms" Then
      xval = "sH9aOPSIjVN"
    Endif

    ' TreeView1.Add("Common Emergency Diseases", "Common Emergency Diseases", pic3)
  Else If sChapter = "Common Emergency Diseases" Then
    If sHead = "Respiratory Emergencies" Then
      xval = "RDyyD3qLnIy"
    Else If sHead = "Cardiac Emergencies" Then
      xval = "RDyyD3qLnIy"
    Else If sHead = "Neurological Emergencies" Then
      xval = "RDyyD3qLnIy"
    Else If sHead = "Gastrointestinal Emergencies" Then
      xval = "RDyyD3qLnIy"
    Else If sHead = "Genitourinary Emergencies" Then
      xval = "RDyyD3qLnIy"
    Else If sHead = "Gynecology and Obstetrical Emergencies" Then
      xval = "RDyyD3qLnIy"
    Else If sHead = "Orthopaedic & Trauma" Then
      xval = "RDyyD3qLnIy"
    Else If sHead = "Metabolic Emergencies" Then
      xval = "RDyyD3qLnIy"
    Else If sHead = "Ocular Emergencies" Then
      xval = "RDyyD3qLnIy"
    Else If sHead = "ENT Emergencies" Then
      xval = "RDyyD3qLnIy"
    Else If sHead = "Burns" Then
      xval = "RDyyD3qLnIy"
    Else If sHead = "Mental Health Emergencies" Then
      xval = "RDyyD3qLnIy"
    Else If sHead = "Toxicological Emergencies" Then
      xval = "RDyyD3qLnIy"
    Else If sHead = "Bite" Then
      xval = "RDyyD3qLnIy"
    Else If sHead = "Paediatric Emergencies" Then
      xval = "RDyyD3qLnIy"
    Endif

    ' TreeView1.Add("Laboratory Services", "Laboratory Services", pic3)
  Else If sChapter = "Laboratory Services" Then
    If sHead = "HAEMATOLOGY" Then
      xval = "jZ0ClbXLtgz"
    Else If sHead = "IMMUNOLOGY" Then
      xval = "jZ0ClbXLtgz"
    Else If sHead = "BIOCHEMISTRY" Then
      xval = "jZ0ClbXLtgz"
    Else If sHead = "BACTERIOLOGY" Then
      xval = "jZ0ClbXLtgz"
    Else If sHead = "VIROLOGY" Then
      xval = "jZ0ClbXLtgz"
    Else If sHead = "PARASITOLOGY" Then
      xval = "jZ0ClbXLtgz"
    Else If sHead = "HORMONE/ENDOCRINE" Then
      xval = "jZ0ClbXLtgz"
    Else If sHead = "DRUG ANALYSIS" Then
      xval = "jZ0ClbXLtgz"
    Else If sHead = "HISTOPATHOLOGY/CYTOLOGY" Then
      xval = "jZ0ClbXLtgz"
    Else If sHead = "IMMUNO-HISTO CHEMISTRY" Then
      xval = "jZ0ClbXLtgz"
    Else If sHead = "MOLECULAR LAB" Then
      xval = "jZ0ClbXLtgz"
    Endif

    ' TreeView1.Add("Geriatric Services", "Geriatric Services", pic3)
  Else If sChapter = "Geriatric Services" Then
    If sHead = "Age Grouping" Then
      xval = "Gcy5LFfxKPi"
    Else If sHead = "Caste/Ethnicity" Then
      xval = "Gcy5LFfxKPi"
    Else If sHead = "HI Enrollment" Then
      xval = "Gcy5LFfxKPi"
    Else If sHead = "Types of services" Then
      xval = "Gcy5LFfxKPi"
    Else If sHead = "Source of expenses" Then
      xval = "Gcy5LFfxKPi"
    Else If sHead = "Hospital department" Then
      xval = "Gcy5LFfxKPi"
    Else If sHead = "Disease" Then
      xval = "Gcy5LFfxKPi"
    Endif

    ' TreeView1.Add("One-Stop Crisis Management Center", "One-Stop Crisis Management Center", pic3)
  Else If sChapter = "One-Stop Crisis Management Center" Then
    If sHead = "Age Group and Sex" Then
      xval = "yojJae2XSYZ"
    Else If sHead = "Disability" Then
      xval = "yojJae2XSYZ"
    Else If sHead = "Number of reported case by service" Then
      xval = "yojJae2XSYZ"
    Else If sHead = "Cause of violence" Then
      xval = "yojJae2XSYZ"
    Else If sHead = "Types of violence" Then
      xval = "yojJae2XSYZ"
    Else If sHead = "Number of new cases by Caste/Ethnicity" Then
      xval = "yojJae2XSYZ"
    Else If sHead = "Relationship of the perpetrator" Then
      xval = "yojJae2XSYZ"
    Else If sHead = "Age and Sex of Perpetrator" Then
      xval = "yojJae2XSYZ"
    Endif

    ' TreeView1.Add("Social Service Unit", "Social Service Unit", pic3)
  Else If sChapter = "Social Service Unit" Then
    If sHead = "Age Group and Sex" Then
      xval = "OQ4e1903ugD"
    Else If sHead = "Caste and Ethinicity" Then
      xval = "OQ4e1903ugD"
    Else If sHead = "HI Enrollment" Then
      xval = "OQ4e1903ugD"
    Else If sHead = "Hospital Department" Then
      xval = "OQ4e1903ugD"
    Else If sHead = "Target group" Then
      xval = "OQ4e1903ugD"
    Endif

  Endif

  Return xval

End
