' Gambas module file

Public Function GetTempleteVariabList() As String[]
  
  Dim ListView1 As String[]
  
  ListView1 = New String[]
  ListView1.Add("{HospitalName}")
  ListView1.Add("{HospitalAddress}")
  ListView1.Add("{Department}")
  ListView1.Add("{CurrentTime}")
  ListView1.Add("{CurrentDate}")
  ListView1.Add("{CurrentUser}")
  ListView1.Add("{ExtScript1}")
  ListView1.Add("{ExtScript2}")
  
  ListView1.Add("{Encounter}")
  ListView1.Add("{PatientNo}")
  ListView1.Add("{PatientName}")
  ListView1.Add("{PatientAddress}")
  ListView1.Add("{PatientDistrict}")
  ListView1.Add("{PatientGender}")
  ListView1.Add("{PatientGuardian}")
  ListView1.Add("{PatientDOB}")
  ListView1.Add("{PatientAge}")
  ListView1.Add("{AgeGroup}")
  ListView1.Add("{AgeGroupCustom}")
  ListView1.Add("{Age/Sex}")
  ListView1.Add("{E-Mail}")
  ListView1.Add("{ContactNo}")
  ListView1.Add("{PatientFileNo}")
  ListView1.Add("{PatientRelation}")
  ListView1.Add("{FirstInvoiceNumber}")
  ListView1.Add("{LastInvoiceNumber}")
  ListView1.Add("{FirstInvoiceAmount}")
  ListView1.Add("{LastInvoiceAmount}")
  ListView1.Add("{FirstReceiptNumber}")
  ListView1.Add("{LastReceiptNumber}")
  
  ListView1.Add("{RegdDepartment}")
  ListView1.Add("{RegdDeptRoom}")
  ListView1.Add("{BedNo}")
  ListView1.Add("{WardName}")
  ListView1.Add("{FirstWardName}")
  ListView1.Add("{CurrDepartment}")
  ListView1.Add("{RegdBillMode}")
  ListView1.Add("{RegistrationDate}")
  ListView1.Add("{RegistrationTime}")
  ListView1.Add("{VisitMode}")
  ListView1.Add("{AdmissionDate}")
  ListView1.Add("{AdmissionTime}")
  ListView1.Add("{DischargeDate}")
  ListView1.Add("{DischargeTime}")
  ListView1.Add("{AdmitDurationHour}")
  ListView1.Add("{FollowUpDate}")
  ListView1.Add("{FollowUpTime}")
  ListView1.Add("{CurrentStatus}")
  ListView1.Add("{CurrentStatusComment}")
  ListView1.Add("{ProvisionalDiagnosis}")
  ListView1.Add("{FinalDiagnosis}")
  
  ListView1.Add("{LastConsultDept}")
  ListView1.Add("{LastConsultRoom}")
  ListView1.Add("{LastConsultant}")
  ListView1.Add("{LastConsultBillMode}")
  ListView1.Add("{LastConsultDate}")
  ListView1.Add("{LastConsultTime}")
  ListView1.Add("{LastConsultStatus}")
  ListView1.Add("{LastConsultComment}")
  ListView1.Add("{LastConsultOutcome}")
  ListView1.Add("{LastConsultQue}")
  ListView1.Add("{LastOPVisitDept}")
  ListView1.Add("{LastOPVisitRoom}")
  ListView1.Add("{LastOPVisitBillMode}")
  ListView1.Add("{LastOPVisitDate}")
  ListView1.Add("{LastOPVisitTime}")
  ListView1.Add("{LastOPVisitStatus}")
  ListView1.Add("{LastOPVisitComment}")
  ListView1.Add("{LastOPVisitOutcome}")
  ListView1.Add("{LastVisitDate}")
  ListView1.Add("{LastVisitTime}")
  ListView1.Add("{LastVisitLocation}")
  
  ListView1.Add("{EXTRA1}")
  ListView1.Add("{EXTRA2}")
  ListView1.Add("{EXTRA3}")
  ListView1.Add("{EXTRA4}")
  ListView1.Add("{EXTRA5}")
  ListView1.Add("{EXTRA6}")
  
  Return ListView1
  
End

Public Function HTMLNewLine() As String
  
  Dim xx As String
  
  xx = "     " & gb.NewLine
  Return xx
  
End

Public Function TitleHTMLScript() As String
  
  Dim xx As String
  
  xx = ""
  xx = "<!DOCTYPE HTML PUBLIC " & Quote("-//W3C//DTD HTML 4.01//EN") & " " & Quote("http://www.w3.org/TR/html4/strict.dtd") & ">" & HTMLNewLine()
  xx = xx & "<html>" & HTMLNewLine()
  xx = xx & "    <head>" & HTMLNewLine()
  xx = xx & "    <meta content='text/html; charset=utf-8' http-equiv='content-type'>" & HTMLNewLine()
  xx = xx & "           <title>" & Application.Title & "</title>" & HTMLNewLine()
  xx = xx & "    <meta name='generator' content='" & Application.Name & "'/>" & HTMLNewLine()
  xx = xx & "    <meta name='create' content='" & Str(Now()) & "'/>" & HTMLNewLine()
  xx = xx & "    </head>" & HTMLNewLine()
  xx = xx & gb.NewLine
  xx = xx & "     <body>" & HTMLNewLine()
  
  Return xx
  
End

Public Function GetReportNoTitleTemplete() As String
  
  Dim xx As String
  
  xx = "<br><br><br><br>"
  Return xx
  
End

Public Function GetReportTitleTemplete() As String
  
  Dim xx As String
  Dim hospname As String
  Dim hospadd As String
  Dim hospdept As String
  Dim titlestr As String
  
  Dim xhosname As String
  Dim xhosfont As String
  Dim xhosadd As String
  Dim xaddfont As String
  Dim xhosdept As String
  Dim xdeptfont As String
  Dim xheadpic As String
  Dim xheadlogo As String
  
  xhosname = modSettings.ShowSettingFromFIle("ReportFormat/Header_HospitalName")
  If xhosname And If xhosname = "Yes" Then
    xhosfont = modSettings.ShowSettingFromFIle("ReportFormat/HospitalName_Font")
    If xhosfont Then
      hospname = modString.GetFormatTextFontString("{HospitalName}", xhosfont)
    Else
      hospname = "{HospitalName}"
    Endif
  Else
    hospname = ""
  Endif
  
  xhosadd = modSettings.ShowSettingFromFIle("ReportFormat/Header_HospitalAddress")
  If xhosadd And If xhosadd = "Yes" Then
    xaddfont = modSettings.ShowSettingFromFIle("ReportFormat/HospitalAddress_Font")
    If xaddfont Then
      hospadd = modString.GetFormatTextFontString("{HospitalAddress}", xaddfont)
    Else
      hospadd = "{HospitalAddress}"
    Endif
  Else
    hospadd = ""
  Endif
  
  xhosdept = modSettings.ShowSettingFromFIle("ReportFormat/Header_DepartmentName")
  If xhosdept And If xhosdept = "Yes" Then
    xdeptfont = modSettings.ShowSettingFromFIle("ReportFormat/Department_Font")
    If xdeptfont Then
      hospdept = modString.GetFormatTextFontString("{Department}", xdeptfont)
    Else
      hospdept = "{Department}"
    Endif
  Else
    hospdept = ""
  Endif
  
  If modSettings.ShowSettingFromFIle("ReportFormat/BlankLines_Address_Department") Then
    titlestr = hospname & "<br>" & hospadd & modReportVar.BlankLinesAccSetting("ReportFormat/BlankLines_Address_Department") & hospdept
  Else
    titlestr = hospname & "<br>" & hospadd & "<br>" & hospdept
  Endif
  
  xx = ""
  xx = xx & "<table class='title_table' style='text-align: left; width: 100%;' id='titletable'>" & HTMLNewLine()
  xx = xx & "    <tbody>" & HTMLNewLine()
  xx = xx & "           <tr>" & HTMLNewLine()
  
  xheadpic = modSettings.ShowSettingFromFIle("ReportFormat/Header_Picture")
  If xheadpic Then
    xx = xx & "                 <td style='vertical-align: top; text-align: center;'>" & modString.GetImageForHTML(modPrint.GetFileWebURL(xheadpic)) & "<br>" & hospdept & "</td>" & HTMLNewLine()
  Else
    xheadlogo = modSettings.ShowSettingFromFIle("ReportFormat/Header_Logo")
    If xheadlogo And If xheadlogo = "Yes" Then
      xx = xx & "              <td style='vertical-align: top;'><img style='width: " & modSettings.ShowSettingFromFIle("ReportFormat/Header_LogoWidth") & "px; height: " & modSettings.ShowSettingFromFIle("ReportFormat/Header_LogoHeight") & "px;' alt='' src=" & "{HospLogo}" & "><br></td>" & HTMLNewLine()                                     ''
    Endif
    xx = xx & "                 <td style='vertical-align: top; text-align: center;'>" & titlestr & "</td>" & HTMLNewLine()                                                            ''
  Endif
  
  xx = xx & "           </tr>" & HTMLNewLine()
  xx = xx & "    </tbody>" & HTMLNewLine()
  xx = xx & "</table>" & HTMLNewLine()
  
  Return xx
  
End

Public Function GetPatientHeaderTemplete() As String
  
  Dim xx As String
  Dim xheadlabelfont As String
  Dim xheadvaluefont As String
  Dim xpatimage As String
  Dim xlabel11 As String
  Dim xlabel12 As String
  Dim xlabel21 As String
  Dim xlabel22 As String
  Dim xlabel31 As String
  Dim xlabel32 As String
  Dim xlabel41 As String
  Dim xlabel42 As String
  Dim xlabel51 As String
  Dim xlabel52 As String
  
  xheadlabelfont = modSettings.ShowSettingFromFIle("ReportFormat/Header_LabelFont")
  xheadvaluefont = modSettings.ShowSettingFromFIle("ReportFormat/Header_ValueFont")
  
  xx = ""
  xx = xx & "<table class='header_table' style='text-align: left; width: 100%;' id='headtable'>" & HTMLNewLine()
  xx = xx & "    <tbody>" & HTMLNewLine()
  
  xlabel11 = modSettings.ShowSettingFromFIle("ReportFormat/Header_Label11")
  xlabel12 = modSettings.ShowSettingFromFIle("ReportFormat/Header_Label12")
  If xlabel11 Or If xlabel12 Then
    xx = xx & "        <tr>" & HTMLNewLine()
    If xlabel11 Then
      xx = xx & "<td style='vertical-align: top;'>" & modString.GetFormatTextFontString(xlabel11 & ":", xheadlabelfont) & " " & modString.GetFormatTextFontString(modSettings.ShowSettingFromFIle("ReportFormat/Header_Value11"), xheadvaluefont) & "</td>" & HTMLNewLine()
    Else
      xx = xx & "<td style='vertical-align: top;'>" & " " & "</td>" & HTMLNewLine()
    Endif
    If xlabel12 Then
      xx = xx & "<td style='vertical-align: top;'>" & modString.GetFormatTextFontString(xlabel12 & ":", xheadlabelfont) & " " & modString.GetFormatTextFontString(modSettings.ShowSettingFromFIle("ReportFormat/Header_Value12"), xheadvaluefont) & "</td>" & HTMLNewLine()
    Else
      xx = xx & "<td style='vertical-align: top;'>" & " " & "</td>" & HTMLNewLine()
    Endif
    xpatimage = modSettings.ShowSettingFromFIle("ReportFormat/PatientImage")
    If xpatimage = "No Image" Then
    Else
      xx = xx & "<td colspan='1' rowspan='4' style='vertical-align: middle; width: 35%; text-align: center;'><img style='width: " & modSettings.ShowSettingFromFIle("ReportFormat/PatientImage_Width") & "%; height: " & modSettings.ShowSettingFromFIle("ReportFormat/PatientImage_Height") & "%;' alt='' src={barcodelink}></td>" & HTMLNewLine()
    Endif
    xx = xx & "        </tr>" & HTMLNewLine()
  Endif
  
  xlabel21 = modSettings.ShowSettingFromFIle("ReportFormat/Header_Label21")
  xlabel22 = modSettings.ShowSettingFromFIle("ReportFormat/Header_Label22")
  If xlabel21 Or If xlabel22 Then
    xx = xx & "        <tr>" & HTMLNewLine()
    If xlabel21 Then
      xx = xx & "<td style='vertical-align: top;'>" & modString.GetFormatTextFontString(xlabel21 & ":", xheadlabelfont) & " " & modString.GetFormatTextFontString(modSettings.ShowSettingFromFIle("ReportFormat/Header_Value21"), xheadvaluefont) & "</td>" & HTMLNewLine()
    Else
      xx = xx & "<td style='vertical-align: top;'>" & " " & "</td>" & HTMLNewLine()
    Endif
    If xlabel22 Then
      xx = xx & "<td style='vertical-align: top;'>" & modString.GetFormatTextFontString(xlabel22 & ":", xheadlabelfont) & " " & modString.GetFormatTextFontString(modSettings.ShowSettingFromFIle("ReportFormat/Header_Value22"), xheadvaluefont) & "</td>" & HTMLNewLine()
    Else
      xx = xx & "<td style='vertical-align: top;'>" & " " & "</td>" & HTMLNewLine()
    Endif
    xx = xx & "        </tr>" & HTMLNewLine()
  Endif
  
  xlabel31 = modSettings.ShowSettingFromFIle("ReportFormat/Header_Label31")
  xlabel32 = modSettings.ShowSettingFromFIle("ReportFormat/Header_Label32")
  If xlabel31 Or If xlabel32 Then
    xx = xx & "        <tr>" & HTMLNewLine()
    If xlabel31 Then
      xx = xx & "<td style='vertical-align: top;'>" & modString.GetFormatTextFontString(xlabel31 & ":", xheadlabelfont) & " " & modString.GetFormatTextFontString(modSettings.ShowSettingFromFIle("ReportFormat/Header_Value31"), xheadvaluefont) & "</td>" & HTMLNewLine()
    Else
      xx = xx & "<td style='vertical-align: top;'>" & " " & "</td>" & HTMLNewLine()
    Endif
    If xlabel32 Then
      xx = xx & "<td style='vertical-align: top;'>" & modString.GetFormatTextFontString(xlabel32 & ":", xheadlabelfont) & " " & modString.GetFormatTextFontString(modSettings.ShowSettingFromFIle("ReportFormat/Header_Value32"), xheadvaluefont) & "</td>" & HTMLNewLine()
    Else
      xx = xx & "<td style='vertical-align: top;'>" & " " & "</td>" & HTMLNewLine()
    Endif
    xx = xx & "        </tr>" & HTMLNewLine()
  Endif
  
  xlabel41 = modSettings.ShowSettingFromFIle("ReportFormat/Header_Label41")
  xlabel42 = modSettings.ShowSettingFromFIle("ReportFormat/Header_Label42")
  If xlabel41 Or If xlabel42 Then
    xx = xx & "        <tr>" & HTMLNewLine()
    If xlabel41 Then
      xx = xx & "<td style='vertical-align: top;'>" & modString.GetFormatTextFontString(xlabel41 & ":", xheadlabelfont) & " " & modString.GetFormatTextFontString(modSettings.ShowSettingFromFIle("ReportFormat/Header_Value41"), xheadvaluefont) & "</td>" & HTMLNewLine()
    Else
      xx = xx & "<td style='vertical-align: top;'>" & " " & "</td>" & HTMLNewLine()
    Endif
    If xlabel42 Then
      xx = xx & "<td style='vertical-align: top;'>" & modString.GetFormatTextFontString(xlabel42 & ":", xheadlabelfont) & " " & modString.GetFormatTextFontString(modSettings.ShowSettingFromFIle("ReportFormat/Header_Value42"), xheadvaluefont) & "</td>" & HTMLNewLine()
    Else
      xx = xx & "<td style='vertical-align: top;'>" & " " & "</td>" & HTMLNewLine()
    Endif
    xx = xx & "        </tr>" & HTMLNewLine()
  Endif
  
  xlabel51 = modSettings.ShowSettingFromFIle("ReportFormat/Header_Label51")
  xlabel52 = modSettings.ShowSettingFromFIle("ReportFormat/Header_Label52")
  If xlabel51 Or If modSettings.ShowSettingFromFIle("ReportFormat/Header_Label52") Then
    xx = xx & "        <tr>" & HTMLNewLine()
    If xlabel51 Then
      xx = xx & "<td style='vertical-align: top;'>" & modString.GetFormatTextFontString(xlabel51 & ":", xheadlabelfont) & " " & modString.GetFormatTextFontString(modSettings.ShowSettingFromFIle("ReportFormat/Header_Value51"), xheadvaluefont) & "</td>" & HTMLNewLine()
    Else
      xx = xx & "<td style='vertical-align: top;'>" & " " & "</td>" & HTMLNewLine()
    Endif
    If xlabel52 Then
      xx = xx & "<td style='vertical-align: top;'>" & modString.GetFormatTextFontString(xlabel52 & ":", xheadlabelfont) & " " & modString.GetFormatTextFontString(modSettings.ShowSettingFromFIle("ReportFormat/Header_Value52"), xheadvaluefont) & "</td>" & HTMLNewLine()
    Else
      xx = xx & "<td style='vertical-align: top;'>" & " " & "</td>" & HTMLNewLine()
    Endif
    xx = xx & "        </tr>" & HTMLNewLine()
  Endif
  
  xx = xx & "    </tbody>" & HTMLNewLine()
  xx = xx & "</table>" & HTMLNewLine()
  
  Return xx
  
End

Public Function GetGeneralHeaderTemplete() As String
  
  Dim xx As String
  
  xx = ""
  xx = xx & "<ul>" & HTMLNewLine()
  xx = xx & "      <li> {PARAM1}</li>" & HTMLNewLine()
  xx = xx & "      <li> {PARAM2}</li>" & HTMLNewLine()
  xx = xx & "</ul>" & HTMLNewLine()
  
  Return xx
  
End

Public Function GetPatientFooterTemplete() As String
  
  Dim xx As String
  Dim xsummary As String
  Dim xcommen As String
  Dim xfootcolm As String
  
  xx = ""
  xx = xx & "<hr style='width: 100%; height: 2px;'>" & HTMLNewLine()
  
  xsummary = modSettings.ShowSettingFromFIle("ReportFormat/ShowSummary")
  If xsummary And If xsummary = "Yes" Then
    xx = xx & "<table class='footer_table' style='text-align: left; width: 100%;'>" & HTMLNewLine()
    xx = xx & "    <tbody>" & HTMLNewLine()
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "             <td style='vertical-align: top; width: 100%;'>{FooterSummary}<br></td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
    xx = xx & "    </tbody>" & HTMLNewLine()
    xx = xx & "</table>" & HTMLNewLine()
  Endif
  
  xcommen = modSettings.ShowSettingFromFIle("ReportFormat/ShowComment")
  If xcommen And If xcommen = "Yes" Then
    xx = xx & "<p>{COMMENT}</p>" & HTMLNewLine()
  Endif
  
  xx = xx & "<table class='footer_table' style='text-align: left; width: 100%;' id='foottable'>" & HTMLNewLine()
  xx = xx & "    <tbody>" & HTMLNewLine()
  xx = xx & "         <tr>" & HTMLNewLine()
  
  xfootcolm = modSettings.ShowSettingFromFIle("ReportFormat/FooterColumn")
  If xfootcolm Then
    If CInt(xfootcolm) > 1 Then
      xx = xx & "             <td style='vertical-align: top; width: 33%;'>{Footer1}<br></td>" & HTMLNewLine()
      If CInt(xfootcolm) > 2 Then
        xx = xx & "             <td style='vertical-align: top; width: 33%;'>{Footer2}<br></td>" & HTMLNewLine()
      Endif
    Endif
    xx = xx & "             <td style='vertical-align: top; width: 33%;'>{Footer3}<br></td>" & HTMLNewLine()
  Endif
  
  xx = xx & "         </tr>" & HTMLNewLine()
  xx = xx & "    </tbody>" & HTMLNewLine()
  xx = xx & "</table>" & HTMLNewLine()
  
  xx = xx & "<p><small>{CurrentUser},{CurrentDate}</small></p>" & HTMLNewLine()
  
  Return xx
  
End

Public Function GetGeneralFooterTemplete() As String
  
  Dim xx As String
  
  xx = "<p><small>{CurrentUser},{CurrentDate}</small></p>" & HTMLNewLine()
  Return xx
  
End

Public Function GetPurchaseFooterTemplete() As String
  
  Dim xx As String
  
  xx = ""
  xx = xx & "<table class='footer_table' style='text-align: left; width: 100%;' id='foottable'>" & HTMLNewLine()
  xx = xx & "    <tbody>" & HTMLNewLine()
  xx = xx & "         <tr>" & HTMLNewLine()
  xx = xx & "             <td style='vertical-align: top; width: 33%;'>Prepared By:<br></td>" & HTMLNewLine()
  xx = xx & "             <td style='vertical-align: top; width: 33%;'>Recommended By:<br></td>" & HTMLNewLine()
  xx = xx & "             <td style='vertical-align: top; width: 33%;'>Approved By:<br></td>" & HTMLNewLine()
  xx = xx & "         </tr>" & HTMLNewLine()
  xx = xx & "    </tbody>" & HTMLNewLine()
  xx = xx & "</table>" & HTMLNewLine()
  
  xx = xx & "<p><small>{CurrentUser},{CurrentDate}</small></p>" & HTMLNewLine()
  
  Return xx
  
End

Public Function ReportFootImage() As String
  
  Dim xx As String
  Dim xfootpic As String
  
  xx = ""
  xfootpic = modSettings.ShowSettingFromFIle("ReportFormat/Footer_Picture")
  If xfootpic Then
    xx = xx & "<table class='footer_table' style='text-align: left; width: 100%;'>" & HTMLNewLine()
    xx = xx & "    <tbody>" & HTMLNewLine()
    xx = xx & "           <tr>" & HTMLNewLine()
    xx = xx & "                 <td style='vertical-align: top; text-align: center;'>" & modString.GetImageForHTML(modPrint.GetFileWebURL(xfootpic)) & "</td>" & HTMLNewLine()
    xx = xx & "           </tr>" & HTMLNewLine()
    xx = xx & "    </tbody>" & HTMLNewLine()
    xx = xx & "</table>" & HTMLNewLine()
  Endif
  
  Return xx
  
End

''for invoice
Public Function GetInvoiceTitleTemplete() As String
  
  Dim xx As String
  Dim hospname As String
  Dim hospadd As String
  Dim hospdept As String
  Dim titlestr As String
  
  Dim xhosname As String
  Dim xhosfont As String
  Dim xhosadd As String
  Dim xaddfont As String
  Dim xhosdept As String
  Dim xdeptfont As String
  Dim xheadpic As String
  Dim xheadlogo As String
  
  xhosname = modSettings.ShowSettingFromFIle("Invoice/Header_HospitalName")
  If xhosname And If xhosname = "Yes" Then
    xhosfont = modSettings.ShowSettingFromFIle("Invoice/HospitalName_Font")
    If xhosfont Then
      hospname = modString.GetFormatTextFontString("{HospitalName}", xhosfont)
    Else
      hospname = "{HospitalName}"
    Endif
  Else
    hospname = ""
  Endif
  
  xhosadd = modSettings.ShowSettingFromFIle("Invoice/Header_HospitalAddress")
  If xhosadd And If xhosadd = "Yes" Then
    xaddfont = modSettings.ShowSettingFromFIle("Invoice/HospitalAddress_Font")
    If xaddfont Then
      hospadd = modString.GetFormatTextFontString("{HospitalAddress}", xaddfont)
    Else
      hospadd = "{HospitalAddress}"
    Endif
  Else
    hospadd = ""
  Endif
  
  xhosdept = modSettings.ShowSettingFromFIle("Invoice/DepartmentName")
  If xhosdept And If xhosdept = "Yes" Then
    xdeptfont = modSettings.ShowSettingFromFIle("Invoice/Department_Font")
    If xdeptfont Then
      hospdept = modString.GetFormatTextFontString("{Department}", xdeptfont)
    Else
      hospdept = "{Department}"
    Endif
  Else
    hospdept = ""
  Endif
  
  If modSettings.ShowSettingFromFIle("Invoice/BlankLines_Address_Department") Then
    titlestr = hospname & "<br>" & hospadd & modReportVar.BlankLinesAccSetting("Invoice/BlankLines_Address_Department") & hospdept
  Else
    titlestr = hospname & "<br>" & hospadd & "<br>" & hospdept
  Endif
  
  xx = ""
  xx = xx & "<table class='title_table' style='text-align: left; width: 100%;' id='titletable'>" & HTMLNewLine()
  xx = xx & "    <tbody>" & HTMLNewLine()
  xx = xx & "           <tr>" & HTMLNewLine()
  
  xheadpic = modSettings.ShowSettingFromFIle("Invoice/Header_Picture")
  If xheadpic Then
    xx = xx & "                 <td style='vertical-align: top; text-align: center;'>" & modString.GetImageForHTML(modPrint.GetFileWebURL(xheadpic)) & "<br>" & hospdept & "</td>" & HTMLNewLine()
  Else
    xheadlogo = modSettings.ShowSettingFromFIle("Invoice/Header_Logo")
    If xheadlogo And If xheadlogo = "Yes" Then
      xx = xx & "              <td style='vertical-align: top;'><img style='width: " & modSettings.ShowSettingFromFIle("Invoice/Header_LogoWidth") & "px; height: " & modSettings.ShowSettingFromFIle("Invoice/Header_LogoHeight") & "px;' alt='' src=" & "{HospLogo}" & "><br></td>" & HTMLNewLine()                                    ''
    Endif
    xx = xx & "                 <td style='vertical-align: top; text-align: center;'>" & titlestr & "</td>" & HTMLNewLine()                                                          ''
  Endif
  
  xx = xx & "           </tr>" & HTMLNewLine()
  xx = xx & "    </tbody>" & HTMLNewLine()
  xx = xx & "</table>" & HTMLNewLine()
  
  Return xx
  
End

Public Function GetInvoiceBillType() As String
  
  Dim xx As String
  Dim bill As String
  
  Dim xtype As String
  Dim xalign As String
  
  xx = ""
  xx = xx & "<table class='invtypetable' style='text-align: left; width: 100%;' id='invtypetable'>" & HTMLNewLine()
  xx = xx & "    <tbody>" & HTMLNewLine()
  xx = xx & "           <tr>" & HTMLNewLine()
  
  xtype = modSettings.ShowSettingFromFIle("Invoice/InvoiceType_Font")
  If xtype Then
    bill = modString.GetFormatTextFontString("{InvoiceType}", xtype)
  Else
    bill = "{InvoiceType}"
  Endif
  
  xalign = modSettings.ShowSettingFromFIle("Invoice/InvoiceType_Align")
  If xalign Then
    xx = xx & "<td style='vertical-align: top; text-align: " & xalign & ";'>" & bill & "</td>" & HTMLNewLine()
  Else
    xx = xx & "<td style='vertical-align: top; text-align: center;'>" & bill & "</td>" & HTMLNewLine()
  Endif
  
  xx = xx & "           </tr>" & HTMLNewLine()
  xx = xx & "    </tbody>" & HTMLNewLine()
  xx = xx & "</table>" & HTMLNewLine()
  
  Return xx
  
End

Public Function GetInvoiceHeaderTemplete() As String
  
  Dim xx As String
  Dim lblDesign As String
  Dim txtDesign As String
  
  Dim xheadlabelfont As String
  Dim xheadtextfont As String
  Dim xlabel11 As String
  Dim xtext11 As String
  Dim xlabel12 As String
  Dim xtext12 As String
  Dim xlabel21 As String
  Dim xtext21 As String
  Dim xlabel22 As String
  Dim xtext22 As String
  Dim xlabel31 As String
  Dim xtext31 As String
  Dim xlabel32 As String
  Dim xtext32 As String
  Dim xlabelwid As String
  Dim xtextwid As String
  
  xheadlabelfont = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderTable_LabelFont")
  xheadtextfont = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderTable_TextFont")
  
  xlabelwid = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderTable_LabelWidth")
  If xlabelwid Then
    lblDesign = modString.GetDesignFormatString(xlabelwid, modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderTable_LabelAlignment"), "top", modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderTable_LabelWidUnit"))
  Else
    lblDesign = modString.GetDesignFormatString(, modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderTable_LabelAlignment"), "top")
  Endif
  
  xtextwid = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderTable_TextWidth")
  If modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderTable_TextWidth") Then
    txtDesign = modString.GetDesignFormatString(xtextwid, modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderTable_TextAlignment"), "top", modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderTable_TextWidUnit"))
  Else
    txtDesign = modString.GetDesignFormatString(, modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderTable_TextAlignment"), "top")
  Endif
  
  xx = ""
  xx = xx & "<table class='header_table' style='text-align: left; width: 100%;' id='headtable'>" & HTMLNewLine()
  xx = xx & "    <tbody>" & HTMLNewLine()
  
  xlabel11 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderLabel_Col11")
  xtext11 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderText_Col11")
  xlabel12 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderLabel_Col12")
  xtext12 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderText_Col12")
  If xtext11 Or If xtext12 Or If xlabel11 Or If xlabel12 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel11, xheadlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext11, xheadtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.HTMLBlankSpace(3) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel12, xheadlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext12, xheadtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xlabel21 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderLabel_Col21")
  xtext21 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderText_Col21")
  xlabel22 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderLabel_Col22")
  xtext22 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderText_Col22")
  If xtext21 Or If xtext22 Or If xlabel21 Or If xlabel22 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel21, xheadlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext21, xheadtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.HTMLBlankSpace(3) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel22, xheadlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext22, xheadtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xlabel31 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderLabel_Col31")
  xtext31 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderText_Col31")
  xlabel32 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderLabel_Col32")
  xtext32 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderText_Col32")
  If xtext31 Or If xtext32 Or If xlabel31 Or If xlabel32 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel31, xheadlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext31, xheadtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.HTMLBlankSpace(3) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel32, xheadlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext32, xheadtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xx = xx & "    </tbody>" & HTMLNewLine()
  xx = xx & "</table>" & HTMLNewLine()
  
  Return xx
  
End

Public Function GetPurchaseHeaderTemplete() As String
  
  Dim xx As String
  
  xx = ""
  xx = xx & "<table class='header_table' style='text-align: left; width: 100%;' id='headtable'>" & HTMLNewLine()
  xx = xx & "    <tbody>" & HTMLNewLine()
  xx = xx & "         <tr>" & HTMLNewLine()
  xx = xx & "                 <td style='vertical-align: top;'>SUPPLIER:{SupplierName}</td>" & HTMLNewLine()
  xx = xx & "              <td style='vertical-align: top;'>" & modString.HTMLBlankSpace(3) & "</td>" & HTMLNewLine()
  xx = xx & "                 <td style='vertical-align: top;'>PAYMENT:{PaymentType}</td>" & HTMLNewLine()
  xx = xx & "         </tr>" & HTMLNewLine()
  xx = xx & "         <tr>" & HTMLNewLine()
  xx = xx & "                 <td style='vertical-align: top;'>INVOICE:{InvoiceNumber}</td>" & HTMLNewLine()
  xx = xx & "              <td style='vertical-align: top;'>" & modString.HTMLBlankSpace(3) & "</td>" & HTMLNewLine()
  xx = xx & "                 <td style='vertical-align: top;'>REFERENCE:{ReferenceNo}</td>" & HTMLNewLine()
  xx = xx & "         </tr>" & HTMLNewLine()
  xx = xx & "    </tbody>" & HTMLNewLine()
  xx = xx & "</table>" & HTMLNewLine()
  
  Return xx
  
End

Public Function GetDepositInvoiceFooterTemplete() As String
  
  Dim xx As String
  Dim lblDesign As String
  Dim txtDesign As String
  
  Dim xlabelfont As String
  Dim xtextfont As String
  Dim xlabel11 As String
  Dim xtext11 As String
  Dim xlabel12 As String
  Dim xtext12 As String
  Dim xlabel21 As String
  Dim xtext21 As String
  Dim xlabel22 As String
  Dim xtext22 As String
  Dim xlabel31 As String
  Dim xtext31 As String
  Dim xlabel32 As String
  Dim xtext32 As String
  Dim xlabel41 As String
  Dim xtext41 As String
  Dim xlabel42 As String
  Dim xtext42 As String
  Dim xfootend1 As String
  Dim xfootend2 As String
  Dim xendfootcollabel1 As String
  Dim xendfootcoltext1 As String
  Dim xendfootcollabel2 As String
  Dim xendfootcoltext2 As String
  Dim xtablabelwid As String
  Dim xtabtextwid As String
  
  xlabelfont = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_LabelFont")
  xtextfont = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_TextFont")
  
  xtablabelwid = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_LabelWidth")
  If xtablabelwid Then
    lblDesign = modString.GetDesignFormatString(xtablabelwid, modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_LabelAlignment"), "top", modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_LabelWidUnit"))
  Else
    lblDesign = modString.GetDesignFormatString(, modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_LabelAlignment"), "top")
  Endif
  
  xtabtextwid = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_TextWidth")
  If xtabtextwid Then
    txtDesign = modString.GetDesignFormatString(xtabtextwid, modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_TextAlignment"), "top", modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_TextWidUnit"))
  Else
    txtDesign = modString.GetDesignFormatString(, modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_TextAlignment"), "top")
  Endif
  
  xx = ""
  xx = xx & "<table class='footer_table' style='text-align: left; width: 100%;' id='foottable'>" & HTMLNewLine()
  xx = xx & "    <tbody>" & HTMLNewLine()
  
  xlabel11 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col11_Cash")
  xtext11 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col11_Cash")
  xlabel12 = modSettings.ShowSettingFromFIle("Invoice/BiultIn_FooterLabel_Col12_Cash")
  xtext12 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col12_Cash")
  If xtext11 Or If xtext12 Or If xlabel11 Or If xlabel12 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel11, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext11, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.HTMLBlankSpace(3) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel12, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext12, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xlabel21 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col21_Cash")
  xtext21 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col21_Cash")
  xlabel22 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col22_Cash")
  xtext22 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col22_Cash")
  If xtext21 Or If xtext22 Or If xlabel21 Or If xlabel22 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel21, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext21, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.HTMLBlankSpace(3) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel22, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext22, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xlabel31 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col31_Cash")
  xtext31 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col31_Cash")
  xlabel32 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col32_Cash")
  xtext32 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col32_Cash")
  If xtext31 Or If xtext32 Or If xlabel31 Or If xlabel32 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel31, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext31, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.HTMLBlankSpace(3) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel32, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext32, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xlabel41 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col41_Cash")
  xtext41 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col41_Cash")
  xlabel42 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col42_Cash")
  xtext42 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col42_Cash")
  If xtext41 Or If xtext42 Or If xlabel41 Or If xlabel42 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel41, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext41, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.HTMLBlankSpace(3) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel42, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext42, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xx = xx & "    </tbody>" & HTMLNewLine()
  xx = xx & "</table>" & HTMLNewLine()
  
  ''
  xx = xx & "<table class='footer_table' style='text-align: left; width: 100%;'>" & HTMLNewLine()
  xx = xx & "    <tbody>" & HTMLNewLine()
  
  xfootend1 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEnd1")
  If xfootend1 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.GetFormatTextFontString(xfootend1, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xfootend2 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEnd2")
  If xfootend2 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.GetFormatTextFontString(xfootend2, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xx = xx & "    </tbody>" & HTMLNewLine()
  xx = xx & "</table>" & HTMLNewLine()
  
  ''
  xx = xx & "<table style='text-align: left; width: 100%;'>" & HTMLNewLine()
  xx = xx & "    <tbody>" & HTMLNewLine()
  
  xendfootcollabel1 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol1_Label")
  xendfootcoltext1 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol1_Text")
  xendfootcollabel2 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol2_Label")
  xendfootcoltext2 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol2_Text")
  If xendfootcoltext1 Or If xendfootcoltext2 Or If xendfootcollabel1 Or If xendfootcollabel2 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xendfootcollabel1, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xendfootcoltext1, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.HTMLBlankSpace(3) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xendfootcollabel2, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xendfootcoltext2, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xx = xx & "    </tbody>" & HTMLNewLine()
  xx = xx & "</table>" & HTMLNewLine()
  
  Return xx
  
End

Public Function GetBillingInvoiceFooterTemplete() As String
  
  Dim xx As String
  Dim lblDesign As String
  Dim txtDesign As String
  
  Dim xlabelfont As String
  Dim xtextfont As String
  Dim xlabel11 As String
  Dim xtext11 As String
  Dim xlabel12 As String
  Dim xtext12 As String
  Dim xlabel21 As String
  Dim xtext21 As String
  Dim xlabel22 As String
  Dim xtext22 As String
  Dim xlabel31 As String
  Dim xtext31 As String
  Dim xlabel32 As String
  Dim xtext32 As String
  Dim xlabel41 As String
  Dim xtext41 As String
  Dim xlabel42 As String
  Dim xtext42 As String
  Dim xfootend1 As String
  Dim xfootend2 As String
  Dim xendfootcollabel1 As String
  Dim xendfootcoltext1 As String
  Dim xendfootcollabel2 As String
  Dim xendfootcoltext2 As String
  Dim xtablabelwid As String
  Dim xtabtextwid As String
  
  xlabelfont = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_LabelFont")
  xtextfont = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_TextFont")
  
  xtablabelwid = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_LabelWidth")
  If xtablabelwid Then
    lblDesign = modString.GetDesignFormatString(xtablabelwid, modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_LabelAlignment"), "top", modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_LabelWidUnit"))
  Else
    lblDesign = modString.GetDesignFormatString(, modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_LabelAlignment"), "top")
  Endif
  
  xtabtextwid = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_TextWidth")
  If xtabtextwid Then
    txtDesign = modString.GetDesignFormatString(xtabtextwid, modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_TextAlignment"), "top", modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_TextWidUnit"))
  Else
    txtDesign = modString.GetDesignFormatString(, modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterTable_TextAlignment"), "top")
  Endif
  
  xx = ""
  xx = xx & "<table class='footer_table' style='text-align: left; width: 100%;' id='foottable'>" & HTMLNewLine()
  xx = xx & "    <tbody>" & HTMLNewLine()
  
  xlabel11 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col11_Credit")
  xtext11 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col11_Credit")
  xlabel12 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col12_Credit")
  xtext12 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col12_Credit")
  If xtext11 Or If xtext12 Or If xlabel11 Or If xlabel12 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel11, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext11, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.HTMLBlankSpace(3) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel12, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext12, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xlabel21 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col21_Credit")
  xtext21 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col21_Credit")
  xlabel22 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col22_Credit")
  xtext22 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col22_Credit")
  If xtext21 Or If xtext22 Or If xlabel21 Or If xlabel22 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel21, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext21, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.HTMLBlankSpace(3) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel22, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext22, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xlabel31 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col31_Credit")
  xtext31 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col31_Credit")
  xlabel32 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col32_Credit")
  xtext32 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col32_Credit")
  If xtext31 Or If xtext32 Or If xlabel31 Or If xlabel32 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel31, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext31, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.HTMLBlankSpace(3) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel32, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext32, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xlabel41 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col41_Credit")
  xtext41 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col41_Credit")
  xlabel42 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col42_Credit")
  xtext42 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col42_Credit")
  If xtext41 Or If xtext42 Or If xlabel41 Or If xlabel42 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel41, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext41, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.HTMLBlankSpace(3) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xlabel42, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xtext42, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xx = xx & "    </tbody>" & HTMLNewLine()
  xx = xx & "</table>" & HTMLNewLine()
  
  ''
  xx = xx & "<table class='footer_table' style='text-align: left; width: 100%;'>" & HTMLNewLine()
  xx = xx & "    <tbody>" & HTMLNewLine()
  
  xfootend1 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEnd1")
  If xfootend1 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.GetFormatTextFontString(xfootend1, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xfootend2 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEnd2")
  If xfootend2 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.GetFormatTextFontString(xfootend2, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  xx = xx & "    </tbody>" & HTMLNewLine()
  xx = xx & "</table>" & HTMLNewLine()
  
  ''
  xx = xx & "<table style='text-align: left; width: 100%;'>" & HTMLNewLine()
  xx = xx & "    <tbody>" & HTMLNewLine()
  
  xendfootcollabel1 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol1_Label")
  xendfootcoltext1 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol1_Text")
  xendfootcollabel2 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol2_Label")
  xendfootcoltext2 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol2_Text")
  If xendfootcoltext1 Or If xendfootcoltext2 Or If xendfootcollabel1 Or If xendfootcollabel2 Then
    xx = xx & "         <tr>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xendfootcollabel1, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xendfootcoltext1, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td style='vertical-align: top;'>" & modString.HTMLBlankSpace(3) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & lblDesign & ">" & modString.GetFormatTextFontString(xendfootcollabel2, xlabelfont) & "</td>" & HTMLNewLine()
    xx = xx & "              <td " & txtDesign & ">" & modString.GetFormatTextFontString(xendfootcoltext2, xtextfont) & "</td>" & HTMLNewLine()
    xx = xx & "         </tr>" & HTMLNewLine()
  Endif
  
  xx = xx & "    </tbody>" & HTMLNewLine()
  xx = xx & "</table>" & HTMLNewLine()
  
  Return xx
  
End

Public Function InvoiceFootImage() As String
  
  Dim xx As String
  Dim xfootpic As String
  
  xx = ""
  xfootpic = modSettings.ShowSettingFromFIle("Invoice/Footer_Picture")
  If xfootpic Then
    xx = xx & "<table class='footer_table' style='text-align: left; width: 100%;'>" & HTMLNewLine()
    xx = xx & "    <tbody>" & HTMLNewLine()
    xx = xx & "           <tr>" & HTMLNewLine()
    xx = xx & "                 <td style='vertical-align: top; text-align: center;'>" & modString.GetImageForHTML(modPrint.GetFileWebURL(xfootpic)) & "</td>" & HTMLNewLine()
    xx = xx & "           </tr>" & HTMLNewLine()
    xx = xx & "    </tbody>" & HTMLNewLine()
    xx = xx & "</table>" & HTMLNewLine()
  Endif
  
  Return xx
  
End

''For both
Public Function EndTemplete() As String
  
  Dim xx As String
  
  xx = "</body>" & HTMLNewLine()
  xx = xx & "</html>" & HTMLNewLine()
  
  Return xx
  
End

''--------------------------------------------- Line Invoice -------------------------------------------------
Public Function LineTitleTemplete() As String
  
  Dim xx As String
  Dim sPath As String
  
  Dim xhosname As String
  Dim xhosadd As String
  Dim xhosdept As String
  
  xx = ""
  xhosname = modSettings.ShowSettingFromFIle("Invoice/Header_HospitalName")
  If xhosname And If xhosname = "Yes" Then
    xx = xx & "{HospitalName}" & gb.NewLine
  Endif
  
  xhosadd = modSettings.ShowSettingFromFIle("Invoice/Header_HospitalAddress")
  If xhosadd And If xhosadd = "Yes" Then
    xx = xx & "{HospitalAddress}" & gb.NewLine
  Endif
  
  xhosdept = modSettings.ShowSettingFromFIle("Invoice/DepartmentName")
  If xhosdept And If xhosdept = "Yes" Then
    xx = xx & "{Department}"
  Endif
  
  sPath = Temp()
  File.Save(sPath, xx)
  Return sPath
  
End

Public Function LineHeaderTemplete() As String
  
  Dim xx As String
  Dim brk As String
  Dim sPath As String
  
  Dim xlabel11 As String
  Dim xtext11 As String
  Dim xlabel12 As String
  Dim xtext12 As String
  Dim xlabel21 As String
  Dim xtext21 As String
  Dim xlabel22 As String
  Dim xtext22 As String
  Dim xlabel31 As String
  Dim xtext31 As String
  Dim xlabel32 As String
  Dim xtext32 As String
  
  xx = ""
  brk = " : "
  
  xlabel11 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderLabel_Col11")
  xtext11 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderText_Col11")
  If xtext11 Then
    xx = xx & xlabel11 & brk & xtext11
  Endif
  
  xlabel12 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderLabel_Col12")
  xtext12 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderText_Col12")
  If xtext12 Then
    xx = xx & ";" & xlabel12 & brk & xtext12
  Endif
  xx = xx & gb.NewLine
  
  xlabel21 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderLabel_Col21")
  xtext21 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderText_Col21")
  If xtext21 Then
    xx = xx & xlabel21 & brk & xtext21
  Endif
  
  xlabel22 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderLabel_Col22")
  xtext22 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderText_Col22")
  If xtext22 Then
    xx = xx & ";" & xlabel22 & brk & xtext22
  Endif
  
  xlabel31 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderLabel_Col31")
  xtext31 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderText_Col31")
  If xtext31 Then
    xx = xx & xlabel31 & brk & xtext31
  Endif
  
  xlabel32 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderLabel_Col32")
  xtext32 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_HeaderText_Col32")
  If xtext32 Then
    xx = xx & ";" & xlabel32 & brk & xtext32
  Endif
  
  sPath = Temp()
  File.Save(sPath, xx)
  Return sPath
  
End

Public Function LineFooterCreditTemplete() As String
  
  Dim xx As String
  Dim brk As String
  Dim sPath As String
  
  Dim xlabel11 As String
  Dim xtext11 As String
  Dim xlabel12 As String
  Dim xtext12 As String
  Dim xlabel21 As String
  Dim xtext21 As String
  Dim xlabel22 As String
  Dim xtext22 As String
  Dim xlabel31 As String
  Dim xtext31 As String
  Dim xlabel32 As String
  Dim xtext32 As String
  Dim xlabel41 As String
  Dim xtext41 As String
  Dim xlabel42 As String
  Dim xtext42 As String
  Dim xfootend1 As String
  Dim xfootend2 As String
  Dim xendfootcollabel1 As String
  Dim xendfootcoltext1 As String
  Dim xendfootcollabel2 As String
  Dim xendfootcoltext2 As String
  
  xx = ""
  brk = " : "
  
  xlabel11 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col11_Credit")
  xtext11 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col11_Credit")
  If xtext11 Then
    xx = xx & xlabel11 & brk & xtext11
  Endif
  
  xlabel12 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col12_Credit")
  xtext12 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col12_Credit")
  If xtext12 Then
    xx = xx & ";" & xlabel12 & brk & xtext12
  Endif
  xx = xx & gb.NewLine
  
  xlabel21 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col21_Credit")
  xtext21 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col21_Credit")
  If xtext21 Then
    xx = xx & xlabel21 & brk & xtext21
  Endif
  
  xlabel22 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col22_Credit")
  xtext22 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col22_Credit")
  If xtext22 Then
    xx = xx & ";" & xlabel22 & brk & xtext22
  Endif
  xx = xx & gb.NewLine
  
  xlabel31 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col31_Credit")
  xtext31 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col31_Credit")
  If xtext31 Then
    xx = xx & xlabel31 & brk & xtext31
  Endif
  
  xlabel32 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col32_Credit")
  xtext32 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col32_Credit")
  If xtext32 Then
    xx = xx & ";" & xlabel32 & brk & xtext32
  Endif
  xx = xx & gb.NewLine
  
  xlabel41 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col41_Credit")
  xtext41 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col41_Credit")
  If xtext41 Then
    xx = xx & xlabel41 & brk & xtext41
  Endif
  
  xlabel42 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col42_Credit")
  xtext42 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col42_Credit")
  If xtext42 Then
    xx = xx & ";" & xlabel42 & brk & xtext42
  Endif
  
  xfootend1 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEnd1")
  If xfootend1 Then
    xx = xx & gb.NewLine
    xx = xx & xfootend1
  Endif
  
  xfootend2 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEnd2")
  If xfootend2 Then
    xx = xx & gb.NewLine
    xx = xx & xfootend2
  Endif
  xx = xx & gb.NewLine
  
  xendfootcollabel1 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol1_Label")
  xendfootcoltext1 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol1_Text")
  If xendfootcoltext1 Then
    xx = xx & xendfootcollabel1 & brk & xendfootcoltext1
  Endif
  
  xendfootcollabel2 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol2_Label")
  xendfootcoltext2 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol2_Text")
  If xendfootcoltext2 Then
    xx = xx & ";" & xendfootcollabel2 & brk & xendfootcoltext2
  Endif
  
  sPath = Temp()
  File.Save(sPath, xx)
  Return sPath
  
End

Public Function LineFooterCashTemplete() As String
  
  Dim xx As String
  Dim brk As String
  Dim sPath As String
  
  Dim xlabel11 As String
  Dim xtext11 As String
  Dim xlabel12 As String
  Dim xtext12 As String
  Dim xlabel21 As String
  Dim xtext21 As String
  Dim xlabel22 As String
  Dim xtext22 As String
  Dim xlabel31 As String
  Dim xtext31 As String
  Dim xlabel32 As String
  Dim xtext32 As String
  Dim xlabel41 As String
  Dim xtext41 As String
  Dim xlabel42 As String
  Dim xtext42 As String
  Dim xfootend1 As String
  Dim xfootend2 As String
  Dim xendfootcollabel1 As String
  Dim xendfootcoltext1 As String
  Dim xendfootcollabel2 As String
  Dim xendfootcoltext2 As String
  
  xx = ""
  brk = " : "
  
  xlabel11 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col11_Cash")
  xtext11 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col11_Cash")
  If xtext11 Then
    xx = xx & xlabel11 & brk & xtext11
  Endif
  
  xlabel12 = modSettings.ShowSettingFromFIle("Invoice/BiultIn_FooterLabel_Col12_Cash")
  xtext12 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col12_Cash")
  If xtext12 Then
    xx = xx & ";" & xlabel12 & brk & xtext12
  Endif
  xx = xx & gb.NewLine
  
  xlabel21 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col21_Cash")
  xtext21 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col21_Cash")
  If xtext21 Then
    xx = xx & xlabel21 & brk & xtext21
  Endif
  
  xlabel22 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col22_Cash")
  xtext22 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col22_Cash")
  If xtext22 Then
    xx = xx & ";" & xlabel22 & brk & xtext22
  Endif
  xx = xx & gb.NewLine
  
  xlabel31 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col31_Cash")
  xtext31 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col31_Cash")
  If xtext31 Then
    xx = xx & xlabel31 & brk & xtext31
  Endif
  
  xlabel32 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col32_Cash")
  xtext32 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col32_Cash")
  If xtext32 Then
    xx = xx & ";" & xlabel32 & brk & xtext32
  Endif
  xx = xx & gb.NewLine
  
  xlabel41 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col41_Cash")
  xtext41 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col41_Cash")
  If xtext41 Then
    xx = xx & xlabel41 & brk & xtext41
  Endif
  
  xlabel42 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col42_Cash")
  xtext42 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col42_Cash")
  If xtext42 Then
    xx = xx & ";" & xlabel42 & brk & xtext42
  Endif
  
  xfootend1 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEnd1")
  If xfootend1 Then
    xx = xx & gb.NewLine
    xx = xx & xfootend1
  Endif
  
  xfootend2 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEnd2")
  If xfootend2 Then
    xx = xx & gb.NewLine
    xx = xx & xfootend2
  Endif
  xx = xx & gb.NewLine
  
  xendfootcollabel1 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol1_Label")
  xendfootcoltext1 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol1_Text")
  If xendfootcoltext1 Then
    xx = xx & xendfootcollabel1 & brk & xendfootcoltext1
  Endif
  
  xendfootcollabel2 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol2_Label")
  xendfootcoltext2 = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterEndCol2_Text")
  If xendfootcoltext2 Then
    xx = xx & ";" & xendfootcollabel2 & brk & xendfootcoltext2
  Endif
  
  sPath = Temp()
  File.Save(sPath, xx)
  Return sPath
  
End

Public Function HTMLTableSyntax(Optional sWidth As Integer) As String
  
  Dim xx As String
  Dim xwidth As String
  
  If sWidth Then
    xwidth = CStr(sWidth)
  Else
    xwidth = "100"
  Endif
  xx = "<table class='reportmid_table' style='text-align: left; width: " & xwidth & "%;'>" & gb.NewLine
  Return xx
  
End

Public Function HTMLDualTableSyntax(Optional sWidth As Integer) As String
  
  Dim xx As String
  Dim xwidth As String
  
  If sWidth Then
    xwidth = CStr(sWidth)
  Else
    xwidth = "100"
  Endif
  xx = "<table class='reportdual_table' style='text-align: left; width: " & xwidth & "%;'>" & gb.NewLine
  Return xx
  
End

Public Function GetPageNumberHTML() As String
  
  Dim xx As String
  
  xx = "Page <span id='page'></span> of " & gb.NewLine
  xx = xx & "<span id='topage'></span>" & gb.NewLine
  xx = xx & "<script>" & gb.NewLine
  xx = xx & "var vars={};" & gb.NewLine
  xx = xx & "var x=window.location.search.substring(1).split('&');" & gb.NewLine
  xx = xx & "for (var i in x) {" & gb.NewLine
  xx = xx & "var z=x[i].split('=',2);" & gb.NewLine
  xx = xx & "vars[z[0]] = unescape(z[1]);" & gb.NewLine
  xx = xx & "}" & gb.NewLine
  xx = xx & "document.getElementById('page').innerHTML = vars.page;" & gb.NewLine
  xx = xx & "document.getElementById('topage').innerHTML = vars.topage;" & gb.NewLine
  xx = xx & "</script>"
  
  Return xx
  
End
