' Gambas module file

Public Function AddPopulationParameters(sChapter As String, sCategory As String, sMale As Float, sFemale As Float, sOther As Float, xPality As String, xDistrict As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpopulation")
  res["fldchapter"] = sChapter
  res["fldcategory"] = sCategory
  res["fldmale"] = sMale
  res["fldfemale"] = sFemale
  res["fldother"] = sOther
  res["fldpality"] = xPality
  res["flddistrict"] = xDistrict
  res["fldtime"] = Now()
  res["flduserid"] = modBasic.$lbluser
  res["fldverify"] = False
  res.Update

End

Public Sub GetPopulationVerify(sID As Long)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpopulation", "fldid=&1", sID)
  If res.Available Then
    res["fldverify"] = True
    res.Update
  Endif

End

Public Sub DisablePopulationParam(sChapter As String, sDistrict As String, sMunicipal As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpopulation", "fldchapter=&1 and fldverify=&2 and fldpality=&3 and flddistrict=&4", sChapter, True, sMunicipal, sDistrict)
  If res.Available Then
    For Each res
      res["fldverify"] = False
      res.Update
    Next
  Endif

End

Public Function AddPopulationGeneral(sChapter As String, sCategory As String, sQuali As String, aQuanti As Float, xPality As String, xDistrict As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tbldashparameters")
  res["fldchapter"] = sChapter
  res["fldcategory"] = sCategory
  res["fldquali"] = sQuali
  res["fldquanti"] = aQuanti
  res["fldpality"] = xPality
  res["flddistrict"] = xDistrict
  res["fldtime"] = Now()
  res["flduserid"] = modBasic.$lbluser
  res["fldverify"] = False
  res.Update

End
