' Gambas module file

Public $LastEncounterID As String
Public $HideFormList As String[]
Public $FormOpenList As Variant[]
Public $FormOpenQue As Integer

Public $CompletionList As String[]
Public $CompletionEnable As String

' Public Sub InsertTexEditortData(xTextArea As WebTextArea)
'
' End

Public Sub GetOpenModalForm(sWebForm As WebForm)

  If modBasic.$TabletModeEnable = "Yes" Then
    ' sWebForm.Move(0, 0)
  Endif

End

Public Function GetWebDepartList() As String[]

  Dim i As Integer
  Dim lstequation As String[]
  Dim xvar As String

  lstequation = New String[]
  For i = 1 To 100
    xvar = modSettings.ShowSettingFromFIle("Departments/Comp" & CStr(i))
    If xvar Then
      lstequation.Add(xvar)
    Endif
  Next
  Return lstequation

End

Public Sub SetAutoCompleteTextArea()

  Dim xPath As String
  Dim hFile As File
  Dim sLine As String
  Dim sWord As String[]

  If Exist(modHelpVariable.$docsDirectory &/ "textcompletion") Then
    xPath = modHelpVariable.$docsDirectory &/ "textcompletion"
  Else
    xPath = modBasic.$SpellCheckFile
  Endif
  $CompletionList = New String[]
  If Exist(xPath) Then
    hFile = Open xPath
    modBasic.DebugString("Open File " & xPath)
    For Each sLine In hFile.Lines
      If Trim(sLine) Then
        sWord = Split(sLine, ";")
        If sWord.Count = 2 Then
          $CompletionList.Add("{ key: " & JS(sWord[0]) & ", value: " & JS(sWord[1]) & " }")
        Else
          $CompletionList.Add("{ key: " & JS(Trim(sLine)) & ", value: " & JS(Trim(sLine)) & " }")
        Endif
      Endif
    Next
  Endif
  WebForm._AddJavascript("$AutoTextComoleteList = [" & modGeneralMain.$CompletionList.Join(",") & "]")
  $CompletionEnable = modSettings.ShowSettingFromFIle("GeneralSettings/CompletionList")

End

Public Function GetSystemIcon(sLink As String) As String

  Dim sImage As String

  ' If sLink Begins "http://" Or If sLink Begins "https://" Then
  '   Return sLink
  ' Else If sLink Begins "icon:/" Or If sLink Begins "flag:/" Then
  '   Return "/" &/ Application.Root &/ "icon:" & Replace(sLink, "/", ":")
  ' Else
  '   Return "/" &/ Application.Root &/ sLink
  ' Endif
  sImage = WebControl._GetImageLink(sLink)
  Return sImage

End

Public Sub SetActiveForms()

  If MMain.$SISHAppMode = "HIS" Or If MMain.$SISHAppMode = "REP" Then ''remoteoptimized
    $HideFormList = modControlSub.GetDirectFillresult(modDatabase.$myConn.Exec("select fldformname from tbluserformaccess where flduserid=&1 and fldcategory=&2 and fldstatus=&3", modBasic.$lbluser, modHelpVariable.$LogInCategory, "Inactive"))                   ''
  Else
    $HideFormList = New String[]
  Endif

End

Public Sub ShowSelectedFormMenu(mnuform As WebMenu)

  If $HideFormList.Exist(mnuform.Tag) = True Then
    mnuform.Visible = False
  Endif

End

Public Sub RecordFormUse(frm As WebForm)

  Dim res As Result
  Dim xx As String

  If modDatabase.$myConn.Tables.Exist("tbljobrecord") Then
    ' xx = modString.GetDateString(modHelpVariable.$LogInTime) & ":" & xx & ":" & frm.Id
    xx = modString.GetDateString(Now()) & ":" & Session.Id & ":" & CStr(frm.Id)
    res = modDatabase.$myConn.Create("tbljobrecord")
    res["fldindex"] = xx
    res["fldfrmname"] = frm.Name
    res["fldfrmlabel"] = frm.Title
    res["flduser"] = modBasic.$lbluser
    res["fldcomp"] = modBasic.$compID
    res["fldentrytime"] = Now()
    res["fldexittime"] = ""
    res["fldpresent"] = True
    res["fldhostuser"] = CGI["HTTP_USER_AGENT"]
    res["fldhostip"] = modHelpVariable.$MACAddress
    res["fldhostname"] = CGI["SERVER_SOFTWARE"] & ":" & Application.Name & "-" & Application.Version
    res["fldhostmac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res.Update()
  Endif

End

Public Sub RecordFormExit(frm As WebForm)

  Dim res As Result
  Dim xx As String

  If modDatabase.$myConn.Tables.Exist("tbljobrecord") Then
    xx = modString.GetDateString(modHelpVariable.$LogInTime) & ":" & Session.Id & ":" & CStr(frm.Id)
    res = modDatabase.$myConn.Edit("tbljobrecord", "fldindex=&1 and fldpresent=&2", xx, True)                                                                               ''"
    If res.Available = True Then
      For Each res
        res["fldexittime"] = Now()
        res["fldpresent"] = False
        res.Update()
      Next
    Endif
  Endif

End

''------------------------ cache setting --------------------
Public Sub EnableCollectionCache()

  modBasic.DebugString("Activating Local Cache")
  modGeneralMain.$FormOpenList = New Variant[]

  modPatient.$PatProfileData = New Collection
  modNonMedical.$InvoiceTableData = New Collection
  modNonMedical.$ReceiptTableData = New Collection
  modStock.$StockCurrData = New Collection

  modFixClinic.$ExamMasterData = New Collection
  modFixLab.$TestMastereData = New Collection
  modLabTest.$LabQueryValueColl = New Collection

  modPatient.$PatDOAData = New Collection
  modPatient.$PatDODData = New Collection
  modPatient.$PatDOFollData = New Collection

  modFixLab.$TestIDFromSysConst = New Collection

  modFixLab.$TestDrugHypo = New Collection
  modFixLab.$TestdrugHyper = New Collection
  modFixLab.$TestSyndroBrady = New Collection
  modFixLab.$TestSyndroTachy = New Collection

  modFixClinic.$ExamIDFromSysConst = New Collection
  modFixClinic.$ExamSysOptionType = New Collection

  modFixClinic.$ExamDrugHypo = New Collection
  modFixClinic.$ExamdrugHyper = New Collection
  modFixClinic.$ExamSyndroBrady = New Collection
  modFixClinic.$ExamSyndroTachy = New Collection

  modFixRadio.$RadioItemCategory = New Collection
  modFixRadio.$RadioIDFromSysConst = New Collection
  modFixRadio.$RadioOptionType = New Collection
  modFixRadio.$RadioCaption = New Collection

  modLabTest.$LabIDUnitReference = New Collection
  modLabTest.$LabIDUnitAccepTRange = New Collection
  modLabTest.$LabIDUnitUnitString = New Collection
  modLabTest.$LabIDEncounter = New Collection
  modLabTest.$LabIDTestName = New Collection
  modLabTest.$LabIDTestMethod = New Collection

  modGeneral.$UserNameData = New Collection
  modGeneral.$UserCodeData = New Collection
  modGeneral.$EthnicCodeData = New Collection
  modGeneral.$UserContactData = New Collection
  modGeneral.$UserEmailData = New Collection

  modGeneral.$UserAccountData = New Collection
  modGeneral.$UserPANNoData = New Collection
  modGeneral.$UserTDSData = New Collection
  modSharingGroup.$GroupSharePercentData = New Collection
  modSharingGroup.$GroupShareAmountData = New Collection

  modDate.$LocalDateData = New Collection
  modDataRepo.$DistMunicipals = New Collection
  modExternal.$ExecValueColl = New Collection

  modNonMedical.$CashItemTarget = New Collection
  modNonMedical.$CashItemID = New Collection
  modNonMedical.$CashItemGroup = New Collection
  modNonMedical.$CashAccGroup = New Collection
  ' modNonMedical.$BillInvTypeData = New Collection
  ' modNonMedical.$BillReferenceData = New Collection

  modMedConstant.$MedBrandToGeneric = New Collection
  modMedConstant.$MedCodeFromStock = New Collection
  modMedConstant.$MedDrugFromStock = New Collection
  modMedConstant.$MedBrandFromStock = New Collection
  modMedConstant.$MedCodeFromDrug = New Collection
  modMedConstant.$MedSensiFromStock = New Collection
  modMedConstant.$MedCategFromStock = New Collection
  modMedConstant.$MedRiskFromStock = New Collection
  modMedConstant.$MedStrengthStock = New Collection
  modMedConstant.$MedStrenUntStock = New Collection
  modMedConstant.$MedDoseUntStock = New Collection
  modMedConstant.$MedNarcoticStock = New Collection

  modPharmLabel.$PharmPackVolume = New Collection
  modPharmLabel.$PharmPackVolUnit = New Collection

  modStock.$SurgiNameFromStock = New Collection
  modStock.$ExtraNameFromStock = New Collection

  modMedError.$CodeReference = New Collection
  modMedError.$DrugReference = New Collection
  modMedError.$CodeAllowPRN = New Collection
  modMedError.$CodeChemiClass = New Collection
  modMedError.$DrugAgeContra = New Collection
  modMedError.$StockPreservIn = New Collection
  modMedError.$StockAllowTabBreak = New Collection

  modMedError.$CodePregnancyPrec = New Collection
  modMedError.$CodeHepaticPrec = New Collection
  modMedError.$CodeDrugIntxn = New Collection
  modMedError.$CodeDiseaseContra = New Collection
  modMedError.$CodeAdverseRxn = New Collection
  modMedError.$CodeDrugAllergy = New Collection
  modMedError.$DrugInjecIncompat = New Collection
  modMedError.$DrugFluidIncompat = New Collection

  modDataRepo.$RepoDistrictColl = New Collection
  modDataRepo.$RepoCategoryColl = New Collection
  modDataRepo.$RepoProvinceColl = New Collection
  modDataRepo.$RepoMunicipalColl = New Collection

End

Public Sub RemovePatientCacheSelected(sItem As String)

  If sItem = "PatientData" Then
    modPatient.$PatProfileData.Clear()

    modPatient.$PatDOAData.Clear()
    modPatient.$PatDODData.Clear()
    modPatient.$PatDOFollData.Clear()

  Else If sItem = "Diagnostic" Then
    modFixClinic.$ExamMasterData.Clear()
    modFixLab.$TestMastereData.Clear()
    modLabTest.$LabQueryValueColl.Clear()

    modFixLab.$TestIDFromSysConst.Clear()
    modFixLab.$TestDrugHypo.Clear()
    modFixLab.$TestdrugHyper.Clear()
    modFixLab.$TestSyndroBrady.Clear()
    modFixLab.$TestSyndroTachy.Clear()

    modFixClinic.$ExamIDFromSysConst.Clear()
    modFixClinic.$ExamSysOptionType.Clear()

    modFixClinic.$ExamDrugHypo.Clear()
    modFixClinic.$ExamdrugHyper.Clear()
    modFixClinic.$ExamSyndroBrady.Clear()
    modFixClinic.$ExamSyndroTachy.Clear()

    modFixRadio.$RadioItemCategory.Clear()
    modFixRadio.$RadioIDFromSysConst.Clear()
    modFixRadio.$RadioOptionType.Clear()
    modFixRadio.$RadioCaption.Clear()

    modLabTest.$LabIDUnitReference.Clear()
    modLabTest.$LabIDUnitAccepTRange.Clear()
    modLabTest.$LabIDUnitUnitString.Clear()
    modLabTest.$LabIDEncounter.Clear()
    modLabTest.$LabIDTestName.Clear()
    modLabTest.$LabIDTestMethod.Clear()

  Else If sItem = "UserData" Then
    modGeneral.$UserNameData.Clear()
    modGeneral.$UserCodeData.Clear()
    modGeneral.$EthnicCodeData.Clear()
    modGeneral.$UserContactData.Clear()
    modGeneral.$UserEmailData.Clear()

  Else If sItem = "UserSharing" Then
    modGeneral.$UserAccountData.Clear()
    modGeneral.$UserPANNoData.Clear()
    modGeneral.$UserTDSData.Clear()
    modSharingGroup.$GroupSharePercentData.Clear()
    modSharingGroup.$GroupShareAmountData.Clear()

  Else If sItem = "Repository" Then
    modDataRepo.$RepoDistrictColl.Clear()
    modDataRepo.$RepoCategoryColl.Clear()
    modDataRepo.$RepoProvinceColl.Clear()
    modDataRepo.$RepoMunicipalColl.Clear()

  Else If sItem = "DateData" Then
    modDate.$LocalDateData.Clear()
    modDataRepo.$DistMunicipals.Clear()

  Else If sItem = "ExecValue" Then
    modExternal.$ExecValueColl.Clear()

  Else If sItem = "Medicine" Then
    modMedConstant.$MedBrandToGeneric.Clear()
    modMedConstant.$MedCodeFromStock.Clear()
    modMedConstant.$MedDrugFromStock.Clear()
    modMedConstant.$MedBrandFromStock.Clear()
    modMedConstant.$MedCodeFromDrug.Clear()
    modMedConstant.$MedSensiFromStock.Clear()
    modMedConstant.$MedRiskFromStock.Clear()
    modMedConstant.$MedStrengthStock.Clear()
    modMedConstant.$MedStrenUntStock.Clear()
    modMedConstant.$MedDoseUntStock.Clear()
    modMedConstant.$MedNarcoticStock.Clear()
    modMedConstant.$MedCategFromStock.Clear()

    modPharmLabel.$PharmPackVolume.Clear()
    modPharmLabel.$PharmPackVolUnit.Clear()

  Else If sItem = "Inventory" Then
    modStock.$StockCurrData.Clear()

    modStock.$SurgiNameFromStock.Clear()
    modStock.$ExtraNameFromStock.Clear()

  Else If sItem = "Account" Then
    modNonMedical.$InvoiceTableData.Clear()
    modNonMedical.$ReceiptTableData.Clear()

    modNonMedical.$CashItemTarget.Clear()
    modNonMedical.$CashItemID.Clear()
    modNonMedical.$CashItemGroup.Clear()
    modNonMedical.$CashAccGroup.Clear()
    ' modNonMedical.$BillInvTypeData.Clear()
    ' modNonMedical.$BillReferenceData.Clear()

  Else If sItem = "DrugProblems" Then
    modMedError.$CodeReference.Clear()
    modMedError.$DrugReference.Clear()
    modMedError.$CodeAllowPRN.Clear()
    modMedError.$CodeChemiClass.Clear()
    modMedError.$DrugAgeContra.Clear()
    modMedError.$StockPreservIn.Clear()
    modMedError.$StockAllowTabBreak.Clear()

    modMedError.$CodePregnancyPrec.Clear()
    modMedError.$CodeHepaticPrec.Clear()
    modMedError.$CodeDrugIntxn.Clear()
    modMedError.$CodeDiseaseContra.Clear()
    modMedError.$CodeAdverseRxn.Clear()
    modMedError.$CodeDrugAllergy.Clear()
    modMedError.$DrugInjecIncompat.Clear()
    modMedError.$DrugFluidIncompat.Clear()

  Endif

End

Public Sub CLearUserCollection()

  Dim xx As String[] = ["PatientData", "Diagnostic", "UserData", "UserSharing", "DateData", "Medicine", "Inventory", "Account", "DrugProblems", "ExecValue", "Repository"]
  Dim sItem As String
  Dim sList As String[]

  sList = SelectListView(("Select Cache Type"), xx, True)
  If sList And If sList.Count Then
    For Each sItem In sList
      RemovePatientCacheSelected(sItem)
    Next
  Endif

End

''==================== LOAD FORMS =====================
''Cash Billing Form
Public Sub LoadCashBillingForm()

  Dim hForm As FmCashBilling

  hForm = New FmCashBilling(fmCashier.Workspace1)

End

''deposit form
Public Sub LoadDepositEntryForm()

  Dim hForm As FmDeposit

  hForm = New FmDeposit(fmCashier.Workspace1)

End

''Return form
Public Sub LoadCashreturnForm()

  Dim hForm As FmBillReturn

  hForm = New FmBillReturn(fmCashier.Workspace1)

End

''Dispensing Form
Public Sub LoadDispensingForm()

  Dim hForm As FmPatPharmacy

  hForm = New FmPatPharmacy(fmDispensar.Workspace1)

End

''pharmacy return
Public Sub LoadPharmReturnForm()

  Dim hForm As FmReturn

  hForm = New FmReturn(fmDispensar.Workspace1)

End

''Due clearance
Public Sub LoadDueClearanceForm()

  ' Dim hForm As FmDueClear
  '
  ' hForm = New FmDueClear(fmDispensar.Workspace1)

End

''OPD Form
Public Sub LoadOPDClinicForm()

  Dim hForm As FmPatCliNew

  hForm = New FmPatCliNew("", 0, "", fmOfficer.Workspace1)

End

''IP Form
Public Sub LoadInpatientForm()

  Dim hForm As FmPatientMain

  hForm = New FmPatientMain("", fmOfficer.Workspace1)

End

''Delivery Form
Public Sub LoadDeliveryForm()

  Dim hForm As FmDeliveryNew

  hForm = New FmDeliveryNew("", fmOfficer.Workspace1)

End

''Procedure
Public Sub LoadProcedureForm()

  Dim hForm As FmProcedure

  hForm = New FmProcedure(fmOfficer.Workspace1)

End

''Structured: HIS
Public Sub LoadStructuredForm(sType As String, sDept As String)

  Dim hForm As FmWardHistory

  hForm = New FmWardHistory(sType, "", sDept, fmOfficer.Workspace1)

End

''Structured: Register
Public Sub LoadStructuredFormRegistry(sType As String, sDept As String)

  Dim hForm As FmWardHistory

  hForm = New FmWardHistory(sType, "", sDept, fmOfficer.Workspace1)

End

''Sample Addition Form
Public Sub LoadSampleAddForm()

  Dim hForm As FmSamplingFir

  hForm = New FmSamplingFir(fmTechnician.Workspace1)

End

''Sampling Form
Public Sub LoadSamplingForm()

  Dim hForm As FmSampling

  hForm = New FmSampling(fmTechnician.Workspace1)

End

''Reporting Form
Public Sub LoadReportingForm()

  Dim hForm As FmLabReporting

  hForm = New FmLabReporting(fmTechnician.Workspace1)

End

Public Sub LoadCashVerifyForm()

  Dim hForm As FmCashVerify

  hForm = New FmCashVerify(fmAccount.Workspace1)

End

Public Sub LoadRadioReporting()

  Dim hForm As FmRadioReporting

  hForm = New FmRadioReporting(fmTechnician.Workspace1)

End

''Maternal Register
Public Sub LoadMatNeonatalForm()

  Dim hForm As FmMatNeoExam

  hForm = New FmMatNeoExam("", fmHMISMatNeo.Workspace1)

End

Public Sub SendBugReport(sUser As String)

  Dim hForm As FmRemoteMail

  hForm = New FmRemoteMail("", "", "Bug Report", "")
  hForm.ShowModal

End
