' Gambas module file

Public $LastEncounterID As String
Public $HideFormList As String[]
Public $FormOpenList As Variant[]
Public $FormOpenQue As Integer

Public $CompletionList As String[]
Public $CompletionEnable As String

' Public Sub InsertTexEditortData(xTextArea As WebTextArea)
'
' End

Public Sub GetOpenModalForm(sWebForm As WebForm)

  If modBasic.$TabletModeEnable = "Yes" Then
    sWebForm.Move(0, 0)
  Endif

End

Public Function GetWebDepartList() As String[]

  Dim i As Integer
  Dim lstequation As String[]
  Dim xvar As String

  lstequation = New String[]
  For i = 1 To 100
    xvar = modSettings.ShowSettingFromFIle("Departments/Comp" & CStr(i))
    If xvar Then
      lstequation.Add(xvar)
    Endif
  Next
  Return lstequation

End

Public Sub SetAutoCompleteTextArea()

  Dim xPath As String
  Dim hFile As File
  Dim sLine As String
  Dim sWord As String[]

  If Exist(modHelpVariable.$docsDirectory &/ "textcompletion") Then
    xPath = modHelpVariable.$docsDirectory &/ "textcompletion"
  Else
    xPath = modBasic.$SpellCheckFile
  Endif
  $CompletionList = New String[]
  If Exist(xPath) Then
    hFile = Open xPath
    modBasic.DebugString("Open File " & xPath)
    For Each sLine In hFile.Lines
      If Trim(sLine) Then
        sWord = Split(sLine, ";")
        If sWord.Count = 2 Then
          $CompletionList.Add("{ key: " & JS(sWord[0]) & ", value: " & JS(sWord[1]) & " }")
        Else
          $CompletionList.Add("{ key: " & JS(Trim(sLine)) & ", value: " & JS(Trim(sLine)) & " }")
        Endif
      Endif
    Next
  Endif
  WebForm._AddJavascript("$AutoTextComoleteList = [" & modGeneralMain.$CompletionList.Join(",") & "]")
  $CompletionEnable = modSettings.ShowSettingFromFIle("GeneralSettings/CompletionList")

End

Public Function GetSystemIcon(sLink As String) As String

  Dim sImage As String

  ' If sLink Begins "http://" Or If sLink Begins "https://" Then
  '   Return sLink
  ' Else If sLink Begins "icon:/" Or If sLink Begins "flag:/" Then
  '   Return "/" &/ Application.Root &/ "icon:" & Replace(sLink, "/", ":")
  ' Else
  '   Return "/" &/ Application.Root &/ sLink
  ' Endif
  sImage = WebControl._GetImageLink(sLink)
  Return sImage

End

Public Sub SetActiveForms()

  If MMain.$SISHAppMode = "HIS" Or If MMain.$SISHAppMode = "REP" Then ''remoteoptimized
    $HideFormList = modControlSub.GetDirectFillresult(modDatabase.$myConn.Exec("select fldformname from tbluserformaccess where flduserid=&1 and fldcategory=&2 and fldstatus=&3", modBasic.$lbluser, modHelpVariable.$LogInCategory, "Inactive"))                   ''
  Else
    $HideFormList = New String[]
  Endif

End

Public Sub ShowSelectedFormMenu(mnuform As WebMenu)

  If $HideFormList.Exist(mnuform.Tag) = True Then
    mnuform.Visible = False
  Endif

End

Public Sub RecordFormUse(frm As WebForm)

  Dim res As Result
  Dim xx As String

  If modDatabase.$myConn.Tables.Exist("tbljobrecord") Then
    ' xx = modString.GetDateString(modHelpVariable.$LogInTime) & ":" & xx & ":" & frm.Id
    xx = modString.GetDateString(Now()) & ":" & Session.Id & ":" & CStr(frm.Id)
    res = modDatabase.$myConn.Create("tbljobrecord")
    res["fldindex"] = xx
    res["fldfrmname"] = frm.Name
    res["fldfrmlabel"] = frm.Title
    res["flduser"] = modBasic.$lbluser
    res["fldcomp"] = modBasic.$compID
    res["fldentrytime"] = Now()
    res["fldexittime"] = ""
    res["fldpresent"] = True
    res["fldhostuser"] = CGI["HTTP_USER_AGENT"]
    res["fldhostip"] = modHelpVariable.$MACAddress
    res["fldhostname"] = CGI["SERVER_SOFTWARE"] & ":" & Application.Name & "-" & Application.Version
    res["fldhostmac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res.Update()
  Endif

End

Public Sub RecordFormExit(frm As WebForm)

  Dim res As Result
  Dim xx As String

  If modDatabase.$myConn.Tables.Exist("tbljobrecord") Then
    xx = modString.GetDateString(modHelpVariable.$LogInTime) & ":" & Session.Id & ":" & CStr(frm.Id)
    res = modDatabase.$myConn.Edit("tbljobrecord", "fldindex=&1 and fldpresent=&2", xx, True)                                                                               ''"
    If res.Available = True Then
      For Each res
        res["fldexittime"] = Now()
        res["fldpresent"] = False
        res.Update()
      Next
    Endif
  Endif

End

''------------------------ cache setting --------------------
Public Sub EnableCollectionCache()

  modBasic.DebugString("Activating Local Cache")
  modGeneralMain.$FormOpenList = New Variant[]

  modLabTest.$LabQueryValueColl = New Collection

  modGeneral.$EthnicCodeData = New Collection

  modGeneral.$UserAccountData = New Collection
  modGeneral.$UserPANNoData = New Collection
  modGeneral.$UserTDSData = New Collection
  modSharingGroup.$GroupSharePercentData = New Collection
  modSharingGroup.$GroupShareAmountData = New Collection

  modDate.$LocalDateData = New Collection
  modDataRepo.$DistMunicipals = New Collection
  modExternal.$ExecValueColl = New Collection

  modDataRepo.$RepoDistrictColl = New Collection
  modDataRepo.$RepoCategoryColl = New Collection
  modDataRepo.$RepoProvinceColl = New Collection
  modDataRepo.$RepoMunicipalColl = New Collection

End

Public Sub CLearUserCollection()

  ' Dim xx As String[] = ["PatientData", "Diagnostic", "UserData", "UserSharing", "DateData", "Medicine", "Inventory", "Account", "DrugProblems", "ExecValue", "Repository"]
  ' Dim sItem As String
  ' Dim sList As String[]
  '
  ' sList = SelectListView(("Select Cache Type"), xx, True)
  ' If sList And If sList.Count Then
  '   For Each sItem In sList
  '     RemovePatientCacheSelected(sItem)
  '   Next
  ' Endif

End

''==================== LOAD FORMS =====================
''Cash Billing Form
Public Sub LoadCashBillingForm()

  Dim hForm As FmCashBilling

  hForm = New FmCashBilling(fmCashier.Workspace1)

End

''deposit form
Public Sub LoadDepositEntryForm()

  Dim hForm As FmDeposit

  hForm = New FmDeposit(fmCashier.Workspace1)

End

''Return form
Public Sub LoadCashreturnForm()

  Dim hForm As FmBillReturn

  hForm = New FmBillReturn(fmCashier.Workspace1)

End

''Dispensing Form
Public Sub LoadDispensingForm()

  Dim hForm As FmPatPharmacy

  hForm = New FmPatPharmacy(fmDispensar.Workspace1)

End

''pharmacy return
Public Sub LoadPharmReturnForm()

  Dim hForm As FmReturn

  hForm = New FmReturn(fmDispensar.Workspace1)

End

''Due clearance
Public Sub LoadDueClearanceForm()

  ' Dim hForm As FmDueClear
  '
  ' hForm = New FmDueClear(fmDispensar.Workspace1)

End

''OPD Form
Public Sub LoadOPDClinicForm()

  Dim hForm As FmPatCliNew

  hForm = New FmPatCliNew("", 0, "", "", fmOfficer.Workspace1)

End

''IP Form
Public Sub LoadInpatientForm()

  Dim hForm As FmPatientMain

  hForm = New FmPatientMain("", fmOfficer.Workspace1)

End

''Delivery Form
Public Sub LoadDeliveryForm()

  Dim hForm As FmDeliveryNew

  hForm = New FmDeliveryNew("", fmOfficer.Workspace1)

End

''Structured: HIS
Public Sub LoadStructuredForm(sType As String, sDept As String)

  Dim hForm As FmWardHistory

  hForm = New FmWardHistory(sType, "", sDept, fmOfficer.Workspace1)

End

''Structured: Register
Public Sub LoadStructuredFormRegistry(sType As String, sDept As String)

  Dim hForm As FmWardHistory

  hForm = New FmWardHistory(sType, "", sDept, fmOfficer.Workspace1)

End

''Sample Addition Form
Public Sub LoadSampleAddForm()

  Dim hForm As FmSamplingFir

  hForm = New FmSamplingFir(fmTechnician.Workspace1)

End

''Sampling Form
Public Sub LoadSamplingForm()

  Dim hForm As FmSampling

  hForm = New FmSampling(fmTechnician.Workspace1)

End

''Reporting Form
Public Sub LoadReportingForm()

  Dim hForm As FmLabReporting

  hForm = New FmLabReporting(fmTechnician.Workspace1)

End

Public Sub LoadCashVerifyForm()

  Dim hForm As FmCashVerify

  hForm = New FmCashVerify(fmAccount.Workspace1)

End

Public Sub LoadRadioReporting()

  Dim hForm As FmRadioReporting

  hForm = New FmRadioReporting(fmTechnician.Workspace1)

End

''Maternal Register
Public Sub LoadMatNeonatalForm()

  Dim hForm As FmMatNeoExam

  hForm = New FmMatNeoExam("", fmHMISMatNeo.Workspace1)

End

Public Sub SendBugReport(sUser As String)

  Dim hForm As FmRemoteMail

  hForm = New FmRemoteMail("", "", "Bug Report", "")
  hForm.ShowModal

End
