' Gambas module file

Public Sub ReadSmallData(GridView1 As WebTable, $hres As Result, $aMyFields As String[])

  Dim rxf As ResultField

  ' GridView1.Clear
  GridView1.Columns.Count = $hres.Fields.Count
  GridView1.Count = $hres.Count
  For Each rxf In $hres.Fields
    $aMyFields.Add(rxf.Name)
  Next

End

Public Sub ReadSmallMyData(GridView1 As WebTable, $hres As MyResult, $aMyFields As String[])

  Dim rxf As String

  ' GridView1.Clear
  GridView1.Columns.Count = $hres.Fields.Count
  GridView1.Count = $hres.Count
  For Each rxf In $hres.Fields
    $aMyFields.Add(rxf)
  Next

End

Public Sub GridViewDecoration(Data As WebTableData, Row As Integer)

  If Frac(Row / 2) = 0 Then 'even row
    If modBasic.$DataEvenBackColor Then
      Data.Background = modBasic.$DataEvenBackColor
    Endif
    If modBasic.$DataEvenForeColor Then
      Data.Foreground = modBasic.$DataEvenForeColor
    Endif
  Else
    If modBasic.$DataOddBackColor Then
      Data.Background = modBasic.$DataOddBackColor
    Endif
    If modBasic.$DataOddForeColor Then
      Data.Foreground = modBasic.$DataOddForeColor
    Endif
  Endif

End

Public Function GetColumnsListString(xWebTable1 As WebTable) As String

  Dim Column As Integer
  Dim xxx As String
  Dim xColumns As String[] = ["Column", "Column"]
  Dim xleft As String[]
  Dim xright As String[]

  xleft = New String[]
  xright = New String[]
  For Column = 0 To xWebTable1.Columns.Count - 1
    If Frac((Column + 1) / 2) = 0 Then
      xright.Add(CStr(Column + 1) & " : " & xWebTable1.Columns[Column].Text)
    Else
      xleft.Add(CStr(Column + 1) & " : " & xWebTable1.Columns[Column].Text)
    Endif
  Next
  If Frac((xWebTable1.Columns.Count) / 2) = 0 Then
  Else
    xright.Add("X : X")
  Endif
  xxx = modString.GetDualTableFormat(xleft, xright, xColumns)
  Return xxx

End

Public Function GetGridViewColumns(GridView1 As WebTable) As String[]

  Dim Column As Integer
  Dim xColm As String[]

  xColm = New String[]
  For Column = 0 To GridView1.Columns.Count - 1
    If GridView1.Columns[Column].Text Then
      xColm.Add(GridView1.Columns[Column].Text)
    Else
      xColm.Add("X")
    Endif
  Next
  Return xColm

End
