' Gambas module file

''========================================================
''بسم الله الرحمن الرحيم''
''+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Public $CustomFormat As String '''= "Nobel"
Public $IsPolice As Boolean
Public $IsDrugInfo As Boolean
Public $AutoIDFiscal As Boolean

Public $GovtApp As String = "Yes"
Public $Ayurveda As String = "No"  ''"Yes" if Ayurvedic EMR
Public $SISHAppMode As String = "HIS"  ''["REP"/"HIS"/"HMIS"/"Registry"/"Portal"/"Dashboard"/"TeleMed"/"Insurance"/"POL"/"PHM"/"LAB"]

Public $WebReport As String ''"Multiple" if Report selection by district/municipality/hospital. "Single" otherwise
Public $RepoReportMode As Boolean ''True if Report format as Repository
Public $WebEntry As Boolean  ''True if data entry from online (extra fields like browser and hosp code saved)

Public $isdebug As Boolean = True
Public $IsGUIApp As Boolean = True
' Public $IsNewBilling As Boolean

Public $defUnit As String = "Metric"

''HMIS/Repo Range Variables
Public $AppLogCategory As String
Public $AppLogString As String

''App Settings
Public $AppFontName As String

Public Sub InitialAppMode()

  Select MMain.$SISHAppMode
    Case "Dashboard", "REP", "TeleMed", "Insurance"
      MMain.$WebReport = "Multiple"
      MMain.$RepoReportMode = True
      MMain.$WebEntry = True

    Case "Portal", "HMIS", "Registry"
      If MMain.$GovtApp = "Yes" Then
        MMain.$WebReport = "Multiple"
        MMain.$RepoReportMode = True
        MMain.$WebEntry = True
      Else
        MMain.$WebReport = "Single"
        MMain.$RepoReportMode = False
        MMain.$WebEntry = False
      Endif

      ' Case "HIS"
      '   MMain.$WebReport = "Multiple"
      '   MMain.$RepoReportMode = True
      '   MMain.$WebEntry = True
    Case Else
      MMain.$WebReport = "Single"
      MMain.$RepoReportMode = False
      MMain.$WebEntry = False

  End Select

End

Public Sub GetApplVersionType()

  Dim xList As String[]

  xList = modDBApp.GetFIeldsinTable("tblautoid", True, modDatabase.$myConn)
  If xList.Exist("fldfiscal") = True Then
    $AutoIDFiscal = True
  Else
    $AutoIDFiscal = False
  Endif

End

Public Sub SetApplicationWideSettings()

  Dim xshel As String
  Dim xlocal As String

  Dim xfont As String
  Dim xfirday As String
  Dim xtooltip As String
  Dim xtheme As String

  xlocal = modSettings.ShowSettingFromFIle("Application/Localization")
  ' If xlocal Then
  '   System.Language = xlocal
  ' Else
  '   System.Language = "en_US.UTF-8"
  ' Endif

  'set shell to use
  xshel = modSettings.ShowSettingFromFIle("Application/ShellPath")
  ' If xshel Then
  '   System.Shell = xshel
  ' Endif

  'choose first day of week
  xfirday = modSettings.ShowSettingFromFIle("Application/WeekFirstDay")
  ' If xfirday Then
  '   System.FirstDayOfWeek = modDate.GetDayCode(xfirday)
  ' Else
  '   System.FirstDayOfWeek = gb.Sunday
  ' Endif

  'choose font for application
  xfont = modSettings.ShowSettingFromFIle("Application/ApplicationFont")
  If xfont Then
    $AppFontName = xfont
  Endif

  'choose icon theme
  xtheme = modSettings.ShowSettingFromFIle("Application/IconTheme")
  If xtheme Then
    Application.Theme = xtheme
  Else
    Application.Theme = "gambas-thin"
  Endif

  'disable tooltip
  xtooltip = modSettings.ShowSettingFromFIle("GeneralSettings/DisableToolTip")
  ' If xtooltip = "Yes" Then
  '   Application.ShowTooltips = False
  ' Endif

End
