' Gambas module file

''================== CRF ==================================
Public Function GetHashValue(sType As String, sParam As String) As String

  Dim xhash As String

  If sParam = "program" Then
    If sType = "UTI" Then
      xhash = "M8NaBxbdPO8"
    Else If sType = "BSI" Then
      xhash = "a6stuBktaPg"
    Endif

  Else If sParam = "programStage@Infection" Then
    If sType = "UTI" Then
      xhash = "xIPRGF0ngCA"
    Else If sType = "BSI" Then
      xhash = "O5Iq7H6l1T4"
    Endif
  Else If sParam = "programStage@Device" Then
    If sType = "UTI" Then
      xhash = "eH3Gw0pHKTJ"
    Else If sType = "BSI" Then
      xhash = "lkrpoqN35if"
    Endif
  Else If sParam = "programStage@Info" Then
    If sType = "UTI" Then
      xhash = "Jryk5H6TdFV"
    Else If sType = "BSI" Then
      xhash = "eG19Yil2k8x"
    Endif
  Else If sParam = "programStage@Outcome" Then
    If sType = "UTI" Then
      xhash = "xascHBoMpq5"
    Else If sType = "BSI" Then
      xhash = "BPajErcpM2T"
    Endif
  Else If sParam = "programStage@Microbiology" Then
    If sType = "UTI" Then
      xhash = "T0dyIq0Jx8e"
    Else If sType = "BSI" Then
      xhash = "jrU5AZlHQbh"
    Endif

  Else If sParam = "programStage@Susceptibility" Then
    If sType = "UTI" Then
      xhash = "tpG1qhJPitx"
    Else If sType = "BSI" Then
      xhash = "Yq812QhtVw7"
    Endif

  Endif

  Return xhash

End

Public Function GetCRFPatientHash(sParam As String) As String

  Dim xhash As String

  If sParam = "Patient ID" Then
    xhash = "ejyCdg75ujn"
  Else If sParam = "Gender" Then
    xhash = "FsNErzh7G9J"
  Else If sParam = "Date of Birth" Then
    xhash = "TkM4DJhfFBs"
  Else If sParam = "Encounter" Then
    xhash = "cRxm3jAPn5k"
  Else If sParam = "Date of Admission" Then
    xhash = "cThmCY3k76g"
  Else If sParam = "Ward of Admission" Then
    xhash = "Z6oGXGPo50v"
  Else If sParam = "Current Ward" Then
    xhash = "ksBuyhUyaCv"
  Else If sParam = "Gestational Age" Then
    xhash = "mHp8pSk7bFf"
  Else If sParam = "Birth Weight" Then
    xhash = "TqucZU2iXRH"
  Endif

  Return xhash

End

Public Function GetCRFPathoHash(sParam As String) As String

  Dim xhash As String

  If sParam = "Manifestation of Infection" Then
    xhash = "dZL3TIHpMZS"
  Else If sParam = "Manifestation of Infection Result" Then
    xhash = "qKRSCwhdhTO"
  Else If sParam = "CMI-Other Specific" Then
    xhash = "Qkqdc2SBD7z"
  Endif

  Return xhash

End

Public Function GetCRFOutcomeHash(sParam As String) As String

  Dim xhash As String

  If sParam = "14 Day Status" Then
    xhash = "UKdXMtRcMIu"
  Else If sParam = "Patient outcome" Then
    xhash = "q4VuMGLGMGN"
  Else If sParam = "Date of outcome" Then
    xhash = "DzIr6CgrMZ0"
  Else If sParam = "Case Classification" Then
    xhash = "xQsB1aDudlQ"
  Endif

  Return xhash

End

Public Function GetCRFLabsHash(sParam As String) As String

  Dim xhash As String

  ''Stage : MICROBIOLOGY SAMPLE DETAILS
  If sParam = "Sample ID" Then
    xhash = "FYKFm1N5dqu"
  Else If sParam = "Specimen Type" Then
    xhash = "Cf2FuvIKIxW"
  Else If sParam = "Other Specimen Type" Then
    xhash = "esowfjLfIWK"
  Else If sParam = "Sampling Date" Then
    xhash = "qJxAvXSYqWX"
  Else If sParam = "Reception Date" Then
    xhash = "ymGJTpyJ4AF"
  Else If sParam = "Processing Date" Then
    xhash = "rswxflqPKCI"
  Else If sParam = "Reporting Date" Then
    xhash = "fKuqQgzPuT5"
  Else If sParam = "Culture findings" Then
    xhash = "Y1X7zhGmdbp"

    ''Stage : "ANTIMICROBIOLOGY SUSCEPTIBILITY TESTING"
  Else If sParam = "Organism isolated" Then
    xhash = "uKVBZfKPJz1"
  Else If sParam = "Type of organism" Then
    xhash = "AXQ1jOR8nPG"
  Else If sParam = "Antibiotic" Then
    xhash = "vCGjdd19Al4"
  Else If sParam = "Susceptibility" Then
    xhash = "cdyULiid7m2"
  Endif

  Return xhash

End

Public Function GetUrinaryHash(sParam As String) As String

  Dim xhash As String

  ''Stage : "INVASIVE DEVICE DETAILS : URINARY CATHETER"
  If sParam = "Foley catheter at any time" Then
    xhash = "ftP52zXFXCO"
  Else If sParam = "Date catheter first inserted" Then
    xhash = "UvPfDQ7tCes"
  Else If sParam = "Foley catheter for 2 days" Then
    xhash = "gsWwg0PhM09"

    ''Stage : "UTI INFORMATION"
  Else If sParam = "Date of event" Then
    xhash = "NgHCkBLsU0n"

    ''Stage : "OUTCOME"
  Else If sParam = "Secondary BSI detected" Then
    xhash = "hqJQhh3eAlo"
  Else If sParam = "Central line/peripheral catheter" Then
    xhash = "GtSIHKib6Xk"
  Else If sParam = "Causative pathogen of secondary BSI" Then
    xhash = "MxmAKYmJix8"
  Endif

  Return xhash

End

Public Function GetBSIHash(sParam As String) As String

  Dim xhash As String

  If sParam = "BS line at any time" Then
    xhash = "K9za6dH0WFi"
  Else If sParam = "BS catheter first inserted" Then
    xhash = "W6xZrPB9yIu"
  Else If sParam = "BS catheter for 2 days" Then
    xhash = "tZcsox0wIbl"
  Else If sParam = "Type of central line in place" Then
    xhash = "qNfaPhAjtNX"
  Else If sParam = "Central Line Type Other" Then
    xhash = "nXBA9wZNSYR"
  Else If sParam = "Location of  central lines" Then
    xhash = "mHC6VW1S3L7"
  Else If sParam = "Central Line Location Other" Then
    xhash = "qtNQ4vxUO3i"

  Else If sParam = "Date of event" Then
    xhash = "NgHCkBLsU0n"

  Else If sParam = "Type of laboratory-confirmed BSI" Then
    xhash = "vUUruJPEc6m"
  Else If sParam = "BSI Attribution Period" Then
    xhash = "s8l5OdXGABh"
  Endif

  Return xhash

End

''================== DENOMINATOR ==================================
Public Function GetChapterTagCode(sChapter As String) As String

  Dim xval As String

  If sChapter = "Denominators:Adult" Then
    xval = "t5zBTjVXBHb"
  Else If sChapter = "Denominators:Newborn" Then
    xval = "P98NaagzDV5"
  Else If sChapter = "Case Reporting Form" Then
    xval = ""
  Endif

  Return xval

End

Public Function GetHAITags(sChapter As String) As Variant[]

  Dim aVar As Variant[]
  Dim xArr As String[]

  aVar = New Variant[]
  If sChapter = "Denominators:Adult" Then
    xArr = ["fldward", "Department", "NvTaX23TveS"]
    aVar.Add(xArr)
    xArr = ["flddate", "Time", "BDQ8K8Srjkv"]
    aVar.Add(xArr)
    xArr = ["fldcentral", "Integer", "VMzZONpFgfV"]
    aVar.Add(xArr)
    xArr = ["fldperipheral", "Integer", "f0tzVMWNOIK"]
    aVar.Add(xArr)
    xArr = ["fldurinary", "Integer", "hUIqYH4QE7O"]
    aVar.Add(xArr)
    xArr = ["fldtotal", "Integer", "VmAQ3OINrxT"]
    aVar.Add(xArr)
    xArr = ["fldsave", "Boolean", "Le5JnfdUcsq"]
    aVar.Add(xArr)

  Else If sChapter = "Denominators:Newborn" Then
    xArr = ["fldward", "Department", "NvTaX23TveS"]
    aVar.Add(xArr)
    xArr = ["flddate", "Time", "BDQ8K8Srjkv"]
    aVar.Add(xArr)
    xArr = ["fldcentral", "Integer", "lZNWcYuwNJy"]
    aVar.Add(xArr)
    xArr = ["fldperipheral", "Integer", "a9JQktTrGRM"]
    aVar.Add(xArr)
    xArr = ["fldurinary", "Integer", "WhKQMc6rO54"]
    aVar.Add(xArr)
    xArr = ["fldtotal", "Integer", "vlSeX8HPsXM"]
    aVar.Add(xArr)
    xArr = ["fldsave", "Boolean", "Le5JnfdUcsq"]
    aVar.Add(xArr)

  Endif

  Return aVar

End

Public Function GetHAIBirthWeightCode(sWeight As String) As String

  Dim sCode As String

  If sWeight = "< 750 Grams" Then
    sCode = "xuiB7c8oWUu"
  Else If sWeight = "751-1000 Grams" Then
    sCode = "R1w6ea18SSw"
  Else If sWeight = "1001-1500 Grams" Then
    sCode = "yigZ3Jhx9HK"
  Else If sWeight = "1501-2500 Grams" Then
    sCode = "FsNqGE43903"
  Else If sWeight = "> 2500 Grams" Then
    sCode = "PRhoRhRCxEq"
  Endif

  Return sCode

End

''================ New format ====================
Public Function GetNewChapterTagCode(sChapter As String) As String

  Dim xval As String

  If sChapter = "Denominators:Adult" Then
    xval = "ycTybPRDPfW"
  Else If sChapter = "Denominators:Newborn" Then
    xval = "P98NaagzDV5"
  Else If sChapter = "Case Reporting Form" Then
    xval = ""
  Endif

  Return xval

End

Public Function GetHAINewDeptCode(sFormat As String) As String

  Dim xx As String

  If sFormat = "ANNX2" Then
    xx = "ifu2SGbN68A"
  Else If sFormat = "MICU" Then
    xx = "WnukMXChh27"
  Endif

  Return xx

End

Public Function GetHAINewTags(sChapter As String) As Variant[]

  Dim aVar As Variant[]
  Dim xArr As String[]

  aVar = New Variant[]
  If sChapter = "Denominators:Adult" Then
    xArr = ["flddate", "Time", "SU6dEl5I7w5"]
    aVar.Add(xArr)
    xArr = ["fldcentral", "Integer", "fYyPSTrubdp"]
    aVar.Add(xArr)
    xArr = ["fldperipheral", "Integer", "yaUsduffBP8"]
    aVar.Add(xArr)
    xArr = ["fldurinary", "Integer", "ZyGaLaXnSRP"]
    aVar.Add(xArr)
    xArr = ["fldtotal", "Integer", "HxW3J4NsEI9"]
    aVar.Add(xArr)
    xArr = ["fldsave", "Boolean", "llC3IbyH2dy"]
    aVar.Add(xArr)
  Endif

  Return aVar

End
