' Gambas module file

Public Sub InstallSelectedApplication(AppList As String[])

  ' Dim xlist As String[]
  ' Dim hForm As FmTerminal

  If AppList And If AppList.Count Then
    Message.Warning("Missing Applications are: " & "<br>" & AppList.Join(Space(1)), ("OK"))

    ' If UCase(modApplication.DistributionOSName()) = "UBUNTU" Then
    '   xlist = ["sudo", "apt-get", "--no-install-recommends", "install"]
    '   xlist.Insert(AppList)
    '   hForm = New FmTerminal("Exec", xlist)
    '   hForm.ShowModal
    ' Endif
  Endif

End

Public Function EssentialAppText() As String[]

  Dim xlist As String[]
  Dim xsel As String[]

  xsel = modApplication.EssenAppList()
  If xsel.Count Then
    xlist = SelectListView("Select Application to install", xsel, True)
  Endif
  Return xlist

End

Public Function OptionalAppText() As String[]

  Dim xlist As String[]
  Dim xsel As String[]

  xsel = modApplication.OptionalAppList()
  If xsel.Count Then
    xlist = SelectListView("Select Application to install", xsel, True)
  Endif
  Return xlist

End

' ' Public Function GetFontsAllList() As String[]
' '
' '   Dim xx As String
' '   Dim xxx As String[]
' '
' '   xxx = New String[]
' '   For Each xx In Fonts
' '     xxx.Add(xx)
' '   Next
' '   Return xxx
' '
' ' End

Public Function GetEnvironmentList() As String[]

  Dim xx As String
  Dim xenv As String[]

  xenv = New String[]
  For Each xx In Application.Env
    xenv.Add(xx & " : " & Env[xx])
  Next
  Return xenv

End

Public Function GetGambasComponets() As String[]

  Dim sComp As Component
  Dim xx As String[]

  xx = New String[]
  For Each sComp In Components
    xx.Add(sComp.Name)
  Next
  Return xx

End
