' Gambas module file

Public Function GetAccountReportChartSummary(dtfir As Date, dtlast As Date, cmblocation As String, cmbvalue As String) As Variant[]

  Dim resx As Result
  Dim xcash As Float
  Dim xcred As Float

  Dim xFinal As Variant[]
  Dim xRowVal As Collection

  xFinal = New Variant[]

  xcash = 0
  xcred = 0
  resx = modDatabase.$syConn.Exec("select SUM(fldreceivedamt) as xcash,SUM(flditemamt+fldtaxamt-flddiscountamt-fldreceivedamt) as xcredit from tblpatbilldetail where fldtime>=&1 and fldtime<=&2" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast))
  If resx.Available Then
    If resx["xcash"] Then
      xcash = resx["xcash"]
    Endif
    If resx["xcredit"] Then
      xcred = resx["xcredit"]
    Endif
  Endif
  xRowVal = New Collection
  xRowVal.Add("Cash", CStr(0))
  xRowVal.Add(modReportVar.GetLocaleNumberFormat(xcash, gb.Fixed), CStr(1))
  xFinal.Add(xRowVal)

  xRowVal = New Collection
  xRowVal.Add("Credit", CStr(0))
  xRowVal.Add(modReportVar.GetLocaleNumberFormat(xcred, gb.Fixed), CStr(1))
  xFinal.Add(xRowVal)

  Return xFinal

End

Public Function GetAccountCashChartDiff(dtfir As Date, dtlast As Date, cmblocation As String, cmbvalue As String) As Variant[]

  Dim res As Result
  Dim itmamt As Float
  Dim discamt As Float
  Dim recvamt As Float

  Dim xFinal As Variant[]
  Dim xRowVal As Collection

  xFinal = New Variant[]
  itmamt = 0
  discamt = 0
  recvamt = 0
  res = modDatabase.$syConn.Exec("select SUM(flditemamt) as xitem,SUM(flddiscountamt) as xdisc,SUM(fldreceivedamt) as xrecv from tblpatbilldetail where fldtime>=&1 and fldtime<=&2 and fldbilltype=&3" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "Cash")
  If res.Available Then
    If res["xitem"] Then
      itmamt = res["xitem"]
    Endif
    If res["xdisc"] Then
      discamt = res["xdisc"]
    Endif
    If res["xrecv"] Then
      recvamt = res["xrecv"]
    Endif
  Endif

  xRowVal = New Collection
  xRowVal.Add("SubTotal", CStr(0))
  xRowVal.Add(modReportVar.GetLocaleNumberFormat(itmamt, gb.Fixed), CStr(1))
  xFinal.Add(xRowVal)

  xRowVal = New Collection
  xRowVal.Add("Discount", CStr(0))
  xRowVal.Add(modReportVar.GetLocaleNumberFormat(discamt, gb.Fixed), CStr(1))
  xFinal.Add(xRowVal)

  xRowVal = New Collection
  xRowVal.Add("Received", CStr(0))
  xRowVal.Add(modReportVar.GetLocaleNumberFormat(recvamt, gb.Fixed), CStr(1))
  xFinal.Add(xRowVal)

  Return xFinal

End

Public Function GetAccountReportChart(sSource As String, grpList As String[], dtfir As Date, dtlast As Date, cmblocation As String, cmbvalue As String, cmbinvoice As String) As Variant[]

  Dim resx As Result
  Dim xitem As Float
  Dim aval As String
  Dim bval As String

  Dim grpname As String
  Dim xFinal As Variant[]
  Dim xRowVal As Collection

  xFinal = New Variant[]

  For Each grpname In grpList

    If cmbinvoice = "Cashier" Then
      If sSource = "Credit" Then
        resx = modDatabase.$syConn.Exec("select SUM(flditemamt+fldtaxamt-flddiscountamt-fldreceivedamt) as totamt from tblpatbilldetail where fldtime>=&1 and fldtime<=&2 and fldbilltype=&3 and flduserid like &4" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "Credit", grpname)
      Else If sSource = "Cash" Then
        resx = modDatabase.$syConn.Exec("select SUM(fldreceivedamt) as totamt from tblpatbilldetail where fldtime>=&1 and fldtime<=&2 and flduserid like &3" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), grpname)
      Endif

    Else If cmbinvoice = "Location" Then
      If sSource = "Credit" Then
        resx = modDatabase.$syConn.Exec("select SUM(flditemamt+fldtaxamt-flddiscountamt-fldreceivedamt) as totamt from tblpatbilldetail where fldtime>=&1 and fldtime<=&2 and fldbilltype=&3 and fldcomp like &4" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "Credit", grpname)
      Else If sSource = "Cash" Then
        resx = modDatabase.$syConn.Exec("select SUM(fldreceivedamt) as totamt from tblpatbilldetail where fldtime>=&1 and fldtime<=&2 and fldcomp like &3" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), grpname)
      Endif

    Else If cmbinvoice = "Ledger A/C" Then
      If sSource = "Credit" Then
        resx = modDatabase.$syConn.Exec("select SUM(flditemamt+fldtaxamt-flddiscountamt-fldreceivedamt) as totamt from tblpatbilldetail where fldtime>=&1 and fldtime<=&2 and fldbilltype=&3 and fldbankname like &4" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "Credit", grpname)
      Else If sSource = "Cash" Then
        resx = modDatabase.$syConn.Exec("select SUM(fldreceivedamt) as totamt from tblpatbilldetail where fldtime>=&1 and fldtime<=&2 and fldbankname like &3" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), grpname)
      Endif

    Else If cmbinvoice = "Status" Then
      If sSource = "Credit" Then
        resx = modDatabase.$syConn.Exec("select SUM(flditemamt+fldtaxamt-flddiscountamt-fldreceivedamt) as totamt from tblpatbilldetail where fldtime>=&1 and fldtime<=&2 and fldbilltype=&3 and fldprevdeposit=&4" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "Credit", GetPatStatusCode(grpname))
      Else If sSource = "Cash" Then
        resx = modDatabase.$syConn.Exec("select SUM(fldreceivedamt) as totamt from tblpatbilldetail where fldtime>=&1 and fldtime<=&2 and fldprevdeposit=&3" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), GetPatStatusCode(grpname))
      Endif

    Else If cmbinvoice = "Category" Then
      If grpname = "Counter Billing" Then
        aval = modBillLock.InvSign("Counter Sales")
        bval = modBillLock.InvSign("Counter Return")
      Else If grpname = "Pharmacy Billing" Then
        aval = modBillLock.InvSign("Pharmacy Sales")
        bval = modBillLock.InvSign("Pharmacy Return")
      Else If grpname = "Due Clearance" Then
        aval = modBillLock.InvSign("Due Clearance")
        bval = modBillLock.InvSign("Due Clearance")
      Endif
      If sSource = "Credit" Then
        resx = modDatabase.$syConn.Exec("select SUM(flditemamt+fldtaxamt-flddiscountamt-fldreceivedamt) as totamt from tblpatbilldetail where fldtime>=&1 and fldtime<=&2 and fldbilltype=&3 and (fldbillno like &4 or fldbillno like &5)" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "Credit", aval & "%", bval & "%")
      Else If sSource = "Cash" Then
        resx = modDatabase.$syConn.Exec("select SUM(fldreceivedamt) as totamt from tblpatbilldetail where fldtime>=&1 and fldtime<=&2 and (fldbillno like &3 or fldbillno like &4)" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), aval & "%", bval & "%")
      Endif

    Endif

    xitem = 0
    If resx.Available Then
      If resx["totamt"] Then
        xitem = xitem + resx["totamt"]
      Endif

      xRowVal = New Collection
      xRowVal.Add(grpname, CStr(0))
      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xitem, gb.Fixed), CStr(1))
      xFinal.Add(xRowVal)
    Endif
  Next

  Return xFinal

End

Private Function GetPatStatusCode(xStatus As String) As Integer

  Dim xcode As Integer

  Select xStatus
    Case "Discharged", "LAMA", "Death", "Refer", "Absconder"
      xcode = 3
    Case "Admitted"
      xcode = 2
    Case Else
      xcode = 1
  End Select

  Return xcode

End

Public Function GetInvoiceReportDash(sSource As String, grpList As String[], dtfir As Date, dtlast As Date, cmblocation As String, cmbvalue As String, cmbinvoice As String) As Variant[]

  Dim sql As String
  Dim resx As Result
  Dim xdue As Float
  Dim xcash As Float
  Dim xcrdt As Float
  Dim xtax As Float
  Dim xdsc As Float

  Dim adue As Float
  Dim acash As Float
  Dim acrdt As Float
  Dim atax As Float
  Dim adsc As Float

  Dim grpname As String
  Dim xFinal As Variant[]
  Dim xRowVal As Collection

  Dim aval As String
  Dim bval As String

  xFinal = New Variant[]

  If sSource = "Invoice" Then
    sql = Subst("select SUM(flditemamt) as duemt,SUM(flddiscountamt) as disctot,SUM(fldtaxamt) as taxtot,SUM(flditemamt+fldtaxamt-flddiscountamt-fldreceivedamt) as crdtamt,SUM(fldreceivedamt) as cashamt from &1", "tblpatbilldetail")
  Else If sSource = "Receipt" Then
    sql = Subst("select SUM(flditemamt) as duemt,SUM(flddiscountamt) as disctot,SUM(fldtaxamt) as taxtot,SUM(flditemamt+fldtaxamt-flddiscountamt-fldreceivedamt) as crdtamt,SUM(fldreceivedamt) as cashamt from &1", "tbltempbilldetail")
  Endif
  adue = 0
  acash = 0
  acrdt = 0
  atax = 0
  adsc = 0
  For Each grpname In grpList

    If cmbinvoice = "Cashier" Then
      resx = modDatabase.$syConn.Exec(sql & " where fldtime>=&1 and fldtime<=&2 and flduserid like &3" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), grpname)
    Else If cmbinvoice = "Location" Then
      resx = modDatabase.$syConn.Exec(sql & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &3" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), grpname)
    Else If cmbinvoice = "Ledger A/C" Then
      resx = modDatabase.$syConn.Exec(sql & " where fldtime>=&1 and fldtime<=&2 and fldbankname like &3" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), grpname)
    Else If cmbinvoice = "Status" Then
      resx = modDatabase.$syConn.Exec(sql & " where fldtime>=&1 and fldtime<=&2 and fldprevdeposit=&3" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), GetPatStatusCode(grpname))
    Else
      If sSource = "Invoice" Then
        If grpname = "Counter Billing" Then
          aval = modBillLock.InvSign("Counter Sales")
          bval = modBillLock.InvSign("Counter Return")
        Else If grpname = "Pharmacy Billing" Then
          aval = modBillLock.InvSign("Pharmacy Sales")
          bval = modBillLock.InvSign("Pharmacy Return")
        Else If grpname = "Due Clearance" Then
          aval = modBillLock.InvSign("Due Clearance")
          bval = modBillLock.InvSign("Due Clearance")
        Endif
      Else If sSource = "Receipt" Then
        If grpname = "Counter Billing" Then
          aval = modBillLock.ReceiptSign("Counter Sales")
          bval = modBillLock.ReceiptSign("Counter Return")
        Else If grpname = "Pharmacy Billing" Then
          aval = modBillLock.ReceiptSign("Pharmacy Sales")
          bval = modBillLock.ReceiptSign("Pharmacy Return")
        Else If grpname = "Due Clearance" Then
          aval = modBillLock.ReceiptSign("Due Clearance")
          bval = modBillLock.ReceiptSign("Due Clearance")
        Endif
      Endif
      resx = modDatabase.$syConn.Exec(sql & " where fldtime>=&1 and fldtime<=&2 and (fldbillno like &3 or fldbillno like &4)" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), aval & "%", bval & "%")
    Endif

    xdue = 0
    xcash = 0
    xcrdt = 0
    xtax = 0
    xdsc = 0
    If resx.Available Then
      If resx["duemt"] Then
        xdue = xdue + resx["duemt"]
      Endif
      If resx["disctot"] Then
        xdsc = xdsc + resx["disctot"]
      Endif
      If resx["taxtot"] Then
        xtax = xtax + resx["taxtot"]
      Endif
      If resx["crdtamt"] Then
        xcrdt = xcrdt + resx["crdtamt"]
      Endif
      If resx["cashamt"] Then
        xcash = xcash + resx["cashamt"]
      Endif

      adue = adue + xdue
      atax = atax + xtax
      adsc = adsc + xdsc
      acrdt = acrdt + xcrdt
      acash = acash + xcash
      xRowVal = New Collection
      xRowVal.Add(grpname, CStr(0))
      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xdue, gb.Fixed), CStr(1))
      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xdsc, gb.Fixed), CStr(2))
      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Fixed), CStr(3))
      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xcrdt, gb.Fixed), CStr(4))
      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xcash, gb.Fixed), CStr(5))
      xFinal.Add(xRowVal)
    Endif
  Next

  xRowVal = New Collection
  xRowVal.Add("Grand Total", CStr(0))
  xRowVal.Add(modReportVar.GetLocaleNumberFormat(adue, gb.Fixed), CStr(1))
  xRowVal.Add(modReportVar.GetLocaleNumberFormat(adsc, gb.Fixed), CStr(2))
  xRowVal.Add(modReportVar.GetLocaleNumberFormat(atax, gb.Fixed), CStr(3))
  xRowVal.Add(modReportVar.GetLocaleNumberFormat(acrdt, gb.Fixed), CStr(4))
  xRowVal.Add(modReportVar.GetLocaleNumberFormat(acash, gb.Fixed), CStr(5))
  xFinal.Add(xRowVal)

  Return xFinal

End

'' Registration
Public Function GetRegisterReportDash(deptList As String[], dtfir As Date, dtlast As Date, cmblocation As String, cmbvalue As String, disctype As String) As Variant[]

  Dim genlst As String[]
  Dim res As Result
  Dim xdept As String
  Dim sgen As String
  Dim j As Integer
  Dim xtot As Integer
  Dim xall As Integer
  Dim xgrand As Integer

  Dim xFinal As Variant[]
  Dim xRowVal As Collection

  xFinal = New Variant[]
  genlst = ["New", "Follow-up"]
  xgrand = 0

  For Each xdept In deptList
    xRowVal = New Collection
    xRowVal.Add(xdept, CStr(0))

    j = 0
    xall = 0
    For Each sgen In genlst
      xtot = 0
      res = modDatabase.$syConn.Exec("select count(fldencounterval) as cnt from tblencounter where fldregdate>=&1 and fldregdate<=&2 and fldadmitlocat like &3 and flddisctype like &4 and fldfollow=&5" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), xdept, disctype, sgen)
      If res["cnt"] Then
        xtot = xtot + res["cnt"]
      Endif
      xall = xall + xtot
      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtot, 0), CStr(j + 1))
      j = j + 1
    Next
    xgrand = xgrand + xall
    xRowVal.Add(modReportVar.GetLocaleNumberFormat(xall, 0), CStr(3))

    xFinal.Add(xRowVal)
  Next

  Return xFinal

End

'' visit
Public Function GetAllVisitReportDash(consList As String[], opVisList As String[], dtfir As Date, dtlast As Date, cmblocation As String, cmbvalue As String, cmbconsultmode As String) As Variant[]

  Dim genlst As String[]
  Dim res As Result
  Dim xdept As String
  Dim sgen As String
  Dim j As Integer
  Dim xtot As Integer
  Dim xall As Integer
  Dim xgrand As Integer

  Dim xFinal As Variant[]
  Dim xRowVal As Collection

  xFinal = New Variant[]
  genlst = ["Male", "Female", "Other"]
  xgrand = 0

  For Each xdept In consList
    xRowVal = New Collection
    xRowVal.Add(xdept, CStr(0))

    j = 0
    xall = 0
    For Each sgen In genlst
      xtot = 0
      res = modDatabase.$syConn.Exec("select count(fldencounterval) as cnt from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname like &3 and fldbillingmode like &4 and fldstatus<>&5 and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where fldptsex=&6))" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), xdept, cmbconsultmode, "Cancelled", sgen)
      If res["cnt"] Then
        xtot = xtot + res["cnt"]
      Endif
      xall = xall + xtot
      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtot, 0), CStr(j + 1))
      j = j + 1
    Next
    xgrand = xgrand + xall
    xRowVal.Add(modReportVar.GetLocaleNumberFormat(xall, 0), CStr(4))

    xFinal.Add(xRowVal)
  Next

  For Each xdept In opVisList
    xRowVal = New Collection
    xRowVal.Add(xdept, CStr(0))

    j = 0
    xall = 0
    For Each sgen In genlst
      xtot = 0
      res = modDatabase.$syConn.Exec("select count(fldencounterval) as cnt from tblopvisit where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname like &3 and fldbillingmode like &4 and fldstatus<>&5 and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where fldptsex=&6))" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), xdept, cmbconsultmode, "Cancelled", sgen)                     ''
      If res["cnt"] Then
        xtot = xtot + res["cnt"]
      Endif
      xall = xall + xtot
      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtot, 0), CStr(j + 1))
      j = j + 1
    Next
    xgrand = xgrand + xall
    xRowVal.Add(modReportVar.GetLocaleNumberFormat(xall, 0), CStr(4))

    xFinal.Add(xRowVal)
  Next

  Return xFinal

End

Public Function GetInPatientReportDash(depList As String[], sPackage As String, dtfir As Date, dtlast As Date, cmblocation As String, cmbvalue As String, cmbinpatstatus As String) As Variant[]

  Dim xdept As String
  Dim res1 As Result
  Dim res2 As Result
  Dim res3 As Result

  Dim genlst As String[] = ["Male", "Female", "Other"]
  Dim sgen As String
  Dim xtot As Integer
  Dim j As Integer
  Dim xall As Integer

  Dim xFinal As Variant[]
  Dim xRowVal As Collection

  xFinal = New Variant[]
  If cmbinpatstatus = "Admissions" Then

    For Each xdept In depList
      xRowVal = New Collection
      xRowVal.Add(xdept, CStr(0))

      j = 0
      xall = 0
      For Each sgen In genlst
        xtot = 0
        res1 = modDatabase.$syConn.Exec("select count(fldencounterval) as cnt from tblencounter where flddoa>=&1 and flddoa<=&2 and flddisctype like &3 and fldpatientval in(select fldpatientval from tblpatientinfo where fldptsex like &4) and fldadmitward like &5" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), sPackage, sgen, xdept)
        If res1["cnt"] Then
          xtot = xtot + res1["cnt"]
        Endif
        xall = xall + xtot
        xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtot, 0), CStr(j + 1))
        j = j + 1
      Next

      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xall, 0), CStr(4))
      xFinal.Add(xRowVal)
    Next

  Else If cmbinpatstatus = "Exits(All)" Then

    For Each xdept In depList
      xRowVal = New Collection
      xRowVal.Add(xdept, CStr(0))

      j = 0
      xall = 0
      For Each sgen In genlst
        xtot = 0
        res2 = modDatabase.$syConn.Exec("select count(fldencounterval) as cnt from tblencounter where flddod>=&1 and flddod<=&2 and flddisctype like &3 and fldpatientval in(select fldpatientval from tblpatientinfo where fldptsex like &4) and fldcurrlocat in(select fldbed from tbldepartmentbed where flddept like &5)" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), sPackage, sgen, xdept)
        If res2["cnt"] Then
          xtot = xtot + res2["cnt"]
        Endif
        xall = xall + xtot
        xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtot, 0), CStr(j + 1))
        j = j + 1
      Next

      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xall, 0), CStr(4))
      xFinal.Add(xRowVal)
    Next

  Else If cmbinpatstatus = "Outcome" Then

    For Each xdept In depList
      xRowVal = New Collection
      xRowVal.Add(xdept, CStr(0))
      j = 0
      xall = 0
      For Each sgen In genlst
        xtot = 0
        res3 = modDatabase.$syConn.Exec("select count(fldid) as cnt from tblpatientdate where fldtime>=&1 and fldtime<=&2 and fldhead=&3 and fldencounterval in(select fldencounterval from tblencounter where flddisctype like &4 and fldpatientval in(select fldpatientval from tblpatientinfo where fldptsex like &5))" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), xdept, sPackage, sgen)
        If res3["cnt"] Then
          xtot = xtot + res3["cnt"]
        Endif
        xall = xall + xtot
        xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtot, 0), CStr(j + 1))
        j = j + 1
      Next

      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xall, 0), CStr(4))
      xFinal.Add(xRowVal)
    Next

  Endif

  Return xFinal

End

Public Function GetDiagnosticReportDash(depList As String[], dtfir As Date, dtlast As Date, cmblocation As String, cmbvalue As String, cmbdiagnostic As String) As Variant[]

  Dim xdept As String
  Dim res1 As Result
  Dim res2 As Result
  Dim res3 As Result

  Dim xsample As Integer
  Dim xreport As Integer
  Dim xverify As Integer

  Dim xmale As Integer
  Dim xfemale As Integer

  Dim xFinal As Variant[]
  Dim xRowVal As Collection

  xFinal = New Variant[]
  If cmbdiagnostic = "Diagnostic Tests" Then

    For Each xdept In depList
      xsample = 0
      xreport = 0
      xverify = 0
      res1 = modDatabase.$syConn.Exec("select count(fldid) as cnt from tblpatlabtest where fldtime_sample>=&1 and fldtime_sample<=&2 and fldtestid in(select fldtestid from tbltest where fldcategory like &3) and (fldstatus=&4 or fldstatus=&5 or fldstatus=&6)" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), xdept, "Sampled", "Reported", "Verified")
      res2 = modDatabase.$syConn.Exec("select count(fldid) as cnt from tblpatlabtest where fldtime_report>=&1 and fldtime_report<=&2 and fldtestid in(select fldtestid from tbltest where fldcategory like &3) and (fldstatus=&4 or fldstatus=&5 or fldstatus=&6)" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), xdept, "Sampled", "Reported", "Verified")
      res3 = modDatabase.$syConn.Exec("select count(fldid) as cnt from tblpatlabtest where fldtime_verify>=&1 and fldtime_verify<=&2 and fldtestid in(select fldtestid from tbltest where fldcategory like &3) and (fldstatus=&4 or fldstatus=&5 or fldstatus=&6)" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), xdept, "Sampled", "Reported", "Verified")
      If res1["cnt"] Then
        xsample = xsample + res1["cnt"]
      Endif
      If res2["cnt"] Then
        xreport = xreport + res2["cnt"]
      Endif
      If res3["cnt"] Then
        xverify = xverify + res3["cnt"]
      Endif

      xRowVal = New Collection
      xRowVal.Add(xdept, CStr(0))
      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xsample, 0), CStr(1))
      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xreport, 0), CStr(2))
      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xverify, 0), CStr(3))
      xFinal.Add(xRowVal)
    Next

  Else If cmbdiagnostic = "Radio Diagnostics" Then

    For Each xdept In depList
      xmale = 0
      xfemale = 0
      res1 = modDatabase.$syConn.Exec("select count(fldid) as cnt from tblpatradiotest where fldtime_report>=&1 and fldtime_report<=&2 and fldtestid in(select fldexamid from tblradio where fldcategory like &3) and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where fldptsex like &4)) and (fldstatus=&5 or fldstatus=&6)" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), xdept, "Male", "Reported", "Verified")
      res2 = modDatabase.$syConn.Exec("select count(fldid) as cnt from tblpatradiotest where fldtime_report>=&1 and fldtime_report<=&2 and fldtestid in(select fldexamid from tblradio where fldcategory like &3) and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where fldptsex like &4)) and (fldstatus=&5 or fldstatus=&6)" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), xdept, "Female", "Reported", "Verified")
      If res1["cnt"] Then
        xmale = xmale + res1["cnt"]
      Endif
      If res2["cnt"] Then
        xfemale = xfemale + res2["cnt"]
      Endif

      xRowVal = New Collection
      xRowVal.Add(xdept, CStr(0))
      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xmale, 0), CStr(1))
      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xfemale, 0), CStr(2))
      xRowVal.Add(modReportVar.GetLocaleNumberFormat((xmale + xfemale), 0), CStr(3))
      xFinal.Add(xRowVal)
    Next
  Endif

  Return xFinal

End

Public Function GetConfinementReportDash(delTypeList As String[], dtfir As Date, dtlast As Date, cmblocation As String, cmbvalue As String) As Variant[]

  Dim res As Result
  Dim modeList As String[] = ["Live Baby", "Fresh Still Birth", "Macerated Still Birth"]
  Dim xmode As String
  Dim xtype As String
  Dim Row As Integer
  Dim xval As Integer
  Dim xtot As Integer

  Dim xFinal As Variant[]
  Dim xRowVal As Collection

  xFinal = New Variant[]
  For Each xtype In delTypeList
    xRowVal = New Collection
    xRowVal.Add(xtype, CStr(0))

    Row = 1
    xtot = 0
    For Each xmode In modeList
      xval = 0
      res = modDatabase.$syConn.Exec("select count(fldencounterval) as col from tblconfinement where flddeltime>=&1 and flddeltime<=&2 and flddeltype=&3 and flddelresult=&4" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), xtype, xmode)
      If res.Available And If res["col"] Then
        xval = res["col"]
        xtot = xtot + xval
      Endif
      xRowVal.Add(xval, CStr(Row))
      Row = Row + 1
    Next
    xRowVal.Add(xtot, CStr(Row))
    xFinal.Add(xRowVal)

  Next
  Return xFinal

End

''================================== Inventory dashboard ===========================
Public Sub AutoDashboardExpiry(xdate As Date)

  Dim xPath As String
  Dim xcomp As String[]
  Dim RepoStr As String

  If xdate Then
    If modBasic.$ViewLockInventory = "Location" Then
      xcomp = [modBasic.$compID]
    Else If modBasic.$ViewLockInventory = "Branch" Then
      xcomp = modBasic.$branchList.Copy()
    Else
      RepoStr = modDataRepo.GetRepoLastStr()
      xcomp = modControlSub.GetDirectFillresultNoNull(modDatabase.$syConn.Exec("select distinct(fldcomp) as fldcomp from tblentry where fldexpiry<=&1 and fldqty>&2" & RepoStr, xdate, 0))
    Endif
    If xcomp And If xcomp.Count Then
      xPath = modHTMLStock.ShowTotalExpiryReport("Expired", xdate, "%", xcomp)
      modControlSub.OpenHTMLPreview("", xPath, "ReportSize")
    Endif
  Endif

End

Public Sub AutoDashboardNearExpiry(sMonth As String)

  Dim xPath As String
  Dim xdate As Date
  Dim xmon As Integer
  Dim xcomp As String[]
  Dim RepoStr As String

  xmon = modMisc.GetExpiryMonth(sMonth)
  xdate = DateAdd(Now(), gb.Month, xmon)
  If xdate Then
    If modBasic.$ViewLockInventory = "Location" Then
      xcomp = [modBasic.$compID]
    Else If modBasic.$ViewLockInventory = "Branch" Then
      xcomp = modBasic.$branchList.Copy()
    Else
      RepoStr = modDataRepo.GetRepoLastStr()
      xcomp = modControlSub.GetDirectFillresultNoNull(modDatabase.$syConn.Exec("select distinct(fldcomp) as fldcomp from tblentry where fldexpiry>&1 and fldexpiry<=&2 and fldqty>&3" & RepoStr, Now(), xdate, 0))
    Endif
    If xcomp And If xcomp.Count Then
      xPath = modHTMLStock.ShowTotalExpiryReport("Near Expiry", xdate, "%", xcomp)
      modControlSub.OpenHTMLPreview("", xPath, "ReportSize")
    Endif
  Endif

End
