' Gambas module file

Public Function GetPublicRegistrationSumm(dtfir As Date, dtlast As Date, cmblocation As String, cmbvalue As String) As Variant[]

  Dim res1 As Result
  Dim res2 As Result
  Dim res3 As Result
  Dim res4 As Result
  Dim xtot As Integer

  Dim xFinal As Variant[]
  Dim xRowVal As Collection

  xFinal = New Variant[]
  ''HI
  xRowVal = New Collection
  xRowVal.Add("Health Insurance", CStr(0))
  xtot = 0
  res1 = modDatabase.$syConn.Exec("select count(fldencounterval) as cnt from tblencounter where fldregdate>=&1 and fldregdate<=&2 and flddisctype in(select fldtype from tbldiscount where fldreference=&3)" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "Claim Code")
  If res1.Available And If res1["cnt"] Then
    xtot = res1["cnt"]
  Endif
  xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtot, 0), CStr(1))
  xFinal.Add(xRowVal)

  ''SSF
  xRowVal = New Collection
  xRowVal.Add("SSF", CStr(0))
  xtot = 0
  res2 = modDatabase.$syConn.Exec("select count(fldencounterval) as cnt from tblencounter where fldregdate>=&1 and fldregdate<=&2 and flddisctype in(select fldtype from tbldiscount where (fldreference=&3 or fldreference=&4 or fldreference=&5))" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "Accident SSF", "Medical SSF", "Critical SSF")
  If res2.Available And If res2["cnt"] Then
    xtot = res2["cnt"]
  Endif
  xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtot, 0), CStr(1))
  xFinal.Add(xRowVal)

  ''Other Credit
  xRowVal = New Collection
  xRowVal.Add("Other Credit", CStr(0))
  xtot = 0
  res3 = modDatabase.$syConn.Exec("select count(fldencounterval) as cnt from tblencounter where fldregdate>=&1 and fldregdate<=&2 and flddisctype in(select fldtype from tbldiscount where fldbilltype=&3 and (fldreference<>&4 and fldreference<>&5 and fldreference<>&6 and fldreference<>&7))" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "Credit", "Claim Code", "Accident SSF", "Medical SSF", "Critical SSF")
  If res3.Available And If res3["cnt"] Then
    xtot = res3["cnt"]
  Endif
  xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtot, 0), CStr(1))
  xFinal.Add(xRowVal)

  ''Other Credit
  xRowVal = New Collection
  xRowVal.Add("Cash Schemes", CStr(0))
  xtot = 0
  res4 = modDatabase.$syConn.Exec("select count(fldencounterval) as cnt from tblencounter where fldregdate>=&1 and fldregdate<=&2 and flddisctype in(select fldtype from tbldiscount where fldbilltype=&3)" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "Cash")
  If res4.Available And If res4["cnt"] Then
    xtot = res4["cnt"]
  Endif
  xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtot, 0), CStr(1))
  xFinal.Add(xRowVal)

  Return xFinal

End

Public Function GetPublicDepartmentSumm(dtfir As Date, dtlast As Date, sMater As Boolean, cmblocation As String, cmbvalue As String) As Variant[]

  Dim genlst As String[] = ["Male", "Female"]
  Dim sgen As String

  Dim res1 As Result
  Dim res2 As Result
  Dim res3 As Result
  Dim res4 As Result
  Dim res5 As Result
  Dim xtot As Integer
  Dim j As Integer

  Dim xFinal As Variant[]
  Dim xRowVal As Collection
  Dim sql As String

  xFinal = New Variant[]

  ''consultation
  xRowVal = New Collection
  xRowVal.Add("Out Patients", CStr(0))
  j = 0
  For Each sgen In genlst
    res1 = modDatabase.$syConn.Exec("select count(fldencounterval) as cnt from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldstatus<>&3 and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where fldptsex=&4))" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "Cancelled", sgen)
    xtot = 0
    If res1.Available And If res1["cnt"] Then
      xtot = res1["cnt"]
    Endif
    xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtot, 0), CStr(j + 1))
    j = j + 1
  Next
  xFinal.Add(xRowVal)

  ''op visit
  sql = db.Subst("(select fldvalue from tblhmissetting where fldtype=&1 and fldcategory=&2)", "OutPatientDept", "Emergency")
  xRowVal = New Collection
  xRowVal.Add("Emergency", CStr(0))
  j = 0
  For Each sgen In genlst
    xtot = 0
    res2 = modDatabase.$syConn.Exec("select count(fldencounterval) as cnt from tblopvisit where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname in " & sql & " and fldstatus<>&3 and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where fldptsex=&4))" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "Cancelled", sgen)                     ''
    If res2.Available And If res2["cnt"] Then
      xtot = res2["cnt"]
    Endif
    xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtot, 0), CStr(j + 1))
    j = j + 1
  Next
  xFinal.Add(xRowVal)

  ''admission
  xRowVal = New Collection
  xRowVal.Add("Admission", CStr(0))
  j = 0
  For Each sgen In genlst
    xtot = 0
    res3 = modDatabase.$syConn.Exec("select count(fldencounterval) as cnt from tblencounter where flddoa>=&1 and flddoa<=&2 and fldpatientval in(select fldpatientval from tblpatientinfo where fldptsex like &3)" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), sgen)
    If res3.Available And If res3["cnt"] Then
      xtot = res3["cnt"]
    Endif
    xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtot, 0), CStr(j + 1))
    j = j + 1
  Next
  xFinal.Add(xRowVal)

  ''discharge
  xRowVal = New Collection
  xRowVal.Add("Discharge and Exits", CStr(0))
  j = 0
  For Each sgen In genlst
    xtot = 0
    res4 = modDatabase.$syConn.Exec("select count(fldencounterval) as cnt from tblencounter where flddod>=&1 and flddod<=&2 and fldpatientval in(select fldpatientval from tblpatientinfo where fldptsex like &3)" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), sgen)
    If res4.Available And If res4["cnt"] Then
      xtot = res4["cnt"]
    Endif
    xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtot, 0), CStr(j + 1))
    j = j + 1
  Next
  xFinal.Add(xRowVal)

  ''maternity
  If sMater = True Then
    xRowVal = New Collection
    xRowVal.Add("New Born", CStr(0))
    j = 0
    For Each sgen In genlst
      xtot = 0
      res5 = modDatabase.$syConn.Exec("select count(fldbabypatno) as cnt from tblconfinement where flddeltime>=&1 and flddeltime<=&2 and fldbabypatno in(select fldpatientval from tblpatientinfo where fldptsex like &3)" & modDataRepo.GetWhereStringRepo(cmblocation, cmbvalue), modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), sgen)
      If res5.Available And If res5["cnt"] Then
        xtot = res5["cnt"]
      Endif
      xRowVal.Add(modReportVar.GetLocaleNumberFormat(xtot, 0), CStr(j + 1))
      j = j + 1
    Next
    xFinal.Add(xRowVal)
  Endif

  Return xFinal

End

Public Function SubGetRadiologyDash(sList As String[], xdtfir As Date, xdtlast As Date, sLocaType As String, sLocation As String) As Variant[]

  Dim sql As String
  Dim xval As String
  Dim res As Result
  Dim res1 As Result
  Dim xcnt As Integer
  Dim acnt As Integer

  Dim xFinal As Variant[]
  Dim xRowVal As Collection

  xFinal = New Variant[]
  For Each xval In sList
    xRowVal = New Collection
    sql = db.Subst("(select fldvalue from tblhmissetting where fldtype=&1 and fldcategory=&2)", "DiagnosticServices", xval)

    xcnt = 0
    res = modDatabase.$syConn.Exec("select SUM(flditemqty) as tot from tblpatbilling where fldtime>=&1 and fldtime<=&2 and flditemname in " & sql & " and fldsave=&3" & modDataRepo.GetWhereStringRepo(sLocaType, sLocation), modDate.StartSqlDate(xdtfir), modDate.EndSqlDate(xdtlast), True)
    If res.Available And If res["tot"] Then
      xcnt = res["tot"]
    Endif
    xRowVal.Add(xval, CStr(0))
    xRowVal.Add(xcnt, CStr(1))
    xFinal.Add(xRowVal)
  Next

  acnt = 0
  xRowVal = New Collection
  res1 = modDatabase.$syConn.Exec("select SUM(flditemqty) as xtot from tblpatbilling where fldtime>=&1 and fldtime<=&2 and flditemtype=&3 and fldsave=&4" & modDataRepo.GetWhereStringRepo(sLocaType, sLocation), modDate.StartSqlDate(xdtfir), modDate.EndSqlDate(xdtlast), "Diagnostic Tests", True)
  If res1.Available And If res1["xtot"] Then
    acnt = res1["xtot"]
  Endif
  xRowVal.Add("Laboratory Services", CStr(0))
  xRowVal.Add(acnt, CStr(1))
  xFinal.Add(xRowVal)

  Return xFinal

End

Public Function SubGetConsultationDash(xdtfir As Date, xdtlast As Date, sLocaType As String, sLocation As String) As Variant[]

  Dim res As Result
  Dim xFinal As Variant[]
  Dim xRowVal As Collection
  Dim xtot As Integer

  xFinal = New Variant[]
  res = modDatabase.$syConn.Exec("select fldconsultname,count(fldencounterval) as cnt from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldstatus<>&3" & modDataRepo.GetWhereStringRepo(sLocaType, sLocation) & " GROUP BY fldconsultname", modDate.StartSqlDate(xdtfir), modDate.EndSqlDate(xdtlast), "Cancelled")
  If res.Available Then
    For Each res
      xRowVal = New Collection
      xRowVal.Add(res["fldconsultname"], CStr(0))
      xtot = 0
      If res["cnt"] Then
        xtot = res["cnt"]
      Endif
      xRowVal.Add(xtot, CStr(1))
      xFinal.Add(xRowVal)
    Next
  Endif

  Return xFinal

End

Public Function SubGetCurrOccupancyDash(sType As String, sLocaType As String, sLocation As String) As Variant[]

  Dim res As Result
  Dim xFinal As Variant[]
  Dim xRowVal As Collection
  Dim strmnt As String
  Dim xtot As Integer
  Dim xoccp As Integer
  Dim xmaint As Integer

  xFinal = New Variant[]
  strmnt = db.Subst("SUM(CASE WHEN fldstatus = &1 THEN 1 ELSE NULL END) as mntcnt", "Maintenance")
  If sType = "Service" Then
    res = modDatabase.$syConn.Exec("select fldservice as xformat,count(fldbed) as xtotl,count(fldencounterval) as xcnt," & strmnt & " from tbldepartmentbed where (fldstatus IS NULL or fldstatus=&1 or fldstatus=&2)" & modDataRepo.GetWhereStringRepo(sLocaType, sLocation) & " GROUP BY fldservice", "Active", "Maintenance")
  Else
    res = modDatabase.$syConn.Exec("select flddept as xformat,count(fldbed) as xtotl,count(fldencounterval) as xcnt," & strmnt & " from tbldepartmentbed where (fldstatus IS NULL or fldstatus=&1 or fldstatus=&2)" & modDataRepo.GetWhereStringRepo(sLocaType, sLocation) & " GROUP BY flddept", "Active", "Maintenance")
  Endif
  If res.Available Then
    For Each res
      xtot = 0
      xoccp = 0
      xmaint = 0

      xRowVal = New Collection
      xRowVal.Add(res["xformat"], CStr(0))
      If res["xtotl"] Then
        xtot = res["xtotl"]
      Endif
      If res["xcnt"] Then
        xoccp = res["xcnt"]
      Endif
      If res["mntcnt"] Then
        xmaint = res["mntcnt"]
      Endif
      xRowVal.Add(xtot, CStr(1))
      xRowVal.Add(xoccp + xmaint, CStr(2))
      xFinal.Add(xRowVal)
    Next
  Endif

  Return xFinal

End
