' Gambas module file

Public Function ReceiptReportBillingRangeSummary(sFormat As String, $con As Connection, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tbltempbilldetail As String) As String                                ''

  Dim $BillingReport As CReportHTML
  Dim RepoPath As String
  Dim xparam As String
  Dim RepoVal As Float

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("CATEGORY"), ("COUNT"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("Receipt Summary", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  RepoVal = modReceiptAll.GetReceiptReportBillingRangeSummary($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tbltempbilldetail)
  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function ReceiptReportBillingRangeUserDetail(sFormat As String, $con As Connection, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tbltempbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim RepoPath As String
  Dim xparam As String
  Dim RepoVal As Float

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("USER"), ("COUNT"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH"), ("DEPOSIT")], "", "")
  $BillingReport.UserData.Add("User Collection", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  RepoVal = modReceiptAll.GetReceiptReportBillingRangeUserDetail($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tbltempbilldetail)
  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function ReceiptReportBillingRangeUserBrief(sFormat As String, $con As Connection, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tbltempbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim RepoPath As String
  Dim xparam As String
  Dim RepoVal As Float

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("USER"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH"), ("DEPOSIT")], "", "")
  $BillingReport.UserData.Add("User Collection", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  RepoVal = modReceiptAll.GetReceiptReportBillingRangeUserBrief($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tbltempbilldetail)
  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function ReceiptReportBillingRangeGroupDetail(sFormat As String, $con As Connection, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tblpatbilling As String, $tbltempbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim RepoPath As String
  Dim xparam As String
  Dim RepoVal As Float

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("CATEGORY"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("Group Collection", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  RepoVal = modReceiptAll.GetReceiptReportBillingRangeGroupDetail($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tbltempbilldetail)
  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function ReceiptReportBillingRangeGroupBrief(sFormat As String, $con As Connection, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tblpatbilling As String, $tbltempbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim RepoPath As String
  Dim xparam As String
  Dim RepoVal As Float

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("CATEGORY"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("Group Collection", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  RepoVal = modReceiptAll.GetReceiptReportBillingRangeGroupBrief($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tbltempbilldetail)
  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function ReceiptReportBillingRangeAccount(sFormat As String, $con As Connection, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tbltempbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim RepoPath As String
  Dim xparam As String
  Dim RepoVal As Float

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("CATEGORY"), ("COUNT"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("Receipt Summary", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  RepoVal = modReceiptAll.GetReceiptReportBillingRangeAccount($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tbltempbilldetail)
  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function ReceiptReportBillingRangeTaxDiscount(sFormat As String, $con As Connection, sType As String, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tbltempbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim RepoPath As String
  Dim xparam As String
  Dim RepoVal As Float

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("DATE"), ("ENCID"), ("PATIENT"), ("TYPE"), ("INVOICE"), ("GROSS"), UCase(sType), ("LABEL"), ("ACCOUNT"), ("CASHIER")], "", "")
  $BillingReport.UserData.Add(sType & " Report", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  RepoVal = modReceiptAll.GetReceiptReportBillingRangeTaxDiscount($BillingReport, sFormat, $con, sType, bill1, bill2, sLocaType, sLocation, $tbltempbilldetail)
  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function ReceiptReportBillingRangeLocation(sFormat As String, $con As Connection, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tblpatbilling As String, $tbltempbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim RepoPath As String
  Dim xparam As String
  Dim RepoVal As Float

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("CATEGORY"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("Group Collection", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  RepoVal = modReceiptAll.GetReceiptReportBillingRangeLocation($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tbltempbilldetail)
  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function ReceiptReportBillingRangeCashCredit(sFormat As String, $con As Connection, sType As String, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tbltempbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim RepoPath As String
  Dim xparam As String
  Dim RepoVal As Float

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  If sType = "Cash" Then
    $BillingReport = New CReportHTML([("DATE"), ("ENCID"), ("PATIENT"), ("TYPE"), ("INVOICE"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("NET"), ("RECEIVED"), ("QR-PAY"), ("HAND-CASH"), ("ACCOUNT")], "", "")
  Else
    $BillingReport = New CReportHTML([("DATE"), ("ENCID"), ("PATIENT"), ("TYPE"), ("INVOICE"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("NET"), ("RECEIVED"), ("ACCOUNT")], "", "")
  Endif
  $BillingReport.UserData.Add(sType & " Report", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  RepoVal = modReceiptAll.GetReceiptReportBillingRangeCashCredit($BillingReport, sFormat, $con, sType, bill1, bill2, sLocaType, sLocation, $tbltempbilldetail)
  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function ReceiptInvoiceReportDetailByMismatch(sFormat As String, $con As Connection, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tblpatbilling As String, $tbltempbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim RepoPath As String
  Dim xparam As String
  Dim RepoVal As Float

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("InvNo"), ("ItemTotal"), ("InvTotal"), ("TotDiff"), ("ItemTax"), ("InvTax"), ("TaxDiff"), ("ItemDisc"), ("InvDisc"), ("DiscDiff"), ("ItemCash"), ("InvCash"), ("CashDiff")], "", "")
  $BillingReport.UserData.Add("Receipt Tax/Discount Mismatch", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  RepoVal = modReceiptAll.GetReceiptInvoiceReportDetailByMismatch($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tbltempbilldetail)
  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End
