' Gambas module file

' Private $ProgressBar1 As ProgressBar

''=================== SERVICE SUMMARY =======================
Public Function GetFieldServiceSummary(sFormat As String) As String

  Dim xval As String

  If sFormat = "Category" Then
    xval = "flditemtype"
  Else If sFormat = "RatePlan" Then
    xval = "fldbillingmode"
  Else If sFormat = "Package" Then
    xval = "flddisctype"
  Else If sFormat = "Payable" Then
    xval = "fldpayto"
  Else If sFormat = "Referral" Then
    xval = "fldrefer"
  Else If sFormat = "LedgerA/C" Then
    xval = "fldacledger"
  Else If sFormat = "TargetComp" Then
    xval = "fldtarget"
  Else If sFormat = "PatLocation" Then
    xval = "fldcurrlocat"
  Else If sFormat = "BillType" Then
    xval = "fldbilltype"
  Else If sFormat = "Hospital" Then
    xval = "fldhospcode"
  Endif
  Return xval

End

Private Function GetDepartQuery(sType As String) As String

  Dim yval As String

  If sType = "OPD" Then
    yval = db.Subst("fldcurrlocat in(select flddept from tbldepartment where fldcateg=&1 or fldcateg=&2)", "Consultation", "OPD Visit")
  Else If sType = "IPD" Then
    yval = db.Subst("fldcurrlocat not in(select flddept from tbldepartment where fldcateg=&1 or fldcateg=&2)", "Consultation", "OPD Visit")
  Endif
  Return yval

End

Public Function ShowProfitReport($con As Connection, sType As String, dt1 As Date, dt2 As Date, aCompLst As String[], sLocaType As String, sLocation As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res2 As Result
  Dim rs3 As Result
  Dim sCompLst As String[]
  Dim j As Integer

  Dim sale As Float
  Dim cost As Float
  Dim prof As Float

  Dim salqty As Float
  Dim salcost As Float
  Dim salamt As Float

  Dim RepoStr As String

  ' If MMain.$IsGUIApp = True Then
  '   $ProgressBar1 = modAppSupport.FindWorkProgressBar(modHelpVariable.$LogInCategory)
  '   $ProgressBar1.Tag = "Const"
  ' Endif

  sCompLst = aCompLst.Copy()
  $BillingReport = New CReportHTML([("PARTICULARS"), ("QTY"), ("TOTAL(CP)"), ("TOTAL(SP)"), ("PROFIT")], "", "")
  $BillingReport.UserData.Add("PROFIT ESTIMATION: " & sType, "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")
  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)

  For j = 0 To sCompLst.Count - 1
    sCompLst[j] = "'" & sCompLst[j] & "'"
  Next

  sale = 0
  cost = 0
  prof = 0
  res2 = $con.Exec("select distinct(flditemname) as col from tblpatbilling where fldtime>=&1 and fldtime<=&2 and flditemtype=&3 and fldcomp in(" & sCompLst.Join(",") & ")" & RepoStr & " ORDER BY flditemname ASC", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sType)                                                  ''
  For Each res2
    rs3 = $con.Exec("select flditemno,flditemqty,flditemrate,flddiscper,fldtaxper from tblpatbilling where fldtime>=&1 and fldtime<=&2 and flditemname=&3 and flditemtype=&4 and fldcomp in(" & sCompLst.Join(",") & ")" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), res2["col"], sType)
    salqty = 0
    salcost = 0
    salamt = 0
    For Each rs3
      salqty = salqty + rs3["flditemqty"]
      salcost = salcost + modStock.GetAverageCostPriceByStockNo(rs3["flditemno"], dt2) * rs3["flditemqty"]
      salamt = salamt + rs3["flditemrate"] * rs3["flditemqty"] * (1 - rs3["flddiscper"] / 100) * (1 + rs3["fldtaxper"] / 100)
    Next

    sale = sale + salamt
    cost = cost + salcost
    prof = sale - cost

    With asx
      .Add(res2["col"])
      .Add(modReportVar.GetLocaleNumberFormat(salqty, -2))
      .Add(modReportVar.GetLocaleNumberFormat(salcost, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(salamt, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(salamt - salcost, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

    ' If MMain.$IsGUIApp = True Then
    '   $ProgressBar1.Value = (res2.Index + 1) / res2.Count
    '   Wait
    ' Endif
  Next

  With asx
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
  End With
  $BillingReport.Add(asx)
  asx.Clear()
  With asx
    .Add("<b>GRAND TOTAL</b>")
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(cost, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(sale, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(prof, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  $BillingReport.AddSummary("Cost Price Calculation: " & modBasic.$InvReportCost)
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowProfitReportMapped($con As Connection, sType As String, dt1 As Date, dt2 As Date, aCompLst As String[], sLocaType As String, sLocation As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res2 As Result
  Dim rs3 As Result
  Dim sCompLst As String[]
  Dim j As Integer

  Dim sale As Float
  Dim cost As Float
  Dim prof As Float

  Dim salqty As Float
  Dim salcost As Float
  Dim salamt As Float

  Dim RepoStr As String

  ' If MMain.$IsGUIApp = True Then
  '   $ProgressBar1 = modAppSupport.FindWorkProgressBar(modHelpVariable.$LogInCategory)
  '   $ProgressBar1.Tag = "Const"
  ' Endif

  sCompLst = aCompLst.Copy()
  $BillingReport = New CReportHTML([("PARTICULARS"), ("QTY"), ("TOTAL(CP)"), ("TOTAL(SP)"), ("PROFIT")], "", "")
  $BillingReport.UserData.Add("PROFIT ESTIMATION: " & sType, "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")
  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)

  For j = 0 To sCompLst.Count - 1
    sCompLst[j] = "'" & sCompLst[j] & "'"
  Next

  sale = 0
  cost = 0
  prof = 0
  res2 = $con.Exec("select distinct(flditemname) as col from tblpatbilling where fldtime>=&1 and fldtime<=&2 and flditemtype=&3 and fldcomp in(" & sCompLst.Join(",") & ") and flditemname in(select flditemname from tblstockrate)" & RepoStr & " ORDER BY flditemname ASC", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sType)                                                  ''
  For Each res2
    rs3 = $con.Exec("select flditemno,flditemqty,flditemrate,flddiscper,fldtaxper from tblpatbilling where fldtime>=&1 and fldtime<=&2 and flditemname=&3 and flditemtype=&4 and fldcomp in(" & sCompLst.Join(",") & ")" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), res2["col"], sType)
    salqty = 0
    salcost = 0
    salamt = 0
    For Each rs3
      salqty = salqty + rs3["flditemqty"]
      salcost = salcost + modStock.GetAverageCostPriceByStockNo(rs3["flditemno"], dt2) * rs3["flditemqty"]
      salamt = salamt + rs3["flditemrate"] * rs3["flditemqty"] * (1 - rs3["flddiscper"] / 100) * (1 + rs3["fldtaxper"] / 100)
    Next

    sale = sale + salamt
    cost = cost + salcost
    prof = sale - cost

    With asx
      .Add(res2["col"])
      .Add(modReportVar.GetLocaleNumberFormat(salqty, -2))
      .Add(modReportVar.GetLocaleNumberFormat(salcost, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(salamt, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(salamt - salcost, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

    ' If MMain.$IsGUIApp = True Then
    '   $ProgressBar1.Value = (res2.Index + 1) / res2.Count
    '   Wait
    ' Endif
  Next

  With asx
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
  End With
  $BillingReport.Add(asx)
  asx.Clear()
  With asx
    .Add("<b>GRAND TOTAL</b>")
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(cost, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(sale, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(prof, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  $BillingReport.AddSummary("Cost Price Calculation: " & modBasic.$InvReportCost)
  Return $BillingReport.NewHTMLPath()

End

''======================== cross tab ============================
Public Function SummaryAccountCrossTab(conn As Connection, dt1 As Date, dt2 As Date, sRow As String, sColumn As String, sItemType As String, sVariable As String, sInvoiced As Boolean, sLocaType As String, sLocation As String) As String

  Dim $BillingReport As CReportHTML
  Dim sql1 As String
  Dim asx As New String[0]
  Dim res1 As Result
  Dim xval As String
  Dim yval As String
  Dim xcol As String[]
  Dim valtotal As Float
  Dim coltot As Float
  Dim categList As String[]
  Dim xcateg As String

  Dim res2 As Result
  Dim dtlst As Date[]
  Dim dt As Date
  Dim i As Integer
  Dim xtot As Float
  Dim aTot As Integer

  Dim res As Result
  Dim sql As String
  Dim xstr As String

  Dim chapdate As String
  Dim xfirdate As Date
  Dim xlasdate As Date
  Dim xdateform As String

  xstr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  Select sRow
    Case "Gender", "Surname", "District", "Municipality", "Service Rank", "Service Unit", "Service Category", "Last Status", "Visit Type", "Visit Mode"
      xval = modMedReports.GetColumnEncounter(sRow)
    Case Else
      xval = modRHTMLSummary.GetFieldServiceSummary(sRow)
  End Select

  yval = modRHTMLSummary.GetFieldServiceSummary(sColumn)
  sql = Subst("select distinct(&1) as fld from tblpatbilling", yval)
  If sInvoiced = True Then
    res = conn.Exec(sql & " where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4" & xstr & " ORDER BY " & yval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
  Else
    res = conn.Exec(sql & " where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4" & xstr & " ORDER BY " & yval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
  Endif

  xcol = New String[]
  If res.Available Then
    xcol.Add(UCase(sRow))
    For Each res
      If res["fld"] Then
        xcol.Add(res["fld"])
      Endif
    Next
    xcol.Add("TOTAL")
  Endif

  $BillingReport = New CReportHTML(xcol, "", "")
  $BillingReport.UserData.Add("Category: " & sItemType & "  Value: " & sVariable, "PARAM1")
  $BillingReport.UserData.Add("Date: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")

  If sRow = "Year" Or If sRow = "Month" Or If sRow = "Date" Then
    xdateform = modSettings.ShowSettingFromFIle("HealthReport/RowDateFormat")

    If sRow = "Year" Then
      If modBasic.$DateFormat = "BS Date" Then
        dtlst = modDate.GetSelectDateBSArrayBetween(gb.Year, dt1, dt2)
      Else
        dtlst = modDate.GetSelectDateArrayBetween(gb.Year, dt1, dt2)
      Endif
    Else If sRow = "Month" Then
      If modBasic.$DateFormat = "BS Date" Then
        dtlst = modDate.GetSelectDateBSArrayBetween(gb.Month, dt1, dt2)
      Else
        dtlst = modDate.GetSelectDateArrayBetween(gb.Month, dt1, dt2)
      Endif
    Else
      dtlst = modDate.GetDateArrayBetween(dt1, dt2)
    Endif
    coltot = 0
    For Each dt In dtlst
      If sRow = "Year" Then
        If modBasic.$DateFormat = "BS Date" Then
          chapdate = modDate.DateFormatViewBS(dt, "YearOnly")
          xfirdate = modDate.StartSqlYearBS(dt)
          xlasdate = modDate.EndSqlYearBS(dt)
        Else
          chapdate = Format(dt, "yyyy")
          xfirdate = modDate.StartSqlYear(dt)
          xlasdate = modDate.EndSqlYear(dt)
        Endif
      Else If sRow = "Month" Then
        If modBasic.$DateFormat = "BS Date" Then
          chapdate = modDate.DateFormatViewBS(dt, "YearMonth")
          xfirdate = modDate.StartSqlMonthBS(dt)
          xlasdate = modDate.EndSqlMonthBS(dt)
        Else
          chapdate = Format(dt, "mmm yyyy")
          xfirdate = modDate.StartSqlMonth(dt)
          xlasdate = modDate.EndSqlMonth(dt)
        Endif
      Else
        If xdateform = "Disable" Then
          chapdate = modReportVar.GetDateTimeReport(dt, gb.MediumDate)
        Else
          chapdate = modReportVar.GetDateTimeReport(dt, gb.MediumDate) & " [" & modDate.GetWeekDay(dt) & "]"
        Endif
        xfirdate = modDate.StartSqlDate(dt)
        xlasdate = modDate.EndSqlDate(dt)
      Endif

      With asx
        .Add(chapdate)
        xtot = 0
        For i = 1 To xcol.Count - 2
          valtotal = 0
          If sInvoiced = True Then
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4 and " & yval & " like &5" & xstr, True, xfirdate, xlasdate, sItemType, xcol[i])
          Else
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4 and " & yval & " like &5" & xstr, True, xfirdate, xlasdate, sItemType, xcol[i])
          Endif
          If sVariable = "GrossTotal" Then
            If res2["duemt"] Then
              valtotal = res2["duemt"]
            Endif
          Else If sVariable = "Discount" Then
            If res2["disctot"] Then
              valtotal = res2["disctot"]
            Endif
          Else If sVariable = "TotalTax" Then
            If res2["taxtot"] Then
              valtotal = res2["taxtot"]
            Endif
          Else If sVariable = "CashTotal" Then
            If res2["xcash"] Then
              valtotal = res2["xcash"]
            Endif
          Else If sVariable = "CreditTotal" Then
            If res2["xcredit"] Then
              valtotal = res2["xcredit"]
            Endif
          Else
            If res2["netamt"] Then
              valtotal = res2["netamt"]
            Endif
          Endif
          If valtotal Then
            xtot = xtot + valtotal
            .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
          Else
            .Add(modReportVar.GetLocaleNumberFormat(0, 0))
          Endif
        Next
        coltot = coltot + xtot
        .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next

    With asx
      .Add("GRAND TOTAL")
      For i = 1 To xcol.Count - 2
        .Add("")
      Next
      .Add(modReportVar.GetLocaleNumberFormat(coltot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

    With asx
      .Add("TOTAL(Actual)")
      aTot = 0
      For i = 1 To xcol.Count - 2
        valtotal = 0
        If sInvoiced = True Then
          res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4 and " & yval & " like &5" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcol[i])
        Else
          res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4 and " & yval & " like &5" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcol[i])
        Endif
        If sVariable = "GrossTotal" Then
          If res2["duemt"] Then
            valtotal = res2["duemt"]
          Endif
        Else If sVariable = "Discount" Then
          If res2["disctot"] Then
            valtotal = res2["disctot"]
          Endif
        Else If sVariable = "TotalTax" Then
          If res2["taxtot"] Then
            valtotal = res2["taxtot"]
          Endif
        Else If sVariable = "CashTotal" Then
          If res2["xcash"] Then
            valtotal = res2["xcash"]
          Endif
        Else If sVariable = "CreditTotal" Then
          If res2["xcredit"] Then
            valtotal = res2["xcredit"]
          Endif
        Else
          If res2["netamt"] Then
            valtotal = res2["netamt"]
          Endif
        Endif
        If valtotal Then
          aTot = aTot + valtotal
          .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
        Else
          .Add(modReportVar.GetLocaleNumberFormat(0, 0))
        Endif
      Next
      .Add(modReportVar.GetLocaleNumberFormat(aTot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Else
    If sRow = "Last Status" Or If sRow = "Visit Type" Or If sRow = "Visit Mode" Then
      sql1 = Subst("select distinct(&1) as col from tblencounter", xval)
      If sInvoiced = True Then
        res1 = conn.Exec(sql1 & " where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4)" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
      Else
        res1 = conn.Exec(sql1 & " where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4)" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
      Endif
    Else If sRow = "Gender" Or If sRow = "Surname" Or If sRow = "District" Or If sRow = "Municipality" Or If sRow = "Service Rank" Or If sRow = "Service Unit" Or If sRow = "Service Category" Then
      sql1 = Subst("select distinct(&1) as col from tblpatientinfo", xval)
      If sInvoiced = True Then
        res1 = conn.Exec(sql1 & " where fldpatientval in(select fldpatientval from tblencounter where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
      Else
        res1 = conn.Exec(sql1 & " where fldpatientval in(select fldpatientval from tblencounter where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
      Endif
    Else
      sql1 = Subst("select distinct(&1) as col from tblpatbilling", xval)
      If sInvoiced = True Then
        res1 = conn.Exec(sql1 & " where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
      Else
        res1 = conn.Exec(sql1 & " where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
      Endif
    Endif
    If res1.Available Then
      categList = modControlSub.GetDirectFillresultNoNull(res1)
      coltot = 0
      For Each xcateg In categList
        With asx
          .Add(xcateg)
          xtot = 0
          For i = 1 To xcol.Count - 2
            valtotal = 0
            If sRow = "Last Status" Or If sRow = "Visit Type" Or If sRow = "Visit Mode" Then
              If sInvoiced = True Then
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4 and fldencounterval in(select fldencounterval from tblencounter where " & xval & " like &5) and " & yval & " like &6" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcateg, xcol[i])
              Else
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4 and fldencounterval in(select fldencounterval from tblencounter where " & xval & " like &5) and " & yval & " like &6" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcateg, xcol[i])
              Endif
            Else If sRow = "Gender" Or If sRow = "Surname" Or If sRow = "District" Or If sRow = "Municipality" Or If sRow = "Service Rank" Or If sRow = "Service Unit" Or If sRow = "Service Category" Then
              If sInvoiced = True Then
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4 and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where " & xval & " like &5)) and " & yval & " like &6" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcateg, xcol[i])
              Else
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4 and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where " & xval & " like &5)) and " & yval & " like &6" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcateg, xcol[i])
              Endif
            Else
              If sInvoiced = True Then
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4 and " & xval & " like &5 and " & yval & " like &6" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcateg, xcol[i])
              Else
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4 and " & xval & " like &5 and " & yval & " like &6" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcateg, xcol[i])
              Endif
            Endif
            If sVariable = "GrossTotal" Then
              If res2["duemt"] Then
                valtotal = res2["duemt"]
              Endif
            Else If sVariable = "Discount" Then
              If res2["disctot"] Then
                valtotal = res2["disctot"]
              Endif
            Else If sVariable = "TotalTax" Then
              If res2["taxtot"] Then
                valtotal = res2["taxtot"]
              Endif
            Else If sVariable = "CashTotal" Then
              If res2["xcash"] Then
                valtotal = res2["xcash"]
              Endif
            Else If sVariable = "CreditTotal" Then
              If res2["xcredit"] Then
                valtotal = res2["xcredit"]
              Endif
            Else
              If res2["netamt"] Then
                valtotal = res2["netamt"]
              Endif
            Endif
            If valtotal Then
              xtot = xtot + valtotal
              .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
            Else
              .Add(modReportVar.GetLocaleNumberFormat(0, 0))
            Endif
          Next
          coltot = coltot + xtot
          .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Next

      With asx
        .Add("GRAND TOTAL")
        For i = 1 To xcol.Count - 2
          .Add("")
        Next
        .Add(modReportVar.GetLocaleNumberFormat(coltot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()

      With asx
        .Add("TOTAL(Actual)")
        aTot = 0
        For i = 1 To xcol.Count - 2
          valtotal = 0
          If sInvoiced = True Then
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4 and " & yval & " like &5" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcol[i])
          Else
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4 and " & yval & " like &5" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcol[i])
          Endif
          If sVariable = "GrossTotal" Then
            If res2["duemt"] Then
              valtotal = res2["duemt"]
            Endif
          Else If sVariable = "Discount" Then
            If res2["disctot"] Then
              valtotal = res2["disctot"]
            Endif
          Else If sVariable = "TotalTax" Then
            If res2["taxtot"] Then
              valtotal = res2["taxtot"]
            Endif
          Else If sVariable = "CashTotal" Then
            If res2["xcash"] Then
              valtotal = res2["xcash"]
            Endif
          Else If sVariable = "CreditTotal" Then
            If res2["xcredit"] Then
              valtotal = res2["xcredit"]
            Endif
          Else
            If res2["netamt"] Then
              valtotal = res2["netamt"]
            Endif
          Endif
          If valtotal Then
            aTot = aTot + valtotal
            .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
          Else
            .Add(modReportVar.GetLocaleNumberFormat(0, 0))
          Endif
        Next
        .Add(modReportVar.GetLocaleNumberFormat(aTot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

  Endif
  Return $BillingReport.NewHTMLPath()

End

Public Function SummaryAccountOPIPCrossTab(conn As Connection, dt1 As Date, dt2 As Date, sRow As String, sItemType As String, sVariable As String, sInvoiced As Boolean, sLocaType As String, sLocation As String) As String

  Dim $BillingReport As CReportHTML
  Dim sql1 As String
  Dim asx As New String[0]
  Dim res1 As Result
  Dim xval As String
  Dim yval As String
  Dim xcol As String[] = ["OPD", "IPD"]
  Dim xdept As String
  Dim valtotal As Float
  Dim coltot As Float
  Dim categList As String[]
  Dim xcateg As String

  Dim res2 As Result
  Dim dtlst As Date[]
  Dim dt As Date

  Dim xtot As Float
  Dim aTot As Integer
  Dim xstr As String

  Dim chapdate As String
  Dim xfirdate As Date
  Dim xlasdate As Date
  Dim xdateform As String

  xstr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  Select sRow
    Case "Gender", "Surname", "District", "Municipality", "Service Rank", "Service Unit", "Service Category", "Last Status", "Visit Type", "Visit Mode"
      xval = modMedReports.GetColumnEncounter(sRow)
    Case Else
      xval = modRHTMLSummary.GetFieldServiceSummary(sRow)
  End Select

  $BillingReport = New CReportHTML([UCase(sRow), "OPD", "IPD", "TOTAL"], "", "")
  $BillingReport.UserData.Add("Category: " & sItemType & "  Value: " & sVariable, "PARAM1")
  $BillingReport.UserData.Add("Date: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")

  If sRow = "Year" Or If sRow = "Month" Or If sRow = "Date" Then
    xdateform = modSettings.ShowSettingFromFIle("HealthReport/RowDateFormat")

    If sRow = "Year" Then
      If modBasic.$DateFormat = "BS Date" Then
        dtlst = modDate.GetSelectDateBSArrayBetween(gb.Year, dt1, dt2)
      Else
        dtlst = modDate.GetSelectDateArrayBetween(gb.Year, dt1, dt2)
      Endif
    Else If sRow = "Month" Then
      If modBasic.$DateFormat = "BS Date" Then
        dtlst = modDate.GetSelectDateBSArrayBetween(gb.Month, dt1, dt2)
      Else
        dtlst = modDate.GetSelectDateArrayBetween(gb.Month, dt1, dt2)
      Endif
    Else
      dtlst = modDate.GetDateArrayBetween(dt1, dt2)
    Endif
    coltot = 0
    For Each dt In dtlst
      If sRow = "Year" Then
        If modBasic.$DateFormat = "BS Date" Then
          chapdate = modDate.DateFormatViewBS(dt, "YearOnly")
          xfirdate = modDate.StartSqlYearBS(dt)
          xlasdate = modDate.EndSqlYearBS(dt)
        Else
          chapdate = Format(dt, "yyyy")
          xfirdate = modDate.StartSqlYear(dt)
          xlasdate = modDate.EndSqlYear(dt)
        Endif
      Else If sRow = "Month" Then
        If modBasic.$DateFormat = "BS Date" Then
          chapdate = modDate.DateFormatViewBS(dt, "YearMonth")
          xfirdate = modDate.StartSqlMonthBS(dt)
          xlasdate = modDate.EndSqlMonthBS(dt)
        Else
          chapdate = Format(dt, "mmm yyyy")
          xfirdate = modDate.StartSqlMonth(dt)
          xlasdate = modDate.EndSqlMonth(dt)
        Endif
      Else
        If xdateform = "Disable" Then
          chapdate = modReportVar.GetDateTimeReport(dt, gb.MediumDate)
        Else
          chapdate = modReportVar.GetDateTimeReport(dt, gb.MediumDate) & " [" & modDate.GetWeekDay(dt) & "]"
        Endif
        xfirdate = modDate.StartSqlDate(dt)
        xlasdate = modDate.EndSqlDate(dt)
      Endif

      With asx
        .Add(chapdate)
        xtot = 0
        For Each xdept In xcol
          valtotal = 0
          yval = GetDepartQuery(xdept)
          If sInvoiced = True Then
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4 and " & yval & xstr, True, xfirdate, xlasdate, sItemType)
          Else
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4 and " & yval & xstr, True, xfirdate, xlasdate, sItemType)
          Endif
          If sVariable = "GrossTotal" Then
            If res2["duemt"] Then
              valtotal = res2["duemt"]
            Endif
          Else If sVariable = "Discount" Then
            If res2["disctot"] Then
              valtotal = res2["disctot"]
            Endif
          Else If sVariable = "TotalTax" Then
            If res2["taxtot"] Then
              valtotal = res2["taxtot"]
            Endif
          Else If sVariable = "CashTotal" Then
            If res2["xcash"] Then
              valtotal = res2["xcash"]
            Endif
          Else If sVariable = "CreditTotal" Then
            If res2["xcredit"] Then
              valtotal = res2["xcredit"]
            Endif
          Else
            If res2["netamt"] Then
              valtotal = res2["netamt"]
            Endif
          Endif
          If valtotal Then
            xtot = xtot + valtotal
            .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
          Else
            .Add(modReportVar.GetLocaleNumberFormat(0, 0))
          Endif
        Next
        coltot = coltot + xtot
        .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next

    With asx
      .Add("GRAND TOTAL")
      For Each xdept In xcol
        .Add("")
      Next
      .Add(modReportVar.GetLocaleNumberFormat(coltot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

    With asx
      .Add("TOTAL(Actual)")
      aTot = 0
      For Each xdept In xcol
        valtotal = 0
        yval = GetDepartQuery(xdept)
        If sInvoiced = True Then
          res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4 and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
        Else
          res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4 and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
        Endif
        If sVariable = "GrossTotal" Then
          If res2["duemt"] Then
            valtotal = res2["duemt"]
          Endif
        Else If sVariable = "Discount" Then
          If res2["disctot"] Then
            valtotal = res2["disctot"]
          Endif
        Else If sVariable = "TotalTax" Then
          If res2["taxtot"] Then
            valtotal = res2["taxtot"]
          Endif
        Else If sVariable = "CashTotal" Then
          If res2["xcash"] Then
            valtotal = res2["xcash"]
          Endif
        Else If sVariable = "CreditTotal" Then
          If res2["xcredit"] Then
            valtotal = res2["xcredit"]
          Endif
        Else
          If res2["netamt"] Then
            valtotal = res2["netamt"]
          Endif
        Endif
        If valtotal Then
          aTot = aTot + valtotal
          .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
        Else
          .Add(modReportVar.GetLocaleNumberFormat(0, 0))
        Endif
      Next
      .Add(modReportVar.GetLocaleNumberFormat(aTot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Else
    If sRow = "Last Status" Or If sRow = "Visit Type" Or If sRow = "Visit Mode" Then
      sql1 = Subst("select distinct(&1) as col from tblencounter", xval)
      If sInvoiced = True Then
        res1 = conn.Exec(sql1 & " where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4)" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
      Else
        res1 = conn.Exec(sql1 & " where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4)" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
      Endif
    Else If sRow = "Gender" Or If sRow = "Surname" Or If sRow = "District" Or If sRow = "Municipality" Or If sRow = "Service Rank" Or If sRow = "Service Unit" Or If sRow = "Service Category" Then
      sql1 = Subst("select distinct(&1) as col from tblpatientinfo", xval)
      If sInvoiced = True Then
        res1 = conn.Exec(sql1 & " where fldpatientval in(select fldpatientval from tblencounter where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
      Else
        res1 = conn.Exec(sql1 & " where fldpatientval in(select fldpatientval from tblencounter where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
      Endif
    Else
      sql1 = Subst("select distinct(&1) as col from tblpatbilling", xval)
      If sInvoiced = True Then
        res1 = conn.Exec(sql1 & " where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
      Else
        res1 = conn.Exec(sql1 & " where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
      Endif
    Endif
    If res1.Available Then
      categList = modControlSub.GetDirectFillresultNoNull(res1)
      coltot = 0
      For Each xcateg In categList
        With asx
          .Add(xcateg)
          xtot = 0
          For Each xdept In xcol
            valtotal = 0
            yval = GetDepartQuery(xdept)
            If sRow = "Last Status" Or If sRow = "Visit Type" Or If sRow = "Visit Mode" Then
              If sInvoiced = True Then
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4 and fldencounterval in(select fldencounterval from tblencounter where " & xval & " like &5) and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcateg)
              Else
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4 and fldencounterval in(select fldencounterval from tblencounter where " & xval & " like &5) and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcateg)
              Endif
            Else If sRow = "Gender" Or If sRow = "Surname" Or If sRow = "District" Or If sRow = "Municipality" Or If sRow = "Service Rank" Or If sRow = "Service Unit" Or If sRow = "Service Category" Then
              If sInvoiced = True Then
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4 and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where " & xval & " like &5)) and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcateg)
              Else
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4 and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where " & xval & " like &5)) and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcateg)
              Endif
            Else
              If sInvoiced = True Then
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4 and " & xval & " like &5 and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcateg)
              Else
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4 and " & xval & " like &5 and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType, xcateg)
              Endif
            Endif
            If sVariable = "GrossTotal" Then
              If res2["duemt"] Then
                valtotal = res2["duemt"]
              Endif
            Else If sVariable = "Discount" Then
              If res2["disctot"] Then
                valtotal = res2["disctot"]
              Endif
            Else If sVariable = "TotalTax" Then
              If res2["taxtot"] Then
                valtotal = res2["taxtot"]
              Endif
            Else If sVariable = "CashTotal" Then
              If res2["xcash"] Then
                valtotal = res2["xcash"]
              Endif
            Else If sVariable = "CreditTotal" Then
              If res2["xcredit"] Then
                valtotal = res2["xcredit"]
              Endif
            Else
              If res2["netamt"] Then
                valtotal = res2["netamt"]
              Endif
            Endif
            If valtotal Then
              xtot = xtot + valtotal
              .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
            Else
              .Add(modReportVar.GetLocaleNumberFormat(0, 0))
            Endif
          Next
          coltot = coltot + xtot
          .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Next

      With asx
        .Add("GRAND TOTAL")
        For Each xdept In xcol
          .Add("")
        Next
        .Add(modReportVar.GetLocaleNumberFormat(coltot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()

      With asx
        .Add("TOTAL(Actual)")
        aTot = 0
        For Each xdept In xcol
          valtotal = 0
          yval = GetDepartQuery(xdept)
          If sInvoiced = True Then
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemtype like &4 and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
          Else
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemtype like &4 and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItemType)
          Endif
          If sVariable = "GrossTotal" Then
            If res2["duemt"] Then
              valtotal = res2["duemt"]
            Endif
          Else If sVariable = "Discount" Then
            If res2["disctot"] Then
              valtotal = res2["disctot"]
            Endif
          Else If sVariable = "TotalTax" Then
            If res2["taxtot"] Then
              valtotal = res2["taxtot"]
            Endif
          Else If sVariable = "CashTotal" Then
            If res2["xcash"] Then
              valtotal = res2["xcash"]
            Endif
          Else If sVariable = "CreditTotal" Then
            If res2["xcredit"] Then
              valtotal = res2["xcredit"]
            Endif
          Else
            If res2["netamt"] Then
              valtotal = res2["netamt"]
            Endif
          Endif
          If valtotal Then
            aTot = aTot + valtotal
            .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
          Else
            .Add(modReportVar.GetLocaleNumberFormat(0, 0))
          Endif
        Next
        .Add(modReportVar.GetLocaleNumberFormat(aTot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

  Endif
  Return $BillingReport.NewHTMLPath()

End

''=================== Group cross tabs ==========================
Public Function SummaryGroupAccCrossTab(conn As Connection, dt1 As Date, dt2 As Date, sRow As String, sColumn As String, sGroup As String, sVariable As String, sInvoiced As Boolean, sLocaType As String, sLocation As String) As String

  Dim $BillingReport As CReportHTML
  Dim sql1 As String
  Dim asx As New String[0]
  Dim res1 As Result
  Dim xval As String
  Dim yval As String
  Dim xcol As String[]
  Dim valtotal As Float
  Dim coltot As Float
  Dim categList As String[]
  Dim xcateg As String

  Dim res2 As Result
  Dim dtlst As Date[]
  Dim dt As Date
  Dim i As Integer
  Dim xtot As Float
  Dim aTot As Integer

  Dim res As Result
  Dim sql As String
  Dim xstr As String

  Dim chapdate As String
  Dim xfirdate As Date
  Dim xlasdate As Date
  Dim xdateform As String

  xstr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  Select sRow
    Case "Gender", "Surname", "District", "Municipality", "Service Rank", "Service Unit", "Service Category", "Last Status", "Visit Type", "Visit Mode"
      xval = modMedReports.GetColumnEncounter(sRow)
    Case Else
      xval = modRHTMLSummary.GetFieldServiceSummary(sRow)
  End Select

  yval = modRHTMLSummary.GetFieldServiceSummary(sColumn)
  sql = Subst("select distinct(&1) as fld from tblpatbilling", yval)
  If sInvoiced = True Then
    res = conn.Exec(sql & " where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4)" & xstr & " ORDER BY " & yval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
  Else
    res = conn.Exec(sql & " where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4)" & xstr & " ORDER BY " & yval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
  Endif

  xcol = New String[]
  If res.Available Then
    xcol.Add(UCase(sRow))
    For Each res
      If res["fld"] Then
        xcol.Add(res["fld"])
      Endif
    Next
    xcol.Add("TOTAL")
  Endif

  $BillingReport = New CReportHTML(xcol, "", "")
  $BillingReport.UserData.Add("Group: " & sGroup & "  Value: " & sVariable, "PARAM1")
  $BillingReport.UserData.Add("Date: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")

  If sRow = "Year" Or If sRow = "Month" Or If sRow = "Date" Then
    xdateform = modSettings.ShowSettingFromFIle("HealthReport/RowDateFormat")

    If sRow = "Year" Then
      If modBasic.$DateFormat = "BS Date" Then
        dtlst = modDate.GetSelectDateBSArrayBetween(gb.Year, dt1, dt2)
      Else
        dtlst = modDate.GetSelectDateArrayBetween(gb.Year, dt1, dt2)
      Endif
    Else If sRow = "Month" Then
      If modBasic.$DateFormat = "BS Date" Then
        dtlst = modDate.GetSelectDateBSArrayBetween(gb.Month, dt1, dt2)
      Else
        dtlst = modDate.GetSelectDateArrayBetween(gb.Month, dt1, dt2)
      Endif
    Else
      dtlst = modDate.GetDateArrayBetween(dt1, dt2)
    Endif
    coltot = 0
    For Each dt In dtlst
      If sRow = "Year" Then
        If modBasic.$DateFormat = "BS Date" Then
          chapdate = modDate.DateFormatViewBS(dt, "YearOnly")
          xfirdate = modDate.StartSqlYearBS(dt)
          xlasdate = modDate.EndSqlYearBS(dt)
        Else
          chapdate = Format(dt, "yyyy")
          xfirdate = modDate.StartSqlYear(dt)
          xlasdate = modDate.EndSqlYear(dt)
        Endif
      Else If sRow = "Month" Then
        If modBasic.$DateFormat = "BS Date" Then
          chapdate = modDate.DateFormatViewBS(dt, "YearMonth")
          xfirdate = modDate.StartSqlMonthBS(dt)
          xlasdate = modDate.EndSqlMonthBS(dt)
        Else
          chapdate = Format(dt, "mmm yyyy")
          xfirdate = modDate.StartSqlMonth(dt)
          xlasdate = modDate.EndSqlMonth(dt)
        Endif
      Else
        If xdateform = "Disable" Then
          chapdate = modReportVar.GetDateTimeReport(dt, gb.MediumDate)
        Else
          chapdate = modReportVar.GetDateTimeReport(dt, gb.MediumDate) & " [" & modDate.GetWeekDay(dt) & "]"
        Endif
        xfirdate = modDate.StartSqlDate(dt)
        xlasdate = modDate.EndSqlDate(dt)
      Endif

      With asx
        .Add(chapdate)
        xtot = 0
        For i = 1 To xcol.Count - 2
          valtotal = 0
          If sInvoiced = True Then
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & yval & " like &5" & xstr, True, xfirdate, xlasdate, sGroup, xcol[i])
          Else
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & yval & " like &5" & xstr, True, xfirdate, xlasdate, sGroup, xcol[i])
          Endif
          If sVariable = "GrossTotal" Then
            If res2["duemt"] Then
              valtotal = res2["duemt"]
            Endif
          Else If sVariable = "Discount" Then
            If res2["disctot"] Then
              valtotal = res2["disctot"]
            Endif
          Else If sVariable = "TotalTax" Then
            If res2["taxtot"] Then
              valtotal = res2["taxtot"]
            Endif
          Else If sVariable = "CashTotal" Then
            If res2["xcash"] Then
              valtotal = res2["xcash"]
            Endif
          Else If sVariable = "CreditTotal" Then
            If res2["xcredit"] Then
              valtotal = res2["xcredit"]
            Endif
          Else
            If res2["netamt"] Then
              valtotal = res2["netamt"]
            Endif
          Endif
          If valtotal Then
            xtot = xtot + valtotal
            .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
          Else
            .Add(modReportVar.GetLocaleNumberFormat(0, 0))
          Endif
        Next
        coltot = coltot + xtot
        .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next

    With asx
      .Add("GRAND TOTAL")
      For i = 1 To xcol.Count - 2
        .Add("")
      Next
      .Add(modReportVar.GetLocaleNumberFormat(coltot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

    With asx
      .Add("TOTAL(Actual)")
      aTot = 0
      For i = 1 To xcol.Count - 2
        valtotal = 0
        If sInvoiced = True Then
          res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & yval & " like &5" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcol[i])
        Else
          res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & yval & " like &5" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcol[i])
        Endif
        If sVariable = "GrossTotal" Then
          If res2["duemt"] Then
            valtotal = res2["duemt"]
          Endif
        Else If sVariable = "Discount" Then
          If res2["disctot"] Then
            valtotal = res2["disctot"]
          Endif
        Else If sVariable = "TotalTax" Then
          If res2["taxtot"] Then
            valtotal = res2["taxtot"]
          Endif
        Else If sVariable = "CashTotal" Then
          If res2["xcash"] Then
            valtotal = res2["xcash"]
          Endif
        Else If sVariable = "CreditTotal" Then
          If res2["xcredit"] Then
            valtotal = res2["xcredit"]
          Endif
        Else
          If res2["netamt"] Then
            valtotal = res2["netamt"]
          Endif
        Endif
        If valtotal Then
          aTot = aTot + valtotal
          .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
        Else
          .Add(modReportVar.GetLocaleNumberFormat(0, 0))
        Endif
      Next
      .Add(modReportVar.GetLocaleNumberFormat(aTot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Else
    If sRow = "Last Status" Or If sRow = "Visit Type" Or If sRow = "Visit Mode" Then
      sql1 = Subst("select distinct(&1) as col from tblencounter", xval)
      If sInvoiced = True Then
        res1 = conn.Exec(sql1 & " where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
      Else
        res1 = conn.Exec(sql1 & " where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
      Endif
    Else If sRow = "Gender" Or If sRow = "Surname" Or If sRow = "District" Or If sRow = "Municipality" Or If sRow = "Service Rank" Or If sRow = "Service Unit" Or If sRow = "Service Category" Then
      sql1 = Subst("select distinct(&1) as col from tblpatientinfo", xval)
      If sInvoiced = True Then
        res1 = conn.Exec(sql1 & " where fldpatientval in(select fldpatientval from tblencounter where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4)))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
      Else
        res1 = conn.Exec(sql1 & " where fldpatientval in(select fldpatientval from tblencounter where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4)))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
      Endif
    Else
      sql1 = Subst("select distinct(&1) as col from tblpatbilling", xval)
      If sInvoiced = True Then
        res1 = conn.Exec(sql1 & " where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4)" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
      Else
        res1 = conn.Exec(sql1 & " where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4)" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
      Endif
    Endif
    If res1.Available Then
      categList = modControlSub.GetDirectFillresultNoNull(res1)
      coltot = 0
      For Each xcateg In categList
        With asx
          .Add(xcateg)
          xtot = 0
          For i = 1 To xcol.Count - 2
            valtotal = 0
            If sRow = "Last Status" Or If sRow = "Visit Type" Or If sRow = "Visit Mode" Then
              If sInvoiced = True Then
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and fldencounterval in(select fldencounterval from tblencounter where " & xval & " like &5) and " & yval & " like &6" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcateg, xcol[i])
              Else
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and fldencounterval in(select fldencounterval from tblencounter where " & xval & " like &5) and " & yval & " like &6" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcateg, xcol[i])
              Endif
            Else If sRow = "Gender" Or If sRow = "Surname" Or If sRow = "District" Or If sRow = "Municipality" Or If sRow = "Service Rank" Or If sRow = "Service Unit" Or If sRow = "Service Category" Then
              If sInvoiced = True Then
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where " & xval & " like &5)) and " & yval & " like &6" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcateg, xcol[i])
              Else
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where " & xval & " like &5)) and " & yval & " like &6" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcateg, xcol[i])
              Endif
            Else
              If sInvoiced = True Then
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & xval & " like &5 and " & yval & " like &6" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcateg, xcol[i])
              Else
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & xval & " like &5 and " & yval & " like &6" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcateg, xcol[i])
              Endif
            Endif
            If sVariable = "GrossTotal" Then
              If res2["duemt"] Then
                valtotal = res2["duemt"]
              Endif
            Else If sVariable = "Discount" Then
              If res2["disctot"] Then
                valtotal = res2["disctot"]
              Endif
            Else If sVariable = "TotalTax" Then
              If res2["taxtot"] Then
                valtotal = res2["taxtot"]
              Endif
            Else If sVariable = "CashTotal" Then
              If res2["xcash"] Then
                valtotal = res2["xcash"]
              Endif
            Else If sVariable = "CreditTotal" Then
              If res2["xcredit"] Then
                valtotal = res2["xcredit"]
              Endif
            Else
              If res2["netamt"] Then
                valtotal = res2["netamt"]
              Endif
            Endif
            If valtotal Then
              xtot = xtot + valtotal
              .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
            Else
              .Add(modReportVar.GetLocaleNumberFormat(0, 0))
            Endif
          Next
          coltot = coltot + xtot
          .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Next

      With asx
        .Add("GRAND TOTAL")
        For i = 1 To xcol.Count - 2
          .Add("")
        Next
        .Add(modReportVar.GetLocaleNumberFormat(coltot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()

      With asx
        .Add("TOTAL(Actual)")
        aTot = 0
        For i = 1 To xcol.Count - 2
          valtotal = 0
          If sInvoiced = True Then
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & yval & " like &5" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcol[i])
          Else
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & yval & " like &5" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcol[i])
          Endif
          If sVariable = "GrossTotal" Then
            If res2["duemt"] Then
              valtotal = res2["duemt"]
            Endif
          Else If sVariable = "Discount" Then
            If res2["disctot"] Then
              valtotal = res2["disctot"]
            Endif
          Else If sVariable = "TotalTax" Then
            If res2["taxtot"] Then
              valtotal = res2["taxtot"]
            Endif
          Else If sVariable = "CashTotal" Then
            If res2["xcash"] Then
              valtotal = res2["xcash"]
            Endif
          Else If sVariable = "CreditTotal" Then
            If res2["xcredit"] Then
              valtotal = res2["xcredit"]
            Endif
          Else
            If res2["netamt"] Then
              valtotal = res2["netamt"]
            Endif
          Endif
          If valtotal Then
            aTot = aTot + valtotal
            .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
          Else
            .Add(modReportVar.GetLocaleNumberFormat(0, 0))
          Endif
        Next
        .Add(modReportVar.GetLocaleNumberFormat(aTot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

  Endif
  Return $BillingReport.NewHTMLPath()

End

Public Function SummaryGroupOPIPAccCrossTab(conn As Connection, dt1 As Date, dt2 As Date, sRow As String, sGroup As String, sVariable As String, sInvoiced As Boolean, sLocaType As String, sLocation As String) As String

  Dim $BillingReport As CReportHTML
  Dim sql1 As String
  Dim asx As New String[0]
  Dim res1 As Result
  Dim xval As String
  Dim yval As String
  Dim xcol As String[] = ["OPD", "IPD"]
  Dim xdept As String
  Dim valtotal As Float
  Dim coltot As Float
  Dim categList As String[]
  Dim xcateg As String

  Dim res2 As Result
  Dim dtlst As Date[]
  Dim dt As Date

  Dim xtot As Float
  Dim aTot As Integer
  Dim xstr As String

  Dim chapdate As String
  Dim xfirdate As Date
  Dim xlasdate As Date
  Dim xdateform As String

  xstr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  Select sRow
    Case "Gender", "Surname", "District", "Municipality", "Service Rank", "Service Unit", "Service Category", "Last Status", "Visit Type", "Visit Mode"
      xval = modMedReports.GetColumnEncounter(sRow)
    Case Else
      xval = modRHTMLSummary.GetFieldServiceSummary(sRow)
  End Select

  $BillingReport = New CReportHTML(["Variable", "OPD", "IPD", "TOTAL"], "", "")
  $BillingReport.UserData.Add("Group: " & sGroup & "  Value: " & sVariable, "PARAM1")
  $BillingReport.UserData.Add("Date: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")

  If sRow = "Year" Or If sRow = "Month" Or If sRow = "Date" Then
    xdateform = modSettings.ShowSettingFromFIle("HealthReport/RowDateFormat")

    If sRow = "Year" Then
      If modBasic.$DateFormat = "BS Date" Then
        dtlst = modDate.GetSelectDateBSArrayBetween(gb.Year, dt1, dt2)
      Else
        dtlst = modDate.GetSelectDateArrayBetween(gb.Year, dt1, dt2)
      Endif
    Else If sRow = "Month" Then
      If modBasic.$DateFormat = "BS Date" Then
        dtlst = modDate.GetSelectDateBSArrayBetween(gb.Month, dt1, dt2)
      Else
        dtlst = modDate.GetSelectDateArrayBetween(gb.Month, dt1, dt2)
      Endif
    Else
      dtlst = modDate.GetDateArrayBetween(dt1, dt2)
    Endif
    coltot = 0
    For Each dt In dtlst
      If sRow = "Year" Then
        If modBasic.$DateFormat = "BS Date" Then
          chapdate = modDate.DateFormatViewBS(dt, "YearOnly")
          xfirdate = modDate.StartSqlYearBS(dt)
          xlasdate = modDate.EndSqlYearBS(dt)
        Else
          chapdate = Format(dt, "yyyy")
          xfirdate = modDate.StartSqlYear(dt)
          xlasdate = modDate.EndSqlYear(dt)
        Endif
      Else If sRow = "Month" Then
        If modBasic.$DateFormat = "BS Date" Then
          chapdate = modDate.DateFormatViewBS(dt, "YearMonth")
          xfirdate = modDate.StartSqlMonthBS(dt)
          xlasdate = modDate.EndSqlMonthBS(dt)
        Else
          chapdate = Format(dt, "mmm yyyy")
          xfirdate = modDate.StartSqlMonth(dt)
          xlasdate = modDate.EndSqlMonth(dt)
        Endif
      Else
        If xdateform = "Disable" Then
          chapdate = modReportVar.GetDateTimeReport(dt, gb.MediumDate)
        Else
          chapdate = modReportVar.GetDateTimeReport(dt, gb.MediumDate) & " [" & modDate.GetWeekDay(dt) & "]"
        Endif
        xfirdate = modDate.StartSqlDate(dt)
        xlasdate = modDate.EndSqlDate(dt)
      Endif

      With asx
        .Add(chapdate)
        xtot = 0
        For Each xdept In xcol
          valtotal = 0
          yval = GetDepartQuery(xdept)
          If sInvoiced = True Then
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & yval & xstr, True, xfirdate, xlasdate, sGroup)
          Else
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & yval & xstr, True, xfirdate, xlasdate, sGroup)
          Endif
          If sVariable = "GrossTotal" Then
            If res2["duemt"] Then
              valtotal = res2["duemt"]
            Endif
          Else If sVariable = "Discount" Then
            If res2["disctot"] Then
              valtotal = res2["disctot"]
            Endif
          Else If sVariable = "TotalTax" Then
            If res2["taxtot"] Then
              valtotal = res2["taxtot"]
            Endif
          Else If sVariable = "CashTotal" Then
            If res2["xcash"] Then
              valtotal = res2["xcash"]
            Endif
          Else If sVariable = "CreditTotal" Then
            If res2["xcredit"] Then
              valtotal = res2["xcredit"]
            Endif
          Else
            If res2["netamt"] Then
              valtotal = res2["netamt"]
            Endif
          Endif
          If valtotal Then
            xtot = xtot + valtotal
            .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
          Else
            .Add(modReportVar.GetLocaleNumberFormat(0, 0))
          Endif
        Next
        coltot = coltot + xtot
        .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next

    With asx
      .Add("GRAND TOTAL")
      For Each xdept In xcol
        .Add("")
      Next
      .Add(modReportVar.GetLocaleNumberFormat(coltot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

    With asx
      .Add("TOTAL(Actual)")
      aTot = 0
      For Each xdept In xcol
        valtotal = 0
        yval = GetDepartQuery(xdept)
        If sInvoiced = True Then
          res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
        Else
          res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
        Endif
        If sVariable = "GrossTotal" Then
          If res2["duemt"] Then
            valtotal = res2["duemt"]
          Endif
        Else If sVariable = "Discount" Then
          If res2["disctot"] Then
            valtotal = res2["disctot"]
          Endif
        Else If sVariable = "TotalTax" Then
          If res2["taxtot"] Then
            valtotal = res2["taxtot"]
          Endif
        Else If sVariable = "CashTotal" Then
          If res2["xcash"] Then
            valtotal = res2["xcash"]
          Endif
        Else If sVariable = "CreditTotal" Then
          If res2["xcredit"] Then
            valtotal = res2["xcredit"]
          Endif
        Else
          If res2["netamt"] Then
            valtotal = res2["netamt"]
          Endif
        Endif
        If valtotal Then
          aTot = aTot + valtotal
          .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
        Else
          .Add(modReportVar.GetLocaleNumberFormat(0, 0))
        Endif
      Next
      .Add(modReportVar.GetLocaleNumberFormat(aTot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Else
    If sRow = "Last Status" Or If sRow = "Visit Type" Or If sRow = "Visit Mode" Then
      sql1 = Subst("select distinct(&1) as col from tblencounter", xval)
      If sInvoiced = True Then
        res1 = conn.Exec(sql1 & " where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
      Else
        res1 = conn.Exec(sql1 & " where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
      Endif
    Else If sRow = "Gender" Or If sRow = "Surname" Or If sRow = "District" Or If sRow = "Municipality" Or If sRow = "Service Rank" Or If sRow = "Service Unit" Or If sRow = "Service Category" Then
      sql1 = Subst("select distinct(&1) as col from tblpatientinfo", xval)
      If sInvoiced = True Then
        res1 = conn.Exec(sql1 & " where fldpatientval in(select fldpatientval from tblencounter where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4)))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
      Else
        res1 = conn.Exec(sql1 & " where fldpatientval in(select fldpatientval from tblencounter where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4)))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
      Endif
    Else
      sql1 = Subst("select distinct(&1) as col from tblpatbilling", xval)
      If sInvoiced = True Then
        res1 = conn.Exec(sql1 & " where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4)" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
      Else
        res1 = conn.Exec(sql1 & " where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4)" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
      Endif
    Endif
    If res1.Available Then
      categList = modControlSub.GetDirectFillresultNoNull(res1)
      coltot = 0
      For Each xcateg In categList
        With asx
          .Add(xcateg)
          xtot = 0
          For Each xdept In xcol
            valtotal = 0
            yval = GetDepartQuery(xdept)
            Print yval
            If sRow = "Last Status" Or If sRow = "Visit Type" Or If sRow = "Visit Mode" Then
              If sInvoiced = True Then
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and fldencounterval in(select fldencounterval from tblencounter where " & xval & " like &5) and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcateg)
              Else
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and fldencounterval in(select fldencounterval from tblencounter where " & xval & " like &5) and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcateg)
              Endif
            Else If sRow = "Gender" Or If sRow = "Surname" Or If sRow = "District" Or If sRow = "Municipality" Or If sRow = "Service Rank" Or If sRow = "Service Unit" Or If sRow = "Service Category" Then
              If sInvoiced = True Then
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where " & xval & " like &5)) and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcateg)
              Else
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where " & xval & " like &5)) and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcateg)
              Endif
            Else
              If sInvoiced = True Then
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & xval & " like &5 and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcateg)
              Else
                res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & xval & " like &5 and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcateg)
              Endif
            Endif
            If sVariable = "GrossTotal" Then
              If res2["duemt"] Then
                valtotal = res2["duemt"]
              Endif
            Else If sVariable = "Discount" Then
              If res2["disctot"] Then
                valtotal = res2["disctot"]
              Endif
            Else If sVariable = "TotalTax" Then
              If res2["taxtot"] Then
                valtotal = res2["taxtot"]
              Endif
            Else If sVariable = "CashTotal" Then
              If res2["xcash"] Then
                valtotal = res2["xcash"]
              Endif
            Else If sVariable = "CreditTotal" Then
              If res2["xcredit"] Then
                valtotal = res2["xcredit"]
              Endif
            Else
              If res2["netamt"] Then
                valtotal = res2["netamt"]
              Endif
            Endif
            If valtotal Then
              xtot = xtot + valtotal
              .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
            Else
              .Add(modReportVar.GetLocaleNumberFormat(0, 0))
            Endif
          Next
          coltot = coltot + xtot
          .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Next

      With asx
        .Add("GRAND TOTAL")
        For Each xdept In xcol
          .Add("")
        Next
        .Add(modReportVar.GetLocaleNumberFormat(coltot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()

      With asx
        .Add("TOTAL(Actual)")
        aTot = 0
        For Each xdept In xcol
          valtotal = 0
          yval = GetDepartQuery(xdept)
          If sInvoiced = True Then
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
          Else
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & yval & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup)
          Endif
          If sVariable = "GrossTotal" Then
            If res2["duemt"] Then
              valtotal = res2["duemt"]
            Endif
          Else If sVariable = "Discount" Then
            If res2["disctot"] Then
              valtotal = res2["disctot"]
            Endif
          Else If sVariable = "TotalTax" Then
            If res2["taxtot"] Then
              valtotal = res2["taxtot"]
            Endif
          Else If sVariable = "CashTotal" Then
            If res2["xcash"] Then
              valtotal = res2["xcash"]
            Endif
          Else If sVariable = "CreditTotal" Then
            If res2["xcredit"] Then
              valtotal = res2["xcredit"]
            Endif
          Else
            If res2["netamt"] Then
              valtotal = res2["netamt"]
            Endif
          Endif
          If valtotal Then
            aTot = aTot + valtotal
            .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
          Else
            .Add(modReportVar.GetLocaleNumberFormat(0, 0))
          Endif
        Next
        .Add(modReportVar.GetLocaleNumberFormat(aTot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

  Endif
  Return $BillingReport.NewHTMLPath()

End

''====================================== Group =======================
Public Function SummaryGroupAccTabular(conn As Connection, dt1 As Date, dt2 As Date, sColumn As String, sVariable As String, sInvoiced As Boolean, sLocaType As String, sLocation As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim grpList As String[]
  Dim sGroup As String

  Dim xval As String
  Dim xcol As String[]
  Dim valtotal As Float

  Dim i As Integer
  Dim res2 As Result
  Dim aTot As Float
  Dim xgrtot As Float
  Dim res As Result
  Dim xstr As String

  xstr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  Select sColumn
    Case "Gender", "Surname", "District", "Municipality", "Service Rank", "Service Unit", "Service Category"
      xval = modMedReports.GetColumnEncounter(sColumn)
      If sInvoiced = True Then
        res = conn.Exec(Subst("select distinct(&1) as fld from tblpatientinfo", xval) & " where fldpatientval in(select fldpatientval from tblencounter where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3)))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2))
      Else
        res = conn.Exec(Subst("select distinct(&1) as fld from tblpatientinfo", xval) & " where fldpatientval in(select fldpatientval from tblencounter where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2))
      Endif

    Case "Last Status", "Visit Type", "Visit Mode"
      xval = modMedReports.GetColumnEncounter(sColumn)
      If sInvoiced = True Then
        res = conn.Exec(Subst("select distinct(&1) as fld from tblencounter", xval) & " where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2))
      Else
        res = conn.Exec(Subst("select distinct(&1) as fld from tblencounter", xval) & " where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3)" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2))
      Endif

    Case Else
      xval = modRHTMLSummary.GetFieldServiceSummary(sColumn)
      If sInvoiced = True Then
        res = conn.Exec(Subst("select distinct(&1) as fld from tblpatbilling", xval) & " where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3)" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2))
      Else
        res = conn.Exec(Subst("select distinct(&1) as fld from tblpatbilling", xval) & " where fldsave=&1 and fldtime>=&2 and fldtime<=&3" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2))
      Endif

  End Select

  xcol = New String[]
  If res.Available Then
    xcol.Add(UCase(sColumn))
    For Each res
      If res["fld"] Then
        xcol.Add(res["fld"])
      Endif
    Next
    xcol.Add("TOTAL")
  Endif

  $BillingReport = New CReportHTML(xcol, "", "")
  $BillingReport.UserData.Add("Value: " & sVariable, "PARAM1")
  $BillingReport.UserData.Add("Date: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")
  grpList = modNonMedical.GetGroupNameAccount()

  xgrtot = 0
  For Each sGroup In grpList

    With asx
      .Add(sGroup)
      aTot = 0
      For i = 1 To xcol.Count - 2
        valtotal = 0
        If sColumn = "Last Status" Or If sColumn = "Visit Type" Or If sColumn = "Visit Mode" Then
          If sInvoiced = True Then
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and fldencounterval in(select fldencounterval from tblencounter where " & xval & " like &5)" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcol[i])
          Else
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and fldencounterval in(select fldencounterval from tblencounter where " & xval & " like &5)" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcol[i])
          Endif
        Else If sColumn = "Gender" Or If sColumn = "Surname" Or If sColumn = "District" Or If sColumn = "Municipality" Or If sColumn = "Service Rank" Or If sColumn = "Service Unit" Or If sColumn = "Service Category" Then
          If sInvoiced = True Then
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where " & xval & " like &5))" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcol[i])
          Else
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where " & xval & " like &5))" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcol[i])
          Endif
        Else
          If sInvoiced = True Then
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3) and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & xval & " like &5" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcol[i])
          Else
            res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup like &4) and " & xval & " like &5" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, xcol[i])
          Endif
        Endif
        If sVariable = "GrossTotal" Then
          If res2["duemt"] Then
            valtotal = res2["duemt"]
          Endif
        Else If sVariable = "Discount" Then
          If res2["disctot"] Then
            valtotal = res2["disctot"]
          Endif
        Else If sVariable = "TotalTax" Then
          If res2["taxtot"] Then
            valtotal = res2["taxtot"]
          Endif
        Else If sVariable = "CashTotal" Then
          If res2["xcash"] Then
            valtotal = res2["xcash"]
          Endif
        Else If sVariable = "CreditTotal" Then
          If res2["xcredit"] Then
            valtotal = res2["xcredit"]
          Endif
        Else
          If res2["netamt"] Then
            valtotal = res2["netamt"]
          Endif
        Endif
        If valtotal Then
          aTot = aTot + valtotal
          .Add(modReportVar.GetLocaleNumberFormat(valtotal, gb.Currency))
        Else
          .Add(modReportVar.GetLocaleNumberFormat(0, 0))
        Endif
      Next
      xgrtot = xgrtot + aTot
      .Add(modReportVar.GetLocaleNumberFormat(aTot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Next

  With asx
    .Add("<b>GRAND TOTAL</b>")
    For i = 1 To xcol.Count - 2
      .Add("")
    Next
    .Add(modReportVar.GetLocaleNumberFormat(xgrtot, gb.Currency))
  End With

  Return $BillingReport.NewHTMLPath()

End

Public Function SummaryServiceAccTabular(conn As Connection, dt1 As Date, dt2 As Date, sColumn As String, sVariable As String, sInvoiced As Boolean, sLocaType As String, sLocation As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim compLst As String[]
  Dim xcomp As String
  Dim xval As String
  Dim xstr As String

  Dim res2 As Result
  Dim res As Result
  Dim xitem As String
  Dim xList As String[]

  Dim aitm As Float
  Dim adsc As Float
  Dim atax As Float
  Dim anet As Float
  Dim acash As Float
  Dim acrdt As Float

  Dim xitm As Float
  Dim xtax As Float
  Dim xdsc As Float
  Dim xnet As Float
  Dim xcash As Float
  Dim xcrdt As Float

  xstr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  Select sColumn
    Case "Gender", "Surname", "District", "Municipality", "Service Rank", "Service Unit", "Service Category"
      xval = modMedReports.GetColumnEncounter(sColumn)
      If sInvoiced = True Then
        res = conn.Exec(Subst("select distinct(&1) as col from tblpatientinfo", xval) & " where fldpatientval in(select fldpatientval from tblencounter where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3)))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2))
      Else
        res = conn.Exec(Subst("select distinct(&1) as col from tblpatientinfo", xval) & " where fldpatientval in(select fldpatientval from tblencounter where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2))
      Endif

    Case "Last Status", "Visit Type", "Visit Mode"
      xval = modMedReports.GetColumnEncounter(sColumn)
      If sInvoiced = True Then
        res = conn.Exec(Subst("select distinct(&1) as col from tblencounter", xval) & " where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3))" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2))
      Else
        res = conn.Exec(Subst("select distinct(&1) as col from tblencounter", xval) & " where fldencounterval in(select fldencounterval from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3)" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2))
      Endif

    Case Else
      xval = modRHTMLSummary.GetFieldServiceSummary(sColumn)
      If sInvoiced = True Then
        res = conn.Exec(Subst("select distinct(&1) as col from tblpatbilling", xval) & " where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3)" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2))
      Else
        res = conn.Exec(Subst("select distinct(&1) as col from tblpatbilling", xval) & " where fldsave=&1 and fldtime>=&2 and fldtime<=&3" & xstr & " ORDER BY " & xval & " ASC", True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2))
      Endif
  End Select
  xList = modControlSub.GetDirectFillresultNoNull(res)

  $BillingReport = New CReportHTML([("CATEGORY"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("NET"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("Value: " & sVariable, "PARAM1")
  $BillingReport.UserData.Add("Date: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")

  If xList And If xList.Count Then
    compLst = modBasic.$AllCompList
    For Each xcomp In compLst
      $BillingReport.AddChapter(xcomp)
      aitm = 0
      adsc = 0
      atax = 0
      anet = 0
      acash = 0
      acrdt = 0

      For Each xitem In xList
        Select sColumn
          Case "Last Status", "Visit Type", "Visit Mode"
            If sInvoiced = True Then
              res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3 and fldcomp like &4) and flditemtype like &5 and fldencounterval in(select fldencounterval from tblencounter where " & xval & " like &6)" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), xcomp, sVariable, xitem)
            Else
              res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and fldcomp like &4 and flditemtype like &5 and fldencounterval in(select fldencounterval from tblencounter where " & xval & " like &6)" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), xcomp, sVariable, xitem)
            Endif
          Case "Gender", "Surname", "District", "Municipality", "Service Rank", "Service Unit", "Service Category"
            If sInvoiced = True Then
              res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3 and fldcomp like &4) and flditemtype like &5 and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where " & xval & " like &6))" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), xcomp, sVariable, xitem)
            Else
              res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and fldcomp like &4 and flditemtype like &5 and fldencounterval in(select fldencounterval from tblencounter where fldpatientval in(select fldpatientval from tblpatientinfo where " & xval & " like &6))" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), xcomp, sVariable, xitem)
            Endif
          Case Else
            If sInvoiced = True Then
              res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldbillno in(select fldbillno from tblpatbilldetail where fldtime>=&2 and fldtime<=&3 and fldcomp like &4) and flditemtype like &5 and " & xval & " like &6" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), xcomp, sVariable, xitem)
            Else
              res2 = conn.Exec("select " & modNonMedical.CashCreditBillSQL() & " from tblpatbilling where fldsave=&1 and fldtime>=&2 and fldtime<=&3 and fldcomp like &4 and flditemtype like &5 and " & xval & " like &6" & xstr, True, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), xcomp, sVariable, xitem)
            Endif
        End Select

        xitm = 0
        xtax = 0
        xdsc = 0
        xnet = 0
        xcash = 0
        xcrdt = 0
        If res2.Available Then
          If res2["duemt"] Then
            xitm = res2["duemt"]
          Endif
          If res2["disctot"] Then
            xdsc = res2["disctot"]
          Endif
          If res2["taxtot"] Then
            xtax = res2["taxtot"]
          Endif
          If res2["netamt"] Then
            xnet = res2["netamt"]
          Endif
          If res2["xcredit"] Then
            xcrdt = res2["xcredit"]
          Endif
          If res2["xcash"] Then
            xcash = res2["xcash"]
          Endif

          If xitm Then
            aitm = aitm + xitm
            adsc = adsc + xdsc
            atax = atax + xtax
            anet = anet + xnet
            acash = acash + xcash
            acrdt = acrdt + xcrdt
            With asx
              .Add(xitem)
              .Add(modReportVar.GetLocaleNumberFormat(xitm, gb.Currency))
              .Add(modReportVar.GetLocaleNumberFormat(xdsc, gb.Currency))
              .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
              .Add(modReportVar.GetLocaleNumberFormat(xnet, gb.Currency))
              .Add(modReportVar.GetLocaleNumberFormat(xcrdt, gb.Currency))
              .Add(modReportVar.GetLocaleNumberFormat(xcash, gb.Currency))
            End With
            $BillingReport.Add(asx)
            asx.Clear()
          Endif
        Endif
      Next

      With asx
        .Add(modString.HTMLBlankSpace(5) & "TOTAL")
        .Add(modReportVar.GetLocaleNumberFormat(aitm, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(adsc, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(atax, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(anet, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(acrdt, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(acash, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()

      With asx
        .Add("")
        .Add("")
        .Add("")
        .Add("")
        .Add("")
        .Add("")
        .Add("")
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
  Endif

  Return $BillingReport.NewHTMLPath()

End
