' Gambas module file

''=================== FACULTY SUMMARY =======================
Public Function GetFacultySUmmaryReportFormat($con As Connection, dt1 As Date, dt2 As Date, sBillMode As String, sDisc As String, sComp As String, sInvoiced As Boolean, sBillType As String, sOption As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim xfield As String
  Dim grpList As String[]
  Dim grpName As String
  Dim xList As String[]
  Dim xType As String
  Dim res As Result
  Dim res2 As Result

  Dim xsubt As Float
  Dim xdisc As Float
  Dim xtax As Float
  Dim xtot As Float

  Dim asubt As Float
  Dim adisc As Float
  Dim atax As Float
  Dim atot As Float

  Dim psubt As Float
  Dim pdisc As Float
  Dim ptax As Float
  Dim ptot As Float
  Dim RepoStr As String

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  $BillingReport = New CReportHTML([("Particulars"), ("SubTotal"), ("Disc"), ("Tax"), ("Total")], "", "")
  $BillingReport.UserData.Add("FACULTY REPORT BY " & sOption, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate) & " COMP: " & sComp & " Plan: " & sBillMode & " Disc: " & sDisc, "PARAM2")
  grpList = modNonMedical.GetMasterDepartAccount()

  xfield = modRHTMLSummary.GetFieldServiceSummary(sOption)
  If sInvoiced = True Then
    res = $con.Exec(Subst("select distinct(&1) as col from " & $tblpatbilling, xfield) & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &4) and fldsave=&3 and fldbillingmode like &5 and flddisctype like &6 and fldbilltype like &7" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sBillMode, sDisc, sBillType)
  Else
    res = $con.Exec(Subst("select distinct(&1) as col from " & $tblpatbilling, xfield) & " where fldtime>=&1 and fldtime<=&2 and fldsave=&3 and fldcomp like &4 and fldbillingmode like &5 and flddisctype like &6 and fldbilltype like &7" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sBillMode, sDisc, sBillType)
  Endif
  xList = modControlSub.GetDirectFillresultNoNull(res)
  xList.Add("Null")

  psubt = 0
  pdisc = 0
  ptax = 0
  ptot = 0
  For Each xType In xList
    $BillingReport.AddChapter(xType)

    asubt = 0
    adisc = 0
    atax = 0
    atot = 0
    For Each grpName In grpList

      If xType = "Null" Then
        If sInvoiced = True Then
          res2 = $con.Exec("select SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&2 and fldtime<=&3 and fldcomp like &5) and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & " and " & xfield & " IS NULL" & RepoStr, grpName, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sBillMode, sDisc, sBillType)
        Else
          res2 = $con.Exec("select SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldtime>=&2 and fldtime<=&3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & " and " & xfield & " IS NULL" & RepoStr, grpName, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sBillMode, sDisc, sBillType)
        Endif
      Else
        If sInvoiced = True Then
          res2 = $con.Exec("select SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&2 and fldtime<=&3 and fldcomp like &5) and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & " and " & xfield & "=&9" & RepoStr, grpName, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sBillMode, sDisc, sBillType, xType)
        Else
          res2 = $con.Exec("select SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldtime>=&2 and fldtime<=&3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & " and " & xfield & "=&9" & RepoStr, grpName, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sBillMode, sDisc, sBillType, xType)
        Endif
      Endif
      If res2.Available Then
        xsubt = 0
        xdisc = 0
        xtax = 0
        xtot = 0
        If res2["itemtot"] Then
          xsubt = res2["itemtot"]
        Endif
        If res2["flddiscamt"] Then
          xdisc = res2["flddiscamt"]
        Endif
        If res2["fldtaxamt"] Then
          xtax = res2["fldtaxamt"]
        Endif
        If res2["fldditemamt"] Then
          xtot = res2["fldditemamt"]
        Endif

        asubt = asubt + xsubt
        adisc = adisc + xdisc
        atax = atax + xtax
        atot = atot + xtot
        If xsubt Then
          With asx
            .Add(grpName)
            .Add(modReportVar.GetLocaleNumberFormat(xsubt, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(xdisc, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
          End With
          $BillingReport.Add(asx)
          asx.Clear()
        Endif
      Endif
    Next

    psubt = psubt + asubt
    pdisc = pdisc + adisc
    ptax = ptax + atax
    ptot = ptot + atot
    With asx
      .Add("TOTAL: " & xType)
      .Add(modReportVar.GetLocaleNumberFormat(asubt, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(adisc, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(atax, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(atot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
    With asx
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  With asx
    .Add("GRAND TOTAL")
    .Add(modReportVar.GetLocaleNumberFormat(psubt, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(pdisc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(ptax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(ptot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  Return $BillingReport.NewHTMLPath()

End

Public Function GetFacultySUmmaryEntryFormat($con As Connection, dt1 As Date, dt2 As Date, sBillMode As String, sDisc As String, sComp As String, sInvoiced As Boolean, sBillType As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim xfield As String
  Dim grpList As String[]
  Dim grpName As String
  Dim xList As String[]
  Dim xType As String
  Dim res As Result
  Dim res2 As Result

  Dim xsubt As Float
  Dim xdisc As Float
  Dim xtax As Float
  Dim xtot As Float

  Dim asubt As Float
  Dim adisc As Float
  Dim atax As Float
  Dim atot As Float

  Dim psubt As Float
  Dim pdisc As Float
  Dim ptax As Float
  Dim ptot As Float
  Dim RepoStr As String

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  $BillingReport = New CReportHTML([("Particulars"), ("SubTotal"), ("Disc"), ("Tax"), ("Total")], "", "")
  $BillingReport.UserData.Add("FACULTY REPORT BY Entry", "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate) & " COMP: " & sComp & " Plan: " & sBillMode & " Disc: " & sDisc, "PARAM2")
  grpList = modNonMedical.GetMasterDepartAccount()

  If sInvoiced = True Then
    res = $con.Exec("select distinct(fldadmitlocat) as col from tblencounter where fldencounterval in(select fldencounterval from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &4) and fldsave=&3 and fldbillingmode like &5 and flddisctype like &6 and fldbilltype like &7)" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sBillMode, sDisc, sBillType)
  Else
    res = $con.Exec("select distinct(fldadmitlocat) as col from tblencounter where fldencounterval in(select fldencounterval from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and fldsave=&3 and fldcomp like &4 and fldbillingmode like &5 and flddisctype like &6 and fldbilltype like &7)" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sBillMode, sDisc, sBillType)
  Endif
  xList = modControlSub.GetDirectFillresultNoNull(res)
  xList.Add("Null")

  psubt = 0
  pdisc = 0
  ptax = 0
  ptot = 0
  For Each xType In xList
    $BillingReport.AddChapter(xType)

    asubt = 0
    adisc = 0
    atax = 0
    atot = 0
    For Each grpName In grpList

      If xType = "Null" Then
        xfield = " and fldencounterval in(select fldencounterval from tblencounter where fldadmitlocat IS NULL)"
        If sInvoiced = True Then
          res2 = $con.Exec("select SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&2 and fldtime<=&3 and fldcomp like &5) and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & xfield & RepoStr, grpName, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sBillMode, sDisc, sBillType)
        Else
          res2 = $con.Exec("select SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldtime>=&2 and fldtime<=&3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & xfield & RepoStr, grpName, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sBillMode, sDisc, sBillType)
        Endif
      Else
        xfield = " and fldencounterval in(select fldencounterval from tblencounter where fldadmitlocat=&9)"
        If sInvoiced = True Then
          res2 = $con.Exec("select SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&2 and fldtime<=&3 and fldcomp like &5) and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & xfield & RepoStr, grpName, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sBillMode, sDisc, sBillType, xType)
        Else
          res2 = $con.Exec("select SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldtime>=&2 and fldtime<=&3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & xfield & RepoStr, grpName, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sBillMode, sDisc, sBillType, xType)
        Endif
      Endif
      If res2.Available Then
        xsubt = 0
        xdisc = 0
        xtax = 0
        xtot = 0
        If res2["itemtot"] Then
          xsubt = res2["itemtot"]
        Endif
        If res2["flddiscamt"] Then
          xdisc = res2["flddiscamt"]
        Endif
        If res2["fldtaxamt"] Then
          xtax = res2["fldtaxamt"]
        Endif
        If res2["fldditemamt"] Then
          xtot = res2["fldditemamt"]
        Endif

        asubt = asubt + xsubt
        adisc = adisc + xdisc
        atax = atax + xtax
        atot = atot + xtot
        If xsubt Then
          With asx
            .Add(grpName)
            .Add(modReportVar.GetLocaleNumberFormat(xsubt, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(xdisc, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
          End With
          $BillingReport.Add(asx)
          asx.Clear()
        Endif
      Endif
    Next

    psubt = psubt + asubt
    pdisc = pdisc + adisc
    ptax = ptax + atax
    ptot = ptot + atot
    With asx
      .Add("TOTAL: " & xType)
      .Add(modReportVar.GetLocaleNumberFormat(asubt, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(adisc, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(atax, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(atot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
    With asx
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  With asx
    .Add("GRAND TOTAL")
    .Add(modReportVar.GetLocaleNumberFormat(psubt, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(pdisc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(ptax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(ptot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  Return $BillingReport.NewHTMLPath()

End

''===================== Faculty Report ==========================
Public Function ServiceFacultySummaryReport($con As Connection, dt1 As Date, dt2 As Date, sInvoiced As Boolean, sComp As String, sDept As String, sDisc As String, sBillType As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim lst As String[]

  Dim aitm As Float
  Dim adsc As Float
  Dim atax As Float
  Dim acash As Float
  Dim acrdt As Float
  Dim xx As String
  Dim res4 As Result

  Dim xcnt As Float
  Dim xitm As Float
  Dim xtax As Float
  Dim xdsc As Float
  Dim xcash As Float
  Dim xcrdt As Float
  Dim RepoStr As String

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  $BillingReport = New CReportHTML([("PARTICULARS"), ("COUNT"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("FACULTY SUMMARY REPORT", "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate) & " COMP: " & sComp & " Plan: " & sDept & " Disc: " & sDisc, "PARAM2")

  aitm = 0
  adsc = 0
  atax = 0
  acash = 0
  acrdt = 0

  ''faulties
  lst = modNonMedical.GetMasterDepartAccount()
  For Each xx In lst
    If sInvoiced = True Then
      res4 = $con.Exec("select SUM(flditemqty) as itemcnt," & modNonMedical.CashCreditBillSQL() & " from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&2 and fldtime<=&3 and fldcomp like &5) and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr, xx, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sDept, sDisc, sBillType)
    Else
      res4 = $con.Exec("select SUM(flditemqty) as itemcnt," & modNonMedical.CashCreditBillSQL() & " from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldtime>=&2 and fldtime<=&3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr, xx, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sDept, sDisc, sBillType)
    Endif
    xcnt = 0
    xitm = 0
    xtax = 0
    xdsc = 0
    xcash = 0
    xcrdt = 0
    If res4.Available = True Then
      If res4["itemcnt"] Then
        xcnt = res4["itemcnt"]
      Endif
      If res4["duemt"] Then
        xitm = res4["duemt"]
      Endif
      If res4["disctot"] Then
        xdsc = res4["disctot"]
      Endif
      If res4["taxtot"] Then
        xtax = res4["taxtot"]
      Endif
      If res4["xcredit"] Then
        xcrdt = res4["xcredit"]
      Endif
      If res4["xcash"] Then
        xcash = res4["xcash"]
      Endif
    Endif

    If Not xitm Then
    Else
      aitm = aitm + xitm
      adsc = adsc + xdsc
      atax = atax + xtax
      acash = acash + xcash
      acrdt = acrdt + xcrdt
      With asx
        .Add(xx)
        .Add(modReportVar.GetLocaleNumberFormat(xcnt, -2))
        .Add(modReportVar.GetLocaleNumberFormat(xitm, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xdsc, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xcrdt, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xcash, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif
  Next

  With asx
    .Add(modString.HTMLBlankSpace(5) & "TOTAL")
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(aitm, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(adsc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(atax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(acrdt, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(acash, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  Return $BillingReport.NewHTMLPath()

End

Public Function ServiceFacultySingleReport($con As Connection, dt1 As Date, dt2 As Date, sInvoiced As Boolean, sDept As String, sComp As String, sDisc As String, sBillType As String, sGroup As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim gitm As Float
  Dim gdsc As Float
  Dim gtax As Float
  Dim xtot As Float

  Dim xx As String
  Dim res1 As Result

  Dim rte As Float
  Dim qty As Float
  Dim xitm As Float
  Dim subt As Float
  Dim xtax As Float
  Dim xdsc As Float
  Dim RepoStr As String

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  $BillingReport = New CReportHTML([("Particulars"), ("Rate"), ("QTY"), ("SubTotal"), ("Disc"), ("Tax"), ("Total")], "", "")
  $BillingReport.UserData.Add("FACULTY SUMMARY REPORT : " & sGroup, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate) & " COMP: " & sComp & " Plan: " & sDept & " Disc: " & sDisc, "PARAM2")

  gitm = 0
  gdsc = 0
  gtax = 0
  xtot = 0
  If sInvoiced = True Then
    res1 = $con.Exec("select flditemname,avg(flditemrate) as rate,SUM(flditemqty) as qnty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as dsc,SUM(fldtaxamt) as tax,SUM(fldditemamt) as tot from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &6) and flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&3)) and fldsave=&4 and fldbillingmode like &5 and flddisctype like &7 and fldbilltype like &8" & RepoStr & " GROUP BY flditemname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, True, sDept, sComp, sDisc, sBillType)             ''
  Else
    res1 = $con.Exec("select flditemname,avg(flditemrate) as rate,SUM(flditemqty) as qnty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as dsc,SUM(fldtaxamt) as tax,SUM(fldditemamt) as tot from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&3)) and fldsave=&4 and fldbillingmode like &5 and fldcomp like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr & " GROUP BY flditemname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sGroup, True, sDept, sComp, sDisc, sBillType)
  Endif

  If res1.Available = True Then
    For Each res1
      rte = 0
      qty = 0
      xitm = 0
      xtax = 0
      xdsc = 0
      subt = 0
      If res1["rate"] Then
        rte = res1["rate"]
      Endif
      If res1["qnty"] Then
        qty = res1["qnty"]
      Endif
      If res1["itemtot"] Then
        xitm = res1["itemtot"]
      Endif
      If res1["dsc"] Then
        xdsc = res1["dsc"]
      Endif
      If res1["tax"] Then
        xtax = res1["tax"]
      Endif
      If res1["tot"] Then
        subt = res1["tot"]
      Endif

      If Not qty And If Not xitm Then
      Else
        gitm = gitm + xitm
        gdsc = gdsc + xdsc
        gtax = gtax + xtax
        xtot = xtot + subt
        With asx
          .Add(res1["flditemname"])
          .Add(modReportVar.GetLocaleNumberFormat(rte, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(qty, -2))
          .Add(modReportVar.GetLocaleNumberFormat(xitm, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xdsc, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(subt, gb.Currency))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Endif
    Next
  Endif

  With asx
    .Add(xx)
    .Add("...")
    .Add("...")
    .Add(modReportVar.GetLocaleNumberFormat(gitm, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(gdsc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(gtax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  Return $BillingReport.NewHTMLPath()

End

Public Function ServiceFacultyDateReportSingle($con As Connection, dt1 As Date, dt2 As Date, sInvoiced As Boolean, sDept As String, sComp As String, sDisc As String, sItem As String, sBillType As String, sDtType As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim gitm As Float
  Dim gdsc As Float
  Dim gtax As Float
  Dim xtot As Float

  Dim res As Result
  Dim res1 As Result

  Dim rte As Float
  Dim qty As Float
  Dim xitm As Float
  Dim subt As Float
  Dim xtax As Float
  Dim xdsc As Float

  Dim dt As Date
  Dim dtlst As Date[]

  Dim aitm As Float
  Dim adsc As Float
  Dim atax As Float
  Dim atot As Float

  Dim xfirdate As Date
  Dim xlasdate As Date
  Dim chapdate As String
  Dim RepoStr As String

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  $BillingReport = New CReportHTML([("Particulars"), ("Rate"), ("QTY"), ("SubTotal"), ("Disc"), ("Tax"), ("Total")], "", "")
  $BillingReport.UserData.Add("FACULTY ITEM REPORT: " & sItem, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate) & " COMP: " & sComp & " Plan: " & sDept & " Disc: " & sDisc, "PARAM2")

  If sDtType = "Year" Then
    If modBasic.$DateFormat = "BS Date" Then
      dtlst = modDate.GetSelectDateBSArrayBetween(gb.Year, dt1, dt2)
    Else
      dtlst = modDate.GetSelectDateArrayBetween(gb.Year, dt1, dt2)
    Endif
  Else If sDtType = "Month" Then
    If modBasic.$DateFormat = "BS Date" Then
      dtlst = modDate.GetSelectDateBSArrayBetween(gb.Month, dt1, dt2)
    Else
      dtlst = modDate.GetSelectDateArrayBetween(gb.Month, dt1, dt2)
    Endif
  Else
    dtlst = modDate.GetSelectDateArrayBetween(gb.Day, dt1, dt2)
  Endif

  aitm = 0
  adsc = 0
  atax = 0
  atot = 0
  For Each dt In dtlst
    If sDtType = "Year" Then
      If modBasic.$DateFormat = "BS Date" Then
        chapdate = modDate.DateFormatViewBS(dt, "YearOnly")
        xfirdate = modDate.StartSqlYearBS(dt)
        xlasdate = modDate.EndSqlYearBS(dt)
      Else
        chapdate = Format(dt, "yyyy")
        xfirdate = modDate.StartSqlYear(dt)
        xlasdate = modDate.EndSqlYear(dt)
      Endif
    Else If sDtType = "Month" Then
      If modBasic.$DateFormat = "BS Date" Then
        chapdate = modDate.DateFormatViewBS(dt, "YearMonth")
        xfirdate = modDate.StartSqlMonthBS(dt)
        xlasdate = modDate.EndSqlMonthBS(dt)
      Else
        chapdate = Format(dt, "mmm yyyy")
        xfirdate = modDate.StartSqlMonth(dt)
        xlasdate = modDate.EndSqlMonth(dt)
      Endif
    Else
      chapdate = modReportVar.GetDateTimeReport(dt, gb.MediumDate)
      xfirdate = modDate.StartSqlDate(dt)
      xlasdate = modDate.EndSqlDate(dt)
    Endif
    xfirdate = modDate.StartSqlDate(Max(dt1, xfirdate))
    xlasdate = modDate.EndSqlDate(Min(dt2, xlasdate))
    $BillingReport.AddSection(modString.HTMLBlankSpace(3) & chapdate, True)

    If sInvoiced = True Then
      res = $con.Exec("select distinct(flditemname) from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1) and flditemname in(select flditemname from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&2 and fldtime<=&3 and fldcomp like &6) and fldsave=&4 and fldbillingmode like &5 and flddisctype like &7)" & RepoStr & " ORDER BY flditemname ASC", sItem, xfirdate, xlasdate, True, sDept, sComp, sDisc)
    Else
      res = $con.Exec("select distinct(flditemname) from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1) and flditemname in(select flditemname from " & $tblpatbilling & " where fldtime>=&2 and fldtime<=&3 and fldsave=&4 and fldbillingmode like &5 and fldcomp like &6 and flddisctype like &7)" & RepoStr & " ORDER BY flditemname ASC", sItem, xfirdate, xlasdate, True, sDept, sComp, sDisc)
    Endif

    gitm = 0
    gdsc = 0
    gtax = 0
    xtot = 0
    If res.Available Then
      For Each res

        If sInvoiced = True Then
          res1 = $con.Exec("select avg(flditemrate) as rate,SUM(flditemqty) as qnty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as dsc,SUM(fldtaxamt) as tax,SUM(fldditemamt) as tot from " & $tblpatbilling & " where flditemname=&1 and fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&2 and fldtime<=&3 and fldcomp like &7) and flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&4)) and fldsave=&5 and fldbillingmode like &6 and fldencounterval in(select fldencounterval from tblencounter where flddisctype like &8)" & RepoStr, res["flditemname"], xfirdate, xlasdate, sItem, True, sDept, sComp, sDisc)
        Else
          res1 = $con.Exec("select avg(flditemrate) as rate,SUM(flditemqty) as qnty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as dsc,SUM(fldtaxamt) as tax,SUM(fldditemamt) as tot from " & $tblpatbilling & " where flditemname=&1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&4)) and fldsave=&5 and fldbillingmode like &6 and fldcomp like &7 and fldencounterval in(select fldencounterval from tblencounter where flddisctype like &8)" & RepoStr, res["flditemname"], xfirdate, xlasdate, sItem, True, sDept, sComp, sDisc)
        Endif
        rte = 0
        qty = 0
        xitm = 0
        xtax = 0
        xdsc = 0
        subt = 0
        If res1.Available = True Then
          If res1["rate"] Then
            rte = res1["rate"]
          Endif
          If res1["qnty"] Then
            qty = res1["qnty"]
          Endif
          If res1["itemtot"] Then
            xitm = res1["itemtot"]
          Endif
          If res1["dsc"] Then
            xdsc = res1["dsc"]
          Endif
          If res1["tax"] Then
            xtax = res1["tax"]
          Endif
          If res1["tot"] Then
            subt = res1["tot"]
          Endif
        Endif

        If Not qty And If Not xitm Then
        Else
          gitm = gitm + xitm
          gdsc = gdsc + xdsc
          gtax = gtax + xtax
          xtot = xtot + subt
          With asx
            .Add(modString.HTMLBlankSpace(5) & res["flditemname"])
            .Add(modReportVar.GetLocaleNumberFormat(rte, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(qty, -2))
            .Add(modReportVar.GetLocaleNumberFormat(xitm, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(xdsc, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(subt, gb.Currency))
          End With
          $BillingReport.Add(asx)
          asx.Clear()
        Endif

      Next  'item
    Endif

    aitm = aitm + gitm
    adsc = adsc + gdsc
    atax = atax + gtax
    atot = atot + xtot
    'date total
    With asx
      .Add(modString.HTMLBlankSpace(3) & chapdate)
      .Add("...")
      .Add("...")
      .Add(modReportVar.GetLocaleNumberFormat(gitm, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(gdsc, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(gtax, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next ''date

  With asx
    .Add(sItem)
    .Add("...")
    .Add("...")
    .Add(modReportVar.GetLocaleNumberFormat(aitm, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(adsc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(atax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(atot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  Return $BillingReport.NewHTMLPath()

End

Public Function ServiceFacultyDateReport($con As Connection, dt1 As Date, dt2 As Date, sInvoiced As Boolean, sComp As String, sDept As String, sDisc As String, sBillType As String, sDtType As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim lst As String[]
  Dim gitm As Float
  Dim gdsc As Float
  Dim gtax As Float
  Dim xtot As Float

  Dim itm As Float
  Dim dsc As Float
  Dim tax As Float
  Dim tot As Float
  Dim xx As String
  Dim res1 As Result

  Dim qty As Float
  Dim dt As Date
  Dim dtlst As Date[]

  Dim aitm As Float
  Dim adsc As Float
  Dim atax As Float
  Dim atot As Float

  Dim xfirdate As Date
  Dim xlasdate As Date
  Dim chapdate As String
  Dim RepoStr As String

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  $BillingReport = New CReportHTML([("Particulars"), ("QTY"), ("SubTotal"), ("Disc"), ("Tax"), ("Total")], "", "")
  $BillingReport.UserData.Add("SERVICE SUMMARY REPORT", "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate) & " COMP: " & sComp & " MODE: " & sDept & " Disc: " & sDisc, "PARAM2")

  If sDtType = "Year" Then
    If modBasic.$DateFormat = "BS Date" Then
      dtlst = modDate.GetSelectDateBSArrayBetween(gb.Year, dt1, dt2)
    Else
      dtlst = modDate.GetSelectDateArrayBetween(gb.Year, dt1, dt2)
    Endif
  Else If sDtType = "Month" Then
    If modBasic.$DateFormat = "BS Date" Then
      dtlst = modDate.GetSelectDateBSArrayBetween(gb.Month, dt1, dt2)
    Else
      dtlst = modDate.GetSelectDateArrayBetween(gb.Month, dt1, dt2)
    Endif
  Else
    dtlst = modDate.GetSelectDateArrayBetween(gb.Day, dt1, dt2)
  Endif
  itm = 0
  dsc = 0
  tax = 0
  tot = 0
  lst = modNonMedical.GetMasterDepartAccount()
  For Each xx In lst
    $BillingReport.AddSection(xx, True)

    aitm = 0
    adsc = 0
    atax = 0
    atot = 0
    For Each dt In dtlst
      If sDtType = "Year" Then
        If modBasic.$DateFormat = "BS Date" Then
          chapdate = modDate.DateFormatViewBS(dt, "YearOnly")
          xfirdate = modDate.StartSqlYearBS(dt)
          xlasdate = modDate.EndSqlYearBS(dt)
        Else
          chapdate = Format(dt, "yyyy")
          xfirdate = modDate.StartSqlYear(dt)
          xlasdate = modDate.EndSqlYear(dt)
        Endif
      Else If sDtType = "Month" Then
        If modBasic.$DateFormat = "BS Date" Then
          chapdate = modDate.DateFormatViewBS(dt, "YearMonth")
          xfirdate = modDate.StartSqlMonthBS(dt)
          xlasdate = modDate.EndSqlMonthBS(dt)
        Else
          chapdate = Format(dt, "mmm yyyy")
          xfirdate = modDate.StartSqlMonth(dt)
          xlasdate = modDate.EndSqlMonth(dt)
        Endif
      Else
        chapdate = modReportVar.GetDateTimeReport(dt, gb.MediumDate)
        xfirdate = modDate.StartSqlDate(dt)
        xlasdate = modDate.EndSqlDate(dt)
      Endif
      xfirdate = modDate.StartSqlDate(Max(dt1, xfirdate))
      xlasdate = modDate.EndSqlDate(Min(dt2, xlasdate))

      If sInvoiced = True Then
        res1 = $con.Exec("select SUM(flditemqty) as qnty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as dsc,SUM(fldtaxamt) as tax,SUM(fldditemamt) as tot from " & $tblpatbilling & " where flditemname like &1 and fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&2 and fldtime<=&3 and fldcomp like &6) and flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&4)) and fldsave=&5 and fldbillingmode like &7 and flddisctype like &8 and fldbilltype like &9" & RepoStr, "%", xfirdate, xlasdate, xx, True, sComp, sDept, sDisc, sBillType)
      Else
        res1 = $con.Exec("select SUM(flditemqty) as qnty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as dsc,SUM(fldtaxamt) as tax,SUM(fldditemamt) as tot from " & $tblpatbilling & " where flditemname like &1 and fldtime>=&2 and fldtime<=&3 and flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&4)) and fldsave=&5 and fldcomp like &6 and fldbillingmode like &7 and flddisctype like &8 and fldbilltype like &9" & RepoStr, "%", xfirdate, xlasdate, xx, True, sComp, sDept, sDisc, sBillType)
      Endif
      qty = 0
      gitm = 0
      gdsc = 0
      gtax = 0
      xtot = 0
      If res1.Available Then
        If res1["qnty"] Then
          qty = res1["qnty"]
        Endif
        If res1["itemtot"] Then
          gitm = res1["itemtot"]
        Endif
        If res1["dsc"] Then
          gdsc = res1["dsc"]
        Endif
        If res1["tax"] Then
          gtax = res1["tax"]
        Endif
        If res1["tot"] Then
          xtot = res1["tot"]
        Endif
        If Not qty And If Not gitm Then
        Else
          aitm = aitm + gitm
          adsc = adsc + gdsc
          atax = atax + gtax
          atot = atot + xtot
          With asx
            .Add(modString.HTMLBlankSpace(5) & chapdate)
            .Add(modReportVar.GetLocaleNumberFormat(qty, -2))
            .Add(modReportVar.GetLocaleNumberFormat(gitm, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(gdsc, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(gtax, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
          End With
          $BillingReport.Add(asx)
          asx.Clear()
        Endif
      Endif
    Next ''date

    itm = itm + aitm
    dsc = dsc + adsc
    tax = tax + atax
    tot = tot + atot
    'category total
    With asx
      .Add(xx)
      .Add("...")
      .Add(modReportVar.GetLocaleNumberFormat(aitm, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(adsc, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(atax, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(atot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next ''category

  'grand total
  With asx
    .Add("TOTAL")
    .Add("***")
    .Add(modReportVar.GetLocaleNumberFormat(itm, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(dsc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(tax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(tot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()
  With asx
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  Return $BillingReport.NewHTMLPath()

End

Public Function ServiceFacultySummaryCashCredit($con As Connection, dt1 As Date, dt2 As Date, sInvoiced As Boolean, sComp As String, sDept As String, sDisc As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim lst As String[]
  Dim crdt As Float
  Dim cash As Float
  Dim dsc As Float
  Dim tax As Float
  Dim tot As Float
  Dim xx As String
  Dim res2 As Result
  Dim res3 As Result
  Dim res4 As Result

  Dim xcrdt As Float
  Dim xcash As Float
  Dim subt As Float
  Dim xtax As Float
  Dim xdsc As Float
  Dim RepoStr As String

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  $BillingReport = New CReportHTML([("Particulars"), ("Credit"), ("Cash"), ("Disc"), ("Tax"), ("Total")], "", "")
  $BillingReport.UserData.Add("FACULTY SUMMARY REPORT", "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate) & " COMP: " & sComp & " Plan: " & sDept & " Disc: " & sDisc, "PARAM2")

  crdt = 0
  cash = 0
  dsc = 0
  tax = 0
  tot = 0
  lst = modNonMedical.GetMasterDepartAccount()
  For Each xx In lst
    If sInvoiced = True Then
      res2 = $con.Exec("select SUM(flditemrate*flditemqty) as itemtot from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&2 and fldtime<=&3 and fldcomp like &5) and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype=&8" & RepoStr, xx, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sDept, sDisc, "Credit")
    Else
      res2 = $con.Exec("select SUM(flditemrate*flditemqty) as itemtot from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldtime>=&2 and fldtime<=&3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype=&8" & RepoStr, xx, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sDept, sDisc, "Credit")
    Endif
    If sInvoiced = True Then
      res3 = $con.Exec("select SUM(flditemrate*flditemqty) as itemtot from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&2 and fldtime<=&3 and fldcomp like &5) and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype=&8" & RepoStr, xx, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sDept, sDisc, "Cash")
    Else
      res3 = $con.Exec("select SUM(flditemrate*flditemqty) as itemtot from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldtime>=&2 and fldtime<=&3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype=&8" & RepoStr, xx, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sDept, sDisc, "Cash")
    Endif
    If sInvoiced = True Then
      res4 = $con.Exec("select SUM(flddiscamt) as dsc,SUM(fldtaxamt) as tax,SUM(fldditemamt) as tot from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&2 and fldtime<=&3 and fldcomp like &5) and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7" & RepoStr, xx, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sDept, sDisc)
    Else
      res4 = $con.Exec("select SUM(flddiscamt) as dsc,SUM(fldtaxamt) as tax,SUM(fldditemamt) as tot from " & $tblpatbilling & " where flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&1)) and fldtime>=&2 and fldtime<=&3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7" & RepoStr, xx, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sDept, sDisc)
    Endif
    xcrdt = 0
    xcash = 0
    xtax = 0
    xdsc = 0
    subt = 0
    If res2.Available Then
      If res2["itemtot"] Then
        xcrdt = res2["itemtot"]
      Endif
    Endif
    If res3.Available Then
      If res3["itemtot"] Then
        xcash = res3["itemtot"]
      Endif
    Endif
    If res4.Available = True Then
      If res4["dsc"] Then
        xdsc = res4["dsc"]
      Endif
      If res4["tax"] Then
        xtax = res4["tax"]
      Endif
      If res4["tot"] Then
        subt = res4["tot"]
      Endif
    Endif

    If Not xcrdt And If Not xcash Then
    Else
      crdt = crdt + xcrdt
      cash = cash + xcash
      dsc = dsc + xdsc
      tax = tax + xtax
      tot = tot + subt
      With asx
        .Add(xx)
        .Add(modReportVar.GetLocaleNumberFormat(xcrdt, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xcash, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xdsc, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(subt, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif
  Next

  With asx
    .Add(modString.HTMLBlankSpace(5) & "TOTAL")
    .Add(modReportVar.GetLocaleNumberFormat(crdt, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(cash, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(dsc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(tax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(tot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  Return $BillingReport.NewHTMLPath()

End

''-------------------------
Public Function ServiceFacultyDetailReport($con As Connection, dt1 As Date, dt2 As Date, sInvoiced As Boolean, sComp As String, sDept As String, sDisc As String, sBillType As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim lst As String[]
  Dim gitm As Float
  Dim gdsc As Float
  Dim gtax As Float
  Dim xtot As Float

  Dim itm As Float
  Dim dsc As Float
  Dim tax As Float
  Dim tot As Float
  Dim xx As String
  Dim res1 As Result

  Dim rte As Float
  Dim qty As Float
  Dim xitm As Float
  Dim subt As Float
  Dim xtax As Float
  Dim xdsc As Float
  Dim RepoStr As String

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  $BillingReport = New CReportHTML([("Particulars"), ("Rate"), ("QTY"), ("SubTotal"), ("Disc"), ("Tax"), ("Total")], "", "")
  $BillingReport.UserData.Add("FACULTY SUMMARY REPORT", "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate) & " COMP: " & sComp & " Plan: " & sDept & " Disc: " & sDisc, "PARAM2")

  itm = 0
  dsc = 0
  tax = 0
  tot = 0
  lst = modNonMedical.GetMasterDepartAccount()
  For Each xx In lst
    $BillingReport.AddSection(xx, True)

    gitm = 0
    gdsc = 0
    gtax = 0
    xtot = 0
    If sInvoiced = True Then
      res1 = $con.Exec("select flditemname,avg(flditemrate) as rate,SUM(flditemqty) as qnty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as dsc,SUM(fldtaxamt) as tax,SUM(fldditemamt) as tot from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&3)) and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr & " GROUP BY flditemname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), xx, True, sComp, sDept, sDisc, sBillType)
    Else
      res1 = $con.Exec("select flditemname,avg(flditemrate) as rate,SUM(flditemqty) as qnty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as dsc,SUM(fldtaxamt) as tax,SUM(fldditemamt) as tot from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and flditemname in(select flditemname from tblreportgroup where fldgroup in(select fldgroup from tblmasterdept where fldmaster=&3)) and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr & " GROUP BY flditemname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), xx, True, sComp, sDept, sDisc, sBillType)
    Endif
    If res1.Available = True Then
      For Each res1
        rte = 0
        qty = 0
        xitm = 0
        xtax = 0
        xdsc = 0
        subt = 0
        If res1["rate"] Then
          rte = res1["rate"]
        Endif
        If res1["qnty"] Then
          qty = res1["qnty"]
        Endif
        If res1["itemtot"] Then
          xitm = res1["itemtot"]
        Endif
        If res1["dsc"] Then
          xdsc = res1["dsc"]
        Endif
        If res1["tax"] Then
          xtax = res1["tax"]
        Endif
        If res1["tot"] Then
          subt = res1["tot"]
        Endif

        If Not qty And If Not xitm Then
        Else
          gitm = gitm + xitm
          gdsc = gdsc + xdsc
          gtax = gtax + xtax
          xtot = xtot + subt
          With asx
            .Add(modString.HTMLBlankSpace(3) & res1["flditemname"])
            .Add(modReportVar.GetLocaleNumberFormat(rte, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(qty, -2))
            .Add(modReportVar.GetLocaleNumberFormat(xitm, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(xdsc, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(subt, gb.Currency))
          End With
          $BillingReport.Add(asx)
          asx.Clear()
        Endif
      Next
    Endif

    itm = itm + gitm
    dsc = dsc + gdsc
    tax = tax + gtax
    tot = tot + xtot
    With asx
      .Add("TOTAL: " & xx)
      .Add("")
      .Add("")
      .Add(modReportVar.GetLocaleNumberFormat(gitm, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(gdsc, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(gtax, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
    With asx
      .Add("...")
      .Add("...")
      .Add("...")
      .Add("...")
      .Add("...")
      .Add("...")
      .Add("...")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  With asx
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
  End With
  $BillingReport.Add(asx)
  asx.Clear()
  With asx
    .Add("GRAND TOTAL")
    .Add("")
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(itm, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(dsc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(tax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(tot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  Return $BillingReport.NewHTMLPath()

End
