' Gambas module file

''--------------------------------------------- GENERAL --------------------------------------------------------------------
Public Function RegistAutoBillingPackList() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  $BillingReport = New CReportHTML([("Department"), ("Rate"), ("Visit"), ("Particulars"), ("Type"), ("Rate"), ("QTY"), ("Timing"), ("CutOff"), ("Payble")], "", "")
  $BillingReport.UserData.Add("REGISTRATION AUTOBILLING", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(flddisctype) as flddisctype from tblautogroup")
  For Each res
    $BillingReport.AddSection(res["flddisctype"], True)
    res1 = modDatabase.$syConn.Exec("select fldid,fldgroup,fldbillingmode,fldfollow,flditemtype,flditemname,flditemqty,fldexitemtype,fldcutoff,fldpayable from tblautogroup where flddisctype=&1", res["flddisctype"])
    For Each res1
      With asx
        .Add(res1["fldgroup"])
        .Add(res1["fldbillingmode"])
        .Add(res1["fldfollow"])
        .Add(res1["flditemname"])
        .Add(res1["flditemtype"])
        .Add(modReportVar.GetLocaleNumberFormat(modNonMedical.GetCashBillItemCost(res1["flditemname"], "%"), gb.Currency))
        .Add(res1["flditemqty"])
        .Add(res1["fldexitemtype"])
        If res1["fldcutoff"] Then
          .Add(Format(res1["fldcutoff"], gb.ShortTime))
        Else
          .Add("")
        Endif
        .Add(res1["fldpayable"])
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
  Next

  Return $BillingReport.NewHTMLPath()

End

Public Function RegistAutoBillingList() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  $BillingReport = New CReportHTML([("Package"), ("Rate"), ("Visit"), ("Particulars"), ("Type"), ("Rate"), ("QTY"), ("Timing"), ("CutOff"), ("Payble")], "", "")
  $BillingReport.UserData.Add("REGISTRATION AUTOBILLING", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(fldgroup) from tblautogroup")
  For Each res
    $BillingReport.AddSection(res["fldgroup"], True)
    res1 = modDatabase.$syConn.Exec("select fldid,flddisctype,fldbillingmode,fldfollow,flditemtype,flditemname,flditemqty,fldexitemtype,fldcutoff,fldpayable from tblautogroup where fldgroup=&1", res["fldgroup"])
    For Each res1
      With asx
        .Add(res1["flddisctype"])
        .Add(res1["fldbillingmode"])
        .Add(res1["fldfollow"])
        .Add(res1["flditemname"])
        .Add(res1["flditemtype"])
        .Add(modReportVar.GetLocaleNumberFormat(modNonMedical.GetCashBillItemCost(res1["flditemname"], "%"), gb.Currency))
        .Add(res1["flditemqty"])
        .Add(res1["fldexitemtype"])
        If res1["fldcutoff"] Then
          .Add(Format(res1["fldcutoff"], gb.ShortTime))
        Else
          .Add("")
        Endif
        .Add(res1["fldpayable"])
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
  Next

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowBillingListReport(smode As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  $BillingReport = New CReportHTML([("Particulars"), ("Charge"), ("Target/Rate"), ("Status")], "", "")
  $BillingReport.UserData.Add("MEDICAL CHARGES : " & smode, "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(flditemtype) from tblservicecost where fldgroup=&1 or fldgroup like &2", "%", smode)
  For Each res
    $BillingReport.AddSection(res["flditemtype"], True)
    res1 = modDatabase.$syConn.Exec("select flditemname,flditemcost,flditemunit,fldstatus,fldtarget from tblservicecost where flditemtype=&1 and (fldgroup=&2 or fldgroup like &3) ORDER BY flditemname ASC", res["flditemtype"], "%", smode)
    For Each res1
      With asx
        .Add(res1["flditemname"])
        If res1["flditemunit"] Then
          .Add(res1["flditemunit"] & Space(1) & modReportVar.GetLocaleNumberFormat(res1["flditemcost"], gb.Fixed))
        Else
          .Add(modReportVar.GetLocaleNumberFormat(res1["flditemcost"], gb.Currency))
        Endif
        .Add(res1["fldtarget"])
        .Add(res1["fldstatus"])
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
  Next

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowLabGroupingListReport() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  $BillingReport = New CReportHTML([("Particulars"), ("Type"), ("Method")], "", "")
  $BillingReport.UserData.Add("LABORATORY TEST GROUPING", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(fldgroupname) from tblgrouptest ORDER BY fldgroupname ASC")
  For Each res
    $BillingReport.AddChapter(res["fldgroupname"])
    res1 = modDatabase.$syConn.Exec("select fldtestid,fldtesttype,fldactive from tblgrouptest where fldgroupname=&1 ORDER BY fldtestid ASC", res["fldgroupname"])
    For Each res1
      With asx
        .Add(modString.HTMLBlankSpace(3) & res1["fldtestid"])
        .Add(res1["fldtesttype"])
        .Add(res1["fldactive"])
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowRadioGroupingListReport() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  $BillingReport = New CReportHTML([("Particulars"), ("Type"), ("Option"), ("Method")], "", "")
  $BillingReport.UserData.Add("RADIOLOGY TEST GROUPING", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(fldgroupname) from tblgroupradio ORDER BY fldgroupname ASC")
  For Each res
    $BillingReport.AddChapter(res["fldgroupname"])
    res1 = modDatabase.$syConn.Exec("select fldtestid,fldtesttype,fldptsex,fldactive from tblgroupradio where fldgroupname=&1 ORDER BY fldtestid ASC", res["fldgroupname"])
    For Each res1
      With asx
        .Add(modString.HTMLBlankSpace(3) & res1["fldtestid"])
        .Add(res1["fldtesttype"])
        .Add(res1["fldptsex"])
        .Add(res1["fldactive"])
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowComBillingListReport() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  $BillingReport = New CReportHTML([("Particulars"), ("Disc%"), ("PatType")], " ", "")
  $BillingReport.UserData.Add("TAX AND DISCOUNT SETTINGS", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(fldcomp) from tblextrasetting")
  For Each res
    $BillingReport.AddSection(res["fldcomp"], True)
    res1 = modDatabase.$syConn.Exec("select fldid,fldcateg,flddiscpercent,fldcashmode from tblextrasetting where fldcomp=&1", res["fldcomp"])
    For Each res1
      With asx
        .Add(res1["fldcateg"])
        .Add(modReportVar.GetLocaleNumberFormat(res1["flddiscpercent"], -2))
        .Add(res1["fldcashmode"])
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
  Next

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowServiceGroupListHTML() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  $BillingReport = New CReportHTML([("Category"), ("Particulars"), ("QTY")], "", "")
  $BillingReport.UserData.Add("SERVICE GROUPS", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(fldgroup) from tblservicegroup ORDER BY fldgroup ASC")                                                                                        ''
  For Each res
    $BillingReport.AddSection(res["fldgroup"], True)

    res1 = modDatabase.$syConn.Exec("select fldid,flditemtype,flditemname,flditemqty from tblservicegroup where fldgroup=&1 ORDER BY flditemname ASC", res["fldgroup"])
    For Each res1
      With asx
        .Add(res1["flditemtype"])
        .Add(res1["flditemname"])
        .Add(modReportVar.GetLocaleNumberFormat(res1["flditemqty"], -2))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowPharmacyGroupListHTML() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  $BillingReport = New CReportHTML([("Category"), ("Particulars"), ("Dose"), ("Freq"), ("Day"), ("QTY"), ("StartHour")], "", "")
  $BillingReport.UserData.Add("PHARMACY GROUPS", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(fldmedgroup) from tblproductgroup ORDER BY fldmedgroup ASC")                                                                                        ''
  For Each res
    $BillingReport.AddSection(res["fldmedgroup"], True)

    res1 = modDatabase.$syConn.Exec("select fldid,fldroute,flditem,flddose,flddoseunit,fldfreq,fldday,fldqty,fldstart from tblproductgroup where fldmedgroup=&1 ORDER BY flditem ASC", res["fldmedgroup"])
    For Each res1
      With asx
        .Add(res1["fldroute"])
        .Add(res1["flditem"])
        .Add(modReportVar.GetLocaleNumberFormat(res1["flddose"], -2) & Space(1) & res1["flddoseunit"])
        .Add(res1["fldfreq"])
        .Add(modReportVar.GetLocaleNumberFormat(res1["fldday"], -2))
        .Add(modReportVar.GetLocaleNumberFormat(res1["fldqty"], -2))
        .Add(modReportVar.GetLocaleNumberFormat(res1["fldstart"], 0))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowReportGroupListHTML() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  $BillingReport = New CReportHTML([("Category"), ("Particulars"), ("Rate")], "", "")
  $BillingReport.UserData.Add("REPORT GROUPS", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(fldgroup) from tblreportgroup ORDER BY fldgroup ASC")                                                                                        ''
  For Each res
    $BillingReport.AddSection(res["fldgroup"], True)

    res1 = modDatabase.$syConn.Exec("select flditemtype,flditemname from tblreportgroup where fldgroup=&1 ORDER BY flditemname ASC", res["fldgroup"])
    For Each res1
      With asx
        .Add(res1["flditemtype"])
        .Add(res1["flditemname"])
        .Add(modNonMedical.GetCashBillItemCost(res1["flditemname"], res1["flditemtype"]))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowReportStockInsuranceHTML() As String

  Dim $BillingReport As CReportHTML

  Dim res1 As Result
  Dim res2 As Result
  Dim res3 As Result

  Dim res1x As Result
  Dim res2x As Result
  Dim res3x As Result
  Dim asx As New String[0]

  $BillingReport = New CReportHTML([("Category"), ("Particulars"), ("Drug"), ("Medicines"), ("Pack"), ("Rate")], "", "")
  $BillingReport.UserData.Add("PRODUCT MISMATCH", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  $BillingReport.AddSection("Medicines NOT CODED", True)
  res1 = modDatabase.$syConn.Exec("select fldid,flditemname,fldbillingmode,flddrug,fldstockid,fldrate,fldpackvol from tblstockrate where fldcategory=&1 and flddrug not in(select flddrug from tblmedbrand)", "Medicines")
  If res1.Available Then
    For Each res1
      With asx
        .Add(res1["fldbillingmode"])
        .Add(res1["flditemname"])
        .Add(res1["flddrug"])
        .Add(res1["fldstockid"])
        .Add(res1["fldpackvol"])
        .Add(res1["fldrate"])
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Endif

  $BillingReport.AddSection("Medicines OUT OF STOCK", True)
  res1x = modDatabase.$syConn.Exec("select fldid,flditemname,fldbillingmode,flddrug,fldstockid,fldrate,fldpackvol from tblstockrate where fldcategory=&1", "Medicines")    '
  If res1x.Available Then
    For Each res1x
      If modStock.TotalQTYbyDrug(res1x["flddrug"], "Medicines", "%") = 0 Then
        With asx
          .Add(res1x["fldbillingmode"])
          .Add(res1x["flditemname"])
          .Add(res1x["flddrug"])
          .Add(res1x["fldstockid"])
          .Add(res1x["fldpackvol"])
          .Add(res1x["fldrate"])
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Endif
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Endif

  $BillingReport.AddSection("Surgicals NOT CODED", True)
  res2 = modDatabase.$syConn.Exec("select fldid,flditemname,fldbillingmode,flddrug,fldstockid,fldrate,fldpackvol from tblstockrate where fldcategory=&1 and flddrug not in(select fldsurgid from tblsurgbrand)", "Surgicals")
  If res2.Available Then
    For Each res2
      With asx
        .Add(res2["fldbillingmode"])
        .Add(res2["flditemname"])
        .Add(res2["flddrug"])
        .Add(res2["fldstockid"])
        .Add(res2["fldpackvol"])
        .Add(res2["fldrate"])
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Endif

  $BillingReport.AddSection("Surgicals OUT OF STOCK", True)
  res2x = modDatabase.$syConn.Exec("select fldid,flditemname,fldbillingmode,flddrug,fldstockid,fldrate,fldpackvol from tblstockrate where fldcategory=&1 and flddrug in(select fldsurgid from tblsurgbrand where fldbrandid not in(select fldstockid from tblentry where fldcategory=&1))", "Surgicals")
  If res2x.Available Then
    For Each res2x
      If modStock.TotalQTYbyDrug(res2x["flddrug"], "Surgicals", "%") = 0 Then
        With asx
          .Add(res2x["fldbillingmode"])
          .Add(res2x["flditemname"])
          .Add(res2x["flddrug"])
          .Add(res2x["fldstockid"])
          .Add(res2x["fldpackvol"])
          .Add(res2x["fldrate"])
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Endif
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Endif

  $BillingReport.AddSection("Extra Items NOT CODED", True)
  res3 = modDatabase.$syConn.Exec("select fldid,flditemname,fldbillingmode,flddrug,fldstockid,fldrate,fldpackvol from tblstockrate where fldcategory=&1 and flddrug not in(select fldextraid from tblextrabrand)", "Extra Items")
  If res3.Available Then
    For Each res3
      With asx
        .Add(res3["fldbillingmode"])
        .Add(res3["flditemname"])
        .Add(res3["flddrug"])
        .Add(res3["fldstockid"])
        .Add(res3["fldpackvol"])
        .Add(res3["fldrate"])
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Endif

  $BillingReport.AddSection("Extra Items OUT OF STOCK", True)
  res3x = modDatabase.$syConn.Exec("select fldid,flditemname,fldbillingmode,flddrug,fldstockid,fldrate,fldpackvol from tblstockrate where fldcategory=&1 and flddrug in(select fldextraid from tblextrabrand where fldbrandid not in(select fldstockid from tblentry where fldcategory=&1))", "Extra Items")
  If res3x.Available Then
    For Each res3x
      If modStock.TotalQTYbyDrug(res3x["flddrug"], "Extra Items", "%") = 0 Then
        With asx
          .Add(res3x["fldbillingmode"])
          .Add(res3x["flditemname"])
          .Add(res3x["flddrug"])
          .Add(res3x["fldstockid"])
          .Add(res3x["fldpackvol"])
          .Add(res3x["fldrate"])
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Endif
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Endif

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowReportStockCodeInsuranceHTML(sBillMode As String, sComp As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim xList As String[] = ["Medicines", "Surgicals", "Extra Items"]
  Dim xcateg As String

  Dim xstr As String
  Dim res As Result

  $BillingReport = New CReportHTML([("Particulars"), ("Rate"), ("QTY")], "", "")
  $BillingReport.UserData.Add("CURRENT MAPPED STOCK", "PARAM1")
  $BillingReport.UserData.Add(sBillMode, "PARAM2")

  For Each xcateg In xList
    $BillingReport.AddChapter(xcateg)

    If xcateg = "Surgicals" Then
      If modBasic.$BillFixedRateSale = "Brand" Then
        xstr = "select fldstockid,AVG(fldsellpr) as xsell,SUM(fldqty) as qty from tblentry where fldcategory=&1 and fldcomp like &2 and fldstockid in (select fldstockid from tblstockrate where fldbillingmode like &3) GROUP BY fldstockid ORDER BY fldstockid"
      Else If modBasic.$BillFixedRateSale = "Generic" Then
        xstr = "select fldstockid,AVG(fldsellpr) as xsell,SUM(fldqty) as qty from tblentry where fldcategory=&1 and fldcomp like &2 and fldstockid in(select fldbrandid from tblsurgbrand where fldsurgid in (select flddrug from tblstockrate where fldbillingmode like &3)) GROUP BY fldstockid ORDER BY fldstockid"
      Else
        xstr = ""
      Endif

    Else If xcateg = "Extra Items" Then
      If modBasic.$BillFixedRateSale = "Brand" Then
        xstr = "select fldstockid,AVG(fldsellpr) as xsell,SUM(fldqty) as qty from tblentry where fldcategory=&1 and fldcomp like &2 and fldstockid in (select fldstockid from tblstockrate where fldbillingmode like &3) GROUP BY fldstockid ORDER BY fldstockid"
      Else If modBasic.$BillFixedRateSale = "Generic" Then
        xstr = "select fldstockid,AVG(fldsellpr) as xsell,SUM(fldqty) as qty from tblentry where fldcategory=&1 and fldcomp like &2 and fldstockid in(select fldbrandid from tblextrabrand where fldextraid in (select flddrug from tblstockrate where fldbillingmode like &3)) GROUP BY fldstockid ORDER BY fldstockid"
      Else
        xstr = ""
      Endif

    Else
      If modBasic.$BillFixedRateSale = "Brand" Then
        xstr = "select fldstockid,AVG(fldsellpr) as xsell,SUM(fldqty) as qty from tblentry where fldcategory=&1 and fldcomp like &2 and fldstockid in (select fldstockid from tblstockrate where fldbillingmode like &3) GROUP BY fldstockid ORDER BY fldstockid"
      Else If modBasic.$BillFixedRateSale = "Generic" Then
        xstr = "select fldstockid,AVG(fldsellpr) as xsell,SUM(fldqty) as qty from tblentry where fldcategory=&1 and fldcomp like &2 and fldstockid in(select fldbrandid from tblmedbrand where flddrug in (select flddrug from tblstockrate where fldbillingmode like &3)) GROUP BY fldstockid ORDER BY fldstockid"
      Else
        xstr = ""
      Endif
    Endif

    If xstr Then
      res = modDatabase.$syConn.Exec(xstr, xcateg, sComp, sBillMode)
      If res.Available Then
        For Each res
          If res["qty"] > 0 Then
            With asx
              .Add(res["fldstockid"])
              .Add(modReportVar.GetLocaleNumberFormat(res["xsell"], gb.Currency))
              .Add(modReportVar.GetLocaleNumberFormat(res["qty"], -2))
            End With
            $BillingReport.Add(asx)
            asx.Clear()
          Endif
        Next
      Endif
    Endif

    With asx
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Next

  Return $BillingReport.NewHTMLPath()

End
