' Gambas module file

Public Function ServiceSummaryReport($con As Connection, dt1 As Date, dt2 As Date, lst As String[], sInvoiced As Boolean, sComp As String, sBillMode As String, sDisc As String, sBillType As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim aitm As Float
  Dim adsc As Float
  Dim atax As Float
  Dim acash As Float
  Dim acredt As Float
  Dim xx As String
  Dim res2 As Result

  Dim xitot As Float
  Dim xtax As Float
  Dim xdsc As Float
  Dim xcash As Float
  Dim xcrdt As Float
  Dim RepoStr As String

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  $BillingReport = New CReportHTML([("CATEGORY"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("COMP: " & sComp & " RATE: " & sBillMode & " SCHEME: " & sDisc, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")

  aitm = 0
  adsc = 0
  atax = 0
  acash = 0
  acredt = 0
  For Each xx In lst
    If sInvoiced = True Then
      res2 = $con.Exec("select " & modNonMedical.CashCreditBillSQL() & " from " & $tblpatbilling & " where flditemtype=&1 and fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&2 and fldtime<=&3 and fldcomp like &5) and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr, xx, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sBillMode, sDisc, sBillType)
    Else
      res2 = $con.Exec("select " & modNonMedical.CashCreditBillSQL() & " from " & $tblpatbilling & " where flditemtype=&1 and fldtime>=&2 and fldtime<=&3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr, xx, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True, sComp, sBillMode, sDisc, sBillType)
    Endif
    xitot = 0
    xdsc = 0
    xtax = 0
    xcash = 0
    xcrdt = 0
    If res2.Available = True Then
      If res2["duemt"] Then
        xitot = res2["duemt"]
      Endif
      If res2["disctot"] Then
        xdsc = res2["disctot"]
      Endif
      If res2["taxtot"] Then
        xtax = res2["taxtot"]
      Endif
      If res2["xcash"] Then
        xcash = res2["xcash"]
      Endif
      If res2["xcredit"] Then
        xcrdt = res2["xcredit"]
      Endif
    Endif

    aitm = aitm + xitot
    adsc = adsc + xdsc
    atax = atax + xtax
    acash = acash + xcash
    acredt = acredt + xcrdt
    With asx
      .Add(xx)
      .Add(modReportVar.GetLocaleNumberFormat(xitot, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(xdsc, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(xcrdt, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(xcash, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Next

  With asx
    .Add("<b>GRAND TOTAL</b>")
    .Add(modReportVar.GetLocaleNumberFormat(aitm, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(adsc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(atax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(acredt, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(acash, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  Return $BillingReport.NewHTMLPath()

End

Public Function ServiceDetailSumReport($con As Connection, dt1 As Date, dt2 As Date, lst As String[], sInvoiced As Boolean, sComp As String, sBillMode As String, sDisc As String, sBillType As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]

  Dim aitm As Float
  Dim adsc As Float
  Dim atax As Float
  Dim acrdt As Float
  Dim acash As Float

  Dim gitm As Float
  Dim gdsc As Float
  Dim gtax As Float
  Dim gcrdt As Float
  Dim gcash As Float
  Dim xx As String
  Dim res2 As Result

  Dim rte As Float
  Dim qty As Float
  Dim xitm As Float
  Dim xtax As String
  Dim xdsc As Float
  Dim xcrdt As Float
  Dim xcash As Float
  Dim RepoStr As String
  Dim i As Integer

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  $BillingReport = New CReportHTML([("SNO"), ("PARTICULARS"), ("RATE"), ("QTY"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("COMP: " & sComp & " RATE: " & sBillMode & " SCHEME: " & sDisc, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")

  gitm = 0
  gdsc = 0
  gtax = 0
  gcrdt = 0
  gcash = 0
  For Each xx In lst
    $BillingReport.AddSection(xx, True)

    aitm = 0
    adsc = 0
    atax = 0
    acrdt = 0
    acash = 0
    i = 1
    If sInvoiced = True Then
      res2 = $con.Exec("select flditemname,avg(flditemrate) as rate,SUM(flditemqty) as qnty," & modNonMedical.CashCreditBillSQL() & " from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype=&3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr & " GROUP BY flditemname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), xx, True, sComp, sBillMode, sDisc, sBillType)                                                                       ''
    Else
      res2 = $con.Exec("select flditemname,avg(flditemrate) as rate,SUM(flditemqty) as qnty," & modNonMedical.CashCreditBillSQL() & " from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and flditemtype=&3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr & " GROUP BY flditemname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), xx, True, sComp, sBillMode, sDisc, sBillType)
    Endif
    If res2.Available = True Then
      For Each res2
        rte = 0
        qty = 0
        xitm = 0
        xtax = 0
        xdsc = 0
        xcrdt = 0
        xcash = 0
        If res2["rate"] Then
          rte = res2["rate"]
        Endif
        If res2["qnty"] Then
          qty = res2["qnty"]
        Endif
        If res2["duemt"] Then
          xitm = res2["duemt"]
        Endif
        If res2["disctot"] Then
          xdsc = res2["disctot"]
        Endif
        If res2["taxtot"] Then
          xtax = res2["taxtot"]
        Endif
        If res2["xcredit"] Then
          xcrdt = res2["xcredit"]
        Endif
        If res2["xcash"] Then
          xcash = res2["xcash"]
        Endif

        aitm = aitm + xitm
        adsc = adsc + xdsc
        atax = atax + xtax
        acrdt = acrdt + xcrdt
        acash = acash + xcash
        With asx
          .Add(CStr(i))
          .Add(modString.HTMLBlankSpace(3) & res2["flditemname"])
          .Add(modReportVar.GetLocaleNumberFormat(rte, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(qty, -2))
          .Add(modReportVar.GetLocaleNumberFormat(xitm, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xdsc, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xcrdt, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xcash, gb.Currency))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
        i = i + 1
      Next
    Endif

    gitm = gitm + aitm
    gdsc = gdsc + adsc
    gtax = gtax + atax
    gcrdt = gcrdt + acrdt
    gcash = gcash + acash
    With asx
      .Add("")
      .Add("SUBTOTAL: " & xx)
      .Add("...")
      .Add("...")
      .Add(modReportVar.GetLocaleNumberFormat(aitm, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(adsc, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(atax, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(acrdt, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(acash, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  'Grand total
  With asx
    .Add("")
    .Add("<b>GRAND TOTAL</b>")
    .Add("***")
    .Add("***")
    .Add(modReportVar.GetLocaleNumberFormat(gitm, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(gdsc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(gtax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(gcrdt, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(gcash, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  Return $BillingReport.NewHTMLPath()

End

Public Function ServiceDetailDaywiseSumReport($con As Connection, dt1 As Date, dt2 As Date, lst As String[], sInvoiced As Boolean, sComp As String, sBillMode As String, sDisc As String, sBillType As String, sDtType As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim aitm As Float
  Dim adsc As Float
  Dim atax As Float
  Dim acrdt As Float
  Dim acash As Float

  Dim gitm As Float
  Dim gdsc As Float
  Dim gtax As Float
  Dim gcrdt As Float
  Dim gcash As Float
  Dim xx As String
  Dim res2 As Result

  Dim rte As Float
  Dim qty As Float
  Dim xitm As Float
  Dim xtax As Float
  Dim xdsc As Float
  Dim xcrdt As Float
  Dim xcash As Float

  Dim dt As Date
  Dim dtlst As Date[]

  Dim xfirdate As Date
  Dim xlasdate As Date
  Dim chapdate As String
  Dim RepoStr As String

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  $BillingReport = New CReportHTML([("CATEGORY"), ("RATE"), ("QTY"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("COMP: " & sComp & " RATE: " & sBillMode & " SCHEME: " & sDisc, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")

  If sDtType = "Year" Then
    If modBasic.$DateFormat = "BS Date" Then
      dtlst = modDate.GetSelectDateBSArrayBetween(gb.Year, dt1, dt2)
    Else
      dtlst = modDate.GetSelectDateArrayBetween(gb.Year, dt1, dt2)
    Endif
  Else If sDtType = "Month" Then
    If modBasic.$DateFormat = "BS Date" Then
      dtlst = modDate.GetSelectDateBSArrayBetween(gb.Month, dt1, dt2)
    Else
      dtlst = modDate.GetSelectDateArrayBetween(gb.Month, dt1, dt2)
    Endif
  Else
    dtlst = modDate.GetSelectDateArrayBetween(gb.Day, dt1, dt2)
  Endif

  gitm = 0
  gdsc = 0
  gtax = 0
  gcrdt = 0
  gcash = 0
  For Each dt In dtlst
    If sDtType = "Year" Then
      If modBasic.$DateFormat = "BS Date" Then
        chapdate = modDate.DateFormatViewBS(dt, "YearOnly")
        xfirdate = modDate.StartSqlYearBS(dt)
        xlasdate = modDate.EndSqlYearBS(dt)
      Else
        chapdate = Format(dt, "yyyy")
        xfirdate = modDate.StartSqlYear(dt)
        xlasdate = modDate.EndSqlYear(dt)
      Endif
    Else If sDtType = "Month" Then
      If modBasic.$DateFormat = "BS Date" Then
        chapdate = modDate.DateFormatViewBS(dt, "YearMonth")
        xfirdate = modDate.StartSqlMonthBS(dt)
        xlasdate = modDate.EndSqlMonthBS(dt)
      Else
        chapdate = Format(dt, "mmm yyyy")
        xfirdate = modDate.StartSqlMonth(dt)
        xlasdate = modDate.EndSqlMonth(dt)
      Endif
    Else
      chapdate = modReportVar.GetDateTimeReport(dt, gb.MediumDate)
      xfirdate = modDate.StartSqlDate(dt)
      xlasdate = modDate.EndSqlDate(dt)
    Endif
    xfirdate = modDate.StartSqlDate(Max(dt1, xfirdate))
    xlasdate = modDate.EndSqlDate(Min(dt2, xlasdate))
    $BillingReport.AddChapter(chapdate)

    aitm = 0
    adsc = 0
    atax = 0
    acrdt = 0
    acash = 0
    For Each xx In lst
      If sInvoiced = True Then
        res2 = $con.Exec("select avg(flditemrate) as rate,SUM(flditemqty) as qnty," & modNonMedical.CashCreditBillSQL() & " from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype=&3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr, xfirdate, xlasdate, xx, True, sComp, sBillMode, sDisc, sBillType)                                                                       ''
      Else
        res2 = $con.Exec("select avg(flditemrate) as rate,SUM(flditemqty) as qnty," & modNonMedical.CashCreditBillSQL() & " from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and flditemtype=&3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr, xfirdate, xlasdate, xx, True, sComp, sBillMode, sDisc, sBillType)
      Endif
      If res2.Available = True Then
        rte = 0
        qty = 0
        xitm = 0
        xtax = 0
        xdsc = 0
        xcrdt = 0
        xcash = 0
        If res2["rate"] Then
          rte = res2["rate"]
        Endif
        If res2["qnty"] Then
          qty = res2["qnty"]
        Endif
        If res2["duemt"] Then
          xitm = res2["duemt"]
        Endif
        If res2["disctot"] Then
          xdsc = res2["disctot"]
        Endif
        If res2["taxtot"] Then
          xtax = res2["taxtot"]
        Endif
        If res2["xcredit"] Then
          xcrdt = res2["xcredit"]
        Endif
        If res2["xcash"] Then
          xcash = res2["xcash"]
        Endif

        aitm = aitm + xitm
        adsc = adsc + xdsc
        atax = atax + xtax
        acrdt = acrdt + xcrdt
        acash = acash + xcash
        With asx
          .Add(modString.HTMLBlankSpace(5) & xx)
          .Add(modReportVar.GetLocaleNumberFormat(rte, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(qty, -2))
          .Add(modReportVar.GetLocaleNumberFormat(xitm, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xdsc, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xcrdt, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xcash, gb.Currency))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Endif
    Next

    gitm = gitm + aitm
    gdsc = gdsc + adsc
    gtax = gtax + atax
    gcrdt = gcrdt + acrdt
    gcash = gcash + acash
    'date total
    With asx
      .Add("SUBTOTAL: " & chapdate)
      .Add("...")
      .Add("...")
      .Add(modReportVar.GetLocaleNumberFormat(aitm, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(adsc, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(atax, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(acrdt, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(acash, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next 'date

  'Grand total
  With asx
    .Add("<b>GRAND TOTAL</b>")
    .Add("...")
    .Add("...")
    .Add(modReportVar.GetLocaleNumberFormat(gitm, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(gdsc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(gtax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(gcrdt, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(gcash, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  Return $BillingReport.NewHTMLPath()

End

Public Function GetServiceSUmmaryReportFormat($con As Connection, dt1 As Date, dt2 As Date, sCategory As String, sBillMode As String, sDisc As String, sComp As String, sInvoiced As Boolean, sBillType As String, sOption As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]

  Dim xfield As String
  Dim xList As String[]
  Dim xType As String
  Dim res As Result
  Dim res2 As Result

  Dim xrate As Float
  Dim xqty As Float
  Dim xsubt As Float
  Dim xdisc As Float
  Dim xtax As Float
  Dim xcrdt As Float
  Dim xcash As Float

  Dim asubt As Float
  Dim adisc As Float
  Dim atax As Float
  Dim acrdt As Float
  Dim acash As Float

  Dim psubt As Float
  Dim pdisc As Float
  Dim ptax As Float
  Dim pcrdt As Float
  Dim pcash As Float
  Dim RepoStr As String

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  $BillingReport = New CReportHTML([("PARTICULARS"), ("RATE"), ("QTY"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("SUMMARY BY " & sOption & " CATEGORY: " & sCategory & " COMP: " & sComp & " RATE: " & sBillMode & " SCHEME: " & sDisc, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")

  xfield = modRHTMLSummary.GetFieldServiceSummary(sOption)

  If sInvoiced = True Then
    res = $con.Exec(Subst("select distinct(&1) as col from " & $tblpatbilling, xfield) & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype like &3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
  Else
    res = $con.Exec(Subst("select distinct(&1) as col from " & $tblpatbilling, xfield) & " where fldtime>=&1 and fldtime<=&2 and flditemtype like &3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
  Endif
  xList = modControlSub.GetDirectFillresultNoNull(res)
  xList.Add("Null")

  psubt = 0
  pdisc = 0
  ptax = 0
  pcrdt = 0
  pcash = 0
  For Each xType In xList
    $BillingReport.AddSection(xType, True)

    asubt = 0
    adisc = 0
    atax = 0
    acrdt = 0
    acash = 0
    If xType = "Null" Then
      If sInvoiced = True Then
        res2 = $con.Exec("select flditemname,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty," & modNonMedical.CashCreditBillSQL() & " from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype like &3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8 and " & xfield & " IS NULL" & RepoStr & " GROUP BY flditemname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
      Else
        res2 = $con.Exec("select flditemname,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty," & modNonMedical.CashCreditBillSQL() & " from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and flditemtype like &3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8 and " & xfield & " IS NULL" & RepoStr & " GROUP BY flditemname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
      Endif
    Else
      If sInvoiced = True Then
        res2 = $con.Exec("select flditemname,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty," & modNonMedical.CashCreditBillSQL() & " from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype like &3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8 and " & xfield & "=&9" & RepoStr & " GROUP BY flditemname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType, xType)
      Else
        res2 = $con.Exec("select flditemname,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty," & modNonMedical.CashCreditBillSQL() & " from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and flditemtype like &3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8 and " & xfield & "=&9" & RepoStr & " GROUP BY flditemname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType, xType)
      Endif
    Endif
    If res2.Available Then
      For Each res2
        xrate = 0
        xqty = 0
        xsubt = 0
        xdisc = 0
        xtax = 0
        xcrdt = 0
        xcash = 0
        If res2["flditemrate"] Then
          xrate = res2["flditemrate"]
        Endif
        If res2["flditemqty"] Then
          xqty = res2["flditemqty"]
        Endif
        If res2["duemt"] Then
          xsubt = res2["duemt"]
        Endif
        If res2["disctot"] Then
          xdisc = res2["disctot"]
        Endif
        If res2["taxtot"] Then
          xtax = res2["taxtot"]
        Endif
        If res2["xcredit"] Then
          xcrdt = res2["xcredit"]
        Endif
        If res2["xcash"] Then
          xcash = res2["xcash"]
        Endif

        asubt = asubt + xsubt
        adisc = adisc + xdisc
        atax = atax + xtax
        acrdt = acrdt + xcrdt
        acash = acash + xcash
        With asx
          .Add(res2["flditemname"])
          .Add(modReportVar.GetLocaleNumberFormat(xrate, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xqty, 0))
          .Add(modReportVar.GetLocaleNumberFormat(xsubt, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xdisc, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xcrdt, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xcash, gb.Currency))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Next
    Endif

    psubt = psubt + asubt
    pdisc = pdisc + adisc
    ptax = ptax + atax
    pcrdt = pcrdt + acrdt
    pcash = pcash + acash
    With asx
      .Add("SUBTOTAL: " & xType)
      .Add("")
      .Add("")
      .Add(modReportVar.GetLocaleNumberFormat(asubt, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(adisc, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(atax, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(acrdt, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(acash, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
    With asx
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Next

  With asx
    .Add("<b>GRAND TOTAL</b>")
    .Add("")
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(psubt, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(pdisc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(ptax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(pcrdt, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(pcash, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  Return $BillingReport.NewHTMLPath()

End

Public Function GetServiceSUmmaryReportSchemeGrouped($con As Connection, dt1 As Date, dt2 As Date, sCategory As String, sBillMode As String, sComp As String, sInvoiced As Boolean, sBillType As String, sOption As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim discList As String[]
  Dim sDisc As String

  Dim xfield As String
  Dim xList As String[]
  Dim xType As String
  Dim res As Result
  Dim res2 As Result

  Dim xrate As Float
  Dim xqty As Float
  Dim xsubt As Float
  Dim xdisc As Float
  Dim xtax As Float
  Dim xtot As Float

  Dim asubt As Float
  Dim adisc As Float
  Dim atax As Float
  Dim atot As Float

  Dim bsubt As Float
  Dim bdisc As Float
  Dim btax As Float
  Dim btot As Float

  Dim psubt As Float
  Dim pdisc As Float
  Dim ptax As Float
  Dim ptot As Float

  Dim xfield1 As String
  Dim resn As Result
  Dim resl As Result
  Dim RepoStr As String
  Dim RepoStr1 As String

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  RepoStr1 = modDataRepo.GetWhereStringRepo(sLocaType, sLocation, "t1")
  $BillingReport = New CReportHTML([("PARTICULARS"), ("RATE"), ("QTY"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("NET")], "", "")
  $BillingReport.UserData.Add("SUMMARY BY " & sOption & " CATEGORY: " & sCategory & " COMP: " & sComp & " RATE: " & sBillMode & " SCHEME: " & sDisc, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")

  discList = modNonMedical.FillDiscountCombo()
  xfield = modRHTMLSummary.GetFieldServiceSummary(sOption)
  xfield1 = "t1." & xfield

  If sInvoiced = True Then
    res = $con.Exec(Subst("select distinct(&1) as col from " & $tblpatbilling, xfield) & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype like &3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, "%", sBillType)
  Else
    res = $con.Exec(Subst("select distinct(&1) as col from " & $tblpatbilling, xfield) & " where fldtime>=&1 and fldtime<=&2 and flditemtype like &3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, "%", sBillType)
  Endif
  xList = modControlSub.GetDirectFillresultNoNull(res)
  xList.Add("Null")

  psubt = 0
  pdisc = 0
  ptax = 0
  ptot = 0
  For Each xType In xList
    $BillingReport.AddSection(xType, True)

    bsubt = 0
    bdisc = 0
    btax = 0
    btot = 0
    For Each sDisc In discList
      $BillingReport.AddChapter(sDisc)

      asubt = 0
      adisc = 0
      atax = 0
      atot = 0
      If xType = "Null" Then
        If sInvoiced = True Then
          res2 = $con.Exec("select flditemtype,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype like &3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8 and " & xfield & " IS NULL" & RepoStr & " GROUP BY flditemtype", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
        Else
          res2 = $con.Exec("select flditemtype,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and flditemtype like &3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8 and " & xfield & " IS NULL" & RepoStr & " GROUP BY flditemtype", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
        Endif
      Else
        If sInvoiced = True Then
          res2 = $con.Exec("select flditemtype,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype like &3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8 and " & xfield & "=&9" & RepoStr & " GROUP BY flditemtype", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType, xType)
        Else
          res2 = $con.Exec("select flditemtype,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and flditemtype like &3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8 and " & xfield & "=&9" & RepoStr & " GROUP BY flditemtype", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType, xType)
        Endif
      Endif
      If res2.Available Then
        For Each res2
          xrate = 0
          xqty = 0
          xsubt = 0
          xdisc = 0
          xtax = 0
          xtot = 0
          If res2["flditemrate"] Then
            xrate = res2["flditemrate"]
          Endif
          If res2["flditemqty"] Then
            xqty = res2["flditemqty"]
          Endif
          If res2["itemtot"] Then
            xsubt = res2["itemtot"]
          Endif
          If res2["flddiscamt"] Then
            xdisc = res2["flddiscamt"]
          Endif
          If res2["fldtaxamt"] Then
            xtax = res2["fldtaxamt"]
          Endif
          If res2["fldditemamt"] Then
            xtot = res2["fldditemamt"]
          Endif

          asubt = asubt + xsubt
          adisc = adisc + xdisc
          atax = atax + xtax
          atot = atot + xtot
          With asx
            .Add(modString.HTMLBlankSpace(5) & res2["flditemtype"])
            .Add(modReportVar.GetLocaleNumberFormat(xrate, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(xqty, 0))
            .Add(modReportVar.GetLocaleNumberFormat(xsubt, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(xdisc, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
          End With
          $BillingReport.Add(asx)
          asx.Clear()
          ''breaking procedurees into components
          If res2["flditemtype"] = "Procedures" Then
            ''for procedure subtype
            If sInvoiced = True Then
              resn = $con.Exec("select t2.fldtarget as fldtarget,AVG(t1.flditemrate) as flditemrate,SUM(t1.flditemqty) as flditemqty,SUM(t1.flditemrate*t1.flditemqty) as itemtot,SUM(t1.flddiscamt) as flddiscamt,SUM(t1.fldtaxamt) as fldtaxamt,SUM(t1.fldditemamt) as fldditemamt from " & $tblpatbilling & " AS t1 inner join tblservicecost AS t2 on t1.flditemname=t2.flditemname where t1.fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and t1.flditemtype like &3 and t1.fldsave=&4 and t1.fldbillingmode like &6 and t1.flddisctype like &7 and t1.fldbilltype like &8 and " & xfield1 & "=&9 and t1.flditemtype=&{10}" & RepoStr1 & " GROUP BY t2.fldtarget", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType, xType, "Procedures")
            Else
              resn = $con.Exec("select t2.fldtarget as fldtarget,AVG(t1.flditemrate) as flditemrate,SUM(t1.flditemqty) as flditemqty,SUM(t1.flditemrate*t1.flditemqty) as itemtot,SUM(t1.flddiscamt) as flddiscamt,SUM(t1.fldtaxamt) as fldtaxamt,SUM(t1.fldditemamt) as fldditemamt from " & $tblpatbilling & " AS t1 inner join tblservicecost AS t2 on t1.flditemname=t2.flditemname where t1.fldtime>=&1 and t1.fldtime<=&2 and t1.flditemtype like &3 and t1.fldsave=&4 and t1.fldcomp like &5 and t1.fldbillingmode like &6 and t1.flddisctype like &7 and t1.fldbilltype like &8 and " & xfield1 & "=&9 and t1.flditemtype=&{10}" & RepoStr1 & " GROUP BY t2.fldtarget", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType, xType, "Procedures")
            Endif
            If resn.Available Then
              For Each resn
                xrate = 0
                xqty = 0
                xsubt = 0
                xdisc = 0
                xtax = 0
                xtot = 0
                If resn["flditemrate"] Then
                  xrate = resn["flditemrate"]
                Endif
                If resn["flditemqty"] Then
                  xqty = resn["flditemqty"]
                Endif
                If resn["itemtot"] Then
                  xsubt = resn["itemtot"]
                Endif
                If resn["flddiscamt"] Then
                  xdisc = resn["flddiscamt"]
                Endif
                If resn["fldtaxamt"] Then
                  xtax = resn["fldtaxamt"]
                Endif
                If resn["fldditemamt"] Then
                  xtot = resn["fldditemamt"]
                Endif
                With asx
                  .Add(modString.HTMLBlankSpace(7) & resn["fldtarget"])
                  .Add(modReportVar.GetLocaleNumberFormat(xrate, gb.Currency))
                  .Add(modReportVar.GetLocaleNumberFormat(xqty, 0))
                  .Add(modReportVar.GetLocaleNumberFormat(xsubt, gb.Currency))
                  .Add(modReportVar.GetLocaleNumberFormat(xdisc, gb.Currency))
                  .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
                  .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
                End With
                $BillingReport.Add(asx)
                asx.Clear()
              Next
            Endif
          Endif

        Next
      Endif

      bsubt = bsubt + asubt
      bdisc = bdisc + adisc
      btax = btax + atax
      btot = btot + atot
      With asx
        .Add(modString.HTMLBlankSpace(3) & "SUBTOTAL: " & sDisc)
        .Add("")
        .Add("")
        .Add(modReportVar.GetLocaleNumberFormat(asubt, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(adisc, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(atax, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(atot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      With asx
        .Add("")
        .Add("")
        .Add("")
        .Add("")
        .Add("")
        .Add("")
        .Add("")
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next

    psubt = psubt + bsubt
    pdisc = pdisc + bdisc
    ptax = ptax + btax
    ptot = ptot + btot
    With asx
      .Add("TOTAL: " & xType)
      .Add("")
      .Add("")
      .Add(modReportVar.GetLocaleNumberFormat(bsubt, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(bdisc, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(btax, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(btot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
    With asx
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Next

  With asx
    .Add("<b>GRAND TOTAL</b>")
    .Add("")
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(psubt, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(pdisc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(ptax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(ptot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  ''GRAND SUMMARY
  With asx
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  $BillingReport.AddSection("GRAND SUMMARY", True)
  If sInvoiced = True Then
    resl = $con.Exec("select flditemtype,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype like &3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr & " GROUP BY flditemtype", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, "%", sBillType)
  Else
    resl = $con.Exec("select flditemtype,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and flditemtype like &3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr & " GROUP BY flditemtype", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, "%", sBillType)
  Endif
  If resl.Available Then
    For Each resl
      xrate = 0
      xqty = 0
      xsubt = 0
      xdisc = 0
      xtax = 0
      xtot = 0
      If resl["flditemrate"] Then
        xrate = resl["flditemrate"]
      Endif
      If resl["flditemqty"] Then
        xqty = resl["flditemqty"]
      Endif
      If resl["itemtot"] Then
        xsubt = resl["itemtot"]
      Endif
      If resl["flddiscamt"] Then
        xdisc = resl["flddiscamt"]
      Endif
      If resl["fldtaxamt"] Then
        xtax = resl["fldtaxamt"]
      Endif
      If resl["fldditemamt"] Then
        xtot = resl["fldditemamt"]
      Endif
      With asx
        .Add(resl["flditemtype"])
        .Add(modReportVar.GetLocaleNumberFormat(xrate, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xqty, 0))
        .Add(modReportVar.GetLocaleNumberFormat(xsubt, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xdisc, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
  Endif

  Return $BillingReport.NewHTMLPath()

End

Public Function ServiceSingleDaywiseSumReport($con As Connection, dt1 As Date, dt2 As Date, sInvoiced As Boolean, sItem As String, sComp As String, sBillMode As String, sDisc As String, sBillType As String, sDtType As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res2 As Result

  Dim rte As Float
  Dim qty As Float
  Dim xitm As Float
  Dim subt As Float
  Dim xtax As Float
  Dim xdsc As Float

  Dim dt As Date
  Dim dtlst As Date[]

  Dim aqty As Float
  Dim aitm As Float
  Dim adsc As Float
  Dim atax As Float
  Dim atot As Float

  Dim xfirdate As Date
  Dim xlasdate As Date
  Dim chapdate As String
  Dim RepoStr As String

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  $BillingReport = New CReportHTML([("Date"), ("PARTICULARS"), ("Rate"), ("QTY"), ("SubTotal"), ("Disc"), ("Tax"), ("Total")], "", "")
  $BillingReport.UserData.Add("SERVICE SUMMARY REPORT :" & sItem, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")

  If sDtType = "Year" Then
    If modBasic.$DateFormat = "BS Date" Then
      dtlst = modDate.GetSelectDateBSArrayBetween(gb.Year, dt1, dt2)
    Else
      dtlst = modDate.GetSelectDateArrayBetween(gb.Year, dt1, dt2)
    Endif
  Else If sDtType = "Month" Then
    If modBasic.$DateFormat = "BS Date" Then
      dtlst = modDate.GetSelectDateBSArrayBetween(gb.Month, dt1, dt2)
    Else
      dtlst = modDate.GetSelectDateArrayBetween(gb.Month, dt1, dt2)
    Endif
  Else
    dtlst = modDate.GetSelectDateArrayBetween(gb.Day, dt1, dt2)
  Endif

  aitm = 0
  adsc = 0
  atax = 0
  atot = 0
  aqty = 0
  For Each dt In dtlst
    If sDtType = "Year" Then
      If modBasic.$DateFormat = "BS Date" Then
        chapdate = modDate.DateFormatViewBS(dt, "YearOnly")
        xfirdate = modDate.StartSqlYearBS(dt)
        xlasdate = modDate.EndSqlYearBS(dt)
      Else
        chapdate = Format(dt, "yyyy")
        xfirdate = modDate.StartSqlYear(dt)
        xlasdate = modDate.EndSqlYear(dt)
      Endif
    Else If sDtType = "Month" Then
      If modBasic.$DateFormat = "BS Date" Then
        chapdate = modDate.DateFormatViewBS(dt, "YearMonth")
        xfirdate = modDate.StartSqlMonthBS(dt)
        xlasdate = modDate.EndSqlMonthBS(dt)
      Else
        chapdate = Format(dt, "mmm yyyy")
        xfirdate = modDate.StartSqlMonth(dt)
        xlasdate = modDate.EndSqlMonth(dt)
      Endif
    Else
      chapdate = modReportVar.GetDateTimeReport(dt, gb.MediumDate)
      xfirdate = modDate.StartSqlDate(dt)
      xlasdate = modDate.EndSqlDate(dt)
    Endif
    xfirdate = modDate.StartSqlDate(Max(dt1, xfirdate))
    xlasdate = modDate.EndSqlDate(Min(dt2, xlasdate))

    If sInvoiced = True Then
      res2 = $con.Exec("select avg(flditemrate) as rate,SUM(flditemqty) as qnty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as dsc,SUM(fldtaxamt) as tax,SUM(fldditemamt) as totl from " & $tblpatbilling & " where flditemname=&1 and fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&2 and fldtime<=&3 and fldcomp like &5) and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr, sItem, xfirdate, xlasdate, True, sComp, sBillMode, sDisc, sBillType)                                                                       ''
    Else
      res2 = $con.Exec("select avg(flditemrate) as rate,SUM(flditemqty) as qnty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as dsc,SUM(fldtaxamt) as tax,SUM(fldditemamt) as totl from " & $tblpatbilling & " where flditemname=&1 and fldtime>=&2 and fldtime<=&3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr, sItem, xfirdate, xlasdate, True, sComp, sBillMode, sDisc, sBillType)
    Endif
    rte = 0
    qty = 0
    xitm = 0
    xtax = 0
    xdsc = 0
    subt = 0
    If res2.Available = True Then
      If res2["rate"] Then
        rte = res2["rate"]
      Endif
      If res2["qnty"] Then
        qty = res2["qnty"]
      Endif
      If res2["itemtot"] Then
        xitm = res2["itemtot"]
      Endif
      If res2["dsc"] Then
        xdsc = res2["dsc"]
      Endif
      If res2["tax"] Then
        xtax = res2["tax"]
      Endif
      If res2["totl"] Then
        subt = res2["totl"]
      Endif

      aqty = aqty + qty
      aitm = aitm + xitm
      adsc = adsc + xdsc
      atax = atax + xtax
      atot = atot + subt

      If qty Then
        With asx
          .Add(chapdate)
          .Add(sItem)
          .Add(modReportVar.GetLocaleNumberFormat(rte, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(qty, -2))
          .Add(modReportVar.GetLocaleNumberFormat(xitm, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xdsc, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(subt, gb.Currency))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Endif

    Endif
  Next

  With asx
    .Add("...")
    .Add("...")
    .Add("...")
    .Add(modReportVar.GetLocaleNumberFormat(aqty, -2))
    .Add(modReportVar.GetLocaleNumberFormat(aitm, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(adsc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(atax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(atot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  Return $BillingReport.NewHTMLPath()

End

''========================== Servive Stats =====================
Public Function GetServiceSUmmaryReportFormatGrouped($con As Connection, dt1 As Date, dt2 As Date, sCategory As String, sBillMode As String, sDisc As String, sComp As String, sInvoiced As Boolean, sBillType As String, sOption As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]

  Dim xfield As String
  Dim xList As String[]
  Dim xType As String
  Dim res As Result
  Dim res2 As Result

  Dim xrate As Float
  Dim xqty As Float
  Dim xsubt As Float
  Dim xdisc As Float
  Dim xtax As Float
  Dim xtot As Float

  Dim asubt As Float
  Dim adisc As Float
  Dim atax As Float
  Dim atot As Float

  Dim psubt As Float
  Dim pdisc As Float
  Dim ptax As Float
  Dim ptot As Float

  Dim xfield1 As String
  Dim resn As Result
  Dim resl As Result
  Dim RepoStr As String
  Dim RepoStr1 As String

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  RepoStr1 = modDataRepo.GetWhereStringRepo(sLocaType, sLocation, "t1")
  $BillingReport = New CReportHTML([("Particulars"), ("Rate"), ("QTY"), ("SubTotal"), ("Disc"), ("Tax"), ("Total")], "", "")
  $BillingReport.UserData.Add("SUMMARY BY " & sOption, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate) & " Category: " & sCategory & " COMP: " & sComp & " Plan: " & sBillMode & " Disc: " & sDisc, "PARAM2")

  xfield = modRHTMLSummary.GetFieldServiceSummary(sOption)
  xfield1 = "t1." & xfield

  If sInvoiced = True Then
    res = $con.Exec(Subst("select distinct(&1) as col from " & $tblpatbilling, xfield) & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype like &3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
  Else
    res = $con.Exec(Subst("select distinct(&1) as col from " & $tblpatbilling, xfield) & " where fldtime>=&1 and fldtime<=&2 and flditemtype like &3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
  Endif
  xList = modControlSub.GetDirectFillresultNoNull(res)
  xList.Add("Null")

  psubt = 0
  pdisc = 0
  ptax = 0
  ptot = 0
  For Each xType In xList
    $BillingReport.AddChapter(xType)

    asubt = 0
    adisc = 0
    atax = 0
    atot = 0
    If xType = "Null" Then
      If sInvoiced = True Then
        res2 = $con.Exec("select flditemtype,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype like &3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8 and " & xfield & " IS NULL" & RepoStr & " GROUP BY flditemtype", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
      Else
        res2 = $con.Exec("select flditemtype,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and flditemtype like &3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8 and " & xfield & " IS NULL" & RepoStr & " GROUP BY flditemtype", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
      Endif
    Else
      If sInvoiced = True Then
        res2 = $con.Exec("select flditemtype,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype like &3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8 and " & xfield & "=&9" & RepoStr & " GROUP BY flditemtype", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType, xType)
      Else
        res2 = $con.Exec("select flditemtype,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and flditemtype like &3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8 and " & xfield & "=&9" & RepoStr & " GROUP BY flditemtype", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType, xType)
      Endif
    Endif
    If res2.Available Then
      For Each res2
        xrate = 0
        xqty = 0
        xsubt = 0
        xdisc = 0
        xtax = 0
        xtot = 0
        If res2["flditemrate"] Then
          xrate = res2["flditemrate"]
        Endif
        If res2["flditemqty"] Then
          xqty = res2["flditemqty"]
        Endif
        If res2["itemtot"] Then
          xsubt = res2["itemtot"]
        Endif
        If res2["flddiscamt"] Then
          xdisc = res2["flddiscamt"]
        Endif
        If res2["fldtaxamt"] Then
          xtax = res2["fldtaxamt"]
        Endif
        If res2["fldditemamt"] Then
          xtot = res2["fldditemamt"]
        Endif

        asubt = asubt + xsubt
        adisc = adisc + xdisc
        atax = atax + xtax
        atot = atot + xtot
        With asx
          .Add(res2["flditemtype"])
          .Add(modReportVar.GetLocaleNumberFormat(xrate, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xqty, 0))
          .Add(modReportVar.GetLocaleNumberFormat(xsubt, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xdisc, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
        ''breaking procedurees into components
        If res2["flditemtype"] = "Procedures" Then
          ''for procedure subtype
          If sInvoiced = True Then
            resn = $con.Exec("select t2.fldtarget as fldtarget,AVG(t1.flditemrate) as flditemrate,SUM(t1.flditemqty) as flditemqty,SUM(t1.flditemrate*t1.flditemqty) as itemtot,SUM(t1.flddiscamt) as flddiscamt,SUM(t1.fldtaxamt) as fldtaxamt,SUM(t1.fldditemamt) as fldditemamt from " & $tblpatbilling & " AS t1 inner join tblservicecost AS t2 on t1.flditemname=t2.flditemname where t1.fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and t1.flditemtype like &3 and t1.fldsave=&4 and t1.fldbillingmode like &6 and t1.flddisctype like &7 and t1.fldbilltype like &8 and " & xfield1 & "=&9 and t1.flditemtype=&{10}" & RepoStr1 & " GROUP BY t2.fldtarget", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType, xType, "Procedures")
          Else
            resn = $con.Exec("select t2.fldtarget as fldtarget,AVG(t1.flditemrate) as flditemrate,SUM(t1.flditemqty) as flditemqty,SUM(t1.flditemrate*t1.flditemqty) as itemtot,SUM(t1.flddiscamt) as flddiscamt,SUM(t1.fldtaxamt) as fldtaxamt,SUM(t1.fldditemamt) as fldditemamt from " & $tblpatbilling & " AS t1 inner join tblservicecost AS t2 on t1.flditemname=t2.flditemname where t1.fldtime>=&1 and t1.fldtime<=&2 and t1.flditemtype like &3 and t1.fldsave=&4 and t1.fldcomp like &5 and t1.fldbillingmode like &6 and t1.flddisctype like &7 and t1.fldbilltype like &8 and " & xfield1 & "=&9 and t1.flditemtype=&{10}" & RepoStr1 & " GROUP BY t2.fldtarget", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType, xType, "Procedures")
          Endif
          If resn.Available Then
            For Each resn
              xrate = 0
              xqty = 0
              xsubt = 0
              xdisc = 0
              xtax = 0
              xtot = 0
              If resn["flditemrate"] Then
                xrate = resn["flditemrate"]
              Endif
              If resn["flditemqty"] Then
                xqty = resn["flditemqty"]
              Endif
              If resn["itemtot"] Then
                xsubt = resn["itemtot"]
              Endif
              If resn["flddiscamt"] Then
                xdisc = resn["flddiscamt"]
              Endif
              If resn["fldtaxamt"] Then
                xtax = resn["fldtaxamt"]
              Endif
              If resn["fldditemamt"] Then
                xtot = resn["fldditemamt"]
              Endif
              With asx
                .Add(modString.HTMLBlankSpace(5) & resn["fldtarget"])
                .Add(modReportVar.GetLocaleNumberFormat(xrate, gb.Currency))
                .Add(modReportVar.GetLocaleNumberFormat(xqty, 0))
                .Add(modReportVar.GetLocaleNumberFormat(xsubt, gb.Currency))
                .Add(modReportVar.GetLocaleNumberFormat(xdisc, gb.Currency))
                .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
                .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
              End With
              $BillingReport.Add(asx)
              asx.Clear()
            Next
          Endif
        Endif

      Next
    Endif

    psubt = psubt + asubt
    pdisc = pdisc + adisc
    ptax = ptax + atax
    ptot = ptot + atot
    With asx
      .Add("TOTAL: " & xType)
      .Add("")
      .Add("")
      .Add(modReportVar.GetLocaleNumberFormat(asubt, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(adisc, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(atax, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(atot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
    With asx
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Next

  With asx
    .Add("GRAND TOTAL")
    .Add("")
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(psubt, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(pdisc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(ptax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(ptot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  ''GRAND SUMMARY
  With asx
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  $BillingReport.AddSection("GRAND SUMMARY", True)
  If sInvoiced = True Then
    resl = $con.Exec("select flditemtype,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype like &3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr & " GROUP BY flditemtype", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
  Else
    resl = $con.Exec("select flditemtype,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and flditemtype like &3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & RepoStr & " GROUP BY flditemtype", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
  Endif
  If resl.Available Then
    For Each resl
      xrate = 0
      xqty = 0
      xsubt = 0
      xdisc = 0
      xtax = 0
      xtot = 0
      If resl["flditemrate"] Then
        xrate = resl["flditemrate"]
      Endif
      If resl["flditemqty"] Then
        xqty = resl["flditemqty"]
      Endif
      If resl["itemtot"] Then
        xsubt = resl["itemtot"]
      Endif
      If resl["flddiscamt"] Then
        xdisc = resl["flddiscamt"]
      Endif
      If resl["fldtaxamt"] Then
        xtax = resl["fldtaxamt"]
      Endif
      If resl["fldditemamt"] Then
        xtot = resl["fldditemamt"]
      Endif
      With asx
        .Add(resl["flditemtype"])
        .Add(modReportVar.GetLocaleNumberFormat(xrate, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xqty, 0))
        .Add(modReportVar.GetLocaleNumberFormat(xsubt, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xdisc, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
  Endif

  Return $BillingReport.NewHTMLPath()

End

Public Function GetServiceSUmmaryEntryFormat($con As Connection, dt1 As Date, dt2 As Date, sCategory As String, sBillMode As String, sDisc As String, sComp As String, sInvoiced As Boolean, sBillType As String, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]

  Dim xfield As String
  Dim xList As String[]
  Dim xType As String
  Dim res As Result
  Dim res2 As Result

  Dim xrate As Float
  Dim xqty As Float
  Dim xsubt As Float
  Dim xdisc As Float
  Dim xtax As Float
  Dim xtot As Float

  Dim asubt As Float
  Dim adisc As Float
  Dim atax As Float
  Dim atot As Float

  Dim psubt As Float
  Dim pdisc As Float
  Dim ptax As Float
  Dim ptot As Float
  Dim RepoStr As String

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  $BillingReport = New CReportHTML([("Particulars"), ("Rate"), ("QTY"), ("SubTotal"), ("Disc"), ("Tax"), ("Total")], "", "")
  $BillingReport.UserData.Add("SUMMARY BY Entry", "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate) & " Category: " & sCategory & " COMP: " & sComp & " Plan: " & sBillMode & " Disc: " & sDisc, "PARAM2")

  If sInvoiced = True Then
    res = $con.Exec("select distinct(fldadmitlocat) as col from tblencounter where fldencounterval in(select fldencounterval from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype like &3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8)" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
  Else
    res = $con.Exec("select distinct(fldadmitlocat) as col from tblencounter where fldencounterval in(select fldencounterval from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and flditemtype like &3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8)" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
  Endif
  xList = modControlSub.GetDirectFillresultNoNull(res)
  xList.Add("Null")

  psubt = 0
  pdisc = 0
  ptax = 0
  ptot = 0
  For Each xType In xList
    $BillingReport.AddSection(xType, True)

    asubt = 0
    adisc = 0
    atax = 0
    atot = 0
    If xType = "Null" Then
      xfield = " and fldencounterval in(select fldencounterval from tblencounter where fldadmitlocat IS NULL)"
      If sInvoiced = True Then
        res2 = $con.Exec("select flditemname,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype like &3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & xfield & RepoStr & " GROUP BY flditemname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
      Else
        res2 = $con.Exec("select flditemname,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and flditemtype like &3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & xfield & RepoStr & " GROUP BY flditemname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType)
      Endif
    Else
      xfield = " and fldencounterval in(select fldencounterval from tblencounter where fldadmitlocat=&9)"
      If sInvoiced = True Then
        res2 = $con.Exec("select flditemname,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldbillno in(select fldbillno from " & $tblpatbilldetail & " where fldtime>=&1 and fldtime<=&2 and fldcomp like &5) and flditemtype like &3 and fldsave=&4 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & xfield & RepoStr & " GROUP BY flditemname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType, xType)
      Else
        res2 = $con.Exec("select flditemname,AVG(flditemrate) as flditemrate,SUM(flditemqty) as flditemqty,SUM(flditemrate*flditemqty) as itemtot,SUM(flddiscamt) as flddiscamt,SUM(fldtaxamt) as fldtaxamt,SUM(fldditemamt) as fldditemamt from " & $tblpatbilling & " where fldtime>=&1 and fldtime<=&2 and flditemtype like &3 and fldsave=&4 and fldcomp like &5 and fldbillingmode like &6 and flddisctype like &7 and fldbilltype like &8" & xfield & RepoStr & " GROUP BY flditemname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sCategory, True, sComp, sBillMode, sDisc, sBillType, xType)
      Endif
    Endif
    If res2.Available Then
      For Each res2
        xrate = 0
        xqty = 0
        xsubt = 0
        xdisc = 0
        xtax = 0
        xtot = 0
        If res2["flditemrate"] Then
          xrate = res2["flditemrate"]
        Endif
        If res2["flditemqty"] Then
          xqty = res2["flditemqty"]
        Endif
        If res2["itemtot"] Then
          xsubt = res2["itemtot"]
        Endif
        If res2["flddiscamt"] Then
          xdisc = res2["flddiscamt"]
        Endif
        If res2["fldtaxamt"] Then
          xtax = res2["fldtaxamt"]
        Endif
        If res2["fldditemamt"] Then
          xtot = res2["fldditemamt"]
        Endif

        asubt = asubt + xsubt
        adisc = adisc + xdisc
        atax = atax + xtax
        atot = atot + xtot
        With asx
          .Add(res2["flditemname"])
          .Add(modReportVar.GetLocaleNumberFormat(xrate, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xqty, 0))
          .Add(modReportVar.GetLocaleNumberFormat(xsubt, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xdisc, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xtax, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Next
    Endif

    psubt = psubt + asubt
    pdisc = pdisc + adisc
    ptax = ptax + atax
    ptot = ptot + atot
    With asx
      .Add("TOTAL: " & xType)
      .Add("")
      .Add("")
      .Add(modReportVar.GetLocaleNumberFormat(asubt, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(adisc, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(atax, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(atot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
    With asx
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
      .Add("***")
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Next

  With asx
    .Add("GRAND TOTAL")
    .Add("")
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(psubt, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(pdisc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(ptax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(ptot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  Return $BillingReport.NewHTMLPath()

End
