' Gambas module file

' Private $ProgressBar1 As ProgressBar

''-------------------- supporting --------------------------
Private Function GetCollectionCount(res As Result) As Collection

  Dim aColl As Collection

  aColl = New Collection
  If res.Available Then
    For Each res
      If res["fldvalue"] Then
        aColl.Add(res["fldvalue"], res["fldname"])
      Else
        aColl.Add(0, res["fldname"])
      Endif
    Next
  Endif

  Return aColl

End

Private Function GetCollectionRecord(res As Result) As Collection

  Dim aColl As Collection

  aColl = New Collection
  If res.Available Then
    For Each res
      If res["fldvalue"] Then
        aColl.Add(res["fldvalue"], res["fldcode"] & "|" & res["fldname"])
      Else
        aColl.Add(0, res["fldcode"] & "|" & res["fldname"])
      Endif
    Next
  Endif

  Return aColl

End

Private Function GetCollectionDualRecord(res As Result) As Collection

  Dim aColl As Collection
  Dim xcnt As Float
  Dim xamt As Float

  aColl = New Collection
  If res.Available Then
    For Each res
      xcnt = 0
      xamt = 0
      If res["fldcount"] Then
        xcnt = res["fldcount"]
      Endif
      If res["fldamount"] Then
        xamt = res["fldamount"]
      Endif
      aColl.Add([xcnt, xamt], res["fldcode"] & "|" & res["fldname"])
    Next
  Endif

  Return aColl

End

''======================= distinct by stockid ==============================
Public Function ShowOpeningStockQtyColl($con As Connection, sType As String, dt As Date, sComp As String, sLocaType As String, sLocation As String) As Collection

  Dim dtx As Date
  Dim res As Result
  Dim rs1 As Result
  Dim rs2 As Result
  Dim rs3 As Result
  Dim rs4 As Result
  Dim rs5 As Result
  Dim rs6 As Result
  Dim rs7 As Result
  Dim rs8 As Result

  Dim bulqty As Float
  Dim purqty As Float
  Dim retqty As Float
  Dim salqty As Float
  Dim sentqty As Float
  Dim recvqty As Float
  Dim adjqty As Float
  Dim curqty As Float
  Dim xval As Float
  Dim RepoStr As String

  Dim rex As Result
  Dim rss3 As Result

  Dim aCollEntryAll As Collection
  Dim bCollPurchPast As Collection
  Dim bCollRetnPast As Collection
  Dim bCollBulkPast As Collection
  Dim bCollSalePast As Collection
  Dim bCollSentPast As Collection
  Dim bCollRecvPast As Collection
  Dim bCollAdjusPast As Collection

  Dim xColl As Collection

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  dtx = Now()

  aCollEntryAll = New Collection
  rs6 = $con.Exec("select fldstockid as fldname,SUM(fldqty) as fldvalue from tblentry where fldcategory=&1 and fldcomp like &2" & RepoStr & " GROUP BY fldname", sType, sComp)
  aCollEntryAll = GetCollectionCount(rs6)

  bCollPurchPast = New Collection
  rs1 = $con.Exec("select fldstockid as fldname,SUM(fldtotalqty) as fldvalue from tblpurchase where fldtime>&1 and fldtime<=&2 and fldcategory=&3 and fldcomp like &4 and fldsav=&5" & RepoStr & " GROUP BY fldname", modDate.EndSqlDate(dt), dtx, sType, sComp, False)
  bCollPurchPast = GetCollectionCount(rs1)

  bCollRetnPast = New Collection
  rs8 = $con.Exec("select fldstockid as fldname,SUM(fldqty) as fldvalue from tblstockreturn where fldtime>&1 and fldtime<=&2 and fldcomp like &3 and fldsave=&4" & RepoStr & " GROUP BY fldname", modDate.EndSqlDate(dt), dtx, sComp, True)
  bCollRetnPast = GetCollectionCount(rs8)

  bCollBulkPast = New Collection
  rs2 = $con.Exec("select fldstockid as fldname,SUM(fldqtydisp) as fldvalue from tblbulksale where fldtime>&1 and fldtime<=&2 and fldcategory=&3 and fldsave=&4 and fldcomp like &5" & RepoStr & " GROUP BY fldname", modDate.EndSqlDate(dt), dtx, sType, True, sComp)
  bCollBulkPast = GetCollectionCount(rs2)

  bCollSalePast = New Collection
  rs3 = $con.Exec("select t2.fldstockid as fldname,SUM(t1.flditemqty) as fldvalue from tblpatbilling AS t1 inner join tblentry AS t2 on t1.flditemno=t2.fldstockno where t1.fldtime>&1 and t1.fldtime<=&2 and t1.flditemtype=&3 and t1.fldcomp like &4 and t1.fldsave=&5" & RepoStr & " GROUP BY fldname", modDate.EndSqlDate(dt), dtx, sType, sComp, True)
  bCollSalePast = GetCollectionCount(rs3)

  bCollSentPast = New Collection
  rs4 = $con.Exec("select fldstockid as fldname,SUM(fldqty) as fldvalue from tbltransfer where fldtoentrytime>&1 and fldtoentrytime<=&2 and fldcategory=&3 and fldtosav=&4 and fldfromcomp like &5" & RepoStr & " GROUP BY fldname", modDate.EndSqlDate(dt), dtx, sType, True, sComp)
  bCollSentPast = GetCollectionCount(rs4)

  bCollRecvPast = New Collection
  rs5 = $con.Exec("select fldstockid as fldname,SUM(fldqty) as fldvalue from tbltransfer where fldtoentrytime>&1 and fldtoentrytime<=&2 and fldcategory=&3 and fldtosav=&4 and fldtocomp like &5" & RepoStr & " GROUP BY fldname", modDate.EndSqlDate(dt), dtx, sType, True, sComp)
  bCollRecvPast = GetCollectionCount(rs5)

  bCollAdjusPast = New Collection
  rs7 = $con.Exec("select fldstockid as fldname,SUM(fldcompqty-fldcurrqty) as fldvalue from tbladjustment where fldtime>&1 and fldtime<=&2 and fldcategory=&3 and fldsav=&4 and fldcomp like &5" & RepoStr & " GROUP BY fldname", modDate.EndSqlDate(dt), dtx, sType, True, sComp)
  bCollAdjusPast = GetCollectionCount(rs7)

  xColl = New Collection
  res = $con.Exec("select distinct(fldstockid) as fldstockid from tblentry where fldcategory=&1 and fldcomp like &2" & RepoStr, sType, sComp)
  If res.Available Then
    For Each res
      xval = 0

      curqty = 0
      If aCollEntryAll[res["fldstockid"]] Then
        curqty = aCollEntryAll[res["fldstockid"]]
      Endif

      purqty = 0
      If bCollPurchPast[res["fldstockid"]] Then
        purqty = bCollPurchPast[res["fldstockid"]]
      Endif

      retqty = 0
      If bCollRetnPast[res["fldstockid"]] Then
        retqty = bCollRetnPast[res["fldstockid"]]
      Endif

      bulqty = 0
      If bCollBulkPast[res["fldstockid"]] Then
        bulqty = bCollBulkPast[res["fldstockid"]]
      Endif

      salqty = 0
      If bCollSalePast[res["fldstockid"]] Then
        salqty = bCollSalePast[res["fldstockid"]]
      Endif

      rex = $con.Exec("select fldpatbilling from tblfisclosing where (fldstate=&1 or fldstate IS NULL)", "Active")
      If rex.Available Then
        For Each rex
          If rex["fldpatbilling"] = "tblpatbilling" Then
          Else
            rss3 = $con.Exec("select SUM(flditemqty) as qty from " & rex["fldpatbilling"] & " where fldtime>&1 and fldtime<=&2 and flditemno in(select fldstockno from tblentry where fldstockid=&3) and flditemtype=&4 and fldcomp like &5 and fldsave=&6" & RepoStr, modDate.EndSqlDate(dt), dtx, res["fldstockid"], sType, sComp, True)
            If rss3.Available = True Then
              If rss3["qty"] Then
                salqty = salqty + rss3["qty"]
              Endif
            Endif
          Endif
        Next
      Endif

      sentqty = 0
      If bCollSentPast[res["fldstockid"]] Then
        sentqty = bCollSentPast[res["fldstockid"]]
      Endif

      recvqty = 0
      If bCollRecvPast[res["fldstockid"]] Then
        recvqty = bCollRecvPast[res["fldstockid"]]
      Endif

      adjqty = 0
      If bCollAdjusPast[res["fldstockid"]] Then
        adjqty = bCollAdjusPast[res["fldstockid"]]
      Endif

      xval = curqty - (purqty - retqty + recvqty) + (salqty + bulqty + sentqty + adjqty)

      xColl.Add(xval, res["fldstockid"])
    Next
  Endif

  Return xColl

End

Public Function GetTransactionPurchaseColl($con As Connection, sType As String, dt1 As Date, dt2 As Date, sComp As String, sLocaType As String, sLocation As String) As Collection

  Dim rs1 As Result
  Dim RepoStr As String
  Dim xColl As Collection

  xColl = New Collection
  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  rs1 = $con.Exec("select fldstockid as fldname,SUM(fldtotalqty) as fldvalue from tblpurchase where fldtime>=&1 and fldtime<=&2 and fldcategory=&3 and fldcomp like &4 and fldsav=&5" & RepoStr & " GROUP BY fldname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sType, sComp, False)
  xColl = GetCollectionCount(rs1)

  Return xColl

End

Public Function GetTransactionPurReturnColl($con As Connection, sType As String, dt1 As Date, dt2 As Date, sComp As String, sLocaType As String, sLocation As String) As Collection

  Dim rs1 As Result
  Dim RepoStr As String
  Dim xColl As Collection

  xColl = New Collection
  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  rs1 = $con.Exec("select fldstockid as fldname,SUM(fldqty) as fldvalue from tblstockreturn where fldtime>=&1 and fldtime<=&2 and fldcomp like &3 and fldsave=&4" & RepoStr & " GROUP BY fldname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sComp, True)
  xColl = GetCollectionCount(rs1)

  Return xColl

End

Public Function GetTransactionBulkSaleColl($con As Connection, sType As String, dt1 As Date, dt2 As Date, sComp As String, sLocaType As String, sLocation As String) As Collection

  Dim rs2 As Result
  Dim RepoStr As String
  Dim xColl As Collection

  xColl = New Collection
  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  rs2 = $con.Exec("select fldstockid as fldname,SUM(fldqtydisp) as fldvalue from tblbulksale where fldtime>=&1 and fldtime<=&2 and fldcategory=&3 and fldsave=&4 and fldcomp like &5" & RepoStr & " GROUP BY fldname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sType, True, sComp)
  xColl = GetCollectionCount(rs2)

  Return xColl

End

Public Function GetTransactionBillingColl($con As Connection, sType As String, dt1 As Date, dt2 As Date, sComp As String, sLocaType As String, sLocation As String) As Collection

  ' Dim rex As Result
  ' Dim rs2 As Result
  Dim rs3 As Result
  Dim RepoStr As String
  Dim xColl As Collection

  xColl = New Collection
  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  rs3 = $con.Exec("select t2.fldstockid as fldname,SUM(t1.flditemqty) as fldvalue from tblpatbilling AS t1 inner join tblentry AS t2 on t1.flditemno=t2.fldstockno where t1.fldtime>=&1 and t1.fldtime<=&2 and t1.flditemtype=&3 and t1.fldcomp like &4 and t1.fldsave=&5" & RepoStr & " GROUP BY fldname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sType, sComp, True)
  xColl = GetCollectionCount(rs3)

  ' ' rex = $con.Exec("select fldpatbilling from tblfisclosing where (fldstate=&1 or fldstate IS NULL)", "Active")
  ' ' If rex.Available Then
  ' '   For Each rex
  ' '     If rex["fldpatbilling"] = "tblpatbilling" Then
  ' '     Else
  ' '
  ' '       rs2 = $con.Exec("select SUM(flditemqty) as qty from " & rex["fldpatbilling"] & " where fldtime>=&1 and fldtime<=&2 and flditemno in(select fldstockno from tblentry where fldstockid=&3) and flditemtype=&4 and fldcomp like &5 and fldsave=&6" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sItem, sType, sComp, True)
  ' '       If rs2.Available = True Then
  ' '         If rs2["qty"] Then
  ' '           salqty = salqty + rs2["qty"]
  ' '         Endif
  ' '       Endif
  ' '
  ' '     Endif
  ' '   Next
  ' ' Endif

  Return xColl

End

Public Function GetTransactionTransferFromColl($con As Connection, sType As String, dt1 As Date, dt2 As Date, sComp As String, sLocaType As String, sLocation As String) As Collection

  Dim rs4 As Result
  Dim RepoStr As String
  Dim xColl As Collection

  xColl = New Collection
  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  rs4 = $con.Exec("select fldstockid as fldname,SUM(fldqty) as fldvalue from tbltransfer where fldtoentrytime>=&1 and fldtoentrytime<=&2 and fldcategory=&3 and fldtosav=&4 and fldfromcomp like &5" & RepoStr & " GROUP BY fldname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sType, True, sComp)
  xColl = GetCollectionCount(rs4)

  Return xColl

End

Public Function GetTransactionTransferToColl($con As Connection, sType As String, dt1 As Date, dt2 As Date, sComp As String, sLocaType As String, sLocation As String) As Collection

  Dim rs5 As Result
  Dim RepoStr As String
  Dim xColl As Collection

  xColl = New Collection
  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  rs5 = $con.Exec("select fldstockid as fldname,SUM(fldqty) as fldvalue from tbltransfer where fldtoentrytime>=&1 and fldtoentrytime<=&2 and fldcategory=&3 and fldtosav=&4 and fldtocomp like &5" & RepoStr & " GROUP BY fldname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sType, True, sComp)
  xColl = GetCollectionCount(rs5)

  Return xColl

End

Public Function GetTransactionAdjustmentColl($con As Connection, sType As String, dt1 As Date, dt2 As Date, sComp As String, sLocaType As String, sLocation As String) As Collection

  Dim rs7 As Result
  Dim RepoStr As String
  Dim xColl As Collection

  xColl = New Collection
  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  rs7 = $con.Exec("select fldstockid as fldname,SUM(fldcompqty-fldcurrqty) as fldvalue from tbladjustment where fldtime>=&1 and fldtime<=&2 and fldcategory=&3 and fldsav=&4 and fldcomp like &5" & RepoStr & " GROUP BY fldname", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sType, True, sComp)
  xColl = GetCollectionCount(rs7)

  Return xColl

End

''''
'''
''
'

Public Function ShowSpecStockReportItemwise($con As Connection, sType As String, dt As Date, sComp As String, sList As String[], sLocaType As String, sLocation As String, ShowNull As Boolean) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim i As Integer
  Dim xcost As Float

  Dim xval As Float
  Dim sItem As String
  Dim xtot As Float
  Dim p As Integer
  Dim xgo As Boolean
  Dim aCollEntryAll As Collection

  ' If MMain.$IsGUIApp = True Then
  '   $ProgressBar1 = modAppSupport.FindWorkProgressBar(modHelpVariable.$LogInCategory)
  '   $ProgressBar1.Tag = "Const"
  ' Endif

  ' $BillingReport = New CReportHTML([("SNO"), ("PARTICULARS"),  ("QTY"), ("PUR-RATE"),("CUR-VALUE")], "", "")
  $BillingReport = New CReportHTML([("SNO"), ("PARTICULARS"), ("AVG CP*"), ("QTY")], "", "")
  $BillingReport.UserData.Add("CATEGORY: " & sType, "PARAM1")
  $BillingReport.UserData.Add("Date: " & modReportVar.GetDateTimeReport(dt, gb.MediumDate) & "   Comp: " & sComp, "PARAM2")

  aCollEntryAll = ShowOpeningStockQtyColl($con, sType, dt, sComp, sLocaType, sLocation)

  i = 1
  p = 1
  xtot = 0
  For Each sItem In sList
    xcost = 0
    xval = 0
    If aCollEntryAll[sItem] Then
      xval = aCollEntryAll[sItem]
    Endif
    xcost = modStock.GetAverageCostPriceByStockName(sItem, dt)
    ' xtot = xtot + xcost * xval
    If ShowNull = True Then
      xgo = True
    Else
      If xval = 0 Then
        xgo = False
      Else
        xgo = True
      Endif
    Endif
    If xgo = True Then
      With asx
        .Add(modReportVar.GetLocaleNumberFormat(i, 0))
        .Add(sItem)
        .Add(modReportVar.GetLocaleNumberFormat(xcost, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(xval, -2))
        ' .Add(modReportVar.GetLocaleNumberFormat(xcost * xval, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      i = i + 1
    Endif

    ' If MMain.$IsGUIApp = True Then
    '   $ProgressBar1.Value = p / sList.Count
    '   Wait
    ' Endif
    p = p + 1
  Next

  With asx
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    ' .Add("")
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  $BillingReport.AddSummary("Cost Price Calculation: " & modBasic.$InvReportCost)
  $BillingReport.AddSummary("* The Avg Rate is not the actual cost price but the average of all batches of the particular medicine.")

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowTransectionReportItemwise($con As Connection, sType As String, dt1 As Date, dt2 As Date, sComp As String, sList As String[], sLocaType As String, sLocation As String, ShowNull As Boolean) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim xvax As Float

  Dim bulqty As Float
  Dim purqty As Float
  Dim rtnqty As Float
  Dim salqty As Float
  Dim sentqty As Float
  Dim recvqty As Float
  Dim adjqty As Float

  Dim openqty As Float
  Dim i As Integer

  Dim aCollEntryAll As Collection
  Dim bCollPurchPast As Collection
  Dim bCollRetnPast As Collection
  Dim bCollBulkPast As Collection
  Dim bCollSalePast As Collection
  Dim bCollSentPast As Collection
  Dim bCollRecvPast As Collection
  Dim bCollAdjusPast As Collection

  Dim sItem As String
  Dim p As Integer
  Dim xgo As Boolean

  ' If MMain.$IsGUIApp = True Then
  '   $ProgressBar1 = modAppSupport.FindWorkProgressBar(modHelpVariable.$LogInCategory)
  '   $ProgressBar1.Tag = "Const"
  ' Endif

  $BillingReport = New CReportHTML([("SNO"), ("PARTICULARS"), ("OPENING"), ("PURCHASE"), ("RECEIVED"), ("RETURN"), ("SALES"), ("CONSUMED"), ("SENT"), ("ADJUST"), ("ENDING")], "", "")
  $BillingReport.UserData.Add("CATEGORY: " & sType, "PARAM1")
  $BillingReport.UserData.Add("Date: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate) & "   Comp: " & sComp, "PARAM2")

  aCollEntryAll = ShowOpeningStockQtyColl($con, sType, dt2, sComp, sLocaType, sLocation)
  bCollPurchPast = GetTransactionPurchaseColl($con, sType, dt1, dt2, sComp, sLocaType, sLocation)
  bCollRetnPast = GetTransactionPurReturnColl($con, sType, dt1, dt2, sComp, sLocaType, sLocation)
  bCollBulkPast = GetTransactionBulkSaleColl($con, sType, dt1, dt2, sComp, sLocaType, sLocation)
  bCollSalePast = GetTransactionBillingColl($con, sType, dt1, dt2, sComp, sLocaType, sLocation)
  bCollSentPast = GetTransactionTransferFromColl($con, sType, dt1, dt2, sComp, sLocaType, sLocation)
  bCollRecvPast = GetTransactionTransferToColl($con, sType, dt1, dt2, sComp, sLocaType, sLocation)
  bCollAdjusPast = GetTransactionAdjustmentColl($con, sType, dt1, dt2, sComp, sLocaType, sLocation)

  i = 1
  p = 1
  For Each sItem In sList
    xvax = 0
    purqty = 0
    rtnqty = 0
    bulqty = 0
    salqty = 0
    sentqty = 0
    recvqty = 0
    adjqty = 0
    If aCollEntryAll[sItem] Then
      xvax = aCollEntryAll[sItem]
    Endif
    If bCollPurchPast[sItem] Then
      purqty = bCollPurchPast[sItem]
    Endif
    If bCollRetnPast[sItem] Then
      rtnqty = bCollRetnPast[sItem]
    Endif
    If bCollBulkPast[sItem] Then
      bulqty = bCollBulkPast[sItem]
    Endif
    If bCollSalePast[sItem] Then
      salqty = bCollSalePast[sItem]
    Endif
    If bCollSentPast[sItem] Then
      sentqty = bCollSentPast[sItem]
    Endif
    If bCollRecvPast[sItem] Then
      recvqty = bCollRecvPast[sItem]
    Endif
    If bCollAdjusPast[sItem] Then
      adjqty = bCollAdjusPast[sItem]
    Endif

    openqty = xvax - (purqty - rtnqty + recvqty) + (salqty + bulqty + sentqty + adjqty)
    If ShowNull = True Then
      xgo = True
    Else
      If openqty = 0 And If rtnqty = 0 And If purqty = 0 And If recvqty = 0 And If salqty = 0 And If bulqty = 0 And If sentqty = 0 And If adjqty = 0 And If xvax = 0 Then
        xgo = False
      Else
        xgo = True
      Endif
    Endif
    If xgo = True Then
      With asx
        .Add(modReportVar.GetLocaleNumberFormat(i, 0))
        .Add(sItem)
        .Add(modReportVar.GetLocaleNumberFormat(openqty, -2))
        .Add(modReportVar.GetLocaleNumberFormat(purqty, -2))
        .Add(modReportVar.GetLocaleNumberFormat(recvqty, -2))
        .Add(modReportVar.GetLocaleNumberFormat(rtnqty, -2))
        .Add(modReportVar.GetLocaleNumberFormat(salqty, -2))
        .Add(modReportVar.GetLocaleNumberFormat(bulqty, -2))
        .Add(modReportVar.GetLocaleNumberFormat(sentqty, -2))
        .Add(modReportVar.GetLocaleNumberFormat(adjqty, -2))
        .Add(modReportVar.GetLocaleNumberFormat(xvax, -2))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      i = i + 1
    Endif

    ' If MMain.$IsGUIApp = True Then
    '   $ProgressBar1.Value = p / sList.Count
    '   Wait
    ' Endif
    p = p + 1
  Next

  Return $BillingReport.NewHTMLPath()

End

''========================== distinct by stockno ============================================
Public Function ShowSpecStockReport($con As Connection, sType As String, dt As Date, sComp As String, sList As String[], sLocaType As String, sLocation As String, ShowNull As Boolean) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result
  Dim dt2 As Date
  Dim xitem As String
  Dim i As Integer

  Dim rs1 As Result
  Dim rs2 As Result
  Dim rs3 As Result
  Dim rs4 As Result
  Dim rs5 As Result
  Dim rs6 As Result
  Dim rs7 As Result
  Dim rs8 As Result

  Dim bulqty As Float
  Dim purqty As Float
  Dim rtnqty As Float
  Dim salqty As Float
  Dim sentqty As Float
  Dim recvqty As Float
  Dim adjqty As Float
  Dim curqty As Float
  Dim xval As Float

  Dim rex As Result
  Dim rss3 As Result
  Dim xcost As Float
  Dim sumcost As Float
  Dim sumsale As Float
  Dim RepoStr As String
  Dim xgo As Boolean

  Dim aCollEntryAll As Collection
  Dim bCollPurchPast As Collection
  Dim bCollRetnPast As Collection
  Dim bCollBulkPast As Collection
  Dim bCollSalePast As Collection
  Dim bCollSentPast As Collection
  Dim bCollRecvPast As Collection
  Dim bCollAdjusPast As Collection

  ' If MMain.$IsGUIApp = True Then
  '   $ProgressBar1 = modAppSupport.FindWorkProgressBar(modHelpVariable.$LogInCategory)
  '   $ProgressBar1.Tag = "Const"
  ' Endif

  $BillingReport = New CReportHTML([("CODE"), ("PARTICULARS"), ("BATCH"), ("EXPIRY"), ("QTY"), ("PUR-RATE"), ("PUR-TOTAL"), ("SALE-RATE"), ("SALE-TOTAL")], "", "")
  $BillingReport.UserData.Add("CATEGORY: " & sType, "PARAM1")
  $BillingReport.UserData.Add("Date: " & modReportVar.GetDateTimeReport(dt, gb.MediumDate) & "   Comp: " & sComp, "PARAM2")

  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)
  dt2 = Now()

  aCollEntryAll = New Collection
  rs6 = $con.Exec("select CONVERT(fldstockno,CHAR) as fldcode,fldstockid as fldname,SUM(fldqty) as fldvalue from tblentry where fldcategory=&1 and fldcomp like &2" & RepoStr & " GROUP BY CONVERT(fldstockno,CHAR),fldname", sType, sComp)
  aCollEntryAll = GetCollectionRecord(rs6)

  bCollPurchPast = New Collection
  rs1 = $con.Exec("select CONVERT(fldstockno,CHAR) as fldcode,fldstockid as fldname,SUM(fldtotalqty) as fldvalue from tblpurchase where fldtime>&1 and fldtime<=&2 and fldcategory=&3 and fldcomp like &4 and fldsav=&5" & RepoStr & " GROUP BY CONVERT(fldstockno,CHAR),fldname", modDate.EndSqlDate(dt), dt2, sType, sComp, False)
  bCollPurchPast = GetCollectionRecord(rs1)

  bCollRetnPast = New Collection
  rs8 = $con.Exec("select CONVERT(fldstockno,CHAR) as fldcode,fldstockid as fldname,SUM(fldqty) as fldvalue from tblstockreturn where fldtime>&1 and fldtime<=&2 and fldcomp like &3 and fldsave=&4" & RepoStr & " GROUP BY CONVERT(fldstockno,CHAR),fldname", modDate.EndSqlDate(dt), dt2, sComp, True)
  bCollRetnPast = GetCollectionRecord(rs8)

  bCollBulkPast = New Collection
  rs2 = $con.Exec("select CONVERT(fldstockno,CHAR) as fldcode,fldstockid as fldname,SUM(fldqtydisp) as fldvalue from tblbulksale where fldtime>&1 and fldtime<=&2 and fldcategory=&3 and fldsave=&4 and fldcomp like &5" & RepoStr & " GROUP BY CONVERT(fldstockno,CHAR),fldname", modDate.EndSqlDate(dt), dt2, sType, True, sComp)
  bCollBulkPast = GetCollectionRecord(rs2)

  bCollSalePast = New Collection
  rs3 = $con.Exec("select CONVERT(t1.flditemno,CHAR) as fldcode,t2.fldstockid as fldname,SUM(t1.flditemqty) as fldvalue from tblpatbilling AS t1 inner join tblentry AS t2 on t1.flditemno=t2.fldstockno where t1.fldtime>&1 and t1.fldtime<=&2 and t1.flditemtype=&3 and t1.fldcomp like &4 and t1.fldsave=&5" & modDataRepo.GetWhereStringRepo(sLocaType, sLocation, "t1") & " GROUP BY CONVERT(t1.flditemno,CHAR),fldname", modDate.EndSqlDate(dt), dt2, sType, sComp, True)
  bCollSalePast = GetCollectionRecord(rs3)

  bCollSentPast = New Collection
  rs4 = $con.Exec("select CONVERT(fldoldstockno,CHAR) as fldcode,fldstockid as fldname,SUM(fldqty) as fldvalue from tbltransfer where fldtoentrytime>&1 and fldtoentrytime<=&2 and fldcategory=&3 and fldtosav=&4 and fldfromcomp like &5" & RepoStr & " GROUP BY CONVERT(fldoldstockno,CHAR),fldname", modDate.EndSqlDate(dt), dt2, sType, True, sComp)
  bCollSentPast = GetCollectionRecord(rs4)

  bCollRecvPast = New Collection
  rs5 = $con.Exec("select CONVERT(fldstockno,CHAR) as fldcode,fldstockid as fldname,SUM(fldqty) as fldvalue from tbltransfer where fldtoentrytime>&1 and fldtoentrytime<=&2 and fldcategory=&3 and fldtosav=&4 and fldtocomp like &5" & RepoStr & " GROUP BY CONVERT(fldstockno,CHAR),fldname", modDate.EndSqlDate(dt), dt2, sType, True, sComp)
  bCollRecvPast = GetCollectionRecord(rs5)

  bCollAdjusPast = New Collection
  rs7 = $con.Exec("select CONVERT(fldstockno,CHAR) as fldcode,fldstockid as fldname,SUM(fldcompqty-fldcurrqty) as fldvalue from tbladjustment where fldtime>&1 and fldtime<=&2 and fldcategory=&3 and fldsav=&4 and fldcomp like &5" & RepoStr & " GROUP BY CONVERT(fldstockno,CHAR),fldname", modDate.EndSqlDate(dt), dt2, sType, True, sComp)
  bCollAdjusPast = GetCollectionRecord(rs7)

  i = 0
  sumcost = 0
  sumsale = 0
  For Each xitem In sList

    res = $con.Exec("select CONVERT(fldstockno,CHAR) as col,fldstockid,fldsellpr,fldpast from tblentry where fldcategory=&1 and fldstockid=&2" & RepoStr, sType, xitem)
    For Each res
      xcost = 0
      xval = 0

      curqty = 0
      If aCollEntryAll[res["col"] & "|" & res["fldstockid"]] Then
        curqty = aCollEntryAll[res["col"] & "|" & res["fldstockid"]]
      Endif

      purqty = 0
      If bCollPurchPast[res["col"] & "|" & res["fldstockid"]] Then
        purqty = bCollPurchPast[res["col"] & "|" & res["fldstockid"]]
      Endif

      rtnqty = 0
      If bCollRetnPast[res["col"] & "|" & res["fldstockid"]] Then
        rtnqty = bCollRetnPast[res["col"] & "|" & res["fldstockid"]]
      Endif

      bulqty = 0
      If bCollBulkPast[res["col"] & "|" & res["fldstockid"]] Then
        bulqty = bCollBulkPast[res["col"] & "|" & res["fldstockid"]]
      Endif

      salqty = 0
      If bCollSalePast[res["col"] & "|" & res["fldstockid"]] Then
        salqty = bCollSalePast[res["col"] & "|" & res["fldstockid"]]
      Endif

      rex = $con.Exec("select fldpatbilling from tblfisclosing where (fldstate=&1 or fldstate IS NULL)", "Active")
      If rex.Available Then
        For Each rex
          If rex["fldpatbilling"] = "tblpatbilling" Then
          Else
            rss3 = $con.Exec("select SUM(flditemqty) as qty from " & rex["fldpatbilling"] & " where fldtime>&1 and fldtime<=&2 and flditemno=&3 and flditemno in(select fldstockno from tblentry where fldstockid=&4) and flditemtype=&5 and fldcomp like &6 and fldsave=&7" & RepoStr, modDate.EndSqlDate(dt), dt2, CInt(res["col"]), res["fldstockid"], sType, sComp, True)
            If rss3.Available = True Then
              If rss3["qty"] Then
                salqty = salqty + rss3["qty"]
              Endif
            Endif
          Endif
        Next
      Endif

      sentqty = 0
      If bCollSentPast[res["col"] & "|" & res["fldstockid"]] Then
        sentqty = bCollSentPast[res["col"] & "|" & res["fldstockid"]]
      Endif

      recvqty = 0
      If bCollRecvPast[res["col"] & "|" & res["fldstockid"]] Then
        recvqty = bCollRecvPast[res["col"] & "|" & res["fldstockid"]]
      Endif

      adjqty = 0
      If bCollAdjusPast[res["col"] & "|" & res["fldstockid"]] Then
        adjqty = bCollAdjusPast[res["col"] & "|" & res["fldstockid"]]
      Endif

      xval = curqty - (purqty - rtnqty + recvqty) + (salqty + bulqty + sentqty + adjqty)
      If ShowNull = True Then
        xgo = True
      Else
        If xval = 0 Then
          xgo = False
        Else
          xgo = True
        Endif
      Endif
      If xgo = True Then
        xcost = modStock.GetAverageCostPriceByStockNo(res["col"], dt)
        sumcost = sumcost + xcost * xval
        sumsale = sumsale + res["fldsellpr"] * xval

        With asx
          .Add(res["col"])
          .Add(res["fldstockid"])
          .Add(modStock.GetBatchFromStockNo(CInt(res["col"])))
          .Add(modReportVar.GetDateTimeReport(modStock.GetExpiryFromStockNo(res["col"]), gb.MediumDate))
          .Add(modReportVar.GetLocaleNumberFormat(xval, -2))
          .Add(modReportVar.GetLocaleNumberFormat(xcost, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xcost * xval, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(res["fldsellpr"], gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(res["fldsellpr"] * xval, gb.Currency))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Endif

    Next

    ' If MMain.$IsGUIApp = True Then
    '   $ProgressBar1.Value = (i + 1) / sList.Count
    '   Wait
    ' Endif
    i = i + 1
  Next

  With asx
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
  End With
  $BillingReport.Add(asx)
  asx.Clear()
  With asx
    .Add("")
    .Add("<b>GRAND TOTAL</b>")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(sumcost, gb.Currency))
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(sumsale, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  $BillingReport.AddSummary("Cost Price Calculation: " & modBasic.$InvReportCost)
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowTransectionReport($con As Connection, sType As String, dt1 As Date, dt2 As Date, sComp As String, sList As String[], sLocaType As String, sLocation As String, ShowNull As Boolean) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result
  Dim xitem As String
  Dim i As Integer
  Dim xpast As Float
  Dim sFormat As String
  Dim xavrg As Float

  'for last stock calculation
  Dim rsx1 As Result
  Dim rsx2 As Result
  Dim rsx3 As Result
  Dim rsx4 As Result
  Dim rsx5 As Result
  Dim rsx6 As Result
  Dim rsx7 As Result
  Dim rsx8 As Result

  Dim bulqx As Float
  Dim purqx As Float
  Dim rtnqx As Float
  Dim salqx As Float
  Dim sentqx As Float
  Dim recvqx As Float
  Dim adjqtx As Float
  Dim curqty As Float
  Dim xvax As Float

  'for transection during interval
  Dim rs1 As Result
  Dim pur As Float
  Dim rs8 As Result
  Dim rtn As Float
  Dim rs2 As Result
  Dim blk As Float
  Dim rs3 As Result
  Dim sale As Float
  Dim disp As Float
  Dim rs4 As Result
  Dim sent As Float
  Dim rs5 As Result
  Dim recv As Float
  Dim rs7 As Result
  Dim adj As Float

  Dim bulqty As Float
  Dim bulamt As Float
  Dim purqty As Float
  Dim puramt As Float
  Dim rtnqty As Float
  Dim rtnamt As Float
  Dim salqty As Float
  Dim salamt As Float
  Dim dispamt As Float
  Dim sentqty As Float
  Dim sentamt As Float
  Dim recvqty As Float
  Dim recvamt As Float
  Dim adjqty As Float
  Dim adjamt As Float

  Dim openqty As Float
  Dim dtx As Date
  Dim RepoStr As String

  Dim rex As Result
  Dim rxx3 As Result
  Dim rss3 As Result
  Dim xgo As Boolean

  ' If MMain.$IsGUIApp = True Then
  '   $ProgressBar1 = modAppSupport.FindWorkProgressBar(modHelpVariable.$LogInCategory)
  '   $ProgressBar1.Tag = "Const"
  ' Endif

  Select modBasic.$InvReportCost
    Case "Average", "Latest", "Fixed"
      sFormat = "Setting"
      $BillingReport = New CReportHTML([("CODE"), ("PARTICULARS"), ("BATCH"), ("OPEN(QTY)"), ("OPEN(CP)"), ("PUR(QTY)"), ("PUR(CP)"), ("RECV(QTY)"), ("RECV(CP)"), ("RETN(QTY)"), ("RETN(CP)"), ("SALE(QTY)"), ("SALE(CP)"), ("SALE(SP)"), ("USE(QTY)"), ("USE(CP)"), ("SENT(QTY)"), ("SENT(CP)"), ("ADJ(QTY)"), ("ADJ(CP)"), ("END(QTY)"), ("END(CP)")], "", "")
    Case Else
      sFormat = "Exact"
      $BillingReport = New CReportHTML([("CODE"), ("PARTICULARS"), ("BATCH"), ("OPEN(QTY)"), ("OPEN(CP)"), ("PUR(QTY)"), ("PUR(CP)"), ("RECV(QTY)"), ("RECV(CP)"), ("RETN(QTY)"), ("RETN(CP)"), ("SALE(QTY)"), ("SALE(CP)"), ("USE(QTY)"), ("USE(CP)"), ("SENT(QTY)"), ("SENT(CP)"), ("ADJ(QTY)"), ("ADJ(CP)"), ("END(QTY)"), ("END(CP)")], "", "")
  End Select
  ' $BillingReport = New CReportHTML([("CODE"), ("PARTICULARS"), ("BATCH"), ("OPEN(QTY)"), ("OPEN(AMT)"), ("PUR(QTY)"), ("PUR(AMT)"), ("RECV(QTY)"), ("RECV(AMT)"), ("SALE(QTY)"), ("SALE(AMT)"), ("USE(QTY)"), ("USE(AMT)"), ("SENT(QTY)"), ("SENT(AMT)"), ("ADJ(QTY)"), ("ADJ(AMT)"), ("END(QTY)"), ("EST-Cost")], "", "")
  $BillingReport.UserData.Add("CATEGORY: " & sType, "PARAM1")
  $BillingReport.UserData.Add("Date: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate) & "   Comp: " & sComp, "PARAM2")
  RepoStr = modDataRepo.GetWhereStringRepo(sLocaType, sLocation)

  pur = 0
  rtn = 0
  sale = 0
  disp = 0
  blk = 0
  sent = 0
  recv = 0
  adj = 0
  dtx = Now()
  i = 0
  For Each xitem In sList
    res = $con.Exec("select fldstockno as col,fldstockid,fldbatch,fldpast from tblentry where fldcategory=&1 and fldstockid=&2" & RepoStr, sType, xitem)
    For Each res
      xavrg = 0
      If sFormat = "Setting" Then
        xavrg = modStock.GetAverageCostPriceByStockNo(res["col"], dt2)
      Endif

      xvax = 0
      xpast = 0
      If res["fldpast"] Then
        xpast = res["fldpast"]
      Else
        xpast = 0
      Endif

      'calculate current stock ---------------------------------------
      curqty = 0
      rsx6 = $con.Exec("select SUM(fldqty) as col from tblentry where fldstockno=&1 and fldstockid=&2 and fldcategory=&3 and fldcomp like &4" & RepoStr, res["col"], res["fldstockid"], sType, sComp)
      If rsx6.Available = True Then
        If rsx6["col"] Then
          curqty = rsx6["col"]
        Endif
      Endif

      ''for last stock calculation -------------------------
      purqx = 0
      rsx1 = $con.Exec("select SUM(fldtotalqty) as qty from tblpurchase where fldtime>&1 and fldtime<=&2 and fldstockno=&3 and fldstockid=&4 and fldcategory=&5 and fldcomp like &6 and fldsav=&7" & RepoStr, modDate.EndSqlDate(dt2), dtx, res["col"], res["fldstockid"], sType, sComp, False)
      If rsx1.Available = True Then
        If rsx1["qty"] Then
          purqx = rsx1["qty"]
        Endif
      Endif

      rtnqx = 0
      rsx8 = $con.Exec("select SUM(fldqty) as qty from tblstockreturn where fldtime>&1 and fldtime<=&2 and fldstockno=&3 and fldstockid=&4 and fldcomp like &5 and fldsave=&6" & RepoStr, modDate.EndSqlDate(dt2), dtx, res["col"], res["fldstockid"], sComp, True)
      If rsx8.Available = True Then
        If rsx8["qty"] Then
          rtnqx = rsx8["qty"]
        Endif
      Endif

      bulqx = 0
      rsx2 = $con.Exec("select SUM(fldqtydisp) as qty from tblbulksale where fldtime>&1 and fldtime<=&2 and fldstockno=&3 and fldstockid=&4 and fldcategory=&5 and fldsave=&6 and fldcomp like &7" & RepoStr, modDate.EndSqlDate(dt2), dtx, res["col"], res["fldstockid"], sType, True, sComp)
      If rsx2.Available = True Then
        If rsx2["qty"] Then
          bulqx = rsx2["qty"]
        Endif
      Endif

      salqx = 0
      rsx3 = $con.Exec("select SUM(flditemqty) as qty from tblpatbilling where fldtime>&1 and fldtime<=&2 and flditemno=&3 and flditemno in(select fldstockno from tblentry where fldstockid=&4) and flditemtype=&5 and fldcomp like &6 and fldsave=&7" & RepoStr, modDate.EndSqlDate(dt2), dtx, res["col"], res["fldstockid"], sType, sComp, True)
      If rsx3.Available = True Then
        If rsx3["qty"] Then
          salqx = rsx3["qty"]
        Endif
      Endif

      rex = $con.Exec("select fldpatbilling from tblfisclosing where (fldstate=&1 or fldstate IS NULL)", "Active")
      If rex.Available Then
        For Each rex
          If rex["fldpatbilling"] = "tblpatbilling" Then
          Else
            rxx3 = $con.Exec("select SUM(flditemqty) as qty from " & rex["fldpatbilling"] & " where fldtime>&1 and fldtime<=&2 and flditemno=&3 and flditemno in(select fldstockno from tblentry where fldstockid=&4) and flditemtype=&5 and fldcomp like &6 and fldsave=&7" & RepoStr, modDate.EndSqlDate(dt2), dtx, res["col"], res["fldstockid"], sType, sComp, True)
            If rxx3.Available = True Then
              If rxx3["qty"] Then
                salqx = salqx + rxx3["qty"]
              Endif
            Endif
          Endif
        Next
      Endif

      sentqx = 0
      rsx4 = $con.Exec("select SUM(fldqty) as qty from tbltransfer where fldoldstockno=&1 and fldstockid=&2 and fldtoentrytime>&3 and fldtoentrytime<=&4 and fldcategory=&5 and fldtosav=&6 and fldfromcomp like &7" & RepoStr, res["col"], res["fldstockid"], modDate.EndSqlDate(dt2), dtx, sType, True, sComp)
      If rsx4.Available Then
        If rsx4["qty"] Then
          sentqx = rsx4["qty"]
        Endif
      Endif

      recvqx = 0
      rsx5 = $con.Exec("select SUM(fldqty) as qty from tbltransfer where fldstockno=&1 and fldstockid=&2 and fldtoentrytime>&3 and fldtoentrytime<=&4 and fldcategory=&5 and fldtosav=&6 and fldtocomp like &7" & RepoStr, res["col"], res["fldstockid"], modDate.EndSqlDate(dt2), dtx, sType, True, sComp)
      If rsx5.Available Then
        If rsx5["qty"] Then
          recvqx = rsx5["qty"]
        Endif
      Endif

      adjqtx = 0
      rsx7 = $con.Exec("select sum(fldcompqty-fldcurrqty) as qty from tbladjustment where fldstockno=&1 and fldstockid=&2 and fldtime>&3 and fldtime<=&4 and fldcategory=&5 and fldsav=&6 and fldcomp like &7" & RepoStr, res["col"], res["fldstockid"], modDate.EndSqlDate(dt2), dtx, sType, True, sComp)
      If rsx7.Available Then
        If rsx7["qty"] Then
          adjqtx = rsx7["qty"]
        Endif
      Endif

      'for transection during interval ------------------------------------------
      purqty = 0
      puramt = 0
      rs1 = $con.Exec("select SUM(fldtotalqty) as qty,SUM(fldnetcost*fldtotalqty) as col from tblpurchase where fldtime>=&1 and fldtime<=&2 and fldstockno=&3 and fldstockid=&4 and fldcategory=&5 and fldcomp like &6 and fldsav=&7" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), res["col"], res["fldstockid"], sType, sComp, False)
      If rs1.Available = True Then
        If rs1["qty"] Then
          purqty = rs1["qty"]
        Endif
        If sFormat = "Setting" Then
          puramt = purqty * xavrg
        Else
          If rs1["col"] Then
            puramt = rs1["col"]
          Endif
        Endif
      Endif

      rtnqty = 0
      rtnamt = 0
      rs8 = $con.Exec("select SUM(fldqty) as qty,SUM(fldcost*fldqty) as col from tblstockreturn where fldtime>=&1 and fldtime<=&2 and fldstockno=&3 and fldstockid=&4 and fldcomp like &5 and fldsave=&6" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), res["col"], res["fldstockid"], sComp, True)
      If rs8.Available = True Then
        If rs8["qty"] Then
          rtnqty = rs8["qty"]
        Endif
        If sFormat = "Setting" Then
          rtnamt = rtnqty * xavrg
        Else
          If rs8["col"] Then
            rtnamt = rs8["col"]
          Endif
        Endif
      Endif

      bulqty = 0
      bulamt = 0
      rs2 = $con.Exec("select SUM(fldqtydisp) as qty,SUM(fldnetcost*fldqtydisp) as col from tblbulksale where fldtime>=&1 and fldtime<=&2 and fldstockno=&3 and fldstockid=&4 and fldcategory=&5 and fldsave=&6 and fldcomp like &7" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), res["col"], res["fldstockid"], sType, True, sComp)
      If rs2.Available = True Then
        If rs2["qty"] Then
          bulqty = rs2["qty"]
        Endif
        If sFormat = "Setting" Then
          bulamt = bulqty * xavrg
        Else
          If rs2["col"] Then
            bulamt = rs2["col"]
          Endif
        Endif
      Endif

      salqty = 0
      salamt = 0
      dispamt = 0
      rs3 = $con.Exec("select SUM(flditemqty) as qty,SUM(fldditemamt) as col from tblpatbilling where fldtime>=&1 and fldtime<=&2 and flditemno=&3 and flditemno in(select fldstockno from tblentry where fldstockid=&4) and flditemtype=&5 and fldcomp like &6 and fldsave=&7" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), res["col"], res["fldstockid"], sType, sComp, True)
      If rs3.Available = True Then
        If rs3["qty"] Then
          salqty = rs3["qty"]
        Endif
        If sFormat = "Setting" Then
          salamt = salqty * xavrg
          If rs3["col"] Then
            dispamt = rs3["col"]
          Endif
        Else
          If rs3["col"] Then
            salamt = rs3["col"]
          Endif
        Endif
      Endif

      rex = $con.Exec("select fldpatbilling from tblfisclosing where (fldstate=&1 or fldstate IS NULL)", "Active")
      If rex.Available Then
        For Each rex
          If rex["fldpatbilling"] = "tblpatbilling" Then
          Else
            rss3 = $con.Exec("select SUM(flditemqty) as qty,SUM(fldditemamt) as col from " & rex["fldpatbilling"] & " where fldtime>=&1 and fldtime<=&2 and flditemno=&3 and flditemno in(select fldstockno from tblentry where fldstockid=&4) and flditemtype=&5 and fldcomp like &6 and fldsave=&7" & RepoStr, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), res["col"], res["fldstockid"], sType, sComp, True)
            If rss3.Available = True Then
              If rss3["qty"] Then
                salqty = salqty + rss3["qty"]
              Endif
              If sFormat = "Setting" Then
                salamt = salamt + (salqty * xavrg)
                If rss3["col"] Then
                  dispamt = dispamt + rss3["col"]
                Endif
              Else
                If rss3["col"] Then
                  salamt = salamt + rss3["col"]
                Endif
              Endif
            Endif
          Endif
        Next
      Endif

      sentqty = 0
      sentamt = 0
      rs4 = $con.Exec("select SUM(fldqty) as qty,SUM(fldqty*fldnetcost) as totl from tbltransfer where fldoldstockno=&1 and fldstockid=&2 and fldtoentrytime>=&3 and fldtoentrytime<=&4 and fldcategory=&5 and fldtosav=&6 and fldfromcomp like &7" & RepoStr, res["col"], res["fldstockid"], modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sType, True, sComp)
      If rs4.Available Then
        If rs4["qty"] Then
          sentqty = rs4["qty"]
        Endif
        If sFormat = "Setting" Then
          sentamt = sentqty * xavrg
        Else
          If rs4["totl"] Then
            sentamt = rs4["totl"]
          Endif
        Endif
      Endif

      recvqty = 0
      recvamt = 0
      rs5 = $con.Exec("select SUM(fldqty) as qty,SUM(fldqty*fldnetcost) as totl from tbltransfer where fldstockno=&1 and fldstockid=&2 and fldtoentrytime>=&3 and fldtoentrytime<=&4 and fldcategory=&5 and fldtosav=&6 and fldtocomp like &7" & RepoStr, res["col"], res["fldstockid"], modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sType, True, sComp)
      If rs5.Available Then
        If rs5["qty"] Then
          recvqty = rs5["qty"]
        Endif
        If sFormat = "Setting" Then
          recvamt = recvqty * xavrg
        Else
          If rs5["totl"] Then
            recvamt = rs5["totl"]
          Endif
        Endif
      Endif

      adjqty = 0
      adjamt = 0
      rs7 = $con.Exec("select sum(fldcompqty-fldcurrqty) as qty,SUM((fldcompqty-fldcurrqty)*fldnetcost) as totl from tbladjustment where fldstockno=&1 and fldstockid=&2 and fldtime>=&3 and fldtime<=&4 and fldcategory=&5 and fldsav=&6 and fldcomp like &7" & RepoStr, res["col"], res["fldstockid"], modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sType, True, sComp)
      If rs7.Available Then
        If rs7["qty"] Then
          adjqty = rs7["qty"]
        Endif
        If sFormat = "Setting" Then
          adjamt = adjqty * xavrg
        Else
          If rs7["totl"] Then
            adjamt = rs7["totl"]
          Endif
        Endif
      Endif

      xvax = curqty - (purqx - rtnqx + recvqx) + (xpast + salqx + bulqx + sentqx + adjqtx)
      openqty = xvax - (purqty - rtnqty + recvqty) + (xpast + salqty + bulqty + sentqty + adjqty)

      pur = pur + puramt
      rtn = rtn + rtnamt
      sale = sale + salamt
      disp = disp + dispamt
      blk = blk + bulamt
      sent = sent + sentamt
      recv = recv + recvamt
      adj = adj + adjamt

      If ShowNull = True Then
        xgo = True
      Else
        If purqty = 0 And If rtnqty = 0 And If salqty = 0 And If bulqty = 0 And If sentqty = 0 And If recvqty = 0 And If adjqty = 0 And If openqty = 0 And If xvax = 0 Then
          xgo = False
        Else
          xgo = True
        Endif
      Endif
      If xgo = True Then
        With asx
          .Add(res["col"])
          .Add(res["fldstockid"])
          .Add(res["fldbatch"])
          .Add(modReportVar.GetLocaleNumberFormat(openqty, -2))
          .Add(modReportVar.GetLocaleNumberFormat(openqty * xavrg, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(purqty, -2))
          .Add(modReportVar.GetLocaleNumberFormat(puramt, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(recvqty, -2))
          .Add(modReportVar.GetLocaleNumberFormat(recvamt, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(rtnqty, -2))
          .Add(modReportVar.GetLocaleNumberFormat(rtnamt, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(salqty, -2))
          .Add(modReportVar.GetLocaleNumberFormat(salamt, gb.Currency))
          If sFormat = "Setting" Then
            .Add(modReportVar.GetLocaleNumberFormat(dispamt, gb.Currency))
          Endif
          .Add(modReportVar.GetLocaleNumberFormat(bulqty, -2))
          .Add(modReportVar.GetLocaleNumberFormat(bulamt, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(sentqty, -2))
          .Add(modReportVar.GetLocaleNumberFormat(sentamt, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(adjqty, -2))
          .Add(modReportVar.GetLocaleNumberFormat(adjamt, gb.Currency))
          .Add(modReportVar.GetLocaleNumberFormat(xvax, -2))
          .Add(modReportVar.GetLocaleNumberFormat(xvax * xavrg, gb.Currency))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Endif
    Next

    ' If MMain.$IsGUIApp = True Then
    '   $ProgressBar1.Value = (i + 1) / sList.Count
    '   Wait
    ' Endif
    i = i + 1
  Next

  With asx
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    If sFormat = "Setting" Then
      .Add("")
    Endif
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  With asx
    .Add("")
    .Add("GRAND TOTAL")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(pur, gb.Currency))
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(recv, gb.Currency))
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(rtn, gb.Currency))
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(sale, gb.Currency))
    If sFormat = "Setting" Then
      .Add(modReportVar.GetLocaleNumberFormat(disp, gb.Currency))
    Endif
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(blk, gb.Currency))
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(sent, gb.Currency))
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(adj, gb.Currency))
    .Add("")
    .Add("")
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  $BillingReport.AddSummary("Cost Price Calculation: " & modBasic.$InvReportCost)
  Return $BillingReport.NewHTMLPath()

End
