' Gambas module file

Public Sub GetAgeInHoursToFormat(sHours As Float, txtval As WebValueBox, cmbunit As WebComboBox)

  Dim xdiff As Integer
  Dim xval As Float
  Dim xunit As String

  If sHours Then
    xdiff = sHours * 60
    If xdiff < (60 * 24) Then
      xval = xdiff / 60
      xunit = "Hours"
    Else If xdiff >= (60 * 24) And If xdiff < 60 * 24 * 30 Then
      xval = xdiff / (60 * 24)
      xunit = "Days"
    Else If xdiff >= (60 * 24 * 30) And If xdiff < (60 * 24 * 365) Then
      xval = xdiff / (60 * 24 * 30)
      xunit = "Months"
    Else If xdiff >= (60 * 24 * 365) Then
      xval = xdiff / (60 * 24 * 365)
      xunit = "Years"
    Endif
    cmbunit.Text = xunit
    txtval.Value = Round(xval, -1)
  Else
    txtval.Value = 0
    cmbunit.Text = ""
  Endif

End

Public Sub GetAgeControlFromDate(sDate As Date, txtval As WebValueBox, cmbunit As WebComboBox)

  Dim xdiff As Integer
  Dim xval As Float
  Dim xunit As String

  If sDate Then
    xdiff = DateDiff(sDate, Now(), gb.Minute)
    If xdiff < (60 * 24) Then
      xval = xdiff / 60
      xunit = "Hours"
    Else If xdiff >= (60 * 24) And If xdiff < 60 * 24 * 30 Then
      xval = xdiff / (60 * 24)
      xunit = "Days"
    Else If xdiff >= (60 * 24 * 30) And If xdiff < (60 * 24 * 365) Then
      xval = xdiff / (60 * 24 * 30)
      xunit = "Months"
    Else If xdiff >= (60 * 24 * 365) Then
      xval = xdiff / (60 * 24 * 365)
      xunit = "Years"
    Endif
    cmbunit.Text = xunit
    txtval.Value = Round(xval, -1)
  Else
    txtval.Value = 0
    cmbunit.Text = ""
  Endif

End

Public Sub DateToYearandMonth(dob As Date, txtyear As WebValueBox, txtmonth As WebValueBox, btnyear As WebButton, btnmon As WebButton)    ''

  Dim xdiff As Integer
  Dim xval As Float

  If dob Then
    xdiff = DateDiff(dob, Now(), gb.Minute)
    If xdiff < (60 * 24) Then
      xval = xdiff / 60
      txtyear.Value = 0
      txtmonth.Value = Round(xval, -1)
      btnyear.Text = "Day"
      btnmon.Text = "Hour"
    Else If xdiff >= (60 * 24) And If xdiff < 60 * 24 * 30 Then
      xval = xdiff / (60 * 24)
      txtyear.Value = Fix(xval)
      txtmonth.Value = Round(Frac(xval) * 24, -1)
      btnyear.Text = "Day"
      btnmon.Text = "Hour"
    Else If xdiff >= (60 * 24 * 30) And If xdiff < (60 * 24 * 365) Then
      xval = xdiff / (60 * 24 * 30)
      txtyear.Value = Fix(xval)
      txtmonth.Value = Round(Frac(xval) * 30, -1)
      btnyear.Text = "Mon"
      btnmon.Text = "Day"
    Else If xdiff >= (60 * 24 * 365) Then
      xval = xdiff / (60 * 24 * 365)
      txtyear.Value = Fix(xval)
      txtmonth.Value = Round(Frac(xval) * 12, -1)
      btnyear.Text = "Year"
      btnmon.Text = "Mon"
    Endif
  Endif

End
