' Gambas module file

''--------------------------------------- PATIENT FINDINGS -------------------------------------
Public Sub AddPatientFindings(sType As String, encid As String, txtname As String, codeidnew As String, Optional codeidold As String, Optional sUser As String)

  Dim res As Result
  Dim xIntVal As String

  res = modDatabase.$myConn.Create("tblpatfindings")
  res["fldtype"] = sType
  res["fldencounterval"] = encid
  res["fldcode"] = txtname
  res["fldcodeid"] = codeidold
  res["fldcodenew"] = codeidnew
  If sUser Then
    res["flduserid"] = sUser
  Else
    res["flduserid"] = modBasic.$lbluser
  Endif
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = True
  res["xyz"] = False

  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif
  res.Update()
  'don't catch error

End

''-----------------------------------INSERT/UPDATE tblpatevents--------------------------------------------------------------------
Public Function AddPatientEventsFirstTime(encid As String, txtcateg As String, txtitem As String, sDetail As String, sComment As String, Optional lstDate As Date) As Long

  Dim res As Result
  Dim xIntVal As String

  res = modDatabase.$myConn.Create("tblpatevents")
  res["fldencounterval"] = encid
  res["fldtype"] = txtcateg
  res["flditem"] = txtitem
  res["flddetail"] = sDetail
  res["fldcomment"] = sComment

  res["fldfirstuserid"] = modBasic.$lbluser
  res["fldfirsttime"] = Now()
  res["fldfirstcomp"] = modBasic.$compID
  res["fldfirstsave"] = True

  If lstDate Then
    res["fldseconduserid"] = modBasic.$lbluser
    res["fldsecondtime"] = lstDate
    res["fldsecondcomp"] = modBasic.$compID
    res["fldsecondsave"] = True
  Else
    res["fldseconduserid"] = ""
    res["fldsecondtime"] = ""
    res["fldsecondcomp"] = ""
    res["fldsecondsave"] = False
  Endif

  res["fldstatus"] = "Active"
  res["fldsave"] = False
  res["xyz"] = True

  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif
  res.Update

  Return modDatabase.$myConn.LastInsertId
  'don't catch error

End

Public Sub UpdatePatientEventSecondTime(id As Long, Optional sDate As Date)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatevents", "fldid=&1", id)
  res["fldseconduserid"] = modBasic.$lbluser
  If sDate Then
    res["fldsecondtime"] = sDate
  Else
    res["fldsecondtime"] = Now()
  Endif
  res["fldsecondcomp"] = modBasic.$compID
  res["fldsecondsave"] = True
  res["xyz"] = False
  res.Update
  'Dont catch error. Used in billing

End

''-----------------------------------INSERT/UPDATE tblpattiming--------------------------------------------------------------------
Public Function AddPatientTableFirstTime(encid As String, txtcateg As String, sDiscType As String, txtitem As String, txtval As String, sDate As Date, Optional lstDate As Date) As Long

  Dim res As Result
  Dim xIntVal As String

  res = modDatabase.$myConn.Create("tblpattiming")
  res["fldencounterval"] = encid
  res["fldtype"] = txtcateg
  res["flditem"] = txtitem
  res["fldbillitem"] = ""
  res["flddisctype"] = sDiscType

  res["fldfirstreport"] = txtval
  res["fldfirstuserid"] = modBasic.$lbluser
  res["fldfirsttime"] = sDate
  res["fldfirstcomp"] = modBasic.$compID
  res["fldfirstsave"] = True

  res["fldsecondreport"] = ""
  If lstDate Then
    res["fldseconduserid"] = modBasic.$lbluser
    res["fldsecondtime"] = lstDate
    res["fldsecondcomp"] = modBasic.$compID
    res["fldsecondsave"] = True
  Else
    res["fldseconduserid"] = ""
    res["fldsecondtime"] = ""
    res["fldsecondcomp"] = ""
    res["fldsecondsave"] = False
  Endif

  res["fldcomment"] = ""
  res["fldsave"] = False
  res["xyz"] = True

  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif
  res.Update

  Return modDatabase.$myConn.LastInsertId
  'don't catch error

End

Public Sub UpdatePatientTableSecondTime(id As Long, txtval As String, Optional sItem As String, Optional sDate As Date)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpattiming", "fldid=&1", id)
  If sItem Then
    res["fldbillitem"] = sItem
  Endif
  res["fldsecondreport"] = txtval
  res["fldseconduserid"] = modBasic.$lbluser
  If sDate Then
    res["fldsecondtime"] = sDate
  Else
    res["fldsecondtime"] = Now()
  Endif
  res["fldsecondcomp"] = modBasic.$compID
  res["fldsecondsave"] = True
  res["xyz"] = False
  res.Update
  'Dont catch error. Used in billing

End

Public Sub UpdatePatientTableEndTime(encid As String, txtcateg As String, txtitem As String, txtval As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpattiming", "fldencounterval=&1 and fldtype=&2 and flditem=&3 and fldfirstsave=&4", encid, txtcateg, txtitem, True)
  res["fldsecondreport"] = txtval
  res["fldseconduserid"] = modBasic.$lbluser
  res["fldsecondtime"] = Now()
  res["fldsecondcomp"] = modBasic.$compID
  res["fldsecondsave"] = True
  res["xyz"] = False
  res.Update
  'dont catch error. used with billing

End

''----------------------------- for exam general ----------------------------------------
Public Sub AddExamGeneralQuantiData(encid As String, strInput As String, strItem As String, strReport As Float, strDetail As String, Optional sUnique As Boolean)

  Dim res As Result
  Dim rsx As Result
  Dim suniq As Boolean
  Dim xIntVal As String

  If sUnique Then
    If sUnique = True Then
      If MMain.$WebEntry = True Then
        rsx = modDatabase.$myConn.Exec("select fldid from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and fldtype=&3 and flditem=&4", encid, strInput, "Quantitative", strItem)
      Else
        rsx = modDatabase.$myConn.Exec("select fldid from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and fldtype=&3 and flditem=&4", encid, strInput, "Quantitative", strItem)
      Endif
      If rsx.Available Then
        suniq = True
      Else
        suniq = False
      Endif
    Else
      suniq = False
    Endif
  Else
    suniq = False
  Endif

  If suniq = True Then
    res = modDatabase.$myConn.Edit("tblexamgeneral", "fldencounterval=&1 and fldinput=&2 and fldtype=&3 and flditem=&4", encid, strInput, "Quantitative", strItem)
    If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
      res["fldreportquali"] = CStr(strReport)
      res["fldreportquanti"] = strReport
      res["flddetail"] = strDetail
      res["flduserid"] = modBasic.$lbluser
      res["fldcomp"] = modBasic.$compID
      res["fldsave"] = True
      res["flduptime"] = Now()
      res["xyz"] = False
      res.Update()
    Else
      Message.Warning("Authorization with " & res["flduserid"], ("OK"))
    Endif
  Else If suniq = False Then
    res = modDatabase.$myConn.Create("tblexamgeneral")
    res["fldencounterval"] = encid
    res["fldinput"] = strInput
    res["fldtype"] = "Quantitative"
    res["flditem"] = strItem
    res["fldreportquali"] = CStr(strReport)
    res["fldreportquanti"] = strReport
    res["flddetail"] = strDetail
    res["flduserid"] = modBasic.$lbluser
    res["fldtime"] = Now()
    res["fldcomp"] = modBasic.$compID
    res["fldsave"] = True
    res["flduptime"] = ""
    res["xyz"] = False

    If MMain.$WebEntry = True Then
      xIntVal = modString.GetDateString(Now())
      res["fldid"] = CLong(xIntVal)
      res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
      res["fldrepodate"] = Now()
      res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
      res["fldhospcode"] = modBasic.$HospCode
    Endif

    res.Update()
    'don't catch error
  Endif

End

Public Sub AddExamGeneralQualiData(encid As String, strInput As String, strItem As String, strReport As String, strDetail As String, Optional sUnique As Boolean)

  Dim res As Result
  Dim rsx As Result
  Dim suniq As Boolean
  Dim xIntVal As String

  If sUnique Then
    If sUnique = True Then
      If MMain.$WebEntry = True Then
        rsx = modDatabase.$myConn.Exec("select fldrepoid from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and fldtype=&3 and flditem=&4", encid, strInput, "Qualitative", strItem)
      Else
        rsx = modDatabase.$myConn.Exec("select fldid from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and fldtype=&3 and flditem=&4", encid, strInput, "Qualitative", strItem)
      Endif
      If rsx.Available Then
        suniq = True
      Else
        suniq = False
      Endif
    Else
      suniq = False
    Endif
  Else
    suniq = False
  Endif

  If suniq = True Then
    res = modDatabase.$myConn.Edit("tblexamgeneral", "fldencounterval=&1 and fldinput=&2 and fldtype=&3 and flditem=&4", encid, strInput, "Qualitative", strItem)
    If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
      res["fldreportquali"] = strReport
      res["fldreportquanti"] = 0
      res["flddetail"] = strDetail
      res["flduserid"] = modBasic.$lbluser
      res["fldcomp"] = modBasic.$compID
      res["fldsave"] = True
      res["flduptime"] = Now()
      res["xyz"] = False
      res.Update()
    Else
      Message.Warning("Authorization with " & res["flduserid"], ("OK"))
    Endif
  Else If suniq = False Then
    res = modDatabase.$myConn.Create("tblexamgeneral")
    res["fldencounterval"] = encid
    res["fldinput"] = strInput
    res["fldtype"] = "Qualitative"
    res["flditem"] = strItem
    res["fldreportquali"] = strReport
    res["fldreportquanti"] = 0
    res["flddetail"] = strDetail
    res["flduserid"] = modBasic.$lbluser
    res["fldtime"] = Now()
    res["fldcomp"] = modBasic.$compID
    res["fldsave"] = True
    res["flduptime"] = ""
    res["xyz"] = False

    If MMain.$WebEntry = True Then
      xIntVal = modString.GetDateString(Now())
      res["fldid"] = CLong(xIntVal)
      res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
      res["fldrepodate"] = Now()
      res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
      res["fldhospcode"] = modBasic.$HospCode
    Endif

    res.Update()
    'don't catch error
  Endif

End

Public Sub AddExamGeneralQualiQuantiData(encid As String, strInput As String, strItem As String, strReport As String, strValue As Float, strDetail As String)

  Dim res As Result
  Dim xIntVal As String

  res = modDatabase.$myConn.Create("tblexamgeneral")
  res["fldencounterval"] = encid
  res["fldinput"] = strInput
  res["fldtype"] = "Qualitative"
  res["flditem"] = strItem
  res["fldreportquali"] = strReport
  res["fldreportquanti"] = strValue
  res["flddetail"] = strDetail
  res["flduserid"] = modBasic.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = True
  res["flduptime"] = ""
  res["xyz"] = False

  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif
  res.Update()
  'don't catch error

End

''Update
Public Sub UpdateExamGeneralQualiData(id As Long, strItem As String, strReport As String, strDetail As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblexamgeneral", "fldid=&1", id)
  If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
    res["flditem"] = strItem
    res["fldreportquali"] = strReport
    res["flddetail"] = strDetail
    res["flduserid"] = modBasic.$lbluser
    res["flduptime"] = Now()
    res["fldcomp"] = modBasic.$compID
    res["xyz"] = False
    res.Update()
  Else
    Message.Warning("Authorization with " & res["flduserid"], ("OK"))
  Endif
  'don't catch error

End

Public Sub UpdateExamGeneralQuantiData(id As Long, strItem As String, strReport As Float, strDetail As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblexamgeneral", "fldid=&1", id)
  If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
    res["flditem"] = strItem
    res["fldreportquali"] = CStr(strReport)
    res["fldreportquanti"] = strReport
    res["flddetail"] = strDetail
    res["flduserid"] = modBasic.$lbluser
    res["flduptime"] = Now()
    res["fldcomp"] = modBasic.$compID
    res["xyz"] = False
    res.Update()
  Else
    Message.Warning("Authorization with " & res["flduserid"], ("OK"))
  Endif
  'don't catch error

End

''-------------------------------- INSERT/UPDATE  tblpatgeneral----------------------------------------------------------------
Public Sub AddProcedureData(encid As String, sBillID As Long, strInput As String, strItem As String, strReport As String, sMode As String, dt As Date, sStatus As String, sSummary As String)

  Dim res As Result
  Dim xIntVal As String

  res = modDatabase.$myConn.Create("tblpatgeneral")
  res["fldencounterval"] = encid
  res["fldinput"] = strInput
  res["fldgroupid"] = sBillID
  res["flditem"] = strItem
  res["fldreportquali"] = strReport
  res["flddetail"] = sSummary
  res["fldnewdate"] = dt
  res["fldbillingmode"] = sMode
  res["fldorduserid"] = modBasic.$lbluser
  res["flduserid"] = ""
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = False
  res["fldstatus"] = sStatus
  res["flduptime"] = ""
  res["xyz"] = False

  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif
  res.Update()
  'don't catch error

End

''---------------------------------- Clinical shares -----------------------------
Public Sub AddClinicalSharingUser(sCategory As String, sBillID As Long, encid As String, sUserType As String, sUserCode As String, sReport As String, sStatus As String, sMixPer As Float)

  Dim res As Result
  Dim xIntVal As String

  res = modDatabase.$myConn.Create("tblpatgenshare")
  res["fldencounterval"] = encid
  res["flditemid"] = sBillID
  res["fldcategory"] = sCategory
  res["fldusertype"] = sUserType
  res["fldvalue"] = sUserCode
  res["fldreport"] = sReport
  res["fldmixper"] = sMixPer
  res["fldactive"] = sStatus

  res["fldshareamt"] = 0
  res["fldtdsper"] = 0
  res["fldsharenet"] = 0
  res["fldchange"] = 0
  res["fldchreason"] = ""
  res["flduserid"] = modBasic.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = True
  res["flduptime"] = ""
  res["xyz"] = False
  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif
  res.Update
  'don't catch error

End

''------------------------------------- sub General --------------------------------------------------------
Public Sub AddSubGeneralQualiData(sID As Long, encid As String, sCategory As String, sValue As String, sDetail As String)

  Dim res As Result
  Dim xIntVal As String

  res = modDatabase.$myConn.Create("tblpatsubgeneral")
  res["flditemid"] = sID
  res["fldencounterval"] = encid
  res["fldchapter"] = sCategory
  res["fldreportquali"] = sValue
  res["fldreportquanti"] = 0
  res["fldreport"] = sDetail
  res["flduserid"] = modBasic.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = True
  res["flduptime"] = ""
  res["xyz"] = False
  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif
  res.Update
  'don't catch error

End

Public Sub AddSubGeneralQuantiData(sID As Long, encid As String, sCategory As String, sValue As Float, sDetail As String)

  Dim res As Result
  Dim xIntVal As String

  res = modDatabase.$myConn.Create("tblpatsubgeneral")
  res["flditemid"] = sID
  res["fldencounterval"] = encid
  res["fldchapter"] = sCategory
  res["fldreportquali"] = ""
  res["fldreportquanti"] = sValue
  res["fldreport"] = sDetail
  res["flduserid"] = modBasic.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = True
  res["flduptime"] = ""
  res["xyz"] = False
  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif
  res.Update
  'don't catch error

End

Public Sub EditSUbGeneralDetail(id As Long, sDetail As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatsubgeneral", "fldid=&1", id)
  If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
    res["fldreport"] = sDetail
    res["flduptime"] = Now()
    res["flduserid"] = modBasic.$lbluser
    res["xyz"] = False
    res.Update
  Else
    Message.Warning("Authorization with " & res["flduserid"], ("OK"))
  Endif
  'don't catch error

End

''---------------------------------- Monitoring ------------------------------------
Public Sub AddMonitoringData(encid As String, sCategory As String, sItem As String, sEvery As Integer, sUnit As String, sType As String)

  Dim res As Result
  Dim xIntVal As String

  res = modDatabase.$myConn.Create("tblmonitor")
  res["fldencounterval"] = encid
  res["fldcategory"] = sCategory
  res["flditem"] = sItem
  res["fldevery"] = sEvery
  res["fldunit"] = sUnit
  res["fldtype"] = sType
  res["fldstatus"] = "Continue"
  res["flduserid"] = modBasic.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = True
  res["xyz"] = False
  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif
  res.Update

End

''---------------- Blood ----------------------
Public Sub PatMedicalItemRequest(sCategory As String, encid As String, sItem As String, sPatInfo As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpatmeditem")
  res["fldencounterval"] = encid
  res["fldcategory"] = sCategory
  res["fldcode"] = ""
  res["flditem"] = sItem
  res["fldpatinfo"] = sPatInfo
  res["fldcomment"] = ""

  res["flduserid_order"] = modBasic.$lbluser
  res["fldtime_order"] = Now()
  res["fldcomp_order"] = modBasic.$compID
  res["fldsave_order"] = True
  res["fldorder"] = "Requested"

  res["flduserid"] = ""
  res["fldtime"] = ""
  res["fldcomp"] = ""
  res["fldsave"] = ""
  res["fldstatus"] = ""

  res["fldbillno"] = ""
  res["flduptime"] = ""
  res["xyz"] = True
  res.Update

End

Public Sub PatMedicalItemDirectUse(sCategory As String, encid As String, sItem As String, sPatInfo As String, sItemCode As String, sComment As String)                         ''

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpatmeditem")
  res["fldencounterval"] = encid
  res["fldcategory"] = sCategory
  res["fldcode"] = sItemCode
  res["flditem"] = sItem
  res["fldpatinfo"] = sPatInfo
  res["fldcomment"] = sComment

  res["flduserid_order"] = ""
  res["fldtime_order"] = ""
  res["fldcomp_order"] = ""
  res["fldsave_order"] = ""
  res["fldorder"] = "Done"

  res["flduserid"] = modBasic.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = True
  res["fldstatus"] = ""

  res["fldbillno"] = ""
  res["flduptime"] = ""
  res["xyz"] = False
  res.Update

End

' Public Sub GetSyndromList() As String[]
'
'   Dim sName As String[]
'   Dim xx As String[]
'   Dim res As Result
'
'   xx = New String[]
'   res = modDatabase.$medConn.Exec("select fldsyndrome,fldsymcode from tblsyndromes")
'   If res.Available Then
'     For Each res
'       If res!fldsymcode Then
'         xx.Add(res!fldsyndrome & "@" & res!fldsymcode)
'       Endif
'     Next
'   Endif
'   sName = GridDualView("Syndrome List", xx)
'   Return sName
'
' End
