' Gambas module file

Public Function GetPatPassCheck(sCon As Connection, patno As String) As Boolean

  Dim res As Result
  Dim xx As Boolean
  Dim xval As String
  Dim xpass As String

  res = sCon.Exec("select fldpassword from tblpatientinfo where fldpatientval=&1", patno)
  If res.Available Then
    If res!fldpassword Then
      xval = InputPassword(("Input Patient Password"), "Password", "")
      If xval Then
        xpass = modPassword.EncryptSimple(xval)
        If res!fldpassword = xpass Then
          xx = True
        Else
          xx = False
        Endif
      Else
        xx = False
      Endif
    Else
      xx = True
    Endif
  Else
    xx = False
  Endif
  Return xx

End

Public Function AllowEncIDHistory(encid As String, sCon As Connection) As Boolean

  Dim xval As Boolean
  Dim xx As String

  xx = modPatient.CurrentAdmissionStatus(encid)
  If xx = "Discharged" Or If xx = "LAMA" Or If xx = "Death" Or If xx = "Refer" Or If xx = "Absconder" Then
    If modPatientSub.GetPatPassCheck(sCon, modPatient.GetPatientNoByEnc(encid)) = True Then
      xval = True
    Else
      xval = False
    Endif
  Else
    xval = True
  Endif
  Return xval

End

Public Sub RemovePatientCache(patno As String)

  Dim res As Result
  Dim encid As String

  If modBasic.$AppCachePatientDemographics = "Yes" Then
    res = modDatabase.$myConn.Exec("select fldencounterval from tblencounter where fldpatientval=&1", patno)
    If res.Available Then
      For Each res
        encid = res["fldencounterval"]
        modPatient.$PatProfileData.Remove(encid)

        modPatient.$PatDOAData.Remove(encid)
        modPatient.$PatDODData.Remove(encid)
        modPatient.$PatDOFollData.Remove(encid)
      Next
    Endif
  Endif

End

'NOTE: -------------------BLANK REGISTRATION -------------------------------------
Public Sub RegistBlankPatient()

  Dim res As Result
  Dim dt As Date
  Dim yr As Integer

  yr = 0 - 25
  dt = DateAdd(Now(), gb.Year, yr)
  res = modDatabase.$myConn.Create("tblpatientinfo")
  res["fldpatientval"] = "1"
  res["fldptnamefir"] = "General"
  res["fldptnamelast"] = "Patient"
  res["fldethniccode"] = ""
  res["fldptaddvill"] = "Hospital"
  res["fldptaddward"] = ""
  res["fldptadddist"] = "Hospital"
  res["fldptsex"] = "Male"
  res["fldptcontact"] = ""
  res["fldptguardian"] = ""
  res["fldrelation"] = ""
  res["fldptbirday"] = dt
  res["fldptadmindate"] = Now()
  res["fldemail"] = ""
  res["fldptcode"] = ""
  res["flddiscount"] = ""
  res["fldadmitfile"] = ""
  res["fldcomment"] = ""
  res["fldencrypt"] = False
  res["fldpassword"] = ""

  res["flduserid"] = modBasic.$lbluser
  res["fldtime"] = Now()
  res["fldupuser"] = ""
  res["flduptime"] = ""
  res["xyz"] = True
  res.Update()

Catch

End

Public Sub RegistBlankEncounter()

  Dim res As Result
  Dim xdisctype As String
  Dim xbillmode As String

  If modBasic.$RegistDefaultDisc Then
    xdisctype = modBasic.$RegistDefaultDisc
  Else
    xdisctype = "General"
  Endif
  If modBasic.$RegistDefaultMode Then
    xbillmode = modBasic.$RegistDefaultMode
  Else
    xbillmode = "General"
  Endif

  If modBasic.$RegistDefaultDisc And If modBasic.$RegistDefaultMode Then
    res = modDatabase.$myConn.Create("tblencounter")
    res["fldencounterval"] = "1"
    res["fldpatientval"] = "1"
    res["fldadmitlocat"] = modGeneral.GetCompNameFromCompID(modBasic.$compID)
    res["flddisctype"] = xdisctype
    res["fldbillingmode"] = xbillmode
    res["fldadmission"] = "Recorded"
    res["fldregdate"] = Now()
    res["fldcomp"] = modBasic.$compID
    res["fldvisit"] = "NEW"
    res["fldfollow"] = "New"

    res["fldcurrlocat"] = ""
    res["flddoa"] = ""
    res["flddod"] = ""
    res["fldheight"] = ""
    res["flduserid"] = ""
    res["fldcashdeposit"] = 0
    res["fldcashcredit"] = 0
    res["fldcharity"] = 0
    res["fldvalidity"] = ""
    res["fldfollowdate"] = ""
    res["fldreferto"] = ""

    res["fldregistid"] = ""
    res["fldadmitid"] = ""
    res["xyz"] = True
    res.Update()
  Else
    Message.Warning("Default Scheme and Rate Plan not set", "OK")
  Endif

Catch
  Message.Warning(("Encounter No: 1 already exist"), ("OK"))

End

''--------------------- Patient Date --------------------------
Public Sub EnterPatientImpDate(encid As String, sType As String, sComment As String, Optional sDate As Date)

  Dim res As Result
  Dim xIntVal As String

  res = modDatabase.$myConn.Create("tblpatientdate")
  res["fldencounterval"] = encid
  res["fldhead"] = sType
  res["fldcomment"] = sComment
  res["flduserid"] = modBasic.$lbluser
  If sDate Then
    res["fldtime"] = sDate
  Else
    res["fldtime"] = Now()
  Endif
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = True
  res["flduptime"] = ""
  res["xyz"] = False

  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif

  res.Update
  'don't catch error

End

Public Sub AddEncounterSpecData(encid As String, consultname As String)

  Dim rs As Result

  rs = modDatabase.$myConn.Edit("tblencounter", "fldencounterval=&1", encid)
  If Not rs["fldcurrlocat"] Then
    rs["fldcurrlocat"] = consultname
  Endif
  If rs["fldadmission"] <> "Admitted" Then
    rs["fldadmission"] = "Registered"
  Endif
  rs["xyz"] = False
  rs.Update
  'don't catch error

End

Public Sub AddOPVisitData(encid As String, consultname As String, consulttime As Date, sBillMode As String, sComment As String, Optional sNotice As String)

  Dim res As Result
  Dim xnotice As String
  Dim xIntVal As String

  If sNotice Then
    xnotice = sNotice
  Else
    xnotice = ""
  Endif

  res = modDatabase.$myConn.Create("tblopvisit")
  res["fldencounterval"] = encid
  res["fldconsultname"] = consultname
  res["fldconsulttime"] = consulttime
  res["fldcomment"] = sComment
  res["fldstatus"] = "Planned"
  res["fldbillingmode"] = sBillMode
  res["fldoutcome"] = ""
  res["fldnotice"] = xnotice
  res["flduserid"] = modBasic.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = False
  ' res["fldflag"] = null   ''keep null
  ' res["fldflagtime"] = ""
  If modGeneral.GetDepartCaption(consultname) = "Emergency" Then
    res["fldemerid"] = modBillLock.GetHMISRegVal("Emergency")
  Endif
  res["xyz"] = False
  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif
  res.Update

  modPatientSub.AddEncounterSpecData(encid, consultname)
  modPatientSub.EnterPatientImpDate(encid, "OP Visit", consultname)

End

Public Sub AddConsultData(encid As String, consultname As String, consulttime As Date, sBillMode As String, sComment As String, Optional sUser As String)

  Dim res As Result
  Dim xx As String
  Dim xIntVal As String

  If sUser Then
    xx = sUser
  Else
    xx = ""
  Endif

  res = modDatabase.$myConn.Create("tblconsult")
  res["fldencounterval"] = encid
  res["fldconsultname"] = consultname
  res["fldconsulttime"] = consulttime
  res["fldcomment"] = sComment
  res["fldstatus"] = "Planned"
  res["flduserid"] = xx
  res["fldbillingmode"] = sBillMode
  res["fldoutcome"] = ""
  res["fldnotice"] = ""
  res["fldorduserid"] = modBasic.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = False
  ' res["fldflag"] = null   ''keep null
  ' res["fldflagtime"] = ""
  res["fldconsultid"] = modPatient.GetPatientHMISConsult(encid)
  res["xyz"] = False
  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif
  res.Update

  modPatientSub.AddEncounterSpecData(encid, consultname)
  modPatientSub.EnterPatientImpDate(encid, "Consultation", consultname)

End

Public Sub UpdateConsultConsultant(id As Long, xuser As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblconsult", "fldid=&1", id)
  modPatientSub.EnterPatientImpDate(res["fldencounterval"], "Consultant", modGeneral.GetUserFullName(xuser))
  res["flduserid"] = xuser
  res["xyz"] = False
  res.Update

End

Public Sub UpdateConsultData(id As Long, status As String, comment As String, sOutcome As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblconsult", "fldid=&1", id)
  res["fldnotice"] = comment
  res["fldstatus"] = status
  res["fldoutcome"] = sOutcome
  res["fldorduserid"] = modBasic.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = True
  res["xyz"] = False
  res.Update
  'don't catch error

End

Public Sub UpdateOPVisitData(id As Long, status As String, comment As String, sOutcome As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblopvisit", "fldid=&1", id)
  res["fldnotice"] = comment
  res["fldstatus"] = status
  res["fldoutcome"] = sOutcome
  res["flduserid"] = modBasic.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = True
  res["xyz"] = False
  res.Update
  'don't catch error

End

Public Sub UpdatePatFile(patno As String, txtFile As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatientinfo", "fldpatientval=&1", patno)
  res["fldadmitfile"] = txtFile
  ' res["fldupuser"] = modBasic.$lbluser
  ' res["flduptime"] = Now()
  res["xyz"] = False
  res.Update

End

Public Sub UpdatePatComment(encid As String, sComm As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatientinfo", "fldpatientval=&1", modPatient.GetPatientNoByEnc(encid))
  res["fldcomment"] = sComm
  res["fldupuser"] = modBasic.$lbluser
  res["flduptime"] = Now()
  res["xyz"] = False
  res.Update

End

Public Sub UpdateAdmissionWard(encid As String, sWard As String, Optional sBedNo As String)

  Dim res As Result

  If sWard Then
    res = modDatabase.$myConn.Edit("tblencounter", "fldencounterval=&1 and fldadmitward IS NULL", encid)
    If res.Available Then
      res["fldadmitward"] = sWard
      If sBedNo Then
        res["fldadmitbed"] = sBedNo
      Endif
      res["xyz"] = False
      res.Update()
    Endif
  Endif

End

Public Sub UpdatePatLocation(encid As String, bedno As String, Optional sDate As Date)

  Dim res As Result
  Dim res1 As Result
  Dim res2 As Result

  res = modDatabase.$myConn.Edit("tblencounter", "fldencounterval=&1", encid)
  res["fldcurrlocat"] = bedno
  res["xyz"] = False
  res.Update()

  res2 = modDatabase.$myConn.Edit("tbldepartmentbed", "fldencounterval=&1", encid)
  If res2.Available Then
    res2["fldencounterval"] = ""
    res2["fldaddservice"] = ""
    res2["fldflag"] = False
    res2.Update
  Endif

  res1 = modDatabase.$myConn.Edit("tbldepartmentbed", "fldbed=&1", bedno)
  If res1.Available Then
    res1["fldencounterval"] = encid
    res1["fldfreedate"] = ""
    res1.Update
  Endif

  If bedno Then
    If sDate Then
      modPatientSub.EnterPatientImpDate(encid, "Location Update", bedno, sDate)
    Else
      modPatientSub.EnterPatientImpDate(encid, "Location Update", bedno)
    Endif
  Endif

End

Public Sub UpdatePatLocationRelease(encid As String, Optional sDate As Date)

  Dim res2 As Result

  res2 = modDatabase.$myConn.Edit("tbldepartmentbed", "fldencounterval=&1", encid)
  If res2.Available Then
    res2["fldencounterval"] = ""
    res2["fldaddservice"] = ""
    res2["fldflag"] = False
    res2["fldfreedate"] = Now()
    res2.Update
  Endif

  If sDate Then
    modPatientSub.EnterPatientImpDate(encid, "Bed Release", "", sDate)
  Else
    modPatientSub.EnterPatientImpDate(encid, "Bed Release", "")
  Endif

End

Public Sub SetPatientBedService(sBed As String, sService As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tbldepartmentbed", "fldbed=&1", sBed)
  If res.Available Then
    res["fldaddservice"] = sService
    res.Update
  Endif

End

Public Sub MarkConsultVisitFlag(sIndex As Long, sTable As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit(sTable, "fldid=&1", sIndex)
  If res.Available Then
    res["fldflag"] = True
    If Not res["fldflagtime"] Then
      res["fldflagtime"] = Now()
    Endif
    res.Update
  Endif

End

Public Sub UnMarkConsultVisitFlag(sIndex As Long, sTable As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit(sTable, "fldid=&1", sIndex)
  If res.Available Then
    res["fldflag"] = False
    If Not res["fldflagtime"] Then
      res["fldflagtime"] = Now()
    Endif
    res.Update
  Endif

End

''update age in tblpatientinfo
Public Sub UpdatePatDOB(encid As String, dob As Date)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatientinfo", "fldpatientval=&1", modPatient.GetPatientNoByEnc(encid))
  res["fldptbirday"] = dob
  res["xyz"] = False
  res.Update()

End

' Public Sub UpdateDateOfBirth(encid As String, age As Float, unit As String)
'
'   Dim xsec As Integer
'   Dim dt As Date
'
'   If unit = "Hours" Then
'     xsec = age * 60
'   Else If unit = "Days" Then
'     xsec = age * 60 * 24
'   Else If unit = "Months" Then
'     xsec = age * 60 * 24 * 30
'   Else If unit = "Years" Then
'     xsec = age * 60 * 24 * 365
'   Endif
'   xsec = 0 - xsec
'   dt = DateAdd(Now(), gb.Minute, CInt(xsec))
'   modPatientSub.UpdatePatDOB(encid, dt)
'
' End

Public Function GetPatientAdmission(encid As String) As String

  Dim res As Result
  Dim xval As String

  res = modDatabase.$myConn.Edit("tblencounter", "fldencounterval=&1", encid)
  res["fldadmission"] = "Admitted"
  If Not res["flddoa"] Then
    res["flddoa"] = Now()
  Endif
  res["flddod"] = ""
  If Not res["fldadmitid"] Then
    xval = modPatient.GetPatientHMISAdmission(res["fldpatientval"])
    res["fldadmitid"] = xval
  Endif
  res["xyz"] = False
  res.Update
  modPatientSub.EnterPatientImpDate(encid, "Admitted", "")

  Return xval

End

Public Sub UpdateCurrentStatus(encid As String, status As String, sComment As Variant)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblencounter", "fldencounterval=&1", encid)
  res["fldadmission"] = status
  Select status
    Case "Discharged", "LAMA", "Death", "Absconder"
      res["flddod"] = Now()
    Case "Refer"
      res["flddod"] = Now()
      res["fldreferto"] = sComment
    Case "Refer(OPD)"
      res["fldreferto"] = sComment
    Case "Follow Up"
      res["fldfollowdate"] = sComment
  End Select
  res["xyz"] = False
  res.Update

  If modBasic.$ClinBedReleaseEvent = "Clearance" Then
  Else
    Select status
      Case "Discharged", "LAMA", "Death", "Refer", "Absconder"
        GetPatBedRelease(encid)
    End Select
  Endif
  modPatientSub.EnterPatientImpDate(encid, status, sComment)

End

Public Sub GetPatBedRelease(encid As String)

  Dim res1 As Result

  res1 = modDatabase.$myConn.Edit("tbldepartmentbed", "fldencounterval=&1", encid)
  If res1.Available Then
    For Each res1
      res1["fldencounterval"] = ""
      res1["fldaddservice"] = ""
      res1["fldflag"] = False
      res1["fldfreedate"] = Now()
      res1.Update
    Next
  Endif

End

Public Sub RollbackDischarge(encid As String)

  Dim res As Result

  modDatabase.$myConn.Begin
  res = modDatabase.$myConn.Edit("tblencounter", "fldencounterval=&1", encid)
  res["fldadmission"] = "Admitted"
  res["flddod"] = ""
  res["fldreferto"] = ""
  res["xyz"] = False
  res.Update

  modPatientSub.EnterPatientImpDate(encid, "Admitted", "Discharge Rollback")
  modDatabase.$myConn.Commit

Catch
  modDatabase.$myConn.Rollback
  modHelpVariable.CreateErrorReport()

End

Public Sub UpdateAttendingConsultant(encid As String, sUserID As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblencounter", "fldencounterval=&1", encid)
  res["flduserid"] = sUserID
  res["xyz"] = False
  res.Update
  modPatientSub.EnterPatientImpDate(encid, "Consultant", modGeneral.GetUserFullName(sUserID))

End

''-------------------------- Encounter Lock ---------------------------------------
' Private Function LockEncounterTable(encid As String, sType As String) As Boolean
'
'   Dim res As Result
'   Dim rs As Result
'   Dim xx As Boolean
'
'   rs = modDatabase.$myConn.Exec("select fldid from tblenclock where fldencounterval=&1 and fldlocktype=&2 and fldhostmac<>&3", encid, sType, modHelpVariable.$MACAddress)
'   If rs.Available = False Then
'     res = modDatabase.$myConn.Create("tblenclock")
'     res["fldencounterval"] = encid
'     res["fldlocktype"] = sType
'     res["fldhostmac"] = modHelpVariable.$MACAddress
'     res.Update
'     xx = True
'   Else
'     xx = False
'   Endif
'
'   Return xx
'
' End

' Public Function LockEncounterDesk(encid As String) As Boolean
'
'   Dim xx As Boolean
'
'   If modBasic.$PatientEncLock = "Yes" Then
'     xx = LockEncounterTable(encid, modHelpVariable.$LogInCategory)
'   Else
'     xx = True
'   Endif
'   Return xx
'   ''dont catch error. Allow roll back
'
' End

Public Sub ReleaseLockEncounter(encid As String, sType As String)

  modDatabase.$myConn.Delete("tblenclock", "fldencounterval=&1 and fldlocktype=&2 and fldhostmac=&3", encid, sType, Session.Id)

End

Public Sub CLearAllEncounterLocks(sType As String)

  modDatabase.$myConn.Delete("tblenclock", "fldlocktype=&1", sType)
  Message.Info(("Locks Cleared"), ("OK"))

End

''--------------------- social id ---------------------
Public Sub UpdateSocialUnitIDTable(staffid As String, patno As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblsociallist", "fldptcode=&1 and fldpatientval IS &2", staffid, Null)
  If res.Available Then
    res["fldpatientval"] = patno
    res["xyz"] = False
    res.Update
  Endif
  'don't catch error

End

''-------------------- staffid ---------------------------
Public Sub UpdateStaffIDTable(staffid As String, patno As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblstafflist", "fldptcode=&1 and fldpatientval IS &2", staffid, Null)
  If res.Available Then
    res["fldpatientval"] = patno
    res["xyz"] = False
    res.Update
  Endif
  'don't catch error

End

''-------------------- booking ---------------------------
Public Sub UpdateBookingTable(bookid As String, patno As String, encid As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatientbook", "fldbookingval=&1", bookid)
  res["fldpatientval"] = patno
  res["fldstate"] = "Done"
  res["fldencounterval"] = encid
  res["xyz"] = False
  res.Update
  'don't catch error

End

Public Sub UpdateRemoteUserNo(xemail As String, sPatNo As String)

  Dim res As Result

  If xemail Then
    res = modDatabase.$myConn.Edit("tblremoteusers", "fldusrcode=&1 and fldpatientval IS NULL", xemail)
    If res.Available Then
      res["fldpatientval"] = sPatNo
      res["xyz"] = False
      res.Update
    Endif
  Endif

End

''----------------------- Reports -------------------------
Public Sub PrintRegistExtraReport(encid As String)

  Dim hCls As CReportCustom
  Dim res As Result
  Dim xregist As String
  Dim xlateregist As String

  res = modDatabase.$myConn.Exec("select fldvisit from tblencounter where fldencounterval=&1", encid)
  xregist = modSettings.ShowSettingFromFIle("RegistrationForm/Template")
  xlateregist = modSettings.ShowSettingFromFIle("RegistrationLaterForm/Template")
  If res!fldvisit Then
    If res!fldvisit = "NEW" Then
      If xregist Then
        hCls = New CReportCustom(encid, xregist, "ReportSize", MMain.$defUnit)
        hCls.Preview()
      Endif
    Else If res!fldvisit = "OLD" Then
      If xregist Then
        hCls = New CReportCustom(encid, xregist, "ReportSize", MMain.$defUnit)
        hCls.Preview()
      Endif
    Endif

  Else
    If xregist Then
      hCls = New CReportCustom(encid, xregist, "ReportSize", MMain.$defUnit)
      hCls.Preview()
    Endif
  Endif

End

Public Sub PrintExtraReport(encid As String, sType As String)

  Dim hCls As CReportCustom
  Dim xval As String

  xval = modSettings.ShowSettingFromFIle("ExtraPrint/" & sType)
  If xval Then
    hCls = New CReportCustom(encid, xval, modSettings.ShowSettingFromFIle("ExtraPrintMode/" & sType), MMain.$defUnit)
    hCls.Preview()
  Endif

End

Public Sub PopUpPatientForm(encid As String, sTag As String)

  Dim hForm As FmIndexForm
  Dim patno As String
  Dim xset As String

  xset = modGlobalSetting.ShowSettingFromDB("PatientFormPopUp/" & sTag)
  If xset = "Yes" Then
    patno = modPatient.GetPatientNoByEnc(encid)
    If modPatient.PatientParameterPresent(patno) = False Then
      hForm = New FmIndexForm(encid, False, True)
      hForm.Show()
    Endif
  Endif

End

''------------------------------------ Assign device -------------------------------------------
Public Sub SetPatientDevice(encid As String, sType As String, sDevice As String)

  Dim rs As Result
  Dim res As Result

  modBasic.DebugString("Setting webcam device for patient")
  rs = modDatabase.$myConn.Exec("select flddevicepath from tblpatdevice where flddevicetype=&1 and fldencounterval=&2", sType, encid)
  If rs.Available = False Then
    res = modDatabase.$myConn.Create("tblpatdevice")
    res["fldencounterval"] = encid
    res["flddevicetype"] = sType
    res["flddevicepath"] = sDevice
    res["fldhostmac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhostuser"] = CGI["HTTP_USER_AGENT"]
    res["fldhostip"] = modHelpVariable.$MACAddress
    res["fldhostname"] = CGI["SERVER_SOFTWARE"] & ":" & Application.Name & "-" & Application.Version
    res["fldcomp"] = modBasic.$compID
    res.Update

  Else
    res = modDatabase.$myConn.Edit("tblpatdevice", "flddevicetype=&1 and fldencounterval=&2", sType, encid)
    res["flddevicepath"] = sDevice
    res["fldhostmac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhostuser"] = CGI["HTTP_USER_AGENT"]
    res["fldhostip"] = modHelpVariable.$MACAddress
    res["fldhostname"] = CGI["SERVER_SOFTWARE"] & ":" & Application.Name & "-" & Application.Version
    res["fldcomp"] = modBasic.$compID
    res.Update

  Endif

End

''======================== Patient List =======================
' Public Function GetAdmittedPatientList(sDept As String, sColor As String)
'
'   Dim hForm As FmPatBedList
'   Dim xdept As String
'   Dim xcolor As String
'
'   If sDept Then
'     xdept = UnQuote(sDept)
'   Else
'     xdept = "%"
'   Endif
'   If sColor Then
'     xcolor = sColor
'   Else
'     xcolor = "All"
'   Endif
'   modHelpVariable.ConnectionMain()
'   modHelpVariable.CalenderConnection()
'   modHelpVariable.ICDTablesConnection()
'   If modDatabase.$myConn.Opened = True Then
'     modGeneralMain.EnableCollectionCache()
'     modBasic.LoadGeneralVariables()
'     hForm = New FmPatBedList(xdept, xcolor)
'     hForm.Show
'   Endif
'
' End

''------------------------- patient Exit ---------------------------
Public Function GetClearanceForExit(encid As String) As Boolean

  Dim sTypeList As String[] = ["Events", "Delivery", "Procedure", "Devices"]
  Dim xType As String
  Dim res As Result
  Dim res1 As Result
  Dim res2 As Result
  Dim xval As Boolean

  xval = True
  If xval = True Then
    res1 = modDatabase.$myConn.Exec("select fldid,flditem,fldfirsttime from tblpattiming where fldencounterval=&1 and fldtype=&2 and fldfirstsave=&3 and fldsecondsave=&4", encid, "Equipment", True, False)
    If res1.Available Then
      xval = False
      Message.Warning(("Please Close running Equipment(s)"), ("OK"))
    Endif
  Endif

  If xval = True Then
    For Each xType In sTypeList
      res = modDatabase.$myConn.Exec("select fldid,flditem,fldfirsttime from tblpatevents where fldencounterval=&1 and fldtype=&2 and fldfirstsave=&3 and fldsecondsave=&4", encid, xType, True, False)
      If res.Available Then
        xval = False
        Message.Warning(("Please Close running Event(s) for " & xType), ("OK"))
        Break
      Endif
    Next
  Endif

  If xval = True Then
    res2 = modDatabase.$myConn.Exec("select fldid,flddoseno,fldfromtime,fldtotime from tblnurdosing where fldencounterval=&1 and flddoseno in(select fldid from tblpatdosing where fldencounterval=&1 and fldsave_order=&2 and fldroute=&3 and fldcurval=&4)", encid, True, "fluid", "Continue")
    If res2.Available Then
      For Each res2
        If res2!fldfromtime And If Not res2!fldtotime Then
          xval = False
          Message.Warning(("Please Close running IV Infusion(s)"), ("OK"))
          Break
        Endif
      Next
    Endif
  Endif

  Return xval

End

''-------------------------------- Acc Demographic ----------------------------------
Public Sub AddAccGeneralQualiData(encid As String, strInput As String, strItem As String, strReport As String, strDetail As String, dt As Date, sav As Boolean)

  Dim res As Result
  Dim xIntVal As String

  res = modDatabase.$myConn.Create("tblpataccgeneral")
  res["fldencounterval"] = encid
  res["fldinput"] = strInput
  res["fldtype"] = "Qualitative"
  res["flditem"] = strItem
  res["fldreportquali"] = strReport
  res["fldreportquanti"] = 0
  res["flddetail"] = strDetail
  res["fldnewdate"] = dt
  res["flduserid"] = modBasic.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = sav
  res["flduptime"] = ""
  res["xyz"] = False

  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif

  res.Update()
  'don't catch error

End

Public Sub AddAccGeneralQuantiData(encid As String, strInput As String, strItem As String, strReport As Float, strDetail As String, dt As Date, sav As Boolean)

  Dim res As Result
  Dim xIntVal As String

  res = modDatabase.$myConn.Create("tblpataccgeneral")
  res["fldencounterval"] = encid
  res["fldinput"] = strInput
  res["fldtype"] = "Quantitative"
  res["flditem"] = strItem
  res["fldreportquali"] = CStr(strReport)
  res["fldreportquanti"] = strReport
  res["flddetail"] = strDetail
  res["fldnewdate"] = dt
  res["flduserid"] = modBasic.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = sav
  res["flduptime"] = ""
  res["xyz"] = False

  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif

  res.Update()
  'don't catch error

End

''Update
Public Sub UpdateAccGeneralQualiData(id As Long, strItem As String, strReport As String, strDetail As String, dt As Date, sav As Boolean)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpataccgeneral", "fldid=&1", id)
  If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
    res["flditem"] = strItem
    res["fldreportquali"] = strReport
    res["flddetail"] = strDetail
    res["fldnewdate"] = dt
    res["flduserid"] = modBasic.$lbluser
    res["flduptime"] = Now()
    res["fldcomp"] = modBasic.$compID
    res["fldsave"] = sav
    res["xyz"] = False
    res.Update()
  Else
    Message.Warning("Authorization with " & res["flduserid"], ("OK"))
  Endif
  'don't catch error

End

Public Sub UpdateAccGeneralQuantiData(id As Long, strItem As String, strReport As Float, strDetail As String, dt As Date, sav As Boolean)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpataccgeneral", "fldid=&1", id)
  If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
    res["flditem"] = strItem
    res["fldreportquali"] = CStr(strReport)
    res["fldreportquanti"] = strReport
    res["flddetail"] = strDetail
    res["fldnewdate"] = dt
    res["flduserid"] = modBasic.$lbluser
    res["flduptime"] = Now()
    res["fldcomp"] = modBasic.$compID
    res["fldsave"] = sav
    res["xyz"] = False
    res.Update()
  Else
    Message.Warning("Authorization with " & res["flduserid"], ("OK"))
  Endif
  'don't catch error

End

Public Sub LockPatientActivity(frm As String, encid As String)

  Dim res As Result
  Dim res1 As Result

  res1 = modDatabase.$myConn.Edit("tblactivity", "fldcategory=&1 and fldactivity=&2 and fldcomment=&3", "Patient Lock", "EncounterID", encid)
  If res1.Available = False Then
    res = modDatabase.$myConn.Create("tblactivity")
    res["fldfrmname"] = frm
    res["fldcategory"] = "Patient Lock"
    res["fldactivity"] = "EncounterID"
    res["fldcomment"] = encid
    res["flduserid"] = modBasic.$lbluser
    res["fldtime"] = Now()
    res["fldcomp"] = modBasic.$compID
    res["fldsave"] = True
    res["fldhostmac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res.Update
  Else
    res["fldfrmname"] = frm
    res["flduserid"] = modBasic.$lbluser
    res["fldtime"] = Now()
    res["fldcomp"] = modBasic.$compID
    res["fldsave"] = True
    res["fldhostmac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res.Update
  Endif

End
