' Gambas module file

Public Sub InsertRadioTestOrder(encid As String, strTest As String, strType As String, strMethod As String, grpid As Long, sRefer As String, sBillNo As String, sComment As String, plandate As Date, sFormat As String, Optional sPacsForm As String, Optional sStudyUID As String, Optional sSeriesUID As String)                      ''

  Dim res As Result
  Dim xIntVal As String

  res = modDatabase.$myConn.Create("tblpatradiotest")
  res["fldencounterval"] = encid
  res["fldtestid"] = strTest
  res["fldmethod"] = strMethod
  res["fldgroupid"] = grpid
  res["fldsampletype"] = sFormat
  res["fldsampleid"] = ""
  res["fldreportquali"] = ""
  res["fldreportquanti"] = 0
  res["fldfilepath"] = ""
  res["fldstatus"] = "Sampled"
  res["fldprint"] = False
  res["fldabnormal"] = False
  res["fldrefername"] = sRefer
  res["fldcondition"] = ""
  res["fldcomment"] = sComment
  res["fldbillno"] = sBillNo
  If modBasic.$LabAddHidden = "Yes" Then
    res["flvisible"] = "Hidden"
  Else
    res["flvisible"] = "Visible"
  Endif
  res["fldnewdate"] = plandate

  If sStudyUID Then
    res["fldpacstudy"] = sStudyUID
  Else
    res["fldpacstudy"] = ""
  Endif
  If sSeriesUID Then
    res["fldpacseries"] = sSeriesUID
  Else
    res["fldpacseries"] = ""
  Endif
  If sPacsForm Then
    res["fldpacsform"] = sPacsForm
  Else
    res["fldpacsform"] = ""
  Endif

  res["fldtest_type"] = strType
  res["fldchk"] = False
  res["fldorder"] = 0

  res["flduserid_report"] = ""
  res["fldtime_report"] = ""
  res["fldcomp_report"] = modBasic.$compID
  res["fldsave_report"] = False
  res["flduptime_report"] = ""
  res["fldupuser_report"] = ""

  res["flduserid_verify"] = ""
  res["fldtime_verify"] = ""
  res["fldcomp_verify"] = ""
  res["fldsave_verify"] = False
  res["flduptime_verify"] = ""
  res["fldupuser_verify"] = ""
  res["xyz"] = True

  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif
  res.Update()
  'don't catch error

End

Public Sub InsertRadioSubTestUnit(encid As String, testId As Long, examName As String, subExam As String, optionType As String, sOrder As Variant)

  Dim res As Result
  Dim xIntVal As String

  res = modDatabase.$myConn.Create("tblpatradiosubtest")
  res["fldencounterval"] = encid
  res["fldtestid"] = testId
  res["fldparent"] = examName
  res["fldsubtest"] = subExam
  res["fldindex"] = modApplication.GetMD5SumString(testId & ":" & encid & ":" & examName & ":" & subExam)
  res["fldtanswertype"] = optionType
  res["fldreport"] = ""
  res["fldsave"] = False
  res["fldabnormal"] = False
  res["fldchk"] = False
  If sOrder Then
    res["fldorder"] = sOrder
  Else
    res["fldorder"] = 0
  Endif
  res["fldfilepath"] = ""
  res["xyz"] = True
  If MMain.$WebEntry = True Then
    xIntVal = modString.GetDateString(Now())
    res["fldid"] = CLong(xIntVal)
    res["fldrepoid"] = modMisc.GetWebIndexStr(xIntVal)
    res["fldrepodate"] = Now()
    res["fldrepomac"] = CGI["REMOTE_ADDR"] & ":" & CGI["REMOTE_PORT"]
    res["fldhospcode"] = modBasic.$HospCode
  Endif
  res.Update()
  'don't catch error

End

Public Sub InsertRadioSubTest(encid As String, testId As Long, examName As String, subtestList As String[])

  Dim xx As String
  Dim opType As String

  For Each xx In subtestList
    opType = modFixRadio.GetSubRadioOption(examName, xx)
    InsertRadioSubTestUnit(encid, testId, examName, xx, opType, 0)
  Next
  'don't catch error

End

Public Sub UpdateRadioTestReportQuali(id As Long, strReport As String, abn As Boolean, Optional KeyList As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatradiotest", "fldid=&1", id)
  res["fldreportquali"] = Trim(strReport)
  If IsFloat(strReport) = True Then
    res["fldreportquanti"] = CFloat(Trim(strReport))
  Else
    res["fldreportquanti"] = 0
  Endif
  If KeyList Then
    res["fldfilepath"] = KeyList
  Endif
  res["fldstatus"] = "Reported"
  res["flduserid_report"] = modBasic.$lbluser
  If res["fldtime_report"] Then
    res["flduptime_report"] = Now()
  Else
    res["fldtime_report"] = Now()
  Endif
  res["fldcomp_report"] = modBasic.$compID
  res["fldsave_report"] = True
  res["fldabnormal"] = abn
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdateRadioTestReportQuanti(id As Long, strReport As Float, abn As Boolean)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatradiotest", "fldid=&1", id)
  res["fldreportquali"] = CStr(strReport)
  res["fldreportquanti"] = strReport
  res["fldstatus"] = "Reported"
  res["flduserid_report"] = modBasic.$lbluser
  If res["fldtime_report"] Then
    res["flduptime_report"] = Now()
  Else
    res["fldtime_report"] = Now()
  Endif
  res["fldcomp_report"] = modBasic.$compID
  res["fldsave_report"] = True
  res["fldabnormal"] = abn
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdateRadioTestOrder(id As Long, sOrder As Integer)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatradiotest", "fldid=&1", id)
  res["fldorder"] = sOrder
  ' res["xyz"] = False
  res.Update

End

Public Sub UpdateRadioSubTestOrder(id As Long, sOrder As Integer)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatradiosubtest", "fldid=&1", id)
  res["fldorder"] = sOrder
  ' res["xyz"] = False
  res.Update

End

Public Sub UpdateEquipmenRadiotMethod(id As Long, sMethod As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatradiotest", "fldid=&1", id)
  res["fldmethod"] = sMethod
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdateConditionRadio(id As Long, condition As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatradiotest", "fldid=&1", id)
  res["fldcondition"] = condition
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdateVerifyRadioReport(id As Long)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatradiotest", "fldid=&1", id)
  res["fldstatus"] = "Verified"
  res["flvisible"] = "Visible"
  res["flduserid_verify"] = modBasic.$lbluser
  If res["fldtime_verify"] Then
    res["flduptime_verify"] = Now()
  Else
    res["fldtime_verify"] = Now()
  Endif
  res["fldcomp_verify"] = modBasic.$compID
  res["fldsave_verify"] = True
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub CancelVerifyRadioReport(id As Long)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatradiotest", "fldid=&1", id)
  res["fldstatus"] = "Reported"
  res["flduserid_verify"] = modBasic.$lbluser
  If res["fldtime_verify"] Then
    res["flduptime_verify"] = Now()
  Else
    res["fldtime_verify"] = Now()
  Endif
  res["fldcomp_verify"] = modBasic.$compID
  res["fldsave_verify"] = False
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Function GetRadioAutoIncreasingNo() As String

  Dim xsampauto As String
  Dim xprefix As String

  xprefix = modBasic.$RadioSamplePrefix
  If modBasic.$LabAutoSampNo = "Yes" Then
    xsampauto = xprefix & CStr(modBillLock.CurrentRadioNo())
  Else
    xsampauto = xprefix
  Endif
  Return xsampauto

End

Public Function GetRadioRepoOrder(sType As String) As String

  Dim xx As String
  Dim xorder As String

  xorder = modBasic.$LabTestOrdering
  If xorder Then
    If xorder = "ASC" Then
      If sType = "Test" Then
        xx = " ORDER BY fldtestid ASC"
      Else If sType = "SubTest" Then
        xx = " ORDER BY fldsubtest ASC"
      Endif
    Else If xorder = "DESC" Then
      If sType = "Test" Then
        xx = " ORDER BY fldtestid DESC"
      Else If sType = "SubTest" Then
        xx = " ORDER BY fldsubtest DESC"
      Endif
    Else If xorder = "Manual" Then
      If sType = "Test" Then
        xx = " ORDER BY fldorder ASC"
      Else If sType = "SubTest" Then
        xx = " ORDER BY fldorder ASC"
      Endif
    Else
      If sType = "Test" Then
        xx = ""
      Else If sType = "SubTest" Then
        xx = ""
      Endif
    Endif
  Else
    If sType = "Test" Then
      xx = ""
    Else If sType = "SubTest" Then
      xx = ""
    Endif
  Endif

  Return xx

End
