' Gambas module file

Public Function GetBarCodeString(strPic As String) As String

  Dim xx As String
  Dim yy As String
  Dim arcmd As String[]

  If System.Exist("zbarimg") Then
    arcmd = ["zbarimg", "-q", "--raw", strPic]
    modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
    Exec arcmd To xx
    If xx Then
      yy = xx
    Else
      yy = ""
    Endif
  Else
    modApplSub.InstallSelectedApplication(["zbar-tools"])
  Endif
  Return yy

End

Public Function GetBarCodeFromVideo(strDev As String) As String

  Dim xx As String
  Dim yy As String
  Dim arcmd As String[]

  If System.Exist("zbarcam") = True Then
    arcmd = ["zbarcam", "--raw", strDev]
    modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
    Exec arcmd To xx
    If xx Then
      yy = xx
    Else
      yy = ""
    Endif
  Endif
  Return yy

End
