' Gambas module file

Public Function GetPythonLineChart(sTitle As String, dataFile As String, xLabel As String, yLabel As String) As String

  Dim ReportPart As String
  Dim sTemp As String
  Dim sPath As String

  sTemp = Temp() & ".png"
  sPath = Temp()
  ReportPart = File.Load(modHelpVariable.$pythonDirectory &/ "linechart.py")
  ReportPart = Replace(ReportPart, "{DataList}", Quote(dataFile))
  ReportPart = Replace(ReportPart, "{TITLE}", Quote(sTitle))
  ReportPart = Replace(ReportPart, "{xLabel}", Quote(xLabel))
  ReportPart = Replace(ReportPart, "{yLabel}", Quote(yLabel))
  ReportPart = Replace(ReportPart, "{TargetImage}", Quote(sTemp))

  File.Save(sPath, ReportPart)
  If System.Exist("python3") Then
    Exec ["python3", sPath] Wait
  Else
    modApplSub.InstallSelectedApplication(["python3"])
  Endif

  Return sTemp

End
