' Gambas module file

''============= using ICD 10 ===================
Public Function GetDiagnosisValue(sName As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$icdConn.Exec("select fldoldcode from tblicddisease where fldicdnme=&1", sName)
  If res.Available Then
    If res["fldoldcode"] Then
      xx = res["fldoldcode"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetDiagnoCodeValue(sCode As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$icdConn.Exec("select fldicdnme from tblicddisease where fldoldcode=&1", sCode)
  If res.Available Then
    If res["fldicdnme"] Then
      xx = res["fldicdnme"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

''============= using ICD 11 ===================
Public Function GetNewDiagnosisValue(sName As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$icdConn.Exec("select fldicdcode from tblicddisease where fldicdnme=&1", sName)
  If res.Available Then
    If res["fldicdcode"] Then
      xx = res["fldicdcode"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetNewDiagnoCodeValue(sCode As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$icdConn.Exec("select fldicdnme from tblicddisease where fldicdcode=&1", sCode)
  If res.Available Then
    If res["fldicdnme"] Then
      xx = res["fldicdnme"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

''============= 10 and 11 conversion ==================
Public Function GetNewCodeFromOld(sCode As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$icdConn.Exec("select fldicdcode from tblicddisease where fldoldcode=&1", sCode)
  If res.Available Then
    If res["fldicdcode"] Then
      xx = res["fldicdcode"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetOldCodeFromNew(sCode As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$icdConn.Exec("select fldoldcode from tblicddisease where fldicdcode=&1", sCode)
  If res.Available Then
    If res["fldoldcode"] Then
      xx = res["fldoldcode"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End
