' Gambas module file

Public Sub SetGeneralCredentials()

  modHelpVariable.$CryptValue = "123" ''for password/encryption
  modHelpVariable.$CryptDBVal = "123"  ''for database
  modHelpVariable.$CryptZip = "123"  ''only for 7z archiving for non-repository
  modHelpVariable.$CryptPDF = "123"    ''only for PDFencryption

  modHelpVariable.$CryptRepo = "123"   ''only for patient encryption (including repository)
  modHelpVariable.$CryptRepoZip = "123"  ''only for 7z archiving for repository
  modHelpVariable.$SaltValue = "\x01"

End

''=================== NEWER VERSION (0.4 or later) =============================
Public Function ValidateKeyLatest() As Integer

  
  Return 0

End
