' Gambas module file

Public Sub SetGeneralCredentials()

  modHelpVariable.$CryptValue = "23qP53Xxszqytppz6uRIr9" ''for password/encryption
  modHelpVariable.$CryptDBVal = "23qP53Xxszqytppz6uRIr9"  ''for database
  modHelpVariable.$CryptZip = "23qP53Xxszqytppz6uRIr9"  ''only for 7z archiving for non-repository
  modHelpVariable.$CryptPDF = "23qP53Xszqppz6uIr9"    ''only for PDFencryption

  modHelpVariable.$CryptRepo = "23qP53Xxszqytppz6uRIr9"   ''only for patient encryption (including repository)
  modHelpVariable.$CryptRepoZip = "23qP53Xxrtftppz6uRIr9"  ''only for 7z archiving for repository
  modHelpVariable.$SaltValue = "\x01\x23\x45\x67\x89\xab\xcd\xef"

End

''=================== NEWER VERSION (0.4 or later) =============================
Public Function ValidateKeyLatest() As Integer

  Dim res As Result
  Dim xx As Integer
  Dim dy As Integer
  Dim remn As String
  Dim rsx As Result

  Dim las As Integer
  Dim sdate As Date
  Dim xkey As String

  Dim keyval1 As String
  Dim keyval2 As String
  Dim asxKey As String[]
  Dim res1 As Result

  If MMain.$RepoReportMode = True Then
    xx = 0
  Else
    rsx = modDatabase.$myConn.Exec("select COUNT(fldhostmac) as tot from tblmacaccess")
    If rsx["tot"] = 1 Then
      xx = 0
    Else

      modBasic.DebugString("Validating First Key")
      xkey = modSettings.ShowSettingFromFIle("TermsOfUse/ExtendKey1")
      If xkey And If xkey = "Yes" Then
        las = 95
      Else
        las = 90
      Endif

      sdate = modPatient.GetFirstRegistrationDate()
      If Not sdate Then
        xx = 3
        Message.Warning(("Invalid table data"), ("OK"))
      Else
        res = modDatabase.$myConn.Exec("select key1,key2 from tblnewkey")
        If res.Available = True Then
          res.MoveLast
          keyval1 = modPassword.DecryptSimple(UnBase64(res["key1"]))
          keyval2 = modPassword.DecryptSimple(UnBase64(res["key2"]))
          asxKey = Split(keyval1, ":")
          If asxKey[0] = MMain.$SISHAppMode And If asxKey[1] = CStr(Month(sdate)) & CStr(Day(sdate)) & CStr(Hour(sdate)) & CStr(Minute(sdate)) Then        '
            res1 = modDatabase.$myConn.Exec("select fldhostmac from tblmacaccess where fldhostmac=&1", keyval2)
            If res1.Available Then
              xx = 0
            Else
              xx = 3
              Message.Warning(("Missing License key location"), ("OK"))
            Endif
          Else
            xx = 3
            Message.Warning(("Invalid License key"), ("OK"))
          Endif

        Else If res.Available = False Then
          dy = DateDiff(sdate, Now(), gb.Day)
          remn = CStr(120 - dy)
          If dy >= 60 And If dy < las Then
            Message.Warning(remn & (" day remaining. Please insert License key"), ("OK"))
            xx = 1
          Else If dy >= las And If dy < 120 Then
            Message.Warning(remn & (" day remaining. Please insert License key"), ("OK"))
            xx = 2
          Else If dy >= 120 Then
            xx = 3
            Message.Warning(("Please insert License key to proceed"), ("OK"))
          Endif

        Endif
      Endif

    Endif
  Endif

  Return xx

End
