' Gambas module file

''---------------------------------------------- QUOTA (fixed parameters) ---------------------------------------------------------------
Public Function GetPatientQuota(sDept As String, sDate As Date, sBillMode As String, sUserid As String) As Integer

  Dim res As Result
  Dim res1 As Result
  Dim res2 As Result
  Dim xx As Integer
  Dim xdeptmode As String

  xdeptmode = modGeneral.GetCategoryFromDept(sDept)
  If xdeptmode = "Consultation" Then
    If modBasic.$RegistQuotaQueMode = "ConsultOnly" Then
      res = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddate>=&1 and flddate<=&2 and fldselect=&3 and flduserid=&4 and fldcomp like &5 and fldmethod=&6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), "Specific", sUserid, modBasic.$compID, "ConsultOnly")
      If res.Available And If res["tot"] Then
        xx = res["tot"]
      Else
        res1 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where fldselect=&1 and flduserid=&2 and fldcomp like &3 and fldmethod=&4", modDate.GetWeekDay(sDate), sUserid, modBasic.$compID, "ConsultOnly")
        If res1.Available And If res1["tot"] Then
          xx = res1["tot"]
        Else
          res2 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where fldselect=&1 and flduserid=&2 and fldcomp like &3 and fldmethod=&4", "AllDays", sUserid, modBasic.$compID, "ConsultOnly")
          If res2.Available And If res2["tot"] Then
            xx = res2["tot"]
          Else
            xx = 0
          Endif
        Endif
      Endif

    Else If modBasic.$RegistQuotaQueMode = "DepartOnly" Then
      res = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddate>=&1 and flddate<=&2 and fldselect=&3 and flddept=&4 and fldcomp like &5 and fldmethod=&6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), "Specific", sDept, modBasic.$compID, "DepartOnly")
      If res.Available And If res["tot"] Then
        xx = res["tot"]
      Else
        res1 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where fldselect=&1 and flddept=&2 and fldcomp like &3 and fldmethod=&4", modDate.GetWeekDay(sDate), sDept, modBasic.$compID, "DepartOnly")
        If res1.Available And If res1["tot"] Then
          xx = res1["tot"]
        Else
          res2 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where fldselect=&1 and flddept=&2 and fldcomp like &3 and fldmethod=&4", "AllDays", sDept, modBasic.$compID, "DepartOnly")
          If res2.Available And If res2["tot"] Then
            xx = res2["tot"]
          Else
            xx = 0
          Endif
        Endif
      Endif

    Else If modBasic.$RegistQuotaQueMode = "Consult+Mode" Then
      res = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddate>=&1 and flddate<=&2 and fldselect=&3 and fldbillingmode like &4 and flduserid=&5 and fldcomp like &6 and fldmethod=&7", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), "Specific", sBillMode, sUserid, modBasic.$compID, "Consult+Mode")
      If res.Available And If res["tot"] Then
        xx = res["tot"]
      Else
        res1 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where fldselect=&1 and fldbillingmode like &2 and flduserid=&3 and fldcomp like &4 and fldmethod=&5", modDate.GetWeekDay(sDate), sBillMode, sUserid, modBasic.$compID, "Consult+Mode")
        If res1.Available And If res1["tot"] Then
          xx = res1["tot"]
        Else
          res2 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where fldselect=&1 and fldbillingmode like &2 and flduserid=&3 and fldcomp like &4 and fldmethod=&5", "AllDays", sBillMode, sUserid, modBasic.$compID, "Consult+Mode")
          If res2.Available And If res2["tot"] Then
            xx = res2["tot"]
          Else
            xx = 0
          Endif
        Endif
      Endif

    Else
      If sUserid Then
        res = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddate>=&1 and flddate<=&2 and (flddept like &3 or flddept=&7) and fldselect=&4 and fldbillingmode like &5 and flduserid=&6 and fldcomp like &8 and fldmethod=&9", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, "Specific", sBillMode, sUserid, "%", modBasic.$compID, "AllParam")
      Else
        res = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddate>=&1 and flddate<=&2 and (flddept like &3 or flddept=&6) and fldselect=&4 and fldbillingmode like &5 and fldcomp like &7 and fldmethod=&8", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, "Specific", sBillMode, "%", modBasic.$compID, "AllParam")
      Endif
      If res.Available And If res["tot"] Then
        xx = res["tot"]
      Else
        If sUserid Then
          res1 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and flduserid=&4 and fldcomp like &5 and fldmethod=&6", sDept, modDate.GetWeekDay(sDate), sBillMode, sUserid, modBasic.$compID, "AllParam")
        Else
          res1 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and fldcomp like &4 and fldmethod=&5", sDept, modDate.GetWeekDay(sDate), sBillMode, modBasic.$compID, "AllParam")
        Endif
        If res1.Available And If res1["tot"] Then
          xx = res1["tot"]
        Else
          If sUserid Then
            res2 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and flduserid=&4 and fldcomp like &5 and fldmethod=&6", sDept, "AllDays", sBillMode, sUserid, modBasic.$compID, "AllParam")
          Else
            res2 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and fldcomp like &4 and fldmethod=&5", sDept, "AllDays", sBillMode, modBasic.$compID, "AllParam")
          Endif
          If res2.Available And If res2["tot"] Then
            xx = res2["tot"]
          Else
            xx = 0
          Endif
        Endif
      Endif

    Endif

  Else If xdeptmode = "OPD Visit" Then
    If modBasic.$RegistOPQuotaQueMode = "DepartOnly" Then
      res = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddate>=&1 and flddate<=&2 and fldselect=&3 and flddept=&4 and fldcomp like &5 and fldmethod=&6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), "Specific", sDept, modBasic.$compID, "DepartOnly")
      If res.Available And If res["tot"] Then
        xx = res["tot"]
      Else
        res1 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where fldselect=&1 and flddept=&2 and fldcomp like &3 and fldmethod=&4", modDate.GetWeekDay(sDate), sDept, modBasic.$compID, "DepartOnly")
        If res1.Available And If res1["tot"] Then
          xx = res1["tot"]
        Else
          res2 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where fldselect=&1 and flddept=&2 and fldcomp like &3 and fldmethod=&4", "AllDays", sDept, modBasic.$compID, "DepartOnly")
          If res2.Available And If res2["tot"] Then
            xx = res2["tot"]
          Else
            xx = 0
          Endif
        Endif
      Endif

    Else
      res = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddate>=&1 and flddate<=&2 and (flddept like &3 or flddept=&6) and fldselect=&4 and fldbillingmode like &5 and fldcomp like &7 and fldmethod=&8", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, "Specific", sBillMode, "%", modBasic.$compID, "AllParam")
      If res.Available And If res["tot"] Then
        xx = res["tot"]
      Else
        res1 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and fldcomp like &4 and fldmethod=&5", sDept, modDate.GetWeekDay(sDate), sBillMode, modBasic.$compID, "AllParam")
        If res1.Available And If res1["tot"] Then
          xx = res1["tot"]
        Else
          res2 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and fldcomp like &4 and fldmethod=&5", sDept, "AllDays", sBillMode, modBasic.$compID, "AllParam")
          If res2.Available And If res2["tot"] Then
            xx = res2["tot"]
          Else
            xx = 0
          Endif
        Endif
      Endif

    Endif

  Endif

  Return xx

End

Public Function GetUserPostingList(sDept As String, sDate As Date, sBillMode As String) As Variant[]

  Dim res As Result
  Dim res1 As Result
  Dim res2 As Result
  Dim xx As String[]
  Dim yy As String[]

  Dim xVar As Variant[]
  Dim xval As String

  xx = New String[]
  If modBasic.$RegistQuotaQueMode = "ConsultOnly" Then
    If MMain.$WebEntry = True And If modBasic.$HospCode Then
      res = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where flddate>=&1 and flddate<=&2 and fldselect=&3 and fldcomp like &4 and fldmethod=&5 and fldhospcode like &6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), "Specific", modBasic.$compID, "ConsultOnly", modBasic.$HospCode)
    Else
      res = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where flddate>=&1 and flddate<=&2 and fldselect=&3 and fldcomp like &4 and fldmethod=&5", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), "Specific", modBasic.$compID, "ConsultOnly")
    Endif
    If res.Available Then
      For Each res
        If res["doc"] Then
          xx.Add(res["doc"])
        Endif
      Next
    Endif
    If MMain.$WebEntry = True And If modBasic.$HospCode Then
      res1 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where fldselect=&1 and fldcomp like &2 and fldmethod=&3 and fldhospcode like &4", modDate.GetWeekDay(sDate), modBasic.$compID, "ConsultOnly", modBasic.$HospCode)
    Else
      res1 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where fldselect=&1 and fldcomp like &2 and fldmethod=&3", modDate.GetWeekDay(sDate), modBasic.$compID, "ConsultOnly")
    Endif
    If res1.Available Then
      For Each res1
        If res1["doc"] Then
          xx.Add(res1["doc"])
        Endif
      Next
    Endif
    If MMain.$WebEntry = True And If modBasic.$HospCode Then
      res2 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where fldselect=&1 and fldcomp like &2 and fldmethod=&3 and fldhospcode like &4", "AllDays", modBasic.$compID, "ConsultOnly", modBasic.$HospCode)
    Else
      res2 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where fldselect=&1 and fldcomp like &2 and fldmethod=&3", "AllDays", modBasic.$compID, "ConsultOnly")
    Endif
    If res2.Available Then
      For Each res2
        If res2["doc"] Then
          xx.Add(res2["doc"])
        Endif
      Next
    Endif

  Else If modBasic.$RegistQuotaQueMode = "DepartOnly" Then
    xx = modBasic.$OPConsulUserList

  Else If modBasic.$RegistQuotaQueMode = "Consult+Mode" Then
    If MMain.$WebEntry = True And If modBasic.$HospCode Then
      res = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where flddate>=&1 and flddate<=&2 and fldselect=&3 and fldbillingmode like &4 and fldcomp like &5 and fldmethod=&6 and fldhospcode like &7", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), "Specific", sBillMode, modBasic.$compID, "Consult+Mode", modBasic.$HospCode)
    Else
      res = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where flddate>=&1 and flddate<=&2 and fldselect=&3 and fldbillingmode like &4 and fldcomp like &5 and fldmethod=&6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), "Specific", sBillMode, modBasic.$compID, "Consult+Mode")
    Endif
    If res.Available Then
      For Each res
        If res["doc"] Then
          xx.Add(res["doc"])
        Endif
      Next
    Endif
    If MMain.$WebEntry = True And If modBasic.$HospCode Then
      res1 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where fldselect=&1 and fldbillingmode like &2 and fldcomp like &3 and fldmethod=&4 and fldhospcode like &5", modDate.GetWeekDay(sDate), sBillMode, modBasic.$compID, "Consult+Mode", modBasic.$HospCode)
    Else
      res1 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where fldselect=&1 and fldbillingmode like &2 and fldcomp like &3 and fldmethod=&4", modDate.GetWeekDay(sDate), sBillMode, modBasic.$compID, "Consult+Mode")
    Endif
    If res1.Available Then
      For Each res1
        If res1["doc"] Then
          xx.Add(res1["doc"])
        Endif
      Next
    Endif
    If MMain.$WebEntry = True And If modBasic.$HospCode Then
      res2 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where fldselect=&1 and fldbillingmode like &2 and fldcomp like &3 and fldmethod=&4 and fldhospcode like &5", "AllDays", sBillMode, modBasic.$compID, "Consult+Mode", modBasic.$HospCode)
    Else
      res2 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where fldselect=&1 and fldbillingmode like &2 and fldcomp like &3 and fldmethod=&4", "AllDays", sBillMode, modBasic.$compID, "Consult+Mode")
    Endif
    If res2.Available Then
      For Each res2
        If res2["doc"] Then
          xx.Add(res2["doc"])
        Endif
      Next
    Endif

  Else
    If MMain.$WebEntry = True And If modBasic.$HospCode Then
      res = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where flddate>=&1 and flddate<=&2 and flddept like &3 and fldselect=&4 and fldbillingmode like &5 and fldcomp like &6 and fldmethod=&7 and fldhospcode like &8", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, "Specific", sBillMode, modBasic.$compID, "AllParam", modBasic.$HospCode)
    Else
      res = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where flddate>=&1 and flddate<=&2 and flddept like &3 and fldselect=&4 and fldbillingmode like &5 and fldcomp like &6 and fldmethod=&7", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, "Specific", sBillMode, modBasic.$compID, "AllParam")
    Endif
    If res.Available Then
      For Each res
        If res["doc"] Then
          xx.Add(res["doc"])
        Endif
      Next
    Endif
    If MMain.$WebEntry = True And If modBasic.$HospCode Then
      res1 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and fldcomp like &4 and fldmethod=&5 and fldhospcode like &6", sDept, modDate.GetWeekDay(sDate), sBillMode, modBasic.$compID, "AllParam", modBasic.$HospCode)
    Else
      res1 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and fldcomp like &4 and fldmethod=&5", sDept, modDate.GetWeekDay(sDate), sBillMode, modBasic.$compID, "AllParam")
    Endif
    If res1.Available Then
      For Each res1
        If res1["doc"] Then
          xx.Add(res1["doc"])
        Endif
      Next
    Endif
    If MMain.$WebEntry = True And If modBasic.$HospCode Then
      res2 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and fldcomp like &4 and fldmethod=&5 and fldhospcode like &6", sDept, "AllDays", sBillMode, modBasic.$compID, "AllParam", modBasic.$HospCode)
    Else
      res2 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and fldcomp like &4 and fldmethod=&5", sDept, "AllDays", sBillMode, modBasic.$compID, "AllParam")
    Endif
    If res2.Available Then
      For Each res2
        If res2["doc"] Then
          xx.Add(res2["doc"])
        Endif
      Next
    Endif

  Endif

  xVar = New Variant[]
  If xx And If xx.Count Then
    yy = modString.BinaryDistinctStringArray(xx)
    For Each xval In yy
      xVar.Add([xval, modGeneral.GetUserFullName(xval)])
    Next
  Endif

  Return xVar

End

''------------------------------------ Quota (patient parameters)
Public Function GetPatientBooked(sType As String, sDept As String, sDate As Date, sBillMode As String, sUserid As String) As Integer

  Dim res As Result
  Dim xx As Integer

  If modBasic.$RegistQuotaQueMode = "ConsultOnly" Then
    res = modDatabase.$myConn.Exec("select COUNT(fldbookingval) as tot from tblpatientbook where fldconsultdate>=&1 and fldconsultdate<=&2 and flduserid=&3 and fldstate like &4 and fldcomp=&5", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sUserid, sType, modBasic.$compID)

  Else If modBasic.$RegistQuotaQueMode = "DepartOnly" Then
    res = modDatabase.$myConn.Exec("select COUNT(fldbookingval) as tot from tblpatientbook where fldconsultdate>=&1 and fldconsultdate<=&2 and fldadmitlocat=&3 and fldstate like &4 and fldcomp=&5", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, sType, modBasic.$compID)

  Else If modBasic.$RegistQuotaQueMode = "Consult+Mode" Then
    res = modDatabase.$myConn.Exec("select COUNT(fldbookingval) as tot from tblpatientbook where fldconsultdate>=&1 and fldconsultdate<=&2 and fldbillingmode like &3 and flduserid=&4 and fldstate like &5 and fldcomp=&6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sBillMode, sUserid, sType, modBasic.$compID)

  Else
    If sUserid Then
      res = modDatabase.$myConn.Exec("select COUNT(fldbookingval) as tot from tblpatientbook where fldconsultdate>=&1 and fldconsultdate<=&2 and fldadmitlocat like &3 and fldbillingmode like &4 and flduserid=&5 and fldstate like &6 and fldcomp=&7", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, sBillMode, sUserid, sType, modBasic.$compID)                                                  ''
    Else
      res = modDatabase.$myConn.Exec("select COUNT(fldbookingval) as tot from tblpatientbook where fldconsultdate>=&1 and fldconsultdate<=&2 and fldadmitlocat like &3 and fldbillingmode like &4 and fldstate like &5 and fldcomp=&6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, sBillMode, sType, modBasic.$compID)                                                  ''
    Endif

  Endif
  If res.Available And If res["tot"] Then
    xx = res["tot"]
  Else
    xx = 0
  Endif
  Return xx

End

Public Function GetPatientRegisteredValid(sDept As String, sDate As Date, sBillMode As String, sUserid As String) As Integer

  Dim res As Result
  Dim xx As Integer
  Dim xdeptmode As String

  xdeptmode = modGeneral.GetCategoryFromDept(sDept)
  If xdeptmode = "Consultation" Then
    If modBasic.$RegistQuotaQueMode = "ConsultOnly" Then
      res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and flduserid=&3 and fldstatus<>&4 and fldcomp like &5", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sUserid, "Cancelled", modBasic.$compID)
    Else If modBasic.$RegistQuotaQueMode = "DepartOnly" Then
      res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname=&3 and fldstatus<>&4 and fldcomp like &5", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, "Cancelled", modBasic.$compID)
    Else If modBasic.$RegistQuotaQueMode = "Consult+Mode" Then
      res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldbillingmode like &3 and flduserid=&4 and fldstatus<>&5 and fldcomp like &6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sBillMode, sUserid, "Cancelled", modBasic.$compID)
    Else
      If sUserid Then
        res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname like &3 and fldbillingmode like &4 and flduserid=&5 and fldstatus<>&6 and fldcomp like &7", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, sBillMode, sUserid, "Cancelled", modBasic.$compID)
      Else
        res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname like &3 and fldbillingmode like &4 and fldstatus<>&5 and fldcomp like &6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, sBillMode, "Cancelled", modBasic.$compID)                                                  ''
      Endif
    Endif
    If res.Available And If res["tot"] Then
      xx = res["tot"]
    Else
      xx = 0
    Endif

  Else If xdeptmode = "OPD Visit" Then
    If modBasic.$RegistOPQuotaQueMode = "DepartOnly" Then
      res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblopvisit where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname=&3 and fldstatus<>&4 and fldcomp like &5", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, "Cancelled", modBasic.$compID)
    Else
      res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblopvisit where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname like &3 and fldbillingmode like &4 and fldstatus<>&5 and fldcomp like &6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, sBillMode, "Cancelled", modBasic.$compID)                                                  ''
    Endif
    If res.Available And If res["tot"] Then
      xx = res["tot"]
    Else
      xx = 0
    Endif

  Endif

  Return xx

End

Public Function GetPatientRegisteredCancel(sDept As String, sDate As Date, sBillMode As String, sUserid As String) As Integer

  Dim res As Result
  Dim xx As Integer
  Dim xdeptmode As String

  xdeptmode = modGeneral.GetCategoryFromDept(sDept)
  If xdeptmode = "Consultation" Then
    If modBasic.$RegistQuotaQueMode = "ConsultOnly" Then
      res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and flduserid=&3 and fldstatus=&4 and fldcomp like &5", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sUserid, "Cancelled", modBasic.$compID)
    Else If modBasic.$RegistQuotaQueMode = "DepartOnly" Then
      res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname=&3 and fldstatus=&4 and fldcomp like &5", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, "Cancelled", modBasic.$compID)
    Else If modBasic.$RegistQuotaQueMode = "Consult+Mode" Then
      res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldbillingmode like &3 and flduserid=&4 and fldstatus=&5 and fldcomp like &6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sBillMode, sUserid, "Cancelled", modBasic.$compID)
    Else
      If sUserid Then
        res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname like &3 and fldbillingmode like &4 and flduserid=&5 and fldstatus=&6 and fldcomp like &7", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, sBillMode, sUserid, "Cancelled", modBasic.$compID)
      Else
        res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname like &3 and fldbillingmode like &4 and fldstatus=&5 and fldcomp like &6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, sBillMode, "Cancelled", modBasic.$compID)                                                  ''
      Endif
    Endif

  Else If xdeptmode = "OPD Visit" Then
    If modBasic.$RegistOPQuotaQueMode = "DepartOnly" Then
      res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblopvisit where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname=&3 and fldstatus=&4 and fldcomp like &5", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, "Cancelled", modBasic.$compID)
    Else
      res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblopvisit where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname like &3 and fldbillingmode like &4 and fldstatus=&5 and fldcomp like &6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, sBillMode, "Cancelled", modBasic.$compID)                                                  ''
    Endif

  Endif

  If res.Available And If res["tot"] Then
    xx = res["tot"]
  Else
    xx = 0
  Endif
  Return xx

End

Public Function GetQueNumber(sDept As String, sDate As Date, encid As String, sBillMode As String, sUserid As String) As String

  Dim res As Result
  Dim xx As String
  Dim xdeptmode As String

  xdeptmode = modGeneral.GetCategoryFromDept(sDept)
  If xdeptmode = "Consultation" Then
    If sUserid Then
      If modBasic.$RegistQuotaQueMode = "ConsultOnly" Then
        res = modDatabase.$myConn.Exec("select fldencounterval from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and flduserid=&3 and fldcomp like &4 ORDER BY fldid ASC", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sUserid, modBasic.$compID)                    ''
      Else If modBasic.$RegistQuotaQueMode = "Consult+Mode" Then
        res = modDatabase.$myConn.Exec("select fldencounterval from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and flduserid=&3 and fldbillingmode=&4 and fldcomp like &5 ORDER BY fldid ASC", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sUserid, sBillMode, modBasic.$compID)                    ''
      Else
        res = modDatabase.$myConn.Exec("select fldencounterval from tblconsult where fldconsultname=&1 and fldconsulttime>=&2 and fldconsulttime<=&3 and fldbillingmode=&4 and flduserid=&5 and fldcomp like &6 ORDER BY fldid ASC", sDept, modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sBillMode, sUserid, modBasic.$compID)                    ''
      Endif
    Else
      If modBasic.$RegistQuotaQueMode = "ConsultOnly" Then
        res = modDatabase.$myConn.Exec("select fldencounterval from tblconsult where fldconsultname=&1 and fldconsulttime>=&2 and fldconsulttime<=&3 and fldcomp like &4 ORDER BY fldid ASC", sDept, modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), modBasic.$compID)
      Else If modBasic.$RegistQuotaQueMode = "DepartOnly" Then
        res = modDatabase.$myConn.Exec("select fldencounterval from tblconsult where fldconsultname=&1 and fldconsulttime>=&2 and fldconsulttime<=&3 and fldcomp like &4 ORDER BY fldid ASC", sDept, modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), modBasic.$compID)
      Else
        res = modDatabase.$myConn.Exec("select fldencounterval from tblconsult where fldconsultname=&1 and fldconsulttime>=&2 and fldconsulttime<=&3 and fldbillingmode=&4 and fldcomp like &5 ORDER BY fldid ASC", sDept, modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sBillMode, modBasic.$compID)                    ''
      Endif
    Endif

  Else If xdeptmode = "OPD Visit" Then
    If modBasic.$RegistOPQuotaQueMode = "ConsultOnly" Then
      res = modDatabase.$myConn.Exec("select fldencounterval from tblopvisit where fldconsultname=&1 and fldconsulttime>=&2 and fldconsulttime<=&3 and fldcomp like &4 ORDER BY fldid ASC", sDept, modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), modBasic.$compID)
    Else If modBasic.$RegistOPQuotaQueMode = "DepartOnly" Then
      res = modDatabase.$myConn.Exec("select fldencounterval from tblopvisit where fldconsultname=&1 and fldconsulttime>=&2 and fldconsulttime<=&3 and fldcomp like &4 ORDER BY fldid ASC", sDept, modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), modBasic.$compID)
    Else
      res = modDatabase.$myConn.Exec("select fldencounterval from tblopvisit where fldconsultname=&1 and fldconsulttime>=&2 and fldconsulttime<=&3 and fldbillingmode=&4 and fldcomp like &5 ORDER BY fldid ASC", sDept, modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sBillMode, modBasic.$compID)                    ''
    Endif

  Endif

  If res.Available Then
    For Each res
      If res["fldencounterval"] = encid Then
        xx = CStr(res.Index + 1)
      Endif
    Next
  Else
    xx = ""
  Endif

  Return xx

End
