' Gambas module file

Public $MLModelOutputColl As Collection

''---------------------- Integration -------------------------
Public Function GetAIModelsList(sType As String) As String[]

  Dim i As Integer
  Dim xxx As String[]

  xxx = New String[]
  For i = 1 To 20
    If modSettings.ShowModelsSettingFromFIle("AIModel" & CStr(i) & "/" & "Name") Then
      If modSettings.ShowModelsSettingFromFIle("AIModel" & CStr(i) & "/" & "Role") = sType Then
        xxx.Add(modSettings.ShowModelsSettingFromFIle("AIModel" & CStr(i) & "/" & "Name"))
      Endif
    Endif
  Next
  Return xxx

End

Public Function GeAItModelValueArguments(xModel As String, xArgs As String[], Optional sFile As String) As String

  Dim i As Integer
  Dim xurl As String
  Dim xexec As String
  Dim xval As String

  For i = 1 To 20
    If modSettings.ShowModelsSettingFromFIle("AIModel" & CStr(i) & "/" & "Name") = xModel Then
      xurl = modSettings.ShowModelsSettingFromFIle("AIModel" & CStr(i) & "/" & "URL")
      xexec = modSettings.ShowModelsSettingFromFIle("AIModel" & CStr(i) & "/" & "Shell")
      Break
    Endif
  Next

  If sFile Then
    xval = ModelValueArguments(xModel, xurl, xexec, xArgs, sFile)
  Else
    xval = ModelValueArguments(xModel, xurl, xexec, xArgs)
  Endif

  Return xval

End

Public Function GetAIModelValue(encid As String, xModel As String, Optional sFile As String) As String

  Dim i As Integer
  Dim xstrargs As String
  Dim xnumargs As String
  Dim xurl As String
  Dim xexec As String
  Dim xval As String

  For i = 1 To 20
    If modSettings.ShowModelsSettingFromFIle("AIModel" & CStr(i) & "/" & "Name") = xModel Then
      xurl = modSettings.ShowModelsSettingFromFIle("AIModel" & CStr(i) & "/" & "URL")
      xexec = modSettings.ShowModelsSettingFromFIle("AIModel" & CStr(i) & "/" & "Shell")
      xstrargs = modSettings.ShowModelsSettingFromFIle("AIModel" & CStr(i) & "/" & "StrArgument")
      xnumargs = modSettings.ShowModelsSettingFromFIle("AIModel" & CStr(i) & "/" & "NumArgument")
      Break
    Endif
  Next

  If sFile Then
    xval = ModelValue(encid, xModel, xurl, xexec, xstrargs, xnumargs, sFile)
  Else
    xval = ModelValue(encid, xModel, xurl, xexec, xstrargs, xnumargs)
  Endif

  Return xval

End

''------------------------ local ----------------------------
Public Function GetMLModelsList(sType As String) As String[]

  Dim i As Integer
  Dim xxx As String[]

  xxx = New String[]
  For i = 1 To 20
    If modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "Name") Then
      If modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "Role") = sType Then
        xxx.Add(modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "Name"))
      Endif
    Endif
  Next
  Return xxx

End

Public Function GetModelValueArguments(xModel As String, xArgs As String[], Optional sFile As String) As String

  Dim i As Integer
  Dim xurl As String
  Dim xexec As String
  Dim xval As String

  For i = 1 To 20
    If modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "Name") = xModel Then
      xurl = modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "URL")
      xexec = modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "Shell")
      Break
    Endif
  Next

  If sFile Then
    xval = ModelValueArguments(xModel, xurl, xexec, xArgs, sFile)
  Else
    xval = ModelValueArguments(xModel, xurl, xexec, xArgs)
  Endif

  Return xval

End

Public Function GetModelValue(encid As String, xModel As String, Optional sFile As String) As String

  Dim i As Integer
  Dim xstrargs As String
  Dim xnumargs As String
  Dim xurl As String
  Dim xexec As String
  Dim xval As String

  For i = 1 To 20
    If modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "Name") = xModel Then
      xurl = modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "URL")
      xexec = modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "Shell")
      xstrargs = modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "StrArgument")
      xnumargs = modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "NumArgument")
      Break
    Endif
  Next

  If sFile Then
    xval = ModelValue(encid, xModel, xurl, xexec, xstrargs, xnumargs, sFile)
  Else
    xval = ModelValue(encid, xModel, xurl, xexec, xstrargs, xnumargs)
  Endif

  Return xval

End

''---------------------- Procedures ------------------------------------
Private Function ModelValueArguments(xModel As String, xurl As String, xexec As String, xArgs As String[], Optional sFile As String) As String

  Dim j As Integer
  Dim xcmd As String

  Dim aData As String[]
  Dim xval As String

  aData = New String[]
  aData.Add("--form 'model=" & Quote(xModel) & "'")
  aData.Add("--form 'exec=" & Quote(xexec) & "'")

  For j = 0 To xArgs.Count - 1
    If IsNumber(xArgs[j]) Then
      aData.Add("--form 'numargs" & CStr(j + 1) & "=" & Quote(xArgs[j]) & "'")
    Else
      aData.Add("--form 'strargs" & CStr(j + 1) & "=" & Quote(xArgs[j]) & "'")
    Endif
  Next

  If sFile Then
    aData.Add("--form 'files=@" & Quote(sFile) & "'")
  Endif

  If xurl Then
    If $MLModelOutputColl[JSON.Encode(aData)] Then
      xval = $MLModelOutputColl[JSON.Encode(aData)]
    Else
      xcmd = "curl --no-buffer --location " & xurl & "?upload" & Space(1) & aData.Join(Space(1))
      modBasic.DebugAPIString(xcmd)
      Shell xcmd To xval
      $MLModelOutputColl.Add(xval, JSON.Encode(aData))
    Endif
  Endif

  Return xval

End

Private Function ModelValue(encid As String, xModel As String, xurl As String, xexec As String, xstrargs As String, xnumargs As String, Optional sFile As String) As String

  Dim xcmd As String
  Dim j As Integer
  Dim k As Integer

  Dim asx As String[]
  Dim asy As String[]
  Dim xvar As Variant

  Dim aData As String[]
  Dim xval As String
  Dim strCount As Integer
  Dim numCount As Integer
  Dim strAllow As Boolean
  Dim numAllow As Boolean

  aData = New String[]
  aData.Add("--form 'model=" & Quote(xModel) & "'")
  aData.Add("--form 'exec=" & Quote(xexec) & "'")

  strAllow = True
  If xstrargs Then
    asx = Split(xstrargs, ";")
    strCount = 0
    For j = 0 To asx.Count - 1
      xvar = ""
      xvar = modReportVar.GetPatientVariableValue(Trim(asx[j]), encid)
      If xvar Then
        If xvar = "__" Then
          Break
        Else
          aData.Add("--form 'strargs" & CStr(j + 1) & "=" & Quote(xvar) & "'")
          strCount = strCount + 1
        Endif
      Endif
    Next
    If asx.Count > strCount Then
      strAllow = False
    Endif
  Endif

  numAllow = True
  If xnumargs Then
    asy = Split(xnumargs, ";")
    numCount = 0
    For k = 0 To asy.Count - 1
      xvar = ""
      xvar = modReportVar.GetPatientVariableValue(Trim(asy[k]), encid)
      If xvar Then
        If xvar = "__" Then
          Break
        Else
          aData.Add("--form 'numargs" & CStr(k + 1) & "=" & Quote(xvar) & "'")
          numCount = numCount + 1
        Endif
      Endif
    Next
    If asy.Count > numCount Then
      numAllow = False
    Endif
  Endif

  If sFile Then
    aData.Add("--form 'files=@" & Quote(sFile) & "'")
  Endif

  If strAllow = True And If numAllow = True Then
    If xurl Then
      If $MLModelOutputColl[JSON.Encode(aData)] Then
        xval = $MLModelOutputColl[JSON.Encode(aData)]
      Else
        xcmd = "curl --no-buffer --location " & xurl & "?upload" & Space(1) & aData.Join(Space(1))
        modBasic.DebugAPIString(xcmd)
        Shell xcmd To xval
        $MLModelOutputColl.Add(xval, JSON.Encode(aData))
      Endif
    Endif
  Endif

  Return xval

End
