' Gambas module file

'NOTE:------------------------------------- Dose calculation -----------------------------------------
Public Function GetDoseInMg(dos As Float, unt As String, encid As String) As Float

  Dim dosval As Float
  Dim wt As Float
  Dim bsa As Float

  Select unt
    Case "mg", "IU", "mL"
      dosval = dos

    Case "mg/Kg", "IU/Kg", "mL/Kg"
      wt = modClinic.GetBodyWeight(encid)
      If wt Then
        dosval = dos * wt
      Else
        dosval = 0
      Endif

    Case "mg/sqm", "IU/sqm", "mL/sqm"
      bsa = modSysCons.GetCalculationAValue("Body_Surface_Area", encid)
      If bsa Then
        dosval = dos * bsa
      Else
        dosval = 0
      Endif

  End Select

  If dosval Then
    dosval = Round(dosval, -2)
  Endif

  Return dosval

End

Public Function GetDoseInMgFoFromRegID(id As Long, encid As String) As Float

  Dim res As Result
  Dim dose As Float
  Dim xval As Float

  res = modDatabase.$medConn.Exec("select flddose,flddoseunit from tblregimen where fldid=&1", id)
  If res.Available = True Then
    If res["flddose"] Then
      xval = GetDoseInMg(res["flddose"], res["flddoseunit"], encid)
      If xval Then
        dose = xval
      Else
        dose = 0
      Endif
    Else
      dose = 0
    Endif
  Else
    dose = 0
  Endif

  Return dose

End

Public Function GetDoseAdjustmentFactor(xEliminationFraction As Float, xCreatinineClearence As Float) As Float

  Dim xx As Float

  xx = (xCreatinineClearence / 120) - 1
  xx = 1 + xx * xEliminationFraction
  xx = Round(1 / xx, -3)

  Return xx

End
