' Gambas module file

Public Function GetStudyTitle(studycode As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldstudyname from tblresearch where fldstudycode=&1", studycode)
  If res.Available Then
    If res["fldstudyname"] Then
      xx = res["fldstudyname"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetStudyGroup(studycode As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldstudylocat from tblresearch where fldstudycode=&1", studycode)
  If res.Available Then
    If res["fldstudylocat"] Then
      xx = res["fldstudylocat"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetStudySelection(studycode As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldstudycriteria from tblresearch where fldstudycode=&1", studycode)
  If res.Available Then
    If res["fldstudycriteria"] Then
      xx = res["fldstudycriteria"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetStudyAllSample(studycode As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldstudysample from tblresearch where fldstudycode=&1", studycode)
  If res.Available Then
    If res["fldstudysample"] Then
      xx = res["fldstudysample"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End
