' Gambas module file

Public Sub CreateDatabaseForSish($con As Connection)

  ''------------------- essential ----------------------
  CreateDatabaseForSish_System($con)
  CreateDatabaseForSish_Demographics($con)
  ''------------------- Fixed Data table--------------------
  CreateDatabaseForSish_Medicine($con)
  CreateDatabaseForSish_Pathology($con)
  CreateDatabaseForSish_Diadnostic($con)
  CreateDatabaseForSish_Data($con)
  ''-------------------Patient data--------------------------
  CreateDatabaseForSish_Finance($con)
  CreateDatabaseForSish_Inventory($con)
  CreateDatabaseForSish_Patient($con)
  CreateDatabaseForSish_Telemed($con)
  ''------------------ Research--------------------------------
  CreateDatabaseForSish_Research($con)

  ''For Ayurveda only
  If MMain.$Ayurveda = "Yes" Then
    CreateDatabaseForSish_Ayurveda($con)
  Endif
  ''Repo Index
  If modDBTables.$DbFormat = "REP" Then
    modDBExternal.CREATEtbladvertise($con)
    modDBExternal.CREATEtbladlinks($con)
    modDBExternal.CREATEtblapplog($con)
    modDBApp.CreateRepositoryIndex($con)
  Endif

End

Public Sub CreateDatabaseForMedical($con As Connection)

  CreateDatabaseForSish_Medicine($con)
  CreateDatabaseForSish_Pathology($con)
  CreateDatabaseForSish_Diadnostic($con)
  CreateDatabaseForSish_Data($con)

End

Public Sub CreateDatabaseForDashboard($con As Connection)

  modDBTables.$DbFormat = "Dashboard"
  CreateDatabaseForSish_System($con)
  CreateDatabaseForSish_Demographics($con)

  modDBTables.CREATEtblpopulation($con)
  modDBTables.CREATEtbldashparameters($con)

End

Private Sub CreateDatabaseForSish_Ayurveda($con As Connection)

  modDBTables.CREATEtblamissetting($con)

End

Private Sub CreateDatabaseForSish_Medicine($con As Connection)

  'blood
  modDBTables.CREATEtblblood($con)
  modDBTables.CREATEtblbloodstore($con)
  modDBTables.CREATEtblvaccine($con)

  'medicines
  modDBTables.CREATEtblmedcategory($con)
  modDBTables.CREATEtblsensidrugs($con)
  modDBTables.CREATEtblchemclass($con)
  modDBTables.CREATEtblcode($con)
  modDBTables.CREATEtblcodelimit($con)
  modDBTables.CREATEtblcompatdrug($con)
  modDBTables.CREATEtblcompatfluid($con)
  modDBTables.CREATEtbldilutionfluid($con)
  modDBTables.CREATEtblincompatdrug($con)
  modDBTables.CREATEtblincompatfluid($con)
  modDBTables.CREATEtblreconstfluid($con)
  modDBTables.CREATEtbldosageforms($con)
  modDBTables.CREATEtblmanufacturer($con)
  modDBTables.CREATEtblextradepartment($con)
  modDBTables.CREATEtbldrug($con)
  modDBTables.CREATEtblinjection($con)
  modDBTables.CREATEtbllabel($con)
  modDBTables.CREATEtblmedbrand($con)
  modDBTables.CREATEtblmedregimen($con)
  modDBTables.CREATEtblmedhepatic($con)
  modDBTables.CREATEtblmedinteraction($con)
  modDBTables.CREATEtblmedpregnancy($con)
  modDBTables.CREATEtblmedrenal($con)
  modDBTables.CREATEtblmedcontraindication($con)
  modDBTables.CREATEtblmedadveffect($con)
  modDBTables.CREATEtblmedmonitor($con)
  modDBTables.CREATEtblregimen($con)
  modDBTables.CREATEtbllocallabel($con)
  modDBTables.CREATEtblmedgroup($con)

  'groupings
  modDBTables.CREATEtblproductgroup($con)
  modDBTables.CREATEtblsurgicalname($con)

  'surgicals
  modDBTables.CREATEtblsuturetype($con)
  modDBTables.CREATEtblsurgicals($con)
  modDBTables.CREATEtblsurgbrand($con)

  'extra
  modDBTables.CREATEtblextra($con)
  modDBTables.CREATEtblextrabrand($con)

  'nutrition
  modDBTables.CREATEtblfoodlist($con)
  modDBTables.CREATEtblfoodtype($con)
  modDBTables.CREATEtblfoodcontent($con)
  modDBTables.CREATEtblfoodmix($con)
  modDBTables.CREATEtblfoodgroup($con)
  modDBTables.CREATEtbldietgroup($con)
  modDBTables.CREATEtblnutrition($con)

End

Private Sub CreateDatabaseForSish_Pathology($con As Connection)

  'general
  modDBTables.CREATEtblpathocategory($con)
  modDBTables.CREATEtblbodyfluid($con)
  modDBTables.CREATEtblsurveillance($con)
  modDBTables.CREATEtblbilldisease($con)
  modDBTables.CREATEtblethnicgroup($con)
  modDBTables.CREATEtbldiagnogroup($con)

  'symptom/syndrome
  modDBTables.CREATEtblsymptoms($con)
  modDBTables.CREATEtblsubsymptoms($con)
  modDBTables.CREATEtblpathosymp($con)
  modDBTables.CREATEtblsyndromes($con)

  'features
  modDBTables.CREATEtblpathotest($con)
  modDBTables.CREATEtblpathoexam($con)
  modDBTables.CREATEtbltriage($con)
  modDBTables.CREATEtblclinchart($con)
  modDBTables.CREATEtblaiquery($con)

End

Private Sub CreateDatabaseForSish_Diadnostic($con As Connection)

  'test
  modDBTables.CREATEtblagegroups($con)
  modDBTables.CREATEtbltestmethod($con)
  modDBTables.CREATEtblorganism($con)
  modDBTables.CREATEtblsampletype($con)
  modDBTables.CREATEtbltestcondition($con)
  modDBTables.CREATEtbllabchemical($con)
  modDBTables.CREATEtbltestmachine($con)
  modDBTables.CREATEtblmachinemethod($con)
  modDBTables.CREATEtbltest($con)
  modDBTables.CREATEtbltestoption($con)
  modDBTables.CREATEtbltestlimit($con)
  modDBTables.CREATEtbltestcomment($con)
  modDBTables.CREATEtblcodehypo($con)
  modDBTables.CREATEtblcodehyper($con)
  modDBTables.CREATEtblsyndrohypo($con)
  modDBTables.CREATEtblsyndrohyper($con)
  modDBTables.CREATEtbltestquali($con)
  modDBTables.CREATEtblsubtestquali($con)
  modDBTables.CREATEtblantipanel($con)
  modDBTables.CREATEtblgrouptest($con)

  'exam
  modDBTables.CREATEtblstructexam($con)
  modDBTables.CREATEtblstructexamoption($con)
  modDBTables.CREATEtblcompexam($con)
  modDBTables.CREATEtblcomplaints($con)
  modDBTables.CREATEtbldeptexam($con)
  modDBTables.CREATEtbldeptexamoption($con)
  modDBTables.CREATEtblgroupexam($con)
  modDBTables.CREATEtblexam($con)
  modDBTables.CREATEtblexamoption($con)
  modDBTables.CREATEtblexamlimit($con)
  modDBTables.CREATEtblexamcomment($con)
  modDBTables.CREATEtblcodebrady($con)
  modDBTables.CREATEtblcodetachy($con)
  modDBTables.CREATEtblsyndrobrady($con)
  modDBTables.CREATEtblsyndrotachy($con)
  modDBTables.CREATEtblexamquali($con)
  modDBTables.CREATEtblsubexamquali($con)

  'radio
  modDBTables.CREATEtblradio($con)
  modDBTables.CREATEtblradiooption($con)
  modDBTables.CREATEtblradiolimit($con)
  modDBTables.CREATEtblradiocomment($con)
  modDBTables.CREATEtblradioquali($con)
  modDBTables.CREATEtblsubradioquali($con)
  modDBTables.CREATEtblgroupradio($con)

  'demographics
  modDBTables.CREATEtblprocname($con)
  modDBTables.CREATEtblgroupproc($con)
  modDBTables.CREATEtbldemographic($con)
  modDBTables.CREATEtbldemogoption($con)
  modDBTables.CREATEtblevents($con)
  modDBTables.CREATEtbldevices($con)
  modDBTables.CREATEtblreferlist($con)

  'List & delivery
  modDBTables.CREATEtbldischarge($con)
  modDBTables.CREATEtblhistory($con)
  modDBTables.CREATEtbldelivery($con)
  modDBTables.CREATEtbldelcomplication($con)
  modDBTables.CREATEtbldeldeformity($con)
  modDBTables.CREATEtbldellabour($con)
  modDBTables.CREATEtblprocedure($con)
  modDBTables.CREATEtblprocedureuser($con)
  modDBTables.CREATEtblanaesthesia($con)
  modDBTables.CREATEtblchecklist($con)

  modDBTables.CREATEtblsysconst($con)
  modDBTables.CREATEtblrepomapping($con)

End

Private Sub CreateDatabaseForSish_Data($con As Connection)

  modDBTables.CREATEtblmedimage($con)
  modDBTables.CREATEtblelectrolyte($con)
  modDBTables.CREATEtblresearch($con)

End

Private Sub CreateDatabaseForSish_System($con As Connection)

  'system tables
  modDBTables.CREATEtblautoid($con)
  modDBTables.CREATEtblinvid($con)
  modDBTables.CREATEtblpatsubs($con)
  modDBTables.CREATEtbllock($con)
  modDBTables.CREATEtblfiscalid($con)
  modDBTables.CREATEtblfisclosing($con)
  modDBTables.CREATEtblenclock($con)
  modDBTables.CREATEtbldiagnoid($con)
  modDBTables.CREATEtbltabsettings($con)
  modDBTables.CREATEtblsettings($con)
  modDBTables.CREATEtblhmissetting($con)
  modDBTables.CREATEtblgnupg($con)

  'logs
  modDBTables.CREATEtblautoemail($con)
  modDBTables.CREATEtblcronjob($con)
  modDBTables.CREATEtblirdactivity($con)
  modDBTables.CREATEtblactivity($con)
  modDBTables.CREATEtbljobrecord($con)
  modDBTables.CREATEtblmessage($con)
  modDBTables.CREATEtblsystemlog($con)
  modDBTables.CREATEtblauthenticate($con)
  modDBTables.CREATEtblreposync($con)
  modDBTables.CREATEtblreportlog($con)
  modDBTables.CREATEtblsmslog($con)
  modDBTables.CREATEtblmessagelog($con)

  'users
  modDBTables.CREATEtblstafflist($con)
  modDBTables.CREATEtblsociallist($con)
  modDBTables.CREATEtbluser($con)
  modDBTables.CREATEtblusercategory($con)
  modDBTables.CREATEtblmiscategory($con)
  modDBTables.CREATEtbluserimage($con)
  modDBTables.CREATEtblreportgroup($con)
  modDBTables.CREATEtblmasterdept($con)
  modDBTables.CREATEtblreportuser($con)

  'security
  modDBTables.CREATEtblkey($con)
  modDBTables.CREATEtblnewkey($con)
  modDBTables.CREATEtbluseraccess($con)
  modDBTables.CREATEtblcompaccess($con)
  modDBTables.CREATEtblmacaccess($con)
  modDBTables.CREATEtbluserformaccess($con)
  modDBTables.CREATEtblclinicentry($con)

  'extra
  modDBTables.CREATEtblpersonal($con)
  modDBTables.CREATEtblfileshare($con)

End

Private Sub CreateDatabaseForSish_Demographics($con As Connection)

  modDBTables.CREATEtblsurname($con)
  modDBTables.CREATEtblhospitals($con)
  modDBTables.CREATEtblmunicipals($con)
  modDBTables.CREATEtblrelations($con)
  modDBTables.CREATEtblranks($con)
  modDBTables.CREATEtblunits($con)

End

Private Sub CreateDatabaseForSish_Finance($con As Connection)

  'general
  modDBTables.CREATEtblipdservice($con)
  modDBTables.CREATEtblhospbranch($con)
  modDBTables.CREATEtbldepartment($con)
  modDBTables.CREATEtbldeptgroup($con)
  modDBTables.CREATEtbldepartmentbed($con)
  modDBTables.CREATEtbldepartbedcharge($con)
  modDBTables.CREATEtblacledger($con)
  modDBTables.CREATEtblcategorylist($con)
  modDBTables.CREATEtblschemecategory($con)

  'billing
  modDBTables.CREATEtbldiscount($con)
  modDBTables.CREATEtblforcediscount($con)
  modDBTables.CREATEtblnodiscount($con)
  modDBTables.CREATEtbllockedservice($con)
  modDBTables.CREATEtblcustdiscount($con)
  modDBTables.CREATEtblcustquantity($con)
  modDBTables.CREATEtblcustcredit($con)
  modDBTables.CREATEtblbillingset($con)
  modDBTables.CREATEtblpackschedule($con)
  modDBTables.CREATEtblbillitem($con)
  modDBTables.CREATEtblbillsection($con)
  modDBTables.CREATEtblcurrency($con)
  modDBTables.CREATEtblservicecheck($con)
  modDBTables.CREATEtblservicecost($con)
  modDBTables.CREATEtblcostgroup($con)
  modDBTables.CREATEtblextrasetting($con)
  modDBTables.CREATEtbldepconsult($con)

  modDBTables.CREATEtblprocedureshare($con)
  modDBTables.CREATEtblusershare($con)
  modDBTables.CREATEtbluserpay($con)
  modDBTables.CREATEtblservicegroup($con)
  modDBTables.CREATEtblcostbreak($con)
  modDBTables.CREATEtblautogroup($con)
  modDBTables.CREATEtblfoodorder($con)
  modDBTables.CREATEtbltaxgroup($con)
  modDBTables.CREATEtbldiscgroup($con)
  modDBTables.CREATEtblcashvendor($con)
  modDBTables.CREATEtblpackgroup($con)
  modDBTables.CREATEtblaccdemograp($con)
  modDBTables.CREATEtblaccdemogoption($con)

  'logs
  modDBTables.CREATEtbljournal($con)

  ''-------------extra payments -------------------------
  modDBTables.CREATEtblextrapayers($con)
  modDBTables.CREATEtblextrapayitems($con)
  modDBTables.CREATEtblextrareceipt($con)

  ''fixed assets
  modDBTables.CREATEtblassetsname($con)
  modDBTables.CREATEtblassetsentry($con)

End

Private Sub CreateDatabaseForSish_Inventory($con As Connection)

  'stock
  modDBTables.CREATEtblentry($con)
  modDBTables.CREATEtblentrybackup($con)
  modDBTables.CREATEtblstockrate($con)
  modDBTables.CREATEtbladjustment($con)

  'purchase
  modDBTables.CREATEtblpurchase($con)
  modDBTables.CREATEtblpurchasebill($con)
  modDBTables.CREATEtblstockreturn($con)
  modDBTables.CREATEtblsupplier($con)
  modDBTables.CREATEtbltenderlist($con)
  modDBTables.CREATEtblpayment($con)

  'transfers
  modDBTables.CREATEtbltransfer($con)
  modDBTables.CREATEtblpurorder($con)
  modDBTables.CREATEtblrequest($con)
  modDBTables.CREATEtbltarget($con)
  modDBTables.CREATEtblbulksale($con)

  'blood/other
  modDBTables.CREATEtblmedinventory($con)

End

Private Sub CreateDatabaseForSish_Patient($con As Connection)

  'general
  modDBTables.CREATEtblpatientbook($con)
  modDBTables.CREATEtblonlinebook($con)
  modDBTables.CREATEtblpatientinfo($con)
  modDBTables.CREATEtblencounter($con)
  modDBTables.CREATEtblabsconder($con)
  modDBTables.CREATEtblcreditlimit($con)
  modDBTables.CREATEtblclaimcode($con)
  modDBTables.CREATEtblssfclaim($con)
  modDBTables.CREATEtblpataccgeneral($con)
  modDBTables.CREATEtblpatdevice($con)
  modDBTables.CREATEtblpatientdate($con)

  'exam/test
  modDBTables.CREATEtblpatientexam($con)
  modDBTables.CREATEtblpatientsubexam($con)
  modDBTables.CREATEtblpatexamsubtable($con)
  modDBTables.CREATEtblpatlabtest($con)
  modDBTables.CREATEtblpatlabsubtest($con)
  modDBTables.CREATEtblpatlabsubtable($con)
  modDBTables.CREATEtblpatfindings($con)
  modDBTables.CREATEtblexamgeneral($con)
  modDBTables.CREATEtblpatgeneral($con)
  modDBTables.CREATEtblpatsubgeneral($con)
  modDBTables.CREATEtblpatgenshare($con)
  modDBTables.CREATEtblsharepayment($con)
  modDBTables.CREATEtblpatplanning($con)
  modDBTables.CREATEtblpatevents($con)
  modDBTables.CREATEtblpattiming($con)
  modDBTables.CREATEtblconsult($con)
  modDBTables.CREATEtblopvisit($con)
  modDBTables.CREATEtblgenviolence($con)
  modDBTables.CREATEtblobstetrics($con)
  modDBTables.CREATEtblconfinement($con)
  modDBTables.CREATEtblpatradiotest($con)
  modDBTables.CREATEtblpatradiosubtest($con)
  modDBTables.CREATEtblpatradiosubtable($con)
  modDBTables.CREATEtblradiocounter($con)
  modDBTables.CREATEtblsurgerysection($con)
  modDBTables.CREATEtblmonitor($con)
  modDBTables.CREATEtblextradosing($con)

  'billing
  modDBTables.CREATEtblusercollection($con)
  modDBTables.CREATEtblfiscal($con)
  modDBTables.CREATEtblduebilling($con)
  modDBTables.CREATEtblpatbilling($con)
  modDBTables.CREATEtblpatbilldetail($con)
  modDBTables.CREATEtbltempbilldetail($con)
  modDBTables.CREATEtblduebilldetail($con)
  modDBTables.CREATEtbladvreceiptdetail($con)
  modDBTables.CREATEtblcashsources($con)
  modDBTables.CREATEtblwebpayment($con)
  modDBTables.CREATEtblpatusershares($con)
  modDBTables.CREATEtblpatbillcounts($con)
  modDBTables.CREATEtblpatbillbooking($con)
  modDBTables.CREATEtblpatcharity($con)

  'dispensing
  modDBTables.CREATEtblpatmeditem($con)
  modDBTables.CREATEtbldrugproblems($con)
  modDBTables.CREATEtblpatdosing($con)
  modDBTables.CREATEtblpatoutdosing($con)
  modDBTables.CREATEtblpatdoseremote($con)
  modDBTables.CREATEtbltaperdose($con)
  modDBTables.CREATEtblnurdosing($con)
  modDBTables.CREATEtblvaccdosing($con)

  'images
  modDBTables.CREATEtblpayimage($con)
  modDBTables.CREATEtblpersonimage($con)
  modDBTables.CREATEtblpatimagedata($con)
  modDBTables.CREATEtblpatserialimage($con)
  modDBTables.CREATEtblpatreport($con)
  modDBTables.CREATEtblbillupload($con)
  modDBTables.CREATEtblbillrepoload($con)
  modDBTables.CREATEtblofficedocs($con)

  'general
  modDBTables.CREATEtblpatientpass($con)
  modDBTables.CREATEtblremotefollow($con)
  modDBTables.CREATEtblremoteusers($con)
  modDBTables.CREATEtblpacsupload($con)

End

Private Sub CreateDatabaseForSish_Telemed($con As Connection)

  modDBTables.CREATEtbltelemeduser($con)
  modDBTables.CREATEtbltelemedtalk($con)
  modDBTables.CREATEtblcurrteleuser($con)

  modDBTables.CREATEtbltelradiotest($con)
  modDBTables.CREATEtbltelradiosubtest($con)

End

Private Sub CreateDatabaseForSish_Research($con As Connection)

  modDBTables.CREATEtblpatientstudy($con)
  modDBTables.CREATEtblhaidenominators($con)
  modDBTables.CREATEtblhaicasereports($con)

End

Public Sub UpdateDBIndexes(sCon As Connection, sTable As String)

  Dim hTable As Table

  For Each hTable In sCon.Tables
    If hTable.Name = sTable Then

      If hTable.Name = "tblencounter" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldpatientval", ["fldpatientval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldregdate", ["fldregdate"], False)
        Try hTable.Indexes.Add(hTable.Name & "_flddoa", ["flddoa"], False)
        Try hTable.Indexes.Add(hTable.Name & "_flddod", ["flddod"], False)
      Else If hTable.Name = "tblpatientinfo" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldptbirday", ["fldptbirday"], False)
      Else If hTable.Name = "tblextrareceipt" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldreference", ["fldreference"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblmedinventory" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldcode", ["fldcode"], True)
      Else If hTable.Name = "tblpatdevice" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
      Else If hTable.Name = "tblpatientdate" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblpatientexam" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblpatientsubexam" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldheadid", ["fldheadid"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldindex", ["fldindex"], False)
      Else If hTable.Name = "tblpatexamsubtable" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldsubexamid", ["fldsubexamid"], False)
      Else If hTable.Name = "tblpatlabtest" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldsampleid", ["fldsampleid"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldbillno", ["fldbillno"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime_sample", ["fldtime_sample"], False)
      Else If hTable.Name = "tblpatlabsubtest" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtestid", ["fldtestid"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldindex", ["fldindex"], False)
      Else If hTable.Name = "tblpatlabsubtable" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldtestid_fldsubtestid", ["fldsubtestid", "fldtestid"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldindex", ["fldindex"], False)
      Else If hTable.Name = "tblpatfindings" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblexamgeneral" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblpatgeneral" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblpatsubgeneral" Then
        Try hTable.Indexes.Add(hTable.Name & "_flditemid", ["flditemid"], False)
      Else If hTable.Name = "tblpatgenshare" Then
        Try hTable.Indexes.Add(hTable.Name & "_flditemid", ["flditemid"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblsharepayment" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblpatplanning" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblpatevents" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldfirsttime", ["fldfirsttime"], False)
      Else If hTable.Name = "tblpattiming" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldfirsttime", ["fldfirsttime"], False)
      Else If hTable.Name = "tblconsult" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldconsulttime", ["fldconsulttime"], False)
      Else If hTable.Name = "tblopvisit" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldconsulttime", ["fldconsulttime"], False)
      Else If hTable.Name = "tblgenviolence" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblobstetrics" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldlast", ["fldlast"], False)
      Else If hTable.Name = "tblconfinement" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_flddeltime", ["flddeltime"], False)
      Else If hTable.Name = "tblpatradiotest" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldbillno", ["fldbillno"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime_report", ["fldtime_report"], False)
      Else If hTable.Name = "tblpatradiosubtest" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtestid", ["fldtestid"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldindex", ["fldindex"], False)
      Else If hTable.Name = "tblpatradiosubtable" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldexamid_fldsubexamid", ["fldsubexamid", "fldexamid"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldindex", ["fldindex"], False)
      Else If hTable.Name = "tbltelradiotest" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldbillno", ["fldbillno"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime_report", ["fldtime_report"], False)
      Else If hTable.Name = "tbltelradiosubtest" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldtestid", ["fldtestid"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldindex", ["fldindex"], False)
      Else If hTable.Name = "tblmonitor" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
      Else If hTable.Name = "tblextradosing" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
      Else If hTable.Name = "tblpatcharity" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
      Else If hTable.Name = "tblfiscal" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldbillno", ["fldbillno"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblduebilling" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldbillno", ["fldbillno"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblpatbilling" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldbillno", ["fldbillno"], False)
        Try hTable.Indexes.Add(hTable.Name & "_flditemname", ["flditemname"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldparent", ["fldparent"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldextracol", ["fldextracol"], False)
      Else If hTable.Name = "tblpatbilldetail" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldbillno", ["fldbillno"], True)
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldchequeno", ["fldchequeno"], False)
      Else If hTable.Name = "tbltempbilldetail" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldbillno", ["fldbillno"], True)
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldchequeno", ["fldchequeno"], False)
      Else If hTable.Name = "tblduebilldetail" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tbladvreceiptdetail" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldbillno", ["fldbillno"], True)
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblcashsources" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblwebpayment" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldbillno", ["fldbillno"], True)
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tbldrugproblems" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblpatdosing" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblpatoutdosing" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblpatdoseremote" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tbltaperdose" Then
        Try hTable.Indexes.Add(hTable.Name & "_flddoseno", ["flddoseno"], False)
      Else If hTable.Name = "tblnurdosing" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_flddoseno", ["flddoseno"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblvaccdosing" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblpatreport" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblofficedocs" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblpatientstudy" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
      Else If hTable.Name = "tblpatbillcounts" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldbillno", ["fldbillno"], False)
      Else If hTable.Name = "tblpatmeditem" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tbltelemeduser" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldcontact", ["fldcontact"], False)
      Else If hTable.Name = "tbltelemedtalk" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblpatientbook" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldpatientval", ["fldpatientval"], False)
      Else If hTable.Name = "tblonlinebook" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldpatientval", ["fldpatientval"], False)
      Else If hTable.Name = "tblpataccgeneral" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblpatimagedata" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblpatserialimage" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)

      Else If hTable.Name = "tblpurchase" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldreference", ["fldreference"], False)
      Else If hTable.Name = "tblpurchasebill" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldreference", ["fldreference"], True)
      Else If hTable.Name = "tblbulksale" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldreference", ["fldreference"], False)
      Else If hTable.Name = "tbltransfer" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldtoentrytime", ["fldtoentrytime"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldreference", ["fldreference"], False)
      Else If hTable.Name = "tblpurorder" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblrequest" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tbladjustment" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)

      Else If hTable.Name = "tblmedcontraindication" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
      Else If hTable.Name = "tblmedadveffect" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
      Else If hTable.Name = "tblcompatdrug" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
      Else If hTable.Name = "tblcompatfluid" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
      Else If hTable.Name = "tblincompatdrug" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
      Else If hTable.Name = "tblincompatfluid" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
      Else If hTable.Name = "tblcodebrady" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
      Else If hTable.Name = "tblcodetachy" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
      Else If hTable.Name = "tblcodehypo" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
      Else If hTable.Name = "tblcodehyper" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
      Else If hTable.Name = "tblsyndrohypo" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
      Else If hTable.Name = "tblsyndrohyper" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
      Else If hTable.Name = "tblsyndrobrady" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
      Else If hTable.Name = "tblsyndrotachy" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
      Else If hTable.Name = "tblmedinteraction" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldcodename_fldcondition", ["fldcodename", "fldcondition"], False)
      Else If hTable.Name = "tblmedpregnancy" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldcodename_fldcondition", ["fldcodename", "fldcondition"], False)
      Else If hTable.Name = "tblmedhepatic" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldcodename_fldcondition", ["fldcodename", "fldcondition"], False)
      Else If hTable.Name = "tblmedrenal" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldcodename_fldgfrfrom", ["fldcodename", "fldgfrfrom"], False)

      Else If hTable.Name = "tblstafflist" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldpatientval", ["fldpatientval"], True)
        Try hTable.Indexes.Add(hTable.Name & "_flduserid", ["flduserid"], True)
      Else If hTable.Name = "tblsociallist" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldpatientval_flddisctype", ["fldpatientval", "flddisctype"], True)

      Else If hTable.Name = "tblcreditlimit" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblclaimcode" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
      Else If hTable.Name = "tblssfclaim" Then
        Try hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)

      Endif

      If hTable.Fields.Exist("fldhospcode") Then
        Try hTable.Indexes.Add(hTable.Name & "_fldhospcode", ["fldhospcode"], False)
      Endif

    Endif
  Next

End

''--------------------------- Create Tables -----------------------------
Public Sub CreateRequiredTable($con As Connection, sTable As String)

  If sTable = "tblblood" Then
    modDBTables.CREATEtblblood($con)

  Else If sTable = "tblbloodstore" Then
    modDBTables.CREATEtblbloodstore($con)

  Else If sTable = "tblvaccine" Then
    modDBTables.CREATEtblvaccine($con)

  Else If sTable = "tblmedcategory" Then
    modDBTables.CREATEtblmedcategory($con)

  Else If sTable = "tblsensidrugs" Then
    modDBTables.CREATEtblsensidrugs($con)

  Else If sTable = "tblchemclass" Then
    modDBTables.CREATEtblchemclass($con)

  Else If sTable = "tblcode" Then
    modDBTables.CREATEtblcode($con)

  Else If sTable = "tblcodelimit" Then
    modDBTables.CREATEtblcodelimit($con)

  Else If sTable = "tblcompatdrug" Then
    modDBTables.CREATEtblcompatdrug($con)

  Else If sTable = "tblcompatfluid" Then
    modDBTables.CREATEtblcompatfluid($con)

  Else If sTable = "tbldilutionfluid" Then
    modDBTables.CREATEtbldilutionfluid($con)

  Else If sTable = "tblincompatdrug" Then
    modDBTables.CREATEtblincompatdrug($con)

  Else If sTable = "tblincompatfluid" Then
    modDBTables.CREATEtblincompatfluid($con)

  Else If sTable = "tblreconstfluid" Then
    modDBTables.CREATEtblreconstfluid($con)

  Else If sTable = "tbldosageforms" Then
    modDBTables.CREATEtbldosageforms($con)

  Else If sTable = "tblmanufacturer" Then
    modDBTables.CREATEtblmanufacturer($con)

  Else If sTable = "tblextradepartment" Then
    modDBTables.CREATEtblextradepartment($con)

  Else If sTable = "tbldrug" Then
    modDBTables.CREATEtbldrug($con)

  Else If sTable = "tblinjection" Then
    modDBTables.CREATEtblinjection($con)

  Else If sTable = "tbllabel" Then
    modDBTables.CREATEtbllabel($con)

  Else If sTable = "tblmedbrand" Then
    modDBTables.CREATEtblmedbrand($con)

  Else If sTable = "tblmedregimen" Then
    modDBTables.CREATEtblmedregimen($con)

  Else If sTable = "tblmedhepatic" Then
    modDBTables.CREATEtblmedhepatic($con)

  Else If sTable = "tblmedinteraction" Then
    modDBTables.CREATEtblmedinteraction($con)

  Else If sTable = "tblmedpregnancy" Then
    modDBTables.CREATEtblmedpregnancy($con)

  Else If sTable = "tblmedrenal" Then
    modDBTables.CREATEtblmedrenal($con)

  Else If sTable = "tblmedcontraindication" Then
    modDBTables.CREATEtblmedcontraindication($con)

  Else If sTable = "tblmedadveffect" Then
    modDBTables.CREATEtblmedadveffect($con)

  Else If sTable = "tblmedmonitor" Then
    modDBTables.CREATEtblmedmonitor($con)

  Else If sTable = "tblregimen" Then
    modDBTables.CREATEtblregimen($con)

  Else If sTable = "tbllocallabel" Then
    modDBTables.CREATEtbllocallabel($con)

  Else If sTable = "tblmedgroup" Then
    modDBTables.CREATEtblmedgroup($con)

  Else If sTable = "tblproductgroup" Then
    modDBTables.CREATEtblproductgroup($con)

  Else If sTable = "tblsurgicalname" Then
    modDBTables.CREATEtblsurgicalname($con)

  Else If sTable = "tblsuturetype" Then
    modDBTables.CREATEtblsuturetype($con)

  Else If sTable = "tblsurgicals" Then
    modDBTables.CREATEtblsurgicals($con)

  Else If sTable = "tblsurgbrand" Then
    modDBTables.CREATEtblsurgbrand($con)

  Else If sTable = "tblextra" Then
    modDBTables.CREATEtblextra($con)

  Else If sTable = "tblextrabrand" Then
    modDBTables.CREATEtblextrabrand($con)

  Else If sTable = "tblfoodlist" Then
    modDBTables.CREATEtblfoodlist($con)

  Else If sTable = "tblfoodtype" Then
    modDBTables.CREATEtblfoodtype($con)

  Else If sTable = "tblfoodcontent" Then
    modDBTables.CREATEtblfoodcontent($con)

  Else If sTable = "tblfoodmix" Then
    modDBTables.CREATEtblfoodmix($con)

  Else If sTable = "tblfoodgroup" Then
    modDBTables.CREATEtblfoodgroup($con)

  Else If sTable = "tbldietgroup" Then
    modDBTables.CREATEtbldietgroup($con)

  Else If sTable = "tblnutrition" Then
    modDBTables.CREATEtblnutrition($con)

  Else If sTable = "tblpathocategory" Then
    modDBTables.CREATEtblpathocategory($con)

  Else If sTable = "tblbodyfluid" Then
    modDBTables.CREATEtblbodyfluid($con)

  Else If sTable = "tblsurveillance" Then
    modDBTables.CREATEtblsurveillance($con)

  Else If sTable = "tblbilldisease" Then
    modDBTables.CREATEtblbilldisease($con)

  Else If sTable = "tblethnicgroup" Then
    modDBTables.CREATEtblethnicgroup($con)

  Else If sTable = "tbldiagnogroup" Then
    modDBTables.CREATEtbldiagnogroup($con)

  Else If sTable = "tblsymptoms" Then
    modDBTables.CREATEtblsymptoms($con)

  Else If sTable = "tblsubsymptoms" Then
    modDBTables.CREATEtblsubsymptoms($con)

  Else If sTable = "tblpathosymp" Then
    modDBTables.CREATEtblpathosymp($con)

  Else If sTable = "tblsyndromes" Then
    modDBTables.CREATEtblsyndromes($con)

  Else If sTable = "tblpathotest" Then
    modDBTables.CREATEtblpathotest($con)

  Else If sTable = "tblpathoexam" Then
    modDBTables.CREATEtblpathoexam($con)

  Else If sTable = "tbltriage" Then
    modDBTables.CREATEtbltriage($con)

  Else If sTable = "tblclinchart" Then
    modDBTables.CREATEtblclinchart($con)

  Else If sTable = "tblaiquery" Then
    modDBTables.CREATEtblaiquery($con)

  Else If sTable = "tblsysconst" Then
    modDBTables.CREATEtblsysconst($con)

  Else If sTable = "tblagegroups" Then
    modDBTables.CREATEtblagegroups($con)

  Else If sTable = "tbltestmethod" Then
    modDBTables.CREATEtbltestmethod($con)

  Else If sTable = "tblorganism" Then
    modDBTables.CREATEtblorganism($con)

  Else If sTable = "tblsampletype" Then
    modDBTables.CREATEtblsampletype($con)

  Else If sTable = "tbltestcondition" Then
    modDBTables.CREATEtbltestcondition($con)

  Else If sTable = "tbllabchemical" Then
    modDBTables.CREATEtbllabchemical($con)

  Else If sTable = "tbltestmachine" Then
    modDBTables.CREATEtbltestmachine($con)

  Else If sTable = "tblmachinemethod" Then
    modDBTables.CREATEtblmachinemethod($con)

  Else If sTable = "tbltest" Then
    modDBTables.CREATEtbltest($con)

  Else If sTable = "tbltestoption" Then
    modDBTables.CREATEtbltestoption($con)

  Else If sTable = "tbltestlimit" Then
    modDBTables.CREATEtbltestlimit($con)

  Else If sTable = "tbltestcomment" Then
    modDBTables.CREATEtbltestcomment($con)

  Else If sTable = "tblcodehypo" Then
    modDBTables.CREATEtblcodehypo($con)

  Else If sTable = "tblcodehyper" Then
    modDBTables.CREATEtblcodehyper($con)

  Else If sTable = "tblsyndrohypo" Then
    modDBTables.CREATEtblsyndrohypo($con)

  Else If sTable = "tblsyndrohyper" Then
    modDBTables.CREATEtblsyndrohyper($con)

  Else If sTable = "tbltestquali" Then
    modDBTables.CREATEtbltestquali($con)

  Else If sTable = "tblsubtestquali" Then
    modDBTables.CREATEtblsubtestquali($con)

  Else If sTable = "tblantipanel" Then
    modDBTables.CREATEtblantipanel($con)

  Else If sTable = "tblgrouptest" Then
    modDBTables.CREATEtblgrouptest($con)

  Else If sTable = "tblstructexam" Then
    modDBTables.CREATEtblstructexam($con)

  Else If sTable = "tblstructexamoption" Then
    modDBTables.CREATEtblstructexamoption($con)

  Else If sTable = "tblcompexam" Then
    modDBTables.CREATEtblcompexam($con)

  Else If sTable = "tblcomplaints" Then
    modDBTables.CREATEtblcomplaints($con)

  Else If sTable = "tbldeptexam" Then
    modDBTables.CREATEtbldeptexam($con)

  Else If sTable = "tbldeptexamoption" Then
    modDBTables.CREATEtbldeptexamoption($con)

  Else If sTable = "tblgroupexam" Then
    modDBTables.CREATEtblgroupexam($con)

  Else If sTable = "tblexam" Then
    modDBTables.CREATEtblexam($con)

  Else If sTable = "tblexamoption" Then
    modDBTables.CREATEtblexamoption($con)

  Else If sTable = "tblexamlimit" Then
    modDBTables.CREATEtblexamlimit($con)

  Else If sTable = "tblexamcomment" Then
    modDBTables.CREATEtblexamcomment($con)

  Else If sTable = "tblcodebrady" Then
    modDBTables.CREATEtblcodebrady($con)

  Else If sTable = "tblcodetachy" Then
    modDBTables.CREATEtblcodetachy($con)

  Else If sTable = "tblsyndrobrady" Then
    modDBTables.CREATEtblsyndrobrady($con)

  Else If sTable = "tblsyndrotachy" Then
    modDBTables.CREATEtblsyndrotachy($con)

  Else If sTable = "tblexamquali" Then
    modDBTables.CREATEtblexamquali($con)

  Else If sTable = "tblsubexamquali" Then
    modDBTables.CREATEtblsubexamquali($con)

  Else If sTable = "tblradio" Then
    modDBTables.CREATEtblradio($con)

  Else If sTable = "tblradiooption" Then
    modDBTables.CREATEtblradiooption($con)

  Else If sTable = "tblradiolimit" Then
    modDBTables.CREATEtblradiolimit($con)

  Else If sTable = "tblradiocomment" Then
    modDBTables.CREATEtblradiocomment($con)

  Else If sTable = "tblradioquali" Then
    modDBTables.CREATEtblradioquali($con)

  Else If sTable = "tblsubradioquali" Then
    modDBTables.CREATEtblsubradioquali($con)

  Else If sTable = "tblgroupradio" Then
    modDBTables.CREATEtblgroupradio($con)

  Else If sTable = "tblgroupproc" Then
    modDBTables.CREATEtblgroupproc($con)

  Else If sTable = "tblprocname" Then
    modDBTables.CREATEtblprocname($con)

  Else If sTable = "tbldemographic" Then
    modDBTables.CREATEtbldemographic($con)

  Else If sTable = "tbldemogoption" Then
    modDBTables.CREATEtbldemogoption($con)

  Else If sTable = "tblreferlist" Then
    modDBTables.CREATEtblreferlist($con)

  Else If sTable = "tbldischarge" Then
    modDBTables.CREATEtbldischarge($con)

  Else If sTable = "tblhistory" Then
    modDBTables.CREATEtblhistory($con)

  Else If sTable = "tbldelivery" Then
    modDBTables.CREATEtbldelivery($con)

  Else If sTable = "tbldelcomplication" Then
    modDBTables.CREATEtbldelcomplication($con)

  Else If sTable = "tbldeldeformity" Then
    modDBTables.CREATEtbldeldeformity($con)

  Else If sTable = "tbldellabour" Then
    modDBTables.CREATEtbldellabour($con)

  Else If sTable = "tblprocedure" Then
    modDBTables.CREATEtblprocedure($con)

  Else If sTable = "tblprocedureuser" Then
    modDBTables.CREATEtblprocedureuser($con)

  Else If sTable = "tblchecklist" Then
    modDBTables.CREATEtblchecklist($con)

  Else If sTable = "tblanaesthesia" Then
    modDBTables.CREATEtblanaesthesia($con)

  Else If sTable = "tblevents" Then
    modDBTables.CREATEtblevents($con)

  Else If sTable = "tbldevices" Then
    modDBTables.CREATEtbldevices($con)

  Else If sTable = "tblrepomapping" Then
    modDBTables.CREATEtblrepomapping($con)

  Else If sTable = "tblmedimage" Then
    modDBTables.CREATEtblmedimage($con)

  Else If sTable = "tblelectrolyte" Then
    modDBTables.CREATEtblelectrolyte($con)

  Else If sTable = "tblresearch" Then
    modDBTables.CREATEtblresearch($con)

  Else If sTable = "tblautoid" Then
    modDBTables.CREATEtblautoid($con)

  Else If sTable = "tblinvid" Then
    modDBTables.CREATEtblinvid($con)

  Else If sTable = "tblpatsubs" Then
    modDBTables.CREATEtblpatsubs($con)

  Else If sTable = "tbllock" Then
    modDBTables.CREATEtbllock($con)

  Else If sTable = "tblfiscalid" Then
    modDBTables.CREATEtblfiscalid($con)

  Else If sTable = "tblfisclosing" Then
    modDBTables.CREATEtblfisclosing($con)

  Else If sTable = "tblenclock" Then
    modDBTables.CREATEtblenclock($con)

  Else If sTable = "tbldiagnoid" Then
    modDBTables.CREATEtbldiagnoid($con)

  Else If sTable = "tbltabsettings" Then
    modDBTables.CREATEtbltabsettings($con)

  Else If sTable = "tblsettings" Then
    modDBTables.CREATEtblsettings($con)

  Else If sTable = "tblhmissetting" Then
    modDBTables.CREATEtblhmissetting($con)

  Else If sTable = "tblgnupg" Then
    modDBTables.CREATEtblgnupg($con)

  Else If sTable = "tblautoemail" Then
    modDBTables.CREATEtblautoemail($con)

  Else If sTable = "tblcronjob" Then
    modDBTables.CREATEtblcronjob($con)

  Else If sTable = "tbljobrecord" Then
    modDBTables.CREATEtbljobrecord($con)

  Else If sTable = "tblmessage" Then
    modDBTables.CREATEtblmessage($con)

  Else If sTable = "tblirdactivity" Then
    modDBTables.CREATEtblirdactivity($con)

  Else If sTable = "tblactivity" Then
    modDBTables.CREATEtblactivity($con)

  Else If sTable = "tblsystemlog" Then
    modDBTables.CREATEtblsystemlog($con)

  Else If sTable = "tblauthenticate" Then
    modDBTables.CREATEtblauthenticate($con)

  Else If sTable = "tblreposync" Then
    modDBTables.CREATEtblreposync($con)

  Else If sTable = "tblreportlog" Then
    modDBTables.CREATEtblreportlog($con)

  Else If sTable = "tblsmslog" Then
    modDBTables.CREATEtblsmslog($con)

  Else If sTable = "tblmessagelog" Then
    modDBTables.CREATEtblmessagelog($con)

  Else If sTable = "tblstafflist" Then
    modDBTables.CREATEtblstafflist($con)

  Else If sTable = "tblsociallist" Then
    modDBTables.CREATEtblsociallist($con)

  Else If sTable = "tbluser" Then
    modDBTables.CREATEtbluser($con)

  Else If sTable = "tblusercategory" Then
    modDBTables.CREATEtblusercategory($con)

  Else If sTable = "tblmiscategory" Then
    modDBTables.CREATEtblmiscategory($con)

  Else If sTable = "tbluserimage" Then
    modDBTables.CREATEtbluserimage($con)

  Else If sTable = "tblreportuser" Then
    modDBTables.CREATEtblreportuser($con)

  Else If sTable = "tblkey" Then
    modDBTables.CREATEtblkey($con)

  Else If sTable = "tblnewkey" Then
    modDBTables.CREATEtblnewkey($con)

  Else If sTable = "tbluseraccess" Then
    modDBTables.CREATEtbluseraccess($con)

  Else If sTable = "tblcompaccess" Then
    modDBTables.CREATEtblcompaccess($con)

  Else If sTable = "tblmacaccess" Then
    modDBTables.CREATEtblmacaccess($con)

  Else If sTable = "tbluserformaccess" Then
    modDBTables.CREATEtbluserformaccess($con)

  Else If sTable = "tblclinicentry" Then
    modDBTables.CREATEtblclinicentry($con)

  Else If sTable = "tblpersonal" Then
    modDBTables.CREATEtblpersonal($con)

  Else If sTable = "tblfileshare" Then
    modDBTables.CREATEtblfileshare($con)

  Else If sTable = "tblsurname" Then
    modDBTables.CREATEtblsurname($con)

  Else If sTable = "tblhospitals" Then
    modDBTables.CREATEtblhospitals($con)

  Else If sTable = "tblmunicipals" Then
    modDBTables.CREATEtblmunicipals($con)

  Else If sTable = "tblrelations" Then
    modDBTables.CREATEtblrelations($con)

  Else If sTable = "tblranks" Then
    modDBTables.CREATEtblranks($con)

  Else If sTable = "tblunits" Then
    modDBTables.CREATEtblunits($con)

  Else If sTable = "tblipdservice" Then
    modDBTables.CREATEtblipdservice($con)

  Else If sTable = "tblhospbranch" Then
    modDBTables.CREATEtblhospbranch($con)

  Else If sTable = "tbldepartment" Then
    modDBTables.CREATEtbldepartment($con)

  Else If sTable = "tbldeptgroup" Then
    modDBTables.CREATEtbldeptgroup($con)

  Else If sTable = "tbldepartmentbed" Then
    modDBTables.CREATEtbldepartmentbed($con)

  Else If sTable = "tbldepartbedcharge" Then
    modDBTables.CREATEtbldepartbedcharge($con)

  Else If sTable = "tblacledger" Then
    modDBTables.CREATEtblacledger($con)

  Else If sTable = "tblcategorylist" Then
    modDBTables.CREATEtblcategorylist($con)

  Else If sTable = "tblschemecategory" Then
    modDBTables.CREATEtblschemecategory($con)

  Else If sTable = "tbldiscount" Then
    modDBTables.CREATEtbldiscount($con)

  Else If sTable = "tblforcediscount" Then
    modDBTables.CREATEtblforcediscount($con)

  Else If sTable = "tblnodiscount" Then
    modDBTables.CREATEtblnodiscount($con)

  Else If sTable = "tbllockedservice" Then
    modDBTables.CREATEtbllockedservice($con)

  Else If sTable = "tblcustdiscount" Then
    modDBTables.CREATEtblcustdiscount($con)

  Else If sTable = "tblcustquantity" Then
    modDBTables.CREATEtblcustquantity($con)

  Else If sTable = "tblcustcredit" Then
    modDBTables.CREATEtblcustcredit($con)

  Else If sTable = "tblpackgroup" Then
    modDBTables.CREATEtblpackgroup($con)

  Else If sTable = "tblaccdemograp" Then
    modDBTables.CREATEtblaccdemograp($con)

  Else If sTable = "tblaccdemogoption" Then
    modDBTables.CREATEtblaccdemogoption($con)

  Else If sTable = "tblbillingset" Then
    modDBTables.CREATEtblbillingset($con)

  Else If sTable = "tblpackschedule" Then
    modDBTables.CREATEtblpackschedule($con)

  Else If sTable = "tblbillitem" Then
    modDBTables.CREATEtblbillitem($con)

  Else If sTable = "tblbillsection" Then
    modDBTables.CREATEtblbillsection($con)

  Else If sTable = "tblcurrency" Then
    modDBTables.CREATEtblcurrency($con)

  Else If sTable = "tblservicecheck" Then
    modDBTables.CREATEtblservicecheck($con)

  Else If sTable = "tblservicecost" Then
    modDBTables.CREATEtblservicecost($con)

  Else If sTable = "tblreportgroup" Then
    modDBTables.CREATEtblreportgroup($con)

  Else If sTable = "tblmasterdept" Then
    modDBTables.CREATEtblmasterdept($con)

  Else If sTable = "tblcostgroup" Then
    modDBTables.CREATEtblcostgroup($con)

  Else If sTable = "tblextrasetting" Then
    modDBTables.CREATEtblextrasetting($con)

  Else If sTable = "tbldepconsult" Then
    modDBTables.CREATEtbldepconsult($con)

  Else If sTable = "tblprocedureshare" Then
    modDBTables.CREATEtblprocedureshare($con)

  Else If sTable = "tblusershare" Then
    modDBTables.CREATEtblusershare($con)

  Else If sTable = "tbluserpay" Then
    modDBTables.CREATEtbluserpay($con)

  Else If sTable = "tblservicegroup" Then
    modDBTables.CREATEtblservicegroup($con)

  Else If sTable = "tblcostbreak" Then
    modDBTables.CREATEtblcostbreak($con)

  Else If sTable = "tblautogroup" Then
    modDBTables.CREATEtblautogroup($con)

  Else If sTable = "tblfoodorder" Then
    modDBTables.CREATEtblfoodorder($con)

  Else If sTable = "tbltaxgroup" Then
    modDBTables.CREATEtbltaxgroup($con)

  Else If sTable = "tbldiscgroup" Then
    modDBTables.CREATEtbldiscgroup($con)

  Else If sTable = "tblcashvendor" Then
    modDBTables.CREATEtblcashvendor($con)

  Else If sTable = "tbljournal" Then
    modDBTables.CREATEtbljournal($con)

  Else If sTable = "tblextrapayers" Then
    modDBTables.CREATEtblextrapayers($con)

  Else If sTable = "tblextrapayitems" Then
    modDBTables.CREATEtblextrapayitems($con)

  Else If sTable = "tblextrareceipt" Then
    modDBTables.CREATEtblextrareceipt($con)

  Else If sTable = "tblassetsname" Then
    modDBTables.CREATEtblassetsname($con)

  Else If sTable = "tblassetsentry" Then
    modDBTables.CREATEtblassetsentry($con)

  Else If sTable = "tblentry" Then
    modDBTables.CREATEtblentry($con)

  Else If sTable = "tblentrybackup" Then
    modDBTables.CREATEtblentrybackup($con)

  Else If sTable = "tblstockrate" Then
    modDBTables.CREATEtblstockrate($con)

  Else If sTable = "tbladjustment" Then
    modDBTables.CREATEtbladjustment($con)

  Else If sTable = "tblpurchase" Then
    modDBTables.CREATEtblpurchase($con)

  Else If sTable = "tblpurchasebill" Then
    modDBTables.CREATEtblpurchasebill($con)

  Else If sTable = "tblstockreturn" Then
    modDBTables.CREATEtblstockreturn($con)

  Else If sTable = "tblsupplier" Then
    modDBTables.CREATEtblsupplier($con)

  Else If sTable = "tbltenderlist" Then
    modDBTables.CREATEtbltenderlist($con)

  Else If sTable = "tblpayment" Then
    modDBTables.CREATEtblpayment($con)

  Else If sTable = "tbltransfer" Then
    modDBTables.CREATEtbltransfer($con)

  Else If sTable = "tblpurorder" Then
    modDBTables.CREATEtblpurorder($con)

  Else If sTable = "tblrequest" Then
    modDBTables.CREATEtblrequest($con)

  Else If sTable = "tbltarget" Then
    modDBTables.CREATEtbltarget($con)

  Else If sTable = "tblbulksale" Then
    modDBTables.CREATEtblbulksale($con)

  Else If sTable = "tblmedinventory" Then
    modDBTables.CREATEtblmedinventory($con)

  Else If sTable = "tbltelemeduser" Then
    modDBTables.CREATEtbltelemeduser($con)

  Else If sTable = "tbltelemedtalk" Then
    modDBTables.CREATEtbltelemedtalk($con)

  Else If sTable = "tblcurrteleuser" Then
    modDBTables.CREATEtblcurrteleuser($con)

  Else If sTable = "tblpatientbook" Then
    modDBTables.CREATEtblpatientbook($con)

  Else If sTable = "tblonlinebook" Then
    modDBTables.CREATEtblonlinebook($con)

  Else If sTable = "tblpatientinfo" Then
    modDBTables.CREATEtblpatientinfo($con)

  Else If sTable = "tblencounter" Then
    modDBTables.CREATEtblencounter($con)

  Else If sTable = "tblabsconder" Then
    modDBTables.CREATEtblabsconder($con)

  Else If sTable = "tblcreditlimit" Then
    modDBTables.CREATEtblcreditlimit($con)

  Else If sTable = "tblclaimcode" Then
    modDBTables.CREATEtblclaimcode($con)

  Else If sTable = "tblssfclaim" Then
    modDBTables.CREATEtblssfclaim($con)

  Else If sTable = "tblpataccgeneral" Then
    modDBTables.CREATEtblpataccgeneral($con)

  Else If sTable = "tblpatdevice" Then
    modDBTables.CREATEtblpatdevice($con)

  Else If sTable = "tblpatientdate" Then
    modDBTables.CREATEtblpatientdate($con)

  Else If sTable = "tblpatientexam" Then
    modDBTables.CREATEtblpatientexam($con)

  Else If sTable = "tblpatientsubexam" Then
    modDBTables.CREATEtblpatientsubexam($con)

  Else If sTable = "tblpatexamsubtable" Then
    modDBTables.CREATEtblpatexamsubtable($con)

  Else If sTable = "tblpatlabtest" Then
    modDBTables.CREATEtblpatlabtest($con)

  Else If sTable = "tblpatlabsubtest" Then
    modDBTables.CREATEtblpatlabsubtest($con)

  Else If sTable = "tblpatlabsubtable" Then
    modDBTables.CREATEtblpatlabsubtable($con)

  Else If sTable = "tblpatfindings" Then
    modDBTables.CREATEtblpatfindings($con)

  Else If sTable = "tblexamgeneral" Then
    modDBTables.CREATEtblexamgeneral($con)

  Else If sTable = "tblpatgeneral" Then
    modDBTables.CREATEtblpatgeneral($con)

  Else If sTable = "tblpatsubgeneral" Then
    modDBTables.CREATEtblpatsubgeneral($con)

  Else If sTable = "tblpatgenshare" Then
    modDBTables.CREATEtblpatgenshare($con)

  Else If sTable = "tblsharepayment" Then
    modDBTables.CREATEtblsharepayment($con)

  Else If sTable = "tblpatplanning" Then
    modDBTables.CREATEtblpatplanning($con)

  Else If sTable = "tblpatevents" Then
    modDBTables.CREATEtblpatevents($con)

  Else If sTable = "tblpattiming" Then
    modDBTables.CREATEtblpattiming($con)

  Else If sTable = "tblconsult" Then
    modDBTables.CREATEtblconsult($con)

  Else If sTable = "tblopvisit" Then
    modDBTables.CREATEtblopvisit($con)

  Else If sTable = "tblgenviolence" Then
    modDBTables.CREATEtblgenviolence($con)

  Else If sTable = "tblobstetrics" Then
    modDBTables.CREATEtblobstetrics($con)

  Else If sTable = "tblconfinement" Then
    modDBTables.CREATEtblconfinement($con)

  Else If sTable = "tblpatradiotest" Then
    modDBTables.CREATEtblpatradiotest($con)

  Else If sTable = "tblpatradiosubtest" Then
    modDBTables.CREATEtblpatradiosubtest($con)

  Else If sTable = "tblpatradiosubtable" Then
    modDBTables.CREATEtblpatradiosubtable($con)

  Else If sTable = "tblradiocounter" Then
    modDBTables.CREATEtblradiocounter($con)

  Else If sTable = "tblsurgerysection" Then
    modDBTables.CREATEtblsurgerysection($con)

  Else If sTable = "tbltelradiotest" Then
    modDBTables.CREATEtbltelradiotest($con)

  Else If sTable = "tbltelradiosubtest" Then
    modDBTables.CREATEtbltelradiosubtest($con)

  Else If sTable = "tblmonitor" Then
    modDBTables.CREATEtblmonitor($con)

  Else If sTable = "tblextradosing" Then
    modDBTables.CREATEtblextradosing($con)

  Else If sTable = "tblusercollection" Then
    modDBTables.CREATEtblusercollection($con)

  Else If sTable = "tblpatcharity" Then
    modDBTables.CREATEtblpatcharity($con)

  Else If sTable = "tblfiscal" Then
    modDBTables.CREATEtblfiscal($con)

  Else If sTable = "tblduebilling" Then
    modDBTables.CREATEtblduebilling($con)

  Else If sTable = "tblpatbilling" Then
    modDBTables.CREATEtblpatbilling($con)

  Else If sTable = "tblpatbilldetail" Then
    modDBTables.CREATEtblpatbilldetail($con)

  Else If sTable = "tbltempbilldetail" Then
    modDBTables.CREATEtbltempbilldetail($con)

  Else If sTable = "tblduebilldetail" Then
    modDBTables.CREATEtblduebilldetail($con)

  Else If sTable = "tbladvreceiptdetail" Then
    modDBTables.CREATEtbladvreceiptdetail($con)

  Else If sTable = "tblcashsources" Then
    modDBTables.CREATEtblcashsources($con)

  Else If sTable = "tblwebpayment" Then
    modDBTables.CREATEtblwebpayment($con)

  Else If sTable = "tblpatusershares" Then
    modDBTables.CREATEtblpatusershares($con)

  Else If sTable = "tblpatbillcounts" Then
    modDBTables.CREATEtblpatbillcounts($con)

  Else If sTable = "tblpatbillbooking" Then
    modDBTables.CREATEtblpatbillbooking($con)

  Else If sTable = "tblpatmeditem" Then
    modDBTables.CREATEtblpatmeditem($con)

  Else If sTable = "tbldrugproblems" Then
    modDBTables.CREATEtbldrugproblems($con)

  Else If sTable = "tblpatdosing" Then
    modDBTables.CREATEtblpatdosing($con)

  Else If sTable = "tblpatoutdosing" Then
    modDBTables.CREATEtblpatoutdosing($con)

  Else If sTable = "tblpatdoseremote" Then
    modDBTables.CREATEtblpatdoseremote($con)

  Else If sTable = "tbltaperdose" Then
    modDBTables.CREATEtbltaperdose($con)

  Else If sTable = "tblnurdosing" Then
    modDBTables.CREATEtblnurdosing($con)

  Else If sTable = "tblvaccdosing" Then
    modDBTables.CREATEtblvaccdosing($con)

  Else If sTable = "tblpayimage" Then
    modDBTables.CREATEtblpayimage($con)

  Else If sTable = "tblpersonimage" Then
    modDBTables.CREATEtblpersonimage($con)

  Else If sTable = "tblpatimagedata" Then
    modDBTables.CREATEtblpatimagedata($con)

  Else If sTable = "tblpatserialimage" Then
    modDBTables.CREATEtblpatserialimage($con)

  Else If sTable = "tblpatreport" Then
    modDBTables.CREATEtblpatreport($con)

  Else If sTable = "tblbillupload" Then
    modDBTables.CREATEtblbillupload($con)

  Else If sTable = "tblbillrepoload" Then
    modDBTables.CREATEtblbillrepoload($con)

  Else If sTable = "tblofficedocs" Then
    modDBTables.CREATEtblofficedocs($con)

  Else If sTable = "tblpatientstudy" Then
    modDBTables.CREATEtblpatientstudy($con)

  Else If sTable = "tblpatientpass" Then
    modDBTables.CREATEtblpatientpass($con)

  Else If sTable = "tblremotefollow" Then
    modDBTables.CREATEtblremotefollow($con)

  Else If sTable = "tblremoteusers" Then
    modDBTables.CREATEtblremoteusers($con)

  Else If sTable = "tblpacsupload" Then
    modDBTables.CREATEtblpacsupload($con)

    ''for Ayurveda only
  Else If sTable = "tblamissetting" Then
    modDBTables.CREATEtblamissetting($con)

  Endif

End

Public Sub CreateLogTable(sConn As Connection, sTab As String)

  If sTab = "tblpatbilling" Then
    modDBGroup.CreateLogTableTrigger(sConn, "tblpatbilling", "tblpatbilling_log")
  Else If sTab = "tblduebilling" Then
    modDBGroup.CreateLogTableTrigger(sConn, "tblduebilling", "tblduebilling_log")
  Else If sTab = "tblpatbilldetail" Then
    modDBGroup.CreateLogTableTrigger(sConn, "tblpatbilldetail", "tblpatbilldetail_log")
  Else If sTab = "tbltempbilldetail" Then
    modDBGroup.CreateLogTableTrigger(sConn, "tbltempbilldetail", "tbltempbilldetail_log")
  Else If sTab = "tblpurchase" Then
    modDBGroup.CreateLogTableTrigger(sConn, "tblpurchase", "tblpurchase_log")
  Else If sTab = "tblpurchasebill" Then
    modDBGroup.CreateLogTableTrigger(sConn, "tblpurchasebill", "tblpurchasebill_log")
  Else If sTab = "tblbulksale" Then
    modDBGroup.CreateLogTableTrigger(sConn, "tblbulksale", "tblbulksale_log")
  Else If sTab = "tblextrareceipt" Then
    modDBGroup.CreateLogTableTrigger(sConn, "tblextrareceipt", "tblextrareceipt_log")
  Else If sTab = "tblservicecost" Then
    modDBGroup.CreateLogTableTrigger(sConn, "tblservicecost", "tblservicecost_log")
  Else If sTab = "tblassetsentry" Then
    modDBGroup.CreateLogTableTrigger(sConn, "tblassetsentry", "tblassetsentry_log")
  Else If sTab = "tblpatientinfo" Then
    modDBGroup.CreateLogTableTrigger(sConn, "tblpatientinfo", "tblpatientinfo_log")
  Else If sTab = "tblencounter" Then
    modDBGroup.CreateLogTableTrigger(sConn, "tblencounter", "tblencounter_log")
  Else
    modDBGroup.CreateLogTableTrigger(sConn, sTab, sTab & "_log")
  Endif

End

Public Function GetBackTableName(sTab As String) As String

  Dim xx As String

  If sTab = "tblpatbilling" Then
    xx = "tblpatbilling_log"
  Else If sTab = "tblduebilling" Then
    xx = "tblduebilling_log"
  Else If sTab = "tblpatbilldetail" Then
    xx = "tblpatbilldetail_log"
  Else If sTab = "tbltempbilldetail" Then
    xx = "tbltempbilldetail_log"
  Else If sTab = "tblpurchase" Then
    xx = "tblpurchase_log"
  Else If sTab = "tblpurchasebill" Then
    xx = "tblpurchasebill_log"
  Else If sTab = "tblbulksale" Then
    xx = "tblbulksale_log"
  Else If sTab = "tblextrareceipt" Then
    xx = "tblextrareceipt_log"
  Else If sTab = "tblservicecost" Then
    xx = "tblservicecost_log"
  Else If sTab = "tblassetsentry" Then
    xx = "tblassetsentry_log"
  Else If sTab = "tblpatientinfo" Then
    xx = "tblpatientinfo_log"
  Else If sTab = "tblencounter" Then
    xx = "tblencounter_log"
  Else
    xx = sTab & "_log"
  Endif

  Return xx

End

Public Sub CreateLogTableTrigger($con As Connection, sMainTable As String, sLogTable As String)

  Dim hTable As Table
  Dim aTable As Table
  Dim aField As Field

  If Not $con.Tables.Exist(sLogTable) Then
    hTable = $con.Tables.Add(sLogTable)
    hTable.Fields.Add("fldsno", db.Serial)

    For Each aTable In $con.Tables
      If aTable.Name = sMainTable Then
        For Each aField In aTable.Fields
          If aField.Type = db.Serial Then
            hTable.Fields.Add(aField.Name, db.Long, aField.Length)
          Else
            hTable.Fields.Add(aField.Name, aField.Type, aField.Length)
          Endif
        Next
      Endif
    Next

    hTable.Fields.Add("fldcurrtime", db.Date)
    hTable.PrimaryKey = ["fldsno"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End
