' Gambas module file

Public $PortalMode As String
Public $PortalReport As String
Public $PortalConnect As String
Public $PortalTelemed As String
Public $PortalBooking As String
Public $PortalBilling As String

Public $PortalHistoryFindings As String
Public $PortalHistoryClinic As String

Public $PaymentClient As String ''= "screenshot","Khalti","fonepay","Chanakya"
Public $PaymentReferred As String

Public Sub SetPaymentParams()

  Dim xclient As String

  xclient = modSettings.ShowSettingFromFIle("Payment/Client")
  If xclient Then
    $PaymentClient = xclient
  Else
    $PaymentClient = "screenshot"
  Endif

End
