' Gambas module file

Public $PortalMode As String
Public $PortalComponents As String[]
' Public $PortalHistoryFindings As String
' Public $PortalHistoryClinic As String

Public $PaymentClient As String ''= "screenshot","Khalti","fonepay","Chanakya"
Public $PaymentReferred As String

Public Sub SetPaymentParams()

  Dim xclient As String

  xclient = modSettings.ShowSettingFromFIle("Payment/Client")
  If xclient Then
    $PaymentClient = xclient
  Else
    $PaymentClient = "screenshot"
  Endif

End
