' Gambas module file

Public $AyurvedicDiagnosis As String

Public Function GetAyurDiseaseName(sPath As String, sCode As String) As String

  Dim hFile As File
  Dim sLine As String
  Dim asx As String[]
  Dim xx As String

  hFile = Open sPath
  modBasic.DebugString("Open File " & sPath)
  For Each sLine In hFile.Lines
    asx = Split(sLine, ";")
    If Trim(asx[0]) = sCode Then
      xx = Trim(asx[1])
    Endif
  Next
  hFile.Close()

  Return xx

End

Public Function GetAyurDiseaseCode(sPath As String, sName As String) As String

  Dim hFile As File
  Dim sLine As String
  Dim asx As String[]
  Dim xx As String

  hFile = Open sPath
  modBasic.DebugString("Open File " & sPath)
  For Each sLine In hFile.Lines
    asx = Split(sLine, ";")
    If Trim(asx[1]) = sName Then
      xx = Trim(asx[0])
    Endif
  Next
  hFile.Close()

  Return xx

End

Public Function GetDiagnoGroupList(sPath As String) As String[]

  Dim hFile As File
  Dim sLine As String
  Dim asx As String[]
  Dim xx As String[]

  xx = New String[]
  hFile = Open sPath
  modBasic.DebugString("Open File " & sPath)
  For Each sLine In hFile.Lines
    asx = Split(sLine, ";")
    If Trim(asx[3]) = "AB" Then
      xx.Add(Trim(asx[1]))
    Endif
  Next
  hFile.Close()

  Return xx

End

Public Function GetDiagnosisName(sPath As String, sItem As String) As String[]

  Dim hFile As File
  Dim sLine As String
  Dim asx As String[]
  Dim xx As String[]
  Dim xbool As Boolean

  xx = New String[]
  hFile = Open sPath
  modBasic.DebugString("Open File " & sPath)
  For Each sLine In hFile.Lines
    asx = Split(sLine, ";")
    If Trim(asx[1]) = sItem And If Trim(asx[3]) = "AB" Then
      xbool = True
    Else If Trim(asx[3]) = "AB" Then
      xbool = False
    Endif

    If xbool = True Then
      If Trim(asx[1]) = sItem And If Trim(asx[3]) = "AB" Then
      Else
        xx.Add(Trim(asx[1]))
      Endif
    Endif

  Next
  hFile.Close()

  Return xx

End
