' Gambas module file

Public $RemoteUserFormat As String = "email" ''/"phone"
Public $UserRemote As String
Public $DefBillMode As String = "General"
Public $DefPackage As String = "General"
Public $DefDemographic As String = "Clinical"

Public $RemotePatPortal As String
Public $RemoteBooking As String
Public $RemoteRegistration As String
Public $RemoteDemographic As String
Public $RemotePaImage As String
Public $RemoteDocuments As String

Public Function GetPatNameFromEmail(semail As String) As String

  Dim res As Result
  Dim xname As String

  res = modDatabase.$myConn.Exec("select fldptnamefir,fldptnamelast from tblremoteusers where fldusrcode=&1", semail)
  If res.Available Then
    xname = res["fldptnamefir"] & Space(1) & res["fldptnamelast"]
  Else
    xname = ""
  Endif
  Return xname

End
