' Gambas module file

Public $LeftAdPathLink As String
Public $RightAdPathLink As String

Public $advCon As Connection
Public AdvertiseId As Long
Public LABEL_CAPTION As String
Public $adLink As String

Private $AdvArray As String[]
Private $AdvLink As String[]

Public Sub ConnectAdLocalDB()

  Dim sPath As String

  sPath = modHelpVariable.AppDirectory &/ "advertise"
  modDBApp.CreateSQliteDB(sPath)
  $advCon = modDBApp.OpenConnection("sqlite3", File.Dir(sPath), File.Name(sPath), "", "")
  If $advCon.Opened = True Then
    modBasic.DebugString("App connected to local sqlite database")
  Endif
  CreateAdvertiseDB()

End

Public Sub CreateAdvertiseDB()

  modDBExternal.CREATEtbladvertise($advCon)
  modDBExternal.CREATEtbladlinks($advCon)

End

Public Sub DownLoadAdvertise()

  Dim sql As String
  Dim res As Result
  Dim xTxt As String
  Dim xURL As String

  xTxt = "This  is  Hospital Information System developed by D Code Technology, Kathmandu"
  xURL = "https://bitnepal.safiur.com.np/healthybit/"

  AdvertiseId = 0
  sql = "select advid,advcontent,advlink from tbladvertise where advdepartment=&1 and advdate=&2"
  res = $advCon.Exec(sql, modHelpVariable.$LogInGroup, Format(Now(), "yyyymmdd"))
  $AdvArray = New String[]
  $AdvLink = New String[]

  $AdvArray.Add(xTxt)
  $AdvLink.Add(xURL)

  If res.Count Then
    For Each res
      $AdvArray.Add(res["advcontent"])
      $AdvLink.Add(UnBase64(res["advlink"]))
    Next
  Else
    $AdvArray.Add(xTxt)
    $AdvLink.Add(xURL)
  Endif

End

Public Sub GetAdvertise()

  Dim xx As Integer

  xx = AdvertiseId + 1
  LABEL_CAPTION = " * * * * *  " & $AdvArray[xx] & "  * * * * * "
  $adLink = $AdvLink[xx]
  AdvertiseId = xx

Catch
  ErrorAdvertise()

End

Private Sub ErrorAdvertise()

  DownLoadAdvertise()
  GetAdvertise()

Catch
  modBasic.DebugString(Error.Text)

End

Public Sub GetSideAdvImage()

  Dim res1 As Result
  Dim res2 As Result

  res1 = $advCon.Exec("select advlink from tbladlinks where advdepartment=&1 and advposition=&2 and advdate=&3", modHelpVariable.$LogInCategory, "Left", Format(Now(), "yyyymmdd"))
  If res1.Available Then
    res1.MoveLast
    If res1["advlink"] Then
      $LeftAdPathLink = UnBase64(res1["advlink"])
    Endif
  Endif

  res2 = $advCon.Exec("select advlink from tbladlinks where advdepartment=&1 and advposition=&2 and advdate=&3", modHelpVariable.$LogInCategory, "Right", Format(Now(), "yyyymmdd"))
  If res2.Available Then
    res2.MoveLast
    If res2["advlink"] Then
      $RightAdPathLink = UnBase64(res2["advlink"])
    Endif
  Endif

End
