' Gambas module file

Public $patReportColl As Collection

Private Function AddCustomReport(stChapter As String, stObservation As String) As String[]

  Dim asx As New String[0]

  If Len(Trim(stObservation)) Then
    With asx
      If modBasic.$MedRepoBody = "Paragraph" Then
        .Add("<b>" & stChapter & "</b><br>" & modString.TextToHTML(stObservation))
      Else
        .Add(stChapter)
        .Add(modString.TextToHTML(stObservation))
      Endif
    End With
  Endif

  Return asx

End

''======================= Reports ===========================
Public Function ShowAllCompleteReport(encid As String, strUnit As String) As String

  Dim $BillingReport As CReportHTML
  Dim hForm As CPatReportAll
  Dim xdelivery As String[]

  $BillingReport = New CReportHTML([("Category"), ("Observations")], "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("COMPLETE REPORT", "PARAM1")

  hForm = New CPatReportAll(encid)
  $BillingReport.AddSection("General", True)
  $BillingReport.Add(hForm.AddCourseOfTreatment())
  $BillingReport.Add(hForm.AddPatDemographics())
  $BillingReport.Add(hForm.AddBedTransition())
  $BillingReport.Add(hForm.AddCauseofAdmission())
  $BillingReport.Add(hForm.AddChiefComplaints())
  $BillingReport.Add(hForm.AddHistoryAllTypes())
  $BillingReport.Add(hForm.AddConsultationAll())
  $BillingReport.Add(hForm.AddDrugAllergy())
  $BillingReport.Add(hForm.AddProvisionalDiagnosis())
  $BillingReport.Add(hForm.AddFinalDiagnosis())
  $BillingReport.Add(hForm.AddTreatmentAdvised())
  $BillingReport.Add(hForm.AddOutpatientAdvice())
  $BillingReport.Add(hForm.AddOrderForNewVisit())
  $BillingReport.Add(hForm.AddPlannedProcedures())
  $BillingReport.Add(hForm.AddUnavailableMeds())

  $BillingReport.AddSection("Investigations", True)
  $BillingReport.Add(hForm.AddExaminationsAll())
  $BillingReport.Add(hForm.AddStructuredExamAll())
  $BillingReport.Add(hForm.AddLaboratoryTests(strUnit))
  $BillingReport.Add(hForm.AddRadioFindings())

  $BillingReport.AddSection("Services Provided", True)
  $BillingReport.Add(hForm.AddMajorProcedures())
  $BillingReport.Add(hForm.AddMinorProcedures())
  $BillingReport.Add(hForm.AddEquipmentsUsed())
  $BillingReport.Add(hForm.AddEventProfile())
  $BillingReport.Add(hForm.AddDevicesUsed())
  ' $BillingReport.Add(hForm.AddMedicationUsed())
  $BillingReport.Add(hForm.AddVaccinesUsed())
  $BillingReport.Add(hForm.AddNutritionUsed())
  xdelivery = modPatReports.DeliveryReportbyMother()
  If xdelivery Then
    $BillingReport.Add(AddCustomReport("Delivery Profile", xdelivery.Join(gb.NewLine)))
  Endif

  $BillingReport.AddSection("Inpatient Records", True)
  $BillingReport.Add(hForm.AddInpatientNotes())
  $BillingReport.Add(hForm.AddTherapeuticPlanning())
  $BillingReport.Add(hForm.AddIPMonitoring())

  If modPatient.CurrentAdmissionStatus(encid) = "Discharged" Then
    $BillingReport.AddSection("Discharge", True)
    $BillingReport.Add(hForm.AddDischargeNotes())
    $BillingReport.Add(hForm.AddDischargeMedication())
  Endif

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowCompleteReport(encid As String, xList As String[], strUnit As String, HTMLOnly As Boolean, Optional sColl As Collection) As String

  Dim $BillingReport As CReportHTML
  Dim hForm As CPatReportAll
  Dim xstate As String
  Dim xxx As String

  If modBasic.$MedRepoBody = "Paragraph" Then
    $BillingReport = New CReportHTML([("Description")], "PatientReport", encid)
  Else
    $BillingReport = New CReportHTML([("Category"), ("Observations")], "PatientReport", encid)
  Endif
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("SELECTED PARAMETERS", "PARAM1")

  hForm = New CPatReportAll(encid)
  If xList.Exist("Course of Treatment") Then
    $BillingReport.Add(hForm.AddCourseOfTreatment())
  Endif
  If xList.Exist("Demographics") Then
    $BillingReport.Add(hForm.AddPatDemographics())
  Endif
  If xList.Exist("Bed Transitions") Then
    $BillingReport.Add(hForm.AddBedTransition())
  Endif
  If xList.Exist("Cause of Admission") Then
    $BillingReport.Add(hForm.AddCauseofAdmission())
  Endif
  If xList.Exist("Chief Complaints") Then
    $BillingReport.Add(hForm.AddChiefComplaints())
  Endif
  If xList.Exist("History") Then
    $BillingReport.Add(hForm.AddHistoryAllTypes())
  Endif
  If xList.Exist("Consultations") Then
    $BillingReport.Add(hForm.AddConsultationAll())
  Endif
  If xList.Exist("Drug Allergy") Then
    $BillingReport.Add(hForm.AddDrugAllergy())
  Endif
  If xList.Exist("Provisional Diagnosis") Then
    $BillingReport.Add(hForm.AddProvisionalDiagnosis())
  Endif
  If xList.Exist("Final Diagnosis") Then
    $BillingReport.Add(hForm.AddFinalDiagnosis())
  Endif
  If xList.Exist("Treatment Advised") Then
    $BillingReport.Add(hForm.AddTreatmentAdvised())
  Endif

  If xList.Exist("Outpatient Advice") Then
    $BillingReport.Add(hForm.AddOutpatientAdvice())
  Endif
  If xList.Exist("Orders for New Visit") Then
    $BillingReport.Add(hForm.AddOrderForNewVisit())
  Endif
  If xList.Exist("Planned Procedures") Then
    $BillingReport.Add(hForm.AddPlannedProcedures())
  Endif
  If xList.Exist("Unavailable Medicines") Then
    $BillingReport.Add(hForm.AddUnavailableMeds())
  Endif

  If xList.Exist("Clinical Finding") Then
    $BillingReport.Add(hForm.AddExaminationsAll())
  Endif
  If xList.Exist("Structured Finding") Then
    $BillingReport.Add(hForm.AddStructuredExamAll())
  Endif
  If xList.Exist("Laboratory Tests") Then
    $BillingReport.Add(hForm.AddCompleteLaboratory(strUnit))
  Endif
  If xList.Exist("Radiological Findings") Then
    $BillingReport.Add(hForm.AddCompleteRadiology())
  Endif

  If xList.Exist("Major Procedures") Then
    $BillingReport.Add(hForm.AddMajorProcedures())
  Endif
  If xList.Exist("Minor Procedures") Then
    $BillingReport.Add(hForm.AddMinorProcedures())
  Endif
  If xList.Exist("Equipments Used") Then
    $BillingReport.Add(hForm.AddEquipmentsUsed())
  Endif
  If xList.Exist("Event Timings") Then
    $BillingReport.Add(hForm.AddEventProfile())
  Endif
  If xList.Exist("Devices Used") Then
    $BillingReport.Add(hForm.AddDevicesUsed())
  Endif

  If xList.Exist("Medication Used") Then
    $BillingReport.Add(hForm.AddMedicationUsed())
  Endif
  If xList.Exist("Vaccines used") Then
    $BillingReport.Add(hForm.AddVaccinesUsed())
  Endif
  If xList.Exist("Nutrition Consumed") Then
    $BillingReport.Add(hForm.AddNutritionUsed())
  Endif

  If xList.Exist("Delivery Profile") Then
    $BillingReport.Add(hForm.AddDeliveryProfile())
  Endif

  If xList.Exist("Inpatient Notes") Then
    $BillingReport.Add(hForm.AddInpatientNotes())
  Endif
  If xList.Exist("Medical Planning") Then
    $BillingReport.Add(hForm.AddTherapeuticPlanning())
  Endif
  If xList.Exist("IP Monitoring") Then
    $BillingReport.Add(hForm.AddIPMonitoring())
  Endif

  xstate = modPatient.CurrentAdmissionStatus(encid)
  If xstate = "Discharged" Then
    If xList.Exist("Discharge Notes") Then
      $BillingReport.Add(hForm.AddDischargeNotes())
    Endif
    If xList.Exist("Discharge Medication") Then
      $BillingReport.Add(hForm.AddDischargeMedication())
    Endif
  Endif

  If sColl Then
    $BillingReport.AddSection("Others", True)
    For Each xxx In sColl
      $BillingReport.Add(AddCustomReport(sColl.Key, xxx))
    Next
  Endif

  If HTMLOnly And If HTMLOnly = True Then
    Return $BillingReport.NewHTMLString()
  Else
    Return $BillingReport.NewHTMLPath()
  Endif

End

Public Function ShowAllEncounterReport(encounter As String, xList As String[], strUnit As String) As String

  Dim $BillingReport As CReportHTML
  Dim hForm As CPatReportAll
  Dim encid As String
  Dim encList As String[]
  Dim xitem As String
  Dim xstate As String

  If modBasic.$MedRepoBody = "Paragraph" Then
    $BillingReport = New CReportHTML([("Description")], "PatientReport", encounter)
  Else
    $BillingReport = New CReportHTML([("Category"), ("Observations")], "PatientReport", encounter)
  Endif
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("ALL ENCOUNTERS REPORT", "PARAM1")

  encList = modPatient.GetEncListFromEncSetting(encounter)
  For Each encid In encList
    hForm = New CPatReportAll(encid)
    $BillingReport.AddSection(encid & " (" & modReportVar.GetDateTimeReport(modPatient.GetRecordDate(encid), gb.MediumDate) & ")", True)

    xstate = modPatient.CurrentAdmissionStatus(encid)
    For Each xitem In xList

      If xitem = "Course of Treatment" Then
        $BillingReport.Add(hForm.AddCourseOfTreatment())
      Endif
      If xitem = "Demographics" Then
        $BillingReport.Add(hForm.AddPatDemographics())
      Endif
      If xitem = "Bed Transitions" Then
        $BillingReport.Add(hForm.AddBedTransition())
      Endif
      If xitem = "Cause of Admission" Then
        $BillingReport.Add(hForm.AddCauseofAdmission())
      Endif
      If xitem = "Chief Complaints" Then
        $BillingReport.Add(hForm.AddChiefComplaints())
      Endif
      If xitem = "History" Then
        $BillingReport.Add(hForm.AddHistoryAllTypes())
      Endif
      If xitem = "Consultations" Then
        $BillingReport.Add(hForm.AddConsultationAll())
      Endif
      If xitem = "Drug Allergy" Then
        $BillingReport.Add(hForm.AddDrugAllergy())
      Endif
      If xitem = "Provisional Diagnosis" Then
        $BillingReport.Add(hForm.AddProvisionalDiagnosis())
      Endif
      If xitem = "Final Diagnosis" Then
        $BillingReport.Add(hForm.AddFinalDiagnosis())
      Endif
      If xitem = "Treatment Advised" Then
        $BillingReport.Add(hForm.AddTreatmentAdvised())
      Endif

      If xitem = "Outpatient Advice" Then
        $BillingReport.Add(hForm.AddOutpatientAdvice())
      Endif
      If xitem = "Orders for New Visit" Then
        $BillingReport.Add(hForm.AddOrderForNewVisit())
      Endif
      If xitem = "Planned Procedures" Then
        $BillingReport.Add(hForm.AddPlannedProcedures())
      Endif
      If xitem = "Unavailable Medicines" Then
        $BillingReport.Add(hForm.AddUnavailableMeds())
      Endif

      If xitem = "Clinical Finding" Then
        $BillingReport.Add(hForm.AddExaminationsAll())
      Endif
      If xList.Exist("Structured Finding") Then
        $BillingReport.Add(hForm.AddStructuredExamAll())
      Endif
      If xitem = "Laboratory Tests" Then
        $BillingReport.Add(hForm.AddLaboratoryTests(strUnit))
      Endif
      If xitem = "Radiological Findings" Then
        $BillingReport.Add(hForm.AddRadioFindings())
      Endif

      If xitem = "Major Procedures" Then
        $BillingReport.Add(hForm.AddMajorProcedures())
      Endif
      If xitem = "Minor Procedures" Then
        $BillingReport.Add(hForm.AddMinorProcedures())
      Endif
      If xitem = "Equipments Used" Then
        $BillingReport.Add(hForm.AddEquipmentsUsed())
      Endif
      If xitem = "Event Timings" Then
        $BillingReport.Add(hForm.AddEventProfile())
      Endif
      If xitem = "Devices Used" Then
        $BillingReport.Add(hForm.AddDevicesUsed())
      Endif

      If xitem = "Medication Used" Then
        $BillingReport.Add(hForm.AddMedicationUsed())
      Endif
      If xitem = "Vaccines used" Then
        $BillingReport.Add(hForm.AddVaccinesUsed())
      Endif
      If xitem = "Nutrition Consumed" Then
        $BillingReport.Add(hForm.AddNutritionUsed())
      Endif

      If xitem = "Delivery Profile" Then
        $BillingReport.Add(hForm.AddDeliveryProfile())
      Endif

      If xitem = "Inpatient Notes" Then
        $BillingReport.Add(hForm.AddInpatientNotes())
      Endif
      If xitem = "Medical Planning" Then
        $BillingReport.Add(hForm.AddTherapeuticPlanning())
      Endif
      If xitem = "IP Monitoring" Then
        $BillingReport.Add(hForm.AddIPMonitoring())
      Endif

      If xstate = "Discharged" Then
        If xitem = "Discharge Notes" Then
          $BillingReport.Add(hForm.AddDischargeNotes())
        Endif
        If xitem = "Discharge Medication" Then
          $BillingReport.Add(hForm.AddDischargeMedication())
        Endif
      Endif

    Next
  Next

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowAllEncounterSpecific(encounter As String, strUnit As String, sType As String) As String

  Dim $BillingReport As CReportHTML
  Dim encid As String
  Dim encList As String[]

  If modBasic.$MedRepoBody = "Paragraph" Then
    $BillingReport = New CReportHTML([("Description")], "PatientReport", encounter)
  Else
    $BillingReport = New CReportHTML([("Category"), ("Observations")], "PatientReport", encounter)
  Endif
  $BillingReport.UserData.Add("REPORT: " & sType, "Report")
  $BillingReport.UserData.Add("ALL ENCOUNTERS REPORT", "PARAM1")

  encList = modPatient.GetEncListFromEncSetting(encounter)
  For Each encid In encList
    $BillingReport.AddSection(encid & " (" & modReportVar.GetDateTimeReport(modPatient.GetRecordDate(encid), gb.MediumDate) & ")", True)

    If sType = "Medicines" Then
      $BillingReport.Add(modPatReports.AddMedicineDispensed(encid))
      $BillingReport.Add(modPatReports.AddUnavailableMeds(encid))
      $BillingReport.Add(modPatReports.AddMedicationUsed(encid))
    Else If sType = "Laboratory" Then
      $BillingReport.Add(modPatReports.AddSelectedTest(encid, modLabTest.PaientAllTestNameArray(encid), strUnit))
    Else If sType = "Radiology" Then
      $BillingReport.Add(modPatReports.AddSelectedRadio(encid, modRadioTest.PaientAllRadioNameArray(encid)))
    Else If sType = "Examination" Then
      $BillingReport.Add(modPatReports.AddSelectedExamination(encid, modClinic.PaientAllExamNameArray(encid)))
    Endif

  Next

  Return $BillingReport.NewHTMLPath()

End

''-------------------- summary ---------------------------
Public Function GetOPDSummaryReportAllComp(encid As String) As String

  Dim $BillingReport As CReportHTML
  Dim hForm As CPatReportAll
  Dim xlist1 As String[]
  Dim xlist2 As String[]
  Dim xlist3 As String[]
  Dim xlist As String[]
  Dim compLst As String[]
  Dim xcomp As String
  Dim curcomp As String
  Dim curlock As String
  Dim xPath As String

  xlist = New String[]
  xlist1 = modControlSub.GetDirectFillresult(modDatabase.$myConn.Exec("select distinct(fldcomp) as col from tblexamgeneral where fldencounterval=&1", encid))
  xlist3 = modControlSub.GetDirectFillresult(modDatabase.$myConn.Exec("select distinct(fldcomp) as col from tblpatientnotes where fldencounterval=&1", encid))
  xlist2 = modControlSub.GetDirectFillresult(modDatabase.$myConn.Exec("select distinct(fldcomp) as col from tblpatientexam where fldencounterval=&1 and fldsave=&2", encid, True))
  xlist.Insert(xlist1)
  xlist.Insert(xlist3)
  xlist.Insert(xlist2)
  If xlist.Count Then
    compLst = modString.GetDistinctStringArray(xlist)

    If modBasic.$MedRepoBody = "Paragraph" Then
      $BillingReport = New CReportHTML([("Description")], "PatientReport", encid)
    Else
      $BillingReport = New CReportHTML([("Category"), ("Observations")], "PatientReport", encid)
    Endif
    $BillingReport.UserData.Add("REPORT", "Report")
    $BillingReport.UserData.Add("OPD VISITS", "PARAM1")

    hForm = New CPatReportAll(encid)
    $BillingReport.Add(hForm.AddConsultationAll())
    $BillingReport.Add(hForm.AddHistoryAllTypes())

    curcomp = modBasic.$compID
    curlock = modBasic.$ViewLockClinic
    modBasic.$ViewLockClinic = "Location"
    For Each xcomp In compLst
      $BillingReport.AddSection(xcomp)
      modBasic.$compID = xcomp
      $BillingReport.Add(modPatReports.AddChiefComplaints(encid))
      $BillingReport.Add(modPatReports.AddExaminationsAll(encid))
      $BillingReport.Add(modPatReports.AddTreatmentAdvised(encid))
      $BillingReport.Add(modPatReports.AddOutpatientAdvice(encid))
      $BillingReport.Add(modPatReports.AddOrderForNewVisit(encid))
    Next
    modBasic.$compID = curcomp
    modBasic.$ViewLockClinic = curlock

    xPath = $BillingReport.NewHTMLPath()
  Endif

  Return xPath

End
