' Gambas module file

Private Function AddCustomReport(stChapter As String, stObservation As String) As String[]

  Dim asx As New String[0]

  With asx
    If modBasic.$MedRepoBody = "Paragraph" Then
      .Add("<b>" & stChapter & "</b><br>" & modString.TextToHTML(stObservation))
    Else
      .Add(stChapter)
      .Add(modString.TextToHTML(stObservation))
    Endif
  End With
  Return asx

End

''--------------- Attached: General -----------------------
Private Function AddCourseOfTreatment(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Course of Treatment"
  Endif
  stObservation = modString.GetHTMLListFormat(modClinicReport.GetCourseOfTreatment(encid))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddBedTransition(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Bed Transitions"
  Endif
  stObservation = modString.GetHTMLListFormat(modPatPatho.GetPatientTransition(encid))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddChiefComplaints(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Chief Complaints"
  Endif
  stObservation = modString.GetHTMLListFormat(modClinicReport.GetPatientChiefComplaintsReport(encid, True))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddPatDemographics(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Demographics"
  Endif
  stObservation = modString.GetHTMLListFormat(modClinicReport.GetPatientDemographicReport(encid, True))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddCauseofAdmission(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Cause of Admission"
  Endif
  stObservation = modPatReports.GetPatientHistoryReport(encid, "Cause of Admission")
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddHistoryAllTypes(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "History"
  Endif

  stObservation = modString.GetHTMLListFormat(modClinicReport.GetPatientHistoryAllTypes(encid))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddConsultationAll(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Consultations"
  Endif
  stObservation = modString.GetHTMLListFormat(modPatient.GetPatientCOnsultList(encid))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddProvisionalDiagnosis(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Provisional Diagnosis"
  Endif
  stObservation = modString.GetHTMLListFormat(modPatient.PatientFindingList(encid, "Provisional Diagnosis"))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddFinalDiagnosis(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Final Diagnosis"
  Endif
  stObservation = modString.GetHTMLListFormat(modPatient.PatientFindingList(encid, "Final Diagnosis"))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddDrugAllergy(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Drug Allergy"
  Endif
  stObservation = modString.GetHTMLListFormat(modPatient.PatientFindingList(encid, "Allergic Drugs"))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddTreatmentAdvised(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Treatment Advised"
  Endif
  stObservation = modClinicReport.GetRequestMedString(encid, "Medicines", True)
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddUnavailableMeds(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Unavailable Medicines"
  Endif
  stObservation = modClinicReport.NonAvailableMedString(encid, "Medicines", True)
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddOutpatientAdvice(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Outpatient Advice"
  Endif
  stObservation = modPatReports.GetPatientNotesAllTypes(encid, "Outpatient Notes").Join(gb.NewLine)
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddOrderForNewVisit(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Orders for New Visit"
  Endif
  stObservation = modPatReports.GetPastBillingOrders(encid)
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddPlannedProcedures(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Planned Procedures"
  Endif
  stObservation = modString.GetHTMLListFormat(modPatReports.GetPatProcedureList(encid, "Procedures", "Planned"))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

''------------------ Attached: Lab/Radio/Exam
Private Function AddExaminationsAll(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]
  Dim categList As String[]
  Dim xcateg As String
  Dim xlist As String[]
  Dim xexams As String[]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Clinical Findings"
  Endif

  xexams = New String[]
  categList = ["ABC Examinations", "Essential Examinations", "Physician Examinations", "Nursing Examinations", "Discharge Examinations"]
  For Each xcateg In categList
    xlist = modPatReports.PaientSelExamNameArray(encid, xcateg)
    If xlist And If xlist.Count Then
      xexams.Add(xcateg & gb.NewLine & modClinicReport.GetExaminationHTMLProfile(encid, xlist))
    Endif
  Next

  stObservation = modString.GetHTMLListFormat(xexams)
  asx = AddCustomReport(stChapter, stObservation)

  Return asx

End

Private Function AddStructuredExamAll(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]
  Dim xexams As String[]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Structured Finding"
  Endif

  xexams = New String[]
  xexams.Add(modClinicReport.GetRecommendedExam(encid, "Physician Examinations") & gb.NewLine)
  xexams.Add(modClinicReport.GetRecommendedExam(encid, "Departmental") & gb.NewLine)
  xexams.Add(modClinicReport.GetRecommendedExam(encid, "Diagnostic Examinations") & gb.NewLine)

  stObservation = xexams.Join("<br>")
  asx = AddCustomReport(stChapter, stObservation)

  Return asx

End

''---------------------- Attached: Services ------------------------------
Private Function AddMajorProcedures(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Major Procedures"
  Endif
  stObservation = modPatSurgery.PatSelectProcedureString(encid, "Procedures", "Done")
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddMinorProcedures(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Minor Procedures"
  Endif
  stObservation = modString.GetHTMLListFormat(modPatReports.GetPatProcedureList(encid, "Minor Procedures", "Done"))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddEquipmentsUsed(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Equipments Used"
  Endif
  stObservation = modString.GetHTMLListFormat(modPatPatho.GetPatientEquipmentUse(encid))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddEventProfile(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Event Timings"
  Endif
  stObservation = modString.GetHTMLListFormat(modPatPatho.GetPatientEventProfile(encid, "Events"))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddDevicesUsed(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Devices Used"
  Endif
  stObservation = modString.GetHTMLListFormat(modPatPatho.GetPatientEventProfile(encid, "Devices"))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddMedicationUsed(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Medication Used"
  Endif
  stObservation = modPharmacy.NurDosingString(encid)
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddVaccinesUsed(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Vaccines used"
  Endif
  stObservation = modPharmacy.GetVaccineUsed(encid, False, False)
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddNutritionUsed(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Nutrition Consumed"
  Endif
  ''stObservation = modPharmacy.NurDosingString(encid)
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

''-------------------------- Attached: Inpatient -------------------
Private Function AddInpatientNotes(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Inpatient Notes"
  Endif
  stObservation = modString.GetHTMLListFormat(modPatReports.GetPatientNotesAllTypes(encid, "Inpatient Notes"))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddTherapeuticPlanning(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Medical Planning"
  Endif
  stObservation = modString.GetHTMLListFormat(modPatReports.GetPatientPlanningReport(encid))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddIPMonitoring(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "IP Monitoring"
  Endif
  stObservation = modString.GetHTMLListFormat(modPatReports.GetPatientMonitorReport(encid))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddDischargeNotes(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Discharge Notes"
  Endif
  stObservation = modString.GetHTMLListFormat(modPatReports.GetPatientNotesAllTypes(encid, "Discharge Notes"))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddDeliveryProfile(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Delivery Profile"
  Endif
  stObservation = modString.GetHTMLListFormat(modPatReports.DeliveryReportbyMother(encid))
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Private Function AddDischargeMedication(encid As String, Optional sTitle As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  If sTitle Then
    stChapter = sTitle
  Else
    stChapter = "Discharge Medication"
  Endif
  stObservation = modClinicReport.DischargeMedString(encid)
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

''======================= Reports ===========================
Public Function ShowAllCompleteReport(encid As String, strUnit As String) As String

  Dim $BillingReport As CReportHTML
  Dim xdelivery As String[]

  $BillingReport = New CReportHTML([("Category"), ("Observations")], "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("COMPLETE REPORT", "PARAM1")

  $BillingReport.AddSection("General", True)
  $BillingReport.Add(AddCourseOfTreatment(encid))
  $BillingReport.Add(AddPatDemographics(encid))
  $BillingReport.Add(AddBedTransition(encid))
  $BillingReport.Add(AddCauseofAdmission(encid))
  $BillingReport.Add(AddChiefComplaints(encid))
  $BillingReport.Add(AddHistoryAllTypes(encid))
  $BillingReport.Add(AddConsultationAll(encid))
  $BillingReport.Add(AddDrugAllergy(encid))
  $BillingReport.Add(AddProvisionalDiagnosis(encid))
  $BillingReport.Add(AddFinalDiagnosis(encid))
  $BillingReport.Add(AddTreatmentAdvised(encid))
  $BillingReport.Add(AddOutpatientAdvice(encid))
  $BillingReport.Add(AddOrderForNewVisit(encid))
  $BillingReport.Add(AddPlannedProcedures(encid))
  $BillingReport.Add(AddUnavailableMeds(encid))

  $BillingReport.AddSection("Investigations", True)
  $BillingReport.Add(AddExaminationsAll(encid))
  $BillingReport.Add(AddStructuredExamAll(encid))
  $BillingReport.Add(modPatReports.AddSelectedTest(encid, modLabTest.PaientAllTestNameArray(encid), strUnit))
  $BillingReport.Add(modPatReports.AddSelectedRadio(encid, modRadioTest.PaientAllRadioNameArray(encid)))

  $BillingReport.AddSection("Services Provided", True)
  $BillingReport.Add(AddMajorProcedures(encid))
  $BillingReport.Add(AddMinorProcedures(encid))
  $BillingReport.Add(AddEquipmentsUsed(encid))
  $BillingReport.Add(AddEventProfile(encid))
  $BillingReport.Add(AddDevicesUsed(encid))
  $BillingReport.Add(AddMedicationUsed(encid))
  $BillingReport.Add(AddVaccinesUsed(encid))
  $BillingReport.Add(AddNutritionUsed(encid))
  xdelivery = modPatReports.DeliveryReportbyMother(encid)
  If xdelivery Then
    $BillingReport.Add(AddCustomReport("Delivery Profile", xdelivery.Join(gb.NewLine)))
  Endif

  $BillingReport.AddSection("Inpatient Records", True)
  $BillingReport.Add(AddInpatientNotes(encid))
  $BillingReport.Add(AddTherapeuticPlanning(encid))
  $BillingReport.Add(AddIPMonitoring(encid))

  If modPatient.CurrentAdmissionStatus(encid) = "Discharged" Then
    $BillingReport.AddSection("Discharge", True)
    $BillingReport.Add(AddDischargeNotes(encid))
    $BillingReport.Add(AddDischargeMedication(encid))
  Endif

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowCompleteReport(encid As String, xList As String[], strUnit As String, HTMLOnly As Boolean, Optional sColl As Collection) As String

  Dim $BillingReport As CReportHTML
  Dim xdelivery As String[]
  Dim xstate As String
  Dim xxx As String

  If modBasic.$MedRepoBody = "Paragraph" Then
    $BillingReport = New CReportHTML([("Description")], "PatientReport", encid)
  Else
    $BillingReport = New CReportHTML([("Category"), ("Observations")], "PatientReport", encid)
  Endif
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("SELECTED PARAMETERS", "PARAM1")

  If xList.Exist("Course of Treatment") Then
    $BillingReport.Add(AddCourseOfTreatment(encid))
  Endif
  If xList.Exist("Demographics") Then
    $BillingReport.Add(AddPatDemographics(encid))
  Endif
  If xList.Exist("Bed Transitions") Then
    $BillingReport.Add(AddBedTransition(encid))
  Endif
  If xList.Exist("Cause of Admission") Then
    $BillingReport.Add(AddCauseofAdmission(encid))
  Endif
  If xList.Exist("Chief Complaints") Then
    $BillingReport.Add(AddChiefComplaints(encid))
  Endif
  If xList.Exist("History") Then
    $BillingReport.Add(AddHistoryAllTypes(encid))
  Endif
  If xList.Exist("Consultations") Then
    $BillingReport.Add(AddConsultationAll(encid))
  Endif
  If xList.Exist("Drug Allergy") Then
    $BillingReport.Add(AddDrugAllergy(encid))
  Endif
  If xList.Exist("Provisional Diagnosis") Then
    $BillingReport.Add(AddProvisionalDiagnosis(encid))
  Endif
  If xList.Exist("Final Diagnosis") Then
    $BillingReport.Add(AddFinalDiagnosis(encid))
  Endif
  If xList.Exist("Treatment Advised") Then
    $BillingReport.Add(AddTreatmentAdvised(encid))
  Endif

  If xList.Exist("Outpatient Advice") Then
    $BillingReport.Add(AddOutpatientAdvice(encid))
  Endif
  If xList.Exist("Orders for New Visit") Then
    $BillingReport.Add(AddOrderForNewVisit(encid))
  Endif
  If xList.Exist("Planned Procedures") Then
    $BillingReport.Add(AddPlannedProcedures(encid))
  Endif
  If xList.Exist("Unavailable Medicines") Then
    $BillingReport.Add(AddUnavailableMeds(encid))
  Endif

  If xList.Exist("Clinical Finding") Then
    $BillingReport.Add(AddExaminationsAll(encid))
  Endif
  If xList.Exist("Structured Finding") Then
    $BillingReport.Add(AddStructuredExamAll(encid))
  Endif
  If xList.Exist("Laboratory Tests") Then
    $BillingReport.Add(modPatReports.AddCompleteTest(encid, strUnit))
  Endif
  If xList.Exist("Radiological Findings") Then
    $BillingReport.Add(modPatReports.AddCompleteRadio(encid))
  Endif

  If xList.Exist("Major Procedures") Then
    $BillingReport.Add(AddMajorProcedures(encid))
  Endif
  If xList.Exist("Minor Procedures") Then
    $BillingReport.Add(AddMinorProcedures(encid))
  Endif
  If xList.Exist("Equipments Used") Then
    $BillingReport.Add(AddEquipmentsUsed(encid))
  Endif
  If xList.Exist("Event Timings") Then
    $BillingReport.Add(AddEventProfile(encid))
  Endif
  If xList.Exist("Devices Used") Then
    $BillingReport.Add(AddDevicesUsed(encid))
  Endif

  If xList.Exist("Medication Used") Then
    $BillingReport.Add(AddMedicationUsed(encid))
  Endif
  If xList.Exist("Vaccines used") Then
    $BillingReport.Add(AddVaccinesUsed(encid))
  Endif
  If xList.Exist("Nutrition Consumed") Then
    $BillingReport.Add(AddNutritionUsed(encid))
  Endif

  If xList.Exist("Delivery Profile") Then
    xdelivery = modPatReports.DeliveryReportbyMother(encid)
    If xdelivery Then
      $BillingReport.Add(AddCustomReport("Delivery Profile", xdelivery.Join(gb.NewLine)))
    Endif
  Endif

  If xList.Exist("Inpatient Notes") Then
    $BillingReport.Add(AddInpatientNotes(encid))
  Endif
  If xList.Exist("Medical Planning") Then
    $BillingReport.Add(AddTherapeuticPlanning(encid))
  Endif
  If xList.Exist("IP Monitoring") Then
    $BillingReport.Add(AddIPMonitoring(encid))
  Endif

  xstate = modPatient.CurrentAdmissionStatus(encid)
  If xstate = "Discharged" Then
    If xList.Exist("Discharge Notes") Then
      $BillingReport.Add(AddDischargeNotes(encid))
    Endif
    If xList.Exist("Discharge Medication") Then
      $BillingReport.Add(AddDischargeMedication(encid))
    Endif
  Endif

  If sColl Then
    $BillingReport.AddSection("Others", True)
    For Each xxx In sColl
      $BillingReport.Add(AddCustomReport(sColl.Key, xxx))
    Next
  Endif

  If HTMLOnly And If HTMLOnly = True Then
    Return $BillingReport.NewHTMLString()
  Else
    Return $BillingReport.NewHTMLPath()
  Endif

End

Public Function ShowAllEncounterReport(encounter As String, xList As String[], strUnit As String) As String

  Dim $BillingReport As CReportHTML
  Dim encid As String
  Dim encList As String[]
  Dim xdelivery As String[]
  Dim xitem As String
  Dim xstate As String

  If modBasic.$MedRepoBody = "Paragraph" Then
    $BillingReport = New CReportHTML([("Description")], "PatientReport", encounter)
  Else
    $BillingReport = New CReportHTML([("Category"), ("Observations")], "PatientReport", encounter)
  Endif
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("ALL ENCOUNTERS REPORT", "PARAM1")

  encList = modPatient.GetEncListFromEncSetting(encounter)
  For Each encid In encList
    $BillingReport.AddSection(encid & " (" & modReportVar.GetDateTimeReport(modPatient.GetRecordDate(encid), gb.MediumDate) & ")", True)

    xstate = modPatient.CurrentAdmissionStatus(encid)
    For Each xitem In xList

      If xitem = "Course of Treatment" Then
        $BillingReport.Add(AddCourseOfTreatment(encid))
      Endif
      If xitem = "Demographics" Then
        $BillingReport.Add(AddPatDemographics(encid))
      Endif
      If xitem = "Bed Transitions" Then
        $BillingReport.Add(AddBedTransition(encid))
      Endif
      If xitem = "Cause of Admission" Then
        $BillingReport.Add(AddCauseofAdmission(encid))
      Endif
      If xitem = "Chief Complaints" Then
        $BillingReport.Add(AddChiefComplaints(encid))
      Endif
      If xitem = "History" Then
        $BillingReport.Add(AddHistoryAllTypes(encid))
      Endif
      If xitem = "Consultations" Then
        $BillingReport.Add(AddConsultationAll(encid))
      Endif
      If xitem = "Drug Allergy" Then
        $BillingReport.Add(AddDrugAllergy(encid))
      Endif
      If xitem = "Provisional Diagnosis" Then
        $BillingReport.Add(AddProvisionalDiagnosis(encid))
      Endif
      If xitem = "Final Diagnosis" Then
        $BillingReport.Add(AddFinalDiagnosis(encid))
      Endif
      If xitem = "Treatment Advised" Then
        $BillingReport.Add(AddTreatmentAdvised(encid))
      Endif

      If xitem = "Outpatient Advice" Then
        $BillingReport.Add(AddOutpatientAdvice(encid))
      Endif
      If xitem = "Orders for New Visit" Then
        $BillingReport.Add(AddOrderForNewVisit(encid))
      Endif
      If xitem = "Planned Procedures" Then
        $BillingReport.Add(AddPlannedProcedures(encid))
      Endif
      If xitem = "Unavailable Medicines" Then
        $BillingReport.Add(AddUnavailableMeds(encid))
      Endif

      If xitem = "Clinical Finding" Then
        $BillingReport.Add(AddExaminationsAll(encid))
      Endif
      If xList.Exist("Structured Finding") Then
        $BillingReport.Add(AddStructuredExamAll(encid))
      Endif
      If xitem = "Laboratory Tests" Then
        $BillingReport.Add(modPatReports.AddSelectedTest(encid, modLabTest.PaientAllTestNameArray(encid), strUnit))
      Endif
      If xitem = "Radiological Findings" Then
        $BillingReport.Add(modPatReports.AddSelectedRadio(encid, modRadioTest.PaientAllRadioNameArray(encid)))
      Endif

      If xitem = "Major Procedures" Then
        $BillingReport.Add(AddMajorProcedures(encid))
      Endif
      If xitem = "Minor Procedures" Then
        $BillingReport.Add(AddMinorProcedures(encid))
      Endif
      If xitem = "Equipments Used" Then
        $BillingReport.Add(AddEquipmentsUsed(encid))
      Endif
      If xitem = "Event Timings" Then
        $BillingReport.Add(AddEventProfile(encid))
      Endif
      If xitem = "Devices Used" Then
        $BillingReport.Add(AddDevicesUsed(encid))
      Endif

      If xitem = "Medication Used" Then
        $BillingReport.Add(AddMedicationUsed(encid))
      Endif
      If xitem = "Vaccines used" Then
        $BillingReport.Add(AddVaccinesUsed(encid))
      Endif
      If xitem = "Nutrition Consumed" Then
        $BillingReport.Add(AddNutritionUsed(encid))
      Endif

      If xitem = "Delivery Profile" Then
        xdelivery = modPatReports.DeliveryReportbyMother(encid)
        If xdelivery Then
          $BillingReport.Add(AddCustomReport("Delivery Profile", xdelivery.Join(gb.NewLine)))
        Endif
      Endif

      If xitem = "Inpatient Notes" Then
        $BillingReport.Add(AddInpatientNotes(encid))
      Endif
      If xitem = "Medical Planning" Then
        $BillingReport.Add(AddTherapeuticPlanning(encid))
      Endif
      If xitem = "IP Monitoring" Then
        $BillingReport.Add(AddIPMonitoring(encid))
      Endif

      If xstate = "Discharged" Then
        If xitem = "Discharge Notes" Then
          $BillingReport.Add(AddDischargeNotes(encid))
        Endif
        If xitem = "Discharge Medication" Then
          $BillingReport.Add(AddDischargeMedication(encid))
        Endif
      Endif

    Next
  Next

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowAllEncounterSpecific(encounter As String, strUnit As String, sType As String) As String

  Dim $BillingReport As CReportHTML
  Dim encid As String
  Dim encList As String[]

  If modBasic.$MedRepoBody = "Paragraph" Then
    $BillingReport = New CReportHTML([("Description")], "PatientReport", encounter)
  Else
    $BillingReport = New CReportHTML([("Category"), ("Observations")], "PatientReport", encounter)
  Endif
  $BillingReport.UserData.Add("REPORT: " & sType, "Report")
  $BillingReport.UserData.Add("ALL ENCOUNTERS REPORT", "PARAM1")

  encList = modPatient.GetEncListFromEncSetting(encounter)
  For Each encid In encList
    $BillingReport.AddSection(encid & " (" & modReportVar.GetDateTimeReport(modPatient.GetRecordDate(encid), gb.MediumDate) & ")", True)

    If sType = "Medicines" Then
      $BillingReport.Add(modPatReports.AddMedicineDispensed(encid))
      $BillingReport.Add(modPatReports.AddMedicationUsed(encid))
      $BillingReport.Add(modPatReports.AddTreatmentAdvised(encid))
    Else If sType = "Laboratory" Then
      $BillingReport.Add(modPatReports.AddSelectedTest(encid, modLabTest.PaientAllTestNameArray(encid), strUnit))
    Else If sType = "Radiology" Then
      $BillingReport.Add(modPatReports.AddSelectedRadio(encid, modRadioTest.PaientAllRadioNameArray(encid)))
    Else If sType = "Examination" Then
      $BillingReport.Add(modPatReports.AddSelectedExamination(encid, modClinic.PaientAllExamNameArray(encid)))
    Endif

  Next

  Return $BillingReport.NewHTMLPath()

End

''-------------------- summary ---------------------------
Public Function GetOPDSummaryReportAllComp(encid As String) As String

  Dim $BillingReport As CReportHTML
  Dim xlist1 As String[]
  Dim xlist2 As String[]
  Dim xlist3 As String[]
  Dim xlist As String[]
  Dim compLst As String[]
  Dim xcomp As String
  Dim curcomp As String
  Dim curlock As String
  Dim xPath As String

  xlist = New String[]
  xlist1 = modControlSub.GetDirectFillresult(modDatabase.$myConn.Exec("select distinct(fldcomp) as col from tblexamgeneral where fldencounterval=&1", encid))
  xlist3 = modControlSub.GetDirectFillresult(modDatabase.$myConn.Exec("select distinct(fldcomp) as col from tblpatientnotes where fldencounterval=&1", encid))
  xlist2 = modControlSub.GetDirectFillresult(modDatabase.$myConn.Exec("select distinct(fldcomp) as col from tblpatientexam where fldencounterval=&1 and fldsave=&2", encid, True))
  xlist.Insert(xlist1)
  xlist.Insert(xlist3)
  xlist.Insert(xlist2)
  If xlist.Count Then
    compLst = modString.GetDistinctStringArray(xlist)

    If modBasic.$MedRepoBody = "Paragraph" Then
      $BillingReport = New CReportHTML([("Description")], "PatientReport", encid)
    Else
      $BillingReport = New CReportHTML([("Category"), ("Observations")], "PatientReport", encid)
    Endif
    $BillingReport.UserData.Add("REPORT", "Report")
    $BillingReport.UserData.Add("OPD VISITS", "PARAM1")

    $BillingReport.Add(AddConsultationAll(encid))
    $BillingReport.Add(AddHistoryAllTypes(encid))

    curcomp = modBasic.$compID
    curlock = modBasic.$ViewLockClinic
    modBasic.$ViewLockClinic = "Location"
    For Each xcomp In compLst
      $BillingReport.AddSection(xcomp)
      modBasic.$compID = xcomp
      $BillingReport.Add(modPatReports.AddChiefComplaints(encid))
      $BillingReport.Add(modPatReports.AddExaminationsAll(encid))
      $BillingReport.Add(modPatReports.AddTreatmentAdvised(encid))
      $BillingReport.Add(modPatReports.AddOutpatientAdvice(encid))
      $BillingReport.Add(modPatReports.AddOrderForNewVisit(encid))
    Next
    modBasic.$compID = curcomp
    modBasic.$ViewLockClinic = curlock

    xPath = $BillingReport.NewHTMLPath()
  Endif

  Return xPath

End
