' Gambas module file

Public Function GetExamSysConstValue(sType As String, sExam As String) As String
  
  Dim xsyscon As String
  
  If sType = "Exam" Then
    xsyscon = modFixClinic.GetExamSysName(sExam)
  Else If sType = "Radio" Then
    xsyscon = modFixRadio.GetRadioSysName(sExam)
  Else If sType = "Test" Then
    xsyscon = modFixLab.GetTestSysName(sExam)
  Else If sType = "Demog" Then
    xsyscon = sExam
  Endif
  
  Return xsyscon
  
End

Public Function GetExamDefaultValue(sType As String, sExam As String) As String
  
  Dim sql As String
  Dim xval As String
  Dim res As Result
  
  If sType = "Test" Then
    sql = "select flddetail from tbltest where fldtestid=&1"
  Else If sType = "Exam" Then
    sql = "select flddetail from tblexam where fldexamid=&1"
  Else If sType = "Radio" Then
    sql = "select flddetail from tblradio where fldexamid=&1"
  Endif
  If sql Then
    res = modDatabase.$myConn.Exec(sql, sExam)
    If res.Available Then
      If res["flddetail"] Then
        xval = res["flddetail"]
      Else
        xval = ""
      Endif
    Else
      xval = ""
    Endif
  Else
    xval = ""
  Endif
  
  Return xval
  
End

Public Function GetESubxamDefaultValue(sType As String, sExam As String, subExam As String) As String
  
  Dim sql As String
  Dim xval As String
  Dim res As Result
  
  If sType = "Test" Then
    sql = "select flddetail from tbltestquali where fldsubtest=&1 and fldtestid=&2 and flddetail IS NOT NULL"
  Else If sType = "Exam" Then
    sql = "select flddetail from tblexamquali where fldsubexam=&1 and fldexamid=&2 and flddetail IS NOT NULL"
  Else If sType = "Radio" Then
    sql = "select flddetail from tblradioquali where fldsubexam=&1 and fldexamid=&2 and flddetail IS NOT NULL"
  Endif
  res = modDatabase.$myConn.Exec(sql, subExam, sExam)
  If res.Available Then
    res.MoveLast
    If res["flddetail"] Then
      xval = res["flddetail"]
    Else
      xval = ""
    Endif
  Else
    xval = ""
  Endif
  
  Return xval
  
End

''----------------------------- Option
Public Function GetVariableOptionType(sType As String, sExam As String) As String
  
  ' Dim res1 As Result
  Dim xval As String
  
  If sType Then
    If sType = "Radio" Then
      xval = modFixRadio.GetRadioTestOption(sExam)
      ' res1 = modDatabase.$medConn.Exec("select fldoption from tblradio where fldexamid=&1", sExam)
    Else If sType = "Test" Then
      xval = modFixLab.GetLabTestOptionType(sExam)
      ' res1 = modDatabase.$medConn.Exec("select fldoption from tbltest where fldtestid=&1", sExam)
    Else If sType = "Demog" Then
      xval = modFixPatho.GetDemographicType(sExam)
      ' res1 = modDatabase.$medConn.Exec("select fldoption from tbldemographic where flddemoid=&1", sExam)
    Else
      xval = modFixClinic.GetExamtOptionType(sExam)
      ' res1 = modDatabase.$medConn.Exec("select fldoption from tblexam where fldexamid=&1", sExam)
    Endif
  Else
    xval = modFixClinic.GetExamtOptionType(sExam)
    ' res1 = modDatabase.$medConn.Exec("select fldoption from tblexam where fldexamid=&1", sExam)
  Endif
  ' If res1.Available Then
  '   If res1["fldoption"] Then
  '     xval = res1["fldoption"]
  '   Else
  '     xval = ""
  '   Endif
  ' Else
  '   xval = ""
  ' Endif
  
  Return xval
  
End

Public Function SelectExamOptionList(sType As String, sExam As String, Optional xOptionType As String) As String[]
  
  Dim res As Result
  Dim opt As String[]
  
  If xOptionType Then
    If sType = "Test" Then
      res = modDatabase.$medConn.Exec("select fldanswer from tbltestoption where fldtestid=&1 and fldanswertype=&2 ORDER BY fldindex", sExam, xOptionType)
    Else If sType = "Radio" Then
      res = modDatabase.$medConn.Exec("select fldanswer from tblradiooption where fldexamid=&1 and fldanswertype=&2 ORDER BY fldindex", sExam, xOptionType)
    Else If sType = "Exam" Then
      res = modDatabase.$medConn.Exec("select fldanswer from tblexamoption where fldexamid=&1 and fldanswertype=&2 ORDER BY fldindex", sExam, xOptionType)
    Else If sType = "Demog" Then
      res = modDatabase.$medConn.Exec("select fldanswer from tbldemogoption where flddemoid=&1 ORDER BY fldindex", sExam)
    Endif
    opt = modControlSub.GetDirectFillresult(res)
    
    If Not opt.Count Then
      If xOptionType = "Dichotomous" Then
        opt = ["Yes", "No"]
      Endif
    Endif
    
  Else
    If sType = "Test" Then
      res = modDatabase.$medConn.Exec("select fldanswer from tbltestoption where fldtestid=&1 ORDER BY fldindex", sExam)
    Else If sType = "Radio" Then
      res = modDatabase.$medConn.Exec("select fldanswer from tblradiooption where fldexamid=&1 ORDER BY fldindex", sExam)
    Else If sType = "Exam" Then
      res = modDatabase.$medConn.Exec("select fldanswer from tblexamoption where fldexamid=&1 ORDER BY fldindex", sExam)
    Else If sType = "Demog" Then
      res = modDatabase.$medConn.Exec("select fldanswer from tbldemogoption where flddemoid=&1 ORDER BY fldindex", sExam)
    Endif
    opt = modControlSub.GetDirectFillresult(res)
  Endif
  
  Return opt
  
End

Public Function SelectSubExamOptionList(sType As String, sExam As String, sSubExam As String, Optional xOptionType As String) As String[]
  
  Dim res As Result
  Dim opt As String[]
  
  If xOptionType Then
    If sType = "Test" Then
      res = modDatabase.$medConn.Exec("select fldanswer as col from tblsubtestquali where fldtestid=&1 and fldsubtest=&2 and fldanswertype=&3 ORDER BY fldindex", sExam, sSubExam, xOptionType)
    Else If sType = "Radio" Then
      res = modDatabase.$medConn.Exec("select fldanswer as col from tblsubradioquali where fldexamid=&1 and fldsubexam=&2 and fldanswertype=&3 ORDER BY fldindex", sExam, sSubExam, xOptionType)
    Else If sType = "Exam" Then
      res = modDatabase.$medConn.Exec("select fldanswer as col from tblsubexamquali where fldexamid=&1 and fldsubexam=&2 and fldanswertype=&3 ORDER BY fldindex", sExam, sSubExam, xOptionType)
    Endif
    opt = modControlSub.GetDirectFillresult(res)
    
    If Not opt.Count Then
      If xOptionType = "Dichotomous" Then
        opt = ["Yes", "No"]
      Endif
    Endif
    
  Else
    If sType = "Test" Then
      res = modDatabase.$medConn.Exec("select fldanswer as col from tblsubtestquali where fldtestid=&1 and fldsubtest=&2 ORDER BY fldindex", sExam, sSubExam)
    Else If sType = "Radio" Then
      res = modDatabase.$medConn.Exec("select fldanswer as col from tblsubradioquali where fldexamid=&1 and fldsubexam=&2 ORDER BY fldindex", sExam, sSubExam)
    Else If sType = "Exam" Then
      res = modDatabase.$medConn.Exec("select fldanswer as col from tblsubexamquali where fldexamid=&1 and fldsubexam=&2 ORDER BY fldindex", sExam, sSubExam)
    Endif
    opt = modControlSub.GetDirectFillresult(res)
  Endif
  
  Return opt
  
End

''----------------------------- clinical scale
Public Function GetCLinicalScaleOptions(sType As String, sExam As String) As String[]
  
  Dim res As Result
  Dim opt As String[]
  
  If sType = "Test" Then
    res = modDatabase.$medConn.Exec("select fldanswertype,fldanswer,fldscale,fldscalegroup from tbltestoption where fldtestid=&1 ORDER BY fldindex", sExam)
  Else If sType = "Radio" Then
    res = modDatabase.$medConn.Exec("select fldanswertype,fldanswer,fldscale,fldscalegroup from tblradiooption where fldexamid=&1 ORDER BY fldindex", sExam)
  Else If sType = "Exam" Then
    res = modDatabase.$medConn.Exec("select fldanswertype,fldanswer,fldscale,fldscalegroup from tblexamoption where fldexamid=&1 ORDER BY fldindex", sExam)
  Endif
  opt = New String[]
  If res.Available Then
    For Each res
      opt.Add(res["fldanswer"] & "@" & res["fldscale"] & "@" & res["fldscalegroup"])
    Next
  Endif
  Return opt
  
End

Public Function GetCLinicalScaleGroups(sType As String, sExam As String) As String[]
  
  Dim res As Result
  Dim opt As String[]
  
  If sType = "Test" Then
    res = modDatabase.$medConn.Exec("select distinct(fldscalegroup) as col from tbltestoption where fldtestid=&1 ORDER BY fldindex", sExam)
  Else If sType = "Radio" Then
    res = modDatabase.$medConn.Exec("select distinct(fldscalegroup) as col from tblradiooption where fldexamid=&1 ORDER BY fldindex", sExam)
  Else If sType = "Exam" Then
    res = modDatabase.$medConn.Exec("select distinct(fldscalegroup) as col from tblexamoption where fldexamid=&1 ORDER BY fldindex", sExam)
  Endif
  opt = modControlSub.GetDirectFillresult(res)
  Return opt
  
End

''--------------------- Abnormal
Public Function SelectExamAbnormal(sType As String, sExam As String, sOption As String, Optional xOptionType As String) As Boolean
  
  Dim res As Result
  Dim xabn As Boolean
  
  If xOptionType Then
    If sType = "Test" Then
      res = modDatabase.$medConn.Exec("select fldabnormal from tbltestoption where fldtestid=&1 and fldanswertype=&2 and fldanswer=&3", sExam, xOptionType, sOption)
    Else If sType = "Radio" Then
      res = modDatabase.$medConn.Exec("select fldabnormal from tblradiooption where fldexamid=&1 and fldanswertype=&2 and fldanswer=&3", sExam, xOptionType, sOption)
    Else If sType = "Exam" Then
      res = modDatabase.$medConn.Exec("select fldabnormal from tblexamoption where fldexamid=&1 and fldanswertype=&2 and fldanswer=&3", sExam, xOptionType, sOption)
    Endif
  Else
    If sType = "Test" Then
      res = modDatabase.$medConn.Exec("select fldabnormal from tbltestoption where fldtestid=&1 and fldanswer=&2", sExam, sOption)
    Else If sType = "Radio" Then
      res = modDatabase.$medConn.Exec("select fldabnormal from tblradiooption where fldexamid=&1 and fldanswer=&2", sExam, sOption)
    Else If sType = "Exam" Then
      res = modDatabase.$medConn.Exec("select fldabnormal from tblexamoption where fldexamid=&1 and fldanswer=&2", sExam, sOption)
    Endif
  Endif
  If res.Available Then
    If res["fldabnormal"] Then
      xabn = res["fldabnormal"]
    Else
      xabn = False
    Endif
  Else
    xabn = False
  Endif
  
  Return xabn
  
End

Public Function SelectSubExamAbnormal(sType As String, sExam As String, sSubExam As String, sOption As String, Optional xOptionType As String) As Boolean
  
  Dim res As Result
  Dim xabn As Boolean
  
  If xOptionType Then
    If sType = "Test" Then
      res = modDatabase.$medConn.Exec("select fldabnormal from tblsubtestquali where fldtestid=&1 and fldsubtest=&2 and fldanswertype=&3 and fldanswer=&4", sExam, sSubExam, xOptionType, sOption)
    Else If sType = "Radio" Then
      res = modDatabase.$medConn.Exec("select fldabnormal from tblsubradioquali where fldexamid=&1 and fldsubexam=&2 and fldanswertype=&3 and fldanswer=&4", sExam, sSubExam, xOptionType, sOption)
    Else If sType = "Exam" Then
      res = modDatabase.$medConn.Exec("select fldabnormal from tblsubexamquali where fldexamid=&1 and fldsubexam=&2 and fldanswertype=&3 and fldanswer=&4", sExam, sSubExam, xOptionType, sOption)
    Endif
  Else
    If sType = "Test" Then
      res = modDatabase.$medConn.Exec("select fldabnormal from tblsubtestquali where fldtestid=&1 and fldsubtest=&2 and fldanswer=&3", sExam, sSubExam, sOption)
    Else If sType = "Radio" Then
      res = modDatabase.$medConn.Exec("select fldabnormal from tblsubradioquali where fldexamid=&1 and fldsubexam=&2 and fldanswer=&3", sExam, sSubExam, sOption)
    Else If sType = "Exam" Then
      res = modDatabase.$medConn.Exec("select fldabnormal from tblsubexamquali where fldexamid=&1 and fldsubexam=&2 and fldanswer=&3", sExam, sSubExam, sOption)
    Endif
  Endif
  If res.Available Then
    If res["fldabnormal"] Then
      xabn = res["fldabnormal"]
    Else
      xabn = False
    Endif
  Else
    xabn = False
  Endif
  
  Return xabn
  
End
