' Gambas module file

Public $TestItemQualiQuanti As Collection
Public $TestItemCategory As Collection
Public $TestIDFromSysConst As Collection
Public $TestSpecimen As Collection
Public $TestCritValue As Collection
Public $TestOptionType As Collection
Public $TestCaption As Collection
Public $TestToolTip As Collection

Public $TestDrugHypo As Collection
Public $TestdrugHyper As Collection
Public $TestSyndroBrady As Collection
Public $TestSyndroTachy As Collection

'NOTE:------------------------------- TEST Procedures ------------------------------------------
Public Function GetTestExamEquipments(sType As String) As String[]

  Dim res As Result
  Dim res1 As Result
  Dim xxx As String[]

  res = modDatabase.$medConn.Exec("select fldmethod from tbltestmethod where fldcateg like &1", sType)
  If res.Available Then
    xxx = modControlSub.GetDirectFillresult(res)
  Else
    res1 = modDatabase.$medConn.Exec("select distinct(fldmethod) from tblpatlabtest")
    xxx = modControlSub.GetDirectFillresult(res1)
  Endif
  Return xxx

End

Public Function MethodsForLabTest(sTestName As String) As String[]

  Dim xx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select distinct(fldmethod) as col from tbltestlimit where fldtestid=&1", sTestName)
  xx = modControlSub.GetDirectFillresult(res)
  Return xx

End

Public Function GetLabTestCaption(test As String) As String

  Dim xx As String
  Dim res As Result

  xx = modHelpVariable.GetCollectionValue($TestCaption, test, modBasic.$AppCacheLaboratoryConstants)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldcaption from tbltest where fldtestid=&1", test)
    If res.Available Then
      If res["fldcaption"] Then
        xx = res["fldcaption"]
        If modBasic.$AppCacheLaboratoryConstants = "Yes" Then
          $TestCaption.Add(xx, test)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetLabTestCategory(test As String) As String

  Dim xx As String
  Dim res As Result

  xx = modHelpVariable.GetCollectionValue($TestItemCategory, test, modBasic.$AppCacheLaboratoryConstants)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldcategory from tbltest where fldtestid=&1", test)
    If res.Available Then
      If res["fldcategory"] Then
        xx = res["fldcategory"]
        If modBasic.$AppCacheLaboratoryConstants = "Yes" Then
          $TestItemCategory.Add(xx, test)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetLabTestType(strTest As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($TestItemQualiQuanti, strTest, modBasic.$AppCacheLaboratoryConstants)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldtype from tbltest where fldtestid=&1", strTest)
    If res.Available Then
      If res["fldtype"] Then
        xx = res["fldtype"]
        If modBasic.$AppCacheLaboratoryConstants = "Yes" Then
          $TestItemQualiQuanti.Add(xx, strTest)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetLabTestIDFromSysConst(sysCons As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($TestIDFromSysConst, sysCons, modBasic.$AppCacheLaboratoryConstants)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldtestid from tbltest where fldsysconst=&1", sysCons)
    If res.Available = True Then
      res.MoveFirst
      If res["fldtestid"] Then
        xx = res["fldtestid"]
        If modBasic.$AppCacheLaboratoryConstants = "Yes" Then
          $TestIDFromSysConst.Add(xx, sysCons)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetLabTestOptionType(strTest As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($TestOptionType, strTest, modBasic.$AppCacheLaboratoryConstants)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldoption from tbltest where fldtestid=&1", strTest)
    If res.Available Then
      If res["fldoption"] Then
        xx = res["fldoption"]
        If modBasic.$AppCacheLaboratoryConstants = "Yes" Then
          $TestOptionType.Add(xx, strTest)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetTestSysName(sTest As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldsysconst from tbltest where fldtestid=&1", sTest)
  If res.Available Then
    If res["fldsysconst"] Then
      xx = res["fldsysconst"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetTestSpecimen(testid As String) As String

  Dim xx As String
  Dim res As Result

  xx = modHelpVariable.GetCollectionValue($TestSpecimen, testid, modBasic.$AppCacheLaboratoryConstants)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldspecimen from tbltest where fldtestid=&1", testid)
    If res.Available Then
      If res["fldspecimen"] Then
        xx = res["fldspecimen"]
        If modBasic.$AppCacheLaboratoryConstants = "Yes" Then
          $TestSpecimen.Add(xx, testid)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetTestSampleSuffix(sTest As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldspecmcode from tbltest where fldtestid=&1", sTest)
  If res.Available Then
    If res["fldspecmcode"] Then
      xx = res["fldspecmcode"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetCritValueTest(strTest As String) As Float

  Dim res As Result
  Dim xval As Float
  Dim yy As Variant

  yy = modHelpVariable.GetCollectionValue($TestCritValue, strTest, modBasic.$AppCacheLaboratoryConstants)
  If yy Then
    xval = CFloat(yy)
  Else
    xval = 0
  Endif

  If Not xval Then
    res = modDatabase.$medConn.Exec("select fldcritical from tbltest where fldtestid=&1", strTest)
    If res.Available Then
      If res["fldcritical"] Then
        xval = res["fldcritical"]
        If modBasic.$AppCacheLaboratoryConstants = "Yes" Then
          $TestCritValue.Add(xval, strTest)
        Endif
      Else
        xval = 0
      Endif
    Else
      xval = 0
    Endif
  Endif
  Return xval

End

Public Function GetTestWithCategory(sTestList As String[]) As String[]

  Dim xx As String
  Dim xval As String[]

  xval = New String[]
  For Each xx In sTestList
    xval.Add(GetLabTestCategory(xx) & "@" & xx)
  Next
  Return xval

End

Public Function GetSubTestArray(testid As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$medConn.Exec("select distinct(fldsubtest) from tbltestquali where fldtestid=&1 ORDER BY fldindex", testid)
  xx = modControlSub.GetDirectFillresult(res)

  Return xx

End

Public Function GetSubTestOption(testid As String, subtest As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldtanswertype from tbltestquali where fldtestid=&1 and fldsubtest=&2", testid, subtest)
  If res.Available Then
    If res["fldtanswertype"] Then
      xx = res["fldtanswertype"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetLabFooterInfo(txtexam As String) As String

  Dim xx As String
  Dim res As Result

  xx = modHelpVariable.GetCollectionValue($TestToolTip, txtexam, modBasic.$AppCacheLaboratoryConstants)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldcomment from tbltest where fldtestid=&1", txtexam)
    If res.Available Then
      If res["fldcomment"] Then
        xx = res["fldcomment"]
        If modBasic.$AppCacheLaboratoryConstants = "Yes" Then
          $TestToolTip.Add(xx, txtexam)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetLabQualiTestTextReference(txttest As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldanswer from tbltestoption where fldtestid=&1 and fldanswertype=&2 ORDER BY fldindex", txttest, "Text Reference")
  If res.Available = True Then
    If res["fldanswer"] Then
      xx = res["fldanswer"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetSubLatTestQualiReference(txttest As String, txtsubtest As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldreference from tbltestquali where fldtestid=&1 and fldsubtest=&2", txttest, txtsubtest)
  If res.Available = True Then
    If res["fldreference"] Then
      xx = res["fldreference"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetTestUnitWithOutAgeSex(strTest As String, strUnit As String) As String

  Dim unt As String
  Dim res As Result

  res = modDatabase.$medConn.Exec("select fldsiunit,fldmetunit from tbltestlimit where fldtestid=&1", strTest)
  res.MoveFirst
  If strUnit = "Metric" Then
    If res["fldmetunit"] Then
      unt = res["fldmetunit"]
    Else
      unt = ""
    Endif
  Else If strUnit = "SI" Then
    If res["fldsiunit"] Then
      unt = res["fldsiunit"]
    Else
      unt = ""
    Endif
  Endif

  Return unt

End

Public Function LabFieldValue(sField As String, strTest As String) As Float

  Dim res As Result
  Dim svalue As Float

  res = modDatabase.$medConn.Exec(Subst("select &1 as fldname from tbltest", sField) & " where fldtestid=&1", strTest)
  If res.Available Then
    If res["fldname"] Then
      svalue = res["fldname"]
    Else
      svalue = 0
    Endif
  Else
    svalue = 0
  Endif
  Return svalue

End

Public Function GetLabTestOrder(sTest As String) As Integer

  Dim res As Result
  Dim xorder As Integer

  res = modDatabase.$medConn.Exec("select fldtestorder from tbltest where fldtestid=&1", sTest)
  If res.Available Then
    If res["fldtestorder"] Then
      xorder = res["fldtestorder"]
    Else
      xorder = 0
    Endif
  Else
    xorder = 0
  Endif
  Return xorder

End
