' Gambas module file

''--------------------- tblcode --------------------------------------------------
Public Function GetInfoReferenceForCode(stockid As String) As String

  Dim sql As String
  Dim res As Result
  Dim ref As String

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    ref = modTableCache.$MedicineDataVar[stockid]["fldreference"]
    If Not ref Then
      ref = ""
    Endif

  Else
    sql = "select fldreference from tblcode where fldcodename in(select fldcodename from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1))"
    res = modDatabase.$medConn.Exec(sql, stockid)
    If res.Available Then
      If res["fldreference"] Then
        ref = res["fldreference"]
      Else
        ref = ""
      Endif
    Else
      ref = ""
    Endif
  Endif
  Return ref

End

Public Function GetAllowPRN(stockid As String) As String

  Dim sql As String
  Dim res As Result
  Dim prn As String

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    prn = modTableCache.$MedicineDataVar[stockid]["fldprn"]
    If Not prn Then
      prn = "Yes"
    Endif

  Else
    sql = "select fldprn from tblcode where fldcodename in(select fldcodename from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1))"
    res = modDatabase.$medConn.Exec(sql, stockid)
    If res.Available Then
      If res["fldprn"] Then
        prn = res["fldprn"]
      Else
        prn = "Yes"
      Endif
    Else
      prn = "Yes"
    Endif
  Endif
  Return prn

End

Public Function GetChemicalClass(txtcode As String) As String

  Dim res As Result
  Dim allergy As String

  res = modDatabase.$medConn.Exec("select fldchemclass from tblcode where fldcodename=&1", txtcode)
  If res.Available Then
    If res["fldchemclass"] Then
      allergy = res["fldchemclass"]
    Else
      allergy = ""
    Endif
  Else
    allergy = ""
  Endif

  Return allergy

End

Public Function GetCategoryFromStockID(stockid As String) As String

  Dim sql As String
  Dim res As Result
  Dim cod As String

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    cod = modTableCache.$MedicineDataVar[stockid]["fldcategory"]
    If Not cod Then
      cod = ""
    Endif

  Else
    sql = "select fldcategory from tblcode where fldcodename in(select fldcodename from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1))"
    res = modDatabase.$medConn.Exec(sql, stockid)
    If res.Available Then
      If res["fldcategory"] Then
        cod = res["fldcategory"]
      Else
        cod = ""
      Endif
    Else
      cod = ""
    Endif
  Endif
  Return cod

End

Public Function GetSensiNameFromStockID(stockid As String) As String

  Dim sql As String
  Dim res As Result
  Dim cod As String

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    cod = modTableCache.$MedicineDataVar[stockid]["fldsensname"]
    If Not cod Then
      cod = ""
    Endif

  Else
    sql = "select fldsensname from tblcode where fldcodename in(select fldcodename from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1))"
    res = modDatabase.$medConn.Exec(sql, stockid)
    If res.Available Then
      If res["fldsensname"] Then
        cod = res["fldsensname"]
      Else
        cod = ""
      Endif
    Else
      cod = ""
    Endif
  Endif
  Return cod

End

Public Function GetRiskTypeFromSTockID(stockid As String) As String

  Dim sql As String
  Dim res As Result
  Dim cod As String

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    cod = modTableCache.$MedicineDataVar[stockid]["fldrisklevel"]
    If Not cod Then
      cod = ""
    Endif

  Else
    sql = "select fldrisklevel from tblcode where fldcodename in(select fldcodename from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1))"
    res = modDatabase.$medConn.Exec(sql, stockid)
    If res.Available Then
      If res["fldrisklevel"] Then
        cod = res["fldrisklevel"]
      Else
        cod = ""
      Endif
    Else
      cod = ""
    Endif
  Endif
  Return cod

End

Public Function GetDrugRenalEliminFraction(stockid As String) As Float

  Dim sql As String
  Dim res As Result
  Dim elim As String

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    elim = modTableCache.$MedicineDataVar[stockid]["fldeliminrenal"]
    If elim Then
      elim = elim / 100
    Else
      elim = 0
    Endif

  Else
    sql = "select fldeliminrenal from tblcode where fldcodename in(select fldcodename from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1))"
    res = modDatabase.$medConn.Exec(sql, stockid)
    If res.Available Then
      If res["fldeliminrenal"] Then
        elim = res["fldeliminrenal"] / 100
      Else
        elim = 0
      Endif
    Else
      elim = 0
    Endif
  Endif
  Return elim

End

''--------------------- tbldrug --------------------------------------------------
Public Function GetInfoReferenceForDrug(stockid As String) As String

  Dim sql As String
  Dim res As Result
  Dim ref As String

  ' ref = modHelpVariable.GetCollectionValue($DrugReference, stockid, modBasic.$AppCacheDrugRelatedProblems)
  ' If Not ref Then
  sql = "select fldreference from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1)"
  res = modDatabase.$medConn.Exec(sql, stockid)
  If res.Available Then
    If res["fldreference"] Then
      ref = res["fldreference"]
    Else
      ref = ""
    Endif
  Else
    ref = ""
  Endif
  ' Endif
  Return ref

End

Public Function GetContraIndicatedLowerAge(stockid As String) As Float

  Dim sql As String
  Dim res As Result
  Dim xx As Float
  Dim xval As Variant

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    xx = modTableCache.$MedicineDataVar[stockid]["fldciyear"]
    If Not xx Then
      xx = 0
    Endif

  Else
    sql = "select fldciyear from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1)"
    res = modDatabase.$medConn.Exec(sql, stockid)
    If res.Available Then
      If res["fldciyear"] Then
        xx = res["fldciyear"]
      Else
        xx = 0
      Endif
    Else
      xx = 0
    Endif
  Endif
  Return xx

End

Public Function GetCodeFromStockID(stockid As String) As String

  Dim sql As String
  Dim res As Result
  Dim cod As String

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    cod = modTableCache.$MedicineDataVar[stockid]["fldcodename"]
    If Not cod Then
      cod = ""
    Endif

  Else
    sql = "select fldcodename from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1)"
    res = modDatabase.$medConn.Exec(sql, stockid)
    If res.Available Then
      If res["fldcodename"] Then
        cod = res["fldcodename"]
      Else
        cod = ""
      Endif
    Else
      cod = ""
    Endif
  Endif
  Return cod

End

Public Function GetCodeFromDrugID(drugid As String) As String

  Dim sql As String
  Dim res As Result
  Dim cod As String

  sql = "select fldcodename from tbldrug where flddrug=&1"
  res = modDatabase.$medConn.Exec(sql, drugid)
  If res.Available Then
    If res["fldcodename"] Then
      cod = res["fldcodename"]
    Else
      cod = ""
    Endif
  Else
    cod = ""
  Endif

  Return cod

End

Public Function GetDrugInitialStrength(stockid As String) As Float

  Dim res As Result
  Dim inistr As Float
  Dim xval As Variant

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    inistr = modTableCache.$MedicineDataVar[stockid]["fldstrength"]
    If Not inistr Then
      inistr = 0
    Endif

  Else
    res = modDatabase.$medConn.Exec("select fldstrength from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1)", stockid)
    If res.Available Then
      If res["fldstrength"] Then
        inistr = res["fldstrength"]
      Else
        inistr = 0
      Endif
    Else
      inistr = 0
    Endif
  Endif
  Return inistr

End

Public Function GetDrugStrengthUnit(stockid As String) As String

  Dim res As Result
  Dim xunit As String

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    xunit = modTableCache.$MedicineDataVar[stockid]["fldstrunit"]
    If Not xunit Then
      xunit = ""
    Endif

  Else
    res = modDatabase.$medConn.Exec("select fldstrunit from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1)", stockid)
    If res.Available Then
      If res["fldstrunit"] Then
        xunit = res["fldstrunit"]
      Else
        xunit = ""
      Endif
    Else
      xunit = ""
    Endif
  Endif
  Return xunit

End

Public Function GetDrugDosingUnit(stockid As String) As String

  Dim res As Result
  Dim xunit As String

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    xunit = modTableCache.$MedicineDataVar[stockid]["flddoseunit"]
    If Not xunit Then
      xunit = ""
    Endif

  Else
    res = modDatabase.$medConn.Exec("select flddoseunit from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1)", stockid)
    If res.Available Then
      If res["flddoseunit"] Then
        xunit = res["flddoseunit"]
      Else
        xunit = ""
      Endif
    Else
      xunit = ""
    Endif
  Endif
  Return xunit

End

''---------------------- tblmedbrand -----------------------------------------------
Public Function GetPackVolValue(stockid As String) As Float

  Dim res As Result
  Dim xx As Float
  Dim yy As Variant

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    xx = modTableCache.$MedicineDataVar[stockid]["fldpackvol"]
    If Not xx Then
      xx = 0
    Endif

  Else
    res = modDatabase.$medConn.Exec("select fldpackvol from tblmedbrand where fldbrandid=&1", stockid)                                                                 '''
    If res.Available Then
      If res["fldpackvol"] Then
        xx = res["fldpackvol"]
      Else
        xx = 0
      Endif
    Else
      xx = 0
    Endif
  Endif
  Return xx

End

Public Function GetPackVolUnit(stockid As String) As String

  Dim res As Result
  Dim xx As String

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    xx = modTableCache.$MedicineDataVar[stockid]["fldvolunit"]
    If Not xx Then
      xx = ""
    Endif

  Else
    res = modDatabase.$medConn.Exec("select fldvolunit from tblmedbrand where fldbrandid=&1", stockid)                                                                 '''
    If res.Available Then
      If res["fldvolunit"] Then
        xx = res["fldvolunit"]
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetAllowTabBreak(stockid As String) As String

  Dim res As Result
  Dim xx As String

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    xx = modTableCache.$MedicineDataVar[stockid]["fldtabbreak"]
    If Not xx Then
      xx = "Yes"
    Endif

  Else
    res = modDatabase.$medConn.Exec("select fldtabbreak from tblmedbrand where fldbrandid=&1", stockid)
    If res.Available Then
      If res["fldtabbreak"] Then
        xx = res["fldtabbreak"]
      Else
        xx = "Yes"
      Endif
    Else
      xx = "Yes"
    Endif
  Endif
  Return xx

End

Public Function GetPreservativeContent(stockid As String) As String

  Dim res As Result
  Dim xx As String

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    xx = modTableCache.$MedicineDataVar[stockid]["fldpreservative"]
    If Not xx Then
      xx = ""
    Endif

  Else
    res = modDatabase.$medConn.Exec("select fldpreservative from tblmedbrand where fldbrandid=&1", stockid)
    If res.Available Then
      If res["fldpreservative"] Then
        xx = res["fldpreservative"]
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetDrugFromStockID(stockid As String) As String

  Dim res As Result
  Dim xx As String

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    xx = modTableCache.$MedicineDataVar[stockid]["flddrug"]
    If Not xx Then
      xx = ""
    Endif

  Else
    res = modDatabase.$medConn.Exec("select flddrug from tblmedbrand where fldbrandid=&1", stockid)
    If res.Available Then
      If res["flddrug"] Then
        xx = res["flddrug"]
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetNarcoticType(stockid As String) As String

  Dim sql As String
  Dim res As Result
  Dim xx As String

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    xx = modTableCache.$MedicineDataVar[stockid]["fldnarcotic"]
    If Not xx Then
      xx = "No"
    Endif

  Else
    sql = "select fldnarcotic from tblmedbrand where fldbrandid=&1"
    res = modDatabase.$medConn.Exec(sql, stockid)
    If res.Available Then
      If res["fldnarcotic"] Then
        xx = res["fldnarcotic"]
      Else
        xx = "No"
      Endif
    Else
      xx = "No"
    Endif
  Endif
  Return xx

End

Public Function GetPacketSizeMedicine(stockid As String) As Float

  Dim res As Result
  Dim xx As Float

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    xx = modTableCache.$MedicineDataVar[stockid]["fldpacksize"]
    If Not xx Then
      xx = 1
    Endif

  Else
    res = modDatabase.$medConn.Exec("select fldpacksize from tblmedbrand where fldbrandid=&1", stockid)
    If res.Available Then
      If res["fldpacksize"] Then
        xx = res["fldpacksize"]
      Else
        xx = 1
      Endif
    Else
      xx = 1
    Endif
  Endif

  Return xx

End

Public Function GetBrandFromStockID(stockid As String) As String

  Dim sql As String
  Dim res As Result
  Dim xx As String

  If modTableCache.$MedicineDataVar.Exist(stockid) Then
    xx = modTableCache.$MedicineDataVar[stockid]["fldbrand"]
    If Not xx Then
      xx = ""
    Endif

  Else
    sql = "select fldbrand from tblmedbrand where fldbrandid=&1"
    res = modDatabase.$medConn.Exec(sql, stockid)
    If res.Available Then
      If res["fldbrand"] Then
        xx = res["fldbrand"]
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

''-------------------- miscell -----------------------
Public Function GetPreAdminTestList(codeid As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$medConn.Exec("select distinct(fldchild) as col from tblmedmonitor where fldparent=&1 and fldtype=&2", codeid, "Pre-Administration")
  xx = modControlSub.GetDirectFillresult(res)
  Return xx

End

Public Function GetDietMixNameFromCode(sCode As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldtitle from tblfoodmix where fldgroup=&1", sCode)
  If res.Available = True Then
    If res["fldtitle"] Then
      xx = res["fldtitle"]
    Else
      xx = sCode
    Endif
  Else
    xx = sCode
  Endif

  Return xx

End

''======================= OTHERS =====================================

Public Function ConvertBrandToGeneric(txtroute As String, txtbrand As String) As String

  Dim res As Result
  Dim xx As String

  ' xx = modHelpVariable.GetCollectionValue($MedBrandToGeneric, txtbrand & "@" & txtroute, modBasic.$AppCacheMedicineConstants)
  ' If Not xx Then
  res = modDatabase.$medConn.Exec("select fldbrandid from tblmedbrand where fldbrand=&1 and fldactive=&2 and flddrug in(select flddrug from tbldrug where fldroute=&3)", txtbrand, "Active", txtroute)
  If res.Available Then
    If res["fldbrandid"] Then
      xx = res["fldbrandid"]
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  ' Endif
  Return xx

End

Public Function GetMedicineDoseUnit(stockid As String) As String

  Dim xx As String
  Dim asx As String[]
  Dim xval As String

  xval = modMedConstant.GetDrugDosingUnit(stockid)
  If Not xval Then
    xx = GetDrugStrengthUnit(stockid)
    If xx Then
      asx = Split(xx, "/")
      If asx.Count Then
        xval = asx[0]
      Else
        xval = xx
      Endif
    Else
      xval = "mg"
    Endif
  Endif

  Return xval

End

Public Function ConvertGenericToBrand(txtstockid As String) As String

  Dim xx As String

  xx = GetBrandFromStockID(txtstockid)
  If Not xx Then
    xx = txtstockid
  Endif
  Return xx

End

Public Function ConvertGenericToDrug(txtstockid As String) As String

  Dim xx As String

  xx = GetDrugFromStockID(txtstockid)
  If Not xx Then
    xx = txtstockid
  Endif
  Return xx

End

Public Function GetQuantityDosingForCOunt(txtmedicine As String, txtdose As Float, sCount As Integer) As Float

  Dim qty As Float
  Dim xqty As Float
  Dim res As Result

  res = modDatabase.$medConn.Exec("select tblmedbrand.fldtabbreak as fldtabbreak,tblmedbrand.fldpackvol as fldpackvol,tblmedbrand.fldpacksize as fldpacksize,tbldrug.fldstrength as fldstrength,tbldrug.fldroute as fldroute from tblmedbrand inner join tbldrug on tblmedbrand.flddrug=tbldrug.flddrug where tblmedbrand.fldbrandid=&1", txtmedicine)                                                                         ''
  If res.Available = True Then
    If res["fldpackvol"] And If res["fldstrength"] Then

      If res["fldtabbreak"] = "No" Then
        xqty = txtdose / (res["fldpackvol"] * res["fldstrength"])
        If xqty Then
          If res["fldpacksize"] And If modBasic.$SalesQTYPack = "Enable" Then
            qty = Ceil(xqty / res["fldpacksize"]) * res["fldpacksize"] * sCount
          Else
            qty = Ceil(xqty) * sCount
          Endif
        Else
          qty = 0
        Endif
      Else
        xqty = (txtdose * sCount) / (res["fldpackvol"] * res["fldstrength"])
        If xqty Then
          If res["fldpacksize"] And If modBasic.$SalesQTYPack = "Enable" Then
            qty = Ceil(xqty / res["fldpacksize"]) * res["fldpacksize"]
          Else
            qty = Ceil(xqty)
          Endif
        Else
          qty = 0
        Endif
      Endif

    Else
      qty = 0
    Endif
  Else
    qty = 0
  Endif
  Return qty

End

Public Function GetQuantityDosing(txtmedicine As String, txtdose As Float, txtftreq As String, txtday As Float) As Float

  Dim qty As Float
  Dim xqty As Float
  Dim res As Result

  res = modDatabase.$medConn.Exec("select tblmedbrand.fldtabbreak as fldtabbreak,tblmedbrand.fldpackvol as fldpackvol,tblmedbrand.fldpacksize as fldpacksize,tbldrug.fldstrength as fldstrength,tbldrug.fldroute as fldroute from tblmedbrand inner join tbldrug on tblmedbrand.flddrug=tbldrug.flddrug where tblmedbrand.fldbrandid=&1", txtmedicine)                                                                         ''
  If res.Available = True Then
    If res["fldpackvol"] And If res["fldstrength"] Then

      If res["fldtabbreak"] = "No" Then
        xqty = txtdose / (res["fldpackvol"] * res["fldstrength"])
        If xqty Then
          If res["fldpacksize"] And If modBasic.$SalesQTYPack = "Enable" Then
            qty = Ceil(xqty / res["fldpacksize"]) * res["fldpacksize"] * modPharmLabel.ConvertFrequencyToNumber(txtftreq) * txtday
          Else
            qty = Ceil(xqty) * modPharmLabel.ConvertFrequencyToNumber(txtftreq) * txtday
          Endif
        Else
          qty = 0
        Endif
      Else
        xqty = (txtdose * modPharmLabel.ConvertFrequencyToNumber(txtftreq) * txtday) / (res["fldpackvol"] * res["fldstrength"])
        If xqty Then
          If res["fldpacksize"] And If modBasic.$SalesQTYPack = "Enable" Then
            qty = Ceil(xqty / res["fldpacksize"]) * res["fldpacksize"]
          Else
            qty = Ceil(xqty)
          Endif
        Else
          qty = 0
        Endif
      Endif

    Else
      qty = 0
    Endif
  Else
    qty = 0
  Endif
  Return qty

End

Public Function GetDrugUseDurationDosing(txtmedicine As String, txtdose As Float, txtftreq As String, txtqty As Float) As Integer

  Dim txtday As Integer
  Dim res As Result

  res = modDatabase.$medConn.Exec("select tblmedbrand.fldpackvol as fldpackvol,tbldrug.fldstrength as fldstrength from tblmedbrand inner join tbldrug on tblmedbrand.flddrug=tbldrug.flddrug where tblmedbrand.fldbrandid=&1", txtmedicine)                                                                         ''
  If res.Available = True Then
    If txtdose Then
      txtday = Ceil((txtqty * res["fldpackvol"] * res["fldstrength"]) / (txtdose * modPharmLabel.ConvertFrequencyToNumber(txtftreq)))
    Else
      txtday = 0
    Endif
  Else
    txtday = 0
  Endif
  Return txtday

End

Public Function GetStockIDWithCategory(sMedList As String[]) As String[]

  Dim xx As String
  Dim asx As String
  Dim xval As String[]

  xval = New String[]
  For Each xx In sMedList
    asx = GetCategoryFromStockID(xx)
    If Not asx Then
      asx = "Unspecified"
    Endif
    xval.Add(asx & "|" & xx)
  Next
  Return xval

End

Public Function GetMedicineDoseFormat(sRoute As String, sMedicine As String, xDose As Float, sFormat As String) As String

  Dim xx As String
  Dim xstr As Float

  If xDose Then
    If sFormat = "Label" Then
      Select sRoute
        Case "fluid", "resp", "topical", "eye/ear", "anal/vaginal"
          xx = CStr(xDose) & Space(1) & modMedConstant.GetMedicineDoseUnit(sMedicine)
        Case Else
          xstr = modMedConstant.GetDrugInitialStrength(sMedicine)
          If xstr Then
            xx = modPharmLabel.ConvertDoseToPrintNum(xDose / xstr) & Space(1) & modMedConstant.GetPackVolUnit(sMedicine)
          Endif
      End Select
    Else
      xx = CStr(xDose) & Space(1) & modMedConstant.GetMedicineDoseUnit(sMedicine)
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetMedicineRegimenInFormat(sRoute As String, sMedicine As String, aDose As Float, sFreq As String, xDays As Float) As String

  Dim xdose As String
  Dim xfreq As String
  Dim xregimen As String

  xdose = modMedConstant.GetMedicineDoseFormat(sRoute, sMedicine, aDose, modBasic.$MedicineDoseFormat)
  If modBasic.$MedicineFrequencyFormat = "Label" Then
    xfreq = modPharmLabel.ConvertMedFreqToLabel(sFreq)
    If xDays Then
      xregimen = xdose & Space(1) & xfreq & Space(1) & " For " & CStr(xDays) & " Days"
    Else
      xregimen = xdose & Space(1) & xfreq & Space(1) & " Every Day"
    Endif
  Else
    xfreq = "X" & Space(1) & sFreq
    If xDays Then
      xregimen = xdose & Space(1) & xfreq & Space(1) & "X " & CStr(xDays) & " Days"
    Else
      xregimen = xdose & Space(1) & xfreq & Space(1) & "X Every Day"
    Endif
  Endif

  Return xregimen

End
