' Gambas module file

''================= Bulk Alteration =============================
Public Sub RecodeMedicineCode(sOldName As String, sNewName As String)

  Dim res As Result
  Dim res1 As Result
  Dim res2 As Result
  Dim res3 As Result
  Dim res4 As Result
  Dim res5 As Result
  Dim res6 As Result
  Dim res7 As Result
  Dim res8 As Result
  Dim res9 As Result

  Dim res10 As Result
  Dim res11 As Result
  Dim res12 As Result
  Dim res13 As Result
  Dim res14 As Result
  Dim res15 As Result
  Dim res16 As Result
  Dim res17 As Result
  Dim res18 As Result
  Dim res19 As Result
  Dim res20 As Result
  Dim res21 As Result
  Dim res22 As Result

  Dim res23 As Result
  Dim res24 As Result
  Dim res25 As Result
  Dim res26 As Result
  Dim res27 As Result
  Dim res28 As Result
  Dim res29 As Result
  Dim res30 As Result
  Dim res31 As Result
  Dim res32 As Result
  Dim res33 As Result

  Dim xdrug As String
  Dim xlabel As String
  Dim xinject As String
  Dim xbrandid As String

  If sNewName And If sNewName <> sOldName Then

    modDatabase.$myConn.Begin
    ''code related
    res1 = modDatabase.$myConn.Edit("tblcodelimit", "fldcodename=&1", sOldName)
    If res1.Available Then
      For Each res1
        res1["fldcodename"] = sNewName
        res1.Update
      Next
    Endif
    res2 = modDatabase.$myConn.Edit("tblmedrenal", "fldcodename=&1", sOldName)
    If res2.Available Then
      For Each res2
        res2["fldcodename"] = sNewName
        res2.Update
      Next
    Endif
    res3 = modDatabase.$myConn.Edit("tblmedhepatic", "fldcodename=&1", sOldName)
    If res3.Available Then
      For Each res3
        res3["fldcodename"] = sNewName
        res3.Update
      Next
    Endif
    res4 = modDatabase.$myConn.Edit("tblmedpregnancy", "fldcodename=&1", sOldName)
    If res4.Available Then
      For Each res4
        res4["fldcodename"] = sNewName
        res4.Update
      Next
    Endif
    res5 = modDatabase.$myConn.Edit("tblmedinteraction", "fldcodename=&1", sOldName)
    If res5.Available Then
      For Each res5
        res5["fldcodename"] = sNewName
        res5.Update
      Next
    Endif
    res9 = modDatabase.$myConn.Edit("tblmedinteraction", "fldcondition=&1", sOldName)
    If res9.Available Then
      For Each res9
        res9["fldcondition"] = sNewName
        res9.Update
      Next
    Endif
    res6 = modDatabase.$myConn.Edit("tblmedcontraindication", "fldparent=&1", sOldName)
    If res6.Available Then
      For Each res6
        res6["fldparent"] = sNewName
        res6.Update
      Next
    Endif
    res7 = modDatabase.$myConn.Edit("tblmedadveffect", "fldparent=&1", sOldName)
    If res7.Available Then
      For Each res7
        res7["fldparent"] = sNewName
        res7.Update
      Next
    Endif
    res8 = modDatabase.$myConn.Edit("tblmedmonitor", "fldparent=&1", sOldName)
    If res8.Available Then
      For Each res8
        res8["fldparent"] = sNewName
        res8.Update
      Next
    Endif
    res20 = modDatabase.$myConn.Edit("tblcompatdrug", "fldchild=&1", sOldName)
    If res20.Available Then
      For Each res20
        res20["fldchild"] = sNewName
        res20.Update
      Next
    Endif
    res21 = modDatabase.$myConn.Edit("tblincompatdrug", "fldchild=&1", sOldName)
    If res21.Available Then
      For Each res21
        res21["fldchild"] = sNewName
        res21.Update
      Next
    Endif

    ''dosage form related
    res10 = modDatabase.$myConn.Edit("tbldrug", "fldcodename=&1", sOldName)
    If res10.Available Then
      For Each res10
        xdrug = sNewName & " -" & res10["fldstrength"] & res10["fldstrunit"]

        ''update related tables
        res11 = modDatabase.$myConn.Edit("tblcompatdrug", "fldparent=&1", res10["flddrug"])
        If res11.Available Then
          For Each res11
            res11["fldparent"] = xdrug
            res11.Update
          Next
        Endif
        res12 = modDatabase.$myConn.Edit("tblincompatdrug", "fldparent=&1", res10["flddrug"])
        If res12.Available Then
          For Each res12
            res12["fldparent"] = xdrug
            res12.Update
          Next
        Endif
        res13 = modDatabase.$myConn.Edit("tblcompatfluid", "fldparent=&1", res10["flddrug"])
        If res13.Available Then
          For Each res13
            res13["fldparent"] = xdrug
            res13.Update
          Next
        Endif
        res14 = modDatabase.$myConn.Edit("tblcompatfluid", "fldchild=&1", res10["flddrug"])
        If res14.Available Then
          For Each res14
            res14["fldchild"] = xdrug
            res14.Update
          Next
        Endif
        res15 = modDatabase.$myConn.Edit("tblincompatfluid", "fldparent=&1", res10["flddrug"])
        If res15.Available Then
          For Each res15
            res15["fldparent"] = xdrug
            res15.Update
          Next
        Endif
        res16 = modDatabase.$myConn.Edit("tblincompatfluid", "fldchild=&1", res10["flddrug"])
        If res16.Available Then
          For Each res16
            res16["fldchild"] = xdrug
            res16.Update
          Next
        Endif
        res22 = modDatabase.$myConn.Edit("tblreconstfluid", "fldchild=&1", res10["flddrug"])
        If res22.Available Then
          For Each res22
            res22["fldchild"] = xdrug
            res22.Update
          Next
        Endif
        res24 = modDatabase.$myConn.Edit("tbldilutionfluid", "fldchild=&1", res10["flddrug"])
        If res24.Available Then
          For Each res24
            res24["fldchild"] = xdrug
            res24.Update
          Next
        Endif
        res33 = modDatabase.$myConn.Edit("tblstockrate", "flddrug=&1", res10["flddrug"])
        If res33.Available Then
          For Each res33
            res33["flddrug"] = xdrug
            res33.Update
          Next
        Endif

        ''label related
        res17 = modDatabase.$myConn.Edit("tbllabel", "flddrug=&1", res10["flddrug"])
        If res17.Available Then
          For Each res17
            xlabel = xdrug & "-" & res17["fldsubroute"]

            ''injection related
            res18 = modDatabase.$myConn.Edit("tblinjection", "fldlabel=&1", res17["fldlabel"])
            If res18.Available Then
              For Each res18
                xinject = xlabel & "()"
                ''update related tables
                res19 = modDatabase.$myConn.Edit("tblreconstfluid", "fldparent=&1", res18["fldinjection"])
                If res19.Available Then
                  For Each res19
                    res19["fldparent"] = xinject
                    res19.Update
                  Next
                Endif
                res23 = modDatabase.$myConn.Edit("tbldilutionfluid", "fldparent=&1", res18["fldinjection"])
                If res23.Available Then
                  For Each res23
                    res23["fldparent"] = xinject
                    res23.Update
                  Next
                Endif
                ''update main table
                res18["fldinjection"] = xinject
                res18["fldlabel"] = xlabel
                res18.Update
              Next
            Endif  ''end of injection related

            ''update main table
            res17["fldlabel"] = xlabel
            res17["flddrug"] = xdrug
            res17.Update
          Next
        Endif  ''end of label related

        ''brand related
        res25 = modDatabase.$myConn.Edit("tblmedbrand", "flddrug=&1", res10["flddrug"])
        If res25.Available Then
          For Each res25
            xbrandid = xdrug & " (" & res25["fldbrand"] & ")"
            ''update related tables
            res26 = modDatabase.$myConn.Edit("tblentry", "fldstockid=&1", res25["fldbrandid"])
            If res26.Available Then
              For Each res26
                res26["fldstockid"] = xbrandid
                res26.Update
              Next
            Endif
            res27 = modDatabase.$myConn.Edit("tblpurchase", "fldstockid=&1", res25["fldbrandid"])
            If res27.Available Then
              For Each res27
                res27["fldstockid"] = xbrandid
                res27.Update
              Next
            Endif
            res28 = modDatabase.$myConn.Edit("tblpatdosing", "flditem=&1", res25["fldbrandid"])
            If res28.Available Then
              For Each res28
                res28["flditem"] = xbrandid
                res28.Update
              Next
            Endif
            res29 = modDatabase.$myConn.Edit("tbltransfer", "fldstockid=&1", res25["fldbrandid"])
            If res29.Available Then
              For Each res29
                res29["fldstockid"] = xbrandid
                res29.Update
              Next
            Endif
            res30 = modDatabase.$myConn.Edit("tblbulksale", "fldstockid=&1", res25["fldbrandid"])
            If res30.Available Then
              For Each res30
                res30["fldstockid"] = xbrandid
                res30.Update
              Next
            Endif
            res31 = modDatabase.$myConn.Edit("tbladjustment", "fldstockid=&1", res25["fldbrandid"])
            If res31.Available Then
              For Each res31
                res31["fldstockid"] = xbrandid
                res31.Update
              Next
            Endif
            res32 = modDatabase.$myConn.Edit("tblstockreturn", "fldstockid=&1", res25["fldbrandid"])
            If res32.Available Then
              For Each res32
                res32["fldstockid"] = xbrandid
                res32.Update
              Next
            Endif
            ''update main table
            res25["fldbrandid"] = xbrandid
            res25["flddrug"] = xdrug
            res25.Update
          Next
        Endif   ''end of brand related

        ''update main table
        res10["flddrug"] = xdrug
        res10["fldcodename"] = sNewName
        res10.Update
      Next
    Endif   ''end of dosage form
    modDatabase.$myConn.Commit

    ''update main table
    res = modDatabase.$myConn.Edit("tblcode", "fldcodename=&1", sOldName)
    res["fldcodename"] = sNewName
    Try res.Update

  Endif

Catch
  modDatabase.$myConn.Rollback
  modHelpVariable.CreateErrorReport()

End

Public Sub RecodeMedicineDrug(sOldName As String, sNewCode As String, sNewStrength As Float, sNewUnit As String)

  Dim res10 As Result
  Dim res11 As Result
  Dim res12 As Result
  Dim res13 As Result
  Dim res14 As Result
  Dim res15 As Result
  Dim res16 As Result
  Dim res17 As Result
  Dim res18 As Result
  Dim res19 As Result
  Dim res22 As Result

  Dim res23 As Result
  Dim res24 As Result
  Dim res25 As Result
  Dim res26 As Result
  Dim res27 As Result
  Dim res28 As Result
  Dim res29 As Result
  Dim res30 As Result
  Dim res31 As Result
  Dim res32 As Result
  Dim res33 As Result

  Dim xdrug As String
  Dim xlabel As String
  Dim xinject As String
  Dim xbrandid As String

  If sNewCode Then
    res10 = modDatabase.$myConn.Edit("tbldrug", "flddrug=&1", sOldName)
    If res10.Available Then

      xdrug = sNewCode & " -" & CStr(sNewStrength) & Trim(sNewUnit)
      modDatabase.$myConn.Begin
      ''update related tables
      res11 = modDatabase.$myConn.Edit("tblcompatdrug", "fldparent=&1", res10["flddrug"])
      If res11.Available Then
        For Each res11
          res11["fldparent"] = xdrug
          res11.Update
        Next
      Endif
      res12 = modDatabase.$myConn.Edit("tblincompatdrug", "fldparent=&1", res10["flddrug"])
      If res12.Available Then
        For Each res12
          res12["fldparent"] = xdrug
          res12.Update
        Next
      Endif
      res13 = modDatabase.$myConn.Edit("tblcompatfluid", "fldparent=&1", res10["flddrug"])
      If res13.Available Then
        For Each res13
          res13["fldparent"] = xdrug
          res13.Update
        Next
      Endif
      res14 = modDatabase.$myConn.Edit("tblcompatfluid", "fldchild=&1", res10["flddrug"])
      If res14.Available Then
        For Each res14
          res14["fldchild"] = xdrug
          res14.Update
        Next
      Endif
      res15 = modDatabase.$myConn.Edit("tblincompatfluid", "fldparent=&1", res10["flddrug"])
      If res15.Available Then
        For Each res15
          res15["fldparent"] = xdrug
          res15.Update
        Next
      Endif
      res16 = modDatabase.$myConn.Edit("tblincompatfluid", "fldchild=&1", res10["flddrug"])
      If res16.Available Then
        For Each res16
          res16["fldchild"] = xdrug
          res16.Update
        Next
      Endif
      res22 = modDatabase.$myConn.Edit("tblreconstfluid", "fldchild=&1", res10["flddrug"])
      If res22.Available Then
        For Each res22
          res22["fldchild"] = xdrug
          res22.Update
        Next
      Endif
      res24 = modDatabase.$myConn.Edit("tbldilutionfluid", "fldchild=&1", res10["flddrug"])
      If res24.Available Then
        For Each res24
          res24["fldchild"] = xdrug
          res24.Update
        Next
      Endif
      res33 = modDatabase.$myConn.Edit("tblstockrate", "flddrug=&1", res10["flddrug"])
      If res33.Available Then
        For Each res33
          res33["flddrug"] = xdrug
          res33.Update
        Next
      Endif

      ''label related
      res17 = modDatabase.$myConn.Edit("tbllabel", "flddrug=&1", res10["flddrug"])
      If res17.Available Then
        For Each res17
          xlabel = xdrug & "-" & res17["fldsubroute"]

          ''injection related
          res18 = modDatabase.$myConn.Edit("tblinjection", "fldlabel=&1", res17["fldlabel"])
          If res18.Available Then
            For Each res18
              xinject = xlabel & "()"
              ''update related tables
              res19 = modDatabase.$myConn.Edit("tblreconstfluid", "fldparent=&1", res18["fldinjection"])
              If res19.Available Then
                For Each res19
                  res19["fldparent"] = xinject
                  res19.Update
                Next
              Endif
              res23 = modDatabase.$myConn.Edit("tbldilutionfluid", "fldparent=&1", res18["fldinjection"])
              If res23.Available Then
                For Each res23
                  res23["fldparent"] = xinject
                  res23.Update
                Next
              Endif
              ''update main table
              res18["fldinjection"] = xinject
              res18["fldlabel"] = xlabel
              res18.Update
            Next
          Endif  ''end of injection related

          ''update main table
          res17["fldlabel"] = xlabel
          res17["flddrug"] = xdrug
          res17.Update
        Next
      Endif  ''end of label related

      ''brand related
      res25 = modDatabase.$myConn.Edit("tblmedbrand", "flddrug=&1", res10["flddrug"])
      If res25.Available Then
        For Each res25
          xbrandid = xdrug & " (" & res25["fldbrand"] & ")"
          ''update related tables
          res26 = modDatabase.$myConn.Edit("tblentry", "fldstockid=&1", res25["fldbrandid"])
          If res26.Available Then
            For Each res26
              res26["fldstockid"] = xbrandid
              res26.Update
            Next
          Endif
          res27 = modDatabase.$myConn.Edit("tblpurchase", "fldstockid=&1", res25["fldbrandid"])
          If res27.Available Then
            For Each res27
              res27["fldstockid"] = xbrandid
              res27.Update
            Next
          Endif
          res28 = modDatabase.$myConn.Edit("tblpatdosing", "flditem=&1", res25["fldbrandid"])
          If res28.Available Then
            For Each res28
              res28["flditem"] = xbrandid
              res28.Update
            Next
          Endif
          res29 = modDatabase.$myConn.Edit("tbltransfer", "fldstockid=&1", res25["fldbrandid"])
          If res29.Available Then
            For Each res29
              res29["fldstockid"] = xbrandid
              res29.Update
            Next
          Endif
          res30 = modDatabase.$myConn.Edit("tblbulksale", "fldstockid=&1", res25["fldbrandid"])
          If res30.Available Then
            For Each res30
              res30["fldstockid"] = xbrandid
              res30.Update
            Next
          Endif
          res31 = modDatabase.$myConn.Edit("tbladjustment", "fldstockid=&1", res25["fldbrandid"])
          If res31.Available Then
            For Each res31
              res31["fldstockid"] = xbrandid
              res31.Update
            Next
          Endif
          res32 = modDatabase.$myConn.Edit("tblstockreturn", "fldstockid=&1", res25["fldbrandid"])
          If res32.Available Then
            For Each res32
              res32["fldstockid"] = xbrandid
              res32.Update
            Next
          Endif
          ''update main table
          res25["fldbrandid"] = xbrandid
          res25["flddrug"] = xdrug
          res25.Update
        Next
      Endif   ''end of brand related
      modDatabase.$myConn.Commit

      ''update main table
      res10["flddrug"] = xdrug
      res10["fldcodename"] = sNewCode
      res10["fldstrength"] = sNewStrength
      res10["fldstrunit"] = sNewUnit
      Try res10.Update

    Endif
  Endif

Catch
  modDatabase.$myConn.Rollback
  modHelpVariable.CreateErrorReport()

End

Public Sub RecodeMedicineStock(sOldName As String, sNewBrand As String)

  Dim res25 As Result
  Dim res26 As Result
  Dim res27 As Result
  Dim res28 As Result
  Dim res29 As Result
  Dim res30 As Result
  Dim res31 As Result
  Dim res32 As Result

  Dim xbrandid As String

  If sOldName Then
    res25 = modDatabase.$myConn.Edit("tblmedbrand", "fldbrandid=&1", sOldName)
    If res25.Available Then

      xbrandid = res25["flddrug"] & " (" & sNewBrand & ")"
      modDatabase.$myConn.Begin
      ''update related tables
      res26 = modDatabase.$myConn.Edit("tblentry", "fldstockid=&1", res25["fldbrandid"])
      If res26.Available Then
        For Each res26
          res26["fldstockid"] = xbrandid
          res26.Update
        Next
      Endif
      res27 = modDatabase.$myConn.Edit("tblpurchase", "fldstockid=&1", res25["fldbrandid"])
      If res27.Available Then
        For Each res27
          res27["fldstockid"] = xbrandid
          res27.Update
        Next
      Endif
      res28 = modDatabase.$myConn.Edit("tblpatdosing", "flditem=&1", res25["fldbrandid"])
      If res28.Available Then
        For Each res28
          res28["flditem"] = xbrandid
          res28.Update
        Next
      Endif
      res29 = modDatabase.$myConn.Edit("tbltransfer", "fldstockid=&1", res25["fldbrandid"])
      If res29.Available Then
        For Each res29
          res29["fldstockid"] = xbrandid
          res29.Update
        Next
      Endif
      res30 = modDatabase.$myConn.Edit("tblbulksale", "fldstockid=&1", res25["fldbrandid"])
      If res30.Available Then
        For Each res30
          res30["fldstockid"] = xbrandid
          res30.Update
        Next
      Endif
      res31 = modDatabase.$myConn.Edit("tbladjustment", "fldstockid=&1", res25["fldbrandid"])
      If res31.Available Then
        For Each res31
          res31["fldstockid"] = xbrandid
          res31.Update
        Next
      Endif
      res32 = modDatabase.$myConn.Edit("tblstockreturn", "fldstockid=&1", res25["fldbrandid"])
      If res32.Available Then
        For Each res32
          res32["fldstockid"] = xbrandid
          res32.Update
        Next
      Endif
      modDatabase.$myConn.Commit

      ''update main table
      res25["fldbrandid"] = xbrandid
      res25["fldbrand"] = sNewBrand
      Try res25.Update

    Endif
  Endif

Catch
  modDatabase.$myConn.Rollback
  modHelpVariable.CreateErrorReport()

End

''============ Surgical code ===========
Public Sub RecodeSurgicalCode(sOldName As String, sNewName As String, sType As String)

  Dim res1 As Result
  Dim res2 As Result
  Dim res3 As Result

  Dim res26 As Result
  Dim res27 As Result
  Dim res28 As Result
  Dim res29 As Result
  Dim res30 As Result
  Dim res31 As Result
  Dim res32 As Result

  Dim xdrug As String
  Dim xbrandid As String

  If sNewName And If sNewName <> sOldName Then

    modDatabase.$myConn.Begin

    res1 = modDatabase.$myConn.Edit("tblsurgicals", "fldsurgname=&1", sOldName)
    If res1.Available Then
      For Each res1
        If sType = "Suture" Then
          If Not res1["fldsurgtype"] And If Not res1["fldsurgcode"] Then
            xdrug = sNewName & " -" & res1["fldsurgsize"]
          Else
            xdrug = sNewName & " -" & res1["fldsurgsize"] & "(" & res1["fldsurgtype"] & "-" & res1["fldsurgcode"] & ")"
          Endif
        Else
          If res1["fldsurgtype"] Then
            xdrug = sNewName & " -" & res1["fldsurgsize"] & "(" & res1["fldsurgtype"] & ")"
          Else
            xdrug = sNewName & " -" & res1["fldsurgsize"]
          Endif
        Endif

        ''brand related
        res2 = modDatabase.$myConn.Edit("tblsurgbrand", "fldsurgid=&1", res1["fldsurgid"])
        If res2.Available Then
          For Each res2
            xbrandid = xdrug & " (" & res2["fldbrand"] & ")"

            ''update related tables
            res26 = modDatabase.$myConn.Edit("tblentry", "fldstockid=&1", res2["fldbrandid"])
            If res26.Available Then
              For Each res26
                res26["fldstockid"] = xbrandid
                res26.Update
              Next
            Endif
            res27 = modDatabase.$myConn.Edit("tblpurchase", "fldstockid=&1", res2["fldbrandid"])
            If res27.Available Then
              For Each res27
                res27["fldstockid"] = xbrandid
                res27.Update
              Next
            Endif
            res28 = modDatabase.$myConn.Edit("tblpatdosing", "flditem=&1", res2["fldbrandid"])
            If res28.Available Then
              For Each res28
                res28["flditem"] = xbrandid
                res28.Update
              Next
            Endif
            res29 = modDatabase.$myConn.Edit("tbltransfer", "fldstockid=&1", res2["fldbrandid"])
            If res29.Available Then
              For Each res29
                res29["fldstockid"] = xbrandid
                res29.Update
              Next
            Endif
            res30 = modDatabase.$myConn.Edit("tblbulksale", "fldstockid=&1", res2["fldbrandid"])
            If res30.Available Then
              For Each res30
                res30["fldstockid"] = xbrandid
                res30.Update
              Next
            Endif
            res31 = modDatabase.$myConn.Edit("tbladjustment", "fldstockid=&1", res2["fldbrandid"])
            If res31.Available Then
              For Each res31
                res31["fldstockid"] = xbrandid
                res31.Update
              Next
            Endif
            res32 = modDatabase.$myConn.Edit("tblstockreturn", "fldstockid=&1", res2["fldbrandid"])
            If res32.Available Then
              For Each res32
                res32["fldstockid"] = xbrandid
                res32.Update
              Next
            Endif
            ''update main table
            res2["fldbrandid"] = xbrandid
            res2["fldsurgid"] = xdrug
            res2.Update
          Next
        Endif

        ''code table
        res3 = modDatabase.$myConn.Edit("tblsurgicalname", "fldsurgname=&1", sOldName)
        If res3.Available Then
          For Each res3
            res3["fldsurgname"] = sNewName
            res3.Update
          Next
        Endif

        ''update main table
        res1["fldsurgid"] = xdrug
        res1["fldsurgname"] = sNewName
        res1.Update
      Next
    Endif

    modDatabase.$myConn.Commit

  Endif

Catch
  modDatabase.$myConn.Rollback
  modHelpVariable.CreateErrorReport()

End

Public Sub RecodeSurgicalStock(sOldName As String, sNewBrand As String)

  Dim res25 As Result
  Dim res26 As Result
  Dim res27 As Result
  Dim res28 As Result
  Dim res29 As Result
  Dim res30 As Result
  Dim res31 As Result
  Dim res32 As Result

  Dim xbrandid As String

  If sOldName Then
    res25 = modDatabase.$myConn.Edit("tblsurgbrand", "fldbrandid=&1", sOldName)
    If res25.Available Then

      xbrandid = res25["fldsurgid"] & " (" & sNewBrand & ")"
      modDatabase.$myConn.Begin
      ''update related tables
      res26 = modDatabase.$myConn.Edit("tblentry", "fldstockid=&1", res25["fldbrandid"])
      If res26.Available Then
        For Each res26
          res26["fldstockid"] = xbrandid
          res26.Update
        Next
      Endif
      res27 = modDatabase.$myConn.Edit("tblpurchase", "fldstockid=&1", res25["fldbrandid"])
      If res27.Available Then
        For Each res27
          res27["fldstockid"] = xbrandid
          res27.Update
        Next
      Endif
      res28 = modDatabase.$myConn.Edit("tblpatdosing", "flditem=&1", res25["fldbrandid"])
      If res28.Available Then
        For Each res28
          res28["flditem"] = xbrandid
          res28.Update
        Next
      Endif
      res29 = modDatabase.$myConn.Edit("tbltransfer", "fldstockid=&1", res25["fldbrandid"])
      If res29.Available Then
        For Each res29
          res29["fldstockid"] = xbrandid
          res29.Update
        Next
      Endif
      res30 = modDatabase.$myConn.Edit("tblbulksale", "fldstockid=&1", res25["fldbrandid"])
      If res30.Available Then
        For Each res30
          res30["fldstockid"] = xbrandid
          res30.Update
        Next
      Endif
      res31 = modDatabase.$myConn.Edit("tbladjustment", "fldstockid=&1", res25["fldbrandid"])
      If res31.Available Then
        For Each res31
          res31["fldstockid"] = xbrandid
          res31.Update
        Next
      Endif
      res32 = modDatabase.$myConn.Edit("tblstockreturn", "fldstockid=&1", res25["fldbrandid"])
      If res32.Available Then
        For Each res32
          res32["fldstockid"] = xbrandid
          res32.Update
        Next
      Endif
      modDatabase.$myConn.Commit

      ''update main table
      res25["fldbrandid"] = xbrandid
      res25["fldbrand"] = sNewBrand
      Try res25.Update

    Endif
  Endif

Catch
  modDatabase.$myConn.Rollback
  modHelpVariable.CreateErrorReport()

End

Public Sub RecodeSupplierName(sOldName As String, sNewCode As String)

  Dim res As Result
  Dim res1 As Result
  Dim res2 As Result
  Dim res3 As Result
  Dim res4 As Result
  Dim res5 As Result
  Dim res6 As Result
  Dim res7 As Result

  If sNewCode Then
    res = modDatabase.$myConn.Edit("tblsupplier", "fldsuppname=&1", sOldName)
    If res.Available Then

      modDatabase.$myConn.Begin
      ''fixed asset
      res1 = modDatabase.$myConn.Edit("tblassetsentry", "fldsuppname=&1", sOldName)
      If res1.Available Then
        For Each res1
          res1["fldsuppname"] = sNewCode
          res1.Update
        Next
      Endif

      ''purchase
      res2 = modDatabase.$myConn.Edit("tblpurchase", "fldsuppname=&1", sOldName)
      If res2.Available Then
        For Each res2
          res2["fldsuppname"] = sNewCode
          res2.Update
        Next
      Endif

      ''purchase bill
      res3 = modDatabase.$myConn.Edit("tblpurchasebill", "fldsuppname=&1", sOldName)
      If res3.Available Then
        For Each res3
          res3["fldsuppname"] = sNewCode
          res3.Update
        Next
      Endif

      ''stock returns
      res4 = modDatabase.$myConn.Edit("tblstockreturn", "fldsuppname=&1", sOldName)
      If res4.Available Then
        For Each res4
          res4["fldsuppname"] = sNewCode
          res4.Update
        Next
      Endif

      ''tender list
      res5 = modDatabase.$myConn.Edit("tbltenderlist", "fldsuppname=&1", sOldName)
      If res5.Available Then
        For Each res5
          res5["fldsuppname"] = sNewCode
          res5.Update
        Next
      Endif

      ''payment
      res6 = modDatabase.$myConn.Edit("tblpayment", "fldsuppname=&1", sOldName)
      If res6.Available Then
        For Each res6
          res6["fldsuppname"] = sNewCode
          res6.Update
        Next
      Endif

      ''purchase orderr
      res7 = modDatabase.$myConn.Edit("tblpurorder", "fldsuppname=&1", sOldName)
      If res7.Available Then
        For Each res7
          res7["fldsuppname"] = sNewCode
          res7.Update
        Next
      Endif

      res["fldsuppname"] = sNewCode
      res.Update
      modDatabase.$myConn.Commit

    Endif
  Endif

Catch
  modDatabase.$myConn.Rollback
  modHelpVariable.CreateErrorReport()

End
