' Gambas module file

Public Function InvoiceReportBillingRangeSummary(sFormat As String, $con As Connection, RepoForm As String, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim xparam As String
  Dim RepoPath As String
  Dim RepoVal As Float

  Dim cParam As CAccParam
  Dim cReport As CBillingAll
  Dim headLst As String[]
  Dim xhead As String
  Dim RepoLst As String[]

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("CATEGORY"), ("COUNT"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("Invoice Summary", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  ' RepoVal = modBillingAll.GetInvoiceReportBillingRangeSummary($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
  If RepoForm = "Summary" Then
    cParam = New CAccParam
    cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
    RepoVal = cReport.GetInvoiceReportBillingRangeSummary($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)

  Else If RepoForm = "Branch" Then
    RepoLst = New String[]
    headLst = modBasic.$AllBranchList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Branch", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      RepoVal = cReport.GetInvoiceReportBillingRangeSummary($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Else If RepoForm = "Location" Then
    RepoLst = New String[]
    headLst = modBasic.$AllCompList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Location", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      RepoVal = cReport.GetInvoiceReportBillingRangeSummary($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Endif

  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function InvoiceReportBillingRangeAccount(sFormat As String, $con As Connection, RepoForm As String, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim xparam As String
  Dim RepoPath As String
  Dim RepoVal As Float

  Dim cParam As CAccParam
  Dim cReport As CBillingAll
  Dim headLst As String[]
  Dim xhead As String
  Dim RepoLst As String[]

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("CATEGORY"), ("COUNT"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("Invoice Summary", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  ' RepoVal = modBillingAll.GetInvoiceReportBillingRangeAccount($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
  If RepoForm = "Summary" Then
    cParam = New CAccParam
    cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
    RepoVal = cReport.GetInvoiceReportBillingRangeAccount($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)

  Else If RepoForm = "Branch" Then
    RepoLst = New String[]
    headLst = modBasic.$AllBranchList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Branch", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      RepoVal = cReport.GetInvoiceReportBillingRangeAccount($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Else If RepoForm = "Location" Then
    RepoLst = New String[]
    headLst = modBasic.$AllCompList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Location", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      RepoVal = cReport.GetInvoiceReportBillingRangeAccount($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Endif

  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function InvoiceReportBillingRangeUserDetail(sFormat As String, $con As Connection, RepoForm As String, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim xparam As String
  Dim RepoPath As String
  Dim RepoVal As Float

  Dim cParam As CAccParam
  Dim cReport As CBillingAll
  Dim headLst As String[]
  Dim xhead As String
  Dim RepoLst As String[]

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("USER"), ("COUNT"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH"), ("DEPOSIT")], "", "")
  $BillingReport.UserData.Add("User Collection", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  ' RepoVal = modBillingAll.GetInvoiceReportBillingRangeUserDetail($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
  If RepoForm = "Summary" Then
    cParam = New CAccParam
    cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
    RepoVal = cReport.GetInvoiceReportBillingRangeUserDetail($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)

  Else If RepoForm = "Branch" Then
    RepoLst = New String[]
    headLst = modBasic.$AllBranchList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Branch", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      RepoVal = cReport.GetInvoiceReportBillingRangeUserDetail($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Else If RepoForm = "Location" Then
    RepoLst = New String[]
    headLst = modBasic.$AllCompList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Location", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      RepoVal = cReport.GetInvoiceReportBillingRangeUserDetail($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Endif

  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function InvoiceReportBillingRangeUserBrief(sFormat As String, $con As Connection, RepoForm As String, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim xparam As String
  Dim RepoPath As String
  Dim RepoVal As Float

  Dim cParam As CAccParam
  Dim cReport As CBillingAll
  Dim headLst As String[]
  Dim xhead As String
  Dim RepoLst As String[]

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("USER"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH"), ("DEPOSIT")], "", "")
  $BillingReport.UserData.Add("User Collection", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  ' RepoVal = modBillingAll.GetInvoiceReportBillingRangeUserBrief($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
  If RepoForm = "Summary" Then
    cParam = New CAccParam
    cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
    RepoVal = cReport.GetInvoiceReportBillingRangeUserBrief($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)

  Else If RepoForm = "Branch" Then
    RepoLst = New String[]
    headLst = modBasic.$AllBranchList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Branch", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      RepoVal = cReport.GetInvoiceReportBillingRangeUserBrief($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Else If RepoForm = "Location" Then
    RepoLst = New String[]
    headLst = modBasic.$AllCompList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Location", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      RepoVal = cReport.GetInvoiceReportBillingRangeUserBrief($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Endif

  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function InvoiceReportBillingRangeGroupDetail(sFormat As String, $con As Connection, RepoForm As String, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim xparam As String
  Dim RepoPath As String
  Dim RepoVal As Float

  Dim cParam As CAccParam
  Dim cReport As CBillingAll
  Dim headLst As String[]
  Dim xhead As String
  Dim RepoLst As String[]

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("CATEGORY"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("Group Collection", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  ' RepoVal = modBillingAll.GetInvoiceReportBillingRangeGroupDetail($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tblpatbilldetail)
  If RepoForm = "Summary" Then
    cParam = New CAccParam
    cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
    cReport.$UserGrp = cParam.GetUserID()
    cReport.$CompGrp = cParam.GetCompID()
    RepoVal = cReport.GetInvoiceReportBillingRangeGroupDetail($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tblpatbilldetail)

  Else If RepoForm = "Branch" Then
    RepoLst = New String[]
    headLst = modBasic.$AllBranchList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Branch", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      cReport.$UserGrp = cParam.GetUserID()
      cReport.$CompLst = cParam.GetCompList()
      RepoVal = cReport.GetInvoiceReportBillingRangeGroupDetail($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Else If RepoForm = "Location" Then
    RepoLst = New String[]
    headLst = modBasic.$AllCompList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Location", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      cReport.$UserGrp = cParam.GetUserID()
      cReport.$CompGrp = cParam.GetCompID()
      RepoVal = cReport.GetInvoiceReportBillingRangeGroupDetail($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Endif

  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function InvoiceReportBillingRangeGroupBrief(sFormat As String, $con As Connection, RepoForm As String, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim xparam As String
  Dim RepoPath As String
  Dim RepoVal As Float

  Dim cParam As CAccParam
  Dim cReport As CBillingAll
  Dim headLst As String[]
  Dim xhead As String
  Dim RepoLst As String[]

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("CATEGORY"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("Group Collection", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  ' RepoVal = modBillingAll.GetInvoiceReportBillingRangeGroupBrief($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tblpatbilldetail)
  If RepoForm = "Summary" Then
    cParam = New CAccParam
    cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
    cReport.$UserGrp = cParam.GetUserID()
    cReport.$CompGrp = cParam.GetCompID()
    RepoVal = cReport.GetInvoiceReportBillingRangeGroupBrief($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tblpatbilldetail)

  Else If RepoForm = "Branch" Then
    RepoLst = New String[]
    headLst = modBasic.$AllBranchList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Branch", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      cReport.$UserGrp = cParam.GetUserID()
      cReport.$CompLst = cParam.GetCompList()
      RepoVal = cReport.GetInvoiceReportBillingRangeGroupBrief($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Else If RepoForm = "Location" Then
    RepoLst = New String[]
    headLst = modBasic.$AllCompList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Location", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      cReport.$UserGrp = cParam.GetUserID()
      cReport.$CompGrp = cParam.GetCompID()
      RepoVal = cReport.GetInvoiceReportBillingRangeGroupBrief($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Endif

  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function InvoiceReportBillingRangeLocation(sFormat As String, $con As Connection, RepoForm As String, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim xparam As String
  Dim RepoPath As String
  Dim RepoVal As Float

  Dim cParam As CAccParam
  Dim cReport As CBillingAll
  Dim headLst As String[]
  Dim xhead As String
  Dim RepoLst As String[]

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("CATEGORY"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("Group Collection", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  ' RepoVal = modBillingAll.GetInvoiceReportBillingRangeLocation($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tblpatbilldetail)
  If RepoForm = "Summary" Then
    cParam = New CAccParam
    cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
    cReport.$UserGrp = cParam.GetUserID()
    cReport.$CompGrp = cParam.GetCompID()
    RepoVal = cReport.GetInvoiceReportBillingRangeLocation($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tblpatbilldetail)

  Else If RepoForm = "Branch" Then
    RepoLst = New String[]
    headLst = modBasic.$AllBranchList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Branch", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      cReport.$UserGrp = cParam.GetUserID()
      cReport.$CompLst = cParam.GetCompList()
      RepoVal = cReport.GetInvoiceReportBillingRangeLocation($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Else If RepoForm = "Location" Then
    RepoLst = New String[]
    headLst = modBasic.$AllCompList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Location", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      cReport.$UserGrp = cParam.GetUserID()
      cReport.$CompGrp = cParam.GetCompID()
      RepoVal = cReport.GetInvoiceReportBillingRangeLocation($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Endif

  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function InvoiceReportBillingRangeTaxDiscount(sFormat As String, $con As Connection, RepoForm As String, sType As String, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim xparam As String
  Dim RepoPath As String
  Dim RepoVal As Float

  Dim cParam As CAccParam
  Dim cReport As CBillingAll
  Dim headLst As String[]
  Dim xhead As String
  Dim RepoLst As String[]

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("DATE"), ("ENCID"), ("PATIENT"), ("TYPE"), ("INVOICE"), ("GROSS"), UCase(sType), ("LABEL"), ("ACCOUNT"), ("CASHIER")], "", "")
  $BillingReport.UserData.Add(sType & " Report", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  ' RepoVal = modBillingAll.GetInvoiceReportBillingRangeTaxDiscount($BillingReport, sFormat, $con, sType, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
  If RepoForm = "Summary" Then
    cParam = New CAccParam
    cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
    RepoVal = cReport.GetInvoiceReportBillingRangeTaxDiscount($BillingReport, sFormat, $con, sType, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)

  Else If RepoForm = "Branch" Then
    RepoLst = New String[]
    headLst = modBasic.$AllBranchList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Branch", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      RepoVal = cReport.GetInvoiceReportBillingRangeTaxDiscount($BillingReport, sFormat, $con, sType, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Else If RepoForm = "Location" Then
    RepoLst = New String[]
    headLst = modBasic.$AllCompList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Location", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      RepoVal = cReport.GetInvoiceReportBillingRangeTaxDiscount($BillingReport, sFormat, $con, sType, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Endif

  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function InvoiceReportBillingRangeCashCredit(sFormat As String, $con As Connection, RepoForm As String, sType As String, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim xparam As String
  Dim RepoPath As String
  Dim RepoVal As Float

  Dim cParam As CAccParam
  Dim cReport As CBillingAll
  Dim headLst As String[]
  Dim xhead As String
  Dim RepoLst As String[]

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  If sType = "Cash" Then
    $BillingReport = New CReportHTML([("DATE"), ("ENCID"), ("PATIENT"), ("TYPE"), ("INVOICE"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("NET"), ("RECEIVED"), ("QR-PAY"), ("HAND-CASH"), ("ACCOUNT")], "", "")
  Else
    $BillingReport = New CReportHTML([("DATE"), ("ENCID"), ("PATIENT"), ("TYPE"), ("INVOICE"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("NET"), ("RECEIVED"), ("ACCOUNT")], "", "")
  Endif
  $BillingReport.UserData.Add(sType & " Report", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  ' RepoVal = modBillingAll.GetInvoiceReportBillingRangeCashCredit($BillingReport, sFormat, $con, sType, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
  If RepoForm = "Summary" Then
    cParam = New CAccParam
    cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
    RepoVal = cReport.GetInvoiceReportBillingRangeCashCredit($BillingReport, sFormat, $con, sType, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)

  Else If RepoForm = "Branch" Then
    RepoLst = New String[]
    headLst = modBasic.$AllBranchList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Branch", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      RepoVal = cReport.GetInvoiceReportBillingRangeCashCredit($BillingReport, sFormat, $con, sType, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Else If RepoForm = "Location" Then
    RepoLst = New String[]
    headLst = modBasic.$AllCompList
    For Each xhead In headLst
      $BillingReport.AddChapter(xhead)
      cParam = New CAccParam("Location", xhead)
      cReport = New CBillingAll(cParam.GetExtraSQL(), cParam.GetFooterText())
      RepoVal = cReport.GetInvoiceReportBillingRangeCashCredit($BillingReport, sFormat, $con, sType, bill1, bill2, sLocaType, sLocation, $tblpatbilldetail)
      $BillingReport.AddChapter("<br>")
    Next

  Endif

  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function InvoiceReportGroupsSummarySpecial(sFormat As String, $con As Connection, bill1 As Variant, bill2 As Variant, xList As String[], sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim xparam As String
  Dim RepoPath As String
  Dim RepoVal As Float

  Dim cReport As CBillingAll

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("CATEGORY"), ("GROSS"), ("DISCOUNT"), ("TAX"), ("CREDIT"), ("CASH")], "", "")
  $BillingReport.UserData.Add("Group Collection : " & xList.Join(", "), "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  cReport = New CBillingAll("", "")
  RepoVal = cReport.GetInvoiceReportGroupsSummarySpecial($BillingReport, sFormat, $con, bill1, bill2, xList, sLocaType, sLocation, $tblpatbilling, $tblpatbilldetail)

  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End

Public Function InvoiceReportDetailByMismatch(sFormat As String, $con As Connection, bill1 As Variant, bill2 As Variant, sLocaType As String, sLocation As String, $tblpatbilling As String, $tblpatbilldetail As String) As String

  Dim $BillingReport As CReportHTML
  Dim xparam As String
  Dim RepoPath As String
  Dim RepoVal As Float

  Dim cReport As CBillingAll

  If sFormat = "Date" Then
    xparam = modReportVar.GetDateTimeReport(bill1, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(bill2, gb.GeneralDate)
  Else
    xparam = bill1 & " TO " & bill2
  Endif
  $BillingReport = New CReportHTML([("Invoice"), ("Type"), ("ItemTotal"), ("InvTotal"), ("TotDiff"), ("ItemTax"), ("InvTax"), ("TaxDiff"), ("ItemDisc"), ("InvDisc"), ("DiscDiff"), ("ItemCredit"), ("InvCredit"), ("CreditDiff"), ("ItemCash"), ("InvCash"), ("CashDiff")], "", "")
  $BillingReport.UserData.Add("Invoice Tax/Discount Mismatch", "PARAM1")
  $BillingReport.UserData.Add(xparam, "PARAM2")

  cReport = New CBillingAll("", "")
  RepoVal = cReport.GetInvoiceReportDetailByMismatch($BillingReport, sFormat, $con, bill1, bill2, sLocaType, sLocation, $tblpatbilling, $tblpatbilldetail)

  RepoPath = $BillingReport.NewHTMLPath()
  Return RepoPath

End
